### ISSUE TITLE
Problems detected in "kube-addon-manager":

### ISSUE THREAD

**Issue by danchirillo** [kubernetes/minikube#4046] opened 2019-04-03 14:01 UTC
Environment:  MacOS 10.14.4

minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to c
[minikubelog.log](https://github.com/kubernetes/minikube/files/3039026/minikubelog.log)
reate a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🔄  Relaunching Kubernetes v1.14.0 using kubeadm ...
⌛  Waiting for pods: apiserver

💣  Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to apply
    error: no objects passed to apply
    error: no objects passed to apply

**Comment by balopat** [comment] 2019-04-04 23:52
Closing as a dupe of #4045

**Closed by balopat** 2019-04-04 23:52 UTC
