### ISSUE TITLE
hyperv: create: creating: exit status 1

### ISSUE THREAD

**Issue by vsbpro** [kubernetes/minikube#5604] opened 2019-10-12 11:27 UTC
**The exact command to reproduce the issue**:
C:\WINDOWS\system32>minikube start

**The full output of the command that failed**:<details>

C:\WINDOWS\system32>minikube start
* minikube v1.4.0 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
*
X Unable to start VM: create: creating: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>minikube delete
* Failed to delete cluster: load: filestore "minikube": open C:\Users\visha\.minikube\machines\minikube\config.json: The system cannot find the file specified.
* You may need to manually remove the "minikube" VM from your hypervisor
* Removing C:\Users\visha\.minikube\machines\minikube ...
* The "minikube" cluster has been deleted.

C:\WINDOWS\system32>minikube start
* minikube v1.4.0 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Retriable failure: create: creating: exit status 1
* Deleting "minikube" in hyperv ...
*
X Unable to start VM: create: creating: exit status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

C:\WINDOWS\system32>minikube logs
*
X api load: filestore "minikube": open C:\Users\visha\.minikube\machines\minikube\config.json: The system cannot find the file specified.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

C:\WINDOWS\system32>dir C:\Users\visha\.minikube\machines\minikube\config.json
 Volume in drive C has no label.
 Volume Serial Number is BE2C-5AEE

 Directory of C:\Users\visha\.minikube\machines\minikube

File Not Found

C:\WINDOWS\system32>dir C:\Users\visha\.minikube\machines\minikube\
 Volume in drive C has no label.
 Volume Serial Number is BE2C-5AEE

 Directory of C:\Users\visha\.minikube\machines\minikube

12/10/2019  12:14    <DIR>          .
12/10/2019  12:14    <DIR>          ..
12/10/2019  12:13             1,675 id_rsa
12/10/2019  12:13               381 id_rsa.pub
               2 File(s)          2,056 bytes
               2 Dir(s)  310,824,669,184 bytes free

</details>

**The operating system version**:
Microsoft Windows 10 Pro

**Comment by tstromberg** [comment] 2019-10-30 18:27
Do you mind trying with minikube v1.5.x with the following arguments?

`minikube start --alsologtostderr -v=3`

We added some debugging that will help. My guess is that you may not have elevated permissions to be able to manage Hyper-V.

**Comment by brainfull** [comment] 2019-11-06 16:40
On my side, everytime I call 'minikube delete' I also delete automatically %userprofile%/.minikube. It resolves a lot of weird behavior and doesn't create unwanted side effect, at least for me.

**Comment by priyawadhwa** [comment] 2020-01-29 19:19
This issue appears to be a duplicate of #5580, do you mind if we move the conversation there?

This way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by priyawadhwa** 2020-01-29 19:19 UTC
Labels: triage/needs-information, triage/support
