### ISSUE TITLE
hyperkit mac: could not find an IP address for b2:a1....

### ISSUE THREAD

**Issue by chainhead** [kubernetes/minikube#8940] opened 2020-08-08 02:25 UTC
**Steps to reproduce the issue:** 

1. `minikube start --vm-driver hyperkit`

**Full output of failed command:** 

```bash
error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for b2:a1:b8:52:7:bb
```

This is the output (trimmed for brevity) of `sudo fs_usage -f network -w  2>&1 | egrep  'hyper|Sharing|launchd|socketfilter' | egrep -i 'bind|AF_INET'` command. Basically, `launchd` is not seen in the output.

```bash
07:48:22.095635  bind              F=3                                                                                                                                                                                        0.000005   docker-machine-driver-hyperkit.752195
07:48:23.017515  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000012   InternetSharing.718101
07:48:23.017740  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000010   InternetSharing.718101
07:48:23.017764  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000008   InternetSharing.718101
07:48:23.017775  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000006   InternetSharing.718101
07:48:23.017961  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000009   InternetSharing.718101
07:48:23.017994  socket            F=7        <AF_INET, SOCK_DGRAM, 0x0>                                                                                                                                                      0.000005   InternetSharing.718101
0
```

@tstromberg

**Comment by chainhead** [comment] 2020-08-20 14:10
Any update, work-around on this one, please ?

**Comment by priyawadhwa** [comment] 2020-09-08 17:35
Hey @chainhead sorry for the late response. This looks like a duplicate of https://github.com/kubernetes/minikube/issues/1926

Do you have a VPN enabled? If so, it seems like turning it off fixed it for other minikube users.

**Comment by chainhead** [comment] 2020-09-09 02:49
VPN is off.

```bash
minikube start --vm-driver hyperkit
😄  minikube v1.12.0 on Darwin 10.15.6
🎉  minikube 1.13.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.13.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for 2:12:7e:e6:f8:da
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. "minikube start" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for ea:38:81:be:56:50

💣  error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: could not find an IP address for ea:38:81:be:56:50

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by priyawadhwa** [comment] 2020-09-09 18:56
Hey @chainhead looks like this issue is a dupe of https://github.com/kubernetes/minikube/issues/4206 -- I'm going to close this issue so that we can centralize the conversation there.

I'd suggest commenting on that issue and also reading through it, there are a few different fixes suggested by other users.

If you think this issue is different, feel free to reopen at any time by commenting /reopen!

**Comment by chainhead** [comment] 2020-09-11 07:18
/reopen

Doesn't work.

That other post basically says to switch off VPN and use `docker-machine-driver-hyperkit` from Docker Desktop from Mac.

**Comment by medyagh** [comment] 2020-10-28 18:35
@chainhead sorry to hear you still hve this issue, our docker driver has better support for VPN envirinments, have you tried our docker driver ?

Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by medyagh** [comment] 2020-11-11 19:21
@chainhead I haven't heard from you, do you still have this issue ?

**Comment by chainhead** [comment] 2020-11-13 01:49
No, I gave up. I ended up using Virtual box as driver. Please close this.

**Closed** 2020-11-13 18:15 UTC
Labels: kind/support, triage/duplicate, triage/needs-information
