### ISSUE TITLE
Unable to start minikube with 0.25

### ISSUE THREAD

**Issue by VenkateshSrini** [kubernetes/minikube#2473] opened 2018-01-27 13:51 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):Bug

If this is a BUG REPORT, please:
  - Fill in as much of the template below as you can.  If you leave out
Trying to use the command 
**minikube.exe start --vm-driver="hyperv" --hyperv-virtual-switch="kubevirtualswitch"  --alsologtostderr**

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):v0.25.0
- **OS** (e.g. from /etc/os-release):Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**:
- **Others**:

**What happened**: I'm not getting minikube successuffly configured message

**What you expected to happen**: Minikube should work happily

**How to reproduce it** (as minimally and precisely as possible): run the command 
**minikube.exe start --vm-driver="hyperv" --hyperv-virtual-switch="kubevirtualswitch"  --alsologtostderr**

**Output of `minikube logs` (if applicable)**:
Getting an error

I0127 19:02:09.502759    2992 notify.go:109] Checking for updates...
I0127 19:02:10.458743    2992 cache_images.go:292] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.0 at C:\Users\Narasima\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.0
Starting local Kubernetes v1.9.0 cluster...
I0127 19:02:10.459706    2992 cache_images.go:292] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.1 at C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.8.1
Starting VM...
I0127 19:02:10.461930    2992 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.5 at C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.5
I0127 19:02:10.461930    2992 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.5 at C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 19:02:10.461930    2992 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.5 at C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.5
I0127 19:02:10.462921    2992 cache_images.go:292] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.5 at C:\Users\Narasima\.minikube\cache\images\gcr.io\google-containers\kube-addon-manager_v6.5
I0127 19:02:10.462921    2992 cache_images.go:292] Attempting to cache image: k8s.gcr.io/pause-amd64:3.0 at C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\pause-amd64_3.0
I0127 19:02:10.469056    2992 cluster.go:74] Skipping create...Using existing machine configuration
I0127 19:02:10.479456    2992 cache_images.go:79] Successfully cached all images.
I0127 19:02:11.292593    2992 cluster.go:83] Machine state:  Stopped
I0127 19:03:12.686618    2992 ssh_runner.go:57] Run: sudo rm -f /etc/docker/ca.pem
I0127 19:03:12.747173    2992 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
I0127 19:03:12.766875    2992 ssh_runner.go:57] Run: sudo rm -f /etc/docker/server.pem
I0127 19:03:12.782299    2992 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
I0127 19:03:12.800406    2992 ssh_runner.go:57] Run: sudo rm -f /etc/docker/server-key.pem
I0127 19:03:12.816641    2992 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
Getting VM IP address...
Moving files into cluster...
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.0
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.8.1
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.5
I0127 19:03:33.381331    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/kubernetes-dashboard-amd64_v1.8.1
I0127 19:03:33.381331    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-kube-dns-amd64_1.14.5
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\pause-amd64_3.0
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\gcr.io\google-containers\kube-addon-manager_v6.5
I0127 19:03:33.380331    2992 cache_images.go:194] Loading image from cache at  C:\Users\Narasima\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.5
I0127 19:03:33.380331    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/storage-provisioner_v1.8.0
I0127 19:03:33.381331    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 19:03:33.381331    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/pause-amd64_3.0
I0127 19:03:33.382334    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/kube-addon-manager_v6.5
I0127 19:03:33.382334    2992 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-sidecar-amd64_1.14.5
I0127 19:03:33.389446    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.403042    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.410834    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.416782    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.417989    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.424462    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.424826    2992 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 19:03:33.556115    2992 ssh_runner.go:57] Run: docker load -i \tmp\pause-amd64_3.0
I0127 19:03:33.594226    2992 kubernetes_versions.go:88] [{v1.9.0} {v1.8.0} {v1.7.5} {v1.7.4} {v1.7.3} {v1.7.2} {v1.7.0} {v1.7.0-rc.1} {v1.7.0-alpha.2} {v1.6.4} {v1.6.3} {v1.6.0} {v1.6.0-rc.1} {v1.6.0-beta.4} {v1.6.0-beta.3} {v1.6.0-beta.2} {v1.6.0-alpha.1} {v1.6.0-alpha.0} {v1.5.3} {v1.5.2} {v1.5.1} {v1.4.5} {v1.4.3} {v1.4.2} {v1.4.1} {v1.4.0} {v1.3.7} {v1.3.6} {v1.3.5} {v1.3.4} {v1.3.3} {v1.3.0}]
I0127 19:03:34.114485    2992 ssh_runner.go:57] Run: docker load -i \tmp\k8s-dns-sidecar-amd64_1.14.5
W0127 19:03:34.115487    2992 localkube_caching.go:70] Unable to check localkube checksum... continuing.
I0127 19:03:34.118484    2992 localkube_caching.go:144] Using cached localkube
E0127 19:03:34.119485    2992 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: C:\Users\Narasima\.minikube\cache\localkube\localkube-v1.9.0: open C:\Users\Narasima\.minikube\cache\localkube\localkube-v1.9.0: The system cannot find the file specified.
I0127 19:03:34.298745    2992 ssh_runner.go:57] Run: docker load -i \tmp\k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 19:03:34.416728    2992 ssh_runner.go:57] Run: docker load -i \tmp\k8s-dns-kube-dns-amd64_1.14.5
I0127 19:03:34.687785    2992 ssh_runner.go:57] Run: docker load -i \tmp\kube-addon-manager_v6.5
I0127 19:03:34.696834    2992 ssh_runner.go:57] Run: docker load -i \tmp\storage-provisioner_v1.8.0
I0127 19:03:34.899474    2992 ssh_runner.go:57] Run: docker load -i \tmp\kubernetes-dashboard-amd64_v1.8.1
**Anything else do we need to know**:

**Comment by afbjorklund** [comment] 2018-01-27 14:15
@VenkateshSrini : the reason for this is stated in #2472 - along with some workarounds you can use

**Comment by VenkateshSrini** [comment] 2018-01-27 14:29
I'm using windows 10. So what should I do

**Comment by afbjorklund** [comment] 2018-01-27 14:38
Use one of the following workarounds:
`minikube start --kubernetes-version=https://github.com/kubernetes/minikube/releases/download/v0.25.0/localkube`

`minikube start --kubernetes-version=v1.8.0`

`minikube start --bootstrapper kubeadm`

**Comment by VenkateshSrini** [comment] 2018-01-27 14:52
But this is not installing the dashboard UI. Earlier(V 24.1) this used to get installed with minikube

**Comment by VenkateshSrini** [comment] 2018-01-27 15:00
It is also having authentication issues. on the whole it is completely messed up. Since reverting to older version

**Comment by afbjorklund** [comment] 2018-01-27 15:04
Sounds like _different_ errors. Maybe similar to #2464 ?

**Comment by VenkateshSrini** [comment] 2018-01-27 15:07
Awaiting a stable  release. Can Minikube team let us know when we have a comprehensive version

**Comment by vorsprung** [comment] 2018-01-27 19:14
first workaround frrom @afbjorklund working on ubuntu 14.04..hurrah

**Comment by r2d4** [comment] 2018-01-27 19:53
Duplicate of #2472

**Closed by r2d4** 2018-01-27 19:53 UTC
