### ISSUE TITLE
VBoxManage.exe: The virtual machine 'minikube' has terminated unexpectedly with exit code 1 (0x1)

### ISSUE THREAD

**Issue by AGtechm** [kubernetes/minikube#3910] opened 2019-03-20 03:13 UTC
Failing with below error code. This also happens for the previous versions of both minikube and virtualbox. Tried to disable device guard but still the same issue.

Unable to start VM: start: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1).  More details may be available in 'C:\Users\Swati\.minikube\machines\minikube\minikube\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

**Comment by tstromberg** [comment] 2019-03-22 02:00
Could you attach the output of the log file it mentioned? VBoxHardening.log

- What happens if you run `minikube delete` followed by `minikube start`?

**Comment by AGtechm** [comment] 2019-03-22 13:44
Tried the delete followed by start. Same result. I attached the complete
logs.

**Comment by AGtechm** [comment] 2019-03-22 20:08
[VBoxHardening.log](https://github.com/kubernetes/minikube/files/2998118/VBoxHardening.log)

Logs attached

**Comment by tstromberg** [comment] 2019-03-22 22:02
Thanks! This seems to be the important part of why VirtualBox is failing:

```
23d8.47c4: Error -104 in supR3HardenedWinReSpawn! (enmWhat=5)
23d8.47c4: Error relaunching VirtualBox VM process: 5
```

I found a few related pages from non-minikube users about this issue, which makes it sound like some other installed software may be interfering with VirtualBox's ability to function properly.

- https://forums.virtualbox.org/viewtopic.php?f=25&t=82106
- https://forums.virtualbox.org/viewtopic.php?f=6&t=88357
- https://forums.virtualbox.org/viewtopic.php?f=6&t=91767

Looking at your log, I don't see any 3rd party software packages that are listed as "adversaries", but 
based on these pages, my advice is to try the following:

# Disable Trusteer Endpoint Protection (aka Rapport) if it is installed
# Disable any real-time antivirus
# Reinstall VirtualBox
# Reboot

Please let me know if this helps.

**Comment by tstromberg** [comment] 2019-05-02 23:31
Dupe of #3845

**Closed by tstromberg** 2019-05-02 23:31 UTC
Labels: co/virtualbox, os/windows, priority/awaiting-more-evidence, triage/needs-information

**Comment by luisrojas17** [comment] 2021-11-08 14:28
Nothing that you recommend works. I do not have any antivirus and I still have the same problem.

* Failed to start virtualbox VM. Running "minikube delete" may fix it: creating
host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualB
ox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedl
y during startup with exit code 1 (0x1).  More details may be available in 'C:\U
sers\BereniceRE\.minikube\machines\minikube\minikube\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
 interface IMachine

**Comment by peyafaguerre** [comment] 2023-09-29 10:59
I have the same problem in windows 10 when I launched vagrant up. 
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
 interface IMachine
Any help?

**Comment by nav2924** [comment] 2025-04-18 15:10
Try installing Virtualbox 6.1
