### ISSUE TITLE
unable to run minikube 

### ISSUE THREAD

**Issue by khavali** [kubernetes/minikube#14478] opened 2022-06-30 06:58 UTC
### What Happened?

Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.

### Attach the log file

Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.

### Operating System

Ubuntu

### Driver

Docker

**Comment by gkwan-ibm** [comment] 2022-06-30 14:41
We encountered the same problem.

**Comment by spowelljr** [comment] 2022-06-30 20:34
Hi @khavali, thanks for reporting your issue with minikube.

I'm going to assume you created your currently cluster with minikube v1.25.2 or previous and now you're trying to start the cluster with minikube v1.26.0 binary.

The problem is clusters previous to v1.26.0 used Dockershim, but now it uses cri-docker, and because the cluster was created previously is doesn't have cri-docker installed.

To resolve your issue run `minikube delete` to clear out the existing cluster and then try starting minikube again and that should resolve you error, thanks

**Comment by spowelljr** [comment] 2022-06-30 22:07
@khavali & @gkwan-ibm double checking, are both of you using the `docker` driver? Or are you perhaps using the `none` driver?

**Comment by gkwan-ibm** [comment] 2022-06-30 22:09
I used `none` and ran under github action

**Comment by spowelljr** [comment] 2022-06-30 22:43
Ah, @gkwan-ibm, your problem is you need to install `cri-docker` on your machine if you want to use the combination of `none` driver, `docker` container runtime, and Kubernetes v1.24 and greater.

For more details see https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503

Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.

**Closed by spowelljr** 2022-06-30 22:43 UTC
Labels: kind/support, co/runtime/docker

**Comment by khavali** [comment] 2022-07-01 05:48
> 

none driver

**Comment by spowelljr** [comment] 2022-07-01 16:08
Then you'd also follow the comment above, you just need to install `cri-docker` onto your machine.
