### ISSUE TITLE
Не сатртует minikube

### ISSUE THREAD

**Issue by tjkstudent** [kubernetes/minikube#19981] opened 2024-11-20 15:52 UTC
### Что произошло?

Просто запускаю каждый раз такая проблема. пробовал переустановить 
Удалить .minikube папку и .kube 
Ничего не помогает

### Приложите логи

==> Audit <==
|----------------|-----------------|----------|------------------------|---------|---------------------|---------------------|
|    Command     |      Args       | Profile  |          User          | Version |     Start Time      |      End Time       |
|----------------|-----------------|----------|------------------------|---------|---------------------|---------------------|
| update-check   |                 | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:41 MSK | 20 Nov 24 18:41 MSK |
| start          | --driver=docker | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:42 MSK |                     |
| update-context |                 | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:44 MSK | 20 Nov 24 18:44 MSK |
| update-context |                 | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:45 MSK | 20 Nov 24 18:45 MSK |
| start          |                 | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:45 MSK |                     |
| ssh            |                 | minikube | PCDESKTOP\DESKTOP-HOME | v1.34.0 | 20 Nov 24 18:47 MSK | 20 Nov 24 18:47 MSK |
|----------------|-----------------|----------|------------------------|---------|---------------------|---------------------|

==> Last Start <==
Log file created at: 2024/11/20 18:45:17
Running on machine: PCDESKTOP
Binary: Built with gc go1.22.5 for windows/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1120 18:45:17.237035   24072 out.go:345] Setting OutFile to fd 100 ...
I1120 18:45:17.250693   24072 out.go:397] isatty.IsTerminal(100) = true
I1120 18:45:17.250693   24072 out.go:358] Setting ErrFile to fd 104...
I1120 18:45:17.250693   24072 out.go:397] isatty.IsTerminal(104) = true
W1120 18:45:17.261213   24072 root.go:314] Error reading config file at C:\Users\DESKTOP-HOME\.minikube\config\config.json: open C:\Users\DESKTOP-HOME\.minikube\config\config.json: The system cannot find the file specified.
I1120 18:45:17.264394   24072 out.go:352] Setting JSON to false
I1120 18:45:17.268015   24072 start.go:129] hostinfo: {"hostname":"PCDESKTOP","uptime":23026,"bootTime":1732094490,"procs":275,"os":"windows","platform":"Microsoft Windows 11 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.22631.4460 Build 22631.4460","kernelVersion":"10.0.22631.4460 Build 22631.4460","kernelArch":"x86_64","virtualizationSystem":"","virtualizationRole":"","hostId":"3f566424-7952-4d8b-862c-3c39b2093245"}
W1120 18:45:17.268015   24072 start.go:137] gopshost.Virtualization returned error: not implemented yet
I1120 18:45:17.268537   24072 out.go:177] 😄  minikube v1.34.0 на Microsoft Windows 11 Pro 10.0.22631.4460 Build 22631.4460
I1120 18:45:17.269060   24072 notify.go:220] Checking for updates...
I1120 18:45:17.269578   24072 config.go:182] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.31.0
I1120 18:45:17.269578   24072 driver.go:394] Setting default libvirt URI to qemu:///system
I1120 18:45:17.333181   24072 docker.go:123] docker version: linux-27.2.0:Docker Desktop 4.34.0 (165256)
I1120 18:45:17.337330   24072 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1120 18:45:17.852685   24072 info.go:266] docker info: {ID:f68cd0fd-3eb8-4280-8cac-e2c28fd7e605 Containers:8 ContainersRunning:1 ContainersPaused:0 ContainersStopped:7 Images:9 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Using metacopy false] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:67 OomKillDisable:false NGoroutines:91 SystemTime:2024-11-20 15:45:17.754073595 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:17 KernelVersion:5.15.167.4-microsoft-standard-WSL2 OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:5 MemTotal:6218743808 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[com.docker.desktop.address=npipe://\\.\pipe\docker_cli] ExperimentalBuild:false ServerVersion:27.2.0 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:8fc6bcff51318944179630522a095cc9dbf9f353 Expected:8fc6bcff51318944179630522a095cc9dbf9f353} RuncCommit:{ID:v1.1.13-0-g58aa920 Expected:v1.1.13-0-g58aa920} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=unconfined name=cgroupns] ProductLicense: Warnings:[WARNING: daemon is not using the default seccomp profile] ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:C:\Program Files\Docker\cli-plugins\docker-buildx.exe SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.16.2-desktop.1] map[Name:compose Path:C:\Program Files\Docker\cli-plugins\docker-compose.exe SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.29.2-desktop.2] map[Name:debug Path:C:\Program Files\Docker\cli-plugins\docker-debug.exe SchemaVersion:0.1.0 ShortDescription:Get a shell into any image or container Vendor:Docker Inc. Version:0.0.34] map[Name:desktop Path:C:\Program Files\Docker\cli-plugins\docker-desktop.exe SchemaVersion:0.1.0 ShortDescription:Docker Desktop commands (Alpha) Vendor:Docker Inc. Version:v0.0.15] map[Name:dev Path:C:\Program Files\Docker\cli-plugins\docker-dev.exe SchemaVersion:0.1.0 ShortDescription:Docker Dev Environments Vendor:Docker Inc. Version:v0.1.2] map[Name:extension Path:C:\Program Files\Docker\cli-plugins\docker-extension.exe SchemaVersion:0.1.0 ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.25] map[Name:feedback Path:C:\Program Files\Docker\cli-plugins\docker-feedback.exe SchemaVersion:0.1.0 ShortDescription:Provide feedback, right in your terminal! Vendor:Docker Inc. Version:v1.0.5] map[Name:init Path:C:\Program Files\Docker\cli-plugins\docker-init.exe SchemaVersion:0.1.0 ShortDescription:Creates Docker-related starter files for your project Vendor:Docker Inc. Version:v1.3.0] map[Name:sbom Path:C:\Program Files\Docker\cli-plugins\docker-sbom.exe SchemaVersion:0.1.0 ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scout Path:C:\Program Files\Docker\cli-plugins\docker-scout.exe SchemaVersion:0.1.0 ShortDescription:Docker Scout Vendor:Docker Inc. Version:v1.13.0]] Warnings:<nil>}}
I1120 18:45:17.853195   24072 out.go:177] ✨  Используется драйвер docker на основе существующего профиля
I1120 18:45:17.853195   24072 start.go:297] selected driver: docker
I1120 18:45:17.853195   24072 start.go:901] validating driver "docker" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 Memory:4000 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:8443 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.31.0 ClusterName:minikube Namespace:default APIServerHAVIP: APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.31.0 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:C:\Users\DESKTOP-HOME:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0 GPUs: AutoPauseInterval:1m0s}
I1120 18:45:17.853195   24072 start.go:912] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I1120 18:45:17.861981   24072 cli_runner.go:164] Run: docker system info --format "{{json .}}"
I1120 18:45:18.116124   24072 info.go:266] docker info: {ID:f68cd0fd-3eb8-4280-8cac-e2c28fd7e605 Containers:8 ContainersRunning:1 ContainersPaused:0 ContainersStopped:7 Images:9 Driver:overlay2 DriverStatus:[[Backing Filesystem extfs] [Supports d_type true] [Using metacopy false] [Native Overlay Diff true] [userxattr false]] SystemStatus:<nil> Plugins:{Volume:[local] Network:[bridge host ipvlan macvlan null overlay] Authorization:<nil> Log:[awslogs fluentd gcplogs gelf journald json-file local splunk syslog]} MemoryLimit:true SwapLimit:true KernelMemory:false KernelMemoryTCP:false CPUCfsPeriod:true CPUCfsQuota:true CPUShares:true CPUSet:true PidsLimit:true IPv4Forwarding:true BridgeNfIptables:true BridgeNfIP6Tables:true Debug:false NFd:66 OomKillDisable:false NGoroutines:89 SystemTime:2024-11-20 15:45:18.011199866 +0000 UTC LoggingDriver:json-file CgroupDriver:cgroupfs NEventsListener:16 KernelVersion:5.15.167.4-microsoft-standard-WSL2 OperatingSystem:Docker Desktop OSType:linux Architecture:x86_64 IndexServerAddress:https://index.docker.io/v1/ RegistryConfig:{AllowNondistributableArtifactsCIDRs:[] AllowNondistributableArtifactsHostnames:[] InsecureRegistryCIDRs:[127.0.0.0/8] IndexConfigs:{DockerIo:{Name:docker.io Mirrors:[] Secure:true Official:true}} Mirrors:[]} NCPU:5 MemTotal:6218743808 GenericResources:<nil> DockerRootDir:/var/lib/docker HTTPProxy:http.docker.internal:3128 HTTPSProxy:http.docker.internal:3128 NoProxy:hubproxy.docker.internal Name:docker-desktop Labels:[com.docker.desktop.address=npipe://\\.\pipe\docker_cli] ExperimentalBuild:false ServerVersion:27.2.0 ClusterStore: ClusterAdvertise: Runtimes:{Runc:{Path:runc}} DefaultRuntime:runc Swarm:{NodeID: NodeAddr: LocalNodeState:inactive ControlAvailable:false Error: RemoteManagers:<nil>} LiveRestoreEnabled:false Isolation: InitBinary:docker-init ContainerdCommit:{ID:8fc6bcff51318944179630522a095cc9dbf9f353 Expected:8fc6bcff51318944179630522a095cc9dbf9f353} RuncCommit:{ID:v1.1.13-0-g58aa920 Expected:v1.1.13-0-g58aa920} InitCommit:{ID:de40ad0 Expected:de40ad0} SecurityOptions:[name=seccomp,profile=unconfined name=cgroupns] ProductLicense: Warnings:[WARNING: daemon is not using the default seccomp profile] ServerErrors:[] ClientInfo:{Debug:false Plugins:[map[Name:buildx Path:C:\Program Files\Docker\cli-plugins\docker-buildx.exe SchemaVersion:0.1.0 ShortDescription:Docker Buildx Vendor:Docker Inc. Version:v0.16.2-desktop.1] map[Name:compose Path:C:\Program Files\Docker\cli-plugins\docker-compose.exe SchemaVersion:0.1.0 ShortDescription:Docker Compose Vendor:Docker Inc. Version:v2.29.2-desktop.2] map[Name:debug Path:C:\Program Files\Docker\cli-plugins\docker-debug.exe SchemaVersion:0.1.0 ShortDescription:Get a shell into any image or container Vendor:Docker Inc. Version:0.0.34] map[Name:desktop Path:C:\Program Files\Docker\cli-plugins\docker-desktop.exe SchemaVersion:0.1.0 ShortDescription:Docker Desktop commands (Alpha) Vendor:Docker Inc. Version:v0.0.15] map[Name:dev Path:C:\Program Files\Docker\cli-plugins\docker-dev.exe SchemaVersion:0.1.0 ShortDescription:Docker Dev Environments Vendor:Docker Inc. Version:v0.1.2] map[Name:extension Path:C:\Program Files\Docker\cli-plugins\docker-extension.exe SchemaVersion:0.1.0 ShortDescription:Manages Docker extensions Vendor:Docker Inc. Version:v0.2.25] map[Name:feedback Path:C:\Program Files\Docker\cli-plugins\docker-feedback.exe SchemaVersion:0.1.0 ShortDescription:Provide feedback, right in your terminal! Vendor:Docker Inc. Version:v1.0.5] map[Name:init Path:C:\Program Files\Docker\cli-plugins\docker-init.exe SchemaVersion:0.1.0 ShortDescription:Creates Docker-related starter files for your project Vendor:Docker Inc. Version:v1.3.0] map[Name:sbom Path:C:\Program Files\Docker\cli-plugins\docker-sbom.exe SchemaVersion:0.1.0 ShortDescription:View the packaged-based Software Bill Of Materials (SBOM) for an image URL:https://github.com/docker/sbom-cli-plugin Vendor:Anchore Inc. Version:0.6.0] map[Name:scout Path:C:\Program Files\Docker\cli-plugins\docker-scout.exe SchemaVersion:0.1.0 ShortDescription:Docker Scout Vendor:Docker Inc. Version:v1.13.0]] Warnings:<nil>}}
I1120 18:45:18.138746   24072 cni.go:84] Creating CNI manager for ""
I1120 18:45:18.138746   24072 cni.go:158] "docker" driver + "docker" container runtime found on kubernetes v1.24+, recommending bridge
I1120 18:45:18.138746   24072 start.go:340] cluster config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 Memory:4000 CPUs:2 DiskSize:20000 Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:8443 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.31.0 ClusterName:minikube Namespace:default APIServerHAVIP: APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin:cni FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.31.0 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:C:\Users\DESKTOP-HOME:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath: SocketVMnetClientPath: SocketVMnetPath: StaticIP: SSHAuthSock: SSHAgentPID:0 GPUs: AutoPauseInterval:1m0s}
I1120 18:45:18.139262   24072 out.go:177] 👍  Starting "minikube" primary control-plane node in "minikube" cluster
I1120 18:45:18.139262   24072 cache.go:121] Beginning downloading kic base image for docker with docker
I1120 18:45:18.139781   24072 out.go:177] 🚜  Pulling base image v0.0.45 ...
I1120 18:45:18.139781   24072 preload.go:131] Checking if preload exists for k8s version v1.31.0 and runtime docker
I1120 18:45:18.139781   24072 image.go:79] Checking for gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 in local docker daemon
I1120 18:45:18.139781   24072 preload.go:146] Found local preload: C:\Users\DESKTOP-HOME\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v18-v1.31.0-docker-overlay2-amd64.tar.lz4
I1120 18:45:18.139781   24072 cache.go:56] Caching tarball of preloaded images
I1120 18:45:18.139781   24072 preload.go:172] Found C:\Users\DESKTOP-HOME\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v18-v1.31.0-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1120 18:45:18.140297   24072 cache.go:59] Finished verifying existence of preloaded tar for v1.31.0 on docker
I1120 18:45:18.140297   24072 profile.go:143] Saving config to C:\Users\DESKTOP-HOME\.minikube\profiles\minikube\config.json ...
W1120 18:45:18.234731   24072 image.go:95] image gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 is of wrong architecture
I1120 18:45:18.234731   24072 cache.go:149] Downloading gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 to local cache
I1120 18:45:18.235248   24072 localpath.go:151] windows sanitize: C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar -> C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase_v0.0.45@sha256_81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar
I1120 18:45:18.235248   24072 localpath.go:151] windows sanitize: C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar -> C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase_v0.0.45@sha256_81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar
I1120 18:45:18.235248   24072 image.go:63] Checking for gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 in local cache directory
I1120 18:45:18.235248   24072 image.go:66] Found gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 in local cache directory, skipping pull
I1120 18:45:18.235248   24072 image.go:135] gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 exists in cache, skipping pull
I1120 18:45:18.235248   24072 cache.go:152] successfully saved gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 as a tarball
I1120 18:45:18.235248   24072 cache.go:162] Loading gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 from local cache
I1120 18:45:18.235248   24072 localpath.go:151] windows sanitize: C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar -> C:\Users\DESKTOP-HOME\.minikube\cache\kic\amd64\kicbase_v0.0.45@sha256_81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85.tar
I1120 18:45:18.740761   24072 cache.go:164] successfully loaded and using gcr.io/k8s-minikube/kicbase:v0.0.45@sha256:81df288595202a317b1a4dc2506ca2e4ed5f22373c19a441b88cfbf4b9867c85 from cached tarball
I1120 18:45:18.740761   24072 cache.go:194] Successfully downloaded all kic artifacts
I1120 18:45:18.740761   24072 start.go:360] acquireMachinesLock for minikube: {Name:mk9688250fa726aff3f1c771a6501f285c8dedc9 Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1120 18:45:18.740761   24072 start.go:364] duration metric: took 0s to acquireMachinesLock for "minikube"
I1120 18:45:18.740761   24072 start.go:96] Skipping create...Using existing machine configuration
I1120 18:45:18.740761   24072 fix.go:54] fixHost starting: 
I1120 18:45:18.750074   24072 cli_runner.go:164] Run: docker container inspect minikube --format={{.State.Status}}
I1120 18:45:18.839121   24072 fix.go:112] recreateIfNeeded on minikube: state=Running err=<nil>
W1120 18:45:18.839121   24072 fix.go:138] unexpected machine state, will restart: <nil>
I1120 18:45:18.839639   24072 out.go:177] 🏃  Обновляется работающий docker "minikube" container ...
I1120 18:45:18.839639   24072 machine.go:93] provisionDockerMachine start ...
I1120 18:45:18.844316   24072 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1120 18:45:18.932441   24072 main.go:141] libmachine: Using SSH client type: native
I1120 18:45:18.932955   24072 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0xb4c9c0] 0xb4f5a0 <nil>  [] 0s} 127.0.0.1 58851 <nil> <nil>}
I1120 18:45:18.932955   24072 main.go:141] libmachine: About to run SSH command:
hostname
I1120 18:45:19.051201   24072 main.go:141] libmachine: SSH cmd err, output: <nil>: minikube

I1120 18:45:19.051201   24072 ubuntu.go:169] provisioning hostname "minikube"
I1120 18:45:19.055686   24072 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1120 18:45:19.141822   24072 main.go:141] libmachine: Using SSH client type: native
I1120 18:45:19.142342   24072 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0xb4c9c0] 0xb4f5a0 <nil>  [] 0s} 127.0.0.1 58851 <nil> <nil>}
I1120 18:45:19.142342   24072 main.go:141] libmachine: About to run SSH command:
sudo hostname minikube && echo "minikube" | sudo tee /etc/hostname
I1120 18:45:19.269835   24072 main.go:141] libmachine: SSH cmd err, output: <nil>: minikube

I1120 18:45:19.275106   24072 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1120 18:45:19.362501   24072 main.go:141] libmachine: Using SSH client type: native
I1120 18:45:19.363016   24072 main.go:141] libmachine: &{{{<nil> 0 [] [] []} docker [0xb4c9c0] 0xb4f5a0 <nil>  [] 0s} 127.0.0.1 58851 <nil> <nil>}
I1120 18:45:19.363016   24072 main.go:141] libmachine: About to run SSH command:

		if ! grep -xq '.*\sminikube' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 minikube/g' /etc/hosts;
			else 
				echo '127.0.1.1 minikube' | sudo tee -a /etc/hosts; 
			fi
		fi
I1120 18:45:19.483774   24072 main.go:141] libmachine: SSH cmd err, output: <nil>: 
I1120 18:45:19.483774   24072 ubuntu.go:175] set auth options {CertDir:C:\Users\DESKTOP-HOME\.minikube CaCertPath:C:\Users\DESKTOP-HOME\.minikube\certs\ca.pem CaPrivateKeyPath:C:\Users\DESKTOP-HOME\.minikube\certs\ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:C:\Users\DESKTOP-HOME\.minikube\machines\server.pem ServerKeyPath:C:\Users\DESKTOP-HOME\.minikube\machines\server-key.pem ClientKeyPath:C:\Users\DESKTOP-HOME\.minikube\certs\key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:C:\Users\DESKTOP-HOME\.minikube\certs\cert.pem ServerCertSANs:[] StorePath:C:\Users\DESKTOP-HOME\.minikube}
I1120 18:45:19.483774   24072 ubuntu.go:177] setting up certificates
I1120 18:45:19.483774   24072 provision.go:84] configureAuth start
I1120 18:45:19.489437   24072 cli_runner.go:164] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I1120 18:45:19.575748   24072 provision.go:143] copyHostCerts
I1120 18:45:19.575748   24072 exec_runner.go:144] found C:\Users\DESKTOP-HOME\.minikube/ca.pem, removing ...
I1120 18:45:19.575748   24072 exec_runner.go:203] rm: C:\Users\DESKTOP-HOME\.minikube\ca.pem
I1120 18:45:19.576265   24072 exec_runner.go:151] cp: C:\Users\DESKTOP-HOME\.minikube\certs\ca.pem --> C:\Users\DESKTOP-HOME\.minikube/ca.pem (1094 bytes)
I1120 18:45:19.576785   24072 exec_runner.go:144] found C:\Users\DESKTOP-HOME\.minikube/cert.pem, removing ...
I1120 18:45:19.576785   24072 exec_runner.go:203] rm: C:\Users\DESKTOP-HOME\.minikube\cert.pem
I1120 18:45:19.577298   24072 exec_runner.go:151] cp: C:\Users\DESKTOP-HOME\.minikube\certs\cert.pem --> C:\Users\DESKTOP-HOME\.minikube/cert.pem (1135 bytes)
I1120 18:45:19.577832   24072 exec_runner.go:144] found C:\Users\DESKTOP-HOME\.minikube/key.pem, removing ...
I1120 18:45:19.577832   24072 exec_runner.go:203] rm: C:\Users\DESKTOP-HOME\.minikube\key.pem
I1120 18:45:19.577832   24072 exec_runner.go:151] cp: C:\Users\DESKTOP-HOME\.minikube\certs\key.pem --> C:\Users\DESKTOP-HOME\.minikube/key.pem (1675 bytes)
I1120 18:45:19.578353   24072 provision.go:117] generating server cert: C:\Users\DESKTOP-HOME\.minikube\machines\server.pem ca-key=C:\Users\DESKTOP-HOME\.minikube\certs\ca.pem private-key=C:\Users\DESKTOP-HOME\.minikube\certs\ca-key.pem org=DESKTOP-HOME.minikube san=[127.0.0.1 192.168.58.2 localhost minikube]
I1120 18:45:19.623373   24072 provision.go:177] copyRemoteCerts
I1120 18:45:19.634732   24072 ssh_runner.go:195] Run: sudo mkdir -p /etc/docker /etc/docker /etc/docker
I1120 18:45:19.638916   24072 cli_runner.go:164] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1120 18:45:19.721651   24072 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:58851 SSHKeyPath:C:\Users\DESKTOP-HOME\.minikube\machines\minikube\id_rsa Username:docker}
I1120 18:45:19.809032   24072 ssh_runner.go:362] scp C:\Users\DESKTOP-HOME\.minikube\machines\server-key.pem --> /etc/docker/server-key.pem (1675 bytes)
I1120 18:45:38.781820   24072 provision.go:87] duration metric: took 19.2980467s to configureAuth
W1120 18:45:38.781820   24072 ubuntu.go:180] configureAuth failed: transferring file to machine &{{C:\Users\DESKTOP-HOME\.minikube\machines\server-key.pem /etc/docker server-key.pem 0640 } 0xc001923230 <nil> 0xc000094d20}: sudo mkdir -p /etc/docker && sudo scp -t /etc/docker && sudo touch -d "2024-11-20 18:45:19.6233735 +0300" /etc/docker/server-key.pem: wait: remote command exited without exit status or exit signal
output: 

### Операционная система

Windows

### Драйвер

Docker
```[tasklist]
### Tasks
- [ ] https://github.com/kubernetes/minikube/issues/19309
- [ ] https://github.com/kubernetes/minikube/issues/19964
```

**Comment by T-Lakshmi** [comment] 2024-11-21 10:23
@tjkstudent,
Can you please update the issue title and description in english(primary language), so that people can easily understand the issue and respond.

/triage needs-information

**Comment by tjkstudent** [comment] 2024-11-21 10:47
> @tjkstudent,
> Can you please update the issue title and description in english(primary language), so that people can easily understand the issue and respond.
> 
> /triage needs-information

Thank you, a have already solved this. Problem was . wslconfig 
I have bit changes on this file, restore to defaults it helps

**Comment by T-Lakshmi** [comment] 2024-11-21 10:55
@tjkstudent,
Thats great. 
If the issue is already resolved, please close it.

**Closed** 2024-11-21 11:09 UTC
Labels: kind/support, triage/needs-information
