### ISSUE TITLE
Docker driver minikube cannot be created after enabling ingress addon

### ISSUE THREAD

**Issue by AndreyIvshin** [kubernetes/minikube#10151] opened 2021-01-15 15:45 UTC
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
1. I used minikube with Docker driver.
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

$ minikube addons enable ingress
* After the addon is enabled, please run "minikube tunnel" and your ingress resources would be available at "127.0.0.1"
* Verifying ingress addon...
* The 'ingress' addon is enabled

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
2. I didn't run "minikube tunnel", tried to play with ingress and then stopped minikibe. After start:
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

$ minikube start
* minikube v1.16.0 on Microsoft Windows 10 Home Single Language 10.0.19041 Build 19041
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing docker container for "minikube" ...
! StartHost failed, but will try again: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

* Restarting existing docker container for "minikube" ...
* Failed to start docker container. Running "minikube delete" may fix it: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minik
ube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

E0115 20:58:44.033016     816 out.go:322] unable to execute Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}
'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil
: html/template:Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil
: "\"" in attribute name: "\"22/tcp\") 0>: error calling inde" - returning raw string.

X Exiting due to GUEST_PROVISION: Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1

stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
3. Tried to recreate minikube, but it no longer able to create it using Docker driver
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

$ minikube delete
* Deleting "minikube" in docker ...
* Deleting container "minikube" ...
* Removing C:\Users\graog\.minikube\machines\minikube ...
* Removed all traces of the "minikube" cluster.

$ minikube start
* Automatically selected the docker driver
* Starting control plane node minikube in cluster minikube
* Creating docker container (CPUs=2, Memory=1993MB) ...
! Listening to 0.0.0.0 on external docker host 192.168.99.100. Please be advised
! StartHost failed, but will try again: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.
0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.

* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=1993MB) ...
! Listening to 0.0.0.0 on external docker host 192.168.99.100. Please be advised
* Failed to start docker container. Running "minikube delete" may fix it: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v m
inikube:/var gcr.io/k8s-minikube/kicbase:v0.0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.

! Startup with docker driver failed, trying with alternate driver virtualbox: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --ent
rypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.

* Deleting "minikube" in docker ...
* Removing C:\Users\graog\.minikube\machines\minikube ...
! Failed to delete cluster minikube, proceeding with retry anyway.
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
* Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
  - env NO_PROXY=192.168.99.100
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
4 Even after removing its image from Docker
<><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>

$ minikube start
* minikube v1.16.0 on Microsoft Windows 10 Home Single Language 10.0.19041 Build 19041
* Automatically selected the docker driver
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
* Creating docker container (CPUs=2, Memory=1993MB) ...
! Listening to 0.0.0.0 on external docker host 192.168.99.100. Please be advised
! StartHost failed, but will try again: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.
0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
Unable to find image 'gcr.io/k8s-minikube/kicbase:v0.0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16' locally
sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16: Pulling from k8s-minikube/kicbase
Digest: sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16
Status: Downloaded newer image for gcr.io/k8s-minikube/kicbase@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.
time="2021-01-15T21:39:37+06:00" level=error msg="error waiting for container: context canceled"

* docker "minikube" container is missing, will recreate.
* Creating docker container (CPUs=2, Memory=1993MB) ...
! Listening to 0.0.0.0 on external docker host 192.168.99.100. Please be advised
* Failed to start docker container. Running "minikube delete" may fix it: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --entrypoint /usr/bin/test -v m
inikube:/var gcr.io/k8s-minikube/kicbase:v0.0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.

! Startup with docker driver failed, trying with alternate driver virtualbox: Failed to start host: recreate: creating host: create: creating: setting up container node: preparing volume for minikube container: docker run --rm --ent
rypoint /usr/bin/test -v minikube:/var gcr.io/k8s-minikube/kicbase:v0.0.15-snapshot4@sha256:ef1f485b5a1cfa4c989bc05e153f0a8525968ec999e242efff871cbb31649c16 -d /var/lib: exit status 125
stdout:

stderr:
docker: Error response from daemon: cgroups: cannot find cgroup mount destination: unknown.

* Deleting "minikube" in docker ...
* Removing C:\Users\graog\.minikube\machines\minikube ...
! Failed to delete cluster minikube, proceeding with retry anyway.
* Starting control plane node minikube in cluster minikube
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
* Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
  - env NO_PROXY=192.168.99.100
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by priyawadhwa** [comment] 2021-02-03 19:13
Hey @AndreyIvshin thank you for opening this issue. It looks like this is a dupe of https://github.com/kubernetes/minikube/issues/10152 which you also opened -- it would be helpful to centralize this conversation in one issue. I'm going to close this issue, and let's discuss in https://github.com/kubernetes/minikube/issues/10152 instead!

**Closed by priyawadhwa** 2021-02-03 19:13 UTC
Labels: kind/support
