### ISSUE TITLE
Failed to start host: creating host: create host timed out in 360.000000 seconds 💡 Suggestion: Try 'minikube delete', and disable any conflicting VPN or firewall software

### ISSUE THREAD

**Issue by VedRatan** [kubernetes/minikube#16673] opened 2023-06-11 19:31 UTC
### What Happened?

I have tried to run minikube inside the devcontainer. But the minikube is unable to start inside the container. I have mounted all the required files inside the devcontainer. 

![image](https://github.com/kubernetes/minikube/assets/82467006/c2404657-6074-4515-bc89-0a960547070c)

## Here is the Dockerfile

![image](https://github.com/kubernetes/minikube/assets/82467006/d11b0398-10b1-496d-8001-48776805e82b)

## Here is the devcontainer.json file

![image](https://github.com/kubernetes/minikube/assets/82467006/0cad5a5a-5da2-4636-9dcc-59e044a0b13e)

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11715511/log.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by lucasfcnunes** [comment] 2023-09-08 15:50
Duplicate of https://github.com/kubernetes/minikube/issues/13950

**Closed** 2024-03-28 02:35 UTC
Labels: lifecycle/rotten
