### ISSUE TITLE
minikube service failing to tunnel in 1.25.2, workaround of kubectl port-forward service still works

### ISSUE THREAD

**Issue by minaelee** [kubernetes/minikube#13746] opened 2022-03-04 09:07 UTC
### What Happened?

I had minikube version 1.23.2. I could run **minikube service _servicename_** fine. I would get a table that looks like this:

<img width="657" alt="image" src="https://user-images.githubusercontent.com/4936954/156730939-e290c93a-17aa-4526-97cf-f469a22dba63.png">
My browser would automatically open to the 127.0.0.1 URL for the tunnel and everything worked great. This is using a very simple NodePort deployment.

Then I updated minikube to version 1.25.2. Nothing else changed on my system. Now when I run **minikube service _servicename_**, I only get this and no table:
<img width="669" alt="image" src="https://user-images.githubusercontent.com/4936954/156732893-b059bb8f-4d5a-4e20-b009-6bd204e4002d.png">
And my browser automatically tries to open a 192.68 address, so it seems the tunnel is failing.

Using the instructions at https://minikube.sigs.k8s.io/docs/start/ I did a quick test by running:
kubectl create deployment hello-minikube --image=k8s.gcr.io/echoserver:1.4
kubectl expose deployment hello-minikube --type=NodePort --port=8080

Then the following instructions at that page say:
<img width="664" alt="image" src="https://user-images.githubusercontent.com/4936954/156731690-6a27a68f-c2f7-4b54-a168-5d2dd8183f79.png">

I tried **minikube service hello-minikube** and it had the same issue as my other example above. Doesn't show a table, and tries to go to a 192.x address instead of a localhost one.

I tried the second suggestion to use **kubectl port-forward service/hello-minikube 7080:8080** then go to localhost:7080 and this _did_ work.
So I tried the same approach using kubectl port-forward service for my other application hellodjango-kube (shown in initial screenshots) and that also worked.

I tested with a Mac with an Intel chip. However, I have heard from several others who have run into this exact issue with 1.25.2, with both Windows 10 and Mac, including M1 Macs. 

### Attach the log file

[logforyou.txt](https://github.com/kubernetes/minikube/files/8184501/logforyou.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by medyagh** [comment] 2022-03-04 20:08
might be duplicate of https://github.com/kubernetes/minikube/issues/13736

**Comment by medyagh** [comment] 2022-03-09 23:08
here is the link to the binary from a PR that I think might fix this issue, do you mind trying it out ?

https://storage.googleapis.com/minikube-builds/13756/minikube-linux-amd64
https://storage.googleapis.com/minikube-builds/13756/minikube-darwin-amd64
https://storage.googleapis.com/minikube-builds/13756/minikube-windows-amd64.exe

**Closed** 2022-03-09 23:08 UTC
