### ISSUE TITLE
MINIKUBE_ADDONS environment variable ignored

### ISSUE THREAD

**Issue by davecardwell** [kubernetes/minikube#11171] opened 2021-04-23 15:07 UTC
`minikube start` does not support the `MINIKUBE_ADDONS` environment variable as a proxy for the `--addons` argument as it does with other options.

**Steps to reproduce the issue:** 

1. `MINIKUBE_PROFILE=this-works MINIKUBE_ADDONS=registry minikube start`
2. `MINIKUBE_PROFILE=this-works minikube addons list`
3. Note that `MINIKUBE_PROFILE` has taken effect (the profile is set to `this-works`), but `MINIKUBE_ADDONS` has not (the `registry` addon has not been enabled).

**Full output of failed command:**

```
$ MINIKUBE_PROFILE=this-works MINIKUBE_ADDONS=registry minikube start

😄  [this-works] minikube v1.19.0 on Darwin 10.15.7
    ▪ MINIKUBE_ADDONS=registry
    ▪ MINIKUBE_PROFILE=this-works
✨  Automatically selected the hyperkit driver. Other choices: virtualbox, ssh
👍  Starting control plane node this-works in cluster this-works
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "this-works" cluster and "default" namespace by default


$ MINIKUBE_PROFILE=this-works minikube addons list

|-----------------------------|------------|--------------|
|         ADDON NAME          |  PROFILE   |    STATUS    |
|-----------------------------|------------|--------------|
| ambassador                  | this-works | disabled     |
| auto-pause                  | this-works | disabled     |
| csi-hostpath-driver         | this-works | disabled     |
| dashboard                   | this-works | disabled     |
| default-storageclass        | this-works | enabled ✅   |
| efk                         | this-works | disabled     |
| freshpod                    | this-works | disabled     |
| gcp-auth                    | this-works | disabled     |
| gvisor                      | this-works | disabled     |
| helm-tiller                 | this-works | disabled     |
| ingress                     | this-works | disabled     |
| ingress-dns                 | this-works | disabled     |
| istio                       | this-works | disabled     |
| istio-provisioner           | this-works | disabled     |
| kubevirt                    | this-works | disabled     |
| logviewer                   | this-works | disabled     |
| metallb                     | this-works | disabled     |
| metrics-server              | this-works | disabled     |
| nvidia-driver-installer     | this-works | disabled     |
| nvidia-gpu-device-plugin    | this-works | disabled     |
| olm                         | this-works | disabled     |
| pod-security-policy         | this-works | disabled     |
| registry                    | this-works | disabled     |
| registry-aliases            | this-works | disabled     |
| registry-creds              | this-works | disabled     |
| storage-provisioner         | this-works | enabled ✅   |
| storage-provisioner-gluster | this-works | disabled     |
| volumesnapshots             | this-works | disabled     |
|-----------------------------|------------|--------------|
💡  To see addons list for other profiles use: `minikube addons -p name list
```

**Comment by medyagh** [comment] 2021-04-25 16:32
@davecardwell than you for creating this sue, not all our flags are configurable by ENV but this should be easy to add support for it. (Since we are using cobra)

Would you be interested to contribute this as a PR to minikube ?

**Comment by davecardwell** [comment] 2021-04-29 19:46
@medyagh I did try to take a quick look prior to reporting, but I’m not a Go programmer so didn’t get beyond looking for any obvious logic issues.

I noticed that unlike most of the options, `--addons` [goes straight into](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go#L150) `&config.AddonList` from `k8s.io/minikube/pkg/minikube/config`. It is then _not_ made part of the `ClusterConfig` like most of the other flags are [here](https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/start_flags.go#L360). I assumed something going awry due to these differences, but didn’t look any further.

I will try to make time to set up the code and write a test case at least to see if I can figure it out. If anybody else with Go experience wants to jump in before then though I’d be fine with that! ;)

**Comment by govargo** [comment] 2021-04-29 22:53
Hi @davecardwell 

Thank you for creating this issue.
I would like to say for this feature.

As you said, the addons flag is through at here.
https://github.com/kubernetes/minikube/blob/fe0a1774a6be272a255f6de1930fb81a82430e28/cmd/minikube/cmd/start_flags.go#L150
And the `config.AddonList` is used at here.
https://github.com/kubernetes/minikube/blob/15cede53bdc5fe242228853e737333b09d4336b5/pkg/minikube/node/start.go#L165-L172

So I think if you set some code about environment `MINIKUBE_ADDONS` to `pkg/minikube/node/start.go`, minikube can set its value to `config.AddonList`.

I'm looking forward to your codes. If you have any questions, please let us know.

**Comment by davecardwell** [comment] 2021-04-30 01:00
@govargo Thank you for the additional context. I think the main part I was unsure of was why the `viper.AutomaticEnv()` stuff was not working for `MINIKUBE_ADDONS` as it seemed to be for the rest of the `start` options:
https://github.com/kubernetes/minikube/blob/fe0a1774a6be272a255f6de1930fb81a82430e28/cmd/minikube/cmd/start_flags.go#L129-L133

I will try to investigate further soon.

**Comment by bisakhmondal** [comment] 2021-05-03 06:44
Hi all, I dig into the problem and it turns out that that the problem is with the viper from spf13. We are trying to capture a `slice` but it seems viper is unable to do so.

1. passing as a flag : single item : works :heavy_check_mark: 
![image](https://user-images.githubusercontent.com/41498427/116847614-853cc400-ac08-11eb-82c8-a77e97b5ca1b.png)

2. passing as a flag : multiple items : does not work :x:
![image](https://user-images.githubusercontent.com/41498427/116847802-ec5a7880-ac08-11eb-8399-28985f307956.png)

3. passing and environment variable: :x: 

I think the issue is with `StringSliceVar`.

**Comment by medyagh** [comment] 2021-05-12 18:57
> Hi all, I dig into the problem and it turns out that that the problem is with the viper from spf13. We are trying to capture a `slice` but it seems viper is unable to do so.
> 
> 1. passing as a flag : single item : works ✔️
>    ![image](https://user-images.githubusercontent.com/41498427/116847614-853cc400-ac08-11eb-82c8-a77e97b5ca1b.png)
> 2. passing as a flag : multiple items : does not work ❌
>    ![image](https://user-images.githubusercontent.com/41498427/116847802-ec5a7880-ac08-11eb-8399-28985f307956.png)
> 3. passing and environment variable: ❌
> 
> I think the issue is with `StringSliceVar`.

@bisakhmondal  seems like you found a bug ! would u like to make a PR to fix it ?

**Comment by utkarsh-pro** [comment] 2021-05-19 17:38
@medyagh can I work on this issue? // @spowelljr

**Comment by spowelljr** [comment] 2021-05-19 17:45
@utkarsh-pro For sure! Just comment `/assign` and the issue will be assigned to you.

**Comment by utkarsh-pro** [comment] 2021-05-19 17:50
Thanks @spowelljr!

/assign

**Comment by DimitrijeManic** [comment] 2021-05-20 12:20
@utkarsh-pro Do you plan on making it possible to set addons in the config or just ENV variables?

**Comment by utkarsh-pro** [comment] 2021-05-20 16:47
@DimitrijeManic, PR https://github.com/kubernetes/minikube/pull/11469 only adds support for setting `addons` using environmental variables (in addition to `--addons` flag). I am not sure if increasing the scope of the issue would be appropriate. 

However, I'd be more than happy to add support for config too if it's a requirement and is accepted by the admins :smile:

**Closed** 2021-05-26 17:19 UTC
Labels: good first issue, help wanted, kind/bug, priority/important-longterm
