### ISSUE TITLE
virtual machine 'minikube' has terminated unexpectedly - NS_ERROR_FAILURE (0x80004005)

### ISSUE THREAD

**Issue by Gopalagithub** [kubernetes/minikube#5090] opened 2019-08-15 06:22 UTC
**The exact command to reproduce the issue**:

minikube start

**The full output of the command that failed**:<details>

😄  minikube v1.3.1 on Ubuntu 16.04
💿  Downloading VM boot image ...
minikube-v1.3.0.iso.sha256: 65 B / 65 B [--------------------] 100.00% ? p/s 0s
minikube-v1.3.0.iso: 131.07 MiB / 131.07 MiB [---] 100.00% 642.87 KiB p/s 3m29s
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0815 11:48:29.684647    6655 start.go:723] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

</details>

**The output of the `minikube logs` command**:<details>

</details>

Ubuntu 16.04 OS

**Comment by medyagh** [comment] 2019-08-15 18:33
I am curious  if you killed the minikube start with ctrl+c or power off ?

**Comment by tstromberg** [comment] 2019-08-15 18:34
This issue appears to be a duplicate of #4908, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-08-15 18:34 UTC
Labels: co/virtualbox
