### ISSUE TITLE
precreate: VirtualBox is configured with multiple host-only adapters with the same IP

### ISSUE THREAD

**Issue by umi0410** [kubernetes/minikube#4332] opened 2019-05-23 12:28 UTC
**The exact command to reproduce the issue**:
`minikube start`
**The full output of the command that failed**:
![error message](https://t1.daumcdn.net/cfile/tistory/99719A435CE60CF22B)
**The output of the `minikube logs` command**:
I didn't get it, sorry.
**The operating system version**:
Linux Ubuntu 18.04

**when does the errors occur**
I guess when I use both `sudo minikube start` and `minikube start`, virtualbox configurations got messed.
In that case, only one user between root and $USER was able to access minikube start.
The following image is the case when the error occurs with using the same IP
![error virtualbox](https://t1.daumcdn.net/cfile/tistory/997C323E5CE649961A)

**What I suggest!**

I think you are aware of why the error occurs ( because of the apapters that have the same IP )
but some users are not familiar with what the host-only adapters are and how to deal with them. So if you append some kind of detailed explanations for the error, it would be great. Like this.

"Try opening virtualbox, click Global Tools - Host Network Manager, and check out if there are network adapters which use the same IP.
Then remove an adapter which has the same IP or change the IP not to be the same."

**Comment by tstromberg** [comment] 2019-05-23 17:26
Thanks for opening this bug report. The error message is raised by libmachine, but minikube has a built-in way to suggest solutions for error messages that we should use here. I like your suggested text. You are welcome to edit this file to add a proper solution for this error message:

https://github.com/kubernetes/minikube/blob/master/pkg/minikube/problem/err_map.go

Otherwise we will try to get to it ourselves at some point. Thank you!

**Comment by tstromberg** [comment] 2019-05-23 18:41
Related: #3138

**Comment by tstromberg** [comment] 2019-05-23 22:33
Dupe of #3870 - will make sure that one gets a solution message though.

**Closed by tstromberg** 2019-05-23 22:33 UTC
Labels: co/virtualbox, needs-solution-message, priority/backlog, reviewed/2019q2
