### ISSUE TITLE
Error starting kubernetes cluster using minikube on windows

### ISSUE THREAD

**Issue by virenhada** [kubernetes/minikube#4707] opened 2019-07-07 20:47 UTC
>minikube start --vm-driver=hyperv --hyperv-virtual-switch={switch-name}

* minikube v1.2.0 on windows (amd64)
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
* Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
* Downloading kubelet v1.15.0
* Downloading kubeadm v1.15.0
* Pulling images ...
* Launching Kubernetes ...

X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
cannot use "fe80::215:5dff:fe2d:210" as the bind address for the API Server

: Process exited with status 1

PS: minikube version: v1.2.0

**Comment by tstromberg** [comment] 2019-07-16 20:47
This issue appears to be a duplicate of #3963, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed by tstromberg** 2019-07-16 20:47 UTC
Labels: co/hyperv, os/windows
