### ISSUE TITLE
Unable to mount CIFS volume

### ISSUE THREAD

**Issue by msnelling** [kubernetes/minikube#1739] opened 2017-07-25 08:28 UTC
**BUG REPORT**

**minikube version: v0.20.0**

**Environment**:
- **OS**: Windows 10 Enterprise 1703 (build 15063.483)
- **VM Driver**: hyperv
- **ISO version**: v0.20.0
- **Install tools**:
- **Others**:

**What happened**:
Tried to mount CIFS volume with the command
```
minikube ssh -- sudo mount -t cifs -o "ro,iocharset=utf8,uid=0,gid=0,username=someuser,password=somepass,vers=2.0" //1.2.3.4/Share /mnt/share
```
I get the following error
```
mount error: cifs filesystem not supported by the system
mount error(19): No such device
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)
```
If I run `minikube ssh -- sudo modprobe cifs` I get the following error
```
modprobe: FATAL: Module cifs not found in directory /lib/modules/4.9.13
```
**What you expected to happen**:
I expected the share to be mounted as read-only under /mnt/share

**How to reproduce it** (as minimally and precisely as possible):
```
minikube ssh -- sudo mkdir -p /mnt/share
minikube ssh -- sudo mount -t cifs -o "ro,iocharset=utf8,uid=0,gid=0,username=myuser,password=mypass,vers=2.0" //1.2.3.4/Share /mnt/share
```

**Anything else do we need to know**:
I have tested the above mount command using an Ubuntu 16.04 VM running in Hyper-V on the same machine and it works successfully.

**Comment by r2d4** [comment] 2017-07-25 16:51
Marking this as a dupe of https://github.com/kubernetes/minikube/issues/1197.

Looks like we need to enable the kernel module also

**Closed by r2d4** 2017-07-25 16:51 UTC
