### ISSUE TITLE
KVM Containerd integration tests timeout

### ISSUE THREAD

**Issue by spowelljr** [kubernetes/minikube#11506] opened 2021-05-25 18:19 UTC
This may he a suspect PR: https://github.com/kubernetes/minikube/pull/11325

**Comment by medyagh** [comment] 2021-05-25 19:25
we should check if this is a Debian 9 problem or is it happening on debian 10 too
on my mac hyperkit it the basic start works
```
$ mk start -p p1 --container-runtime=containerd
😄  [p1] minikube v1.20.0 on Darwin 11.3.1
✨  Automatically selected the docker driver. Other choices: hyperkit, parallels, virtualbox, ssh
👍  Starting control plane node p1 in cluster p1
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
📦  Preparing Kubernetes v1.20.2 on containerd 1.4.4 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "p1" cluster and "default" namespace by default
```
get pods
```
$ kc get pods -A
NAMESPACE     NAME                         READY   STATUS    RESTARTS   AGE
kube-system   coredns-74ff55c5b-jgkl5      0/1     Running   0          39s
kube-system   etcd-p1                      0/1     Running   0          51s
kube-system   kindnet-jrjpb                1/1     Running   0          39s
kube-system   kube-apiserver-p1            1/1     Running   0          51s
kube-system   kube-controller-manager-p1   0/1     Running   0          51s
kube-system   kube-proxy-wlqxj             1/1     Running   0          39s
kube-system   kube-scheduler-p1            0/1     Running   0          51s
kube-system   storage-provisioner          1/1     Running   0          51s
```

**Comment by medyagh** [comment] 2021-05-27 17:20
dupe of https://github.com/kubernetes/minikube/issues/11512

**Closed by medyagh** 2021-05-27 17:20 UTC
Labels: area/testing, co/runtime/containerd, kind/failing-test
