### ISSUE TITLE
Minikube VM clock is out of synch after hibernating a Mac computer and resuming again.

### ISSUE THREAD

**Issue by aidagha** [kubernetes/minikube#4709] opened 2019-07-08 06:41 UTC
**kubectl describe pods your-pod-name**:

<details>
Events: <br /> 
  Type       Reason        Age      From                          Message <br /> 
  ----         ------          ----      ----                            ------- <br /> 
  Normal    Created      4d       kubelet, minikube      Created container x <br /> 
</details>

**macOS Mojave**

I used hyperkit VM for minikube.

**Comment by afbjorklund** [comment] 2019-07-14 09:10
Duplicate #1378 (has workarounds)

**Comment by tstromberg** [comment] 2019-07-16 20:46
This issue appears to be a duplicate of #1378, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed** 2019-07-16 20:46 UTC
Labels: co/hyperkit, triage/duplicate
