### ISSUE TITLE
kvm2: Unable to start VM: new host: dial tcp: missing address

### ISSUE THREAD

**Issue by gouravbansal11** [kubernetes/minikube#4295] opened 2019-05-20 09:59 UTC
[gouravba@gouravba02lx ~]$ minikube start --vm-driver kvm2 --logtostderr
W0520 15:02:34.998166 1333 root.go:145] Error reading config file at /home/gouravba/.minikube/config/config.json: open /home/gouravba/.minikube/config/config.json: no such file or directory
I0520 15:02:34.998755 1333 notify.go:126] Checking for updates...
o minikube v1.0.1 on linux (amd64)
@ Downloading Minikube ISO ...
142.88 MB / 142.88 MB [============================================] 100.00% 0s
$ Downloading Kubernetes v1.14.1 images in the background ...
I0520 15:12:45.476634 1333 start.go:652] Saving config:
{
"MachineConfig": {
"MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.0.1.iso",
"Memory": 2048,
"CPUs": 2,
"DiskSize": 20000,
"VMDriver": "kvm2",
"ContainerRuntime": "docker",
"HyperkitVpnKitSock": "",
"HyperkitVSockPorts": [],
"XhyveDiskDriver": "ahci-hd",
"DockerEnv": [
"HTTP_PROXY=[Proxy]",
"HTTPS_PROXY=[Proxy]"
],
"InsecureRegistry": null,
"RegistryMirror": null,
"HostOnlyCIDR": "192.168.99.1/24",
"HypervVirtualSwitch": "",
"KvmNetwork": "default",
"DockerOpt": null,
"DisableDriverMounts": false,
"NFSShare": [],
"NFSSharesRoot": "/nfsshares",
"UUID": "",
"GPU": false,
"Hidden": false,
"NoVTXCheck": false
},
"KubernetesConfig": {
"KubernetesVersion": "v1.14.1",
"NodeIP": "",
"NodePort": 8443,
"NodeName": "minikube",
"APIServerName": "minikubeCA",
"APIServerNames": null,
"APIServerIPs": null,
"DNSDomain": "cluster.local",
"ContainerRuntime": "docker",
"CRISocket": "",
"NetworkPlugin": "",
"FeatureGates": "",
"ServiceCIDR": "10.96.0.0/12",
"ImageRepository": "",
"ExtraOptions": null,
"ShouldLoadCachedImages": true,
"EnableDefaultCNI": false
}
}
I0520 15:12:45.476713 1333 cache_images.go:309] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at /home/gouravba/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0520 15:12:45.478034 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0520 15:12:45.478370 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.1
I0520 15:12:45.478484 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.14.1
I0520 15:12:45.478582 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.1
I0520 15:12:45.478645 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0520 15:12:45.478673 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.14.1
I0520 15:12:45.478759 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/pause:3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0520 15:12:45.478794 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
I0520 15:12:45.478846 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0520 15:12:45.478924 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0520 15:12:45.478949 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
I0520 15:12:45.479116 1333 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0520 15:12:45.479382 1333 cluster.go:78] Machine does not exist... provisioning new machine
I0520 15:12:45.479393 1333 cluster.go:79] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.0.1.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:kvm2 ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[HTTP_PROXY=[Proxy] HTTPS_PROXY=[Proxy]] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false Hidden:false NoVTXCheck:false}

Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
**I0520 15:12:45.503064 1333 start.go:428] StartHost: new host: dial tcp: missing address
I0520 15:12:45.503097 1333 utils.go:122] non-retriable error: new host: dial tcp: missing address
W0520 15:12:45.505322 1333 exit.go:99] Unable to start VM: new host: dial tcp: missing address

! Unable to start VM: new host: dial tcp: missing address**

Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
https://github.com/kubernetes/minikube/issues/new
[gouravba@gouravba02lx ~]$ sudo systemctl status libvirtd.service
libvirtd.service - Virtualization daemon
Loaded: loaded (/usr/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
Active: active (running) since Mon 2019-05-20 15:00:36 IST; 12min ago
Docs: man:libvirtd(8)
http://libvirt.org
Main PID: 1004 (libvirtd)
CGroup: /system.slice/libvirtd.service
|-1004 /usr/sbin/libvirtd
|-1184 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --dhcp-script=/usr/libexec/libvirt_leaseshelper
`-1185 /sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --dhcp-script=/usr/libexec/libvirt_leaseshelper
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: compile time options: IPv6 GNU-getopt DBus no-i18n IDN DHCP DHCPv6 no-Lua TFTP no-conntrack ipset auth
May 20 15:00:38 gouravba02lx.company dnsmasq-dhcp[1184]: DHCP, IP range 192.168.122.2 -- 192.168.122.254, lease time 1h
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: reading /etc/resolv.conf
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: using nameserver 10.20.40.100#53
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: using nameserver 10.19.212.200#53
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: using nameserver 10.57.80.60#53
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: using nameserver 10.19.93.89#53
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: read /etc/hosts - 6 addresses
May 20 15:00:38 gouravba02lx.company dnsmasq[1184]: read /var/lib/libvirt/dnsmasq/default.addnhosts - 0 addresses
May 20 15:00:38 gouravba02lx.company dnsmasq-dhcp[1184]: read /var/lib/libvirt/dnsmasq/default.hostsfile

**Comment by gouravbansal11** [comment] 2019-05-23 14:48
With -v=999 

I0523 20:13:40.717202    9986 cache_images.go:309] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at /home/gouravba/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.1
I0523 20:13:40.717568    9986 cluster.go:78] Machine does not exist... provisioning new machine
I0523 20:13:40.717579    9986 cluster.go:79] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.0.1.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:kvm2 ContainerRuntime:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] XhyveDiskDriver:ahci-hd DockerEnv:[HTTP_PROXY=genproxy.amdocs.com:8080 HTTPS_PROXY=genproxy.amdocs.com:8080] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: GPU:false Hidden:false NoVTXCheck:false}
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
Found binary path at /usr/local/bin/docker-machine-driver-kvm2
Launching plugin server for driver kvm2
I0523 20:13:40.719128    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.1
I0523 20:13:40.719311    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.14.1
I0523 20:13:40.719426    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.1
I0523 20:13:40.719510    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.14.1
I0523 20:13:40.719597    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/pause:3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0523 20:13:40.719682    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0523 20:13:40.719776    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0523 20:13:40.719851    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0523 20:13:40.719961    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
I0523 20:13:40.720042    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0523 20:13:40.720125    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0523 20:13:40.720238    9986 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt-lxc.so.0: version `LIBVIRT_LXC_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.9' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.11' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
Plugin server listening at address
I0523 20:13:40.721644    9986 start.go:428] StartHost: new host: dial tcp: missing address
I0523 20:13:40.721659    9986 utils.go:122] non-retriable error: new host: dial tcp: missing address
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.14' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.12' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.16' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.15' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.19' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_3.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
W0523 20:13:40.722016    9986 exit.go:99] Unable to start VM: new host: dial tcp: missing address

!   Unable to start VM: new host: dial tcp: missing address

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment] 2019-05-23 18:37
Based on this message, I'm pretty sure this is a dupe of #3437

```
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt-lxc.so.0: version LIBVIRT_LXC_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2) () DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version LIBVIRT_1.2.9' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
```

Do you mind upgrading to the latest kvm2 driver and seeing if it still occurs?

` curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2 && sudo install docker-machine-driver-kvm2 /usr/local/bin/`

You should be able to quickly reproduce this by simply running `/usr/local/bin/docker-machine-driver-kvm2` on your command-line.

**Comment by gouravbansal11** [comment] 2019-05-24 09:11
same issue even after updating the docker-machine-driver-kvm2


Launching plugin server for driver kvm2
I0524 14:03:59.711680    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-proxy_v1.14.1
I0524 14:03:59.711890    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.14.1
I0524 14:03:59.712001    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.1
I0524 14:03:59.712085    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-apiserver_v1.14.1
I0524 14:03:59.712192    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/pause:3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/pause_3.1
I0524 14:03:59.712280    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.13
I0524 14:03:59.712370    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0524 14:03:59.712452    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.13
I0524 14:03:59.712542    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/etcd_3.3.10
I0524 14:03:59.712615    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/coredns_1.3.1
I0524 14:03:59.712722    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.10.1
I0524 14:03:59.712808    6848 cache_images.go:309] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at /home/gouravba/.minikube/cache/images/k8s.gcr.io/kube-addon-manager_v9.0
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt-lxc.so.0: version `LIBVIRT_LXC_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.9' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
Plugin server listening at address
I0524 14:03:59.714414    6848 start.go:428] StartHost: new host: dial tcp: missing address
I0524 14:03:59.714436    6848 utils.go:122] non-retriable error: new host: dial tcp: missing address
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.11' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_2.2.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.14' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.12' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.16' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.15' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.2.19' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_3.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_1.3.3' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
() DBG | /usr/local/bin/docker-machine-driver-kvm2: /lib64/libvirt.so.0: version `LIBVIRT_2.0.0' not found (required by /usr/local/bin/docker-machine-driver-kvm2)
W0524 14:03:59.714783    6848 exit.go:99] Unable to start VM: new host: dial tcp: missing address

!   Unable to start VM: new host: dial tcp: missing address

**Comment by tstromberg** [comment] 2019-05-24 17:36
Signs still point to a version incompatibility with the installed version of libvirt, but I'd like to figure this out. What Linux distribution and version are you running?

Do you mind sharing the output of:

`virsh --version`
`strings /lib64/libvirt-lxc.so.0 | grep LIBVIRT_LXC`
`strings /lib64/libvirt.so.0 | grep LIBVIRT_`

Thanks!

**Comment by gouravbansal11** [comment] 2019-05-24 18:05
[gouravba@gouravba02lx ~]$ virsh --version
1.2.8
[gouravba@gouravba02lx ~]$ strings /lib64/libvirt-lxc.so.0 | grep LIBVIRT_LXC
LIBVIRT_LXC_1.0.2
LIBVIRT_LXC_1.0.4
[gouravba@gouravba02lx ~]$ strings /lib64/libvirt.so.0 | grep LIBVIRT_
LIBVIRT_0.0.3
LIBVIRT_0.0.5
LIBVIRT_0.1.0
LIBVIRT_0.1.1
LIBVIRT_0.1.4
LIBVIRT_0.1.5
LIBVIRT_0.1.9
LIBVIRT_0.2.0
LIBVIRT_0.2.1
LIBVIRT_0.2.3
LIBVIRT_0.3.0
LIBVIRT_0.3.2
LIBVIRT_0.3.3
LIBVIRT_0.4.0
LIBVIRT_0.4.1
LIBVIRT_0.4.2
LIBVIRT_0.4.5
LIBVIRT_0.5.0
LIBVIRT_0.6.0
LIBVIRT_0.6.1
LIBVIRT_0.6.3
LIBVIRT_0.6.4
LIBVIRT_0.7.0
LIBVIRT_0.7.1
LIBVIRT_0.7.2
LIBVIRT_0.7.3
LIBVIRT_0.7.5
LIBVIRT_0.7.7
LIBVIRT_0.8.0
LIBVIRT_0.8.1
LIBVIRT_0.8.2
LIBVIRT_0.8.5
LIBVIRT_0.8.6
LIBVIRT_0.8.8
LIBVIRT_0.9.0
LIBVIRT_0.9.2
LIBVIRT_0.9.3
LIBVIRT_0.9.4
LIBVIRT_0.9.5
LIBVIRT_0.9.7
LIBVIRT_0.9.8
LIBVIRT_0.9.9
LIBVIRT_0.9.10
LIBVIRT_0.9.11
LIBVIRT_0.9.13
LIBVIRT_0.10.0
LIBVIRT_0.10.2
LIBVIRT_1.0.0
LIBVIRT_1.0.1
LIBVIRT_1.0.2
LIBVIRT_1.0.3
LIBVIRT_1.0.5
LIBVIRT_1.0.6
LIBVIRT_1.1.0
LIBVIRT_1.1.1
LIBVIRT_1.1.3
LIBVIRT_1.2.1
LIBVIRT_1.2.3
LIBVIRT_1.2.5
LIBVIRT_1.2.6
LIBVIRT_1.2.7
LIBVIRT_1.2.8
LIBVIRT_PRIVATE_1.2.8
LIBVIRT_AUTH_FILE
LIBVIRT_DOMAIN
LIBVIRT_CODE
LIBVIRT_LOG_OUTPUTS
LIBVIRT_SOURCE
LIBVIRT_DEBUG
LIBVIRT_LOG_FILTERS
LIBVIRT_DRIVER_DIR
LIBVIRT_DEFAULT_URI
Using LIBVIRT_DEFAULT_URI '%s'
LIBVIRT_LOCK_MANAGER_PLUGIN_DIR
LIBVIRT_AUTOSTART
LIBVIRT_GNUTLS_DEBUG
[gouravba@gouravba02lx ~]$

**Comment by gouravbansal11** [comment] 2019-05-24 18:07
[gouravba@gouravba02lx ~]$ cat /etc/*-release
NAME="Red Hat Enterprise Linux Server"
VERSION="7.3 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="7.3"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.3 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.3:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.3"
Red Hat Enterprise Linux Server release 7.3 (Maipo)
Red Hat Enterprise Linux Server release 7.3 (Maipo)

**Comment by tstromberg** [comment] 2019-05-24 21:19
Apparently, the pre-built kvm2 driver requires libvirt 1.3.1 or higher (Jan 2016), and your system has libvirt 1.2.8 (Sep 2014). For older releases, you can try compiling your own driver: https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver

Alternatively, you can likely use the virtualbox VM driver on this system.

**Comment by afbjorklund** [comment] 2019-07-06 11:49
This is due to #4555. As a workaround, please use an older docker-machine-driver-kvm2 (0.30.0)

https://github.com/kubernetes/minikube/releases/download/v0.30.0/docker-machine-driver-kvm2

**Closed** 2019-07-06 11:51 UTC
Labels: co/kvm2, kind/bug, triage/duplicate

**Comment by chakpongchung** [comment] 2019-10-30 01:07
@afbjorklund 

please reopen this one. I am seeing this:

minikube start --vm-driver=docker-machine-driver-kvm2 --memory 8192 --cpus 4
😄  minikube v1.5.1 on Ubuntu 19.04
💣  The driver 'docker-machine-driver-kvm2' is not supported on linux
