### ISSUE TITLE
fix cobra wrong help "use optoins for list of ...."

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#5850] opened 2019-11-06 22:07 UTC
```
$ minikube profile --help
profile sets the current minikube profile, or gets the current profile if no arguments are provided.  This is used to
run and manage multiple minikube instance.  You can return to the default minikube profile by running `minikube profile
default`

Available Commands:
  list        Lists all minikube profiles.

Usage:
  minikube profile [MINIKUBE_PROFILE_NAME].  You can return to the default minikube profile by running `minikube profile
default` [flags] [options]

Use "minikube <command> --help" for more information about a given command.
Use "minikube profile options" for a list of global command-line options (applies to all commands).
```

the last line is wrong:

Use "minikube profile options" for a list of global command-line options (applies to all commands)

**Comment by medyagh** [comment] 2019-11-06 22:07
@sharifelgamal said he might know what is causing this.

**Comment by andylibrian** [comment] 2019-11-07 13:48
There is already an issue about this: https://github.com/kubernetes/minikube/issues/5036

**Comment by sharifelgamal** [comment] 2019-11-08 22:03
Closing as a dupe of #5036.

**Closed by sharifelgamal** 2019-11-08 22:03 UTC
Labels: kind/bug, kind/ux, priority/important-longterm
