### ISSUE TITLE
docker on CrOS: apply authorized_keys file ownership -> container is not running

### ISSUE THREAD

**Issue by steren** [kubernetes/minikube#7346] opened 2020-03-31 23:21 UTC
I want to create a minikube cluster.
I am on Linux in ChomeOS 

```
💣  getting config: cluster "localcluster" does not exist

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
🎉  minikube 1.9.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.9.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

🙄  [localcluster] minikube v1.8.2 on Debian 9.9
✨  Using the docker driver based on user configuration
💾  Downloading preloaded images tarball for k8s v1.17.3 ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 499.26 MiB / 499
🔥  Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=3600MB (14553MB available) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create: creating: prepare kic ssh: apply authorized_keys file ownership, output 
** stderr ** 
Error response from daemon: Container d97998d548bf58d74032a8cb121a29571472e25a8907e984dc3841b7b875ba5d is not running

** /stderr **: chown docker:docker /home/docker/.ssh/authorized_keys: exit status 1
stdout:

stderr:
Error response from daemon: Container d97998d548bf58d74032a8cb121a29571472e25a8907e984dc3841b7b875ba5d is not running
```

**Comment by medyagh** [comment] 2020-04-01 18:41
Hi @steren currently we dont have support for chrome os.

**Comment by tstromberg** [comment] 2020-04-02 21:49
This issue appears to be a duplicate of #6411, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-02 21:49 UTC
Labels: co/docker-driver, long-term-support, os/linux
