### ISSUE TITLE
minikube service opens in browser when it should not

### ISSUE THREAD

**Issue by retracile** [kubernetes/minikube#5789] opened 2019-10-30 16:48 UTC
**The exact command to reproduce the issue**:

minikube service --namespace mynamespace --url mynodeportservice

**The full output of the command that failed**:<details>

In versions of minikube through 1.3.1, this output the service URL to stdout, and _did not_ open the URL in the default browser.  In 1.5.1, it outputs the URL and the "🎉  Opening kubernetes service ..." message to stdout, and it opens in the default browser.

With --url=false, it does not open in the browser, but now it outputs an ascii-art table instead of the plain URL.
With --url=true, it behaves the same as with --url.

Based on finding #5699, I tried using --format="{{ .IP }}".  That leads to even greater insanity... it emits the message about opening the service in the default browser, but then fails to do so because it tries to open a file in the current directory matching the IP address, and errors out.

Please restore the older behavior so scripts can get the URL for a service, and fix --format to _not_ try to open the resulting string in the default browser.
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Mojave
minikube 1.5.1 installed via homebrew

**Comment by tstromberg** [comment] 2019-10-30 16:54
This sounds like a regression, possibly caused by #5718. Perhaps the urlMode logic got inverted?

/cc @nanikjava

**Comment by retracile** [comment] 2019-10-30 17:12
Looks like the logic moved from pkg/minikube/servcice/service.go to cmd/minikube/cmd/service.go between 1.3.1 and 1.5.1.
The logic in the command code is only looking at the length of urlString list to determine if it should open the browser, and is not considering the value of serviceURLMode.

**Comment by tstromberg** [comment] 2019-10-30 17:21
@retracile - Thanks, I'm working on a PR now with an integration test to avoid future similar breakage.

This definitely revealed a short-coming in our testing.

**Comment by retracile** [comment] 2019-10-30 17:24
A quick local test shows that change fixes it for me, and `--url --format "{{.IP}}"` also works. :)

**Comment by retracile** [comment] 2019-10-30 18:47
There's no newline in the `--url` output, but there was in v1.5.0

Tangent: Under some situations I'm also seeing a `* ` prefix on the output... this is very close to when the service is created, and I've seen that in older versions as well.  I have not found a way to consistently reproduce that, so hadn't reported it.

**Comment by tstromberg** [comment] 2019-10-30 19:05
The newline seemed incorrect to me, so I removed it out. I could preserve if it it's useful.

What command are you you seeing the * prefix?

**Comment by retracile** [comment] 2019-10-30 19:13
*NIX commands generally include the newline at the end; otherwise you wind up with your shell prompt tacked on the end of the output (when using it interactively).  When using it within a script, it works either way.

**Comment by tstromberg** [comment] 2019-10-30 19:16
Good point. Will add newline back.

**Comment by retracile** [comment] 2019-10-30 19:16
For the `* ` prefix, that's a separate issue, and dates way back.  I see it when running the same command discussed here, but it appears to only happen for a brief period after the service is created... brief enough that I don't think I've ever managed to reproduce it outside of automated scripting.  Maybe it happens in the time between the service being created and it being ready?  Or something?  ... I'm guessing there.

Regardless, it's a separate issue from this one.

**Comment by tstromberg** [comment] 2019-10-30 21:04
@retracile - Regardless, it sounds wrong. If you know of a way to reproduce it, let me know.

The asterisk is likely caused by a call to `out.T()` rather than the raw equivalent `out.String()`. I removed the calls I saw, but there may be others.

**Comment by retracile** [comment] 2019-10-30 21:29
`out.T()` vs `out.String()` is a useful clue; maybe I can track it down at some point.  Thanks.

**Comment by tstromberg** [comment] 2019-10-30 22:28
Reopening until we release v1.5.2 containing this fix (tomorrow).

**Comment by tstromberg** [comment] 2019-10-31 22:31
Fixed in v1.5.2. Thank you for reporting this issue!

**Closed** 2019-10-31 22:31 UTC
Labels: co/service, kind/bug
