### ISSUE TITLE
Unable to start VM: Hyper-v commands have to be run as an Administrator

### ISSUE THREAD

**Issue by devang-vaidya76** [kubernetes/minikube#4189] opened 2019-05-02 06:04 UTC
I thought I'm logged in with administrator privilege, however, receiving this error when attempting to run minikube with the following command:

minikube start --kubernetes-version="v1.14.0" --vm-driver="hyperv" --hyperv-virtual-switch="drvkube"

Detail of error:

Unable to start VM: create: precreate: Hyper-v commands have to be run as an Administrator

**Comment by tstromberg** [comment] 2019-05-02 16:41
Thank you for raising this issue! This seems to be identical to this minishift issue:

https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#insufficient-privileges

So that we could document this appropriately, do you mind trying to add your user to the Hyper-V administrators group, as that document suggests?

If it works, we can update the error to point other users to the same solution.

**Comment by devang-vaidya76** [comment] 2019-05-02 16:49
Sorry, but it did no work. Receiving same error. Any other suggestions?

Thanks.

**Comment by jfmatth** [comment] 2019-05-31 02:25
I followed the instructions from above by adding myself to the Hyper-V administrators, logged out and then it worked.

**Comment by sharifelgamal** [comment] 2019-07-18 18:22
Seems to be a duplicate of #4146, closing in favor of it.

**Closed by sharifelgamal** 2019-07-18 18:22 UTC
Labels: co/hyperv, priority/important-longterm, r/2019q2

**Comment by foxydevloper** [comment] 2023-10-02 12:29
Ran into this issue myself, didn't know anything about groups on windows so had to look this up
> https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#insufficient-privileges

This seems to be a dead link, its archived at https://web.archive.org/web/20190716051418/https://docs.okd.io/latest/minishift/troubleshooting/troubleshooting-driver-plugins.html#insufficient-privileges
Following the instructions does indeed fix the problem.
