### ISSUE TITLE
Document how to use the registry addon - especially with none driver.

### ISSUE THREAD

**Issue by kumarom** [kubernetes/minikube#4260] opened 2019-05-15 16:13 UTC
I have deployed a minikube environment using **minikube v1.0.1** using **none** driver. And I enabled regisry addon in minikube. At first the registry pods did not start but after editing */etc/kubernetes/addons/registry-rc.yaml*, I was able to bring up registry pod. Then using port-forward, I was able to push an image into the registry as follows:
```
docker tag test-img localhost:5000/test-img
docker push localhost:5000/test-img
```

However, I get error when I tried to run same image in minikube as follows:
```
kubectl run -i -t testimg --image=registry.kube-system/test-img --restart=Never
kubectl run -i -t testimg --image=registry/test-img --restart=Never
kubectl run -i -t testimg --image=registry/test-img --restart=Never
```
Each time I get same error as follows:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  35s                default-scheduler  Successfully assigned default/busybox to minikube
  Normal   Pulling    16s (x2 over 34s)  kubelet, minikube  pulling image "registry.kube-system/test-img"
  Warning  Failed     16s (x2 over 33s)  kubelet, minikube  Failed to pull image "registry.kube-system/test-img": rpc error: code = Unknown desc = Error response from daemon: Get https://registry.kube-system/v2/: Service Unavailable
  Warning  Failed     16s (x2 over 33s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    4s (x2 over 31s)   kubelet, minikube  Back-off pulling image "registry.kube-system/test-img"
  Warning  Failed     4s (x2 over 31s)   kubelet, minikube  Error: ImagePullBackOff
```

- What did I miss?
- Did I miss any configuration steps?
- Is there a documentation available on how to use addon registry within minikube itself..?
- Is this issue only with **none** driver ? I have not tried any other driver

This was on Ubuntu 16.04.6 LTS

**Comment by tstromberg** [comment] 2019-05-16 17:55
We don't have any registry documentation, though we'd love it if some were contributed. I've not used the registry, but presumably you are doing the right thing here. 

https://blog.hasura.io/sharing-a-local-registry-for-minikube-37c7240d0615/ has some external docs.

**Comment by tstromberg** [comment] 2019-05-16 18:39
Duplicate of #4242

**Closed by tstromberg** 2019-05-16 18:39 UTC
Labels: area/registry, good first issue, help wanted, kind/documentation, priority/backlog
