### ISSUE TITLE
getting issue while minikube start

### ISSUE THREAD

**Issue by usax** [kubernetes/minikube#7026] opened 2020-03-13 15:37 UTC
c:\Kubernetes_AWS>minikube.exe start
* minikube v1.8.1 on Microsoft Windows 10 Home 10.0.17134 Build 17134
* Automatically selected the virtualbox driver
*
X Error getting primary cp: could not find master node
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

c:\Kubernetes_AWS>minikube.exe logs
*
X Error getting primary control plane: could not find master node
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment] 2020-03-14 01:52
Please try minikube v1.8.2. This was a problem where v1.8.1 could not upgrade older profiles. 

Dupe of #6943

**Comment by tstromberg** [comment] 2020-03-14 01:53
Please /reopen if v1.8.2 does not fix your issue.

**Closed by tstromberg** 2020-03-14 01:52 UTC
