### ISSUE TITLE
Cannot start Minikube on Ubuntu using docker desktop vm

### ISSUE THREAD

**Issue by AmanSarraf** [kubernetes/minikube#14402] opened 2022-06-23 16:28 UTC
### What Happened?

When I do minikube start 
```cmd
aman@aman-HP-Laptop-15g-br0xx:~$ minikube start
😄  minikube v1.25.2 on Ubuntu 20.04
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔄  Restarting existing docker container for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
🤦  Unable to restart cluster, will reset it: apiserver health: apiserver healthz never reported healthy: cluster wait timed out during healthz check
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...| E0623 21:42:45.788445    5800 start.go:264] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://192.168.49.2:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 192.168.49.2:8443: i/o timeout]
🌟  Enabled addons: storage-provisioner
❌  Problems detected in kubelet:
    Jun 23 16:09:56 minikube kubelet[7626]: W0623 16:09:56.074774    7626 reflector.go:324] object-"kube-system"/"coredns": failed to list *v1.ConfigMap: configmaps "coredns" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
    Jun 23 16:09:56 minikube kubelet[7626]: E0623 16:09:56.075110    7626 reflector.go:138] object-"kube-system"/"coredns": Failed to watch *v1.ConfigMap: failed to list *v1.ConfigMap: configmaps "coredns" is forbidden: User "system:node:minikube" cannot list resource "configmaps" in API group "" in the namespace "kube-system": no relationship found between node 'minikube' and this object
````
Although the Kicbase image is running fine
```cmd
aman@aman-HP-Laptop-15g-br0xx:~$ docker ps
CONTAINER ID   IMAGE                                 COMMAND                  CREATED       STATUS          PORTS                                                                                                                                  NAMES
4582f7f3d9b0   gcr.io/k8s-minikube/kicbase:v0.0.30   "/usr/local/bin/entr…"   6 hours ago   Up 14 minutes   127.0.0.1:39887->22/tcp, 127.0.0.1:41395->2376/tcp, 127.0.0.1:45447->5000/tcp, 127.0.0.1:40909->8443/tcp, 127.0.0.1:34817->32443/tcp   minikube

```

### Attach the log file

The corresponding log file:
[logs.txt](https://github.com/kubernetes/minikube/files/8969059/logs.txt)

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment] 2022-06-23 22:01
Hi @AmanSarraf, thanks for reporting your issue with minikube.

I see that you're restarting an existing instance, if you clean out the existing instance (`minikube delete --all`) and then try starting minikube again fresh do you get a different error?

**Comment by AmanSarraf** [comment] 2022-06-24 02:16
I tried ```minikube logs --file=logs.txt``` but didn't helped 
LOG file :
[logs.txt](https://github.com/kubernetes/minikube/files/8972686/logs.txt)

**Comment by AmanSarraf** [comment] 2022-06-24 02:31
when I try running the docker kicbase image 
```cmd
aman@aman-HP-Laptop-15g-br0xx:~$ docker run docker.io/kicbase/stable:v0.0.32
+ userns=
+ grep -Eqv '0[[:space:]]+0[[:space:]]+4294967295' /proc/self/uid_map
+ validate_userns
+ [[ -z '' ]]
+ return
+ configure_containerd
+ local snapshotter=
+ [[ -n '' ]]
+ [[ -z '' ]]
++ stat -f -c %T /kind
+ '[[overlayfs' == zfs ']]'
/usr/local/bin/entrypoint: line 112: [[overlayfs: command not found
+ [[ -n '' ]]
+ configure_proxy
+ mkdir -p /etc/systemd/system.conf.d/
+ [[ ! -z '' ]]
+ cat
INFO: ensuring we can execute mount/umount even with userns-remap
+ fix_kmsg
+ [[ ! -e /dev/kmsg ]]
+ [[ -e /dev/console ]]
+ echo 'WARN: /dev/kmsg does not exist, nor does /dev/console!'
WARN: /dev/kmsg does not exist, nor does /dev/console!
+ fix_mount
+ echo 'INFO: ensuring we can execute mount/umount even with userns-remap'
++ which mount
++ which umount
+ chown root:root /usr/bin/mount /usr/bin/umount
++ which mount
++ which umount
+ chmod -s /usr/bin/mount /usr/bin/umount
INFO: remounting /sys read-only
+++ which mount
++ stat -f -c %T /usr/bin/mount
+ [[ overlayfs == \a\u\f\s ]]
+ echo 'INFO: remounting /sys read-only'
+ mount -o remount,ro /sys
mount: /sys: permission denied.
+ [[ -n '' ]]
+ exit 1
```

**Comment by afbjorklund** [comment] 2022-06-26 07:52
Same issue as #14202

**Comment by spowelljr** [comment] 2022-09-07 18:39
Hi @AmanSarraf, since this is a duplicate of https://github.com/kubernetes/minikube/issues/14202 I'm going to close this issue to centralize discussion, feel free to ask any follow up questions in https://github.com/kubernetes/minikube/issues/14202, thanks!

**Closed by spowelljr** 2022-09-07 18:39 UTC
Labels: kind/support, triage/duplicate
