### ISSUE TITLE
`node list` command not print all nodes.

### ISSUE THREAD

**Issue by daehyeok** [kubernetes/minikube#10069] opened 2020-12-30 23:28 UTC
`minikube node list` command only print nodes in default profile. It should print all nodes regardless of their profile.
Also, Implement additional argument to filter nodes by profile name will be good.

```
❯ minikube profile list
|--------------|-----------|---------|--------------|------|---------|---------|-------|
|   Profile    | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|--------------|-----------|---------|--------------|------|---------|---------|-------|
| minikube     | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Stopped |     2 |
| test-profile | docker    | docker  | 192.168.49.2 | 8443 | v1.20.0 | Running |     2 |
|--------------|-----------|---------|--------------|------|---------|---------|-------|
❗  Found 2 invalid profile(s) !
         test-profile-m02
         minikube-m02
💡  You can delete them using the following command(s):
         $ minikube delete -p test-profile-m02
         $ minikube delete -p minikube-m02
❯ minikube node list
minikube        192.168.49.2
minikube-m02    192.168.49.3
```

**Comment by tstromberg** [comment] 2021-01-06 18:37
I personally don't agree with this. Most commands are specific to a profile, by design. Will bring this up for discussion at the triage meeting today.

**Comment by medyagh** [comment] 2021-01-06 19:17
I think minikube is doing the right thing here, since -p is an implicit flag that is being passed,
what you are seeing is, the list for

```
minikube node list -p minikube
```

I dont think we should list nodes outside your cluster.

**Comment by medyagh** [comment] 2021-01-06 19:19
btw in the first part of the issue there is a bug that there is a WIP for that https://github.com/kubernetes/minikube/pull/9996

I am going to close this issue, please feel free to re-open if you have more quesitons.

**Closed by medyagh** 2021-01-06 19:19 UTC
Labels: kind/feature, priority/awaiting-more-evidence
