### ISSUE TITLE
minikube fail to start with custom apiserver-port option

### ISSUE THREAD

**Issue by Zikoel** [kubernetes/minikube#4170] opened 2019-04-29 10:42 UTC
# The exact command-lines used so that we can replicate the issue
minikube start --cpus 4 --memory 8192 --apiserver-port=8773 --extra-config=apiserver.service-node-port-range=80-30000
# The full output of the command that failed
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
2019/04/29 12:21:43 No matching credentials were found, falling back on anonymous
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
    ▪ apiserver.service-node-port-range=80-30000
💾  Downloading kubelet v1.14.0
💾  Downloading kubeadm v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health ..................................
💣  apiserver checks failed: Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>
Temporary Error: apiserver status=Stopped err=<nil>

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
# Which operating system version was used
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

# Comments
Seems that simply something doesn't switch to the new customized port

**Comment by tstromberg** [comment] 2019-04-30 23:07
Sorry to hear that you bumped into this. The good news is that this is already fixed in v1.0.1, which incorporates https://github.com/kubernetes/minikube/pull/4058

I tested your command-line, and it works great on Debian. I'm going to close this as obsolete, but please re-open it if it does end up that you are still having issues. Thanks for sharing your experience!

**Comment by tstromberg** [comment] 2019-04-30 23:07
Closing as dupe of #4057 (fixed in v1.0.1)

**Closed by tstromberg** 2019-04-30 23:07 UTC
