### ISSUE TITLE
Stuck at "Stating Cluster Components": failed to "StartContainer" for "etcd" with CrashLoopBackOff

### ISSUE THREAD

**Issue by Berndinox** [kubernetes/minikube#3117] opened 2018-09-05 16:44 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTSR
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): NONE
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): nothing displayed
- **Install tools**: minikube
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
**minikube version: v0.28.2**

**What happened**: Minikube starts once, after a reboot never again

i've tried:
minikube delete
rm -R ~/.kube && rm -R ~/.minikube
rm -R /etc/kubernetes

reinstall kubectl and minikube

**What you expected to happen**: Minikube starts

**How to reproduce it** (as minimally and precisely as possible): Setup Minikube stop & start again

**Output of `minikube logs` (if applicable)**:

**Minikube logs:**
```
Sep 05 18:38:10 anony kubelet[23737]: E0905 18:38:10.081417   23737 dns.go:131] Nameserver limits were exceeded, some nameservers have been omitted, the applied nameserver line is: 213.133.98.98 213.133.99.99 213.133.100.100
Sep 05 18:38:10 anony kubelet[23737]: I0905 18:38:10.081461   23737 kuberuntime_manager.go:757] checking backoff for container "etcd" in pod "etcd-minikube_kube-system(9a42d0c42e2b25c855d77283a7c800c4)"
Sep 05 18:38:10 anony kubelet[23737]: I0905 18:38:10.081588   23737 kuberuntime_manager.go:767] Back-off 20s restarting failed container=etcd pod=etcd-minikube_kube-system(9a42d0c42e2b25c855d77283a7c800c4)
Sep 05 18:38:10 anony kubelet[23737]: E0905 18:38:10.081622   23737 pod_workers.go:186] Error syncing pod 9a42d0c42e2b25c855d77283a7c800c4 ("etcd-minikube_kube-system(9a42d0c42e2b25c855d77283a7c800c4)"), skipping: failed to "StartContainer" for "etcd" with CrashLoopBackOff: "Back-off 20s restarting failed container=etcd pod=etcd-minikube_kube-system(9a42d0c42e2b25c855d77283a7c800c4)"
Sep 05 18:38:11 anony kubelet[23737]: E0905 18:38:11.024799   23737 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"minikube.15518e567438e052", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"minikube", UID:"minikube", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasNoDiskPressure", Message:"Node minikube status is now: NodeHasNoDiskPressure", Source:v1.EventSource{Component:"kubelet", Host:"minikube"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbedc1f7274594652, ext:225359028, loc:(*time.Location)(0x5b98020)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbedc1f7274594652, ext:225359028, loc:(*time.Location)(0x5b98020)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "minikube.15518e567438e052" is forbidden: not yet ready to handle request' (will not retry!)
Sep 05 18:38:11 anony kubelet[23737]: E0905 18:38:11.893155   23737 eviction_manager.go:246] eviction manager: failed to get get summary stats: failed to get node info: node "minikube" not found
Sep 05 18:38:12 anony kubelet[23737]: I0905 18:38:12.009430   23737 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
Sep 05 18:38:12 anony kubelet[23737]: I0905 18:38:12.012768   23737 kubelet_node_status.go:82] Attempting to register node minikube
Sep 05 18:38:21 anony kubelet[23737]: E0905 18:38:21.026290   23737 event.go:200] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"minikube.15518e567438c666", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"minikube", UID:"minikube", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"NodeHasSufficientDisk", Message:"Node minikube status is now: NodeHasSufficientDisk", Source:v1.EventSource{Component:"kubelet", Host:"minikube"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbedc1f7274592c66, ext:225352400, loc:(*time.Location)(0x5b98020)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbedc1f7274592c66, ext:225352400, loc:(*time.Location)(0x5b98020)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "minikube.15518e567438c666" is forbidden: not yet ready to handle request' (will not retry!)
Sep 05 18:38:21 anony kubelet[23737]: E0905 18:38:21.893366   23737 eviction_manager.go:246] eviction manager: failed to get get summary stats: failed to get node info: node "minikube" not found
Sep 05 18:38:22 anony kubelet[23737]: E0905 18:38:22.014879   23737 kubelet_node_status.go:106] Unable to register node "minikube" with API server: nodes "minikube" is forbidden: not yet ready to handle request
Sep 05 18:38:24 anony kubelet[23737]: I0905 18:38:24.776779   23737 kubelet_node_status.go:271] Setting node annotation to enable volume controller attach/detach
```

**docker logs etcd-conatinart:**
```
2018-09-05 16:43:31.378074 I | etcdmain: etcd Version: 3.1.12
2018-09-05 16:43:31.378110 I | etcdmain: Git SHA: 918698add
2018-09-05 16:43:31.378113 I | etcdmain: Go Version: go1.8.7
2018-09-05 16:43:31.378119 I | etcdmain: Go OS/Arch: linux/amd64
2018-09-05 16:43:31.378121 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
2018-09-05 16:43:31.378157 I | embed: peerTLS: cert = /var/lib/localkube/certs/etcd/peer.crt, key = /var/lib/localkube/certs/etcd/peer.key, ca = , trusted-ca = /var/lib/localkube/certs/etcd/ca.crt, client-cert-auth = true
2018-09-05 16:43:31.378163 W | embed: The scheme of peer url http://localhost:2380 is HTTP while peer key/cert files are presented. Ignored peer key/cert files.
2018-09-05 16:43:31.378175 W | embed: The scheme of peer url http://localhost:2380 is HTTP while client cert auth (--peer-client-cert-auth) is enabled. Ignored client cert auth for this url.
2018-09-05 16:43:31.379062 C | etcdmain: listen tcp 144.76.30.175:2380: bind: cannot assign requested address
```
I dont know where this IP cames from (144.76.30.175) - its not mine

**docker logs api-server:**
```
E0905 16:46:07.619587       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.Secret: the server was unable to return a response in the time allotted, but may still be processing the request (get secrets)
E0905 16:46:07.619761       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *rbac.ClusterRoleBinding: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterrolebindings.rbac.authorization.k8s.io)
E0905 16:46:07.621366       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1beta1.MutatingWebhookConfiguration: the server was unable to return a response in the time allotted, but may still be processing the request (get mutatingwebhookconfigurations.admissionregistration.k8s.io)
E0905 16:46:07.621658       1 reflector.go:205] k8s.io/kubernetes/vendor/k8s.io/client-go/informers/factory.go:87: Failed to list *v1.Endpoints: the server was unable to return a response in the time allotted, but may still be processing the request (get endpoints)
E0905 16:46:07.621747       1 reflector.go:205] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: Failed to list *core.LimitRange: the server was unable to return a response in the time allotted, but may still be processing the request (get limitranges)
E0905 16:46:08.600789       1 storage_rbac.go:157] unable to initialize clusterroles: the server was unable to return a response in the time allotted, but may still be processing the request (get clusterroles.rbac.authorization.k8s.io)
I0905 16:46:10.869297       1 trace.go:76] Trace[417805580]: "Patch /api/v1/namespaces/default/events/minikube.15518e567438d77c" (started: 2018-09-05 16:45:40.868766814 +0000 UTC m=+37.181122106) (total time: 30.000495907s):
Trace[417805580]: [30.000495907s] [30.000417682s] END
I0905 16:46:11.322725       1 trace.go:76] Trace[42170192]: "Create /api/v1/nodes" (started: 2018-09-05 16:46:01.322247095 +0000 UTC m=+57.634602352) (total time: 10.000440961s):
Trace[42170192]: [10.000440961s] [10.000308046s] END
I0905 16:46:18.601641       1 trace.go:76] Trace[2012631199]: "Create /api/v1/namespaces" (started: 2018-09-05 16:46:08.601223628 +0000 UTC m=+64.913578892) (total time: 10.000392238s):
Trace[2012631199]: [10.000392238s] [10.0003422s] END
E0905 16:46:18.602006       1 client_ca_hook.go:78] namespaces "kube-system" is forbidden: not yet ready to handle request
I0905 16:46:23.271376       1 naming_controller.go:280] Shutting down NamingConditionController
I0905 16:46:23.271422       1 controller.go:90] Shutting down OpenAPI AggregationController
```

**Anything else do we need to know**:
etcd and kube-apiserver container are restarting continously.

**Comment by tstromberg** [comment] 2018-09-18 21:07
What was the start command you used?

**Comment by tstromberg** [comment] 2018-09-19 01:45
Appears to be dupe of #2967

**Closed by tstromberg** 2018-09-19 01:45 UTC
Labels: area/product-excellence, driver/none, hung-start, more-info-needed, platform/linux
