### ISSUE TITLE
minikube fails from D:\: open minikube-v0.31.0.iso: The system cannot find the path specified.

### ISSUE THREAD

**Issue by AlanCarlyle** [kubernetes/minikube#3462] opened 2018-12-17 08:31 UTC
**Environment**:

**Minikube version**: 0.31.0
- **OS**: Win Pro 10
- **VM Driver**: hyperv
- **ISO version**: *The Issue is with this* - 
- **Install tools**: chocolate (using elevated privileges)

**What happened and how to (maybe) reproduce it**:

I was get a problem with minikube not resolving an IP address after starting and decided to uninstall everything to start again.
After uninstalling kubernetes-*cli and minikube with chocolate I rebooted my machine. I had to manually delete the VM instance from Hyper-V as the chocolate uninstall did not remove this.

I then used chocolate to reinstall the latest version of minikube and tried to start it and it failed. The minikube VM was there. 
After doing a ```minikube delete``` and then ```minikube start``` it downloaded the VM ISO.
When I then did a ```minikube start --vm-driver hyperv --hyperv-virtual-switch DockerNAT``` and got the following response;
```
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E1217 19:55:15.470643   12160 start.go:180] Error starting host: Error creating host: Error executing step: Creating VM.
: exit status 1.

 Retrying.
E1217 19:55:15.767287   12160 start.go:186] Error starting host:  Error creating host: Error executing step: Creating VM.
: exit status 1
``` 
A second time with just ```minikube star --vm-driver hyperv``` worked (though starting took some time).

**What you expected to happen**:

- Uninstalling with choco would completely uninstall with no additional work required. 

- Starting the first time after reinstalling using ```minikube start --vm-driver hyperv``` would install the VM with a default switch named something like ```minikube``` (I would only need to specify switch if I wanted something different.)

**Anything else that instant actually need-to-know**:

I would like to update the documentation to include an **Uninstall** section and **Reinstall** that notes the steps I mentioned above, yet I'm not confident that the issues I have encounter are just my fault or common to others.

Can someone please confirm the problems I have are not atypical? Or if they are suggest where I may have been going wrong. (Clarification in documentation would still be nice and I hope I can become competent enough to contribute.)

Also extending the chocolate Windows  installation/uninstall scripts to ***completely** uninstall would be useful. Though I understand that some may not actually want this behaviour.

Adding a nice progress indicator to ```minikube start``` would be a a nice-to-have though hardly essential. 

**Further research on problem**

Despite having create a minikube vm and got it running I was still unable to use it fully. It returned an IP6 address when I did ```minikube ip``` and refused with lots of errors to open ```minikube dashboard```. I looked as if kubernetes was not setup correctly?
I found this closed post https://github.com/kubernetes/minikube/issues/1012#issue-201297319 with a similar problems and the fix being;
```
rm -rf ~/.minikube
```
Deleting the entire minikube configuration and its resources. 

Now after doing minikube start once again I get this error;

```
Downloading Minikube ISO
 178.87 MB / 178.87 MB [============================================] 100.00% 0s
E1218 18:44:28.588155   12684 start.go:180] Error starting host: Error creating host: Error executing step: Creating VM.
: open /Users/Alan/.minikube/cache/iso/minikube-v0.31.0.iso: The system cannot find the path specified..

 Retrying.
E1218 18:44:28.590154   12684 start.go:186] Error starting host:  Error creating host: Error executing step: Creating VM.
: open /Users/Alan/.minikube/cache/iso/minikube-v0.31.0.iso: The system cannot find the path specified.
```

The problem might be caused by me having being on drive (D:\) rather than (C:\) as I notice the open statement above does not specify what drive to access.

**Comment by tstromberg** [comment] 2018-12-18 21:47
I agree with your observation: this does appear to be a drive letter issue.

**Comment by gbraad** [comment] 2019-01-20 21:44
You should try to have both the executable and other files hosted on
the same drive as Windows, C:. This is a 'known issue' and is
inherited from the use of libmachine.

On Mon, Jan 21, 2019 at 4:26 AM Oleh <notifications@github.com> wrote:
>
> I get this error as well with the version v0.33.1 and the default iso-file location
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.



-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by tstromberg** [comment] 2019-02-20 00:00
Dupe of #1574

**Closed by tstromberg** 2019-02-20 00:00 UTC
Labels: help wanted, kind/bug, os/windows, priority/backlog
