### ISSUE TITLE
💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by khanmaster** [kubernetes/minikube#6006] opened 2019-12-02 23:40 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment] 2019-12-16 20:52
This issue appears to be a duplicate of #5905, do you mind if we move the conversation there? This should have been fixed in minikube v1.6.0, so please try upgrading if you have not already.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-16 20:52 UTC
