### ISSUE TITLE
vpn: Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by jgillscsco** [kubernetes/minikube#4532] opened 2019-06-19 20:08 UTC
configuring environment for Kubernetes v1.14.3 on Docker 18.09.6

Relaunching Kubernetes v1.14.3 using kubeadm ... 

 Error restarting cluster: waiting for apiserver: timed out waiting for the condition

 Sorry that minikube crashed.

**Comment by medyagh** [comment] 2019-06-19 23:07
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by jgillscsco** [comment] 2019-06-19 23:40
Hi,
I started re-installing minikube.  But at very initial stage I get connection refused when I run kubectl version as below....

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
**The connection to the server localhost:8080 was refused - did you specify the right host or port?**

**Comment by jgillscsco** [comment] 2019-06-19 23:53
Here are minikube logs 
--------------------------------------------

[  +5.000364] hpet1: lost 318 rtc interrupts
[  +5.001820] hpet1: lost 318 rtc interrupts
[  +5.001317] hpet1: lost 318 rtc interrupts
[Jun19 23:50] hpet1: lost 318 rtc interrupts
[  +5.000617] hpet1: lost 318 rtc interrupts
[  +5.002050] hpet1: lost 318 rtc interrupts
[  +5.001780] hpet1: lost 319 rtc interrupts
[  +5.000871] hpet1: lost 318 rtc interrupts
[  +5.003539] hpet1: lost 318 rtc interrupts

==> kernel <==
 23:50:27 up 31 min,  0 users,  load average: 0.07, 0.07, 0.11
Linux minikube 4.15.0 #1 SMP Thu Jun 6 15:07:18 PDT 2019 x86_64 GNU/Linux

==> kube-addon-manager <==
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:42:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:43:47+00:00 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
error: no objects passed to apply
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:43:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:44:47+00:00 ==
INFO: == Reconciling with deprecated label ==
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:44:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:45:47+00:00 ==
INFO: == Reconciling with deprecated label ==
error: no objects passed to apply
error: no objects passed to apply
error: no objects passed to apply
error: no objects passed to apply
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:45:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:46:47+00:00 ==
INFO: == Reconciling with deprecated label ==
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:46:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:47:47+00:00 ==
INFO: == Reconciling with deprecated label ==
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:47:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:48:47+00:00 ==
INFO: == Reconciling with deprecated label ==
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:48:49+00:00 ==
INFO: Leader is minikube
INFO: == Kubernetes addon ensure completed at 2019-06-19T23:49:47+00:00 ==
INFO: == Reconciling with deprecated label ==
INFO: == Reconciling with addon-manager label ==
serviceaccount/storage-provisioner unchanged
INFO: == Kubernetes addon reconcile completed at 2019-06-19T23:49:48+00:00 ==

==> kube-apiserver <==
I0619 23:20:37.814043       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:clusterrole-aggregation-controller
I0619 23:20:37.852386       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:cronjob-controller
I0619 23:20:37.898184       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:daemon-set-controller
I0619 23:20:37.942968       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:deployment-controller
I0619 23:20:37.975386       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:disruption-controller
I0619 23:20:38.013713       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:endpoint-controller
I0619 23:20:38.054129       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:expand-controller
I0619 23:20:38.094792       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:generic-garbage-collector
I0619 23:20:38.134518       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:horizontal-pod-autoscaler
I0619 23:20:38.173573       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:job-controller
I0619 23:20:38.212393       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:namespace-controller
I0619 23:20:38.252126       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:node-controller
I0619 23:20:38.292285       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:persistent-volume-binder
I0619 23:20:38.333323       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:pod-garbage-collector
I0619 23:20:38.372956       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:replicaset-controller
I0619 23:20:38.415782       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:replication-controller
I0619 23:20:38.454992       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:resourcequota-controller
I0619 23:20:38.504935       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:route-controller
I0619 23:20:38.533716       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:service-account-controller
I0619 23:20:38.574775       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:service-controller
I0619 23:20:38.613300       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:statefulset-controller
I0619 23:20:38.653978       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:ttl-controller
I0619 23:20:38.693964       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:certificate-controller
I0619 23:20:38.735288       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:pvc-protection-controller
I0619 23:20:38.773683       1 storage_rbac.go:223] created clusterrolebinding.rbac.authorization.k8s.io/system:controller:pv-protection-controller
I0619 23:20:38.810240       1 controller.go:606] quota admission added evaluator for: roles.rbac.authorization.k8s.io
I0619 23:20:38.814240       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/extension-apiserver-authentication-reader in kube-system
I0619 23:20:38.852597       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-system
I0619 23:20:38.892499       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system:controller:cloud-provider in kube-system
I0619 23:20:38.933836       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system:controller:token-cleaner in kube-system
I0619 23:20:38.973282       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager in kube-system
I0619 23:20:39.012938       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler in kube-system
I0619 23:20:39.039335       1 controller.go:606] quota admission added evaluator for: endpoints
I0619 23:20:39.055676       1 storage_rbac.go:254] created role.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
I0619 23:20:39.092109       1 controller.go:606] quota admission added evaluator for: rolebindings.rbac.authorization.k8s.io
I0619 23:20:39.097616       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system::extension-apiserver-authentication-reader in kube-system
I0619 23:20:39.134149       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system::leader-locking-kube-controller-manager in kube-system
I0619 23:20:39.172736       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system::leader-locking-kube-scheduler in kube-system
I0619 23:20:39.214133       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-system
I0619 23:20:39.252956       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system:controller:cloud-provider in kube-system
I0619 23:20:39.293079       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system:controller:token-cleaner in kube-system
I0619 23:20:39.335525       1 storage_rbac.go:284] created rolebinding.rbac.authorization.k8s.io/system:controller:bootstrap-signer in kube-public
W0619 23:20:39.364434       1 lease.go:222] Resetting endpoints for master service "kubernetes" to [192.168.99.101]
I0619 23:20:40.566588       1 controller.go:606] quota admission added evaluator for: serviceaccounts
I0619 23:20:40.909801       1 controller.go:606] quota admission added evaluator for: deployments.apps
I0619 23:20:41.049420       1 controller.go:606] quota admission added evaluator for: namespaces
I0619 23:20:41.109983       1 controller.go:606] quota admission added evaluator for: daemonsets.apps
I0619 23:20:46.898728       1 controller.go:606] quota admission added evaluator for: replicasets.apps
I0619 23:20:47.467977       1 controller.go:606] quota admission added evaluator for: controllerrevisions.apps
E0619 23:40:00.381356       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted

==> kube-proxy <==
W0619 23:20:48.409973       1 server_others.go:267] Flag proxy-mode="" unknown, assuming iptables proxy
I0619 23:20:48.422856       1 server_others.go:146] Using iptables Proxier.
W0619 23:20:48.423153       1 proxier.go:319] clusterCIDR not specified, unable to distinguish between internal and external traffic
I0619 23:20:48.423486       1 server.go:562] Version: v1.14.3
I0619 23:20:48.433866       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_max' to 131072
I0619 23:20:48.433970       1 conntrack.go:52] Setting nf_conntrack_max to 131072
I0619 23:20:48.434489       1 conntrack.go:83] Setting conntrack hashsize to 32768
I0619 23:20:48.440077       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_established' to 86400
I0619 23:20:48.440380       1 conntrack.go:100] Set sysctl 'net/netfilter/nf_conntrack_tcp_timeout_close_wait' to 3600
I0619 23:20:48.440885       1 config.go:102] Starting endpoints config controller
I0619 23:20:48.440933       1 controller_utils.go:1027] Waiting for caches to sync for endpoints config controller
I0619 23:20:48.440949       1 config.go:202] Starting service config controller
I0619 23:20:48.440959       1 controller_utils.go:1027] Waiting for caches to sync for service config controller
I0619 23:20:48.544750       1 controller_utils.go:1034] Caches are synced for endpoints config controller
I0619 23:20:48.544816       1 controller_utils.go:1034] Caches are synced for service config controller

==> kube-scheduler <==
I0619 23:20:31.721481       1 serving.go:319] Generated self-signed cert in-memory
W0619 23:20:32.225551       1 authentication.go:249] No authentication-kubeconfig provided in order to lookup client-ca-file in configmap/extension-apiserver-authentication in kube-system, so client certificate authentication won't work.
W0619 23:20:32.225588       1 authentication.go:252] No authentication-kubeconfig provided in order to lookup requestheader-client-ca-file in configmap/extension-apiserver-authentication in kube-system, so request-header client certificate authentication won't work.
W0619 23:20:32.225604       1 authorization.go:146] No authorization-kubeconfig provided, so SubjectAccessReview of authorization tokens won't work.
I0619 23:20:32.228073       1 server.go:142] Version: v1.14.3
I0619 23:20:32.228128       1 defaults.go:87] TaintNodesByCondition is enabled, PodToleratesNodeTaints predicate is mandatory
W0619 23:20:32.230049       1 authorization.go:47] Authorization is disabled
W0619 23:20:32.230072       1 authentication.go:55] Authentication is disabled
I0619 23:20:32.230081       1 deprecated_insecure_serving.go:49] Serving healthz insecurely on [::]:10251
I0619 23:20:32.230610       1 secure_serving.go:116] Serving securely on 127.0.0.1:10259
E0619 23:20:36.043044       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E0619 23:20:36.065917       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:kube-scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope
E0619 23:20:36.066229       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E0619 23:20:36.066430       1 reflector.go:126] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:223: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list resource "pods" in API group "" at the cluster scope
E0619 23:20:36.066626       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
E0619 23:20:36.084105       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list resource "services" in API group "" at the cluster scope
E0619 23:20:36.084439       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope
E0619 23:20:36.084644       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:kube-scheduler" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E0619 23:20:36.091761       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list resource "nodes" in API group "" at the cluster scope
E0619 23:20:36.092304       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
E0619 23:20:37.044622       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumes" in API group "" at the cluster scope
E0619 23:20:37.067540       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicaSet: replicasets.apps is forbidden: User "system:kube-scheduler" cannot list resource "replicasets" in API group "apps" at the cluster scope
E0619 23:20:37.072884       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:kube-scheduler" cannot list resource "storageclasses" in API group "storage.k8s.io" at the cluster scope
E0619 23:20:37.078111       1 reflector.go:126] k8s.io/kubernetes/cmd/kube-scheduler/app/server.go:223: Failed to list *v1.Pod: pods is forbidden: User "system:kube-scheduler" cannot list resource "pods" in API group "" at the cluster scope
E0619 23:20:37.081093       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:kube-scheduler" cannot list resource "persistentvolumeclaims" in API group "" at the cluster scope
E0619 23:20:37.085799       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Service: services is forbidden: User "system:kube-scheduler" cannot list resource "services" in API group "" at the cluster scope
E0619 23:20:37.087665       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.ReplicationController: replicationcontrollers is forbidden: User "system:kube-scheduler" cannot list resource "replicationcontrollers" in API group "" at the cluster scope
E0619 23:20:37.089136       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.StatefulSet: statefulsets.apps is forbidden: User "system:kube-scheduler" cannot list resource "statefulsets" in API group "apps" at the cluster scope
E0619 23:20:37.093089       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1.Node: nodes is forbidden: User "system:kube-scheduler" cannot list resource "nodes" in API group "" at the cluster scope
E0619 23:20:37.096018       1 reflector.go:126] k8s.io/client-go/informers/factory.go:133: Failed to list *v1beta1.PodDisruptionBudget: poddisruptionbudgets.policy is forbidden: User "system:kube-scheduler" cannot list resource "poddisruptionbudgets" in API group "policy" at the cluster scope
I0619 23:20:38.934100       1 controller_utils.go:1027] Waiting for caches to sync for scheduler controller
I0619 23:20:39.034777       1 controller_utils.go:1034] Caches are synced for scheduler controller
I0619 23:20:39.034918       1 leaderelection.go:217] attempting to acquire leader lease  kube-system/kube-scheduler...
I0619 23:20:39.042663       1 leaderelection.go:227] successfully acquired lease kube-system/kube-scheduler

==> kubelet <==
-- Logs begin at Wed 2019-06-19 23:19:19 UTC, end at Wed 2019-06-19 23:50:27 UTC. --
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.223657    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.324437    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.425524    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.526442    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.626592    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.727057    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.827383    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:34 minikube kubelet[3223]: E0619 23:20:34.927589    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.027865    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.128320    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.228892    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.329673    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.430447    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.530687    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.631041    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.731516    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.831882    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:35 minikube kubelet[3223]: E0619 23:20:35.932279    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:36 minikube kubelet[3223]: E0619 23:20:36.032985    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:36 minikube kubelet[3223]: E0619 23:20:36.103244    3223 controller.go:194] failed to get node "minikube" when trying to set owner ref to the node lease: nodes "minikube" not found
Jun 19 23:20:36 minikube kubelet[3223]: I0619 23:20:36.133237    3223 reconciler.go:154] Reconciler: start to sync state
Jun 19 23:20:36 minikube kubelet[3223]: E0619 23:20:36.133622    3223 kubelet.go:2244] node "minikube" not found
Jun 19 23:20:36 minikube kubelet[3223]: E0619 23:20:36.144571    3223 event.go:191] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"minikube.15a9bce2fe5ee40c", GenerateName:"", Namespace:"default", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Node", Namespace:"", Name:"minikube", UID:"minikube", APIVersion:"", ResourceVersion:"", FieldPath:""}, Reason:"Starting", Message:"Starting kubelet.", Source:v1.EventSource{Component:"kubelet", Host:"minikube"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf3aceaf3a398c0c, ext:155885940, loc:(*time.Location)(0x801e900)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf3aceaf3a398c0c, ext:155885940, loc:(*time.Location)(0x801e900)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'namespaces "default" not found' (will not retry!)

**Comment by medyagh** [comment] 2019-06-20 00:14
I am curious are you using a vpn ?

**Comment by jgillscsco** [comment] 2019-06-20 00:15
Yes, I'm using VPN

**Comment by jgillscsco** [comment] 2019-06-20 00:32
After I execute this command - 
$ **minikube status**
host: Running
kubelet: Running
**apiserver: Stopped**
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.101

**Comment by Alsharah07** [comment] 2019-06-28 23:45
$ docker version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?


I'm getting this error, please help me resolving the error.

**Comment by tstromberg** [comment] 2019-07-17 03:45
This may be a case where the way the VPN is configured prevents you from routing packets to the VM. If you don't mind, please try minikube v1.2.0 with the VPN disabled, and run `minikube delete` first. Let me know what the result is.

Thanks for the report!

**Comment by medyagh** [comment] 2019-07-25 18:28
I guess we could provide a better solution message, for people who have a super restrictive VPN that forces them to send local traffic to vpn !

**Comment by tstromberg** [comment] 2019-09-20 04:39
Dupe of #4302

**Closed by tstromberg** 2019-09-20 04:39 UTC
Labels: cause/firewall-or-proxy, ev/apiserver-timeout, needs-solution-message, priority/backlog
