### ISSUE TITLE
minikube cant start cluster

### ISSUE THREAD

**Issue by maxwang2100** [kubernetes/minikube#4728] opened 2019-07-10 09:39 UTC
sudo minikube start -p myMinikubeNoneVm --vm-driver=none
😄  minikube v1.2.0 on linux (amd64)
🏃  Re-using the currently running none VM for "myMinikubeNoneVm" ...
⌛  Waiting for SSH access ...
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: running command: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: exit status 1

**Comment by tstromberg** [comment] 2019-07-16 20:42
This issue appears to be a duplicate of #4742, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed by tstromberg** 2019-07-16 20:42 UTC
Labels: co/none-driver
