### ISSUE TITLE
minikube 1.14.2 on MS Win 10/docker driver fails to start up

### ISSUE THREAD

**Issue by dzilbermanvmw** [kubernetes/minikube#9584] opened 2020-10-29 19:10 UTC
**Steps to reproduce the issue:** 

1. Installed & validated Docker desktop on Win 10:
 Server: Docker Engine - Community
 Engine:
  **Version:          19.03.13
  API version:      1.40 (minimum version 1.12)**
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

2.  initialized new minikube instance using command:

**minikube start --kubernetes-version=v1.19.2**
* minikube v1.14.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
  - MINIKUBE_HOME=C:\Temp\minikubevms
* Automatically selected the docker driver. Other choices: hyperv, virtualbox
.......
3. minukube fails to start with the error:

* Preparing Kubernetes v1.19.2 on Docker 19.03.8 ...
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
* Enabled addons: storage-provisioner

X **Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.2**

**Full output of failed command:** 

See attached detailed output, the exception appears to be:

**W1029 12:08:58.068570   37088 api_server.go:117] api server version match failed: server version: the server has asked for the client to provide credentials**

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by dzilbermanvmw** [comment] 2020-10-29 19:10
[minikube_startup_error_details.txt](https://github.com/kubernetes/minikube/files/5460728/minikube_startup_error_details.txt)

**Comment by dzilbermanvmw** [comment] 2020-10-30 18:00
FYI, on another Win 10 docker-desktop host I was able to start up minkube with ...--driver=docker and had both K8s clusters - **docker-desktop** and **minikibe** running on Docker platform. 

in work laptop environment however I keep getting the same minikube startup exceptions:

 Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
* Enabled addons: storage-provisioner

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.2

**Comment by dzilbermanvmw** [comment] 2020-11-02 20:30
[minikube_docker-ce_startup-error-details.log](https://github.com/kubernetes/minikube/files/5477857/minikube_docker-ce_startup-error-details.log)
Re-installed Docker Desktop /Win 10, confirmed ability to run KIND K8s cluster but minikube one still fails to start up, exception:
----------------------------------------------------------------------------------------------------------------------------------------
Line 319: * E1102 20:20:34.118303       1 authentication.go:53] Unable to authenticate the request due to an error: x509: certificate has expired or is not yet valid: current time 2020-11-02T20:20:34Z is after 2020-06-24T18:57:35Z
	Line 408: * E1102 20:16:35.757006       1 daemon_controller.go:320] kube-system/kube-proxy failed with : error storing status for daemon set &v1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-proxy", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy", UID:"49b81f4b-8078-4416-bf86-40982f05711f", ResourceVersion:"217", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63739944989, loc:(*time.Location)(0x6a59c80)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-proxy"}, Annotations:map[string]string{"deprecated.daemonset.template.generation":"1"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubeadm", Operation:"Update", APIVersion:"apps/v1", Time:(*v1.Time)(0xc00149cf20), FieldsType:"FieldsV1", FieldsV1:(...
	Line 411: * E1102 20:16:35.775553       1 daemon_controller.go:320] kube-system/kube-proxy failed with : error storing status for daemon set &v1.DaemonSet{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"kube-proxy", GenerateName:"", Namespace:"kube-system", SelfLink:"/apis/apps/v1/namespaces/kube-system/daemonsets/kube-proxy", UID:"49b81f4b-8078-4416-bf86-40982f05711f", ResourceVersion:"347", Generation:1, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:63739944989, loc:(*time.Location)(0x6a59c80)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"k8s-app":"kube-proxy"}, Annotations:map[string]string{"deprecated.daemonset.template.generation":"1"}, OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry{v1.ManagedFieldsEntry{Manager:"kubeadm", Operation:"Update", APIVersion:"apps/v1", Time:(*v1.Time)(0xc0017befc0), FieldsType:"FieldsV1", FieldsV1:(...
	Line 422: * W1102 20:16:36.549563       1 proxier.go:639] Failed to read file /lib/modules/4.19.128-microsoft-standard/modules.builtin with error open /lib/modules/4.19.128-microsoft-standard/modules.builtin: no such file or directory. You can ignore this message when kube-proxy is running inside container without mounting /lib/modules
--------------
Full log attached FYI.

**Comment by dzilbermanvmw** [comment] 2020-11-03 18:18
FYI, I was able to get minikube start with --driver=docker on another Win 10 Docker CE environment, but on the one I filed for keep getting startup error:
...
! Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.19.2
* Verifying Kubernetes components...
! Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
* Enabled addons: storage-provisioner

X Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.19.2

**Comment by sharifelgamal** [comment] 2021-01-27 19:35
Sorry it took us so long to get back to you on this, that shouldn't happen.

The default-storageclass error is mostly a red herring, minikube doesn't need all of its addons to start to start up successfully itself. The `Error listing StorageClasses: Unauthorized` is curious though, it makes me think that something is corrupted in your kubernetes cluster. Like maybe you had an old minikube cluster lying around and it now it can't upgrade?

The best way to check that would be to run a `minikube delete --all` then try starting up again.

**Comment by spowelljr** [comment] 2021-02-18 22:13
The `certificate has expired or is not yet valid` error you got might be related to #8943.

**Comment by medyagh** [comment] 2021-03-24 18:50
this does sound like dupe of this https://github.com/kubernetes/minikube/issues/8943

@dzilbermanvmw I am curious does your machine have a misconfigured time ? 
I am certain this would be fixed by minikube delete --all --purge 
but we still need to find a fix for this so minikube auto-refreshes the certs if they are expired https://github.com/kubernetes/minikube/issues/8943

**Closed by medyagh** 2021-03-24 18:50 UTC
Labels: co/docker-driver, kind/support, os/windows, priority/awaiting-more-evidence
