### ISSUE TITLE
Error starting cluster: kubeadm init error (Process exited with status 1, no root cause)

### ISSUE THREAD

**Issue by lhui8023** [kubernetes/minikube#3038] opened 2018-08-02 07:05 UTC
macOS 10.13.6
VirtualBox-5.2.16-123759-OSX
minikube:v0.28.2

[localhost:v1.10.0 leihui$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
### Setting up kubeconfig...
Starting cluster components...
E0802 14:11:33.136236     886 start.go:300] Error starting cluster:  kubeadm init error 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:

**Comment by erickpearson** [comment] 2018-08-08 22:48
I'm getting the same exact error message on same minikube version, although I'm using hyperkit v0.20171204-60-g0e5b6b

I haven't dug too deep yet, did you find anyway to get your local cluster started?

**Comment by lhui8023** [comment] 2018-08-09 03:25
@erickpearson 
$minikube stop
$minikube delete && rm -rf ~/.minikube
$minikube start --vm-driver=hyperkit --bootstrapper=localkube
retry

**Comment by erickpearson** [comment] 2018-08-09 16:00
@lhui8023  running the localkube bootstrapper worked.  However it does suggest that this is deprecated and consider moving to kubeadm bootstrapper which is what was having trouble initializing.  Thanks for the help, I'll work with this for now.

**Comment by redbearder** [comment] 2018-08-21 03:33
@erickpearson @lhui8023 I have same issue with you, although I have fix that with same solution but I want to know the root cause and have a long term solution about that

**Comment by rfc1459** [comment] 2018-08-21 09:25
After a round of git bisect between v0.28.0 (good) and v0.28.2 (bad), it seems that 81440fe broke k8s 1.10 deployments. k8s 1.11 works fine.

Host environment:
* OS: Ubuntu 18.04
* Hypervisor: VirtualBox 5.2.18-124319
* Behind corporate proxy (if that makes any difference)

**Comment by fabiand** [comment] 2018-08-27 10:42
Using minikube v0.28.0 with Ubuntu Xenial 16.04, non driver and K8s 1.10 or 1.11 does not work form me.

**Comment by fabiand** [comment] 2018-08-29 14:34
There seem to be some deprectaion warnings in the kubelet.

**Comment by tstromberg** [comment] 2018-09-20 17:09
closing as a dupe of #3038

**Closed by tstromberg** 2018-09-20 17:09 UTC
Labels: bootstrapper/kubeadm, drv/virtualbox, failed/kubeadm, kind/bug, os/macos, top5

**Comment by fabiand** [comment] 2018-09-20 18:46
@tstromberg dupe of itself?

I'm not sure what now the correct bug to follow is

**Comment by tstromberg** [comment] 2018-09-20 22:53
@fabiand - Whoops. Thanks for catching my mistake. #2493 is the issue I've duped this one against.

**Comment by haf** [comment] 2019-01-30 15:06
This is not a duplicate, because the error message ` unable to load bootstrap kubeconfig` does not exist in #2493 but it exists in this issue.
