### ISSUE TITLE
minikube 0.28.0 fails starting cluster

### ISSUE THREAD

**Issue by lutingrong** [kubernetes/minikube#2964] opened 2018-07-05 15:48 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
this is a BUG REPORT

Please provide the following details:

**Environment**:

$ minikube version
minikube version: v0.28.0

$ cat /etc/os-release
NAME="Ubuntu"
VERSION="18.04 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ grep DriverName ~/.minikube/machines/minikube/config.json
    "DriverName": "virtualbox",

$ grep -i ISO ~/.minikube/machines/minikube/config.json
        "Boot2DockerURL": "file:///home/l/.minikube/cache/iso/minikube-v0.28.0.iso",

**What happened**:

$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0705 23:00:45.064289    6250 start.go:294] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
.: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
    minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 

**What you expected to happen**:

minikube start without error

**How to reproduce it** (as minimally and precisely as possible):

$ minikube start

**Output of `minikube logs` (if applicable)**:

Jul 05 15:45:50 minikube kubelet[2706]: E0705 15:45:50.096693    2706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.99.100:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
Jul 05 15:45:51 minikube kubelet[2706]: E0705 15:45:51.095345    2706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://192.168.99.100:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
Jul 05 15:45:51 minikube kubelet[2706]: E0705 15:45:51.096568    2706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460: Failed to list *v1.Node: Get https://192.168.99.100:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused
Jul 05 15:45:51 minikube kubelet[2706]: E0705 15:45:51.097517    2706 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Service: Get https://192.168.99.100:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 192.168.99.100:8443: getsockopt: connection refused

**Anything else do we need to know**:

**Comment by lutingrong** [comment] 2018-07-05 16:04
$ minikube status
minikube: Running
cluster: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100

$ minikube dashboard
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting service kubernetes-dashboard: Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboard: dial tcp 192.168.99.100:8443: getsockopt: connection refused

$ kubectl get pods
The connection to the server 192.168.99.100:8443 was refused - did you specify the right host or port?

**Comment by mkrou** [comment] 2018-07-06 10:35
the same problem. Minikube 0.28. OSX 10.13.5

**Comment by orangebook** [comment] 2018-07-08 03:40
```
minikube delete
```
and try again

**Comment by victorpaulo** [comment] 2018-07-09 12:52
The same problem. 
**Minikube 0.28. OSX 10.13.5**
I've tried to "_minikube delete_" and also increasing memory but the no success at all. Any idea so far?

**Comment by lutingrong** [comment] 2018-07-09 14:38
Reinstalling minikube seems resolved this issue.

**Comment by tstromberg** [comment] 2018-09-19 01:49
Dupe of #3038

**Closed by tstromberg** 2018-09-19 01:49 UTC
Labels: drivers/virtualbox/linux, failed-start/networking, platform/linux
