### ISSUE TITLE
minikube start:  Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework

### ISSUE THREAD

**Issue by kgiroux** [kubernetes/minikube#5869] opened 2019-11-08 07:34 UTC
**The exact command to reproduce the issue**:

Minikube was installed with the following tutorial : 

https://kubernetes.io/fr/docs/tasks/tools/install-minikube/

minikube start --vm-driver=hyperkit

**The full output of the command that failed**:<details>

Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔥  Deleting "minikube" in hyperkit ...

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

</details>

**The output of the `minikube logs` command**:<details>
minikube logs

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
MACOS 10.15.1

**Comment by priyawadhwa** [comment] 2019-11-11 17:39
Hey @kgiroux thanks for opening this issue. This issue appears to be a duplicate of #5594, do you mind if we move the conversation there?

This way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by priyawadhwa** 2019-11-11 17:39 UTC
