### ISSUE TITLE
unexpected EOF when launching from systemd unit

### ISSUE THREAD

**Issue by goblain** [kubernetes/minikube#285] opened 2016-07-07 11:38 UTC
for a reason I do not fully comprehend I get EOF issue when launching minikube via systemd unit
```
[Service]
ExecStart       = /usr/local/bin/minikube start --vm-driver=kvm --cpus=4 --memory=10240
RemainAfterExit = true
```
```
Jul 07 12:25:33 warp systemd[1]: Starting minikube.service...
Jul 07 12:25:33 warp systemd[1]: Started minikube.service.
Jul 07 12:25:34 warp minikube[26641]: Starting local Kubernetes cluster...
Jul 07 12:25:34 warp minikube[26641]: E0707 12:25:34.040437   26641 start.go:70] Error starting host:  Error getting state for host: unexpected EOF
Jul 07 12:25:34 warp systemd[1]: minikube.service: main process exited, code=exited, status=1/FAILURE
Jul 07 12:26:16 warp systemd[1]: Stopping minikube.service...
Jul 07 12:26:16 warp systemd[1]: Unit minikube.service entered failed state. 
```
when launched by hand, everything starts up as expected

**Comment by jimmidyson** [comment] 2016-07-07 14:30
Does the libvirt socket exist (IIRC it should be `/var/run/libvirt/libvirt-sock`) & does the user have access to the socket (added to libvirtd group I think)?

**Comment by dlorenc** [comment] 2016-07-07 15:10
You might want to try adding a `User = $YOURUSERNAME` line to the Unit to make sure it runs as you.

**Comment by jimmidyson** [comment] 2016-07-07 15:39
Out of interest, it's a bit unusual to run it as a systemd unit rather than an interactive command. Can I just ask your reasoning behind running it under systemd?

**Comment by dlorenc** [comment] 2016-07-26 15:28
I think this is basically a duplicate of #278, where we need to add better error handling to the kvm driver.

**Closed by dlorenc** 2016-07-26 15:28 UTC
Labels: kind/support

**Comment by goblain** [comment] 2016-08-03 07:53
@jimmidyson the idea was to launch it on dev systems as a service so you don't need to bother with thinking about bringing it up etc. but I actually went around it for now by using full k8s deployment
