### ISSUE TITLE
kubectl: Unable to connect to the server: dial tcp i/o timeout

### ISSUE THREAD

**Issue by norbert-yoimo** [kubernetes/minikube#1234] opened 2017-03-10 11:36 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Minikube version** (use `minikube version`): minikube version: v0.17.1
**Environment**:
- **OS** (e.g. from /etc/os-release): Arch linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v1.0.7.iso
- **Install tools**:
- **Others**:

**What happened**:
`$ ./minikube-linux-amd64 start`
```
Starting local Kubernetes cluster...
Starting VM...
SSH-ing files into VM...
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
```
`$ kubectl get pods`
```
Unable to connect to the server: dial tcp 192.168.99.100:8443: i/o timeout
```
**What you expected to happen**:
Get an empty list of pods

**How to reproduce it** (as minimally and precisely as possible):

**Anything else do we need to know**:
Output of `minikube ssh systemctl status localkube`:

```
● localkube.service - Localkube
   Loaded: loaded (/lib/systemd/system/localkube.service; enabled; vendor preset: enabled)
   Active: active (running) since Mon 2017-03-06 14:09:08 UTC; 14min ago
     Docs: https://github.com/kubernetes/minikube/tree/master/pkg/localkube
 Main PID: 3271 (localkube)
    Tasks: 16 (limit: 4915)
   Memory: 141.8M
      CPU: 1min 54.669s
   CGroup: /system.slice/localkube.service
           ├─3271 /usr/local/bin/localkube --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.100 --apiserver-name=minikubeCA
           └─3350 journalctl -k -f

Mar 06 14:19:12 minikube localkube[3271]: I0306 14:19:12.296016    3271 replication_controller.go:322] Observed updated replication controller kubernetes-dashboard. Desired pod count change: 1->1
Mar 06 14:19:12 minikube localkube[3271]: I0306 14:19:12.296150    3271 replication_controller.go:322] Observed updated replication controller kube-dns-v20. Desired pod count change: 1->1
Mar 06 14:19:17 minikube localkube[3271]: I0306 14:19:17.895294    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
Mar 06 14:20:30 minikube localkube[3271]: I0306 14:20:30.883835    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/836b1214-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "836b1214-0276-11e7-9885-0800272e2447" (UID: "836b1214-0276-11e7-9885-0800272e2447").
Mar 06 14:20:47 minikube localkube[3271]: I0306 14:20:47.820727    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
Mar 06 14:21:02 minikube localkube[3271]: apply entries took too long [11.765144ms for 1 entries]
Mar 06 14:21:02 minikube localkube[3271]: avoid queries with large range/delete range!
Mar 06 14:21:09 minikube localkube[3271]: E0306 14:21:09.826764    3271 repair.go:132] the node port 30000 for service kubernetes-dashboard/kube-system is not allocated; repairing
Mar 06 14:21:57 minikube localkube[3271]: I0306 14:21:57.895042    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/836b1214-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "836b1214-0276-11e7-9885-0800272e2447" (UID: "836b1214-0276-11e7-9885-0800272e2447").
Mar 06 14:21:58 minikube localkube[3271]: I0306 14:21:58.899802    3271 operation_executor.go:917] MountVolume.SetUp succeeded for volume "kubernetes.io/secret/8357ed5c-0276-11e7-9885-0800272e2447-default-token-77nfr" (spec.Name: "default-token-77nfr") pod "8357ed5c-0276-11e7-9885-0800272e2447" (UID: "8357ed5c-0276-11e7-9885-0800272e2447").
```

If I SSH in, I can see that there is 1 failed systemd unit, no idea if it matters or not:

```
$ systemctl status systemd-networkd-wait-online.service
● systemd-networkd-wait-online.service - Wait for Network to be Configured
   Loaded: loaded (/lib/systemd/system/systemd-networkd-wait-online.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-03-06 14:09:08 UTC; 18min ago
     Docs: man:systemd-networkd-wait-online.service(8)
  Process: 3241 ExecStart=/lib/systemd/systemd-networkd-wait-online (code=exited, status=1/FAILURE)
 Main PID: 3241 (code=exited, status=1/FAILURE)

Mar 06 14:07:08 minikube systemd[1]: Starting Wait for Network to be Configured...
Mar 06 14:07:08 minikube systemd-networkd-wait-online[3241]: ignoring: lo
Mar 06 14:09:08 minikube systemd[1]: systemd-networkd-wait-online.service: Main process exited, code=exited, status=1/FAILURE
Mar 06 14:09:08 minikube systemd[1]: Failed to start Wait for Network to be Configured.
Mar 06 14:09:08 minikube systemd[1]: systemd-networkd-wait-online.service: Unit entered failed state.
Mar 06 14:09:08 minikube systemd[1]: systemd-networkd-wait-online.service: Failed with result 'exit-code'.
```

**Comment by donspaulding** [comment] 2017-03-13 20:08
@norbert-yoimo I think I'm seeing a similar issue to you.  Is the kube API server flapping up and down?  I mean, are you able to run `kubectl get pods` at some times, and then within a few seconds, it returns the `dial tcp` error?

**Comment by norbert-yoimo** [comment] 2017-03-14 10:49
I just tried a few times, but I could never get it to connect.

**Comment by aaron-prindle** [comment] 2017-03-16 17:49
Can you post the output of `minkube ssh journalctl` and `minikube logs`?

**Comment by bvdeenen** [comment] 2017-03-20 13:29
Hi, I have the same issue


[minikube.log.txt](https://github.com/kubernetes/minikube/files/855076/minikube.log.txt)
[journalctl.txt](https://github.com/kubernetes/minikube/files/855079/journalctl.txt)

My OS is Void Linux, with VirtualBox 5.1.14

**Comment by gtirloni** [comment] 2017-03-23 14:42
The failed systemd-networkd-wait-online.service is a red herring for this issue. See #1277.

**Comment by norbert-yoimo** [comment] 2017-04-11 15:40
Tried again with 0.18.0, still the same problem, attaching the requested files:

[journalctl](https://pastebin.com/fQCkGLbU)
[logs](https://pastebin.com/aDLA46mH)

**Comment by vadimio** [comment] 2017-04-20 18:59
Same problem

**Comment by RaananHadar** [comment] 2017-04-22 19:50
same problem on ubuntu 17.04

**Comment by david1983** [comment] 2017-05-05 21:20
@RaananHadar I found the solution for ubuntu 17.04 the problem is in the docker version in the Ubuntu repo, you need to uninstall docker docker-engine and install docker-ce.
Here are the steps that I've done:

$sudo apt-get remove docker docker-engine

follow the steps to install docker-ce but you need to change the sources from zesty to xenial because the repo for zesty does not exist yet (tricky bit).

$ sudo apt-get update

$ sudo apt-get install \
    linux-image-extra-$(uname -r) \
    linux-image-extra-virtual

$ sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common

$ curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

$ sudo apt-key fingerprint 0EBFCD88
the key should be equal to this : 9DC8 5822 9FC7 DD38 854A E2D8 8D81 803C 0EBF CD88.

IMPORTANT!!!!
add the repository using xenial instead of zesty
$ sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"

$ sudo apt-get update

$ sudo apt-get install docker-ce

at this point run minikube
$ minikube start

and check the status
$minikube status
minikubeVM: Running
localkube: Running

**Comment by mdmarek** [comment] 2017-05-23 00:55
@david1983 I tried the instructions above but in the end got the same network error, like @RaananHadar was trying this on Ubuntu 17.04.

[journalctl](https://pastebin.com/nxA9t3YJ)
[logs](https://pastebin.com/aE7tPv2b)

**Comment by jpmolinamatute** [comment] 2017-05-29 17:21
same problem here :-(

**Comment by Furtchet** [comment] 2017-07-20 16:14
For others that run into this problem. https://github.com/kubernetes/minikube/issues/1224#issuecomment-316411907 solved it for me.

**Comment by editaxz** [comment] 2019-04-22 01:57
Hi, I had this issue: 
![2019-04-21-205332_928x83_scrot](https://user-images.githubusercontent.com/8731756/56478831-8ebabf80-6477-11e9-8901-2248b86be201.png)

Then I check the minikube: "minikubeis not running"
![2019-04-21-205450_738x169_scrot](https://user-images.githubusercontent.com/8731756/56478890-d5a8b500-6477-11e9-90e1-c930dd552df1.png)

Then I restarted minikube and It started to works.
![2019-04-21-205518_927x533_scrot](https://user-images.githubusercontent.com/8731756/56478917-f07b2980-6477-11e9-8515-37c9a054f1b1.png)

I hope this will be useful to us.

**Comment by jturi** [comment] 2020-02-04 13:45
In my case **use-context** was not set:

Use this if you have kubernetes running with Docker for Desktop:

```
kubectl config use-context docker-for-desktop
```

Use this if you have kubernetes running with minikube:

```
kubectl config use-context minikube
```

If you run into problems with Minikube, the best is to remove and start it over again:

```
minikube stop; minikube delete
rm /usr/local/bin/minikube
rm -rf ~/.minikube
minikube start
```

**Comment by Gauravjaitly** [comment] 2020-09-29 22:26
In my case, my minikube wasnt active. had to start it by "minikube start"

**Comment by priyawadhwa** [comment] 2020-09-30 18:23
Hey @editaxz  did restarting the cluster via

```
minikube delete
minikube start
```
fix it for you?  I'd suggest upgrading to the latest version of minikube, v1.13.1, as well.

**Comment by tstromberg** [comment] 2020-10-07 02:40
Closing as this is due to speaking to a stopped cluster, but opened #9410 to make this less confusing for users.

**Closed by tstromberg** 2020-10-07 02:40 UTC
Labels: kind/bug, lifecycle/rotten, triage/needs-information
