### ISSUE TITLE
minikube crashed on windows with Hyper-V

### ISSUE THREAD

**Issue by BaVanDuong** [kubernetes/minikube#3790] opened 2019-03-05 02:36 UTC
If this is a bug report, please include:

- [x] How to replicate the error, including the exact command-lines used.
 > minikube start -p minikube --vm-driver hyperv --hyperv-virtual-switch "minikube-ext"
- [x] The full output of the command that failed
   
>    minikube v0.34.1 on windows (amd64)
Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
!   Unable to start VM: create: creating: open /Users/devid/.minikube/cache/iso/minikube-v0.34.0.iso: The system cannot find the path specified.
   Sorry that minikube crashed. If this was unexpected, we would love to hear from you: 
   https://github.com/kubernetes/minikube/issues/new

- [x] The operating system name and version used
> OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

**Comment by fooock** [comment] 2019-03-06 16:36
Same error, installed minikube, created the external virtual switch and executed:

```
$ minikube config set vm-driver hyperv
$ minikube config set hyperv-virtual-switch external
```

When I execute `minikube start`, the result is:

```
# minikube start
o   minikube v0.34.1 on windows (amd64)
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
!   Unable to start VM: create: creating: open /Users/javi/.minikube/cache/iso/minikube-v0.34.0.iso: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

I'm using Windows 10 pro 1803

**Comment by fooock** [comment] 2019-03-06 17:05
Complete trace with logs

```
# minikube start -v 9999
o   minikube v0.34.1 on windows (amd64)
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
Creating CA: C:\Users\javi\.minikube\certs\ca.pem
Creating client certificate: C:\Users\javi\.minikube\certs\cert.pem
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
[stdout =====>] : Hyper-V

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole("S-1-5-32-578")
[stdout =====>] : False

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")
[stdout =====>] : True

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (Hyper-V\Get-VMSwitch).Name
[stdout =====>] : external
Modificador predeterminado
DockerNAT

[stderr =====>] :
Downloading C:\Users\javi\.minikube\cache\boot2docker.iso from file://C:/Users/javi/.minikube/cache/iso/minikube-v0.34.0.iso...
!   Unable to start VM: create: creating: open /Users/javi/.minikube/cache/iso/minikube-v0.34.0.iso: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

Path `/Users/jcasanova/.minikube/cache/iso/minikube-v0.34.0.iso` exists. Any idea?

**Comment by tstromberg** [comment] 2019-03-08 18:13
This appears to be a dupe of #1574 - please re-open if it is not.

**Closed by tstromberg** 2019-03-08 18:13 UTC
