### ISSUE TITLE
minikube cannot start in macOS mojave

### ISSUE THREAD

**Issue by hendisantika** [kubernetes/minikube#4033] opened 2019-04-01 23:02 UTC
I was trying to install minikube in macOS Mojave 10.14.3 version.
But, when I am trying to start minikube, error occured:
```
Hendis-MacBook-Pro:demo-k8s hendisantika$ minikube start
There is a newer version of minikube available (v1.0.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v1.0.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
😄  minikube v0.34.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
💣  Unable to start VM: create: creating: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

Is there any solution for that?
Thank You

**Comment by NabheetCloud** [comment] 2019-04-02 02:50
did you try minikube delete then minikube start?

**Comment by hendisantika** [comment] 2019-04-02 06:24
Not yet, but I will try it tonight.
Then let's see.

**Comment by hendisantika** [comment] 2019-04-02 09:51
I already tried:
```
minikube delete
```

Still, It doesn't work for me @NabheetCloud.

**Comment by tstromberg** [comment] 2019-04-04 23:36
Closing as dupe of #4033 - a reboot after installing VirtualBox should fix this. Please re-open if this is not actually a dupe.

**Closed by tstromberg** 2019-04-04 23:36 UTC

**Comment by hendisantika** [comment] 2019-04-05 14:50
I don't understand with this. Why is it closed @tstromberg ?

**Comment by tstromberg** [comment] 2019-04-05 15:12
My apologies. I marked this as a duplicate of the wrong issue. Based on your symptoms, this appears to be related to #3614

**Comment by hendisantika** [comment] 2019-04-05 15:14
Ooo... ya ya ya. Thank You @tstromberg
