### ISSUE TITLE
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Tempor ary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800272e9fe4

### ISSUE THREAD

**Issue by dalingjiuling** [kubernetes/minikube#8252] opened 2020-05-22 17:38 UTC
**重现问题所需的命令**：
E:\soft_install\k8s>minikube config set driver virtualbox
! These changes will take effect upon a minikube delete and then a minikube start

E:\soft_install\k8s>minikube start --image-mirror-country cn --iso-url=https://k
ubernetes.oss-cn-hangzhou.aliyuncs.com/minikube/iso/minikube-v1.9.0.iso --regist
ry-mirror=https://xxxxxx.mirror.aliyuncs.com

**失败的命令的完整输出**：

**`minikube logs`命令的输出**： <details>
* Microsoft Windows 7 Ultimate Service Pack 1 6.1.7601 Build 7601 上的 minikube
v1.9.2
* 根据现有的配置文件使用 virtualbox 驱动程序
* Starting control plane node m01 in cluster minikube
* Downloading Kubernetes v1.18.0 preload ...
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: recreate: creating host: create host tim
ed out in 120.000000 seconds
* Updating the running virtualbox "minikube" VM ...
*
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Tempor
ary Error: error getting ip during provisioning: Could not find matching IP for
MAC address 0800272e9fe4
*
* 由于出错 minikube 正在退出。如果以上信息没有帮助，请提交问题反馈：
  - https://github.com/kubernetes/minikube/issues/new/choose

**使用的操作系统版本**：Windows 7

**Comment by tstromberg** [comment] 2020-05-26 16:23
Do you mind trying in minikube v1.10.1?

Also, this issue appears to be a duplicate of #7725, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-26 16:23 UTC
Labels: co/virtualbox, l/zh-CN
