### ISSUE TITLE
HyperV driver: host.minikube.internal not visible in containers

### ISSUE THREAD

**Issue by mindcrime** [kubernetes/minikube#8444] opened 2020-06-10 19:23 UTC
$> minikube version
minikube version: v1.10.1
commit: 63ab801ac27e5742ae442ce36dff7877dcccb278

**Steps to reproduce the issue:** 

1. minikube start --vm-driver=hyperv --apiserver-port=8080 (on Windows 10)
2. launch container using an image like the echo-server example
3. exec a shell on the running container
4. install ping if not already installed
5. try to ping host.minikube.internal -- note that the name is not resolved
6. drop out of that shell back to the Windows host 
7. Run minikube ssh to get a shell on the minikube VM
8. ping host.minikube.internal - note that the host is resolved
9. shell back into the running container and ping the IP noted in step (8) above. This works. IP connectivity is there, just no name resolution for host.minikube.internal from inside a pod container

<details>

Based on the docs at https://minikube.sigs.k8s.io/docs/handbook/host-access/#hostminikubeinternal, I had thought that host.minikube.internal was intended to facilitate connecting to the underlying host, from pod containers, when using minikube. But while the name resolves OK from the underlying VM, it does not work in the couple of containers I tried. 
</details>

**Comment by mindcrime** [comment] 2020-06-11 13:59
> @mindcrime do u have same problem with docker driver and newest version of minkube?

I haven't been using the docker driver, but I can try that. I can't easily try the latest version, as I'm working in a very locked down environment where I have to do a lot of extra work just to upgrade a software package. I'll see what I can do, but no promises that it will be soon.

**Comment by tstromberg** [comment] 2020-06-24 18:46
Dupe of #8439

**Closed by tstromberg** 2020-06-24 18:46 UTC
Labels: co/hyperv, priority/awaiting-more-evidence, triage/support
