### ISSUE TITLE
Error while running- minikube start --vm-driver=none

### ISSUE THREAD

**Issue by inderjeetsinghaws** [kubernetes/minikube#14403] opened 2022-06-23 16:30 UTC
### What Happened?

sudo minikube start --vm-driver=none
* minikube v1.26.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=7948MB, Disk=7764MB) ...
* OS release is Ubuntu 22.04 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

### Attach the log file

sudo minikube start --vm-driver=none
* minikube v1.26.0 on Ubuntu 22.04 (xen/amd64)
* Using the none driver based on user configuration
* Starting control plane node minikube in cluster minikube
* Running on localhost (CPUs=2, Memory=7948MB, Disk=7764MB) ...
* OS release is Ubuntu 22.04 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment] 2022-06-23 17:56
Hi @inderjeetsinghaws, thanks for reporting your issue with minikube.

Kubernetes v1.24 dropped support for Dockershim, so if you want to use the combination of the none driver, Kubernetes v1.24+, and the Docker container runtime you'll need to install cri-dockerd on your system, as listed in our [requirements page](https://minikube.sigs.k8s.io/docs/drivers/none/#requirements).

Other options include using a [different driver](https://minikube.sigs.k8s.io/docs/drivers/), using an older version of Kubernetes `--kubernetes-version`, or using a different container runtime `--container-runtime`.

Please try one of those solution and let me know if it resolves your issue, thanks

**Comment by amiyaranjansahoo** [comment] 2022-06-24 10:02
HI @[spowelljr](https://github.com/spowelljr),
thank you for the advise. I am also facing the same issue.
I did not find the link for: how to manually install cri-dockerd .

Thanks

**Comment by spowelljr** [comment] 2022-06-24 17:26
Hi @amiyaranjansahoo, it should be listed on our `none` driver page under the requirements sections:
https://minikube.sigs.k8s.io/docs/drivers/none/#requirements

But here's a direct link to the cri-dockerd install instructions:
https://github.com/Mirantis/cri-dockerd#build-and-install

**Comment by afbjorklund** [comment] 2022-06-26 07:56
Upstream documentation is here: https://kubernetes.io/docs/setup/production-environment/container-runtimes/

**Comment by amiyaranjansahoo** [comment] 2022-06-28 10:48
[logs.txt](https://github.com/kubernetes/minikube/files/9000204/logs.txt)

Hi @spowelljr , Thank you for the support. Sorry for my late reply .
 followed the steps to install cri-dockerd and executed   all the steps except 
To build this code (in a POSIX environment):
And I believe this is not required for  Ubuntu 18.04 

Also did not mention any argument for ARCH
specific architecture, add ARCH= as an argument,

Hope this should be fine..
Still getting the error

X Exiting due to RUNTIME_ENABLE: Temporary Error: sudo crictl version: exit status 1
stdout:

stderr:
sudo: crictl: command not found

**Comment by afbjorklund** [comment] 2022-06-28 17:37
In the best of worlds, upstream would mention this already on the installation page.

**Comment by amiyaranjansahoo** [comment] 2022-06-29 05:43
Thank you @spowelljr and @afbjorklund, I will install crictl and update the progress.

**Comment by amiyaranjansahoo** [comment] 2022-06-29 14:58
Thanks @spowelljr and @afbjorklund, The issue is resolved.
I am able to start minikube with below option.

Just out of curiosity, how to install minikube with driver.  say docker ( I have already installed docker in the server)

**Comment by spowelljr** [comment] 2022-06-29 17:21
> Just out of curiosity, how to install minikube with driver. say docker ( I have already installed docker in the server)

`minikube start --driver docker` should be all you need to start minikube with the docker driver if you already have the Docker Engine installed.

**Comment by spowelljr** [comment] 2022-06-30 22:44
Going to close this issue to centralize these duplicated `cri-docker` issues in https://github.com/kubernetes/minikube/issues/14410. If you have any further questions or comments please leave them in https://github.com/kubernetes/minikube/issues/14410, thank you.

**Closed by spowelljr** 2022-06-30 22:44 UTC
Labels: kind/documentation, co/runtime/docker, co/none-driver, priority/backlog

**Comment by sabih12anwar24** [comment] 2022-09-18 13:27
@spowelljr,

 Hi Steven  Good Day hope you are doing well.
I installed cri-dockerd following the above Steps and it's running fine, I am trying to run minikube cluster on AWS EC2 t2 medium Instance

Logs for the same:

**** this is for the cri-docker Installation last two lines just showed here followed the above steps it got installed***

[root@ip-172-31-12-32 cri-dockerd]# systemctl enable cri-docker.service
Created symlink from /etc/systemd/system/multi-user.target.wants/cri-docker.service to /etc/systemd/system/cri-docker.service.
[root@ip-172-31-12-32 cri-dockerd]# systemctl enable --now cri-docker.socket
Created symlink from /etc/systemd/system/sockets.target.wants/cri-docker.socket to /etc/systemd/system/cri-docker.socket.
[root@ip-172-31-12-32 cri-dockerd]# d


**** Status of cri-docker as running****


● cri-docker.service - CRI Interface for Docker Application Container Engine
   Loaded: loaded (/etc/systemd/system/cri-docker.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2022-09-18 13:20:20 UTC; 1min 3s ago
     Docs: https://docs.mirantis.com
 Main PID: 14196 (cri-dockerd)
    Tasks: 7
   Memory: 9.9M
   CGroup: /system.slice/cri-docker.service
           └─14196 /usr/local/bin/cri-dockerd --container-runtime-endpoint fd://

Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Start docker client with request timeout 0s"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Hairpin mode is set to none"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Loaded network plugin cni"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Docker cri networking managed by network plugin cni"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Docker Info: &{ID:AX4E:TG3W:6NVK:4PJU:ADSQ:JCI5:KJSI:IF...ive Over
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Setting cgroupDriver cgroupfs"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal systemd[1]: Started CRI Interface for Docker Application Container Engine.
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Docker cri received runtime config &RuntimeConfig{Netwo...dr:,},}"
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Starting the GRPC backend for the Docker CRI interface."
Sep 18 13:20:20 ip-172-31-12-32.us-west-2.compute.internal cri-dockerd[14196]: time="2022-09-18T13:20:20Z" level=info msg="Start cri-dockerd grpc backend"
Hint: Some lines were ellipsized, use -l to show in full.


** Now when I am running minikube using minikube start --vm-driver=none" it's giving me error saying you have to install again***


[root@ip-172-31-12-32 cri-dockerd]# minikube start --driver=none
* minikube v1.27.0 on Amazon 2 (xen/amd64)
! Kubernetes 1.25.0 has a known issue with resolv.conf. minikube is using a workaround that should work for most use cases.
! For more information, see: https://github.com/kubernetes/kubernetes/issues/112135
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...

* Exiting due to NOT_FOUND_CRI_DOCKERD: 

* Suggestion: 

    The none driver with Kubernetes v1.24+ and the docker container-runtime requires cri-dockerd.
    
    Please install cri-dockerd using these instructions:
    
    https://github.com/Mirantis/cri-dockerd#build-and-install


I have tried many times and don't know what to do next can you help me Steven
