### ISSUE TITLE
[flake test] TestStartStop/group/old-k8s-version/serial/Pause  - Executing: /lib/systemd/systemd-sysv-install disable kubelet"

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11614] opened 2021-06-09 18:54 UTC
```
	I0609 01:41:59.357566  373430 ssh_runner.go:149] Run: sudo systemctl disable kubelet
	I0609 01:41:59.480954  373430 retry.go:31] will retry after 276.165072ms: kubelet disable: sudo systemctl disable kubelet: Process exited with status 1
	stdout:
	
	stderr:
	Synchronizing state of kubelet.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
	I0609 01:41:59.757382  373430 ssh_runner.go:149] Run: sudo systemctl disable kubelet
	I0609 01:41:59.875735  373430 retry.go:31] will retry after 540.190908ms: kubelet disable: sudo systemctl disable kubelet: Process exited with status 1
	stdout:
	
	stderr:
	Synchronizing state of kubelet.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
```

For the full log please see https://storage.googleapis.com/minikube-builds/logs/11610/64a4182/Docker_Linux.html#fail_TestStartStop%2fgroup%2fold-k8s-version%2fserial%2fPause

**Comment by spowelljr** [comment] 2022-01-06 22:41
Duplicate of https://github.com/kubernetes/minikube/issues/11615

**Closed by spowelljr** 2022-01-06 22:41 UTC
Labels: area/testing, priority/important-longterm, lifecycle/frozen, kind/flake
