### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by trplx666** [kubernetes/minikube#19697] opened 2024-09-23 17:35 UTC
### What Happened?

cant create vm on virtual box minikube
❌  Exiting due to GUEST_PROVISION: error provisioning guest: Failed to start host: creating host: create: creating: /usr/bin/VBoxManage modifyvm minikube --firmware bios --bioslogofadein off --bioslogofadeout off --bioslogodisplaytime 0 --biosbootmenu disabled --ostype Linux26_64 --cpus 2 --memory 2200 --acpi on --ioapic on --rtcuseutc on --natdnshostresolver1 on --natdnsproxy1 off --cpuhotplug off --pae on --hpet on --hwvirtex on --nestedpaging on --largepages on --vtxvpid on --accelerate3d off --boot1 dvd --natlocalhostreachable1 on failed:
VBoxManage: error: The graphics controller does not support the given feature
VBoxManage: error: Details: code VBOX_E_NOT_SUPPORTED (0x80bb0009), component GraphicsAdapterWrap, interface IGraphicsAdapter, callee nsISupports
VBoxManage: error: Context: "SetFeature(GraphicsFeature_Acceleration3D, ValueUnion.f)" at line 1108 of file VBoxManageModifyVM.cpp

### Attach the log file

[logs.txt](https://github.com/user-attachments/files/17101514/logs.txt)

### Operating System

Ubuntu

### Driver

VirtualBox

**Comment by spowelljr** [comment] 2024-09-30 21:44
Hi @trplx666, this is a duplicate of https://github.com/kubernetes/minikube/issues/19639, we have a fix in the works, please follow along at https://github.com/kubernetes/minikube/issues/19639 and I'll close this issue to centralize discussion.

**Closed** 2024-09-30 21:44 UTC
Labels: triage/duplicate
