### ISSUE TITLE
minikube is not starting

### ISSUE THREAD

**Issue by GagandeepGupta** [kubernetes/minikube#8221] opened 2020-05-20 17:23 UTC
* minikube v1.9.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Using the virtualbox driver based on existing profile
* Starting control plane node m01 in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
* Updating the running virtualbox "minikube" VM ...
*
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 0800277d2674
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment] 2020-05-20 18:39
Hey @GagandeepGupta thanks for opening this issue.

This issue seems to be a duplicate of https://github.com/kubernetes/minikube/issues/7725. I'm going to close this issue so that all information around this can be centralized there.

If possible, could you provide the information requested in this [comment](https://github.com/kubernetes/minikube/issues/7725#issuecomment-619714022) and add it as a comment in https://github.com/kubernetes/minikube/issues/7725? Thank you!

**Closed by priyawadhwa** 2020-05-20 18:39 UTC
Labels: triage/support
