### ISSUE TITLE
provision: get ssh host-port: get port 22 for "minikube": docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'": exit status 1

### ISSUE THREAD

**Issue by NandiniJB** [kubernetes/minikube#8255] opened 2020-05-23 07:10 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by RA489** [comment] 2020-05-26 06:37
@NandiniJB I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details. Here is additional information that would be helpful:

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=4 for extra logging.

* The full output of minikube logs

* The full output of kubectl get po -A

Thank you for sharing your experience!

**Comment by tstromberg** [comment] 2020-05-28 17:20
This issue appears to be a duplicate of #8163, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-28 17:20 UTC
Labels: co/docker-driver, triage/needs-information, triage/support
