### ISSUE TITLE
Flake TestStartStop/group/no-preload/serial/Pause

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#13012] opened 2021-11-23 00:07 UTC
Example 
https://storage.googleapis.com/minikube-builds/logs/13002/21462/Docker_Linux.html#fail_TestStartStop%2fgroup%2fno-preload%2fserial%2fPause

The logs include:

```
	W1122 23:42:12.704505  384828 out.go:241] X Exiting due to GUEST_PAUSE: kubelet disable --now: sudo systemctl disable --now kubelet: Process exited with status 1
	stdout:
	
	stderr:
	Synchronizing state of kubelet.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
	
	X Exiting due to GUEST_PAUSE: kubelet disable --now: sudo systemctl disable --now kubelet: Process exited with status 1
	stdout:
	
	stderr:
	Synchronizing state of kubelet.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
	
	W1122 23:42:12.704536  384828 out.go:241] * 
```

the important part is

```
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
	
	X Exiting due to GUEST_PAUSE: kubelet disable --now: sudo systemctl disable --now kubelet: Process exited with status 1
	stdout:
	
	stderr:
	Synchronizing state of kubelet.service with SysV service script with /lib/systemd/systemd-sysv-install.
	Executing: /lib/systemd/systemd-sysv-install disable kubelet
	update-rc.d: error: kubelet Default-Start contains no runlevels, aborting.
```

**Comment by spowelljr** [comment] 2022-01-06 22:45
Same error as https://github.com/kubernetes/minikube/issues/11615

**Comment by klaases** [comment] 2022-01-19 19:53
Hi @medyagh, do we want to mark this as a duplicate of #11615?

**Comment by spowelljr** [comment] 2022-01-19 21:52
This is for `TestStartStop/group/old-k8s-version/serial/Pause` while this one if for `TestStartStop/group/no-preload/serial/Pause` `no-preload` vs `group`. But I'm assuming that fixing one will likely fix the other.

**Closed** 2022-06-18 23:55 UTC
Labels: lifecycle/rotten
