### ISSUE TITLE
 docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1

### ISSUE THREAD

**Issue by spiderGX** [kubernetes/minikube#8227] opened 2020-05-21 02:55 UTC
1. minikube start --driver=docker

error log：
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* docker "minikube" container is missing, will recreate.
E0521 10:30:47.920217    2700 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
* Creating docker container (CPUs=2, Memory=8000MB) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=8000mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 : exit status 125
stdout:

stderr:
/usr/bin/docker-current: Error parsing reference: "" is not a valid repository/tag: repository name must have at least one component.
See '/usr/bin/docker-current run --help'.

* docker "minikube" container is missing, will recreate.
E0521 10:31:17.576404    2700 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
* Creating docker container (CPUs=2, Memory=8000MB) ...
* Failed to start docker container. "minikube start" may fix it: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=8000mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 : exit status 125
stdout:

stderr:
/usr/bin/docker-current: Error parsing reference: "" is not a valid repository/tag: repository name must have at least one component.
See '/usr/bin/docker-current run --help'.

*
X error provisioning host: Failed to start host: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=8000mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 : exit status 125
stdout:

stderr:
/usr/bin/docker-current: Error parsing reference: "" is not a valid repository/tag: repository name must have at least one component.
See '/usr/bin/docker-current run --help'.

1. docker inspect minikube
[
    {
        "Driver": "local",
        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true",
            "name.minikube.sigs.k8s.io": "minikube"
        },
        "Mountpoint": "/var/lib/docker/volumes/minikube/_data",
        "Name": "minikube",
        "Options": {},
        "Scope": "local"
    }
]

2.docker images

gcr.io/k8s-minikube/kicbase   v0.0.10             e6bc41c39dc4        3 weeks ago         974 MB

**Comment by spiderGX** [comment] 2020-05-21 03:10
when i try to remove  gcr.io/k8s-minikube/kicbase:v0.0.10 image
docker rmi gcr.io/k8s-minikube/kicbase:v0.0.10
Untagged: gcr.io/k8s-minikube/kicbase:v0.0.10
Deleted: sha256:e6bc41c39dc48b2b472936db36aedb28527ce0f675ed1bc20d029125c9ccf578
Deleted: sha256:61a5235931edd418b69320f92185c106e18afa5e211596326ccce4d502797d49
Deleted: sha256:042e0856c7b4cfb34777d4a6111625348a0159ce9dfdc6bf171e9f6465c969a9
Deleted: sha256:acdf44aed0d03935a08d6614b2bbec2ee7f1e8892c7e58c2a51b661bae1752fe
Deleted: sha256:4bc3e4ff1398e1876b8dc36902f55683baf75d4e3bc7d82d653d8c96d327d9a1
Deleted: sha256:21606b8ee89e8f5843ad820295842e86f861fdf3a85a08369072b2bad413aca5
Deleted: sha256:e588e701428bfc8cde242c8dab7cf504d7ae9ecf3114999a099e44609818533b
Deleted: sha256:a357f647b869b3630f385008d55cf5b1d6ddb49d70c854c08ae95f717fde7c20
Deleted: sha256:0c63c11a175465ab3886e6565cbfa02d4eecfafe192d383a34686f184221a7bc
Deleted: sha256:b4bf37bd2ccc6eb76b97eb202ad58ecd7b841915de5fef9b2224d6a917695049
Deleted: sha256:8e3ca206bf8b17ef7943e93e3e8649ee336d0ff83ff91be8b2d2dd4f28d363a9
Deleted: sha256:6a7cfac3fb09b7406840c5d65d04bbfe9d7c6d37e22cd90652b4906fce94e83a
Deleted: sha256:57205a827e2eeb67305e0c556f7abfe9753757bd4b26503533e5119d04e0cca5
Deleted: sha256:5b9ad24dd9771e8af3db8a8bcdef69de6375f3117d44d2df989d5178697125c3
Deleted: sha256:ce814f6168dcd0a379b263c520992d09fe0f44d365f635fc086eaa6f4f98948f
Deleted: sha256:097c3d7ae2680f1f8c7e0f09fdc8126e20111a8d7cee7860ba0a128ae512897e
Deleted: sha256:25ae00530f37a32d5121254b69424071e9405ba4b6f73eac190969b3522030d9
Deleted: sha256:7d1b8ba98b0bd430f37bdf75fe68835f8e6bbaa94744ae384319001f7409384e
Deleted: sha256:e100135301be89616488a8da9b99ff1bfb5a1d9a504751ac1efeac5fefcf1b6a
Deleted: sha256:768375357e155d673396db64535f3c1472c5955f08072f0a75fb9bdabebd79c2
Deleted: sha256:84e383781e77370a652f1471c5757fd8ed073d7af2edafecebe3d819241b480c
Deleted: sha256:b2839f1dedee562a91bd1e7ee98a5f37f2ce3312f5ed07f266081dc6217059f7
Deleted: sha256:634b4695a7c1807938e5b1653eeb5b5a489912307f0b8860e4eb5edbe46a1c52

then to start  ****minikube start --driver=docker****
* minikube v1.10.1 on Centos 7.5.1804
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* docker "minikube" container is missing, will recreate.
E0521 11:07:59.290554    3453 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"

 docker inspect minikube
[
    {
        "Driver": "local",
        "Labels": {
            "created_by.minikube.sigs.k8s.io": "true",
            "name.minikube.sigs.k8s.io": "minikube"
        },
        "Mountpoint": "/var/lib/docker/volumes/minikube/_data",
        "Name": "minikube",
        "Options": {},
        "Scope": "local"
    }
]

**Comment by medyagh** [comment] 2020-05-21 05:37
@spiderGX do you mind sharing "docker info"
and docker version outputput?

and also the output of "docker logs minikube"
and also minikube start --driver=docker --alsologtostderr ?

**Comment by spiderGX** [comment] 2020-05-21 05:59
minikube start --driver=docker --alsologtostderr
W0521 13:59:22.837501    3017 root.go:252] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0521 13:59:22.932211    3017 start.go:99] hostinfo: {"hostname":"xy-taf-server","uptime":10081,"bootTime":1590030681,"procs":242,"os":"linux","platform":"centos","platformFamily":"rhel","platformVersion":"7.5.1804","kernelVersion":"3.10.0-862.2.3.el7.x86_64","virtualizationSystem":"kvm","virtualizationRole":"host","hostid":"d3a77a49-8111-45b5-bdc9-671ed7f71398"}
I0521 13:59:22.932877    3017 start.go:109] virtualization: kvm host
* minikube v1.10.1 on Centos 7.5.1804
I0521 13:59:22.958453    3017 notify.go:125] Checking for updates...
I0521 13:59:22.958546    3017 driver.go:253] Setting default libvirt URI to qemu:///system
I0521 13:59:22.984431    3017 docker.go:95] docker version: linux-1.13.1
* Using the docker driver based on user configuration
I0521 13:59:22.988900    3017 start.go:215] selected driver: docker
I0521 13:59:22.988916    3017 start.go:594] validating driver "docker" against <nil>
I0521 13:59:22.988932    3017 start.go:600] status for docker: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0521 13:59:22.988969    3017 start.go:917] auto setting extra-config to "kubeadm.pod-network-cidr=10.244.0.0/16".
* The "docker" driver should not be used with root privileges.
* If you are running minikube within a VM, consider using --driver=none:
*   https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Comment by medyagh** [comment] 2020-05-21 07:11
Can you please also share docker info?

**Comment by afbjorklund** [comment] 2020-05-21 07:46
I don't think we have any regression tests on CentOS 7 and Docker 1.13 (a.k.a. 17.03)

It's a _lot_ older than our other platforms, so it might some have special needs... #3552

**Comment by afbjorklund** [comment] 2020-05-21 07:48
This error is the same that we have seen in all the other reports:

` Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"`

I think it is trying to inspect the volume, as if it was a container ?

As in #8192

**Comment by francis-du** [comment] 2020-05-21 11:54
- I get the same error when I run `minikube start --driver='docker'`.

- The error shows that I need a mirror name called 

`docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10` 

- I can't get it from docker package,I used 

`docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10`  

to pull down and changed the tag.

- At this time I successfully launched Minikube.

![image](https://user-images.githubusercontent.com/25944814/82556182-d2608b00-9b9b-11ea-9d4d-c1ee4197ff74.png)

<details>

<summary>This is all the dependencies of Minikube</summary>

![image](https://user-images.githubusercontent.com/25944814/82555835-21f28700-9b9b-11ea-89dc-5aef8e5c27bf.png)

```
k8s.gcr.io/kube-controller-manager:v1.18.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-controller-manager:v1.18.2
k8s.gcr.io/kube-proxy:v1.18.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-proxy:v1.18.2
k8s.gcr.io/etcd:3.4.3-0=registry.cn-hangzhou.aliyuncs.com/google_containers/etcd:3.4.3-0
k8s.gcr.io/coredns:1.6.7=registry.cn-hangzhou.aliyuncs.com/google_containers/coredns:1.6.7
k8s.gcr.io/kube-apiserver:v1.18.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-apiserver:v1.18.2
k8s.gcr.io/kube-scheduler:v1.18.2=registry.cn-hangzhou.aliyuncs.com/google_containers/kube-scheduler:v1.18.2
k8s.gcr.io/pause:3.2=registry.cn-hangzhou.aliyuncs.com/google_containers/pause:3.2
gcr.io/k8s-minikube/storage-provisioner:v1.8.1=registry.cn-hangzhou.aliyuncs.com/minikube-k8s/storage-provisioner:v1.8.1
docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10=registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10
```
`key=value`

    docker pull ${value}
    docker tag ${value} ${key}
    docker rmi ${value}

</details>

Hope this way will work for you (^^).

**Comment by asurin** [comment] 2020-05-22 00:57
I wanted to +1 this issue as I had the same problem today on a fresh minikube install.  Docker info below - it's pretty current so I don't think it's necessarily a version-specific problem.  The above solution _did_ work however

```Client:
 Debug Mode: false

Server:
 Containers: 11
  Running: 0
  Paused: 0
  Stopped: 11
 Images: 119
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 35bd7a5f69c13e1563af8a93431411cd9ecf5021
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683b971d9c3ef73f284f176672c44b448662
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.38-gentooworkstation
 Operating System: Gentoo/Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 32
 Total Memory: 125.8GiB
 Name: workstation
 ID: V2UG:H3SL:W3PY:B4PQ:SCKO:OVLA:NCUH:3DSW:EHRQ:AXP6:OSBL:WVDC
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by spiderGX** [comment] 2020-06-01 02:41
> * I get the same error when I run `minikube start --driver='docker'`.
> * The error shows that I need a mirror name called
> 
> `docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10`
> 
> * I can't get it from docker package,I used
> 
> `docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10`
> 
> to pull down and changed the tag.
> 
> * At this time I successfully launched Minikube.
> 
> ![image](https://user-images.githubusercontent.com/25944814/82556182-d2608b00-9b9b-11ea-9d4d-c1ee4197ff74.png)
> 
> This is all the dependencies of Minikube
> Hope this way will work for you (^^).



> * I get the same error when I run `minikube start --driver='docker'`.
> * The error shows that I need a mirror name called
> 
> `docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10`
> 
> * I can't get it from docker package,I used
> 
> `docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10`
> 
> to pull down and changed the tag.
> 
> * At this time I successfully launched Minikube.
> 
> ![image](https://user-images.githubusercontent.com/25944814/82556182-d2608b00-9b9b-11ea-9d4d-c1ee4197ff74.png)
> 
> This is all the dependencies of Minikube
> Hope this way will work for you (^^).

- when pull  image ：registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase   v0.0.10             e6bc41c39dc4        4 weeks ago         974 MB

- minikube start --driver='docker'

the same error log got:
* minikube v1.10.1 on Centos 7.5.1804
* Using the docker driver based on existing profile
* Starting control plane node minikube in cluster minikube
* docker "minikube" container is missing, will recreate.
E0601 10:40:12.093825   24797 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:


stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
* Creating docker container (CPUs=2, Memory=8000MB) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: docker run -d -t --privileged --security-opt seccomp=unconfined --security-opt apparmor=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=8000mb -e container=docker --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 --publish=127.0.0.1::5000 : exit status 125
stdout:

stderr:
/usr/bin/docker-current: Error parsing reference: "" is not a valid repository/tag: repository name must have at least one component.
See '/usr/bin/docker-current run --help'.

**Comment by spiderGX** [comment] 2020-06-01 02:42
minikube v1.10.1 on Centos 7.5.1804 is not supported ?

**Comment by afbjorklund** [comment] 2020-06-01 05:04
This last error looks like the same as in #8325, some issue when updating the old config...

**Comment by afbjorklund** [comment] 2020-06-01 05:05
> minikube v1.10.1 on Centos 7.5.1804 is not supported ?

The docker driver is untested on that platform, but there is no reason why it shouldn't work

**Comment by medyagh** [comment] 2020-06-17 18:20
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate.



> * I get the same error when I run `minikube start --driver='docker'`.
> * The error shows that I need a mirror name called
> 
> `docker.pkg.github.com/kubernetes/minikube/kicbase:v0.0.10`
> 
> * I can't get it from docker package,I used
> 
> `docker pull registry.cn-hangzhou.aliyuncs.com/google_containers/kicbase:v0.0.10`
> 
> to pull down and changed the tag.
> 
> * At this time I successfully launched Minikube.
> 
> ![image](https://user-images.githubusercontent.com/25944814/82556182-d2608b00-9b9b-11ea-9d4d-c1ee4197ff74.png)
> 
> This is all the dependencies of Minikube
> Hope this way will work for you (^^).

we fixed the image registry issue on v1.11.0 ,

closing this, please if this issue. is still happenning feel free to reopend.

**Closed by medyagh** 2020-06-17 18:20 UTC
Labels: co/docker-driver, os/linux, triage/needs-information, triage/support

**Comment by linxing** [comment] 2020-07-01 10:35
still got this problem on v1.11.0

**Comment by linxing** [comment] 2020-07-01 10:37
> still got this problem on v1.11.0

minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

ubuntu 20.04 5.4.0-37-generic

Docker version 19.03.11, build 42e35e61f3
