### ISSUE TITLE
The exit code for a minikube ssh command is always 0

### ISSUE THREAD

**Issue by pietervogelaar** [kubernetes/minikube#3525] opened 2019-01-10 21:16 UTC
The minikube ssh command always returns with an exit code 0, even if it fails.

    minikube ssh "nonexistingcommand" && minikube ssh "date"

The second command should not be executed, because the first one failed.

**Comment by tstromberg** [comment] 2019-01-19 00:08
Confirmed in v0.33.0:

```
$ minikube ssh "ls /yy" && echo $status
ls: cannot access '/yy': No such file or directory
0
```

Definitely a WTF.

**Comment by adubkov** [comment] 2019-01-29 00:49
Problem in this line. it missing error handling: https://github.com/kubernetes/minikube/blob/master/vendor/github.com/docker/machine/libmachine/ssh/client.go#L326

It is third-party lib, and looks like they already fixed that issue:
https://github.com/docker/machine/blob/master/libmachine/ssh/client.go#L328

The version docker `docker/machine` needs to be update in current repo, but because we are using this fork, owner of that forked repo have to update it and lock file needs to be regenerated:
https://github.com/machine-drivers/machine

**Comment by afbjorklund** [comment] 2019-01-29 06:13
Please don't do any more forks...

This should be fixed (https://github.com/docker/machine/commit/6c90ba4d3da9a37ebc15c4c65d61479db075fca5) by updating  to v0.16.1: https://github.com/machine-drivers/machine/pull/14

When comparing the `master` branch, there are **no** more differences left - only the forking (and merges)

So could go back to docker/machine.

**Comment by tstromberg** [comment] 2019-01-30 19:13
@afbjorklund @adubkov - Thank you for digging into this!

If the machine-drivers/machine PR blockage goes on much longer, I would certainly consider switching back to docker/machine.

**Comment by afbjorklund** [comment] 2019-02-02 12:07
@tstromberg : unfortunately the vendored vmware driver is now blocking the switch:

```
Solving failure: No versions of github.com/machine-drivers/docker-machine-driver-vmware met constraints:
	v0.1.1: Could not introduce github.com/machine-drivers/docker-machine-driver-vmware@v0.1.1, as it depends on github.com/docker/machine from github.com/machine-drivers/machine, but github.com/docker/machine is already marked as coming from github.com/docker/machine by k8s.io/minikube
	v0.1.0: Could not introduce github.com/machine-drivers/docker-machine-driver-vmware@v0.1.0, as it has a dependency on github.com/docker/machine with constraint ^0.13.0, which has no overlap with existing constraint master from (root)
	master: Could not introduce github.com/machine-drivers/docker-machine-driver-vmware@master, as it depends on github.com/docker/machine from github.com/machine-drivers/machine, but github.com/docker/machine is already marked as coming from github.com/docker/machine by k8s.io/minikube
```

But now that `0.16.1` has been merged to the `machine` fork, it is not the end of the world...

**Comment by afbjorklund** [comment] 2019-02-02 14:02
Trying to upgrade the vendored dependency, but `dep` seems to be a bit grumpy...

I want to use `a773edc6f013c9fab13360fea0192fd335023a16` as the new revision.

**Closed** 2019-02-04 17:11 UTC
Labels: good first issue, help wanted, kind/bug, priority/important-soon

**Comment by delwaterman** [comment] 2019-02-12 21:36
Still broken for me:

```
16:34 $ minikube ssh foo; echo $?
bash: foo: command not found
0
16:35 $ minikube version
minikube version: v0.33.1
```
