### ISSUE TITLE
Deleting VM makes starting new VM fail

### ISSUE THREAD

**Issue by itamarst** [kubernetes/minikube#1012] opened 2017-01-17 14:15 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

**Minikube version** (use `minikube version`):

0.15 (but had same experience with earlier versions)

**Environment**:
- Ubuntu 16.04
- VirtualBox
- Docker client 1.12.5, server 1.11.1

**What happened**:

1. `minikube start`
2. Deploy something with kubectl.
3. `minikube stop`
4. `minikube delete`
5. `minikube start`

It then blew up with an error:

```
Starting local Kubernetes cluster...
E0117 09:11:38.961480   31991 start.go:94] Error starting host: Error creating host: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
.

 Retrying.
E0117 09:11:38.962493   31991 start.go:100] Error starting host:  Error creating host: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.100:2376": dial tcp 192.168.99.100:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
```

In order to recover I needed to:
1. `minikube delete`
2. `rm -rf ~/.minikube`

**What you expected to happen**:
I would expect that I should be able to wipe old VMs without breaking creation of new VMs.

**How to reproduce it** (as minimally and precisely as possible):
See above.

**Comment by r2d4** [comment] 2017-01-17 19:39
Closing this as a dupe of https://github.com/kubernetes/minikube/issues/971

Still an annoying bug, the timeout on waiting for the docker daemon is _sometimes_ not long enough.  This is fixed with a subsequent `minikube start`, although we should definitely fix it so thats not necessary

**Closed by r2d4** 2017-01-17 19:39 UTC
