### ISSUE TITLE
Minikube registry addon fails 

### ISSUE THREAD

**Issue by MrBuddyCasino** [kubernetes/minikube#6012] opened 2019-12-04 11:42 UTC
I can't pull images from the Minikube registry using `localhost:5000/instana/echo-client`, it fails with "no route to host". Pushing works though!

**The exact command to reproduce the issue**:
```
minikube start --insecure-registry "10.0.0.0/24" --container-runtime=cri-o
minikube addons enable registry
docker run --name socat-bridge --rm -it --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000" &>/dev/null &

# build & push image
docker build -t instana/echo-client .
docker tag instana/echo-client localhost:5000/instana/echo-client
docker push localhost:5000/instana/echo-client

kubectl apply -f client.yaml
```
**The full output of the command that failed**:<details>

```
Successfully assigned default/echo-client-hlxnk to minikube
Pulling image "localhost:5000/instana/echo-client"
Failed to pull image "localhost:5000/instana/echo-client": rpc error: code = Unknown desc = pinging docker registry returned: Get http://localhost:5000/v2/: dial tcp 127.0.0.1:5000: connect: no route to host
Error: ErrImagePull
```

</details>

**The output of the `minikube logs` command**:<details>

see [minikube.log](https://github.com/kubernetes/minikube/files/3921595/minikube.log)

</details>

**The operating system version**: macOS Mojave

**Comment by MrBuddyCasino** [comment] 2019-12-04 13:25
I also tried using `registry.kube-system.svc.cluster.local:80/instana/echo-client` as the container image location, but the host lookup failed with `ErrImagePull: rpc error: code = Unknown desc = pinging docker registry returned: Get https://registry.kube-system.svc.cluster.local:80/v2/: dial tcp: lookup registry.kube-system.svc.cluster.local: no such host`.

Using the IP worked tough: `10.111.155.225:80/instana/echo-client`

**Comment by MrBuddyCasino** [comment] 2019-12-04 15:50
This might be a duplicate of 
https://github.com/kubernetes/minikube/issues/4553
https://github.com/kubernetes/minikube/issues/4547

**Comment by medyagh** [comment] 2019-12-16 23:05
@MrBuddyCasino  I dont think this is a duplicate of #4547 since this one is about registery addon, the other one is for the regsitery minikube uses

**Comment by medyagh** [comment] 2019-12-16 23:07
@MrBuddyCasino I am curious, do you have this issue with other runtimes other than cri-o ?

**Comment by medyagh** [comment] 2019-12-16 23:20
I will close this issue to track it here https://github.com/kubernetes/minikube/issues/6024

**Closed by medyagh** 2019-12-16 23:20 UTC
