### ISSUE TITLE
Unable to resolve DNS in new cluster due to missing IPTables rules

### ISSUE THREAD

**Issue by davefinster** [kubernetes/minikube#2239] opened 2017-11-30 11:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.24.0
- **OS** (e.g. from /etc/os-release): macOS High Sierra 10.13.2 Beta (17C83a)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.23.4.iso

**What happened**:

Upon starting a new cluster with a basic ```minikube start```, containers/pods that I create are unable to conduct DNS resolution. For example:

```bash
> kubectl run -it --image=alpine:latest test
/ # ping google.com
ping: bad address 'google.com'
/ #
```
**What you expected to happen**:

```bash
> kubectl run -it --image=alpine:latest test
/ #  ping google.com
PING google.com (216.58.220.110): 56 data bytes
64 bytes from 216.58.220.110: icmp_seq=0 ttl=57 time=25.861 ms
```

**How to reproduce it** (as minimally and precisely as possible):

As far as I can tell, a simple ```minikube start``` with no existing cluster using Minikube 0.24. Any container created after that will have non-functional DNS.

**Output of `minikube logs` (if applicable)**:

https://gist.github.com/davefinster/b000db483ef8885f06b39aabd9f31d99

**Anything else do we need to know**:

I believe the issue is related to a lack of IPTables rules being populated by the proxy. This is a complete list of the iptables rules in the running VM:

```
# Generated by iptables-save v1.6.1 on Thu Nov 30 11:06:59 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [10:600]
:POSTROUTING ACCEPT [10:600]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-2AMR4GNIYH7ZRQLQ - [0:0]
:KUBE-SEP-F3JA2MOXYYHCYKC5 - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-XGLOHA7QRQ3V22RZ - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.17.0.0/16 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp --dport 30000 -j KUBE-MARK-MASQ
-A KUBE-NODEPORTS -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp --dport 30000 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-2AMR4GNIYH7ZRQLQ -s 10.0.2.15/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-2AMR4GNIYH7ZRQLQ -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-2AMR4GNIYH7ZRQLQ --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.0.2.15:8443
-A KUBE-SEP-F3JA2MOXYYHCYKC5 -s 172.17.0.4/32 -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-MARK-MASQ
-A KUBE-SEP-F3JA2MOXYYHCYKC5 -p tcp -m comment --comment "kube-system/kubernetes-dashboard:" -m tcp -j DNAT --to-destination 172.17.0.4:9090
-A KUBE-SERVICES -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES -d 10.0.0.84/32 -p tcp -m comment --comment "kube-system/kubernetes-dashboard: cluster IP" -m tcp --dport 80 -j KUBE-SVC-XGLOHA7QRQ3V22RZ
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-2AMR4GNIYH7ZRQLQ --mask 255.255.255.255 --rsource -j KUBE-SEP-2AMR4GNIYH7ZRQLQ
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-2AMR4GNIYH7ZRQLQ
-A KUBE-SVC-XGLOHA7QRQ3V22RZ -m comment --comment "kube-system/kubernetes-dashboard:" -j KUBE-SEP-F3JA2MOXYYHCYKC5
COMMIT
# Completed on Thu Nov 30 11:06:59 2017
# Generated by iptables-save v1.6.1 on Thu Nov 30 11:06:59 2017
*mangle
:PREROUTING ACCEPT [72127:283405802]
:INPUT ACCEPT [72019:283373593]
:FORWARD ACCEPT [104:29905]
:OUTPUT ACCEPT [60113:11754771]
:POSTROUTING ACCEPT [60232:11785450]
COMMIT
# Completed on Thu Nov 30 11:06:59 2017
# Generated by iptables-save v1.6.1 on Thu Nov 30 11:06:59 2017
*filter
:INPUT ACCEPT [1131:246672]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [1126:247604]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-SERVICES - [0:0]
-A INPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
COMMIT
```
Doing a wget against the dashboard, which does have an IPTables entry works fine, however there are no records in place for performing NAT for DNS requests.

Additionally, using a cluster (via profile switching) created under Minikube 0.23 works fine.

**Comment by davefinster** [comment] 2017-11-30 23:34
Seems that using ```--bootstrapper kubeadm``` is a workaround.

**Comment by r2d4** [comment] 2017-12-01 03:52
Closing this as a dupe of #2240, since it is the same issue.  See this comment for 3 different work arounds, or wait for #2251 to be released.

https://github.com/kubernetes/minikube/issues/2240#issuecomment-348319371

**Comment by r2d4** [comment] 2017-12-01 05:05
Fixed in 0.24.1 https://github.com/kubernetes/minikube/releases/tag/v0.24.1

**Closed by r2d4** 2017-12-01 05:05 UTC
