### ISSUE TITLE
changing Service IP Range breaks cluster DNS, local docker registery addon, TLS

### ISSUE THREAD

**Issue by donaldguy** [kubernetes/minikube#2008] opened 2017-09-26 21:35 UTC
departing from the issue format as this is more a worklog issue in case I get derailed before I can write a comprehensive patch. hope that's okay

As discussed in comments on #2006 and as a generalization of #2005 (which was just about TLS), you can change ServiceClusterIPRange via `--extra-options=apiserver.ServiceClusterIPRange` and the changes make it to the parts of `localkube` that actually run service IP allocation, but a number of hardcoded values from https://github.com/kubernetes/minikube/blob/023aea13a24d1c8320d541974ed1d9d2fccb13ae/pkg/util/constants.go#L25-L28

persist and lead to incorrect values in apiserver cert generation, DNS configuration, and docker registry

These hardcoded values should probably be replaced with functions that use the `net.IPNet` returned from https://github.com/kubernetes/minikube/blob/023aea13a24d1c8320d541974ed1d9d2fccb13ae/vendor/k8s.io/kubernetes/pkg/master/services.go#L28-L31

with or without an additional use of https://github.com/kubernetes/minikube/blob/023aea13a24d1c8320d541974ed1d9d2fccb13ae/vendor/k8s.io/kubernetes/pkg/registry/core/service/ipallocator/allocator.go#L263-L264

to do the DNS server allocation at 10 (there may be a better approach here).

In addition to these util constants and their use in
```
$ (ag -l DefaultServiceClusterIP ; ag -l DefaultDNSIP; ag -l DefaultInsecureRegistry ) | sort -u
cmd/localkube/cmd/options.go
cmd/minikube/cmd/start.go
pkg/localkube/localkube.go
pkg/minikube/bootstrapper/certs.go
pkg/minikube/bootstrapper/kubeadm/kubeadm.go
pkg/util/constants.go
```

there are separate hardcodes of `10.0.0`  IPs in the kubeadm bootstrapper template, the dns addon svc.yaml  and a couple tests

```
$ ag '10\.0\.0\.' --go --yaml --ignore vendor
deploy/addons/kube-dns/kube-dns-svc.yaml
27:  clusterIP: 10.0.0.10

pkg/localkube/localkube_test.go
36:	_, ipRange, _ := net.ParseCIDR("10.0.0.0/24")
95:	_, ipRange, _ := net.ParseCIDR("10.0.0.0/24")
113:	_, ipRange, _ := net.ParseCIDR("10.0.0.0/24")

pkg/minikube/bootstrapper/kubeadm/kubeadm.go
52:Environment="KUBELET_DNS_ARGS=--cluster-dns=10.0.0.10 --cluster-domain=cluster.local"

pkg/util/constants.go
25:	DefaultServiceClusterIP   = "10.0.0.1"
27:	DefaultDNSIP              = "10.0.0.10"
28:	DefaultInsecureRegistry   = "10.0.0.0/24"

pkg/util/crypto_test.go
83:	ips := []net.IP{net.ParseIP("192.168.99.100"), net.ParseIP("10.0.0.10")}

test/integration/cluster_dns_test.go
68:	if !strings.Contains(dnsOutput, "10.0.0.1") || !strings.Contains(dnsOutput, "10.0.0.10") {
69:		t.Errorf("DNS lookup failed, could not find both 10.0.0.1 and 10.0.0.10.  Output: %s", dnsOutput)
```

**Comment by donaldguy** [comment] 2017-09-26 21:36
oops this may also be a dupe of #1747 (which I hadn't seen til 2005 was closed while I was writing this)

I'll leave it to a dev to decide if this should be closed

**Comment by r2d4** [comment] 2017-09-28 17:49
Closing as a dupe of #1747, some helpful information in this issue and it'll be linked in that issue

**Closed by r2d4** 2017-09-28 17:49 UTC
