### ISSUE TITLE
hyperkit: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io: read udp x->192.168.64.1:53: i/o timeout

### ISSUE THREAD

**Issue by ChirayuChirayu** [kubernetes/minikube#4265] opened 2019-05-16 02:10 UTC
I am running the following command on my mac(Mac OS high Sierra(10.13.6)

 $ /usr/local/bin/minikube start --vm-driver=hyperkit

😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing hyperkit VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.64.15
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 192.168.64.1:53: read udp 192.168.64.15:48975->192.168.64.1:53: i/o timeout
, error: exit status 1
: Process exited with status 1
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ...
:
$ /usr/local/bin/minikube start --vm-driver=hyperkit

I am getting the following error:

````Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml stdout: stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 192.168.64.1:53: read udp 192.168.64.15:48975->192.168.64.1:53: i/o timeout````

If I run ````docker pull k8s.gcr.io/kube-apiserver:v1.14.1````, then the command is successful. I have tried restarting docker on my mac several times. I have also changed dns settings to 8.8.8.8 as suggested in some other posts but it has not helped:

**$ /usr/local/bin/minikube start --vm-driver=hyperkit

😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing hyperkit VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.64.15
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.3-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on 192.168.64.1:53: read udp 192.168.64.15:48975->192.168.64.1:53: i/o timeout
, error: exit status 1
: Process exited with status 1
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ...**

As mentioned in a forum post,the users from China are facing this issue.But I am from India and not behind any proxy

**Comment by tstromberg** [comment] 2019-05-16 17:50
It seems like the VM is timing out accessing the hyperkit DNS service. Do you mind running:

`sudo lsof -ni:53` 

as well as:

`ls -la /usr/local/bin/*hyperkit*`

**Comment by ChirayuChirayu** [comment] 2019-05-17 05:38
sudo lsof -ni:53 does not return anything

ls -la /usr/local/bin/*hyperkit*

returns following

```
-rwsr-xr-x  1 root     wheel  27785684 May 15 13:09 /usr/local/bin/docker-machine-driver-hyperkit
lrwxr-xr-x  1 sushank  staff        67 May 15 18:03 /usr/local/bin/hyperkit -> /Applications/Docker.app/Contents/Resources/bin/com.docker.hyperkit
```

**Comment by jasmas** [comment] 2019-05-22 16:37
I have the same problem.

**Comment by jasmas** [comment] 2019-05-22 16:47
I think this has something to do with DNS filtering or manipulation on your internet connection. I switched my system over to secure DNS resolution using cloudflared and this worked fine.

**Comment by tstromberg** [comment] 2019-09-20 20:21
This issue appears to be a duplicate of #3036, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-09-20 20:21 UTC
Labels: area/dns, co/hyperkit, triage/support
