### ISSUE TITLE
Ability to assign "external" IP address to LoadBalancer

### ISSUE THREAD

**Issue by whitecolor** [kubernetes/minikube#950] opened 2016-12-23 12:31 UTC
**FEATURE REQUEST**

Currently minikube doesn't support `LoadBalancer`, it doesn't assign to it external IP. And services are supposed to access using [`minikube service service-name...`](https://github.com/kubernetes/minikube/issues/384) is uses port mapping and it is quite cumbersome (esp if service exposes more then one port)

It would be nice if `minikube` could assign "external" IP from some defined pool of addresses, that should be somehow made available from dev host (linux, mac, windows machine) - I'm not a network expert not sure particular way it should be done - but surely it is possible, as it is possible to access 172.x address of docker containers directly.

That would give an ability for more easier access to services/pods without need of port mapping. One could just static records to `hosts` files and access services via friendly DNS names.

Port mapping is very inconvenient way of accessing containers. For example currently for development I use docker-compose and [dnsdock](https://github.com/aacebedo/dnsdock) that tracks the containers IP's and labels and allows to access directly them with DNS names.

What do you think about such ability?

**Comment by r2d4** [comment] 2016-12-23 18:12
Does kube-dns solve your problem?

http://kubernetes.io/docs/admin/dns/

**Comment by r2d4** [comment] 2016-12-23 22:07
We chatted offline.  Closing this as a dupe of https://github.com/kubernetes/minikube/issues/38

**Closed by r2d4** 2016-12-23 22:07 UTC
Labels: kind/feature
