### ISSUE TITLE
Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

### ISSUE THREAD

**Issue by imorti** [kubernetes/minikube#6028] opened 2019-12-08 01:40 UTC
**The exact command to reproduce the issue**:
```minikube start```

`Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1`

**The full output of the command that failed**:<details>

Unable to start VM: create: Error creating machine: Error in driver during machine creation: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by zedtux** [comment] 2019-12-09 09:11
I have it too.

**Comment by tstromberg** [comment] 2019-12-16 20:59
This is likely a dupe of #5594 - what version of macOS are you on?

**Comment by zedtux** [comment] 2019-12-17 05:38
I'm running macOS Catalina 10.15.2 and D4M 2.1.7.0 (channel edge).

**Comment by tstromberg** [comment] 2019-12-19 23:23
If `--vm-driver` is not specified, minikube defaults to hyperkit, so it's likely related.

Interesting that you are already on bleeding edge versions though.

**Comment by imorti** [comment] 2019-12-23 21:57
yeah I'm on Catalina. Will pass in ```--vm-driver``` from now on. Thanks.

**Comment by medyagh** [comment] 2020-01-22 19:59
@imorti glad to see the issue solved, I will close this, please feel free to re-open

**Closed by medyagh** 2020-01-22 19:59 UTC
Labels: triage/needs-information, triage/support
