### ISSUE TITLE
Unable to pull images in minikube due to dockerhub pull limit

### ISSUE THREAD

**Issue by fans3210** [kubernetes/minikube#9760] opened 2020-11-21 10:26 UTC
**Steps to reproduce the issue:** 

1. minikube start --driver=hyperkit --extra-config 'controller-manager.feature-gates=TTLAfterFinished=true' --feature-gates="TTLAfterFinished=true" --disk-size 50GB --cpus 4 --memory 8192 --addons=ingress
2. minikube addons enable ingress

**Full output of `minikube start` command used, if not already included:**

Failed to pull image "jettech/kube-webhook-certgen:v1.2.2": rpc error: code = Unknown desc = Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit

I've already upgraded to pro account and tried $ docker login in both minikube vm and macos system. However it still doesn't work. Is there a way to let minikube able to use my dockerhub account? How to resolve this limit issue?

**Comment by afbjorklund** [comment] 2020-11-21 10:51
You could add it to the minikube cache, as a workaround ?

**Comment by afbjorklund** [comment] 2020-11-21 10:52
Otherwise it sounds like pull secrets

**Comment by fans3210** [comment] 2020-11-21 15:40
@afbjorklund Thanks for the suggestion but I think dockerhub takes time to process my request for plan upgrade. I also noticed that they limit the number of pull requests using ip address. So I switched to my mobile data and currently it seems working.

**Comment by spowelljr** [comment] 2021-03-24 18:47
Hi @fans3210, this doesn't seem like an issue with minikube, and more like a DockerHub specific error. I'm going to close this issue, but feel free to reopen if you see fit, thanks!

**Closed by spowelljr** 2021-03-24 18:47 UTC
Labels: co/hyperkit, kind/support, lifecycle/rotten

**Comment by Stetchy** [comment] 2021-08-05 16:27
Hey @spowelljr, recently came across this issue, or at least very similar.

I do not have a Docker pro account so the rate limiting with Docker Hub applies and I hit it when enabling the addons, if I have had to wipe and re-pull images if I am debugging/developing our internal DX tooling.

The issue is is that the command `minikube addons enable <addon>` uses pre-defined registries, some of which are docker.io / dockerhub. Which, if you hit the rate limit will fail and cause an image pull back off as Docker is restricting image pulls.

Is there a way to specify the registry to pull the addon image(s) from? Using registry mirror or insecure registry command line params doesn't change the registry in this instance. The reason for this is we have an internal ECR mirror for certain images we used to pull from Docker Hub prior to the rate limiting.

Hope this makes sense, thanks!

**Comment by spowelljr** [comment] 2021-08-05 18:35
Hi @Stetchy, thanks for reaching out!

This is something you should be able to do, we have a page about it in our documentation.

https://minikube.sigs.k8s.io/docs/handbook/addons/custom-images/

Let me know if this fulfills your need, thanks!

**Comment by Stetchy** [comment] 2021-08-06 08:10
Brilliant - thanks @spowelljr! I think I was just searching for the wrong things 😄  thanks a mill - that fixed it
