### ISSUE TITLE
Unable to start minikube in Oracle-VM running Oracle Linux-7.5

### ISSUE THREAD

**Issue by kgeyan** [kubernetes/minikube#6114] opened 2019-12-18 11:53 UTC
# minikube start --vm-driver=none
* minikube 1.6.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.6.1
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.5.2 on Oracle 7.5 (xen/amd64)
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running none "minikube" VM ...
* Waiting for the host to be provisioned ...
* Retriable failure: detecting provisioner: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
* Deleting "minikube" in none ...
*
X Unable to start VM: detecting provisioner: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
*
* Sorry that minikube crashed. 

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment] 2019-12-18 23:56
This issue appears to be a duplicate of #4132, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-18 23:56 UTC
