### ISSUE TITLE
precreate: VirtualBox is configured with multiple host-only adapters with the same IP. Please remove one

### ISSUE THREAD

**Issue by dcialdella** [kubernetes/minikube#4289] opened 2019-05-19 16:54 UTC
starting Minilube start
Xubuntu
Physical server has

minikube start
😄  minikube v1.0.1 on linux (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: create: precreate: VirtualBox is configured with multiple host-only adapters with the same IP "192.168.99.1". Please remove one

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

ifconfig
enx1065300c2f14: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        ether 10:65:30:0c:2f:14  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 92121  bytes 1105289276 (1.1 GB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 92121  bytes 1105289276 (1.1 GB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlp2s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.10.65  netmask 255.255.255.0  broadcast 192.168.10.255
        inet6 fe80::4ecc:97c0:4fee:2791  prefixlen 64  scopeid 0x20<link>
        ether 00:24:d6:e6:3a:cf  txqueuelen 1000  (Ethernet)
        RX packets 564131  bytes 763876728 (763.8 MB)
        RX errors 0  dropped 33  overruns 0  frame 0
        TX packets 118576  bytes 28585519 (28.5 MB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

**Comment by dcialdella** [comment] 2019-05-19 16:56
The VMNet2 is disabled, but anyway, Minikube think it has two.

**Comment by tstromberg** [comment] 2019-05-22 03:32
Please try this solution: https://github.com/docker/machine/issues/3584#issuecomment-360972126

Let me know if it works for you.

**Comment by tstromberg** [comment] 2019-05-24 00:22
This issue appears to be a duplicate of #3870, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed by tstromberg** 2019-05-24 00:22 UTC
Labels: co/virtualbox, help wanted, priority/backlog, triage/support
