### ISSUE TITLE
Unable to initialise minikube

### ISSUE THREAD

**Issue by rsotogar** [kubernetes/minikube#13203] opened 2021-12-20 11:19 UTC
### What Happened?

I am new to minikube and after installing minikube using brew, then running`minikube start`, apparently kubelet is not found:

[WARNING Swap]: running with swap on is not supported. Please disable swap
[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'

error execution phase preflight: [preflight] Some fatal errors occurred:

[ERROR KubeletVersion]: couldn't get kubelet version: cannot execute 'kubelet --version': exit status 255
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/7744864/logs.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment] 2022-01-19 20:21
Hi @rsotogar, this a duplicate of https://github.com/kubernetes/minikube/issues/12274 so I'm going to close this issue.

The steps to resolve this issue are as follows:
1. Make sure you're using the arm64 binary of minikube
2. Run minikube delete --all --purge
3. Try starting minikube again

**Closed by spowelljr** 2022-01-19 20:21 UTC
