### ISSUE TITLE
minikube does not support exposing services to Codespaces

### ISSUE THREAD

**Issue by worldofgeese** [kubernetes/minikube#15928] opened 2023-02-26 11:36 UTC
### What Happened?

A [user on the #minikube Slack channel](https://kubernetes.slack.com/archives/C1F5CT6Q1/p1669147969881609) previously asked for help getting minikube to work on GitHub Codespaces. I have confirmed whether exposed as a nodeport or load balancer with `minikube service` or `minikube tunnel` respectively, minikube attempts to expose services using the internal VM network of Codespaces, 193.168.49.2 and not localhost. This is a non-starter for any workflows on Codespaces requiring service access.

### Attach the log file

I've since moved to  using k3d and kind in all my Dev Container and Codespaces workflows, which do expose to 0.0.0.0 and don't have logs to offer but it should be easy to reproduce: fire up [this minimal Dev Container containing minikube](https://github.com/ACSG-64/Codespaces-demo/blob/main/.devcontainer/devcontainer.json), deploy a hello-world service, then attempt to expose with `minikube service` or `minikube tunnel` with the appropriate ingress controller deployed if desired.

### Operating System

Linux

### Driver

Docker

**Comment by afbjorklund** [comment] 2023-02-26 12:34
It would be good if you could explain what you are proposing to change, and how it would help the minikube user ?

Deploying the development k8s cluster to localhost, or to a private VM network, is done on purpose (for security)

**Comment by worldofgeese** [comment] 2023-02-26 13:08
Because Codespaces is already running in a secure VM, minikube should at least expose services to 127.0.0.1 and not the Codespaces VM. Currently minikube will expose a service as http://192.168.49.2:$PORT but `minikube dashboard` (which does work in Codespaces) to 127.0.0.1. Codespaces does support rewriting links that expose to localhost or 127.0.0.1 (see how that works [here](https://docs.github.com/en/codespaces/developing-in-codespaces/forwarding-ports-in-your-codespace)) but not if they expose to the IP of the VM.

Users will expect minikube to *just work* in Codespaces. There's no current method that I know of fix minikube for use in Codespaces. Even the GitHub development team chooses [k3d over minikube](https://github.com/cse-labs/kubernetes-in-codespaces) for this and performance reasons.

We're going to see a lot more users running cloud development environments: it'd be great to see this use-case supported.

**Comment by afbjorklund** [comment] 2023-02-26 13:32
This sounds like it would need more adoption, similar to the katacoda examples, that are currently using "none" driver.

But the docker driver is _supposed_ to publish all the ports to localhost, if it is running in a container (and not in a VM)

> We're going to see a lot more users running cloud development environments in the future: it'd be great to see this use-case supported.

That is true, I don't think the current "let's log in as root on the control plane" tutorial is pointing in the right direction...

* https://github.com/kubernetes/minikube/issues/4730

**Comment by afbjorklund** [comment] 2023-02-26 13:37
Previous attempts to make minikube work better in Lima and in Multipass have not been so successful.

**Comment by afbjorklund** [comment] 2023-02-26 13:52
The earlier attempts are mostly about providing virtual machines, and then running the "none" driver.

I was wondering whether running with "KIC" (or kind or k3s) would be a _separate_ scenario / tutorial ?

* https://github.com/kubernetes/minikube/issues/15651

The single-node cluster is simpler to explain, less magic and less moving parts, but it is also more limited.
(assuming there that setting up a multi-node VM cluster is out of scope, due to  extra resource requirements)

So instead of explaining how to set up the cluster on localhost from within a virtual machine, it would show
how to set up a cluster using fakenodes running in a container runtime (that is: KIC) on said virtual machine ?

The same `minikube start` is _supposed_ to work in both scenarios...

But the extra complexity of the virtual machine not being on the actual user machine, could need some extra care.

Knowing how it is _supposed_ to work (with for instance kind or k3d), would make it clearer how to fix for minikube

**Comment by afbjorklund** [comment] 2023-02-26 14:05
I consider k8s vs k3s to be out of scope for this discussion, there are pros and cons and better discussed elsewhere...

But if it is working with `kind`, then it should work with `minikube`. Similar to the "if it is working with `kubeadm`", before ?

**Comment by worldofgeese** [comment] 2023-02-26 14:07
> I consider k8s vs k3s to be out of scope for this discussion, there are pros and cons and better discussed elsewhere...

I hope that's not the takeaway from my issue: I value the diversity and health of all these projects. With k3d and kind, both do just work given pure defaults so perhaps their implementation can serve as an example for minikube's?

**Comment by afbjorklund** [comment] 2023-02-26 14:11
Probably just bugs, similar to the current issues with the "none" driver.

**Comment by afbjorklund** [comment] 2023-02-27 07:05
@worldofgeese : what is needed, is to enable extra port-forwarding. the same that is currently being done for (and hardcoded to) Docker Desktop. this will set up a localhost tunnel, that Codespaces will see and forward to the real host.

```go
// NeedsPortForward returns true if driver is unable provide direct IP connectivity
func NeedsPortForward(name string) bool {
        if !IsKIC(name) {
                return false
        }
        if oci.IsExternalDaemonHost(name) {
                return true
        }
        // Docker for Desktop
        if runtime.GOOS == "darwin" || runtime.GOOS == "windows" || detect.IsMicrosoftWSL() {
                return true
        }

        si, err := oci.CachedDaemonInfo(name)
        if err != nil {
                panic(err)
        }
        if runtime.GOOS == "linux" && si.DockerOS == "Docker Desktop" {
                return true
        }
        return si.Rootless
}
```

Since the `docker0` bridge is visible from the host (the console), there is normally no need to tunnel that when using Docker Engine... But it could be added as a configuration, and that could be enabled when Codespaces is detected ?

Was confused about 192.168.49.2 mentioned as a VM.

**Comment by afbjorklund** [comment] 2023-02-27 07:07
The environment variable to look for is called `CODESPACES`.

https://docs.github.com/en/codespaces/developing-in-codespaces/default-environment-variables-for-your-codespace

**Comment by worldofgeese** [comment] 2023-02-27 09:44
> @worldofgeese : what is needed, is to enable extra port-forwarding. the same that is currently being done for (and hardcoded to) Docker Desktop. this will set up a localhost tunnel, that Codespaces will see and forward to the real host.
> 
> >

Ah, that might explain why I have difficulty reaching services in Dev Containers on WSL when the container engine is provided by the `docker-ce` package and not Docker Desktop but that is another issue if I wish to try and replicate.

**Comment by afbjorklund** [comment] 2023-02-27 09:46
Same code, different bug ?

**Comment by phillies** [comment] 2023-04-21 11:02
I can confirm this issue, we use codespaces w/ minikube for a simple dev environment and we need the NodePort from one service exposed via codespaces. Using `--listen-address='127.0.0.1'` did not work.

My workaround for now: installing an ssh server in codespaces and creating an ssh tunnel with port forwarding from `192.168.49.2:xxxx` to `xxxx`, which makes the port accessible from the outside.

**Comment by afbjorklund** [comment] 2023-04-21 11:25
> My workaround for now: installing an ssh server in codespaces and creating an ssh tunnel with port forwarding

That is very similar to what `NeedsPortForward`  does.

**Closed** 2024-02-19 02:02 UTC
Labels: kind/feature, priority/awaiting-more-evidence, lifecycle/rotten, co/docker-driver
