### ISSUE TITLE
"minikube dashboard" crashes

### ISSUE THREAD

**Issue by ensonic** [kubernetes/minikube#6679] opened 2020-02-19 08:23 UTC
**The exact command to reproduce the issue**:

```
minikube dashboard
🔌  Enabling dashboard ...

💣  Unable to enable dashboard: [enabling addon deploy/addons/dashboard/dashboard-clusterrole.yaml: error creating file at /etc/kubernetes/addons/dashboard-clusterrole.yaml: open /etc/kubernetes/addons/dashboard-clusterrole.yaml: permission denied]

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

```
sudo minikube dashboard
[sudo] password for ensonic: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x13cee62]

goroutine 1 [running]:
k8s.io/minikube/cmd/minikube/cmd.glob..func5(0x242c8c0, 0x24d05d0, 0x0, 0x0)
	/app/cmd/minikube/cmd/dashboard.go:79 +0x152
github.com/spf13/cobra.(*Command).execute(0x242c8c0, 0x24d05d0, 0x0, 0x0, 0x242c8c0, 0x24d05d0)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x242da40, 0x13, 0x1, 0xc0002cc560)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:106 +0x621
main.main()
	/app/cmd/minikube/main.go:66 +0xe7
```

**Minikube version**:
```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad-dirty
```

**The operating system version**:
```
 uname -a
Linux ensonic.muc.corp.google.com 5.2.17-1rodete3-amd64 #1 SMP Debian 5.2.17-1rodete3 (2019-10-21 > 2018) x86_64 GNU/Linux
```

**Comment by afbjorklund** [comment] 2020-02-22 12:03
Duplicate of #6324, please try again with a newer version of minikube (v1.5.2 is old)

**Closed by afbjorklund** 2020-02-22 12:03 UTC

**Comment by ensonic** [comment] 2020-02-24 12:21
Sorry typo, it was 1.6.2.

**Comment by afbjorklund** [comment] 2020-02-26 06:14
Still old though (1.7.2)
