### ISSUE TITLE
minikube status hangs for a seemingly indefinite amount of time

### ISSUE THREAD

**Issue by MarlonGamez** [kubernetes/minikube#9812] opened 2020-11-30 21:30 UTC
`minikube status` seems to hang when reaching the following step:
```bash
I1130 12:56:09.108407   65296 sshutil.go:45] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/Users/marlongamez/.minikube/machines/minikube/id_rsa Username:docker}`
```

**Steps to reproduce the issue:** 

1. Run `minikube status`

**Full output of failed command:** 
<details>

```bash
❯ minikube status --alsologtostderr
I1130 12:56:08.360112   65296 out.go:185] Setting OutFile to fd 1 ...
I1130 12:56:08.360945   65296 out.go:237] isatty.IsTerminal(1) = true
I1130 12:56:08.360956   65296 out.go:198] Setting ErrFile to fd 2...
I1130 12:56:08.360962   65296 out.go:237] isatty.IsTerminal(2) = true
I1130 12:56:08.361067   65296 root.go:279] Updating PATH: /Users/marlongamez/.minikube/bin
I1130 12:56:08.361521   65296 out.go:192] Setting JSON to false
I1130 12:56:08.361850   65296 mustload.go:66] Loading cluster: minikube
I1130 12:56:08.364448   65296 status.go:238] checking status of minikube ...
I1130 12:56:08.366446   65296 cli_runner.go:110] Run: docker container inspect minikube --format={{.State.Status}}
I1130 12:56:08.751913   65296 status.go:313] minikube host status = "Running" (err=<nil>)
I1130 12:56:08.751979   65296 host.go:66] Checking if "minikube" exists ...
I1130 12:56:08.752422   65296 cli_runner.go:110] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" minikube
I1130 12:56:08.925307   65296 host.go:66] Checking if "minikube" exists ...
I1130 12:56:08.926281   65296 ssh_runner.go:148] Run: sh -c "df -h /var | awk 'NR==2{print $5}'"
I1130 12:56:08.926437   65296 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1130 12:56:09.108407   65296 sshutil.go:45] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/Users/marlongamez/.minikube/machines/minikube/id_rsa Username:docker}
```

</details>

**Optional: Full output of `minikube logs` command:**
Running minikube logs also seems to hang at the same step. Seems like it's an issue with docker?
<details>

```bash
❯ minikube logs --alsologtostderr
I1130 13:27:17.345843   67061 out.go:185] Setting OutFile to fd 1 ...
I1130 13:27:17.346625   67061 out.go:237] isatty.IsTerminal(1) = true
I1130 13:27:17.346636   67061 out.go:198] Setting ErrFile to fd 2...
I1130 13:27:17.346642   67061 out.go:237] isatty.IsTerminal(2) = true
I1130 13:27:17.346732   67061 root.go:279] Updating PATH: /Users/marlongamez/.minikube/bin
I1130 13:27:17.347021   67061 mustload.go:66] Loading cluster: minikube
I1130 13:27:17.347922   67061 cli_runner.go:110] Run: docker container inspect minikube --format={{.State.Status}}
I1130 13:27:17.544553   67061 host.go:66] Checking if "minikube" exists ...
I1130 13:27:17.545080   67061 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" minikube
I1130 13:27:17.735001   67061 ssh_runner.go:148] Run: systemctl --version
I1130 13:27:17.735178   67061 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1130 13:27:17.921460   67061 sshutil.go:45] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/Users/marlongamez/.minikube/machines/minikube/id_rsa Username:docker}
```

</details>

This seems to point to an issue with my docker setup, tho I'm not sure what. I haven't made any changes that I'm aware of recently

**Comment by MarlonGamez** [comment] 2020-12-01 18:53
I'm going to close this as I believe it was an issue with my docker setup. Was able to see things working again after completely reseting my docker setup.

**Comment by medyagh** [comment] 2020-12-22 19:10
info, seems like restating docker have fixed, but this issue still happens I am gonna re-open till we get to the botoom.

**Comment by ilya-zuyev** [comment] 2021-05-12 18:56
Looks like the issue is resolved now, going to close it.

**Closed by ilya-zuyev** 2021-05-12 18:56 UTC
Labels: kind/support, triage/long-term-support
