### ISSUE TITLE
Unit file cri-docker.socket does not exist

### ISSUE THREAD

**Issue by sirajqs** [kubernetes/minikube#14501] opened 2022-07-03 16:11 UTC
### What Happened?

Failed to enable unit: Unit file cri-docker.socket does not exist.

### Attach the log file

sudo systemctl enable cri-docker.socket: exit status 1

### Operating System

Ubuntu

### Driver

VMware

**Comment by sirajqs** [comment] 2022-07-03 16:12
i m facing some problem while running the command
minikube start --vm-driver=none

**Comment by afbjorklund** [comment] 2022-07-03 18:18
same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by spowelljr** [comment] 2022-07-13 18:21
I'm going to close this issue as it's a duplicate of https://github.com/kubernetes/minikube/issues/14410, please follow along there for solutions, thanks!

**Closed by spowelljr** 2022-07-13 18:21 UTC
Labels: triage/duplicate
