### ISSUE TITLE
hyperkit: open /var/db/dhcpd_leases: no such file or directory

### ISSUE THREAD

**Issue by Gerald-Wheaton** [kubernetes/minikube#8287] opened 2020-05-27 13:29 UTC
Hello, I've been trying to get minikube set up on my mac and I keep running into these errors: either it can't find my IP address or this: 

```minikube v1.10.1 on Darwin 10.14.6
✨  Automatically selected the hyperkit driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory
🔥  Creating hyperkit VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start hyperkit VM. "minikube start" may fix it: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory

💣  error provisioning host: Failed to start host: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
```

I used `minkube start` to get this. Originally I had assigned it a specific amount of storage (`minikube start memory=4048`) but then I reverted to just `minkube start`

yesterday it was actually able to start, after considerable effort, but I am not sure why but after I stopped it, it will not start again.

**Comment by rakeshkarnati1** [comment] 2020-05-28 19:44
Yeah, same here stuck with the same issue. 

```👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.18.2 preload ...
    > preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4: 525.43 MiB
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
🔥  Deleting "minikube" in hyperkit ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: IP address never found in dhcp leases file Temporary error: open /var/db/dhcpd_leases: no such file or directory
🔥  Creating hyperkit VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...```

**Comment by Gerald-Wheaton** [comment] 2020-05-28 20:04
So update, I wasn't able to get hyperkit to work, a colleague of mine suggested it might be a versioning issue on my mac since I don't have a `dchpd_leases` file. I switched over to using virtualbox and everything has been working well since then. Try `brew cask install virtualbox` and then `minikube start --driver=virtualbox`. that worked for me

**Comment by tstromberg** [comment] 2020-05-29 20:35
This issue appears to be a duplicate of #6143 do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-29 20:35 UTC
Labels: triage/support

**Comment by AJNOURI** [comment] 2024-11-06 13:31
Just in case it worked for me with docker driver: (with rancher desktop running)

> ➜  ~ minikube start --driver=docker --nodes 3
> ...
> ➜  ~ kubectl get nodes
> NAME           STATUS   ROLES           AGE   VERSION
> minikube       Ready    control-plane   99s   v1.31.0
> minikube-m02   Ready    <none>          70s   v1.31.0
> minikube-m03   Ready    <none>          48s   v1.31.0
