### ISSUE TITLE
Minikube starting issues on macos 10.15.1

### ISSUE THREAD

**Issue by ourboy** [kubernetes/minikube#5871] opened 2019-11-08 16:17 UTC
Im seeing issues when start minikube on macos 10.15.1
```
minikube start --cpus 4 --memory 8000 --insecure-registry "192.168.0.0/16" --disk-size='40000mb' --vm-driver=virtualbox
😄  minikube v1.5.2 on Darwin 10.15.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing virtualbox VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
💣  minikube is unable to connect to the VM: dial tcp 192.168.99.109:22: connect: operation timed out

This is likely due to one of two reasons:

- VPN or firewall interference
- virtualbox network configuration issue

Suggested workarounds:

- Disable your local VPN or firewall software
- Configure your local VPN or firewall to allow access to 192.168.99.109
- Restart or reinstall virtualbox
- Use an alternative --vm-driver
```

minikube seems to be failing in getting IP's

I have tried to deleting and recreating the VM's and im still seeing this issue. 

```
minikube version: v1.5.2
commit: 792dbf92a1de583fcee76f8791cff12e0c9440ad

Docker version 19.03.4, build 9013bf5

docker-compose version 1.24.1, build 4667896b

docker-machine version 0.16.2, build bd45ab13

kubectl version --client
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.2", GitCommit:"c97fe5036ef3df2967d086711e6c0c405941e14b", GitTreeState:"clean", BuildDate:"2019-10-15T23:42:50Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"darwin/amd64"}
```
[VBox.log](https://github.com/kubernetes/minikube/files/3825611/VBox.log)

**Comment by tstromberg** [comment] 2019-11-10 02:57
This issue appears to be a duplicate of #4540, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

As a temporary workaround, I believe you likely  have the dependencies required to use the hyperkit driver: `minikube delete &&  minikube start --vm-driver=hyperkit`. 

Thank you for reporting this!

**Closed** 2019-11-10 19:08 UTC
