### ISSUE TITLE
could not find capabilities for domaintype=kvm

### ISSUE THREAD

**Issue by zybk1003** [kubernetes/minikube#4285] opened 2019-05-18 05:39 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by tstromberg** [comment] 2019-05-22 03:38
Thank you for sharing your experience!

This issue appears to be a duplicate of #2991, so I will close this in preference to that issue so that we may centralize the information around it. If you feel that this is not in fact a duplicate, please feel free to re-open this issue with more information. Thanks!

**Closed by tstromberg** 2019-05-22 03:38 UTC
