### ISSUE TITLE
Unable to do port forwarding: socat not found

### ISSUE THREAD

**Issue by yissachar** [kubernetes/minikube#68] opened 2016-05-13 15:22 UTC
I'm trying to forward local port 5000 to a pod port 5000 with kubectl:

```
kubectl port-forward --namespace kube-system kube-registry-v0-4icv2_kube-system 5000:5000 &
```

But I get the following error:

```
an error occurred forwarding 5000 -> 5000: error forwarding port 5000 to pod kube-registry-v0-4icv2_kube-system, uid : unable to do port forwarding: socat not found
```

**Comment by luxas** [comment] 2016-05-13 15:23
You need `socat` installed on host I think

**Comment by dlorenc** [comment] 2016-05-13 15:33
We should be able to grab it and put it on our VM like here:
https://github.com/skippbox/boot2k8s/blob/master/builddeps.sh

**Comment by runseb** [comment] 2016-05-13 15:39
@dlorenc you might check how we did it for boot2k8s https://github.com/skippbox/boot2k8s/commit/bb3c207fee9f49ce83fe95aaabbec0ffb042648a

since we had this issue as well.

And I bet folks will want nsenter too :) and kubectl:
https://github.com/skippbox/boot2k8s/commit/f2f694f3513f774cc757f607c419fcbae83ebf24

**Comment by yissachar** [comment] 2016-05-13 19:27
How would I go about updating a running minikube to use the merged PR for this?

**Comment by dlorenc** [comment] 2016-05-13 21:48
Right now minikube uses a version of the iso from a static URL. I have to build and push another iso with that change before you'll pick it up. I'll resolve this once I get a chance to do that.

**Comment by dlorenc** [comment] 2016-05-14 18:48
Should be fixed now. If you rebuild minikube from HEAD, delete your cluster and recreate it you'll get a build with socat.

make out/minikube
out/minikube delete
out/minikube start

**Closed by dlorenc** 2016-05-14 18:48 UTC

**Comment by WillemMali** [comment] 2017-11-14 14:15
I think this may have regressed in the 1.8 beta build, or it might be related to me using `--vm-driver=none` inside a Vagrant `debian/stretch64` image. I'm patching this up by installing `socat` to my Vagrant box but it's not super ideal.

**Comment by r2d4** [comment] 2017-11-14 18:09
@WillemMali not necessarily a regression, as we included `socat` in the ISO image and resolved this issue.  Of course, if you're running the `none` driver, you'll need a whole host of dependencies that kubernetes requires: docker, iptables, socat, certain kernel modules enabled, etc.  I'm not sure if a list exists somewhere.

**Comment by WillemMali** [comment] 2017-11-14 19:33
Ah, that makes sense. If it's not documented please respond, I'll send a PR in later this week but I'm too tired to think right now.
-------- Original message --------From: Matt Rickard <notifications@github.com> Date: 11/14/17  19:10  (GMT+01:00) To: kubernetes/minikube <minikube@noreply.github.com> Cc: WillemMali <willem.mali@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [kubernetes/minikube] Unable to do port forwarding: socat not
  found (#68) 
@WillemMali not necessarily a regression, as we included socat in the ISO image and resolved this issue.  Of course, if you're running the none driver, you'll need a whole host of dependencies that kubernetes requires: docker, iptables, socat, certain kernel modules enabled, etc.  I'm not sure if a list exists somewhere.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kubernetes/minikube","title":"kubernetes/minikube","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/kubernetes/minikube"}},"updates":{"snippets":[{"icon":"PERSON","message":"@r2d4 in #68: @WillemMali not necessarily a regression, as we included `socat` in the ISO image and resolved this issue.  Of course, if you're running the `none` driver, you'll need a whole host of dependencies that kubernetes requires: docker, iptables, socat, certain kernel modules enabled, etc.  I'm not sure if a list exists somewhere. "}],"action":{"name":"View Issue","url":"https://github.com/kubernetes/minikube/issues/68#issuecomment-344346923"}}}

**Comment by r2d4** [comment] 2017-11-15 01:10
No its not documented, but we would gladly accept a PR.  I think there's an upstream issue with the dependencies required for running the kubelet, which we should also document for our none-driver, since that has the same requirements
