### ISSUE TITLE
fresh start: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by guilgom** [kubernetes/minikube#3844] opened 2019-03-10 19:19 UTC
<!-- If you are reporting a bug, please include:

  - How to replicate the error, including the exact `minikube` command-line used.
  - The full output of the command that failed
  - The output of the "minikube logs" command
  - Which operating system version was used
  
Thank you! Please write about your experience below this line: --!>

System: Windows 10 Enterprise  <br/>
minikube version: v0.35.0  <br/>
kubectl client version v1.10.11  <br/>
  
How to replicate the error:  <br/>
=================  <br/>
(after "minikube delete", "del /f .minikube" and "del /f .kube"...) <br/>
<br/>
C:\WINDOWS\system32>minikube start<br/>
<br/>
o   minikube v0.35.0 on windows (amd64)<br/>
> Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...<br/>
-   "minikube" IP address is 192.168.99.112<br/>
-   Configuring Docker as the container runtime ...<br/>
-   Preparing Kubernetes environment ...<br/>
-   Pulling images required by Kubernetes v1.13.4 ...<br/>
-   Launching Kubernetes v1.13.4 using kubeadm ...<br/>
:   Waiting for pods: apiserver!   Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition<br/>
<br/>
*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:<br/>
-   https://github.com/kubernetes/minikube/issues/new<br/>

[minikubes_problem.zip](https://github.com/kubernetes/minikube/files/2949942/minikubes_problem.zip)

**Comment by guoleijie** [comment] 2019-03-11 08:23
same as me.
System: macOS 10.14.2
minikube version: v0.35.0
kubectl:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by pistantan** [comment] 2019-03-11 14:50
Same here, on MacOS as well. On a side note, I am running behind a proxy (setting it with --docker-env). Could that be related?

**Comment by zhen-tasktop** [comment] 2019-03-11 15:01
Same here.

System: macOS 10.14.3
minikube version: v0.35.0
Kubernetes version: v1.13.4

**Comment by heidini** [comment] 2019-03-12 06:23
same as me.
SystemL macOS: 10.14.3
minikube version: v.0.35.0
kubectl version:
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}

$ minikube start
😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.104
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubelet v1.13.4
💾  Downloading kubeadm v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver

**Comment by sunfuze** [comment] 2019-03-12 07:07
Same here
System maxOS: 10.14.3
minikube version: v0.35.0
kubectl version: 
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-30T21:39:16Z", GoVersion:"go1.11.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-02-28T13:30:26Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

$ minikube start

o   minikube v0.35.0 on darwin (amd64)

!   Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperkit driver.
!   To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
!   Alternatively, you may delete the existing VM using `minikube delete -p minikube`

:   Re-using the currently running hyperkit VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.64.16
-   Configuring Docker as the container runtime ...
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.13.4 ...
:   Relaunching Kubernetes v1.13.4 using kubeadm ...
:   Waiting for pods: apiserver

**Comment by emp320** [comment] 2019-03-12 16:21
Same Here 
tried setting proxy in bash profile and in the Docker Client
minikube v0.35.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.101
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
❌  Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.13.4": output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
: Process exited with status 1
🔄  Relaunching Kubernetes v1.13.4 using kubeadm ...
⌛  Waiting for pods: apiserver

**Comment by ENGINEBREATH** [comment] 2019-03-12 17:04
Hi there - I too am hitting the same error!
$PROXYDETAILS below are my exported proxy details unsurprisingly
----------------------------

System: Linux CentOS
Minikube version: v0.35.0
kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5+2.1.1.el7", GitCommit:"fc4837e47691a1b1e6731003f4fc33ab9950bbda", GitTreeState:"archive", BuildDate:"2019-02-05T03:19:54Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

$ CHANGE_MINIKUBE_NONE_USER=true sudo -E minikube start --vm-driver=none
😄  minikube v0.35.0 on linux (amd64)
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running none VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 10.167.205.61
🌐  Found network options:
    ▪ HTTP_PROXY=$PROXYDETAILS
    ▪ HTTPS_PROXY=$PROXYDETAILS
    ▪ NO_PROXY=$PROXYDETAILS
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
🔄  Relaunching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver

**Comment by heidini** [comment] 2019-03-12 21:36
I think it is the issue v0.35.0, please follow the steps below to stop and purge it and download lower version v0.22.3, it works ok.

Waiting for pods: apiserver^Z
[7]+  Stopped                 minikube start
$ minikube stop
✋  Stopping "minikube" in virtualbox ...
🛑  "minikube" stopped.
$ minikube delete
🔥  Deleting "minikube" from virtualbox ...
💔  The "minikube" cluster has been deleted.
$ brew cask uninstall minikube;
==> Uninstalling Cask minikube
==> Unlinking Binary '/usr/local/bin/minikube'.
==> Purging files for version 0.35.0 of Cask minikube
$ curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.22.3/minikube-darwin-amd64 && chmod +x minikube
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 73.8M  100 73.8M    0     0  11.8M      0  0:00:06  0:00:06 --:--:-- 12.9M
$ sudo mv minikube /usr/local/bin$ rm -rf ~/.minikube ~/.kube;
$ minikube start
There is a newer version of minikube available (v0.35.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.35.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Downloading Minikube ISO
 139.09 MB / 139.09 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

**Comment by ENGINEBREATH** [comment] 2019-03-13 12:14
@heidini - can confirm I got a working solution removing Minikube:
>sudo rm /usr/bin/minikube
>sudo minikube stop
>sudo minikube delete && sudo rm -rf ~/.minikube ~/.kube /etc/kubernetes

Then using v0.34.1:
>curl -LO https://storage.googleapis.com/minikube/releases/v0.34.1/minikube-linux-amd64 && sudo install minikube-linux-amd64 /usr/bin/minikube

Then removed environment proxy:
>unset HTTP_PROXY
>unset HTTPS_PROXY
>unset NO_PROXY

Then sent proxy details on command:
>CHANGE_MINIKUBE_NONE_USER=true sudo -E minikube start --vm-driver none --docker-env HTTP_PROXY=$PROXYDETAILS --docker-env HTTPS_PROXY=$PROXYDETAILS --docker-env NO_PROXY=$PROXYDETAILS

**Comment by tstromberg** [comment] 2019-03-13 21:00
My suspicion is that your systems network environment is not routing HTTP requests to the VM properly. 

If this is happening to you, please add the output of the following commands to help me out:

`minikube start <options> --alsologtostderr -v=9`

`minikube status`

`minikube logs`

`minikube ssh docker ps -a`

Thank you.

NOTE: If your minikube output mentions anything about HTTP_PROXY or HTTPS_PROXY, please try setting NO_PROXY up as per https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

**Comment by heidini** [comment] 2019-03-14 00:21
@ENGINEBREATH ,  thanks a log,   I just tried v0.34.1, it also works on my Mac:
$ minikube start
😄  minikube v0.34.1 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.30 MB / 184.30 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.108
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
🚜  Pulling images required by Kubernetes v1.13.3 ...
🚀  Launching Kubernetes v1.13.3 using kubeadm ... 
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

To download the the version for mac, please use the following command:
curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.34.1/minikube-darwin-amd64   && chmod +x minikube
sudo mv minikube /usr/local/bin
minikube start

**Comment by kamiiyu** [comment] 2019-03-14 07:36
Same here on my mac.
There are some permission deny errors on /Users folder,  when I start minikube with options "--alsologtostderr -v=9". (@ENGINEBREATH thanks for your advises)
So when I fix the permission of /Users folder, and tried both v0.34.1 and v0.35, it works for me.

**Comment by MilenkoM** [comment] 2019-03-14 08:17
I am on Ubuntu 18.04, I have a similar problem with extra-config

> minikube start  --extra-config=apiserver.Authorization.Mode=RBAC --extra-config=apiserver.Audit.LogOptions.Path=/var/logs/audit.log   --extra-config=apiserver.Audit.PolicyFile=/etc/kubernetes/addons/audit-policy.yaml

Got this

> 😄  minikube v0.35.0 on linux (amd64)
> 💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
> 🔄  Restarting existing virtualbox VM for "minikube" ...
> ⌛  Waiting for SSH access ...
> 📶  "minikube" IP address is 192.168.99.101
> 🐳  Configuring Docker as the container runtime ...
> ✨  Preparing Kubernetes environment ...
>     ▪ apiserver.Authorization.Mode=RBAC
>     ▪ apiserver.Audit.LogOptions.Path=/var/logs/audit.log
>     ▪ apiserver.Audit.PolicyFile=/etc/kubernetes/addons/audit-policy.yaml
> 🚜  Pulling images required by Kubernetes v1.13.4 ...
> 🔄  Relaunching Kubernetes v1.13.4 using kubeadm ... 
> ⌛  Waiting for pods: apiserver

**Comment by tstromberg** [comment] 2019-03-14 15:33
@MilenkoM - Chances are your extra flags are breaking the restart of apiserver. Please open a new issue with the output of `minikube logs` so that we can look into it.

**Comment by coolteddy** [comment] 2019-03-17 21:27
Had a same issue on mac 10.13.6, minikube version: v0.35.0, VirtualBox version 5.1.18....

😄  minikube v0.35.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.112
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
🔄  Relaunching Kubernetes v1.13.4 using kubeadm ...
⌛  Waiting for pods: apiserver

....stop and delete minikube and rm -rf ~/.kube and ~/.minikube, no luck.
But I have reinstall the virutalbox 5.1 to virtualbox 6. 
All sorted.

```
brew cask uninstall --force virtualbox; 
brew cask install virtualbox
minikube start
```

😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.114
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubelet v1.13.4
💾  Downloading kubeadm v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ...
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!

**Comment by ankitm123** [comment] 2019-03-17 22:04
@ENGINEBREATH's trick worked for me. In my case, the proxy variables were not set, so I could safely omit the --docker-env flag, while starting minikube.
```
CHANGE_MINIKUBE_NONE_USER=true sudo -E minikube start --vm-driver none 
```

**Comment by hollylux** [comment] 2019-03-18 07:06
Got the same error on Ubuntu 18.04 with minikube version v0.35.0. Downgrading to v0.34.0 fixed the error.

-- The output of my console
root@ubuntu1804:~# minikube start --vm-driver=none
There is a newer version of minikube available (v0.35.0).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.35.0

To disable this notification, run the following:
minikube config set WantUpdateNotification false
😄  minikube v0.34.0 on linux (amd64)
🤹  Configuring local host environment ...

⚠️  The 'none' driver provides limited isolation and may reduce system security and reliability.
⚠️  For more information, see:
👉  https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

⚠️  kubectl and minikube configuration will be stored in /root
⚠️  To use kubectl or minikube commands as your own user, you may
⚠️  need to relocate them. For example, to overwrite your own settings:

    ▪ sudo mv /root/.kube /root/.minikube $HOME
    ▪ sudo chown -R $USER /root/.kube /root/.minikube

💡  This can also be done automatically by setting the env var CHANGE_MINIKUBE_NONE_USER=true
🔥  Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 10.0.2.15
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.3
💾  Downloading kubelet v1.13.3
🚜  Pulling images required by Kubernetes v1.13.3 ...
🚀  Launching Kubernetes v1.13.3 using kubeadm ...
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
root@ubuntu1804:~# minikube status
host: Running
kubelet: Running
apiserver: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 10.0.2.15

**Comment by davidthewatson** [comment] 2019-03-21 16:17
I resolved this with the following:

Note that the `no_proxy` includes `192.168.39.1/24`

I'm running minikube on manjaro (arch):

```
yaourt minikube
1 aur/docker-machine-driver-kvm2 0.34.1-1 [installed] (15) (2.82)
    Minikube-maintained KVM driver for docker-machine
2 aur/minikube 0.35.0-1 (10) (1.93)
    Minikube is a tool that makes it easy to run Kubernetes locally
3 aur/minikube-bin 0.35.0-1 [installed] (60) (4.23)
    A tool that makes it easy to run Kubernetes locally
4 aur/minikube-git 0.28.2.r55.gbed9aabaf-1 (0) (0.00)
```

I believe that the doc here: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md
is not complete since it mentions the same exclusion for `192.168.99.1/24`. I'm not sure why my minikube uses a different subnet but it does.
```

minikube start --vm-driver kvm2 --docker-env http_proxy=http://proxy.dog.com:80 --docker-env https_proxy=http://proxy.dog.com:80 --docker-env no_proxy="localhost,127.0.0.1,192.168.39.1/24,10.96.0.0/12"
o   minikube v0.35.0 on linux (amd64)
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.39.199
o   Found network options:
    - HTTP_PROXY=http://proxy.dog.com:80
    - HTTPS_PROXY=http://proxy.dog.com:80
    - NO_PROXY=localhost:127.0.0.1,192.168.39.0/24
-   Configuring Docker as the container runtime ...
    - env http_proxy=http://proxy.dog.com:80
    - env https_proxy=http://proxy.dog.com:80
    - env no_proxy=localhost,127.0.0.1,192.168.39.1/24,10.96.0.0/12
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.13.4 ...
-   Launching Kubernetes v1.13.4 using kubeadm ... 
:   Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!
`
```

The results are as you'd expect:
```

 kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-86c58d9df4-4rd8w               1/1     Running   0          96s
kube-system   pod/coredns-86c58d9df4-j4t9d               1/1     Running   0          96s
kube-system   pod/etcd-minikube                          1/1     Running   0          53s
kube-system   pod/kube-addon-manager-minikube            1/1     Running   0          104s
kube-system   pod/kube-apiserver-minikube                1/1     Running   0          57s
kube-system   pod/kube-controller-manager-minikube       1/1     Running   0          49s
kube-system   pod/kube-proxy-rx59r                       1/1     Running   0          96s
kube-system   pod/kube-scheduler-minikube                1/1     Running   0          40s
kube-system   pod/kubernetes-dashboard-ccc79bfc9-xnb9w   1/1     Running   2          95s
kube-system   pod/storage-provisioner                    1/1     Running   0          95s

NAMESPACE     NAME                           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes             ClusterIP   10.96.0.1      <none>        443/TCP         107s
kube-system   service/kube-dns               ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP   103s
kube-system   service/kubernetes-dashboard   ClusterIP   10.96.146.97   <none>        80/TCP          95s

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/kube-proxy   1         1         1       1            1           <none>          103s

NAMESPACE     NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                2/2     2            2           103s
kube-system   deployment.apps/kubernetes-dashboard   1/1     1            1           95s

NAMESPACE     NAME                                             DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-86c58d9df4               2         2         2       96s
kube-system   replicaset.apps/kubernetes-dashboard-ccc79bfc9   1         1         1       95s

```

**Comment by sultanbaabaa** [comment] 2019-03-26 02:24
Hello

m trying minikube installation on Windows 7 system but its getting failed due to following errors (detailed logs attached):
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-apiserver:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net
/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-controller-manager:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io
/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-scheduler:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net
/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/kube-proxy:v1.13.4: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/htt
p: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/pause:3.1: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: reques
t canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/etcd:3.2.24: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: requ
est canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1
        [ERROR ImagePull]: failed to pull image k8s.gcr.io/coredns:1.2.6: output: Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: re
quest canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
, error: exit status 1  
[Minikube Failure Logs.txt](https://github.com/kubernetes/minikube/files/3006241/Minikube.Failure.Logs.txt)

**Comment by reprisle** [comment] 2019-04-02 21:52
Hi there,
Having the same issue on mac 10.14.3, minikube version: v1.0.0, VirtualBox version 6.0.4 r128413
I have run the command bellow, after removing the ~/.minikube/ and ~/.kube/

`minikube start <options> --alsologtostderr -v=9`

And I'm getting this error:
```

I0402 22:20:01.532121    9653 round_trippers.go:386] curl -k -v -XGET  -H "Accept: application/json, */*" -H "User-Agent: minikube/v0.0.0 (darwin/amd64) kubernetes/$Format" 'https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=component%3Dkube-apiserver'
I0402 22:20:31.533744    9653 round_trippers.go:405] GET https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=component%3Dkube-apiserver  in 30001 milliseconds
I0402 22:20:31.533805    9653 round_trippers.go:411] Response Headers:
I0402 22:20:31.533834    9653 kubernetes.go:129] error getting Pods with label selector "component=kube-apiserver" [Get https://192.168.99.100:8443/api/v1/namespaces/kube-system/pods?labelSelector=component%3Dkube-apiserver: dial tcp 192.168.99.100:8443: i/o timeout]
```

And keep waiting until raise the error:

😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ...
⌛  Waiting for pods: apiserver

💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDWRN: == FIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connailed to ect: connection refused
    error: no objects passed to apply
    error: no objects passed to apply

**Comment by tstromberg** [comment] 2019-04-04 17:58
If you run into this:

* If your minikube output mentions anything about  HTTP_PROXY or HTTPS_PROXY, this error likely means that your NO_PROXY environment variable is misconfigured. Please see: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

* If not, please attach the output of `minikube logs`. Otherwise this will be impossible to debug.

Thanks!

**Comment by katylava** [comment] 2019-04-08 17:45
I found a related issue that said to turn off your VPN, especially if you use Cisco AnyConnect, and restart your computer. That cleared up this issue for me.

**Comment by binodluitel** [comment] 2019-04-09 16:58
Having the same problem

![Screen Shot 2019-04-09 at 11 57 31 AM](https://user-images.githubusercontent.com/592437/55819574-b21c5c80-5abe-11e9-886f-f0b128ccda17.png)


✘ 09:09:33 ~ $ minikube delete
🔥  Deleting "minikube" from virtualbox ...
💔  The "minikube" cluster has been deleted.

✔ 11:38:03 ~ $ minikube start --host-only-cidr "192.168.5.1/24"
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.5.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ...
⌛  Waiting for pods: apiserver
💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed to apply
    error: no objects passed toWRN: == Error getting default service account, retry in 0.5 second ==
    error: no objects passed to apply

✘ 11:51:16 ~ $ minikube version
minikube version: v1.0.0

✔ 11:53:58 ~ $

**Comment by binodluitel** [comment] 2019-04-09 17:20
@coolteddy thanks a lot
Updating to latest Virtual box solved the problem for me.
https://github.com/kubernetes/minikube/issues/3844#issuecomment-473716605

![Screen Shot 2019-04-09 at 12 19 59 PM](https://user-images.githubusercontent.com/592437/55820925-d3327c80-5ac1-11e9-9928-763914c3c43b.png)

**Comment by gkbijarniya** [comment] 2019-04-11 15:50
I also faced the same problem and it caused after using/connecting Cisco AnyConnect VPN. Similar networking issue I have seen earlier as well with Virtualbox VM networks.

So basically when we disconnect the VPN it removes the existing routing for VirtualBox networks. So the solution is ifconfig down & ifconfig for all Virtualbox nets.

I use below function in .bashrc file and run it whenever I face this issue.

```bash
function vb()
{
        setopt shwordsplit
        ifs=`VBoxManage list hostonlyifs| grep -w 'Name:'| awk '{print $2}'`
                for i in $ifs
                        do
                                sudo ifconfig $i down && sudo ifconfig $i up
                                echo "Done for $i"
                        done
}
```
```bash
# source ~/.bashrc 
# vb 
```

**Comment by UmamaheshMaxwell** [comment] 2019-04-16 04:36
Yeah, I too have this problem and I always used to get this below error in my Mac machine.

`Fatal error: Error getting controller pod for port-forwarding` 

So I always run below commands. (provided that you have virtualbox installed) 

```
minikube delete
minikube start
```

**Comment by repetty** [comment] 2019-04-16 15:55
> I found a related issue that said to turn off your VPN, especially if you use Cisco AnyConnect, and restart your computer. That cleared up this issue for me.

I did all the hard things first but a restart after having used CiscoVPN a couple weeks ago is what cleared the minikube startup problem I was having ("Waiting for SSH access ...").

This seems like a significant clue to the problem... Maybe my Mac's networking state was in an unexpected configuration as a result of running CiscoVPN. Other's have reported success after doing upgrades and downgrades but I'm wondering if they did not realize that they did other things that might have also had an effect on curing their problem... like rebooting or sleeping (I do neither).

**Comment by andricchan** [comment] 2019-04-17 08:10
I have the same problem no matter which version of minikube used. 
My environment is behind a proxy and I fixed this by settings a correct NO_PROXY env.
..
"minikube" IP address is 10.0.2.15
..

so I config

export NO_PROXY=localhost,127.0.0.1,10.0.2.0/24

minikube start

**Comment by charlseo** [comment] 2019-04-18 01:13
Same issue occurred with mac using minikube v1.0.0. I tried the possible resolution mentioned in this thread but none worked except updating VB version to the latest (from 5.2.26 to 5.2.28)

I'm also using cisco vpn but I turned it off during starting minikube. Will try with ciscoVPN on to see if it works

**Comment by charlseo** [comment] 2019-04-18 01:17
Confirmed minikube started successfully with cisco Anyconnect on after VB upgrade.

**Comment by xyxzfj** [comment] 2019-04-27 15:32
Same issue. 

macOS Mojave 10.14.4 (18E226)
VirtualBox-6.0.6-130049-OSX
Using proxifier to make virtualbox to use proxy. So proxy-related problems are all avoided.
minikube version: v1.0.0

After stuck in `Waiting for pods: apiserver`, restart host (the Mac) and re-run `minikube start`,  and `🏄  Done! Thank you for using minikube!` occurs.

**Comment by ashishdhirwan** [comment] 2019-04-30 08:02
This worked for me!!!

minikube delete
minikube start

regards

**Comment by tstromberg** [comment] 2019-05-22 18:24
I believe this issue was resolved in the v1.1.0 release. Please try upgrading to the latest release of minikube, and if the same issue occurs, please re-open this bug. Thank you opening this bug report, and for your patience!

**Closed by tstromberg** 2019-05-22 18:24 UTC
Labels: area/networking, co/apiserver, ev/apiserver-timeout, priority/important-longterm, reviewed/2019q2, triage/needs-information

**Comment by joan38** [comment] 2019-06-09 23:21
Same issue with 1.1.1

**Comment by lucasrz** [comment] 2019-06-19 17:34
Same issue here with 1.1.1 on macOS Mojave 10.14.4

**Comment by hkousha** [comment] 2019-06-21 19:41
same with 1.1.1 macOS Mojave 10.14.5 virtualbox: 5.2.30r130521

**Comment by DavidChenLiang** [comment] 2019-06-22 13:36
Same with 1.1.1 macOS Mojave 10.14.5 VirtualBox:Version 6.0.8 r130520 (Qt5.6.3)

kubectl delete
kubectl start 
solve the problem while keeping my VPN off.

**Comment by arashout** [comment] 2019-10-09 21:59
> I also faced the same problem and it caused after using/connecting Cisco AnyConnect VPN. Similar networking issue I have seen earlier as well with Virtualbox VM networks.
> 
> So basically when we disconnect the VPN it removes the existing routing for VirtualBox networks. So the solution is ifconfig down & ifconfig for all Virtualbox nets.
> 
> I use below function in .bashrc file and run it whenever I face this issue. It works for me on Mac.
> 
> ```shell
> function vb()
> {
>         setopt shwordsplit
>         ifs=`VBoxManage list hostonlyifs| grep -w 'Name:'| awk '{print $2}'`
>                 for i in $ifs
>                         do
>                                 sudo ifconfig $i down && sudo ifconfig $i up
>                                 echo "Done for $i"
>                         done
> }
> ```
> 
> ```shell
> # source ~/.bashrc 
> # vb 
> ```

bash: setopt: command not found

When I try to run it

**Comment by gkbijarniya** [comment] 2019-10-10 03:18
> > I also faced the same problem and it caused after using/connecting Cisco AnyConnect VPN. Similar networking issue I have seen earlier as well with Virtualbox VM networks.
> > So basically when we disconnect the VPN it removes the existing routing for VirtualBox networks. So the solution is ifconfig down & ifconfig for all Virtualbox nets.
> > I use below function in .bashrc file and run it whenever I face this issue. It works for me on Mac.
> > ```shell
> > function vb()
> > {
> >         setopt shwordsplit
> >         ifs=`VBoxManage list hostonlyifs| grep -w 'Name:'| awk '{print $2}'`
> >                 for i in $ifs
> >                         do
> >                                 sudo ifconfig $i down && sudo ifconfig $i up
> >                                 echo "Done for $i"
> >                         done
> > }
> > ```
> > 
> > 
> > ```shell
> > # source ~/.bashrc 
> > # vb 
> > ```
> 
> bash: setopt: command not found
> 
> When I try to run it

Is it on Mac OSX?
It should work on Mac OSX with Bash & Zsh shells.
