### ISSUE TITLE
minikube start

### ISSUE THREAD

**Issue by alejomantilladasm** [kubernetes/minikube#4147] opened 2019-04-24 19:12 UTC
[root@localhost ~]# minikube start
😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

💣  Unable to start VM: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The vboxdrv kernel module is not loaded. Either there is no module\n         available for the current kernel (5.0.9-1.el7.elrepo.x86_64) or it failed to\n         load. Please recompile the kernel module and install it by\n\n           sudo /sbin/vboxconfig\n\n         You will not be able to start VMs until this problem is fixed.\n6.0.6r130049". Please upgrade at https://www.virtualbox.org

**Comment by tstromberg** [comment] 2019-04-25 18:27
Dupe of #4043

**Closed by tstromberg** 2019-04-25 18:27 UTC
