### ISSUE TITLE
error provisioning host: Hyper-V PowerShell Module is not available

### ISSUE THREAD

**Issue by rajurh** [kubernetes/minikube#9010] opened 2020-08-17 06:33 UTC
I have been using Minikube from a long time but recently I had enabled wsl2 as well. All looks good.

I am trying to start minikube by deleting all -` minikube delete --all --purge`

![image](https://user-images.githubusercontent.com/15551296/90364014-c65f6900-e0b7-11ea-98a1-3749a726fb34.png)

I have been consistently getting above error, I am not able to understand what's wrong when it was working till date.  I tried in powershell with following command no luck  `@(Get-Module -ListAvailable hyper-v).Name | Get-Unique`

But I can see Hyper-v enabled and can see by navigating Hyper-v manager window.

Any help will be much appreciated. I even tried downgrade to lower-end version of minikube no luck. 

System: Windows 10 with WSL2 enabled

**Comment by tstromberg** [comment] 2020-08-20 21:56
This issue appears to be a duplicate of #9040, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-08-20 21:56 UTC
