### ISSUE TITLE
Seccomp profile does not work in minikube

### ISSUE THREAD

**Issue by LordNoteworthy** [kubernetes/minikube#5573] opened 2019-10-08 22:44 UTC
Using last version of minikube v1.4.0.

**The exact command to reproduce the issue**:
kubectl apply -f my-pod.yaml

```
apiVersion: v1
kind: Pod
metadata:
  name: seccomp-app
  namespace: default
  annotations:
    seccomp.security.alpha.kubernetes.io/pod: "localhost/my-profile.json"
    # you can specify seccomp profile per container. If you add another profile you can configure
    # it for a specific container - 'pause' in this case.
    # container.seccomp.security.alpha.kubernetes.io/pause: "localhost/some-other-profile.json"
spec:
  containers:
  - name: pause
    image: k8s.gcr.io/pause:3.1
```

**The full output of the command that failed**:

This manifest installs the seccomp profile. It’s going to copy the policy from the configmap in /var/lib/kubelet/seccomp/my-profile.json.

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: seccomp
  namespace: kube-system
  labels:
    security: seccomp
spec:
  selector:
    matchLabels:
      security: seccomp
  template:
    metadata:
      labels:
        security: seccomp
    spec:
      initContainers:
      - name: installer
        image: alpine:3.10.0
        command: ["/bin/sh", "-c", "cp -r -L /seccomp/*.json /host/seccomp/"]
        volumeMounts:
        - name: profiles
          mountPath: /seccomp
        - name: hostseccomp
          mountPath: /host/seccomp
          readOnly: false
      containers:
      - name: pause
        image: k8s.gcr.io/pause:3.1
      terminationGracePeriodSeconds: 5
      volumes:
      - name: hostseccomp
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: profiles
        configMap:
          name: seccomp-profile
```

The config map contains the json of the seccomp profile:

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: seccomp-profile
  namespace: kube-system
data:
  my-profile.json: |
    {
      "defaultAction": "SCMP_ACT_ALLOW",
      "syscalls": [
        {
          "name": "chmod",
          "action": "SCMP_ACT_ERRNO"
        }
      ]
    }
```

**The operating system version**:
```
Linux ubuntu 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

The pods starts fine, but I can't see in the events when describing the pod that my seccomp custom config has been applied, when I deployed it outside minikube (kops in aws, it just works).

**Comment by medyagh** [comment] 2019-10-09 00:16
thank you for taking the time to create this issue, 
could you share what you expect to see for example that you can not see.

and do you see any relevant errors either in the outputs or `minikbube logs` ?

**Comment by LordNoteworthy** [comment] 2019-12-24 08:16
Nothing really much, the only way I was able to verify that there is something wrong is to check that the process inside the container has NOT been granted the given privileges.

**Comment by tstromberg** [comment] 2020-03-19 18:39
I still don't have a clear sense on how to reproduce this. 

My gut instinct says this may be due to the kernel not applying seccomp. Do you mind testing if minikube v1.9.0-beta.1 is affected, and if so, share the output of `minikube start`?

**Comment by tstromberg** [comment] 2020-04-15 23:52
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Closed by tstromberg** 2020-04-15 23:52 UTC
Labels: area/guest-vm, help wanted, kind/bug, priority/backlog, triage/needs-information

**Comment by nitinmundhara** [comment] 2023-12-11 06:53
I'm facing the same issue as above. 
Any ideas on how to solve this?
