### ISSUE TITLE
Minikube failing to find ISO on Windows 10 Pro machine using MINIKUBE_HOME

### ISSUE THREAD

**Issue by gsoper78** [kubernetes/minikube#2564] opened 2018-02-22 10:41 UTC
Bug report

**Environment**: Windows 10 Pro

**Minikube version**: v1.6.0
- **OS**: 
- **VM Driver**: HyperV
- **ISO version**: minikube-v0.25.1.iso
- **Install tools**:
- **Others**:

**What happened**: 
Tried to start Minikube for the first time. I have a small %HOMEDRIVE% (Corporate network reasons) so used "MINIKUBE_HOME=C:\Minikube" in my user variables to use somewhere without space constraints. Following error is the result:
```
Starting local Kubernetes v1.6.0 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
E0221 17:04:57.911705    8116 start.go:159] Error starting host: Error creating host: Error executing step: Creating VM.
: open /Minikube/.minikube/cache/iso/minikube-v0.25.1.iso: The system cannot find the file specified..

 Retrying.
E0221 17:04:57.925698    8116 start.go:165] Error starting host:  Error creating host: Error executing step: Creating VM.
: open /Minikube/.minikube/cache/iso/minikube-v0.25.1.iso: The system cannot find the file specified.
```
"C:\Minikube\.minikube\cache\iso\minikube-v0.25.1.iso" is present and opens in Window as if it were a CD so I assume it's in a good state. Lack of "C:" in path in error raises suspicion but may be a red herring.

**What you expected to happen**:
Minikube to start

**How to reproduce it** (as minimally and precisely as possible):
Set "MINIKUBE_HOME=C:\Minikube" in the user variables of a Windows 10 Pro machine.

**Output of `minikube logs` (if applicable)**:
Log folder empty

**Anything else do we need to know**:

**Comment by rprouse** [comment] 2018-02-22 20:06
Duplicate of #1574? Where is minikube installed? I got the same when running from my D drive, switching to my C drive helped.

**Comment by DanielRamosAcosta** [comment] 2018-03-01 23:28
As @rprouse says, I was launching "minikube start" from my D drive, but when launching it from C it works... 😕

**Comment by aaron-prindle** [comment] 2018-03-01 23:31
You can run Minikube from the D: drive by setting you minikube config
directory to be on the D: drive using the
MINIKUBE_HOME env var:
https://github.com/kubernetes/minikube/blob/87f48f1731db224b9f52f4722aeb91ab6ec90993/docs/env_vars.md

This issue is because the config dir is automatically set to be on the C:
from the workspace detection lib we use

**Comment by davidovich** [comment] 2018-03-30 17:51
> Lack of "C:" in path in error raises suspicion but may be a red herring.

I think prepending the drive letter would fix this, and "launch minikube from the drive where it is installed" issues that people are having.  But preliminary research into the code (in docker/machine/drivers) does not point to anywhere where the drive is dropped. 

minikube depends on [client-go](https://github.com/kubernetes/minikube/blob/master/vendor/k8s.io/client-go/util/homedir/homedir.go) from kubernetes and this resolves the default minikube path in this order:

1. HOME
2. concatenation of HOMEDRIVE and HOMEPATH
3. USERPROFILE

This would account for different behaviors reported (if you are not using MINIKUBE_HOME, and you have a HOMEDRIVE and combinations etc.)

But this is only at the minikube level. Drivers make their own asumptions on the HOME drive.

**Closed** 2018-08-27 19:55 UTC
Labels: lifecycle/rotten, platform/windows

**Comment by marcelser** [comment] 2019-07-26 12:50
/reopen

Why was this beeing closed at all. It's still valid and not solved
