### ISSUE TITLE
host.minikube.internal resolves inside the VM but not inside of containers.

### ISSUE THREAD

**Issue by JParkinson1991** [kubernetes/minikube#8873] opened 2020-07-29 07:57 UTC
## Setup
- Minikube Version: v1.12.1 Hyperkit Driver
- Docker for Mac Docker Engine: 19.03.12
- Kubernetes local: v1.18.6 (not bundled with docker for mac, installed via homebrew)
- Kubernetes server: v1.18.3

## Issue

I have been following this tutorial here: https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/

I adapated [filebeat configuration](https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/#create-a-kubernetes-secret) to use the new hostname `host.minikube.internal` when trying [deploy filebeat](https://kubernetes.io/docs/tutorials/stateless-application/guestbook-logs-metrics-with-elk/#deploy-filebeat) which attempts the connection to kibana i receive the following host not found error.

```
2020-07-28T14:11:40.056Z        ERROR   instance/beat.go:933    Exiting: error connecting to Kibana: fail to get the Kibana version: HTTP GET request to http://host.minikube.internal:5601/api/status fails: fail to execute the HTTP GET request: Get http://host.minikube.internal:5601/api/status: lookup host.minikube.internal on 10.96.0.10:53: no such host. Response: .
Exiting: error connecting to Kibana: fail to get the Kibana version: HTTP GET request to http://host.minikube.internal:5601/api/status fails: fail to execute the HTTP GET request: Get http://host.minikube.internal:5601/api/status: lookup host.minikube.internal on 10.96.0.10:53: no such host. Response: .
```

Kibana has been configured to bind to address: 0.0.0.0 so this is not an issue with remote connections as shown below.

When using `minikube ssh` i am able to curl the above problematic URL as expected.

```
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ curl http://host.minikube.internal:5601/api/status
{ .. some valid response object here }
```

Does the hostname `host.minikube.internal` not propagate to containers running inside of a minikube cluster? I assumed it would?

The only way i was able to get the above error resolved was to add a `hostAlias` to filebeat DaemonSet like so 

```
hostAliases:
  - ip: "192.168.64.1"
    hostnames:
      - "host.minikube.internal"
```

I guess to summarise, why can the minikube VM access `host.minikube.internal` but containers created within not?

Are there any recommended steps to get around this? It is not ideal having to place the IP address into manifest .yaml  files via hostAliases.

**Comment by JParkinson1991** [comment] 2020-07-29 08:00
Adapated problematic manifest file from tutorial

```
# NOTE: Update api version
# apiVersion: extensions/v1beta1
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat-dynamic
  namespace: kube-system
  labels:
    k8s-app: filebeat-dynamic
    kubernetes.io/cluster-service: "true"
spec:
  # NOTE: Add in selector following api version update
  selector:
    matchLabels:
      k8s-app: filebeat-dynamic
  template:
    metadata:
      labels:
        k8s-app: filebeat-dynamic
        kubernetes.io/cluster-service: "true"
    spec:
      hostAliases:
        - ip: "192.168.64.1"
          hostnames:
            - "host.minikube.internal"
      serviceAccountName: filebeat-dynamic
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat-dynamic
        image: docker.elastic.co/beats/filebeat:7.6.2
        imagePullPolicy: Always
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTIC_CLOUD_ID
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: ELASTIC_CLOUD_ID
              optional: true
        - name: ELASTIC_CLOUD_AUTH
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: ELASTIC_CLOUD_AUTH
              optional: true
        - name: ELASTICSEARCH_HOSTS
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: ELASTICSEARCH_HOSTS
              optional: true
        - name: KIBANA_HOST
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: KIBANA_HOST
              optional: true
        - name: ELASTICSEARCH_USERNAME
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: ELASTICSEARCH_USERNAME
              optional: true
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dynamic-logging
              key: ELASTICSEARCH_PASSWORD
              optional: true
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: dockersock
          mountPath: /var/run/docker.sock
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-dynamic-config
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: data
        emptyDir: {}
```

**Comment by bendavis78** [comment] 2020-07-30 17:28
I'm seeing the same issue. When i try to ping the host from inside a pod, it does not resolve.

    $ kubectl exec -it -n ingress-nginx ingress-nginx-controller-c96557986-r4qvp -- bash
    bash-5.0$ ping host.minikube.internal
    ping: bad address 'host.minikube.internal

**Comment by medyagh** [comment] 2020-08-12 18:25
@JParkinson1991 @bendavis78 

thats a good catch ! I gotta be honest I am surprised that this undocumentted internal feature of minikube was used by tutorials and user's apps !

**Comment by tstromberg** [comment] 2020-08-12 18:57
@medyagh - it's not so undocumented any more! https://minikube.sigs.k8s.io/docs/handbook/host-access/

@priyawadhwa has more context - but my understanding was that kubelet populates the host /etc/hosts into each pod at creation time. I can confirm that this does not appear to be happening, however:

```
minikube start --driver=hyperkit
kubectl apply -f ./test/integration/testdata/netcat-deployment.yaml
kubectl exec -i -t deployment/netcat -- cat /etc/hosts
```

Here is the output:

```
# Kubernetes-managed hosts file.
127.0.0.1	localhost
::1	localhost ip6-localhost ip6-loopback
fe00::0	ip6-localnet
fe00::0	ip6-mcastprefix
fe00::1	ip6-allnodes
fe00::2	ip6-allrouters
172.17.0.3	netcat-7987c4c66b-8bf7m
```

I expected to see `host.minikube.internal` listed, but it is not. It is also not resolvable in DNS (CoreDNS returns `NXDOMAIN`, just as it did in your example, @medyagh).

**Comment by priyawadhwa** [comment] 2020-08-12 21:15
@tstromberg so it does seem like the kubelet should be injecting /etc/hosts based on documentation [here](https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/) 


But from this PR it seems like there are cases when that doens't happen [here](https://github.com/kubernetes/kubernetes/pull/16052/files#diff-bf28da68f62a8df6e99e447c4351122dR962-R965)

```
	// Kubernetes only mounts on /etc/hosts if :
	// - container does not use hostNetwork and
	// - container is not a infrastructure(pause) container
	// - container is not already mounting on /etc/hosts
```

**Comment by roock** [comment] 2020-10-21 05:51
This looks like it is related to #8439?

**Comment by sharifelgamal** [comment] 2020-12-16 19:42
This does appear to be a dupe of #8439, so I'll go ahead and close this issue and we can redirect all conversation over there.

**Closed by sharifelgamal** 2020-12-16 19:42 UTC
Labels: kind/bug, priority/backlog
