### ISSUE TITLE
error provisioning host: Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1

### ISSUE THREAD

**Issue by NandiniJB** [kubernetes/minikube#8256] opened 2020-05-23 07:12 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment] 2020-05-26 17:10
Dupe of #8255

**Closed by tstromberg** 2020-05-26 17:10 UTC
