### ISSUE TITLE
Can't initialize ip6tables table?

### ISSUE THREAD

**Issue by Philomelius** [kubernetes/minikube#18813] opened 2024-05-06 14:16 UTC
### What Happened?

Installed Docker, Minikube, Kemu. Ran `minikube start --driver qemu --network socket_vmnet``

Output:

😄  minikube v1.33.0 sur Darwin 14.4.1 (arm64)
✨  Utilisation du pilote qemu2 basé sur le profil existant
👍  Démarrage du nœud "minikube" primary control-plane dans le cluster "minikube"
🏃  Mise à jour du VM qemu2 en marche "minikube" ...
🐳  Préparation de Kubernetes v1.30.0 sur Docker 26.0.1...
🤦  Impossible de redémarrer le(s) nœud(s) du plan de contrôle, le cluster sera réinitialisé : <no value>
    ▪ Génération des certificats et des clés
    ▪ Démarrage du plan de contrôle ...
    ▪ Configuration des règles RBAC ...
🔗  Configuration de bridge CNI (Container Networking Interface)...
🔎  Vérification des composants Kubernetes...
    ▪ Utilisation de l'image gcr.io/k8s-minikube/storage-provisioner:v5
❗  L'activation de 'default-storageclass' a renvoyé une erreur : running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://10.0.2.15:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 10.0.2.15:8443: i/o timeout]
🌟  Modules activés: storage-provisioner

❌  Fermeture en raison de GUEST_START : failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15221744/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by Philomelius** [comment] 2024-05-06 14:19
➜  ~ git:(master) ✗ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Stopped
kubeconfig: Configured

**Comment by okgolove** [comment] 2024-05-21 13:17
Hi! I have the same on macOS 14.4.1 and minikube version 1.33.1
Version v1.29.0 works for me though.

**Comment by spowelljr** [comment] 2024-07-03 19:21
We have a fix for this, going to close this as a duplicate of https://github.com/kubernetes/minikube/issues/19173 to centralize discussion, please follow there for updates, thank you!

**Closed by spowelljr** 2024-07-03 19:21 UTC
