### ISSUE TITLE
minikube crashed

### ISSUE THREAD

**Issue by surajitc** [kubernetes/minikube#5041] opened 2019-08-11 01:22 UTC
Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
stdout:
stderr: cannot use "fe80::215:5dff:fe41:ee08" as the bind address for the API Server
: Process exited with status 1
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose
PS C:\WINDOWS\system32> minikube ssh "sudo poweroff"
ssh: wait: remote command exited without exit status or exit signal
PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Default Switch"
* minikube v1.3.0 on Microsoft Windows 10 Enterprise 10.0.18362 Build 18362
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
stdout:
stderr: cannot use "fe80::215:5dff:fe41:ee08" as the bind address for the API Server
: Process exited with status 1

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment] 2019-08-13 17:04
This issue appears to be a duplicate of #3963, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-08-13 17:04 UTC
