### ISSUE TITLE
Error downloading checksum file: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by billlih** [kubernetes/minikube#5182] opened 2019-08-23 03:40 UTC
**重现问题所需的命令**：minikube start

**失败的命令的完整输出**：<details>

</details>

**`minikube logs`命令的输出**： <details>

minikube start
* minikube v1.3.1 on Ubuntu 14.04
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
* Downloading VM boot image ...
* 
X Failed to cache ISO
* Error: [DOWNLOAD_IO_TIMEOUT] https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: net/http: TLS handshake timeout
* Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
* Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3846

</details>

**使用的操作系统版本**：VMware® Workstation 12 Pro - ubuntu14.04

**Comment by billlih** [comment] 2019-08-23 03:43
minikube start
* minikube v1.3.1 on Ubuntu 14.04
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
* Downloading VM boot image ...
* 
X Failed to cache ISO
* Error: [DOWNLOAD_IO_TIMEOUT] https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: net/http: TLS handshake timeout
* Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
* Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3846

**Comment by henryguyu** [comment] 2019-08-23 04:02
same issue here, can anyone solve it? or give a solution?

**Comment by tstromberg** [comment] 2019-08-24 17:38
It appears that your Ubuntu machine does not have full access to the internet. Are you running minikube from China by any chance?

You can check by using curl to dowload the ISO: `curl -LO https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso`

If you aren't able to use the internet, you can download the ISO file to `~/.minikube/cache/iso`. You'll also need the appropriate docker images though, so I suggest running `minikube start --download-only` once from a machine with access to the internet, and copying `~/.minikube/cache` over from there.

https://minikube.sigs.k8s.io/docs/reference/disk_cache/

Related: #4774

**Comment by henryguyu** [comment] 2019-08-26 02:00
D:\Tools>curl -LO https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:22 --:--:--     0
curl: (35) schannel: failed to receive handshake, SSL/TLS connection failed

**Comment by henryguyu** [comment] 2019-08-26 02:07
@tstromberg I tried curl from my win10, I mean not from VM. I got "failed to receive handshake".

**Comment by tstromberg** [comment] 2019-09-20 21:08
This issue appears to be a duplicate of #4774, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-09-20 21:08 UTC
Labels: l/zh-CN, triage/needs-information, triage/support
