### ISSUE TITLE
Failed to setup kubeconfig: yaml: control characters are not allowed

### ISSUE THREAD

**Issue by ramesh-anbuthambi** [kubernetes/minikube#5907] opened 2019-11-14 04:42 UTC
In Windows 10 Enterprise edition with Hyper V enabled, I tried to start minikube start and it is failing with following error message

Error Message: X Failed to setup kubeconfig: could not read config: Error decoding config from data:                                   : yaml: control characters are not allowed

I issued following command opening powershell in Administrator mode
 minikube start --vm-driver=hyperv

minikube logs output are given below
PS C:\WINDOWS\system32> minikube logs
* ==> Docker <==
* -- Logs begin at Thu 2019-11-14 04:23:38 UTC, end at Thu 2019-11-14 09:53:37 UTC. --
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.413922199Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.413949599Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.413991599Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414002499Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414010099Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414019299Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414027099Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414034399Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414041399Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414048799Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414156999Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414214299Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414485599Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414503699Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414524599Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414532599Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414539699Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414546099Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414552799Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414561999Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414568699Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414575199Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414581899Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414613399Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414621999Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414629199Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414639599Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414723099Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414784099Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.414790999Z" level=info msg="containerd successfully booted in 0.016475s"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.424126799Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005fe6e0, READY" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.425977199Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426535999Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426591799Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426691799Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426709399Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426733799Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005fea30, CONNECTING" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426834199Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426868299Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005fea30, READY" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426879099Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.426961399Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.427003299Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.427079299Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00071ecc0, CONNECTING" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.427198699Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00071ecc0, READY" module=grpc
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456318099Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456497999Z" level=warning msg="Your kernel does not support cgroup blkio weight"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456510199Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456517199Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456523599Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456529899Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456536799Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.456762399Z" level=info msg="Loading containers: start."
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.530978899Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.581790099Z" level=info msg="Loading containers: done."
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.585926199Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.601862599Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.601966399Z" level=info msg="Daemon has completed initialization"
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.651749199Z" level=info msg="API listen on /var/run/docker.sock"
* Nov 14 04:24:45 minikube systemd[1]: Started Docker Application Container Engine.
* Nov 14 04:24:45 minikube dockerd[2822]: time="2019-11-14T04:24:45.651834599Z" level=info msg="API listen on [::]:2376"*
* ==> container status <==
* time="2019-11-14T04:34:22Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> dmesg <==
* [Nov14 04:23] smpboot: 128 Processors exceeds NR_CPUS limit of 64
* [  +0.113795] You have booted with nomodeset. This means your GPU drivers are DISABLED
* [  +0.000000] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
* [  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
* [  +0.102656] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [  +0.013429] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
*               * this clock source is slow. Consider trying other clock sources
* [ +18.116274] Unstable clock detected, switching default tracing clock to "global"
*               If you want to keep using the local clock, then add:
*                 "trace_clock=local"
*               on the kernel command line
* [  +0.000030] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
* [  +0.804656] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
* [  +0.673247] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
* [  +0.007192] systemd-fstab-generator[1270]: Ignoring "noauto" for root device
* [  +0.003234] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
* [  +0.000001] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
* [  +4.061135] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
* [  +0.446695] vboxguest: loading out-of-tree module taints kernel.
* [  +0.003426] vboxguest: PCI device not found, probably running on physical hardware.
* [Nov14 04:24] systemd-fstab-generator[2563]: Ignoring "noauto" for root device
* [Nov14 04:25] NFSD: Unable to end grace period: -110
*
* ==> kernel <==
*  04:34:22 up 11 min,  0 users,  load average: 0.00, 0.03, 0.03
* Linux minikube 4.19.76 #1 SMP Tue Oct 29 14:56:42 PDT 2019 x86_64 GNU/Linux
* PRETTY_NAME="Buildroot 2019.02.6"
*
* ==> kubelet <==
* -- Logs begin at Thu 2019-11-14 04:23:38 UTC, end at Thu 2019-11-14 09:53:37 UTC. --
* -- No entries --
PS C:\WINDOWS\system32>
</details>

Windows Version:  Windows 10 Enterprise Version 1709 (OS Build 16299.1331)
![Minikube Start Error](https://user-images.githubusercontent.com/42968181/68827249-48ed6f00-06c7-11ea-9d32-eefa715dc493.JPG)

**Comment by tstromberg** [comment] 2019-11-15 02:37
You can get more output using `minikube start --alsologtostderr -v=1`. My guess is that your $KUBECONFIG has an invalid character in it. You might be able to get more diagnostics by running:

`kubectl config get-clusters`
`kubectl config view`

**Comment by ramesh-anbuthambi** [comment] 2019-11-15 09:09
After trying different steps, I have installed Docker Desktop in my machine and started Kubernetes in it and it worked as expected.

Thank You Thomas for helping me out. I will make note of these commands.

Will Minkube and Docker for Desktop works parallel in the same machine?

With Regards,
Ramesh Anbuthambi

**Comment by tstromberg** [comment] 2019-11-15 22:15
Yes, they are designed to coexist peacefully. Let me know if you run into anything else.

I wonder if there is the possibility of a Windows only bug. If you ever get the time, please add the output of `minikube start --alsologtostderr -v=1`, as well as attaching your `.kube/config` file (found under your user directory?) so that we may replicate and root cause the issue.

Thanks!

**Comment by vostruk** [comment] 2019-12-10 08:32
In my case I was getting 
error: Error loading config file "C:\Users\vostruk/.kube/config": yaml: control characters are not allowed
on every kubectl command.

The solution was to delete the config file under "C:\Users\vostruk/.kube/config" (it is being recreated by kubernetes later on without errors)

**Comment by sharifelgamal** [comment] 2019-12-16 23:30
I'll go ahead and close this issue, recreating a kubeconfig if your current config is corrupt in some way is usually the way to go. Feel free reopen if necessary.

**Closed by sharifelgamal** 2019-12-16 23:30 UTC
Labels: triage/needs-information, triage/support
