### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by rajask132** [kubernetes/minikube#6353] opened 2020-01-20 12:14 UTC
panic: runtime error: invalid memory address or nil pointer dereference

log on command prompt

C:\Windows\system32>minikube start
! minikube v1.6.2 on Microsoft Windows 10 Pro 10.0.17763 Build 17763
* Selecting 'hyperv' driver from user configuration (alternates: [virtualbox])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x12ee976]

goroutine 49 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc00055c5d0, 0xa, 0xc00055c5db, 0xe, 0xc00055c5ea, 0x7, 0x0, 0x0, 0xc00046bc58, ...)
        /go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x136
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc00055c5d0, 0x21, 0xc0003f41e0, 0x4b, 0x0, 0x0)
        /app/pkg/minikube/machine/cache_images.go:395 +0x615
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0003ebf68, 0x0)
        /app/pkg/minikube/machine/cache_images.go:85 +0xed
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002c3da0, 0xc0002c3e00)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x6b
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x6d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x12ee976]

goroutine 106 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0x0, 0x0, 0xc00055c7b0, 0x1c, 0xc00055c7cd, 0x6, 0x0, 0x0, 0xc00061fc58, ...)
        /go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x136
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc00055c7b0, 0x23, 0xc000562230, 0x4d, 0x0, 0x0)
        /app/pkg/minikube/machine/cache_images.go:395 +0x615
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0002d5f68, 0x0)
        /app/pkg/minikube/machine/cache_images.go:85 +0xed
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0002c3da0, 0xc0002c3fb0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x6b
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x6d

**Comment by rajask132** [comment] 2020-01-20 12:14
can someone help me in solving those issue

**Comment by medyagh** [comment] 2020-01-22 02:24
@blueelvis  any idea?

**Comment by tstromberg** [comment] 2020-01-22 19:48
This issue appears to be a duplicate of #6147, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-01-22 19:48 UTC
Labels: co/hyperv
