### ISSUE TITLE
waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by phani27** [kubernetes/minikube#3889] opened 2019-03-17 14:59 UTC
😄  minikube v0.35.0 on darwin (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s

📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubelet v1.13.4
💾  Downloading kubeadm v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver

💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by davidthewatson** [comment] 2019-03-18 21:28
I've got what looks like the same problem:

```
uname -a
Linux 4.19.28-1-MANJARO #1 SMP PREEMPT Sun Mar 10 08:32:42 UTC 2019 x86_64 GNU/Linux
minikube start --vm-driver kvm2 --docker-env HTTP_PROXY=http://proxy.dog.com:80 --docker-env HTTPS_PROXY=http://proxy.dog.com:80
😄  minikube v0.35.0 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.39.203
🌐  Found network options:
    ▪ HTTP_PROXY=http://proxy.dog.com:80/
    ▪ HTTPS_PROXY=http://proxy.dog.com:80/
    ▪ NO_PROXY=localhost:127.0.0.1
🐳  Configuring Docker as the container runtime ...
    ▪ env HTTP_PROXY=http://proxy.dog.com:80
    ▪ env HTTPS_PROXY=http://proxy.dog.com:80
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

```
I suspect it may be related to the proxy as I had no such problem running on my home network without the proxy.

**Comment by phani27** [comment] 2019-03-18 21:30
Any Solution with proxy?

**Comment by davidthewatson** [comment] 2019-03-18 22:54
I tried what's suggested here WRT no_proxy. 

https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md

Deleted minikube VM instance and started a new one. 

Crashes identically to the aforementioned log. YMMV. 

Fortunately, I can unplug this Dell XPS 13 and take it home now where none of this will be a problem. 

I still think the NO_PROXY could be a problem, but I'm not convinced that the readme is right since minikube is coming up on a 192.168.39.* address.

**Comment by davidthewatson** [comment] 2019-03-19 13:02
Indeed, as I stated last night, minikube runs fine with no change save for deleting the proxy settings from /etc/environment, restarting and running on my home network with no proxy:

'''
 minikube start --vm-driver kvm2
😄  minikube v0.35.0 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.39.194
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
'''

**Comment by davidthewatson** [comment] 2019-03-21 16:12
I resolved this with the following:

Note that the `no_proxy` includes `192.168.39.1/24`

I'm running minikube on manjaro (arch):

```
yaourt minikube
1 aur/docker-machine-driver-kvm2 0.34.1-1 [installed] (15) (2.82)
    Minikube-maintained KVM driver for docker-machine
2 aur/minikube 0.35.0-1 (10) (1.93)
    Minikube is a tool that makes it easy to run Kubernetes locally
3 aur/minikube-bin 0.35.0-1 [installed] (60) (4.23)
    A tool that makes it easy to run Kubernetes locally
4 aur/minikube-git 0.28.2.r55.gbed9aabaf-1 (0) (0.00)
```

I believe that the doc here: https://github.com/kubernetes/minikube/blob/master/docs/http_proxy.md
is not complete since it mentions the same exclusion for `192.168.99.1/24`. I'm not sure why my minikube uses a different subnet but it does.
```

minikube start --vm-driver kvm2 --docker-env http_proxy=http://proxy.dog.com:80 --docker-env https_proxy=http://proxy.dog.com:80 --docker-env no_proxy="localhost,127.0.0.1,192.168.39.1/24,10.96.0.0/12"
o   minikube v0.35.0 on linux (amd64)
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
-   "minikube" IP address is 192.168.39.199
o   Found network options:
    - HTTP_PROXY=http://proxy.dog.com:80
    - HTTPS_PROXY=http://proxy.dog.com:80
    - NO_PROXY=localhost:127.0.0.1,192.168.39.0/24
-   Configuring Docker as the container runtime ...
    - env http_proxy=http://proxy.dog.com:80
    - env https_proxy=http://proxy.dog.com:80
    - env no_proxy=localhost,127.0.0.1,192.168.39.1/24,10.96.0.0/12
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.13.4 ...
-   Launching Kubernetes v1.13.4 using kubeadm ... 
:   Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
-   Configuring cluster permissions ...
-   Verifying component health .....
+   kubectl is now configured to use "minikube"
=   Done! Thank you for using minikube!
`
```

The results are as you'd expect:
```

 kubectl get all --all-namespaces
NAMESPACE     NAME                                       READY   STATUS    RESTARTS   AGE
kube-system   pod/coredns-86c58d9df4-4rd8w               1/1     Running   0          96s
kube-system   pod/coredns-86c58d9df4-j4t9d               1/1     Running   0          96s
kube-system   pod/etcd-minikube                          1/1     Running   0          53s
kube-system   pod/kube-addon-manager-minikube            1/1     Running   0          104s
kube-system   pod/kube-apiserver-minikube                1/1     Running   0          57s
kube-system   pod/kube-controller-manager-minikube       1/1     Running   0          49s
kube-system   pod/kube-proxy-rx59r                       1/1     Running   0          96s
kube-system   pod/kube-scheduler-minikube                1/1     Running   0          40s
kube-system   pod/kubernetes-dashboard-ccc79bfc9-xnb9w   1/1     Running   2          95s
kube-system   pod/storage-provisioner                    1/1     Running   0          95s

NAMESPACE     NAME                           TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)         AGE
default       service/kubernetes             ClusterIP   10.96.0.1      <none>        443/TCP         107s
kube-system   service/kube-dns               ClusterIP   10.96.0.10     <none>        53/UDP,53/TCP   103s
kube-system   service/kubernetes-dashboard   ClusterIP   10.96.146.97   <none>        80/TCP          95s

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/kube-proxy   1         1         1       1            1           <none>          103s

NAMESPACE     NAME                                   READY   UP-TO-DATE   AVAILABLE   AGE
kube-system   deployment.apps/coredns                2/2     2            2           103s
kube-system   deployment.apps/kubernetes-dashboard   1/1     1            1           95s

NAMESPACE     NAME                                             DESIRED   CURRENT   READY   AGE
kube-system   replicaset.apps/coredns-86c58d9df4               2         2         2       96s
kube-system   replicaset.apps/kubernetes-dashboard-ccc79bfc9   1         1         1       95s

```

**Comment by jurossiar** [comment] 2019-03-27 13:35
I have the same issue but was not able to solve it with the description in previous comment.
I'm using MAC and Virtual Box. Any other solution? thanks!

**Comment by jvdgeest** [comment] 2019-03-28 10:03
Same problem here on macOS and virtual box. Using version 1.0 of minikube.

💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no obWRN: == Error getting default service account, retry in 0.5 second jects passed to apply
    error: no objeWRN: == Error getcts passed to apply
    error: no objects passed to apply

**Comment by zjg95** [comment] 2019-03-28 21:10
Same problem on macOS High Sierra 10.13.6

```
$ minikube version
minikube version: v1.0.0
$ uname -a
Darwin 17.7.0 Darwin Kernel Version 17.7.0: Fri Nov  2 20:43:16 PDT 2018; root:xnu-4570.71.17~1/RELEASE_X86_64 x86_64
$ minikube start
😄  minikube v1.0.0 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 7.95 MB / 142.88 MB [==>------------------------------------------]   5.57% 23s

 142.88 MB / 142.88 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver


💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: n o Erroor bgetting defjault serviecec account, rettry in 0.5 ses pcond ==
    error: no objeWRN: cts== Error get passed to apply
```

**Comment by tstromberg** [comment] 2019-04-04 18:49
Closing as dupe of #3844

**Closed by tstromberg** 2019-04-04 18:49 UTC
