### ISSUE TITLE
[Minikube start] Unable to start minikube on Apple M2 - Unable to load cached images - etcd manifest is missing

### ISSUE THREAD

**Issue by Dmdv** [kubernetes/minikube#17696] opened 2023-11-30 08:40 UTC
### What Happened?

Unable to load cached images: loading cached images: stat /Users/user_name/.minikube/cache/images/arm64/registry.k8s.io/etcd_3.5.9-0

minikube start --driver=docker --force-systemd=true
😄  minikube v1.32.0 on Darwin 14.1.1 (arm64)
✨  Using the docker driver based on user configuration
💨  For improved Docker Desktop performance, Install the official release of Docker Desktop (Minimum recommended version is 20.10.0, minimum supported version is 18.09.0, current version is master)
❗  docker is currently using the stargz storage driver, setting preload=false
📌  Using Docker Desktop driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase...:  410.58 MiB / 410.58 MiB  100.00% 24.38 M
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...\ E1130 16:34:31.723170   37952 cache.go:203] Error caching images:  Caching images: caching images: caching image "/Users/dmitry_dyachkov/.minikube/cache/images/arm64/registry.k8s.io/etcd_3.5.9-0": write: unable to calculate manifest: Error response from daemon: none of the manifests is fully present in the content store

🐳  Preparing Kubernetes v1.28.3 on Docker 24.0.7 ...
❌  Unable to load cached images: loading cached images: stat /Users/dmitry_dyachkov/.minikube/cache/images/arm64/registry.k8s.io/etcd_3.5.9-0: no such file or directory
    > kubectl.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubeadm.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubelet.sha256:  64 B / 64 B [-------------------------] 100.00% ? p/s 0s
    > kubectl:  45.50 MiB / 45.50 MiB [-----------] 100.00% 77.39 MiB p/s 800ms
    > kubeadm:  44.75 MiB / 44.75 MiB [------------] 100.00% 20.86 MiB p/s 2.3s
    > kubelet:  100.31 MiB / 100.31 MiB [----------] 100.00% 21.97 MiB p/s 4.8s
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.28.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,NumCPU,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.28.3
[preflight] Running pre-flight checks

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/13510479/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

### Solution tried

It didn't work

```
minikube delete --all
minikube start --driver=docker --force-systemd=true
```

**Comment by Dmdv** [comment] 2023-11-30 08:50
```
kubectl version
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.2
```

**Comment by spowelljr** [comment] 2024-01-24 19:30
Duplicate of https://github.com/kubernetes/minikube/issues/16425, going to close this issue to centralize the discussion

**Closed by spowelljr** 2024-01-24 19:30 UTC
