### ISSUE TITLE
minikube logo proposals - please vote

### ISSUE THREAD

**Issue by martamarszal** [kubernetes/minikube#176] opened 2016-06-07 11:42 UTC
We played around with some designs for a minikube logo. I'm posting 4 proposals here. Would be great to get feedback from the contributors and community. 
![16 06 07_mini_kubernetes_logo_ideas-01](https://cloud.githubusercontent.com/assets/13485544/15861484/c76a8292-2ccc-11e6-805a-0a8610ffc265.png)

Vote by 👍 on one of the comments below. 
After 1 week we'll determine the winner and submit a pull request. 

We'll also do Twitter poll to get more votes.

**Comment by martamarszal** [comment] 2016-06-07 11:43
<img width="245" alt="screen shot 2016-06-07 at 13 42 38" src="https://cloud.githubusercontent.com/assets/13485544/15856453/c3d4a5de-2cb5-11e6-8674-f6c80934e484.png">

**Comment by martamarszal** [comment] 2016-06-07 11:43
<img width="232" alt="screen shot 2016-06-07 at 13 42 43" src="https://cloud.githubusercontent.com/assets/13485544/15856457/ca45e270-2cb5-11e6-9a2d-29947baa776e.png">

**Comment by martamarszal** [comment] 2016-06-07 11:43
<img width="226" alt="screen shot 2016-06-07 at 13 42 47" src="https://cloud.githubusercontent.com/assets/13485544/15856460/cf9d3e12-2cb5-11e6-8861-8e0803db58d0.png">

**Comment by martamarszal** [comment] 2016-06-07 11:43
<img width="232" alt="screen shot 2016-06-07 at 13 42 52" src="https://cloud.githubusercontent.com/assets/13485544/15856464/d75bfa8a-2cb5-11e6-96d6-979f826c2e91.png">

**Comment by mfburnett** [comment] 2016-06-07 14:29
From purely a practical design standpoint, A is complex enough that it could be hard to accurately reproduce/draw by anyone and looks messy at a distance, C's unenclosed white details at the bottom would make it tricky to do tshirts or stickers without making an arbitrary cutoff somewhere, and D is close enough to the Kubernetes logo to be confusing. 

So B looks like the most practical choice! Will add an emoji of support when I get to my computer.

**Comment by dlorenc** [comment] 2016-06-07 17:32
Wow, thanks! I agree with @mfburnett :)

**Comment by luxas** [comment] 2016-06-07 17:35
Thanks @martamarszal!

**Comment by aaron-prindle** [comment] 2016-06-07 17:40
These are great, thanks @martamarszal!

**Comment by nlamirault** [comment] 2016-06-08 09:36
+1 for D :)

**Comment by philips** [comment] 2016-06-14 05:36
Looks like B is the winner?

**Comment by martamarszal** [comment] 2016-06-14 09:24
We also did a Twitter campaign and there "D" was the absolute winner:
- A 12%
- B 15%
- C 18%
- D 55%
There were 60 votes. 
Our aim was to get input from the community. But since you guys are the creators of Minikube I'll leave the final decision between B and D to you.

**Comment by martamarszal** [comment] 2016-06-14 09:26
I can submit two PR and you decide what to merge.

**Comment by dlorenc** [comment] 2016-06-14 13:16
Thanks @martamarszal!

**Comment by shlomizadok** [comment] 2016-06-21 05:13
+1 for D

**Comment by keontang** [comment] 2016-06-21 06:41
+1 for D

**Comment by dlorenc** [comment] 2016-06-21 22:58
D appears to be there clear winner. @martamarszal, when you have a chance please send us a PR!

**Comment by vishh** [comment] 2016-07-02 15:26
Among the ones here, I like `D`. It is still subtle though.

**Comment by dlorenc** [comment] 2016-07-07 18:52
Hey @martamarszal, do you still want to send us a PR?

**Comment by dlorenc** [comment] 2016-07-14 16:11
I'm going to close this out. Please re-open if you want to send us a PR for these @martamarszal!

**Closed** 2016-08-11 21:27 UTC
