### ISSUE TITLE
none: Error restarting cluster: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by GrimaudNathan** [kubernetes/minikube#5635] opened 2019-10-16 09:22 UTC
**The command:**
minikube start

**The output of the command that failed:**
😄  minikube v1.4.0 sur Ubuntu 18.04
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running none "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Configuring environment for Kubernetes v1.16.0 on Docker 18.06.1-ce...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The operating system version:**
Ubuntu 18.04.3

**Comment by priyawadhwa** [comment] 2019-10-16 18:54
This issue appears to be a duplicate of #5451, do you mind if we move the conversation there?

This way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Comment by priyawadhwa** [comment] 2019-10-17 21:18
Hey @GrimaudNathan, could you please provide some more information so that we can assist in resolving this issue:

 * The full output of `minikube logs`

Thanks!

**Comment by gaoljhy** [comment] 2019-11-03 10:06
My Logs following this:

```
Nov 03 14:05:26 localhost kubelet[19965]: E1103 14:05:26.036199   19965 reflector.go:123] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:46: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: dial tcp [::1]:8443: connect: connection refused
```

**Comment by phirmware** [comment] 2019-11-09 10:19
I had the same issue 
`💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared`
When i ran _`minikube start`_

I solved this by running 
`minikube delete`
And running `minkube start `again . And it worked.

**Comment by claudioabudio** [comment] 2019-11-11 17:40
Thank you all !, I had the same issue on a Mac OS with VirtualBox and running "minikube delete" and after that , minikube start --vm-driver=virtualbox also fixed the issue as mentioned by phfirmware !

**Comment by medyagh** [comment] 2020-01-29 19:39
@claudioabudio glad to see the issue was resolved, I will close this issue, please feel free to reopen if still have isssues.

**Closed by medyagh** 2020-01-29 19:39 UTC
Labels: co/apiserver, co/none-driver, triage/support

**Comment by mirind4** [comment] 2020-02-27 17:05
@phirmware It indeed solves the issue, but it is so irritating that I have to do it frequently. Something is fishy...
