### ISSUE TITLE
CreateContainerError for kube-proxy when using runtime cri-o

### ISSUE THREAD

**Issue by joshiste** [kubernetes/minikube#16371] opened 2023-04-24 13:26 UTC
### What Happened?

When doing a `minikube start --container-runtime cri-o` the kube-proxy pod doesn't start.
Errors:
```
Name:                 kube-proxy-hpn6m
Namespace:            kube-system
Priority:             2000001000
Priority Class Name:  system-node-critical
Service Account:      kube-proxy
Node:                 crio/192.168.49.2
Start Time:           Mon, 24 Apr 2023 15:02:16 +0200
Labels:               controller-revision-hash=5cbfdcddd5
                      k8s-app=kube-proxy
                      pod-template-generation=1
Annotations:          <none>
Status:               Running
IP:                   192.168.49.2
IPs:
  IP:           192.168.49.2
Controlled By:  DaemonSet/kube-proxy
Containers:
  kube-proxy:
    Container ID:  
    Image:         registry.k8s.io/kube-proxy:v1.26.3
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/local/bin/kube-proxy
      --config=/var/lib/kube-proxy/config.conf
      --hostname-override=$(NODE_NAME)
    State:          Waiting
      Reason:       CreateContainerError
    Last State:     Terminated
      Reason:       ContainerStatusUnknown
      Message:      The container could not be located when the pod was deleted.  The container used to be Running
      Exit Code:    137
      Started:      Mon, 01 Jan 0001 00:00:00 +0000
      Finished:     Mon, 01 Jan 0001 00:00:00 +0000
    Ready:          False
    Restart Count:  1
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /lib/modules from lib-modules (ro)
      /run/xtables.lock from xtables-lock (rw)
      /var/lib/kube-proxy from kube-proxy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-7ltxq (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-proxy:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      kube-proxy
    Optional:  false
  xtables-lock:
    Type:          HostPath (bare host directory volume)
    Path:          /run/xtables.lock
    HostPathType:  FileOrCreate
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  kube-api-access-7ltxq:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/network-unavailable:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                  From               Message
  ----     ------     ----                 ----               -------
  Normal   Scheduled  23m                  default-scheduler  Successfully assigned kube-system/kube-proxy-hpn6m to crio
  Normal   Pulled     23m                  kubelet            Container image "registry.k8s.io/kube-proxy:v1.26.3" already present on machine
  Normal   Created    23m                  kubelet            Created container kube-proxy
  Normal   Started    23m                  kubelet            Started container kube-proxy
  Warning  Failed     2m15s                kubelet            Error: container create failed: time="2023-04-24T13:23:16Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     2m14s                kubelet            Error: container create failed: time="2023-04-24T13:23:17Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     2m3s                 kubelet            Error: container create failed: time="2023-04-24T13:23:28Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     109s                 kubelet            Error: container create failed: time="2023-04-24T13:23:42Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     96s                  kubelet            Error: container create failed: time="2023-04-24T13:23:55Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     83s                  kubelet            Error: container create failed: time="2023-04-24T13:24:08Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     67s                  kubelet            Error: container create failed: time="2023-04-24T13:24:24Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     54s                  kubelet            Error: container create failed: time="2023-04-24T13:24:37Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Warning  Failed     43s                  kubelet            Error: container create failed: time="2023-04-24T13:24:48Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
  Normal   Pulled     1s (x12 over 2m15s)  kubelet            Container image "registry.k8s.io/kube-proxy:v1.26.3" already present on machine
  Warning  Failed     1s (x3 over 30s)     kubelet            (combined from similar events): Error: container create failed: time="2023-04-24T13:25:30Z" level=error msg="container_linux.go:380: starting container process caused: apply caps: operation not permitted"
```

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/11310903/log.txt)

### Operating System

macOS (Default)

### Driver

Docker

**Comment by mqasimsarfraz** [comment] 2023-06-22 13:51
It seems we need more work to get it fixed for macOS compared to Linux. I have opened an issue in [docker for mac](https://github.com/docker/for-mac/issues/6883) related to this. Also, it seems duplicate of https://github.com/kubernetes/minikube/issues/13742 so probably please close this one and we can track it via https://github.com/kubernetes/minikube/issues/13742 ?

**Closed** 2024-03-23 06:39 UTC
Labels: lifecycle/rotten
