### ISSUE TITLE
vmware: front-proxy-ca certificate: failed to load certificate: the certificate is not valid yet

### ISSUE THREAD

**Issue by mickeyf001** [kubernetes/minikube#5169] opened 2019-08-22 08:44 UTC
minikube start
😄  minikube v1.3.1 on Darwin 10.13.6

⚠️  Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the vmware driver.
⚠️  To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
⚠️  Alternatively, you may delete the existing VM using `minikube delete -p minikube`

🔄  Starting existing vmware VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: running cmd: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm init phase certs all --config /var/lib/kubeadm.yaml
stdout: [certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk

stderr: error execution phase certs/front-proxy-ca: failure loading front-proxy-ca certificate: failed to load certificate: the certificate is not valid yet
: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment] 2019-08-22 18:33
This issue appears to be a duplicate of #4832, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. If you have additional information to share, please add it to the new issue. In particular, I would like to see the output of:

`minikube start --alsologtostderr -v=2`

Thank you for reporting this!

**Closed by tstromberg** 2019-08-22 18:33 UTC
Labels: co/vmware-driver
