### ISSUE TITLE
[1.0.0] Bug with docker build ca.pem permissions on Ubuntu

### ISSUE THREAD

**Issue by staticdev** [kubernetes/minikube#4090] opened 2019-04-13 01:05 UTC
Fresh installed minikube on Ubuntu 18.10 and using a non-root user.
```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && chmod +x minikube
sudo cp minikube /usr/local/bin && rm minikube
```

* How to reproduce the error:

### minikube_setup.sh:

```
#!/bin/bash
set -e
minikube start
eval $(minikube docker-env)
docker build -t myimage:0.5.0 -f Dockerfile .
```
Was just following along the [documentation](https://kubernetes.io/docs/setup/minikube/) that implies this would work:

```sh
sh minikube_setup.sh
```

Then I receive the error:

> could not read CA certificate "/home/user/.minikube/certs/ca.pem": open /home/user/.minikube/certs/ca.pem: permission denied

I've also tried the solution on #3083: adding `owner @{HOME}/.minikube/certs/*` to /var/lib/snapd/apparmor/profiles/snap.docker.docker and running the parser, but the error persists.

I also tried running minikube with sudo and got the following output:

😄  minikube v1.0.0 on linux (amd64)
🤹  Downloading Kubernetes v1.14.0 images in the background ...
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
2019/04/13 08:45:23 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/13 08:45:23 No matching credentials were found, falling back on anonymous
 142.88 MB / 142.88 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 18.06.2-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.14.0
💾  Downloading kubelet v1.14.0
🚜  Pulling images required by Kubernetes v1.14.0 ...
🚀  Launching Kubernetes v1.14.0 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
could not read CA certificate "/root/.minikube/certs/ca.pem": open /root/.minikube/certs/ca.pem: permission denied

I've also seen on the [docs](https://kubernetes.io/docs/setup/minikube/) this problem occurs on CentOS, but there is no /etc/sysconfig/docker on Ubuntu.

**Comment by tstromberg** [comment] 2019-04-18 17:23
What's the output of:

`ls -la /home/user/.minikube/certs/ca.pem`

It sounds like a basic chmod/chown command should resolve this. Don't runt minikube as root unless you really must (like, for the none driver).

**Comment by staticdev** [comment] 2019-04-18 17:24
@tstromberg 
`-rw-rw-r-- 1 static static 1038 abr 12 23:14 /home/static/.minikube/certs/ca.pem
`

**Comment by tstromberg** [comment] 2019-04-18 18:04
Discussed on #minikube - seems to be a restriction by `snap` installed docker. Though apparently one we haven't figured out a workaround for. Dupe of #3083

**Closed by tstromberg** 2019-04-18 18:04 UTC
