### ISSUE TITLE
allow specifying extra option for k8s's proxy component bind address 0.0.0.0

### ISSUE THREAD

**Issue by ailsonfds** [kubernetes/minikube#6389] opened 2020-01-23 22:24 UTC
Running [minikube](https://github.com/kubernetes/minikube/releases/tag/v1.6.2 "minikube version: v1.6.2
commit: 54f28ac5d3a815d1196cd5d57d707439ee4bb392") on centos 8 VM (with firewalld disabled) and trying to make minikube start a proxy running on another address (cause it will be nice) with the extra config tag `proxy.BindAddress` (also try with `proxy.bindAddress`) and this is the result

```bash
[centos@k8s ~]$ minikube start --vm-driver=kvm2 --extra-config=proxy.BindAddress='0.0.0.0'
😄  minikube v1.6.2 on Centos 8.1.1911
✨  Selecting 'kvm2' driver from user configuration (alternates: [none])
🔥  Creating kvm2 VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
    ▪ proxy.BindAddress=0.0.0.0

💣  Failed to update cluster: generating kubeadm cfg: generating extra component config for kubeadm: unknown component map["apiserver":"apiServer" "controller-manager":"controllerManager" "kubeadm":"kubeadm" "kubelet":"" "scheduler":"scheduler"]. valid components are: map[apiserver:apiServer controller-manager:controllerManager kubeadm:kubeadm kubelet: scheduler:scheduler]

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

So...any idea to why is that happening?

**Comment by medyagh** [comment] 2020-02-26 19:35
@ailsonfds currently we only allow extra config for a specific set of components
if you think this is important, it would be easy to make a PR to add that component as well..

I would accept any PR that would implement it.

**Comment by ailsonfds** [comment] 2020-02-27 12:21
> @ailsonfds currently we only allow extra config for a specific set of components
> if you think this is important, it would be easy to make a PR to add that component as well..
> 
> I would accept any PR that would implement it.

I see...

I wasn't aware that this option wasn't available.

Thanks for the suggestion.

**Comment by medyagh** [comment] 2020-03-04 19:32
thanks for bringing it out attention that some users might need this ! I would accept a PR to add this to our whitelist of extra options

**Comment by tstromberg** [comment] 2020-04-16 00:14
This issue appears to be a duplicate of #6689, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-16 00:14 UTC
Labels: help wanted, kind/feature, priority/backlog, triage/support
