### ISSUE TITLE
addon ingress not installing 

### ISSUE THREAD

**Issue by pushan9** [kubernetes/minikube#11582] opened 2021-06-04 15:22 UTC
**Steps to reproduce the issue:** 

1. minikube addons enable ingress
2. not working getting error
3. witing for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by dinever** [comment] 2021-06-07 02:41
Hi @pushan9, thanks for reporting the issue. Could you share the output of `minikube logs` command?

**Comment by spowelljr** [comment] 2021-06-09 18:40
Hi @pushan9, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!

**Closed by spowelljr** 2021-06-09 18:40 UTC
Labels: addon/ingress, kind/support
