### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LaxmiJ88** [kubernetes/minikube#14517] opened 2022-07-06 11:13 UTC
### What Happened?

[root@ip-172-31-16-66 ~]# minikube start --driver=none
* minikube v1.26.0 on Amazon 2 (xen/amd64)
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Amazon Linux 2

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to execute operation: No such file or directory

### Attach the log file

[logs.txt.txt](https://github.com/kubernetes/minikube/files/9054227/logs.txt.txt)

### Operating System

Other

### Driver

Docker

**Comment by spowelljr** [comment] 2022-07-13 18:42
Hi @LaxmiJ88, thanks for reporting your issue with minikube. This is a duplicate of https://github.com/kubernetes/minikube/issues/14410. I have a detailed comment (https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503) that outlines what steps you should take depending on what driver you're using.

As a quick overview, if you're using the `docker` driver simply delete the minikube instance and recreate it and it should resolve your issue. If you're using the `none` driver follow the instructions on how to install cri-docker https://github.com/Mirantis/cri-dockerd#build-and-install.

I'm going to close this issue as it's a duplicate, but feel free to follow along with https://github.com/kubernetes/minikube/issues/14410, thanks!

**Closed by spowelljr** 2022-07-13 18:42 UTC
