### ISSUE TITLE
minikube enable addons: ingress-controller

### ISSUE THREAD

**Issue by Erfan-Motallebi** [kubernetes/minikube#12908] opened 2021-11-09 17:21 UTC
**Steps to reproduce the issue:** 

1. minikube start
2. minikube addons enable ingress

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>
Log file created at: 2021/11/09 20:25:35
Running on machine: c0d3rz
Binary: Built with gc go1.17.2 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I1109 20:25:35.345175  222800 out.go:297] Setting OutFile to fd 1 ...
I1109 20:25:35.345487  222800 out.go:349] isatty.IsTerminal(1) = true
I1109 20:25:35.345494  222800 out.go:310] Setting ErrFile to fd 2...
I1109 20:25:35.345501  222800 out.go:349] isatty.IsTerminal(2) = true
I1109 20:25:35.345671  222800 root.go:313] Updating PATH: /home/$USER/.minikube/bin
W1109 20:25:35.345846  222800 root.go:291] Error reading config file at /home/$USER/.minikube/config/config.json: open /home/$USER/.minikube/config/config.json: no such file or directory
I1109 20:25:35.346414  222800 config.go:176] Loaded profile config "minikube": Driver=docker, ContainerRuntime=docker, KubernetesVersion=v1.22.3
I1109 20:25:35.346436  222800 addons.go:65] Setting ingress=true in profile "minikube"
I1109 20:25:35.346447  222800 addons.go:153] Setting addon ingress=true in "minikube"
I1109 20:25:35.346729  222800 host.go:66] Checking if "minikube" exists ...
I1109 20:25:35.347625  222800 cli_runner.go:115] Run: docker container inspect minikube --format={{.State.Status}}
I1109 20:25:35.430240  222800 out.go:176]     ▪ Using image k8s.gcr.io/ingress-nginx/controller:v1.0.4
I1109 20:25:35.463439  222800 out.go:176]     ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
I1109 20:25:35.496926  222800 out.go:176]     ▪ Using image k8s.gcr.io/ingress-nginx/kube-webhook-certgen:v1.1.1
I1109 20:25:35.497428  222800 addons.go:348] installing /etc/kubernetes/addons/ingress-deploy.yaml
I1109 20:25:35.497449  222800 ssh_runner.go:319] scp memory --> /etc/kubernetes/addons/ingress-deploy.yaml (17469 bytes)
I1109 20:25:35.497531  222800 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
I1109 20:25:35.547280  222800 sshutil.go:53] new ssh client: &{IP:127.0.0.1 Port:49157 SSHKeyPath:/home/$USER/.minikube/machines/minikube/id_rsa Username:docker}

</details>

**Hint :** This is the result of command `kubectl get pods -n ingress-nginx`
<pre>

ingress-nginx-admission-create--1-zffm5           0/1        Completed   0        10h
ingress-nginx-admission-patch--1-4b2p5           0/1        Completed   2        10h
ingress-nginx-controller-5f66978484-gvsvd       1/1        Running       1        (32m ago)   9h 

</pre>

**Comment by sharifelgamal** [comment] 2021-12-15 20:34
Hey @Erfan-Motallebi, it's not clear to me what the issue is here. It looks like the ingress controller has started up successfully, since the pod is running.

**Comment by sharifelgamal** [comment] 2022-01-19 19:29
I'm going to go ahead and close this issue. If you would like to elaborate on this issue, feel free to reopen.

**Closed by sharifelgamal** 2022-01-19 19:29 UTC
Labels: kind/support
