### ISSUE TITLE
minikube start: Error starting cluster: kubeadm init error (Process exited with status 1)

### ISSUE THREAD

**Issue by zhannk** [kubernetes/minikube#3093] opened 2018-08-25 18:34 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:
Windows 10
VirtualBox-5.2.18-124319-Win.exe

**Minikube version** (use `minikube version`):  minikube version: v0.28.2
- **OS** (e.g. from /etc/os-release):  
00:00:37.595274 VMMDev: Guest Log: VBoxService 5.1.38 r122592 (verbosity: 0) linux.amd64 (May  9 2018 12:22:30) release log
00:00:37.595298 VMMDev: Guest Log: 00:00:00.000057 main     Log opened 2018-08-25T17:29:53.566532000Z
00:00:37.595345 VMMDev: Guest Log: 00:00:00.000139 main     OS Product: Linux
00:00:37.595372 VMMDev: Guest Log: 00:00:00.000169 main     OS Release: 4.15.0
00:00:37.595395 VMMDev: Guest Log: 00:00:00.000192 main     OS Version: #1 SMP Mon Jul 16 20:23:29 UTC 2018
00:00:37.595419 VMMDev: Guest Log: 00:00:00.000215 main     Executable: /usr/sbin/VBoxService
00:00:37.595426 VMMDev: Guest Log: 00:00:00.000216 main     Process ID: 2040
00:00:37.595432 VMMDev: Guest Log: 00:00:00.000217 main     Package type: LINUX_64BITS_GENERIC
00:00:37.597985 VMMDev: Guest Log: 00:00:00.002719 main     5.1.38 r122592 started. Verbose level = 0
00:00:38.112115 VMMDev: Guest Additions capability report: (0x0 -> 0x0) seamless: no, hostWindowMapping: no, graphics: no

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):   "DriverName": "virtualbox",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):        "Boot2DockerURL": "file://C:/Oracle/VMs/.minikube/cache/iso/minikube-v0.28.1.iso",

```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver": 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
when starting minikube with command: minikube.bat start --logtostderr --v 10 --alsologtostderr --vm-driver=virtualbox

minikube hangs a long time with log message: 
Setting up kubeconfig...
I0826 01:30:03.761439    5248 config.go:101] Using kubeconfig:  C:\Users\zhannk/.kube/config
Starting cluster components...
I0826 01:30:03.766341    5248 ssh_runner.go:80] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

and then failed with an error occurred with message:

**What you expected to happen**:
minikube should be started as before.

**How to reproduce it** (as minimally and precisely as possible):
Download latest minikube from https://github.com/kubernetes/minikube/releases
Download kubectl as described in https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Output of `minikube logs` (if applicable)**:
Setting up kubeconfig...
I0826 02:03:36.752179   10788 config.go:101] Using kubeconfig:  C:\Users\zhannk/.kube/config
Starting cluster components...
I0826 02:03:36.754183   10788 ssh_runner.go:80] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

E0826 02:33:41.246126   10788 start.go:300] Error starting cluster:  kubeadm init error
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1

**Comment by feng-haibo** [comment] 2018-08-26 08:12
I am seeing the same error with minikube v0.28.0 + virtualbox on both Ubuntu 4.15.0 and windows 10

**Comment by pourquoi42** [comment] 2018-09-11 12:44
Same problem here. ubuntu 16.04.

**Comment by tstromberg** [comment] 2018-09-18 21:42
I haven't been able to duplicate this yet. What's minikube.bat?

**Comment by tstromberg** [comment] 2018-09-18 22:55
Dupe of #3038

**Closed by tstromberg** 2018-09-18 22:55 UTC
Labels: drivers/virtualbox/windows, failed-start, platform/windows
