### ISSUE TITLE
Can not launch minikube on MacOS Big Sur 11.5.2 

### ISSUE THREAD

**Issue by enrico-j-yang** [kubernetes/minikube#12363] opened 2021-08-28 07:35 UTC
**Steps to reproduce the issue:** 

1.minikube start
2. 
3.

**Full output of `minikube logs` command:**
😄  minikube v1.22.0 on Darwin 11.5.2
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=1987MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.21.2 on Docker 20.10.7 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...| E0828 15:18:40.000703   47106 start.go:141] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.21.2

</details>

**Full output of failed command:**
<details>

</details>
[
[lastStart.txt](https://github.com/kubernetes/minikube/files/7070331/lastStart.txt)
](url)

**Comment by spowelljr** [comment] 2021-08-30 19:00
Hi @enrico-j-yang, thanks for reporting your issue with minikube!

This is an existing issue we're aware of (#8765) but have not yet fixed. The current work around is to run `minikube delete --all --purge` which will clear out the minikube configuration files.

Let me know if that solves your issue, thanks!

**Comment by spowelljr** [comment] 2021-09-08 20:04
Since this issue is a duplicate of #8765 I'm going to close this one. Please feel free to follow along and contribute to #8765, thanks!

**Closed by spowelljr** 2021-09-08 20:04 UTC
Labels: triage/duplicate
