### ISSUE TITLE
fix TestFunctional/parallel/BuildImage for docker driver with containerd runtime

### ISSUE THREAD

**Issue by ilya-zuyev** [kubernetes/minikube#11331] opened 2021-05-07 17:40 UTC
https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerd.html#fail_TestFunctional%2fparallel%2fBuildImage

Full log: https://storage.googleapis.com/minikube-builds/logs/master/c31bd57/Docker_Linux_containerdout.txt

Probably caused by 
```
functional_test.go:349: (dbg) Stderr: out/minikube-linux-amd64 -p functional-20210507151645-5565 image build -t localhost/my-image:functional-20210507151645-5565 testdata/build:
error: failed to get status: rpc error: code = Unavailable desc = connection error: desc = "transport: error while dialing: dial unix /run/buildkit/buildkitd.sock: connect: no such file or directory"
```

**Comment by afbjorklund** [comment] 2021-05-09 11:56
The test framework is supposed to start buildkitd. No idea why it didn't do that here ?

```
=== RUN   TestFunctional
=== RUN   TestFunctional/parallel
=== RUN   TestFunctional/parallel/BuildImage
=== PAUSE TestFunctional/parallel/BuildImage
=== CONT  TestFunctional/parallel/BuildImage
    functional_test.go:369: (dbg) Run:  out/minikube ssh -p minikube -- nohup sudo -b buildkitd --oci-worker=false --containerd-worker=true --containerd-worker-namespace=k8s.io
    functional_test.go:341: (dbg) Run:  out/minikube -p minikube image build -t localhost/my-image:minikube testdata/build
    functional_test.go:341: (dbg) Done: out/minikube -p minikube image build -t localhost/my-image:minikube testdata/build: (6.472253127s)
```

The linked logs seems to be from some other run ?

        --- PASS: TestFunctional/parallel/BuildImage (2.77s)

**Comment by spowelljr** [comment] 2021-05-13 21:10
Test had zero failures until the 7-9 of May at around 15% failure rate. It then recovered and hasn't failed since, possibly fixed by another PR or a PR was reverted. Was not able to reproduce and seems to have recovered, closing for now, we re-open if test starts failing again.

**Closed by spowelljr** 2021-05-13 21:10 UTC
Labels: co/runtime/containerd, kind/failing-test
