### ISSUE TITLE
i have error with Kubernetes in jenkins

### ISSUE THREAD

**Issue by stevenbill** [kubernetes/minikube#7434] opened 2020-04-05 10:54 UTC
![Screenshot from 2020-04-05 12-49-16](https://user-images.githubusercontent.com/29622827/78472879-97fe7400-773c-11ea-882e-976ae0416dc4.png)

**Comment by stevenbill** [comment] 2020-04-05 10:55
my  jenkins  on  Kubernetes pod

**Comment by afbjorklund** [comment] 2020-04-05 16:46
Duplicate of #7414

It seems that you are trying to use Minikube as a Jenkins cloud. This is not something that is generally supported, but as long as it can access the credentials it should work like any client...

**Comment by jatinkushwaha** [comment] 2020-04-08 09:46
I also facing the same issue... Please help!

**Closed** 2020-04-28 09:28 UTC
Labels: triage/support
