### ISSUE TITLE
qemu unexpectedly closed the monitor: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.

### ISSUE THREAD

**Issue by FansinZhao** [kubernetes/minikube#4277] opened 2019-05-17 02:30 UTC
**The exact command to reproduce the issue**:

$ minikube start
😄  minikube v1.0.1 on linux (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing kvm2 VM for "minikube" ...

💣  Unable to start VM: start: Error creating VM: virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2019-05-17T02:20:07.980140Z qemu-system-x86_64: error: failed to set MSR 0x38d to 0x0
qemu-system-x86_64: /build/qemu-lXHhGe/qemu-2.11+dfsg/target/i386/kvm.c:1807: kvm_put_msrs: Assertion `ret == cpu->kvm_msr_buf->nmsrs' failed.')

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: host is not running

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
**The operating system version**:
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

$ go version
go version go1.12.5 linux/amd64
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
$ minikube version
minikube version: v1.0.1
$ kvm -version
QEMU emulator version 2.11.1(Debian 1:2.11+dfsg-1ubuntu7.13)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers

**Comment by tstromberg** [comment] 2019-05-17 02:38
Thank you for sharing your experience!

This issue appears to be a duplicate of #2968, so I will close this in preference to that issue so that we may centralize the information around it. If you feel that this is not in fact a duplicate, please feel free to re-open this issue.

**Comment by tstromberg** [comment] 2019-05-17 02:41
Possibly related bug: https://bugzilla.redhat.com/show_bug.cgi?id=1651021

Is the Ubuntu host running under some sort of virtualization? Based on what I've read, it may be possible to get passed this error by upgrading to QEMU 3.1.0 or higher.

If that's not viable, you may want to try using minikube with `--vm-driver=virtualbox`

**Comment by tstromberg** [comment] 2019-05-22 21:34
Dupe of #2968

**Closed by tstromberg** 2019-05-22 21:34 UTC
Labels: co/kvm2, triage/support
