### ISSUE TITLE
hyperv: Job for docker.service failed because the control process exited with error code

### ISSUE THREAD

**Issue by csgordon** [kubernetes/minikube#4236] opened 2019-05-10 01:55 UTC
With a fresh install of minikube (via the Windows installer), following a fresh install of ```gcloud```, when trying to use minikube with Hyper-V, it seems to be unable to run docker commands inside the minikube VM. The logs might be suggesting that Hyper-V didn't satisfy a memory request (there's some complains about balloons).  The only other VM running on Hyper-V is the Docker MobyLinuxVM, and I have over 6GB of RAM free.

**The exact command to reproduce the issue**:
    minikube config set vm-driver hyperv
    minikube start
**The full output of the command that failed**:
```
PS C:\WINDOWS\system32> minikube.exe start
o   minikube v1.0.1 on windows (amd64)
$   Downloading Kubernetes v1.14.1 images in the background ...
>   Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
2019/05/09 21:24:53 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:53 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:54 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:54 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:55 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:55 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:56 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:57 No matching credentials were found, falling back on anonymous
2019/05/09 21:24:57 No matching credentials were found, falling back on anonymous
-   "minikube" IP address is 10.0.0.152
-   Configuring Docker as the container runtime ...

!   Failed to enable container runtime: command failed: sudo systemctl start docker
stdout:
stderr: Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
: Process exited with status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
PS C:\WINDOWS\system32>
```

**The output of the `minikube logs` command**:
```
PS C:\WINDOWS\system32> minikube.exe logs
E0509 21:36:18.386005   28784 logs.go:155] Failed to list containers for "kube-apiserver": Process exited with status 1
E0509 21:36:18.475464   28784 logs.go:155] Failed to list containers for "coredns": Process exited with status 1
E0509 21:36:18.582925   28784 logs.go:155] Failed to list containers for "kube-scheduler": Process exited with status 1
E0509 21:36:18.726895   28784 logs.go:155] Failed to list containers for "kube-proxy": Process exited with status 1
E0509 21:36:18.854799   28784 logs.go:155] Failed to list containers for "kube-addon-manager": Process exited with status 1
E0509 21:36:18.981436   28784 logs.go:155] Failed to list containers for "kubernetes-dashboard": Process exited with status 1
E0509 21:36:19.108776   28784 logs.go:155] Failed to list containers for "storage-provisioner": Process exited with status 1
==> dmesg <==
[  +0.227115] systemd[1]: Configuration file /usr/lib/systemd/system/containerd.service is marked executable. Please remove executable permission bits. Proceeding anyway.
[  +0.185551] systemd[2706]: docker.service: Failed to connect stdout to the journal socket, ignoring: Connection refused
[  +0.128191] docker-containe invoked oom-killer: gfp_mask=0x14280ca(GFP_HIGHUSER_MOVABLE|__GFP_ZERO), nodemask=(null), order=0, oom_score_adj=0
[  +0.000016] CPU: 1 PID: 2713 Comm: docker-containe Tainted: G        W  O     4.15.0 #1
[  +0.000001] Hardware name: Microsoft Corporation Virtual Machine/Virtual Machine, BIOS 090007  06/02/2017
[  +0.000002] Call Trace:
[  +0.000014]  dump_stack+0x5c/0x82
[  +0.000008]  dump_header+0x66/0x281
[  +0.000005]  oom_kill_process+0x223/0x430
[  +0.000004]  out_of_memory+0x28d/0x490
[  +0.000005]  __alloc_pages_slowpath+0x9db/0xd60
[  +0.000005]  ? trace_event_raw_event_mm_lru_activate+0x90/0x90
[  +0.000006]  __alloc_pages_nodemask+0x21e/0x240
[  +0.000006]  alloc_pages_vma+0x130/0x180
[  +0.000006]  __handle_mm_fault+0x429/0xa70
[  +0.000006]  ? __switch_to_asm+0x24/0x60
[  +0.000005]  handle_mm_fault+0xa5/0x1f0
[  +0.000006]  __do_page_fault+0x235/0x4b0
[  +0.000005]  ? page_fault+0x36/0x60
[  +0.000005]  page_fault+0x4c/0x60
[  +0.000004] RIP: 0033:0x45c142
[  +0.000003] RSP: 002b:000000c4202c9e10 EFLAGS: 00010246
[  +0.000003] Mem-Info:
[  +0.000008] active_anon:3718 inactive_anon:2106 isolated_anon:0
               active_file:25 inactive_file:19 isolated_file:0
               unevictable:116627 dirty:3 writeback:0 unstable:0
               slab_reclaimable:4593 slab_unreclaimable:5915
               mapped:14638 shmem:2148 pagetables:283 bounce:0
               free:3089 free_pcp:56 free_cma:0
[  +0.000006] Node 0 active_anon:14872kB inactive_anon:8424kB active_file:100kB inactive_file:76kB unevictable:466508kB isolated(anon):0kB isolated(file):0kB mapped:58552kB dirty:12k
B writeback:0kB shmem:8592kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
[  +0.000002] Node 0 DMA free:7348kB min:44kB low:56kB high:68kB active_anon:0kB inactive_anon:0kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB
managed:15908kB mlocked:0kB kernel_stack:0kB pagetables:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[  +0.000008] lowmem_reserve[]: 0 1826 1826 1826
[  +0.000006] Node 0 DMA32 free:5008kB min:5444kB low:7312kB high:9180kB active_anon:14872kB inactive_anon:8424kB active_file:100kB inactive_file:76kB unevictable:466508kB writependi
ng:12kB present:2080704kB managed:2011528kB mlocked:0kB kernel_stack:2704kB pagetables:1132kB bounce:0kB free_pcp:224kB local_pcp:224kB free_cma:0kB
[  +0.000008] lowmem_reserve[]: 0 0 0 0
[  +0.000005] Node 0 DMA: 1*4kB (U) 0*8kB 1*16kB (U) 1*32kB (U) 0*64kB 1*128kB (U) 0*256kB 0*512kB 1*1024kB (U) 1*2048kB (M) 1*4096kB (M) = 7348kB
[  +0.000022] Node 0 DMA32: 2*4kB (UE) 7*8kB (UME) 23*16kB (UE) 15*32kB (UE) 18*64kB (UE) 15*128kB (UME) 4*256kB (UM) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 5008kB
[  +0.000025] 118819 total pagecache pages
[  +0.000001] 0 pages in swap cache
[  +0.000002] Swap cache stats: add 0, delete 0, find 0/0
[  +0.000001] Free swap  = 0kB
[  +0.000001] Total swap = 0kB
[  +0.000002] 524174 pages RAM
[  +0.000001] 0 pages HighMem/MovableOnly
[  +0.000001] 17315 pages reserved
[  +0.000135] Out of memory: Kill process 2706 (dockerd) score 15 or sacrifice child
[  +0.000033] Killed process 2713 (docker-containe) total-vm:90492kB, anon-rss:3808kB, file-rss:17920kB, shmem-rss:0kB
[May10 01:28] systemd[1]: docker.service: Failed with result 'exit-code'.
[  +0.002727] systemd[1]: Failed to start Docker Application Container Engine.
[ +10.206599] NFSD: Unable to end grace period: -110
[May10 01:32] hv_balloon: Balloon request will be partially fulfilled. Not enough memory.

==> kernel <==
 01:36:19 up 10 min,  0 users,  load average: 0.00, 0.03, 0.03
Linux minikube 4.15.0 #1 SMP Thu Apr 25 20:51:48 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Thu 2019-05-09 21:26:48 UTC, end at Fri 2019-05-10 01:27:39 UTC. --
-- No entries --
PS C:\WINDOWS\system32>
```

**The operating system version**:
Windows 10 Enterprise, Build 17134

Thanks in advance for any help.

**Comment by tstromberg** [comment] 2019-05-16 18:57
This apparently is caused by docker OOM'ing due to dynamic memory being enabled, so a duplicate of #1766

Please re-open if you feel this is not the case.

**Closed by tstromberg** 2019-05-16 18:57 UTC
Labels: co/hyperv, ev/oom
