### ISSUE TITLE
none: certificate apiserver not signed by CA certificate ca: crypto/rsa: verification error

### ISSUE THREAD

**Issue by ZeeshanRaza25** [kubernetes/minikube#7302] opened 2020-03-28 18:15 UTC
**The exact command to reproduce the issue**:
sudo minikube start --vm-driver=none

**The full output of the command that failed**:<details>
$ sudo minikube start --vm-driver=none
😄  minikube v1.7.2 on Ubuntu 18.04
✨  Using the none driver based on user configuration
⌛  Reconfiguring existing host ...
🔄  Starting existing none VM for "minikube" ...
ℹ️   OS release is Ubuntu 18.04.4 LTS
🐳  Preparing Kubernetes v1.17.2 on Docker 18.09.9 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🚀  Launching Kubernetes ... 

💣  Error starting cluster: init failed. output: "-- stdout --\n[init] Using Kubernetes version: v1.17.2\n[preflight] Running pre-flight checks\n[preflight] Pulling images required for setting up a Kubernetes cluster\n[preflight] This might take a minute or two, depending on the speed of your internet connection\n[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'\n[kubelet-start] Writing kubelet environment file with flags to file \"/var/lib/kubelet/kubeadm-flags.env\"\n[kubelet-start] Writing kubelet configuration to file \"/var/lib/kubelet/config.yaml\"\n[kubelet-start] Starting the kubelet\n[certs] Using certificateDir folder \"/var/lib/minikube/certs\"\n[certs] Using existing ca certificate authority\n\n-- /stdout --\n** stderr ** \nW0328 18:11:09.497771   14542 validation.go:28] Cannot validate kube-proxy config - no validator is available\nW0328 18:11:09.497815   14542 validation.go:28] Cannot validate kubelet config - no validator is available\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\n\t[WARNING Swap]: running with swap on is not supported. Please disable swap\n\t[WARNING FileExisting-ethtool]: ethtool not found in system path\n\t[WARNING FileExisting-socat]: socat not found in system path\nerror execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: crypto/rsa: verification error\nTo see the stack trace of this error execute with --v=5 or higher\n\n** /stderr **": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.2
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Starting the kubelet
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority

stderr:
W0328 18:11:09.497771   14542 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0328 18:11:09.497815   14542 validation.go:28] Cannot validate kubelet config - no validator is available
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING FileExisting-ethtool]: ethtool not found in system path
	[WARNING FileExisting-socat]: socat not found in system path
error execution phase certs/apiserver: [certs] certificate apiserver not signed by CA certificate ca: crypto/rsa: verification error
To see the stack trace of this error execute with --v=5 or higher

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by tstromberg** [comment] 2020-03-28 18:30
Do you mind checking if this happens with  the latest version of minikube (v1.9.0)?

If possible, please add `--alsologtostderr` so that we get additional logs.

**Comment by tstromberg** [comment] 2020-04-02 18:04
This issue appears to be a duplicate of #6596, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-02 18:04 UTC
Labels: co/none-driver, ev/certificate-errors, needs-solution-message, triage/support
