### ISSUE TITLE
can't disable kube-dns: error disabling addon deploy/addons/kube-dns/kube-dns-controller.yaml

### ISSUE THREAD

**Issue by den-is** [kubernetes/minikube#2808] opened 2018-05-14 12:30 UTC
BUG_REPORT

- minikube version: v0.26.1
- macos 10.13.4
- virtualbox
- "Boot2DockerURL": "file:///Users/den/.minikube/cache/iso/minikube-v0.26.0.iso"

I'm trying to start minikube with coredns enabled and kube-dns disabled by default to replicate my production cluster.
First of all I've tried to disable kube-dns on already running minikube instance. And got error from bellow.

**What happened**:
```
❯ minikube addons disable kube-dns
[error disabling addon deploy/addons/kube-dns/kube-dns-controller.yaml: %!s(MISSING): Process exited with status 1]
```

**What you expected to happen**:
disable kube-dns and use coredns instead

**How to reproduce it** (as minimally and precisely as possible):
- get minikube v0.26.1
- minikube start
- minikube addons disable kube-dns

After that i've tryed to setup minikube using its configuration in ~/.minikube/config/config.json.
```
{
    "kube-dns": false,
    "coredns": true
}
```
`minikube addons list` shows appropriate addons as disabled/enabled
```
❯ minikube addons list
- addon-manager: enabled
- coredns: enabled
- dashboard: enabled
- default-storageclass: enabled
- efk: disabled
- freshpod: disabled
- heapster: disabled
- ingress: disabled
- kube-dns: disabled
- metrics-server: disabled
- registry: disabled
- registry-creds: disabled
- storage-provisioner: enabled
```

But when cluster still has kube-dns enabled and running:
```
❯ kubectl get deploy -n kube-system
NAME                   DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
coredns                1         1         1            1           3h
kube-dns               1         1         1            1           3h
kubernetes-dashboard   1         1         1            1           3h

❯ kubectl get po -l k8s-app=kube-dns -n kube-system
NAME                        READY     STATUS    RESTARTS   AGE
coredns-74585495ff-xmvg5    1/1       Running   0          4h
kube-dns-86f4d74b45-h9wvx   3/3       Running   0          4h
```
If there is way to completely disable kube-dns and run with coredns from very start ?

**Comment by den-is** [comment] 2018-05-15 06:56
Just to clarify. 
After starting minikube with config file which disables kube-dns and enables coredns.
One last step required to get rid of kube-dns:
```
kubectl -n kube-system delete deployment kube-dns
```

**Comment by tstromberg** [comment] 2018-09-19 17:35
Dupe of #2281

**Closed by tstromberg** 2018-09-19 17:35 UTC
Labels: lifecycle/rotten

**Comment by outception** [comment] 2019-07-02 09:04
minikube stop
vi ~/.minikube/config/config.json `# change some flag from true to false`
minikube start

`# then delete relative resources manually`
kubectl -n xxx delete xxx xxx
