### ISSUE TITLE
create error type for  "can't create with that IP, address already in use"

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9926] opened 2020-12-11 00:41 UTC
create better error type than  "GUEST_PROVISION"

```
=== RUN   TestFunctional/serial/StartWithProxy
    functional_test.go:231: (dbg) Run:  out/minikube-linux-amd64 start -p functional-20201211000550-316158 --memory=4000 --apiserver-port=8441 --wait=true --driver=docker 
    functional_test.go:231: (dbg) Non-zero exit: out/minikube-linux-amd64 start -p functional-20201211000550-316158 --memory=4000 --apiserver-port=8441 --wait=true --driver=docker : exit status 80 (6.59932072s)
        
        -- stdout --
        	* [functional-20201211000550-316158] minikube v1.15.1 on Debian 9.13
        	  - KUBECONFIG=/home/jenkins/minikube-integration/linux-amd64-docker-9924-312294-0a5ef42ed548d65694b6d96b487fbe0bf8b3db01/kubeconfig
        	  - MINIKUBE_BIN=out/minikube-linux-amd64
        	  - MINIKUBE_HOME=/home/jenkins/minikube-integration/linux-amd64-docker-9924-312294-0a5ef42ed548d65694b6d96b487fbe0bf8b3db01/.minikube
        	  - MINIKUBE_LOCATION=9924
        	* Using the docker driver based on user configuration
        	* Starting control plane node functional-20201211000550-316158 in cluster functional-20201211000550-316158
        	* Creating docker container (CPUs=2, Memory=4000MB) ...
        	
        	
        
        -- /stdout --
        ** stderr ** 
        	! Local proxy ignored: not passing HTTP_PROXY=localhost:36133 to docker env.
        	! Local proxy ignored: not passing HTTP_PROXY=localhost:36133 to docker env.
        	X Exiting due to GUEST_PROVISION: Failed to start host: can't create with that IP, address already in use
        	* 
        	* If the above advice does not help, please let us know: 
        	  - https://github.com/kubernetes/minikube/issues/new/choose
        
        ** /stderr **
    functional_test.go:233: failed minikube start. args "out/minikube-linux-amd64 start -p functional-20201211000550-316158 --memory=4000 --apiserver-port=8441 --wait=true --driver=docker ": exit status 80
    functional_test.go:238: start stdout=* [functional-20201211000550-316158] minikube v1.15.1 on Debian 9.13
          - KUBECONFIG=/home/jenkins/minikube-integration/linux-amd64-docker-9924-312294-0a5ef42ed548d65694b6d96b487fbe0bf8b3db01/kubeconfig
          - MINIKUBE_BIN=out/minikube-linux-amd64
          - MINIKUBE_HOME=/home/jenkins/minikube-integration/linux-amd64-docker-9924-312294-0a5ef42ed548d65694b6d96b487fbe0bf8b3db01/.minikube
          - MINIKUBE_LOCATION=9924
        * Using the docker driver based on user configuration
        * Starting control plane node functional-20201211000550-316158 in cluster functional-20201211000550-316158
        * Creating docker container (CPUs=2, Memory=4000MB) ...
        
        
        , want: *Found network options:*
    functional_test.go:243: start stderr=! Local proxy ignored: not passing HTTP_PROXY=localhost:36133 to docker env.
        ! Local proxy ignored: not passing HTTP_PROXY=localhost:36133 to docker env.
        X Exiting due to GUEST_PROVISION: Failed to start host: can't create with that IP, address already in use
        * 
        * If the above advice does not help, please let us know: 
          - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by priyawadhwa** [comment] 2021-02-10 19:37
Closing as a dupe of https://github.com/kubernetes/minikube/issues/9907

**Closed by priyawadhwa** 2021-02-10 19:37 UTC
Labels: kind/cleanup, priority/important-longterm
