### ISSUE TITLE
minikube start panic

### ISSUE THREAD

**Issue by dingdayu** [kubernetes/minikube#6488] opened 2020-02-04 12:59 UTC
**重现问题所需的命令**：

```bash
minikube start --vm-driver=virtualbox
```

**失败的命令的完整输出**：<details>
  Darwin 10.15.2 上的 minikube v1.6.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💿  正在下载 VM boot image...
    > minikube-v1.6.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.6.0.iso: 150.93 MiB / 150.93 MiB [-] 100.00% 3.55 MiB p/s 42s
🔥  正在创建 virtualbox 虚拟机（CPUs=2，Memory=2000MB, Disk=20000MB）...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd18f]

goroutine 32 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc0004725e0, 0xa, 0xc0004725eb, 0xa, 0xc0004725f6, 0x7, 0x0, 0x0, 0xc000585c68, ...)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc0004725e0, 0x1d, 0xc000789d10, 0x44, 0x0, 0x0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc000060f68, 0x4007a15)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0008153e0, 0xc000815410)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66

</details>

**`minikube logs`命令的输出**： <details>
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**使用的操作系统版本**：
OS: macOS
Driver: virtualbox

**Comment by dingdayu** [comment] 2020-02-04 13:01
Command retry:

```bash
  ✘  ~  minikube start --vm-driver=virtualbox                                                                                                              20:53   20.02.04 
😄  Darwin 10.15.2 上的 minikube v1.6.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd18f]

goroutine 106 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc00079c240, 0x6, 0xc00079c247, 0x20, 0xc00079c268, 0x6, 0x0, 0x0, 0xc00085dc68, ...)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc00079c240, 0x2e, 0xc000798b40, 0x55, 0x0, 0x0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0002e6768, 0x0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0007146f0, 0xc0007148a0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd18f]

goroutine 102 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc00053c440, 0xa, 0xc00053c44b, 0x7, 0xc00053c453, 0x5, 0x0, 0x0, 0xc000853c68, ...)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc00053c440, 0x18, 0xc000236680, 0x3f, 0x0, 0x0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc00013df68, 0x1)
	/private/tmp/minikube-20191220-87806-1hl6ne5/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0007146f0, 0xc0007147e0)
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/minikube-20191220-87806-1hl6ne5/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

**Comment by sharifelgamal** [comment] 2020-02-05 19:44
此问题应在minikube 1.7中修复，您可以升级并重试吗？

Closing as a duplicate of #6147

**Closed by sharifelgamal** 2020-02-05 19:44 UTC
Labels: l/zh-CN
