### ISSUE TITLE
Minikube seems to have issue with emptyDir directory rights

### ISSUE THREAD

**Issue by nvnobelen** [kubernetes/minikube#986] opened 2017-01-10 22:10 UTC
This is a bug report

Problem:

Minikube 0.14.0 seems to have a problem writing to disk with emptyDir, which disappears when the proposed solution is applied.

Proposed Solution:

Update the image with:

chmod o+x /var/lib/kubelet/pods
cd pods ; chmod -R 0755 .

**Comment by r2d4** [comment] 2017-01-10 22:19
Closing this as a dupe of #956

**Closed by r2d4** 2017-01-10 22:19 UTC
