### ISSUE TITLE
Driver "virtualbox" not found

### ISSUE THREAD

**Issue by bfallik** [kubernetes/minikube#420] opened 2016-07-28 00:59 UTC
I'm trying to experiment with minikube but can't start the VM.
```
$ minikube start --show-libmachine-logs
Starting local Kubernetes cluster...
E0727 20:53:10.102359   65464 start.go:78] Error starting host:  Error creating new host: Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
```
I'm not sure if I have the virtualbox driver installed but docker-machine can't find it, or if it's not installed at all.

I've installed docker-machine 0.7.0 via `brew`. I'm running minikube 0.7.0. I don't see the virtualbox driver installed via brew:
```
$ brew search docker-machine
docker-machine ✔                         docker-machine-nfs
docker-machine-driver-xhyve              docker-machine-parallels
```

I'm using virtualbox 5.1.2.

Thanks in advance.

**Comment by jimmidyson** [comment] 2016-07-28 16:55
This is pretty odd as the virtualbox driver is embedded in minikube... Is minikube in your PATH?

**Comment by bfallik** [comment] 2016-07-28 16:59
@jimmidyson minikube is on my path but not in a typical directory, I've copied minikube into ~/bin which is on my PATH.

**Comment by jimmidyson** [comment] 2016-07-28 17:02
And that still doesn't work for you I guess?

**Comment by bfallik** [comment] 2016-07-28 17:03
@jimmidyson yes, I logged this ticket because `minikube start` isn't working for me

**Comment by jimmidyson** [comment] 2016-07-28 17:16
Thanks for the sarcasm :) I read your last comment as you just tried putting it in your PATH, but anyway...

Can't think what could be wrong with this tbh. We have lots of users using virtualbox. Any ideas @dlorenc?

**Comment by bfallik** [comment] 2016-07-28 17:22
Sorry, didn't mean to come across as sarcastic. Wanted to make sure the issue was clear.

Let me know if I can provide any more details.

**Comment by bfallik** [comment] 2016-07-29 13:05
@jimmidyson when you said that "the virtualbox driver is embedded in minikube" what does that mean? minikube is a single binary executable. If the driver is embedded how is it invoked?

I'm trying to track down this issue but I'm not sure how to dig deeper. The error message doesn't explain what a virtualbox driver is, who owns it, or how it was supposed to be installed. Is it typically installed as part of virtualbox? If so where on disk does it live?

**Comment by imorti** [comment] 2016-07-29 13:12
ok hang on, I think we should start from the beginning. Install VirtualBox regularly. Are you on a MAC or Windows? It sounds like a MAC. So then the minikube binary should be in /usr/local/bin. Let's run ```ps://storage.googleapis.com/minikube/releases/v0.7.1/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/``` see if the regular install works then we can get into nuances.

**Comment by jimmidyson** [comment] 2016-07-29 13:27
@imorti The minikube binary can be anywhere accessible in the user's PATH. We don't require the binary to be in /usr/local/bin - but happy for that to be confirmed by testing it out :)

@bfallik Minikube follows the docker-machine way of using embedded drivers: re-execing itself with appropriate environment variables set. This invokes the embedded driver. The error you're getting is because it can't find `minikube` (the value of `os.Args[0]` if you run `minikube start ...` in your PATH (via `exec.LookPath`). External drivers (e.g. xhyve) are handled by execing the appropriate driver plugin binary - virtualbox is an embedded driver, hence no external plugin binary.

Does `which minikube` return the path you would expect? Do you have minikube in your PATH via symlink or anything like that?

**Comment by bfallik** [comment] 2016-07-29 13:29
@jimmidyson actually I think that /usr/local/bin is the key. I need to run to a meeting now but I was just able to get minikube to work but simply copying the binary I'd already downloaded from ~/bin into /usr/local/bin. Both ~/bin and /usr/local/bin are on my PATH.

I can dig a bit deeper once I'm out of this meeting.

**Comment by imorti** [comment] 2016-07-29 13:29
Agreed I just figure let's establish a baseline then introduce nuances.

**Comment by jimmidyson** [comment] 2016-07-29 13:38
That is interesting. There's definitely something different about your PATH then. There is no reference to `/usr/local/bin` in code & I know of many users that don't have the binary in that dir (me included).

So when you have time could you please share the output of:

1. `echo $PATH`
2. `which minikube` (once you've got it back in `~/bin` again)
3. And just to check you're not running it with `sudo` or anything else that could change the PATH when invoking it?

**Comment by bfallik** [comment] 2016-07-29 14:04
@jimmidyson 
```
$ echo $PATH
/Users/bfallik/.rvm/gems/ruby-2.1.3/bin:/Users/bfallik/.rvm/gems/ruby-2.1.3@global/bin:/Users/bfallik/.rvm/rubies/ruby-2.1.3/bin:/usr/local/Cellar/emacs/24.3/bin:~/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/X11/bin:/usr/local/go/bin:/Users/bfallik/.rvm/bin:/usr/local/Cellar/go/1.7rc3/libexec/pkg/tool/darwin_amd64:/Applications/Postgres.app/Contents/Versions/9.4/bin
```

What's odd is that which can't locate minikube when I move the binary back into ~/bin.
```
$ mv /usr/local/bin/minikube ~/bin/
$ which minikube
$ ls ~/bin/minikube
/Users/bfallik/bin/minikube
$ minikube start
Starting local Kubernetes cluster...
E0729 10:02:40.406482   17193 start.go:78] Error starting host:  Error getting state for host: Driver "virtualbox" not found. Do you have the plugin binary accessible in your PATH?
```

I think the issue has to do with how I was adding ~/bin to my PATH. Yup.

The problem is that ~/bin was on my PATH but I need to actually expand the tilde.

Thanks for the help all, sorry for the noise.

**Comment by dlorenc** [comment] 2016-07-29 20:18
Wow, nice debugging! Thanks for letting us know you got this fixed. I'll close this out for now, we can reopen and investigate a better error message or fix if we find this is common enough.

**Closed by dlorenc** 2016-07-29 20:18 UTC

**Comment by jimmidyson** [comment] 2016-07-29 21:38
@bfallik No need to apologise! Glad you got things working in the end.
