### ISSUE TITLE
❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### ISSUE THREAD

**Issue by jonathanharr92** [kubernetes/minikube#11511] opened 2021-05-26 14:25 UTC
Just started learning about Kubernetes, and I'm having some trouble enabling the addon ingress. 
It worked yesterday, or atleast I think it did. I could enable it however, which is the main problem I can't get passed today.

**Steps to reproduce the issue:** 

1. minikube start
2. minikube addon enable ingress

Basically all I'm trying to do is enable ingress, it takes 6 minutes. It keeps posting this in the log:
I0526 16:41:58.245045   17628 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
And then this happens after 6 minutes:

**Full output of failed command:**
<details>

I0526 16:06:28.284567   21688 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0526 16:06:28.284567   21688 kapi.go:108] duration metric: took 6m0.0402131s to wait for app.kubernetes.io/name=ingress-nginx ...
I0526 16:06:28.286159   21688 out.go:170] 
W0526 16:06:28.286690   21688 out.go:235] ❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
W0526 16:06:28.286690   21688 out.go:424] no arguments passed for "\n" - returning raw string
W0526 16:06:28.286690   21688 out.go:235] 
W0526 16:06:28.293210   21688 out.go:424] no arguments passed for "😿  If the above advice does not help, please let us know:\n" - returning raw string
W0526 16:06:28.293210   21688 out.go:424] no arguments passed for "👉  https://github.com/kubernetes/minikube/issues/new/choose\n\n" - returning raw string
W0526 16:06:28.293210   21688 out.go:424] no arguments passed for "Please attach the following file to the GitHub issue:\n" - returning raw string
W0526 16:06:28.293210   21688 out.go:424] no arguments passed for "😿  If the above advice does not help, please let us know:\n👉  https://github.com/kubernetes/minikube/issues/new/choose\n\nPlease attach the following file to the GitHub issue:\n- C:\\Users\\USER~1.SUR\\AppData\\Local\\Temp\\minikube_addons_a7b5bb9bb1f9c161dcddcb1d506bfd73b3ba789f_0.log\n\n" - returning raw string
W0526 16:06:28.294260   21688 out.go:235] [31m╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m                                                                                                                 [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m    😿  If the above advice does not help, please let us know:                                                   [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                 [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m                                                                                                                 [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m    Please attach the following file to the GitHub issue:                                                        [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m    - C:\Users\USER~1.SUR\AppData\Local\Temp\minikube_addons_a7b5bb9bb1f9c161dcddcb1d506bfd73b3ba789f_0.log    [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m│[0m                                                                                                                 [31m│[0m
W0526 16:06:28.294775   21688 out.go:235] [31m╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯[0m
W0526 16:06:28.295305   21688 out.go:235] 
</details>

EDIT:

I have the same problem, when trying to install the registry addon. It works fine through Kubernetes 1.19.7 within my Docker container however.

Additional info:
😄  minikube v1.20.0 on Microsoft Windows 10 Enterprise 10.0.19042 Build 19042
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.20.2 preload ...
    > preloaded-images-k8s-v10-v1...: 491.71 MiB / 491.71 MiB  100.00% 6.78 MiB
    > gcr.io/k8s-minikube/kicbase...: 358.10 MiB / 358.10 MiB  100.00% 4.47 MiB
    > gcr.io/k8s-minikube/kicbase...: 358.10 MiB / 358.10 MiB  100.00% 5.21 MiB
🔥  Creating docker container (CPUs=2, Memory=4000MB) ...
❗  This container is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Comment by henshalb** [comment] 2021-06-03 06:49
I got the same issue. But resolved using 
```
minikube stop
minikube start
minikube addon enable ingress
```

**Comment by spowelljr** [comment] 2021-06-09 18:40
Hi @jonathanharr92, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!

**Closed by spowelljr** 2021-06-09 18:40 UTC
Labels: kind/support

**Comment by Erfan-Motallebi** [comment] 2021-11-09 17:26
I got the same issue when running `minikube addons enable ingress`

- minikube version: v1.24.0
- Kubernetes version : It's been said in the detail mode. 
<details>
Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:41:28Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3", GitCommit:"c92036820499fedefec0f847e2054d824aea6cd1", GitTreeState:"clean", BuildDate:"2021-10-27T18:35:25Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}

</details>
- Docker Version: It's been said in the detail mode .
<details>
Client: Docker Engine - Community
 Version:           20.10.10
 API version:       1.41
 Go version:        go1.16.9
 Git commit:        b485636
 Built:             Mon Oct 25 07:42:59 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.10
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       e2f740d
  Built:            Mon Oct 25 07:41:08 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.11
  GitCommit:        5b46e404f6b9f661a205e28d59c982d3634148f8
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
</details>


I even tested out this approach: 
- minikube stop
- minikube start
- minikube addons enable ingress

**Comment by gotomypc** [comment] 2022-10-03 13:41
Solution： 
1.  Stop minikube and purge the image
   minikube stop
   minikube delete --purge=true

2.  set proxy, esp NO_PROXY, replece 192.168.2.184 with your proxy.
export HTTPS_PROXY="http://192.168.2.184:7078"
export HTTP_PROXY="http://192.168.2.184:7078"
export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.59.0/24,192.168.49.0/24,192.168.39.0/24

3.  Relaunch the minikube
minikube start --image-mirror-country=cn
