### ISSUE TITLE
istio operator addon is enabled by default !

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6271] opened 2020-01-10 22:14 UTC
I noticed since we merged the istio addon, users get an istio operator by default
```
NAMESPACE        NAME                               READY   STATUS              RESTARTS   AGE
istio-operator   istio-operator-5488b4489d-4hf82    0/1     ContainerCreating   0          19s
kube-system      coredns-6955765f44-fdvqn           0/1     ContainerCreating   0          21s
kube-system      coredns-6955765f44-tvbtq           0/1     ContainerCreating   0          21s
kube-system      etcd-minikube                      1/1     Running             0          6s
kube-system      kube-addon-manager-minikube        1/1     Running             0          6s
kube-system      kube-apiserver-minikube            1/1     Running             0          6s
kube-system      kube-controller-manager-minikube   1/1     Running             0          6s
kube-system      kube-proxy-w45wj                   1/1     Running             0          21s
kube-system      kube-scheduler-minikube            1/1     Running             0          6s
kube-system      storage-provisioner                0/1     ContainerCreating   0          19s
```

```
$ ./out/minikube addons list | grep enable
- addon-manager: enabled
- dashboard: enabled
- default-storageclass: enabled
- istio-provisioner: enabled
- storage-provisioner: enabled

```

CC: @fenglixa could this behavior be avoided?

**Comment by afbjorklund** [comment] 2020-01-11 08:31
Duplicate of #6262

**Comment by fenglixa** [comment] 2020-01-13 05:50
@medyagh , yes, it's the behavior as my design, the reason of  istio-provisioner is enabled by default:
1.  Enable/disable istio addon is based on istio-provisioner
2. KUBECTL_EXTRA_PRUNE_WHITELIST need to add into addon-manager to ensure istio could be enabled successfully, that will lead to we need to install related crd during minikube deployed.

**Comment by afbjorklund** [comment] 2020-01-13 06:30
You will have to come up with some other way of doing this, it should not be deployed by default.

**Comment by fenglixa** [comment] 2020-01-13 07:15
Sure, It's high priority to me, to make it works well, and also align with the product requirements.
I saw already a PR provided, will involve into it as well.

BR
-Feng

**Closed** 2020-02-05 19:14 UTC
Labels: kind/bug, priority/important-soon, triage/duplicate
