### ISSUE TITLE
Minikube on Ubuntu error

### ISSUE THREAD

**Issue by SabraO** [kubernetes/minikube#457] opened 2016-08-05 15:20 UTC
Hi,
When I launch minikube on ubuntu 15.10 via VirtualBox, I get the following error.

Starting local Kubernetes cluster...
E0805 20:10:40.312577    8966 start.go:78] Error starting host:  Error getting state for host: machine does not exist

VirtualBox is at the latest version of 5.1.2r108956.

**Comment by dlorenc** [comment] 2016-08-05 17:14
Could you run "minikube delete" and try again, with the flag:

minikube start --show-libmachine-logs

**Comment by SabraO** [comment] 2016-08-06 05:16
This is the error log I got.

Starting local Kubernetes cluster...
Running pre-create checks...
Creating machine...
(minikubeVM) Downloading /home/sabra/.minikube/cache/boot2docker.iso from file:///home/sabra/.minikube/cache/iso/minikube-0.5.iso...
(minikubeVM) Creating VirtualBox VM...
(minikubeVM) Creating SSH key...
(minikubeVM) Check network to re-create if needed...
(minikubeVM) Check network to re-create if needed...
E0806 10:02:06.556406    5774 start.go:78] Error starting host:  Error starting stopped host: Unable to start the VM: /usr/bin/VBoxManage startvm minikubeVM --type headless failed:
VBoxManage: error: The virtual machine 'minikubeVM' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

So I opened the VirtualBox app and on start I got an error "RTR3InitEx failed with rc=-1912 (rc=-1912)". Following which I re-installed VirtualBox. Earlier I had installed virtual box by downloading the .deb package for Ubuntu 15.10 and now I installed by following instructions in "Debian-based Linux distributions". But now when I start minikube with "minikube start --show-libmachine-logs" I get the following error message.

Starting local Kubernetes cluster...
Running pre-create checks...
Creating machine...
(minikubeVM) Downloading /home/sabra/.minikube/cache/boot2docker.iso from file:///home/sabra/.minikube/cache/iso/minikube-0.5.iso...
(minikubeVM) Creating VirtualBox VM...
(minikubeVM) Creating SSH key...
(minikubeVM) Check network to re-create if needed...
(minikubeVM) Waiting for an IP...
Waiting for SSH to be available...
E0806 10:32:35.877137   25185 start.go:78] Error starting host:  Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

Also when I open the VirtualBox app I saw the message "fatal could not read from boot medium system halted"

**Comment by dlorenc** [comment] 2016-08-10 19:46
Thanks for the report! The could not read from boot medium error looks like a duplicate of #431.

**Closed by dlorenc** 2016-08-10 19:46 UTC
Labels: kind/bug

**Comment by SabraO** [comment] 2016-08-12 06:10
Thanks. Removing the old iso file and starting using following command worked. Beforehand we can verify the shasum of the iso file as mentioned in #431.

minikube start --iso-url="https://storage.googleapis.com/minikube/minikube-0.5.iso" --show-libmachine-logs

**Comment by khomesh24** [comment] 2017-08-28 10:28
my system is spiting error while starting kubernetes:
can anyone help me
-----------------------------------------------------------------------------------------------------------------------------------
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
E0828 15:52:43.299388    4857 start.go:129] Error starting host: Temporary Error: Error configuring auth on host: Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
.

 Retrying.

**Comment by shubhamchaudhary** [comment] 2017-09-02 08:41
I was able to fix this by installing [cfssl](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/02-client-tools.md#install-cfssl).
