### ISSUE TITLE
minikube stop: Error decoding config from data: ELF

### ISSUE THREAD

**Issue by mittman** [kubernetes/minikube#5552] opened 2019-10-06 21:47 UTC
Possibly a dupe of #5499

**The exact command to reproduce the issue**:
$ minikube start --vm-driver=kvm2
...
$ kubectl delete deployment hello-node
$ minikube stop

**The full output of the command that failed**:<details>
* Stopping "minikube" in kvm2 ...
* "minikube" stopped.
* 
X update config
* Error: [SYSTEMCTL_EXIT_1] Error getting kubeconfig status: could not read config: Error decoding config from data: ELF>�"@@�l@8
                                                                                                                                 @/.@@@@@���@�@@@x�x�  @ @].].@.@n@n�g�g�=��M��M�`J
>NN����@�@���=��M��P�tdH3�H3�H3�llQ�tdR�td�=��M��/lib64/ld-linux-x86-64.so.2GNUSGo-74ZEobPBIyLQ5AID-uF/LpJY9TW9Yzf-EpodPhmo/I6yjHRmGfyYmARjWSXIt/avtUplE0PM5aRCOo9OApGNUC�Tc���3�=jA��B�`8�%/   �� �(

_Many lines of garbage characters_

�*�s�G�_���m������h��Mݑ������'�_W����2��g��	7
�j��#|RX,l��:X�щ���)�Nċ�?�5d��3_B��X���O�a��g߀|{�ѝ��}��~I�+��r�����5��Bx��Zg�~�Y7)��w�~S/�q�|W�������-��[�q�墄�?����ǁ�ޣ{��
I�~��r��B�xg�?�������='K����_,��iϤz�a��#¯��ǇW$|����
                                                   ���>��������!^
q����2|�|r�r����mo���c9��rڅ/�(aI����'B�/�������P/usr/local/go/src/runtime/runtime-gdb.py.symtab.strtab.shstrtab.interp.note.ABI-tag.note.go.buildid.note.gnu.build-id.gnu.hash.dynsym.dynstr.gnu.version.gnu.version_r.rela.dyn.rela.plt.init.text.fini.rodata.typelink.itablink.gopclntab.eh_frame_hdr.eh_frame.tbss.init_array.fini_array.dynamic.got.got.plt.data.noptrdata.bss.noptrbss.comment.zdebug_aranges.zdebug_pubnames.zdebug_info.zdebug_abbrev.zdebug_line.zdebug_frame.zdebug_str.zdebug_loc.zdebug_pubtypes.zdebug_ranges.debug_gdb_scripts@�#�@� 1@dB�@�$U���o�@�_
                                                                                       h@hx    g�@�(o����|���o�@��(@(�Bp� @ �  @  ���"@�"q.�T2nT2.	�@n@.��� ����� �����֯���'��'��
                                                                                                                                                                                     � �H3�H3�l��4��4��M����M�N>��O��P�@%�Q��A�� +�:��*�`� ����a V��XB E0�N���^�����o���*]0|D!���
                                   !���                                                  3��0?���?���/^M��'a�[
                                                                                                              ��l* �л-� ��&8
                                                                                                                            �l�: yaml: control characters are not allowed
💡  Suggestion: Run minikube from the C: drive.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1574

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
$ minikube logs

💣  command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: host is not running

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Fedora 29 (x86_64)

$ uname -r
5.0.5-200.fc29.x86_64

$ virsh --version
4.7.0

$ minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}

**Comment by tstromberg** [comment] 2019-10-09 20:27
This issue appears to be a duplicate of #5499, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-10-09 20:27 UTC
