### ISSUE TITLE
installing minikube version: v1.0.0

### ISSUE THREAD

**Issue by devopsravikumar** [kubernetes/minikube#4102] opened 2019-04-16 07:23 UTC
following  error while installing minikube version: v1.0.0

wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -O minikube
--2019-04-16 12:27:25--  https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.80, 2404:6800:4007:803::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40149464 (38M) [application/octet-stream]
Saving to: ‘minikube’

100%[=====================================================================================================================================================================>] 40,149,464  2.43MB/s   in 17s

2019-04-16 12:27:42 (2.23 MB/s) - ‘minikube’ saved [40149464/40149464]

[root@localhost ~]# wget https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
--2019-04-16 12:28:31--  https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.80, 2404:6800:4007:803::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38430320 (37M) [application/octet-stream]
Saving to: ‘docker-machine-driver-kvm2’

100%[=====================================================================================================================================================================>] 38,430,320  2.25MB/s   in 17s

2019-04-16 12:28:49 (2.10 MB/s) - ‘docker-machine-driver-kvm2’ saved [38430320/38430320]

[root@localhost ~]# chmod 755 minikube docker-machine-driver-kvm2
[root@localhost ~]# mv minikube docker-machine-driver-kvm2 /usr/local/bin/
[root@localhost ~]# minikube version
minikube version: v1.0.0
[root@localhost ~]# kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "14",
    "gitVersion": "v1.14.1",
    "gitCommit": "b7394102d6ef778017f2ca4046abbaa23b88c290",
    "gitTreeState": "clean",
    "buildDate": "2019-04-08T17:11:31Z",
    "goVersion": "go1.12.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@localhost ~]# minikube start --vm-driver kvm2
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
 10.33 MB / 142.88 MB [==>--------------------------------------]   7.23% 35m17s
 10.95 MB / 142.88 MB [===>-------------------------------------]   7.67% 33m16s
 142.88 MB / 142.88 MB [============================================] 100.00% 0s

!   Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating domain: Error defining domain xml:
<domain type='kvm'>
  <name>minikube</name>
  <memory unit='MB'>2048</memory>
  <vcpu>2</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>

  </features>
  <cpu mode='host-passthrough'/>
  <os>
    <type>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
  </os>
  <devices>
    <disk type='file' device='cdrom'>
      <source file='/root/.minikube/machines/minikube/boot2docker.iso'/>
      <target dev='hdc' bus='scsi'/>
      <readonly/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='/root/.minikube/machines/minikube/minikube.rawdisk'/>
      <target dev='hda' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <mac address='5c:c1:ea:14:f7:e0'/>
      <model type='virtio'/>
    </interface>
    <interface type='network'>
      <source network='minikube-net'/>
      <mac address='b4:d0:3d:18:e7:c8'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <rng model='virtio'>
      <backend model='random'>/dev/random</backend>
    </rng>

  </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

 wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -O minikube

wget https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 -O minikube

--2019-04-16 12:27:25--  https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.80, 2404:6800:4007:803::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 40149464 (38M) [application/octet-stream]
Saving to: ‘minikube’

100%[=====================================================================================================================================================================>] 40,149,464  2.43MB/s   in 17s

2019-04-16 12:27:42 (2.23 MB/s) - ‘minikube’ saved [40149464/40149464]

[root@localhost ~]# wget https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
--2019-04-16 12:28:31--  https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-kvm2
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.163.80, 2404:6800:4007:803::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.163.80|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 38430320 (37M) [application/octet-stream]
Saving to: ‘docker-machine-driver-kvm2’

100%[=====================================================================================================================================================================>] 38,430,320  2.25MB/s   in 17s

2019-04-16 12:28:49 (2.10 MB/s) - ‘docker-machine-driver-kvm2’ saved [38430320/38430320]

[root@localhost ~]# chmod 755 minikube docker-machine-driver-kvm2
[root@localhost ~]# mv minikube docker-machine-driver-kvm2 /usr/local/bin/
[root@localhost ~]# minikube version
minikube version: v1.0.0
[root@localhost ~]# kubectl version -o json
{
  "clientVersion": {
    "major": "1",
    "minor": "14",
    "gitVersion": "v1.14.1",
    "gitCommit": "b7394102d6ef778017f2ca4046abbaa23b88c290",
    "gitTreeState": "clean",
    "buildDate": "2019-04-08T17:11:31Z",
    "goVersion": "go1.12.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
[root@localhost ~]# minikube start --vm-driver kvm2
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
@   Downloading Minikube ISO ...
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
2019/04/16 12:29:48 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/04/16 12:29:48 No matching credentials were found, falling back on anonymous
 10.33 MB / 142.88 MB [==>--------------------------------------]   7.23% 35m17s
 10.95 MB / 142.88 MB [===>-------------------------------------]   7.67% 33m16s
 142.88 MB / 142.88 MB [============================================] 100.00% 0s

!   Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating domain: Error defining domain xml:
<domain type='kvm'>
  <name>minikube</name>
  <memory unit='MB'>2048</memory>
  <vcpu>2</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>

  </features>
  <cpu mode='host-passthrough'/>
  <os>
    <type>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
  </os>
  <devices>
    <disk type='file' device='cdrom'>
      <source file='/root/.minikube/machines/minikube/boot2docker.iso'/>
      <target dev='hdc' bus='scsi'/>
      <readonly/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='/root/.minikube/machines/minikube/minikube.rawdisk'/>
      <target dev='hda' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <mac address='5c:c1:ea:14:f7:e0'/>
      <model type='virtio'/>
    </interface>
    <interface type='network'>
      <source network='minikube-net'/>
      <mac address='b4:d0:3d:18:e7:c8'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <rng model='virtio'>
      <backend model='random'>/dev/random</backend>
    </rng>

  </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

centos-release-7-4.1708.el7.centos.x86_64

**Comment by tstromberg** [comment] 2019-04-22 16:38
Thanks for the bug report. This seems to be a duplicate of #4020 - do you mind following up there, with the output of `virt-host-validate`? Thank you!

**Closed by tstromberg** 2019-04-22 16:38 UTC
