### ISSUE TITLE
Exiting due to GUEST_START: Failed kubeconfig update: writing kubeconfig: Error writing file /etc/kubernetes/admin.conf: open /etc/kubernetes/admin.conf: permission denied

### ISSUE THREAD

**Issue by Cyberkabil10** [kubernetes/minikube#10108] opened 2021-01-08 00:56 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment] 2021-01-25 22:14
Hey @Cyberkabil10 thanks for opening this issue. It seems to be a dupe of #3405

As suggested in this comment (https://github.com/kubernetes/minikube/issues/3405#issuecomment-444192830) do you have KUBECONFIG=/etc/kubernetes/admin.conf set in your environment?

**Comment by choudharyanurag** [comment] 2021-01-28 11:11
Almost the same issue,
I am running M1 apple silicon MB Pro

First things first I do not have any thing set to KUBECONFIG in my environment variable. I am using minikube by doing a `make` on the minikube repo.

Following is the log 

> Anurags-MacBook-Pro:out anurag$ minikube start
> 😄  minikube v1.17.0 on Darwin 11.1
> ✨  Automatically selected the docker driver. Other choices: hyperkit, ssh
> 👍  Starting control plane node minikube in cluster minikube
> 🚜  Pulling base image ...
> 🔥  Creating docker container (CPUs=2, Memory=1981MB) ...
> 🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
> 💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
> stdout:
> 
> stderr:
> SIGSEGV: segmentation violation
> PC=0x0 m=0 sigcode=0
> 
> goroutine 1 [running]:
> qemu: uncaught target signal 11 (Segmentation fault) - core dumped
> 
> 
> 💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
> stdout:
> 
> stderr:
> 
> 
> 😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
> 
> ❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.20.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem,SystemVerification,FileContent--proc-sys-net-bridge-bridge-nf-call-iptables": Process exited with status 139 from signal SEGV
> stdout:
> 
> stderr:
> 
> 
> 😿  If the above advice does not help, please let us know:
> 👉  https://github.com/kubernetes/minikube/issues/new/choose
>

**Comment by ilya-zuyev** [comment] 2021-02-10 19:47
SIGSEGV on M1 is another issue: https://github.com/kubernetes/minikube/issues/10243

**Closed** 2021-02-10 19:50 UTC
Labels: kind/support, triage/needs-information
