### ISSUE TITLE
Bad file ownership in minikube deb packages

### ISSUE THREAD

**Issue by mgabeler-lee-6rs** [kubernetes/minikube#3544] opened 2019-01-18 15:01 UTC
Please provide the following details:

**Environment**:

**Minikube version**: 0.32.0, 0.33.0, probably others
- **OS**: Debian
- **VM Driver**: N/A
- **ISO version**: N/A
- **Install tools**: N/A
- **Others**: N/A

**What happened**: The package has the binary owned by non-root user/group.  On my system this ended up as `usbmix`/`geoclue`, but that is a somewhat random coincidence.  The package shows that it "thinks" it's trying to install the binary owned by `jenkins`/`jenkins`, which is also wrong, but points to the source of the error.

**What you expected to happen**: The minikube binary to be installed with standard permissions, specifically owned by root/root

**How to reproduce it** (as minimally and precisely as possible): Install the package.  `ls -l /usr/bin/minikube`

**Output of `minikube logs` (if applicable)**: N/A

**Anything else do we need to know**: N/A

**Comment by tstromberg** [comment] 2019-01-18 15:13
Ouch. That's terrible and should be fixed ASAP. I don't know the cause of this yet, but if anyone happens to, I'd be happy to review a PR which addresses this.

Marking as a v1.0 blocker due to its severity.

**Comment by leifcr** [comment] 2019-01-21 09:03
Ownership is correct when building the debian package under Ubuntu 18.04 locally using the docker image to build. This likely happens in the CI pipeline somewhere, because the the UID is set to 108, and GID is set to 113. dpkg-deb --build uses the exact UID/GID set on the file while building.

It look likes the builds are done by minikube-bot ?

Here are some options worth trying:
* Add ```fakeroot``` before ```dpkg-deb --build```
* Add ```--root-owner-group``` in ```dpkg-deb``` parameters, while building
* Changing to dpkg-buildpackage. (Gives more options, but stricter file structure when building)

I can give it a try if you have some information regarding how the build is performed for releases.

**Comment by afbjorklund** [comment] 2019-02-24 19:40
Using `fakeroot dpkg-deb --build` seems to be simplest to implement, and fixes the issue.

It seems to be available in the `$(BUILD_IMAGE)`, and should be available on the VM too.

**Closed** 2019-02-26 18:56 UTC
Labels: good first issue, help wanted, kind/bug, packaging/apt, priority/important-soon

**Comment by leifcr** [comment] 2019-03-08 20:35
thanks @afbjorklund for fixing, in #3745
