### ISSUE TITLE
kube-proxy configmap update: timed out (unknown root cause)

### ISSUE THREAD

**Issue by yaserrahimi** [kubernetes/minikube#2755] opened 2018-04-20 16:15 UTC
I start minikube by _minikube start_ command 
`Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0420 20:42:38.971223    4270 start.go:281] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
`
and I get this error

how can I fix it

**Comment by saeidakbari** [comment] 2018-04-22 11:25
same issue when upgrading from `v0.25.0` to `v0.26.1`

**Comment by vrajanap** [comment] 2018-04-22 18:55
I ran into this same error with Minikube in windows using Hyper-V driver.  I had followed the instructions at https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c and had turned off dynamic memory

**Comment by jmenzler** [comment] 2018-04-23 15:20
I had the same issue – Found out that my local firewall software (Little Snitch) blocked some minikube-related requests in the background (Silent Mode was active), which lead to the timeout on my Mac.

**Comment by jldeen** [comment] 2018-04-23 23:00
Confirming same issue here with 0.26.1

**Comment by aseempatni** [comment] 2018-04-24 04:13
Same here on Mac. Minikube version v0.26.1

**Comment by kenelite** [comment] 2018-04-24 11:37
Same here on Mac. 
#minikube version
minikube version: v0.26.1

minikube logs
-- Logs begin at Tue 2018-04-24 11:31:00 UTC, end at Tue 2018-04-24 11:31:16 UTC. --
Apr 24 11:31:11 minikube systemd[1]: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf:7: Unknown lvalue 'Wants' in section 'Install'
Apr 24 11:31:11 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --cadvisor-port has been deprecated, The default will change to 0 (disabled) in 1.12, and the cadvisor port will be removed entirely in 1.13
Apr 24 11:31:11 minikube kubelet[5448]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Apr 24 11:31:11 minikube kubelet[5448]: Flag --allow-privileged has been deprecated, will be removed in a future version
Apr 24 11:31:11 minikube kubelet[5448]: I0424 11:31:11.662881    5448 feature_gate.go:226] feature gates: &{{} map[]}
Apr 24 11:31:11 minikube kubelet[5448]: W0424 11:31:11.678500    5448 hostport_manager.go:68] The binary conntrack is not installed, this can cause failures in network connection cleanup.
Apr 24 11:31:11 minikube kubelet[5448]: I0424 11:31:11.678821    5448 server.go:376] Version: v1.10.0
Apr 24 11:31:11 minikube kubelet[5448]: I0424 11:31:11.679075    5448 feature_gate.go:226] feature gates: &{{} map[]}
Apr 24 11:31:11 minikube kubelet[5448]: I0424 11:31:11.679362    5448 plugins.go:89] No cloud provider specified.
Apr 24 11:31:11 minikube kubelet[5448]: F0424 11:31:11.679562    5448 server.go:233] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Apr 24 11:31:11 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/n/a
Apr 24 11:31:11 minikube systemd[1]: kubelet.service: Unit entered failed state.
Apr 24 11:31:11 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

**Comment by quiram** [comment] 2018-04-24 15:45
I have the same issue, although oddly enough the cluster seems to have started... I can access it via `kubectl`, deploy to it, etc.

**Comment by calebmadrigal** [comment] 2018-04-24 19:53
Same issue, also on `minikube version: v0.26.1`

**Comment by liming-gd** [comment] 2018-04-25 04:45
Got the same problem on v0.26.1 on Mac 10.13.2.

There is an error in `/etc/systemd/system/kubelet.service.d/10-kubeadm.conf`: 
> `Apr 24 11:31:11 minikube systemd[1]: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf:7: Unknown lvalue 'Wants' in section 'Install'`

So when systemd starts kebelet, it will ignore the config. I guess this is the reason, but I don't know how to modify the config file.

**Comment by hungvnvnext** [comment] 2018-04-27 02:13
Got the same issue on v0.26.1 on Mac 10.13.3.
Downgrade minikube to 0.25.2 and it seems to work fine.

**Comment by doubleceston** [comment] 2018-04-27 02:53
same issue on v0.26.0 on Mac High Sierra 10.13.4

**Comment by mission802** [comment] 2018-04-28 05:10
same issue on v0.26.0 on Mac High Sierra 10.13.4 base on vmware fusion 10.

**Comment by walterye** [comment] 2018-04-28 19:17
same issue on v0.26.1 on Mac High Sierra 10.13.2 base on xhyve

**Comment by feuerbach** [comment] 2018-05-01 08:29
I had this error when upgrading from 0.25 to 0.26.1. Simply performing `minikube delete` and then re-creating the cluster fixed the issue for me.

**Comment by cmal** [comment] 2018-05-02 02:47
same error:
minikube version: v0.26.1
Linux 4.13.0-38-generic #43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by markhm** [comment] 2018-05-03 17:58
Same error here.

Env:
  Darwin Marks-MacBook-Pro.local 17.5.0 Darwin Kernel Version 17.5.0: Fri Apr 13 19:32:32 PDT 2018; root:xnu-4570.51.2~1/RELEASE_X86_64 x86_64

  minikube version: v0.26.1

  minikube start --vm-driver=vmwarefusion

Downgrading via 0.25.2 via dciccale's the above-mentioned instructions worked. Many thanks dciccale...!

**Comment by asfernandes** [comment] 2018-05-03 18:04
I my case I did `minikube delete` and `minikube start` and it worked. In the first start try, I had a internet connection problem and pressed ctrl+c.

**Comment by cdavisafc** [comment] 2018-05-05 15:46
`minikube delete` followed by `minikube start` didn't work for me. Same or similar errors to what is reported here on version 0.26.1

Release v0.25.2 works fine.

**Comment by srinivaschejerla** [comment] 2018-05-07 02:56
this solution worked for me

initially it gave checksum error because version change but after given right string and followed steps is perfect 

here is output for reference

MacBook-Air:~ xx$ minikube version
minikube version: v0.25.2
MacBook-Air:~ xx$ minikube --vm-driver=virtualbox start
There is a newer version of minikube available (v0.26.1).  Download it here:
https://github.com/kubernetes/minikube/releases/tag/v0.26.1

To disable this notification, run the following:
minikube config set WantUpdateNotification false
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading localkube binary
 163.02 MB / 163.02 MB [============================================] 100.00% 0s
 0 B / 65 B [----------------------------------------------------------]   0.00%
 65 B / 65 B [======================================================] 100.00% 0sSetting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

**Comment by ccit-spence** [comment] 2018-05-10 00:49
minikube version: v0.26.1
Windows 10 Enterprise
Hyper-V

Was having the same issue with starting a cluster. Did the following and it worked.

`minikube delete`
`minikube start --kubernetes-version="v1.10.0" --vm-driver="hyperv"`

**Comment by pxlphile** [comment] 2018-05-16 12:56
Hi all, I run

- Windows 7 [Version 6.1.7601]
- minikube version: v0.26.1
- re-located MINIKUBE_HOME
- V-TX activated

and had the same issues. A normal

`minikube delete`
`minikube start`

worked for me.

D:\>minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0516 14:11:34.051234    9452 start.go:281] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy
gmap update: timed out waiting for the condition

D:\>minikube delete
Deleting local Kubernetes cluster...
Machine deleted.

D:\>minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

**Comment by tao12345666333** [comment] 2018-05-25 04:35
Same here on Linux (CentOS Linux release 7.4.1708 (Core) ).

```
Linux 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

minikube version: v0.27.0
```


```
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...

E0524 17:22:21.606627   28661 start.go:281] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
```

**Comment by boker** [comment] 2018-05-28 07:27
```
minikube delete
minikube start
```

The above worked for me.

**Comment by deniswsrosa** [comment] 2018-05-29 11:46
minikube delete
minikube start

Also worked for me

**Comment by fedemengo** [comment] 2018-05-29 20:00
On macOS using **hyperkit** instead of **virtualbox** driver fixs a similar problem

**Comment by fedemengo** [comment] 2018-05-29 20:01
On macOS using hyperkit instead of virtualbox driver fix a similar problem

**Comment by fedemengo** [comment] 2018-05-29 20:01
On macOS using **hyperkit** instead of **virtualbox** driver fix a similar problem

**Comment by julianduque** [comment] 2018-05-31 20:14
`minikube delete` && `minikube start` worked for me on macOS.

**Comment by abdennour** [comment] 2018-06-01 00:45
I am confirming the solution of @julianduque for macOS kubernauts. As a summary: 

```
brew cask reinstall minikube
minikube delete
minikube start
```

## Before applying this solution

![image](https://user-images.githubusercontent.com/1788384/40815300-29adbbca-654e-11e8-85bf-afb060182c60.png)


## After applying this solution

![image](https://user-images.githubusercontent.com/1788384/40815305-3440ae26-654e-11e8-8d5b-f597345537f0.png)

**Comment by andrewspiers** [comment] 2018-06-01 06:33
I had this issue on a linux host as well, and minikube delete followed by minikube start also fixed it.

**Comment by prayagupd** [comment] 2018-06-02 21:38
deleting and re-installing worked for with `minikube version: v0.27.0`

```bash
minikube delete
rm -rf ~/.minikube
brew reinstall kubectl

minikube start --vm-driver=xhyve
```

**Comment by Ankk98** [comment] 2018-06-05 06:10
I had a similar issue and I stopped firewall and deleted cluster and restarted it.
I am running Ubuntu 18 LTS.

**Comment by kevinlmadison** [comment] 2018-06-15 14:57
I moved from v0.26.1 to v0.28.0 and had the same issue.

`minikube delete`
`minikube start`

The above solution worked for me as well.

**Comment by jittakal** [comment] 2018-06-21 05:57
As a workarround we can start minikube with bootstrapper localkube, default is kubeadm.

WARNING: The localkube bootstrapper is now deprecated and support for it

`minikube start --bootstrapper=localkube`

**Comment by graphdb2** [comment] 2018-06-22 20:02
same issue on v0.28.0 

minikube delete
minikube start

The above solution worked for me as well. but more than once.

**Comment by kalexmills** [comment] 2018-06-30 22:30
Persists on Windows 10.1 Hyper-V on v0.28.0

For the record, I have disabled dynamic memory allocation -- which I suspect can cause long IPC delays due to swapping (perhaps). I only allocated 1024 MB -- I very much doubt it is not enough.

The default is for minikube to install a VM which has dynamic memory allocation. This *might* be why the delete / start workaround works (and is around).

**Comment by Akhil-Ck** [comment] 2018-07-05 19:32
issue on `v0.28.0`
```
minikube delete
minikube start
```
worked for me.

**Comment by alejovicu** [comment] 2018-07-12 18:53
Same here:
```
E0712 13:46:05.881941    4592 start.go:299] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
```
_OS_: Ubuntu 16.04.4 LTS
_Minikube_:   v0.28.0
_Virtualbox_: Version 5.2.8 r121009 (Qt5.6.1)

**Comment by githublwp** [comment] 2018-07-20 02:13
issue was with 
Minikube: v0.28.1
OS: CentOS Linux release 7.5.1804 (Core)
Virtualbox: 5.2.12r122591
I have done
minikube delete
minikube start
but there is also have problem
```
[root@localhost yum.repos.d]# VBoxManage -v
5.2.12r122591
[root@localhost yum.repos.d]# minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0720 09:20:12.230400    5195 start.go:305] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
[root@localhost yum.repos.d]# free -m
              total        used        free      shared  buff/cache   available
Mem:          15786        1729       11909           8        2147       13660
Swap:          7999           0        7999
[root@localhost yum.repos.d]# minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
[root@localhost yum.repos.d]# minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0720 10:02:48.727977    5779 start.go:300] Error starting cluster:  kubeadm init error 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command: 
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 

```

**Comment by danking** [comment] 2018-07-23 22:01
@githublwp, I encountered the same issue with the same version of minikube on Mac OS X. The following managed to repair my installation so I could successfully execute `minikube start`
```
minikube delete
rm -rf ~/.minikube
brew cask reinstall minikube # brew is an OS X package manager, this reinstalls minikube
```

I also noticed there is a new version of minikube, but I did not try upgrading to that.

**Comment by bitza85** [comment] 2018-07-26 12:34
@githublwp same for me
CentOS 7.5 with 
[root@nginx tmp]# minikube version
minikube version: v0.28.2
[root@nginx tmp]# VBoxManage -v
5.2.16r123759

minikube delete makes no sense here!

I'll try to understand what happens behind this StartCluster
https://github.com/kubernetes/minikube/blob/v0.28.2/cmd/minikube/cmd/start.go#L300

**Comment by bitza85** [comment] 2018-07-26 12:43
As interim solution I've used:
minikube start --bootstrapper=localkube

**Comment by iamkarlson** [comment] 2018-07-26 12:59
hyper-v same issue
```
E0726 14:41:49.967003    2324 start.go:305] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
C:\Users\705534> minikube version
minikube version: v0.28.2
```

**Comment by n1t1nv3rma** [comment] 2018-07-29 09:31
Same issue:
Homes-MBP:~ homekv$ docker -v
Docker version 1.12.0, build 8eab29e, experimental
Homes-MBP:~ homekv$ minikube delete
Homes-MBP:~ homekv$ rm -rf ~/.minikube
Homes-MBP:~ homekv$ brew reinstall kubectl
Homes-MBP:~ homekv$ brew cask reinstall minikube
Homes-MBP:~ homekv$ minikube start

worked fine - not sure whats the magic :( - but it worked for me too!

**Comment by ChristianLuxem** [comment] 2018-08-10 08:52
When i tried to reinstall minikube i received the following error:
`Error: It seems there is already a Binary at '/usr/local/bin/minikube'; not linking.`

The solution is to do the following: 
` rm -rf /usr/local/bin/minikube`
after that you can simply 
`brew cask reinstall minikube && minikube start`

**Comment by manish149** [comment] 2018-08-11 06:17
Just

`minikube delete
minikube start
`

worked for me !!!! 
Thanks

**Comment by entvikas** [comment] 2018-08-12 09:47
~ $minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0812 15:12:52.114237   24535 start.go:299] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition

**Comment by kondaurovDev** [comment] 2018-08-24 23:04
I've tried `minikube delete & minikube start` start but it didn't work
After that i've checked kubectl version (it was 1.9.1). Upgraded it upto 1.11.2
And tried to reinstall minikube cluster `minikube delete & minikube start` and it worked!

```
Aleksandrs-Mini:~ aleksandr$ minikube delete
Deleting local Kubernetes cluster...
Machine deleted.
Error deleting machine profile config
Aleksandrs-Mini:~ aleksandr$ minikube start
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.
Aleksandrs-Mini:~ aleksandr$ kubectl cluster-info
Kubernetes master is running at https://192.168.99.100:8443
KubeDNS is running at https://192.168.99.100:8443/api/v1/namespaces/kube-system/services/kube-dns:dns/proxy
```

**Comment by shubhaat** [comment] 2018-09-11 01:05
I had the same issue with
OS: Mac OSX High Sierra v10.13.6
minikube version: v0.28.2
kubectl version 1.10

I did a minikube delete && minikube start and it resolved the issue.

**Comment by rsrini7** [comment] 2018-09-18 12:17
i was using VPN.. same issue. after disconnect VPN. have to issue delete and start the minikube to work.

is there a way to use even VPN connected ?

**Comment by tstromberg** [comment] 2018-09-19 04:00
I suspect VPN issues in general for this error, but do you mind including the output of "minikube logs"? Thanks.

**Comment by tstromberg** [comment] 2018-09-20 17:06
closing as a dupe of #3031 - absent of any details that prove it to be a different issue.

**Closed by tstromberg** 2018-09-20 17:06 UTC
Labels: bootstrapper/kubeadm, failed/local-firewall-or-proxy, firewall-or-proxy-interference, kind/bug, more-info-needed, svc/kube-proxy, top5

**Comment by defender4github** [comment] 2018-09-25 14:15
Hi,
New to Kubernetes

I had the same issue with
OS: Mac OSX High Sierra v10.13.5
minikube version: v0.28.2
kubectl version 1.10

I did a minikube delete && minikube start and it resolved the issue. But it has happened again after pull more images from dockerhub

**Comment by Abrar124** [comment] 2018-10-23 08:28
I also face the same issue it's occurred because of uncomplete installation or setup of minikube in my case minikube version: v0.30.0
i solve this issue by using:

minikube delete
minikube start

and done it work's

**Comment by rucheeg** [comment] 2018-11-01 18:17
minikube delete followed by minikube start didn't work for me ojn Windows10. Same or similar errors to what is reported here on version 0.26.1. 
Release v0.25.2 works fine.

**Comment by irvifa** [comment] 2018-11-17 18:49
Happened on version `v0.30.0` `MacOS Mojave` solved by `minikube delete && minikube start`

**Comment by Gipada** [comment] 2018-11-30 10:46
Same here, v0.30.0; Ubuntu 18.04 solved by `minikube delete && minikube start`

**Comment by siso** [comment] 2018-12-08 14:15
Same error here on OS X with `minikube version: v0.30.0`.

Fixed as @dciccale suggested (thanks once again!) [here](https://github.com/kubernetes/minikube/issues/2755#issuecomment-385614774), replaced:

```
  version '0.29.0'
  sha256 '196b2cbf4003ccc3574ba105437ae675bcd9cf80e6f8396b5581d40c35c6070d'
```

**Comment by nunojusto** [comment] 2018-12-11 08:53
Ubunto 18.04
`minikube delete` followed by `minikube start` worked for me

**Comment by Pezhvak** [comment] 2018-12-18 10:35
i've found a solution and posted on #3031, i will post it here as well hope it help others:

open virtual box and remove all vms, then follow @n1t1nv3rma hint:
$ minikube delete
$ rm -rf ~/.minikube

now restart your computer (this did the trick for me, i did all these steps without restarting with no luck) 

$ brew cask reinstall minikube

but when you want to start minikube provide kubernetes version to it
first get current kubernetes version by running:
$ kubectl version
(mine is 1.13.1 right now)

now use it like so:
$ minikube start --kubernetes-version v1.13.1

Note: you have to prefix 'v' to the version otherwise it won't work.
Note2: being connected to a vpn will cause timeout issues

all these steps has been posted by others, i just ran them in this order and it worked.

**Comment by zhangxiaoyu-zidif** [comment] 2019-01-02 02:20
@Pezhvak 
failed again...
$ minikube start --kubernetes-version v1.13.1
Starting local Kubernetes v1.13.1 cluster...
Starting VM...
Downloading Minikube ISO
 178.88 MB / 178.88 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.13.1
Downloading kubelet v1.13.1
Finished Downloading kubeadm v1.13.1
Finished Downloading kubelet v1.13.1
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...
E0102 10:07:58.230268   83386 start.go:343] Error starting cluster:  timed out waiting to elevate kube-system RBAC privileges: creating clusterrolebinding: Post https://192.168.99.101:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?timeout=1m0s: EOF
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
	minikube config set WantReportErrorPrompt false
================================================================================

**Comment by zhangxiaoyu-zidif** [comment] 2019-01-02 02:47
when i change to v0.29.0 and kubernetes v1.11.0

```shell
minikube start --kubernetes-version="v1.11.0"
Starting local Kubernetes v1.11.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.11.0
Downloading kubelet v1.11.0
Finished Downloading kubeadm v1.11.0
Finished Downloading kubelet v1.11.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0102 10:46:36.922292   86001 start.go:297] Error starting cluster:  timed out waiting to elevate kube-system RBAC privileges: creating clusterrolebinding: Post https://192.168.99.105:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings: EOF
```

**Comment by Pezhvak** [comment] 2019-01-02 11:53
@zhangxiaoyu-zidif did you restart your server as i mentioned?

**Comment by ahmedamsaleh** [comment] 2019-01-09 19:50
I faced same problem, it is fixed by restarting my laptop; while the laptop is shutting down I saw a message about  VirtualBox interface is stuck.
minikube version: 1.12.4
OS: Windows7 64bit

**Comment by rmartinus** [comment] 2019-01-18 09:01
`minikube delete && minikube restart` works for me.
minikube version: v0.32.0
macOS: Mojave 10.14.2

**Comment by ipusi** [comment] 2019-01-26 06:09
> I had the exact same error message, as suggested by @hungvnvnext I downgraded minikube formula using homebrew and was able to start minikube.
> 
> maybe downgrading helps you until someone with minikube knowledge can review this issue.
> 
> my OS: macOS High Sierra 10.13.3
> VM: vmware fusion
> 
> ```
> $ brew cask edit minikube
> ```
> This is how it should look for minikube version 0.25.2
> 
> ```
> cask 'minikube' do
>   version '0.25.2'
>   sha256 'dc5b00c4a06e8160bd607732c9a2294598d803716e353293b4463cc2c9539eec'
> 
>   # storage.googleapis.com/minikube was verified as official when first introduced to the cask
>   url "https://storage.googleapis.com/minikube/releases/v#{version}/minikube-darwin-amd64"
>   appcast 'https://github.com/kubernetes/minikube/releases.atom',
>           checkpoint: 'ce48a5c392fb7b35a106ae78ca225bc3c01e4afcb99d96957d3f8d0dcf55d910'
>   name 'Minikube'
>   homepage 'https://github.com/kubernetes/minikube'
> 
>   depends_on formula: 'kubernetes-cli'
>   container type: :naked
> 
>   binary 'minikube-darwin-amd64', target: 'minikube'
> 
>   zap trash: '~/.minikube'
> end
> ```
> Re install minikube
> 
> ```
> $ minikube delete
> $ sudo rm -rf ~/.minikube
> $ brew cask reinstall minikube
> $ minikube --vm-driver=vmwarefusion start
> ```

virtualbox is better

**Comment by jadonant** [comment] 2019-02-07 15:42
$ minikube delete && minikube start ... worked for me.

**Comment by tennessine** [comment] 2019-02-25 14:24
export HTTP_PROXY="http://192.168.1.100:1087"
export HTTPS_PROXY="http://192.168.1.100:1087"
export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.1/24

```minikube delete
minikube start --docker-env=HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PROXY \
  --docker-env NO_PROXY=$NO_PROXY
```
mac os version: 10.14.3
minikube version: v0.34.1

It works for me.

**Comment by devendradate** [comment] 2019-10-22 13:31
Ubunto 18.04
`minikube delete` followed by `minikube start` worked for me
