### ISSUE TITLE
k8s.io/minikube-hostpath: support for volumeMode: block

### ISSUE THREAD

**Issue by YiannisGkoufas** [kubernetes/minikube#8295] opened 2020-05-28 09:52 UTC
**Steps to reproduce the issue:** 

1. Create a minikube cluster v1.8.2 using `minikube start --vm-driver=virtualbox`
2. Ssh in the vm and pull gcr.io/k8s-minikube/storage-provisioner:latest
3. Update the storage-provisioner pod to use the latest image
4. Modify RBAC as described https://github.com/kubernetes/minikube/issues/7218#issuecomment-628795243
5. Create the following PVC:
```
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
    storageClassName: standard
    volumeMode: Block
```

**Full output of failed command:** 

PVC remains pending and the provisioner gives the following logs:
```
I0528 09:44:51.316352       1 controller.go:1196] provision "default/set1-data-0-2tgr4" class "standard": started
E0528 09:44:51.332559       1 controller.go:1220] provision "default/set1-data-0-2tgr4" class "standard": failed to provision volume: k8s.io/minikube-hostpath does not support block volume provisioning
I0528 09:44:51.332919       1 event.go:281] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"set1-data-0-2tgr4", UID:"7e0b4207-f26b-4584-8251-7395095aac37", APIVersion:"v1", ResourceVersion:"9186", FieldPath:""}): type: 'Warning' reason: 'ProvisioningFailed' k8s.io/minikube-hostpath does not support block volume provisioning
```

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment] 2020-05-29 20:30
This is by design - I'm curious if any of the alternate hostpath providers, like https://github.com/rancher/local-path-provisioner support block volume provisioning. I suspect not.

In the near future, k8s.io/minikube-hostpath will likely be retired in favor of local-path-provisioner, so I'm going to close this for now as won't fix.  That said, if someone wants to fix this, we'll accept patches and reconsider. Thank you!

**Closed by tstromberg** 2020-05-29 20:30 UTC
Labels: addon/storage-provisioner, co/service, kind/feature, priority/backlog
