### ISSUE TITLE
RBAC: minikube start error

### ISSUE THREAD

**Issue by BYTZJB** [kubernetes/minikube#5858] opened 2019-11-07 09:58 UTC
**The exact command to reproduce the issue**:
minikube start --extra-config=apiserver.Authorization.Mode=RBAC

**The full output of the command that failed**:<details>
😄  minikube v1.5.2 on Darwin 10.15.1
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ HTTP_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ HTTPS_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
    ▪ http_proxy=http://yangweideMacBook-Pro.local:1087
    ▪ https_proxy=http://yangweideMacBook-Pro.local:1087
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
    ▪ env HTTP_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ env HTTPS_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
    ▪ env HTTP_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ env HTTPS_PROXY=http://yangweideMacBook-Pro.local:1087
    ▪ apiserver.Authorization.Mode=RBAC
🚜  Pulling images ...
🚀  Launching Kubernetes ...

💣  Error starting cluster: init failed. cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap\"": Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Mac OS  10.15.1

**Comment by medyagh** [comment] 2019-11-07 18:34
@BYTZJB do you mind retrying it with this log option so I see more logs ?

```minikube start --alsologtostderr -v=8 --extra-config=apiserver.Authorization.Mode=RBAC```

**Comment by tstromberg** [comment] 2019-11-15 03:48
I think we broke including stdout/stderr output when commands fail :(

`Error: unknown flag: --Authorization.Mode`

The root cause is the specified flag is no longer valid for Kubernetes. Where did you find it mentioned?

**Comment by tstromberg** [comment] 2019-11-15 03:49
This issue appears to be a duplicate of #2798, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-11-15 03:49 UTC
Labels: co/virtualbox, priority/awaiting-more-evidence, triage/support
