### ISSUE TITLE
Enabling 'default-storageclass' returned an error: running callbacks: 

### ISSUE THREAD

**Issue by abhya944** [kubernetes/minikube#9285] opened 2020-09-21 11:45 UTC
**Steps to reproduce the issue:** 
abhya@abhyas-MacBook-Pro hybrid_task6 % minikube start
😄  minikube v1.11.0 on Darwin 10.15.6
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
^Z
zsh: suspended  minikube start

1.Unable to restart cluster, will reset it: apiserver health: controlPlane never updated to v1.18.3
abhya@abhyas-MacBook-Pro hybrid_task6 % minikube start &
[2] 2364
abhya@abhyas-MacBook-Pro hybrid_task6 % 😄  minikube v1.11.0 on Darwin 10.15.6
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running virtualbox "minikube" VM ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...

abhya@abhyas-MacBook-Pro hybrid_task6 % 🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get https://192.168.99.100:8443/apis/storage.k8s.io/v1/storageclasses: x509: certificate is valid for 172.17.0.1, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.100]
🌟  Enabled addons: default-storageclass, storage-provisioner

abhya@abhyas-MacBook-Pro hybrid_task6 % 
💣  failed to start node: startup failed: Wait failed: node pressure: list nodes: Get https://192.168.99.100:8443/api/v1/nodes: x509: certificate is valid for 172.17.0.1, 10.96.0.1, 127.0.0.1, 10.0.0.1, not 192.168.99.100

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

[2]  - exit 70    minikube start

2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment] 2020-09-22 01:11
can you test this on minikube v1.13? I think we've fixed this in more recent releases. I believe it's caused by a cancelled startup.

**Comment by ArnabMukherjee1991** [comment] 2020-09-26 10:11
I am trying the same on latest Minikube on WSL2. Getting the same issue.
ubuntu@LAPTOP-U2BFMGHB:~$ minikube start
**😄  minikube v1.13.1 on Ubuntu 20.04**
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🤷  docker "minikube" container is missing, will recreate.
🔥  Creating docker container (CPUs=2, Memory=6300MB) ...
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.8 ...
🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://172.17.0.3:8443/apis/storage.k8s.io/v1/storageclasses": dial tcp 172.17.0.3:8443: i/o timeout]
🌟  Enabled addons: default-storageclass, storage-provisioner

**Comment by tstromberg** [comment] 2020-09-28 17:57
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Closed** 2020-09-28 17:57 UTC
