### ISSUE TITLE
failed to start minikube (windows 10, hyperv driver) from powershell in administrator mode

### ISSUE THREAD

**Issue by jenisov** [kubernetes/minikube#6063] opened 2019-12-11 18:49 UTC
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>

* minikube v1.6.0 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Selecting 'hyperv' driver from user configuration (alternates: [virtualbox])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Using the running hyperv "minikube" VM ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
*
X Failed to setup kubeconfig: writing kubeconfig: Error writing file C:\Users\dea/.kube/config: error acquiring lock for C:\Users\dea/.kube/config: timeout acquiring mutex
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

* ==> Docker <==
* -- Logs begin at Wed 2019-12-11 18:34:19 UTC, end at Wed 2019-12-11 21:34:19 UTC. --
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.033486101Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.033556603Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.033720407Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.033956414Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.033991715Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.034040816Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.034050717Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.81\n": exit status 1"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.034056517Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206177143Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206222444Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206291546Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206303446Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206311147Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206319447Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206327547Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206337147Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206344447Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206352548Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206533853Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206609855Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206940364Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206961764Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206989665Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.206998465Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207026866Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207035466Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207043367Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207052167Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207059167Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207065967Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207072767Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207105068Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207113769Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207121069Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207127669Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207213271Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207257773Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.207265973Z" level=info msg="containerd successfully booted in 0.176358s"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.216475326Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.216520727Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.216548428Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.216569628Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.217286548Z" level=info msg="parsed scheme: \"unix\"" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.217311949Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.217326149Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.217332749Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579888704Z" level=warning msg="Your kernel does not support cgroup blkio weight"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579921105Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579932506Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579936706Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579941306Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.579945506Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
* Dec 11 18:35:15 minikube dockerd[2739]: time="2019-12-11T18:35:15.580290515Z" level=info msg="Loading containers: start."
* Dec 11 18:35:16 minikube dockerd[2739]: time="2019-12-11T18:35:16.148271811Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Dec 11 18:35:16 minikube dockerd[2739]: time="2019-12-11T18:35:16.653757591Z" level=info msg="Loading containers: done."
* Dec 11 18:35:16 minikube dockerd[2739]: time="2019-12-11T18:35:16.790135536Z" level=info msg="Docker daemon" commit=633a0ea838 graphdriver(s)=overlay2 version=19.03.5
* Dec 11 18:35:16 minikube dockerd[2739]: time="2019-12-11T18:35:16.790295040Z" level=info msg="Daemon has completed initialization"
* Dec 11 18:35:17 minikube dockerd[2739]: time="2019-12-11T18:35:17.478908648Z" level=info msg="API listen on /var/run/docker.sock"
* Dec 11 18:35:17 minikube dockerd[2739]: time="2019-12-11T18:35:17.478967450Z" level=info msg="API listen on [::]:2376"
* Dec 11 18:35:17 minikube systemd[1]: Started Docker Application Container Engine.
*
* ==> container status <==
* time="2019-12-11T18:45:20Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> dmesg <==
* [Dec11 18:34] You have booted with nomodeset. This means your GPU drivers are DISABLED
* [  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
* [  +0.000000] Unless you actually understand what nomodeset does, you should reboot without enabling it
* [  +0.057697] MDS CPU bug present and SMT on, data leak possible. See https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html for more details.
* [  +0.048580] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [  +0.007985] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
*               * this clock source is slow. Consider trying other clock sources
* [ +17.375386] Unstable clock detected, switching default tracing clock to "global"
*               If you want to keep using the local clock, then add:
*                 "trace_clock=local"
*               on the kernel command line
* [  +0.000038] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
* [  +0.734602] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
* [  +0.437252] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
* [  +0.006746] systemd-fstab-generator[1222]: Ignoring "noauto" for root device
* [  +0.001209] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
* [  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
* [  +1.955971] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
* [  +1.552999] vboxguest: loading out-of-tree module taints kernel.
* [  +0.003113] vboxguest: PCI device not found, probably running on physical hardware.
* [ +28.247717] systemd-fstab-generator[2470]: Ignoring "noauto" for root device
* [Dec11 18:36] NFSD: Unable to end grace period: -110
* [Dec11 18:40] systemd-fstab-generator[3245]: Ignoring "noauto" for root device
*
* ==> kernel <==
*  18:45:20 up 11 min,  0 users,  load average: 0.04, 0.04, 0.03
* Linux minikube 4.19.81 #1 SMP Tue Dec 10 16:09:50 PST 2019 x86_64 GNU/Linux
* PRETTY_NAME="Buildroot 2019.02.7"
*
* ==> kubelet <==
* -- Logs begin at Wed 2019-12-11 18:34:19 UTC, end at Wed 2019-12-11 21:34:19 UTC. --
* -- No entries --

</details>

**The operating system version**:
Microsoft Windows 10 Pro 10.0.18362 Build 18362

**Comment by tstromberg** [comment] 2019-12-11 21:07
v1.6.1 is now available with this bug fixed: https://github.com/kubernetes/minikube/releases/tag/v1.6.1

Thank you for your patience!

Dupe of #6058

**Closed by tstromberg** 2019-12-11 21:07 UTC
