### ISSUE TITLE
 failed pulling image: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection

### ISSUE THREAD

**Issue by Logibox** [kubernetes/minikube#3270] opened 2018-10-24 13:50 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

Please provide the following details:

**Environment**:
minikube version: v0.30.0

OS:
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

VM driver:
    "DriverName": "kvm2",

ISO version
        "Boot2DockerURL": "file:///home/matthew/.minikube/cache/iso/minikube-v0.30.0.iso",
        "ISO": "/home/matthew/.minikube/machines/minikube/boot2docker.iso",

```
minikube version
echo "";
echo "OS:";
cat /etc/os-release
echo "";
echo "VM driver:"; 
grep DriverName ~/.minikube/machines/minikube/config.json
echo "";
echo "ISO version";
grep -i ISO ~/.minikube/machines/minikube/config.json
```

**What happened**:
`minikube start` hangs at the `Starting cluster components...` starge

**What you expected to happen**:
It not to hang

**How to reproduce it** (as minimally and precisely as possible):
`minikube start --vm-driver kvm2 -v 10 --cpus 8 --memory 16384`

**Output of `minikube logs` (if applicable)**:

[log.txt](https://github.com/kubernetes/minikube/files/2510735/log.txt)

**Anything else do we need to know**:

**Comment by tstromberg** [comment] 2018-10-29 17:55
This appears to be a firewalling issue, where the VM can't talk to the public internet. Dupe of #3115.

```
Oct 24 13:33:17 minikube kubelet[2926]: E1024 13:33:17.342586    2926 kuberuntime_manager.go:646] createPodSandbox for pod "kube-controller-manager-minikube_kube-system(814cdcfaba9d1c42b9a176ee6a2d0def)" failed: rpc error: code = Unknown desc = failed pulling image "k8s.gcr.io/pause-amd64:3.1": Error response from daemon: Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers) 
```

**Closed** 2018-10-29 17:56 UTC
