### ISSUE TITLE
vbox: Error setting up host only network on machine start: code E_FAIL (0x80004005) - Unspecified error

### ISSUE THREAD

**Issue by markcaudill** [kubernetes/minikube#5260] opened 2019-09-04 18:24 UTC
**The exact command to reproduce the issue**: `minikube start --vm-driver=virtualbox`

**The full output of the command that failed**:<details>
```
C:\Users\mark>minikube start --vm-driver=virtualbox
* minikube v1.3.1 on Microsoft Windows 10 Home 10.0.18362 Build 18362
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing virtualbox VM for "minikube" ...
E0904 14:22:16.181131   14428 start.go:723] StartHost: start: Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 531 of file VBoxManageModifyVM.cpp
*
X Unable to start VM: start: Error setting up host only network on machine start: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe modifyvm minikube --nic2 hostonly --nictype2 virtio --nicpromisc2 deny --hostonlyadapter2 VirtualBox Host-Only Ethernet Adapter #2 --cableconnected2 on failed:
VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended info not available)
VBoxManage.exe: error: Context: "LockMachine(a->session, LockType_Write)" at line 531 of file VBoxManageModifyVM.cpp

*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose


```

</details>

**The output of the `minikube logs` command**:<details>

```
*
X command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connectex: No connection could be made because the target machine actively refused it.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

```

</details>

**The operating system version**:

```
C:\Users\mark>"C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" --version
6.0.10r132072

C:\Users\mark>systeminfo

Host Name:                 REDACTED
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00326-10000-00000-AA981
Original Install Date:     9/3/2019, 6:21:26 PM
System Boot Time:          9/3/2019, 6:16:03 PM
System Manufacturer:       System manufacturer
System Model:              System Product Name
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 58 Stepping 9 GenuineIntel ~3201 Mhz
BIOS Version:              American Megatrends Inc. 1701, 8/6/2014
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,696 MB
Available Physical Memory: 20,917 MB
Virtual Memory: Max Size:  37,816 MB
Virtual Memory: Available: 24,582 MB
Virtual Memory: In Use:    13,234 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    REDACTED
Logon Server:              \\REDACTED
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB4506991
                           [02]: KB4503308
                           [03]: KB4508433
                           [04]: KB4512508
Network Card(s):           5 NIC(s) Installed.
                           [01]: Private Internet Access Network Adapter
                                 Connection Name: Ethernet 3
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.7.11.5
                                 IP address(es)
                                 [01]: 10.7.11.6
                                 [02]: fe80::a94a:7fdd:be41:5173
                           [02]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network #2
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.99.1
                                 [02]: fe80::f55a:8c6c:2a46:2301
                           [03]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [04]: VirtualBox Host-Only Ethernet Adapter
                                 Connection Name: VirtualBox Host-Only Network
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.56.1
                                 [02]: fe80::49c:f22:c73c:76a5
                           [05]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.163
                                 IP address(es)
                                 [01]: 192.168.1.236
                                 [02]: fe80::c065:e245:4b8c:c61
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
```

**Comment by tstromberg** [comment] 2019-09-04 18:46
This issue appears to be a duplicate of #5222. Do you mind if we follow-up there so that we keep the content in one place?

Thank you for reporting this!

**Closed** 2019-09-04 18:46 UTC
Labels: co/virtualbox, triage/support

**Comment by markcaudill** [comment] 2019-09-04 19:19
Sounds good.

As an additional datapoint, I totally uninstalled VirtualBox, delete ~/.minikube, ~/.minishift, and ~/kube (not sure if those were all necessary) and now minikube start is working. I _suspect_ the issue may have been with one of those directories' permissions.
