### ISSUE TITLE
minikube start with virtual box not working after upgrading Mac OS Monterey

### ISSUE THREAD

**Issue by sathishsoundharajan** [kubernetes/minikube#12943] opened 2021-11-13 10:02 UTC
**Steps to reproduce the issue:** 

minikube start --driver=virtualbox

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**
Attached the logs.txt

Steps i have taken until now

1. Uninstalled Virtualbox and reinstalled it
2. Enabled system security to allow oracle apps
3. Restart the system and tried once again

Virtual Box Information:

[VirtualBox Graphical User Interface
Version 6.1.28 r147628 (Qt5.6.3)
Copyright © 2021 Oracle Corporation and/or its affiliates. All rights reserved.](url)

**Full output of failed command if not `minikube start`:**
<details>

```
[logs.txt](https://github.com/kubernetes/minikube/files/7531789/logs.txt)
 minikube start --driver=virtualbox
😄  minikube v1.22.0 on Darwin 12.0.1
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup because of signal 10
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Details: 00:00:49.907607 GUI: Passing request to close Runtime UI from machine-logic to UI session.
🔄  Restarting existing virtualbox VM for "minikube" ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup because of signal 10
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Details: 00:00:49.907607 GUI: Passing request to close Runtime UI from machine-logic to UI session.

❌  Exiting due to PR_VBOX_BLOCKED: Failed to start host: driver start: Unable to start the VM: /usr/local/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup because of signal 10
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

Details: 00:00:49.907607 GUI: Passing request to close Runtime UI from machine-logic to UI session.
💡  Suggestion: Reinstall VirtualBox and verify that it is not blocked: System Preferences -> Security & Privacy -> General -> Some system software was blocked from loading
🍿  Related issue: https://github.com/kubernetes/minikube/issues/4107
```

</details>

**Comment by sathishsoundharajan** [comment] 2021-11-13 10:03
Logs File attached URL: https://github.com/kubernetes/minikube/files/7531789/logs.txt

**Comment by sathishsoundharajan** [comment] 2021-11-15 13:08
Anyone faced same issue with Mac OS Update ? I have tried all the stackoverflow blog posts and virtualbox forum answers.. Not getting anywhere.

**Comment by spowelljr** [comment] 2021-11-15 15:41
Hi @sathishsoundharajan, thanks for reporting your issue with minikube!

While your exact issue is unrelated, we included a fix in the v1.24.0 release of minikube (https://github.com/kubernetes/minikube/pull/12811) that adds a fix for using with VirtualBox versions 6.1.28 and above. You're currently using v1.22.0 so I'd strongly recommend updating minikube to v1.24.0.

But now to your issue, there's a duplicate issue (https://github.com/kubernetes/minikube/issues/12881), they have found the issue, which seems to be an issue between VirtualBox and macOS 12, but they found a way to use a maintenance version of VirtualBox which seems to fix the issue.

I'm going to close this issue as it's a duplicate of https://github.com/kubernetes/minikube/issues/12881, but feel free to carry on the conversation there, thanks!

**Closed by spowelljr** 2021-11-15 15:41 UTC

**Comment by sathishsoundharajan** [comment] 2021-11-15 17:16
@spowelljr  Thanks for the detailed info.. Sorry mentioned issue didn't come up in the google search.  Updating the virtualbox to the test build solves the above issue.

But even then i end up with this error now :)

```

minikube start --driver=virtualbox --kubernetes-version=v1.22.3
😄  minikube v1.24.0 on Darwin 12.0.1
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.22.3 preload ...
    > preloaded-images-k8s-v13-v1...: 501.73 MiB / 501.73 MiB  100.00% 14.20 Mi
🏃  Updating the running virtualbox "minikube" VM ...
❌  minikube is unable to connect to the VM: dial tcp 192.168.99.104:22: i/o timeout

	This is likely due to one of two reasons:

	- VPN or firewall interference
	- virtualbox network configuration issue

	Suggested workarounds:

	- Disable your local VPN or firewall software
	- Configure your local VPN or firewall to allow access to 192.168.99.104
	- Restart or reinstall virtualbox
	- Use an alternative --vm-driver
	- Use --force to override this connectivity check


❌  Exiting due to GUEST_PROVISION: Failed to validate network: dial tcp 192.168.99.104:22: i/o timeout

```

**Comment by sathishsoundharajan** [comment] 2021-11-15 17:22
@spowelljr Actually even the above issue solved by running this command
```
rm -rf ~/.minikube ~/.kube
``` 

and then started minikube

```
minikube start --driver=virtualbox --kubernetes-version=v1.22.3
😄  minikube v1.24.0 on Darwin 12.0.1
✨  Using the virtualbox driver based on user configuration
💿  Downloading VM boot image ...
    > minikube-v1.24.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.24.0.iso: 225.58 MiB / 225.58 MiB [ 100.00% 14.17 MiB p/s 16s
👍  Starting control plane node minikube in cluster minikube
💾  Downloading Kubernetes v1.22.3 preload ...
    > preloaded-images-k8s-v13-v1...: 501.73 MiB / 501.73 MiB  100.00% 14.18 Mi
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.22.3 on Docker 20.10.8 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
╭───────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                   │
│    You have selected "virtualbox" driver, but there are better options !                          │
│    For better performance and support consider using a different driver:                          │
│            - hyperkit                                                                             │
│            - vmware                                                                               │
│                                                                                                   │
│    To turn off this warning run:                                                                  │
│                                                                                                   │
│            $ minikube config set WantVirtualBoxDriverWarning false                                │
│                                                                                                   │
│                                                                                                   │
│    To learn more about on minikube drivers checkout https://minikube.sigs.k8s.io/docs/drivers/    │
│    To see benchmarks checkout https://minikube.sigs.k8s.io/docs/benchmarks/cpuusage/              │
│                                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────────────────────╯
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

```

Worked :) 

Posting this here, so it helps anyone in future.

**Comment by spowelljr** [comment] 2021-11-15 17:24
Hi @sathishsoundharajan, glad that everything worked out, thanks for using minikube!
