### ISSUE TITLE
TestStartStop/group/old-docker: calculate hash for cacert: Expecting: TRUSTED CERTIFICATE

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7194] opened 2020-03-24 07:21 UTC
this one fails consistantly 

also https://storage.googleapis.com/minikube-builds/logs/7196/653fac4/Docker_Linux.html#fail_TestStartStop%2fgroup%2fold-docker

```


I0324 01:16:49.628868   21735 kic_runner.go:91] Run: sudo /bin/bash -c "test -f /usr/share/ca-certificates/6279.pem && ln -fs /usr/share/ca-certificates/6279.pem /etc/ssl/certs/6279.pem"

I0324 01:16:49.812210   21735 kic_runner.go:91] Run: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem

W0324 01:16:49.987152   21735 exit.go:101] Failed to setup certs: certificate symlinks: calculate hash for cacert /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: exit status 1

stdout:

stderr:

unable to load certificate

140322467374272:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE

* 

X Failed to setup certs: certificate symlinks: calculate hash for cacert /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: exit status 1

stdout:

stderr:

unable to load certificate

140322467374272:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
```

The error message seems to be same as the other one
https://github.com/kubernetes/minikube/issues/7190

but it is _not_ same as the other Flake old-docker which is about CA Cert  https://github.com/kubernetes/minikube/issues/7200

**Comment by tstromberg** [comment] 2020-03-26 18:02
First appearance: Mar  4 15:38
Last appearance: Mar 25 23:22

**Comment by tstromberg** [comment] 2020-03-26 18:04
Looks predominantly Docker related, but there are two KVM occurrences:

-rw-r--r-- 1 jenkins jenkins 185526 Mar 25 17:22 /var/lib/jenkins/jobs/KVM_Linux_integration/builds/8990/KVM_Linux.txt
-rw-r--r-- 1 jenkins jenkins 139438 Mar 25 23:31 /var/lib/jenkins/jobs/KVM_Linux_integration/builds/8998/KVM_Linux.txt

**Comment by tstromberg** [comment] 2020-03-26 18:36
Dupe of #6956

**Closed by tstromberg** 2020-03-26 18:36 UTC
Labels: kind/failing-test, priority/important-soon
