### ISSUE TITLE
Networking issue on newly created cluster.

### ISSUE THREAD

**Issue by mr337** [kubernetes/minikube#670] opened 2016-10-07 16:51 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG

**Minikube version** (use `minikube version`):  v0.11.0 (and  v0.10.0)

**Environment**:
- **OS** (e.g. from /etc/os-release): Arch Linux
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **Docker version** (e.g. `docker -v`): Docker version 1.12.1, build 23cf638
- **Install tools**: None
- **Others**:

**What happened**:
When creating a cluster via `minikube start` networking isn't getting setup.
```
 $ minikube start
Starting local Kubernetes cluster...
E1007 11:35:19.571212    7811 start.go:87] Error starting host: Error creating host: Error creating machine: Error checking the host: Error checking and/or regenerating the certs: There was an error validating certificates for host "192.168.99.102:2376": dial tcp 192.168.99.102:2376: i/o timeout
You can attempt to regenerate them using 'docker-machine regenerate-certs [name]'.
Be advised that this will trigger a Docker daemon restart which might stop running containers.
. Retrying.
Kubectl is now configured to use the cluster.
```
```
minikube ip
192.168.99.102
```

With v0.10.0, it would only say Kubectl is ready, but any kubectl command resulted in same `i/o timeout`.

**What you expected to happen**:
Simple commands like `kubectl get pod` work. 

**How to reproduce it** (as minimally and precisely as possible):
1. No existing machines in VBox, confirmed by VBox GUI
1. Run `minikube start`
1. Any kubectl commands after that timeout.

**Anything else do we need to know**:
If this helps, `ip addr` after running `minikube start`
```
 $ ip addr
4: docker0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default
    link/ether 02:42:92:49:25:0d brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 scope global docker0
       valid_lft forever preferred_lft forever
5: vboxnet0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether 0a:00:27:00:00:00 brd ff:ff:ff:ff:ff:ff
```

**Comment by r2d4** [comment] 2016-10-07 16:54
I suspect this is a dupe of https://github.com/kubernetes/minikube/issues/549.  We've added net-tools as a dependency in the AUR that we are going to push today from this PR https://github.com/kubernetes/minikube/pull/668

Let me know if installing that package fixes your problem.

**Comment by mr337** [comment] 2016-10-07 18:20
That was it. I checked the AUR this morning and it was marked as out of date with v.0.9. So you guys must have pushed just a little bit ago. :+1: 

```
$ minikube start            
Starting local Kubernetes cluster...
Kubectl is now configured to use the cluster.
 $ kubectl get nodes  
NAME       STATUS    AGE
minikube   Ready     3s
```

This is the first I heard of net-tools as a req, for non packaged install should we include a little blurb about it?

**Comment by r2d4** [comment] 2016-10-07 18:43
Glad it worked for you.  Feel free to open a PR adding a little more info in the README under requirements

As far as I know, net-tools is only a dependency when using virtualbox on arch linux.  

You can see docker machine also has the same dependency https://www.archlinux.org/packages/community/i686/docker-machine/

**Closed** 2016-10-07 20:16 UTC
