### ISSUE TITLE
Minikube complains that VT-X/AMD-v is disabled in BIOS which is clearly wrong.

### ISSUE THREAD

**Issue by aes** [kubernetes/minikube#3739] opened 2019-02-23 15:30 UTC
I can run a virtualbox using the GUI just fine, but minikube complains that VT-X/AMD-v is disabled in BIOS which is clearly wrong. (Maybe there's some other good reason it can't run, but I wouldn't know, I get this message instead.)

- run `minikube start`
- output:
> 😄  minikube v0.34.1 on linux (amd64)
> 🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
> 💣  Unable to start VM: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
> 
> 😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
> 👉  https://github.com/kubernetes/minikube/issues/new
- Operating system name and version
  - lsb_release:
    > Distributor ID:	Debian
    > Description:	Debian GNU/Linux buster/sid
    > Release:	oldstable-updates
    > Codename:	sid
  - uname -a:
    > Linux zzz 4.19.0-2-amd64 #1 SMP Debian 4.19.16-1 (2019-01-17) x86_64 GNU/Linux
  - minikube version
    > minikube version: v0.34.1

**Comment by afbjorklund** [comment] 2019-02-23 16:40
If you happen to have a AMD CPU, this issue is a duplicate of #3706

**Comment by tstromberg** [comment] 2019-03-08 14:53
Alos fixed in v0.35.0.

**Closed** 2019-03-08 14:53 UTC
Labels: cause/libmachine-bug, co/virtualbox, kind/bug, triage/duplicate

**Comment by mattscottuk** [comment] 2020-11-12 20:42
This is also happening to me (Windows 10 Home, VirtualBox, Intel i7-9750H).  Checked BIOS and VT-X is definately enabled.
