### ISSUE TITLE
Remove obsolete vmwarefusion driver in preference to vmware driver (HostIP not yet implemented)

### ISSUE THREAD

**Issue by Shikhar1210918** [kubernetes/minikube#8400] opened 2020-06-07 05:59 UTC
I am using Minikube on MacOS.
minikube start
😄  minikube v1.11.0 on Darwin 10.15.5
✨  Using the vmwarefusion driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running vmwarefusion "minikube" VM ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0607 11:25:55.231652   11845 start.go:94] Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver

💣  failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

**Comment by afbjorklund** [comment] 2020-06-07 07:46
Duplicate, #8374

**Comment by medyagh** [comment] 2020-06-08 22:09
@Shikhar1210918 was this working in previous versions of minikube?

**Comment by notjulian** [comment] 2020-06-17 06:21
> @Shikhar1210918 was this working in previous versions of minikube?

no same error with 1.10.1

😄  minikube v1.10.1 on Darwin 10.14.6
✨  Using the vmwarefusion driver based on existing profile
💿  Downloading VM boot image ...
🎉  minikube 1.11.0 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.11.0
💡  To disable this notice, run: 'minikube config set WantUpdateNotification false'

    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.10.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 9.63 MiB p/s 19s
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running vmwarefusion "minikube" VM ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0617 08:20:53.427066   45756 start.go:95] Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver

💣  failed to start node: startup failed: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by tstromberg** [comment] 2020-07-22 18:22
The `vmwarefusion` driver is deprecated. Please use the `vmware` driver instead: https://minikube.sigs.k8s.io/docs/drivers/vmware/

**Comment by tstromberg** [comment] 2020-07-22 18:23
This issue appears to be a duplicate of #8374, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-07-22 18:23 UTC
Labels: co/vmwarefusion, kind/bug, kind/cleanup, os/macos, priority/important-soon
