### ISSUE TITLE
hyperv: Unable to get host IP: No virtual switch found

### ISSUE THREAD

**Issue by dhaneesht** [kubernetes/minikube#8823] opened 2020-07-24 09:46 UTC
** Full command used to start **
minikube start --alsologtostderr -v=4

**Full output of failed command:** 
Refer Attachment: minikube_start.log

<details>

I have been trying to setup a minikube environment in my laptop(Windows 10) which has VPN configured. When I run the start command, it successfully creates the minikube vm but it fails during the process of creating the kubeconfig with the error that it wasn't able to fine the host IP.

I have configured the Virtual Switch aptly and I confirmed the IPs at both hosts (localhost and minikube vm).

Also I see that there are many steps that have successfully used the IP before failing at this step.

```
I0724 17:28:26.587027   93748 ssh_runner.go:148] Run: docker version --format {{.Server.Version}}
* Preparing Kubernetes v1.18.3 on Docker 19.03.12 ...
E0724 17:28:26.625045   93748 start.go:97] Unable to get host IP: No virtual switch found

```
Minikube Version: 1.12.1
[minikube_start.log](https://github.com/kubernetes/minikube/files/4971238/minikube_start.log)

</details>

**Comment by priyawadhwa** [comment] 2020-08-12 18:14
Hey @dhaneesht thanks for opening this issue.

There are some more details around running with hyperv [here](https://minikube.sigs.k8s.io/docs/drivers/hyperv/), and this issue seems to be a dupe of 

https://github.com/kubernetes/minikube/issues/5691

As suggested in https://github.com/kubernetes/minikube/issues/5691#issuecomment-545128647, could you try creating an external switch and see if minikube works with that?

**Comment by sharifelgamal** [comment] 2020-08-26 18:33
Any luck @dhaneesht ?

**Comment by dhaneesht** [comment] 2020-09-01 05:11
Hi,

I had already tried creating external switch but had no luck. What makes me feel bad is that the previous steps in the log is successfully using the IP, but for some reason, the failing step doesn't.

**Comment by medyagh** [comment] 2020-09-30 23:59
@dhaneesht I am sorry to hear your problem with HyperV driver, I wonder if you have had any luck with docker driver ?

**Comment by priyawadhwa** [comment] 2020-10-21 18:12
Hey @dhaneesht are you still seeing this bug?

**Comment by priyawadhwa** [comment] 2020-11-11 19:51
Hey @dhaneesht this issue has been quiet for a few weeks now so i'm going to close it, please reopen at any point by commenting /reopen if you can provide additional details. Thank you!

**Closed by priyawadhwa** 2020-11-11 19:51 UTC
Labels: kind/support, triage/needs-information
