### ISSUE TITLE
Spinner mess up minikube-pr-bot report

### ISSUE THREAD

**Issue by lingsamuel** [kubernetes/minikube#10043] opened 2020-12-24 03:00 UTC
https://github.com/kubernetes/minikube/pull/9920#issuecomment-747538974

![image](https://user-images.githubusercontent.com/14567045/103056184-35ede380-45d7-11eb-90fb-62b9bdeb5eda.png)

**Comment by priyawadhwa** [comment] 2020-12-28 19:30
Hey @lingsamuel thank you for opening this issue. I'm going to close it as a duplicate of #9939 , which is our solution for improving the output here.

**Closed by priyawadhwa** 2020-12-28 19:30 UTC
Labels: kind/support, triage/duplicate
