### ISSUE TITLE
none: [ERROR Port-2380]: Port 2380 is in use

### ISSUE THREAD

**Issue by sarthak8081** [kubernetes/minikube#6649] opened 2020-02-15 10:54 UTC
master01@OSDCCLDKUBMST03:~$ sudo minikube start --vm-driver=none
😄  minikube v1.7.2 on Ubuntu 19.10
✨  Using the none driver based on user configuration
⌛  Reconfiguring existing host ...
🏃  Using the running none "minikube" VM ...
ℹ️   OS release is Ubuntu 19.10
🐳  Preparing Kubernetes v1.17.2 on Docker 19.03.2 ...
    ▪ kubelet.resolv-conf=/run/systemd/resolve/resolv.conf
🚀  Launching Kubernetes ... 

💣  Error starting cluster: init failed. output: "-- stdout --\n[init] Using Kubernetes version: v1.17.2\n[preflight] Running pre-flight checks\n\n-- /stdout --\n** stderr ** \nW0215 16:20:21.831505   17433 validation.go:28] Cannot validate kube-proxy config - no validator is available\nW0215 16:20:21.831537   17433 validation.go:28] Cannot validate kubelet config - no validator is available\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists\n\t[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists\n\t[WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR Port-2379]: Port 2379 is in use\n\t[ERROR Port-2380]: Port 2380 is in use\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher\n\n** /stderr **": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.2:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.2
[preflight] Running pre-flight checks

stderr:
W0215 16:20:21.831505   17433 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0215 16:20:21.831537   17433 validation.go:28] Cannot validate kubelet config - no validator is available
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml]: /etc/kubernetes/manifests/kube-apiserver.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml]: /etc/kubernetes/manifests/kube-controller-manager.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml]: /etc/kubernetes/manifests/kube-scheduler.yaml already exists
	[WARNING FileAvailable--etc-kubernetes-manifests-etcd.yaml]: /etc/kubernetes/manifests/etcd.yaml already exists
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR Port-2379]: Port 2379 is in use
	[ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by medyagh** [comment] 2020-02-26 19:20
@sarthak8081 it seems like your system has a different cgroup for none driver,

is there any reason not to use docker driver instead of none ?

**Comment by tstromberg** [comment] 2020-03-25 18:13
This one is a bit troublesome because of the `Reconfiguring existing host ...` issue that shows that we know Kubernetes is running already. I'll see if I can improve this.

**Comment by tstromberg** [comment] 2020-03-25 18:15
This issue appears to be a duplicate of #6245, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-03-25 18:15 UTC
Labels: cause/port-conflict, co/none-driver, needs-faq-entry, needs-solution-message, top-10-issues, triage/needs-information, triage/support

**Comment by tstromberg** [comment] 2020-04-02 20:06
Eliminated this issue in v1.9.
