### ISSUE TITLE
validate profile name (shouldn't start with numbers)

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#6307] opened 2020-01-14 00:29 UTC
while trying to name my profile 2 by mistake, I noticed kic cant create a docker container starting with a numeric name.

possilbe solutions
1- append minikube name to all VM and Containers we create
or alternatievely validate profile name not to start with numbers.

**Comment by prasadkatti** [comment] 2020-04-19 01:20
duplicate of #7627 
fixed in #7635

**Closed by prasadkatti** 2020-04-19 01:20 UTC
Labels: kind/feature, priority/important-longterm, triage/duplicate
