### ISSUE TITLE
proxy+VPN: apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by jfrabetti** [kubernetes/minikube#4942] opened 2019-08-01 16:44 UTC
Hello,

I am on a Mac HighSierra 10.13.6.  I am on a VPN.  I set up my proxy for Docker in Docker Preferences, I can connect to my remote cluster using kubectl, I use the following commands to start minikube (I used actual proxy info):

vpn-135-210-77-42:~ jo$ export HTTP_PROXY='<proxy:port>'
vpn-135-210-77-42:~ jo$ export HTTPS_PROXY='<proxy:port>'
vpn-135-210-77-42:~ jo$ export NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
vpn-135-210-77-42:~ jo$ minikube start
😄  minikube v1.2.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
🌐  Found network options:
    ▪ HTTP_PROXY=http://'<proxy:port>'
    ▪ HTTPS_PROXY=https://'<proxy:port>'
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ env HTTP_PROXY='<proxy:port>'
    ▪ env HTTPS_PROXY='<proxy:port>'
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: no objects passed namespace/tkuo be-system unapplych
vpn-135-210-77-42:~ jo$ minikube logs > minikube.log

Will minikube work with a VPN?  Thank you for any assistance with this error!

[minikube.log](https://github.com/kubernetes/minikube/files/3457734/minikube.log)

**Comment by tstromberg** [comment] 2019-08-01 18:24
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

* The full output of `minikube logs`
* The full output of `kubectl get po -A`

Thank you for sharing your experience!

**Comment by jfrabetti** [comment] 2019-08-02 20:21
Thank you for troubleshooting this, I would like to help as much as possible in this troubleshooting effort!  The full output of the minikube logs was attached in the previous post, but I started up minikube again and I am attaching the log (minikube_restart.log) and I could not run 'kubectl get po -A' ('kubectl get pods' did not make sense since no cluster) output.  I am using Cisco AnyConnect VPN software. I installed minikube using Homebrew. I am using VirtualBox 6.0.

😄  minikube v1.2.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
🌐  Found network options:
    ▪ HTTP_PROXY=one.proxy.att.com:8080
    ▪ HTTPS_PROXY=one.proxy.att.com:8080
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  Configuring environment for Kubernetes v1.15.0 on Docker 18.09.6
    ▪ env HTTP_PROXY=one.proxy.att.com:8080
    ▪ env HTTPS_PROXY=one.proxy.att.com:8080
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🔄  Relaunching Kubernetes v1.15.0 using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
❌  Problems detected in "kube-addon-manager":
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

I could not recreate that particular error, but it crashed again.  I found a post by [michaeljeffrey ](https://github.com/kubernetes/minikube/issues/3747), opened my Cisco Route Details panel (under the VPN lock on the Statistics pop-up) and Non-Secured Routes 192.168.xx.xx/24 169.254.xx.xx/xx but when I tried the sudo route add 192.168.xx.xx/24 -iface vboxnet0 (with my info), it still crashed.  Should I be using info from Cisco or the Docker subnet?

**Comment by tstromberg** [comment] 2019-08-22 19:21
That's interesting. Starting up the apiserver shouldn't depend on networking, but the Cisco VPN may be preventing network traffic from accessing the minikube IP on port 8443. 

We now have some documentation as far as what IP's to allow through. Please let me know if it helps:

https://minikube.sigs.k8s.io/docs/reference/networking/vpn/

If you get a chance to try again, I would be curious to see what the output of:

`minikube ssh "docker ps -a"` is

Thank you for your patience.

**Comment by tstromberg** [comment] 2019-09-20 04:43
Marking as dupe of #4302

**Closed by tstromberg** 2019-09-20 04:43 UTC
Labels: cause/firewall-or-proxy, ev/apiserver-timeout, triage/needs-information, triage/support
