### ISSUE TITLE
minikube start failed 

### ISSUE THREAD

**Issue by dfang** [kubernetes/minikube#3407] opened 2018-12-04 09:54 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:
macOS Mojave 10.14.1

**Minikube version** (use `minikube version`): v0.30.0
- **VM Driver**: hyperkit
- **ISO version** : minikube-v0.30.0.iso
- **Install tools**: homebrew
- **How to start**:
```
minikube start --vm-driver hyperkit --registry-mirror https://registry.docker-cn.com --docker-env HTTP_PROXY=http://`ipconfig getifaddr en0`:8118 --docker-env HTTPS_PROXY=http://`ipconfig getifaddr en0`:8118 --docker-env NO_PROXY=127.0.0.1,localhost,192.168.0.0/16,10.0.0.0/8 --logtostderr --v=10
```

**What happened**:
minikube start logs exited with status 1,  but minikube status shows running

log:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):
brew cask install minikube
install hyperkit driver
then start with 
```
minikube start --vm-driver hyperkit --registry-mirror https://registry.docker-cn.com --docker-env HTTP_PROXY=http://`ipconfig getifaddr en0`:8118 --docker-env HTTPS_PROXY=http://`ipconfig getifaddr en0`:8118 --docker-env NO_PROXY=127.0.0.1,localhost,192.168.0.0/16,10.0.0.0/8 --logtostderr --v=10
```
**Output of `minikube logs` (if applicable)**:
```
Starting cluster components...
I1204 17:41:00.870680    9203 ssh_runner.go:80] Run with output:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

E1204 17:42:09.976073    9203 start.go:297] Error starting cluster:  kubeadm init error
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns
 running command: : running command:
sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  &&
sudo /usr/bin/kubeadm alpha phase addon kube-dns

.: Process exited with status 1
```

**Comment by tstromberg** [comment] 2018-12-04 18:42
Thanks for the report. This seems to be a dupe of #3409.

**Closed by tstromberg** 2018-12-04 18:42 UTC
