### ISSUE TITLE
Minikube tunnel command issue in windows 10 using powershell

### ISSUE THREAD

**Issue by thirdpartyusage** [kubernetes/minikube#10265] opened 2021-01-26 08:34 UTC
minikube start -p test

```
[test] minikube v1.17.0 on Microsoft Windows 10 Enterprise 10.0.19041 Build 19041
Using the docker driver based on user configuration
Starting control plane node test in cluster test
Creating docker container (CPUs=2, Memory=8100MB) ...
Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
Generating certificates and keys ...
Booting up control plane ...
Configuring RBAC rules ...
Verifying Kubernetes components...
Enabled addons: storage-provisioner, default-storageclass
Done! kubectl is now configured to use "test" cluster and "default" namespace by default
```
Then

```
minikube tunnel --profile='test' --alsologtostderr --v=2
I0126 13:48:19.951269 17256 out.go:229] Setting OutFile to fd 88 ...
I0126 13:48:19.955224 17256 out.go:276] TERM=,COLORTERM=, which probably does not support color
I0126 13:48:19.955224 17256 out.go:242] Setting ErrFile to fd 92...
I0126 13:48:19.955224 17256 out.go:276] TERM=,COLORTERM=, which probably does not support color
I0126 13:48:19.976229 17256 mustload.go:66] Loading cluster: test
I0126 13:48:20.009229 17256 cli_runner.go:111] Run: docker container inspect test --format={{.State.Status}}
I0126 13:48:20.531365 17256 host.go:66] Checking if "test" exists ...
I0126 13:48:20.538387 17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "8443/tcp") 0).HostPort}}'" test
I0126 13:48:21.010962 17256 api_server.go:146] Checking apiserver status ...
I0126 13:48:21.028960 17256 ssh_runner.go:149] Run: sudo pgrep -xnf kube-apiserver.minikube.
I0126 13:48:21.035959 17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" test
I0126 13:48:21.503667 17256 sshutil.go:48] new ssh client: &{IP:127.0.0.1 Port:49212 SSHKeyPath:C:\Users\XXXX.minikube\machines\test\id_rsa Username:docker}
I0126 13:48:21.680774 17256 ssh_runner.go:149] Run: sudo egrep ^[0-9]+:freezer: /proc/2030/cgroup
I0126 13:48:21.704782 17256 api_server.go:162] apiserver freezer: "7:freezer:/docker/0dec78edc03e209a629cbcbfef2a9b936402d957e20b0aba6e5f2327c14d426d/kubepods/burstable/pod55c89bcbdeb83c8e170424682dd9a951/1bb7d538a165b064917135ab9b4cc02a6984374f5cab1f04a6402ceea4eb0a98"
I0126 13:48:21.738417 17256 ssh_runner.go:149] Run: sudo cat /sys/fs/cgroup/freezer/docker/0dec78edc03e209a629cbcbfef2a9b936402d957e20b0aba6e5f2327c14d426d/kubepods/burstable/pod55c89bcbdeb83c8e170424682dd9a951/1bb7d538a165b064917135ab9b4cc02a6984374f5cab1f04a6402ceea4eb0a98/freezer.state
I0126 13:48:21.760466 17256 api_server.go:184] freezer state: "THAWED"
I0126 13:48:21.760466 17256 api_server.go:221] Checking apiserver healthz at https://127.0.0.1:49209/healthz ...
I0126 13:48:21.784511 17256 api_server.go:241] https://127.0.0.1:49209/healthz returned 200:
ok
I0126 13:48:21.784511 17256 tunnel.go:57] Checking for tunnels to cleanup...
I0126 13:48:21.791509 17256 kapi.go:59] client config for test: &rest.Config{Host:"https://127.0.0.1:49209", APIPath:"", ContentConfig:rest.ContentConfig{AcceptContentTypes:"", ContentType:"", GroupVersion:(*schema.GroupVersion)(nil), NegotiatedSerializer:runtime.NegotiatedSerializer(nil)}, Username:"", Password:"", BearerToken:"", BearerTokenFile:"", Impersonate:rest.ImpersonationConfig{UserName:"", Groups:[]string(nil), Extra:map[string][]string(nil)}, AuthProvider:, AuthConfigPersister:rest.AuthProviderConfigPersister(nil), ExecProvider:, TLSClientConfig:rest.sanitizedTLSClientConfig{Insecure:false, ServerName:"", CertFile:"C:\Users\XXXX\.minikube\profiles\test\client.crt", KeyFile:"C:\Users\XXXX\.minikube\profiles\test\client.key", CAFile:"C:\Users\XXXX\.minikube\ca.crt", CertData:[]uint8(nil), KeyData:[]uint8(nil), CAData:[]uint8(nil), NextProtos:[]string(nil)}, UserAgent:"", DisableCompression:false, Transport:http.RoundTripper(nil), WrapTransport:(transport.WrapperFunc)(0x146f4e0), QPS:0, Burst:0, RateLimiter:flowcontrol.RateLimiter(nil), Timeout:0, Dial:(func(context.Context, string, string) (net.Conn, error))(nil)}
I0126 13:48:21.856436 17256 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" test
```
**Tunnel not working. I updated the latest openssh also. **

ssh -V
OpenSSH_for_Windows_8.1p1, LibreSSL 2.9.2

PowerShell/Win32-OpenSSH#1693

kubernetes/minikube#9753

Referred above two tickets, but still no luck .

Please let me know what i need to add?

@medyagh

**Comment by priyawadhwa** [comment] 2021-01-26 19:28
Hey @thirdpartyusage thanks for opening this issue. Unfortunately, I'm not familiar with tunnel/Windows. 

@blueelvis, would you have any ideas here? Just asking since you were the author of #9753 and definitely know more about this than I do.

**Comment by creste** [comment] 2021-02-04 19:51
I'm also running into this problem using similar steps to reproduce.  First I start minikube:
```
minikube start --memory=8192m --cpus=8
* minikube v1.17.1 on Microsoft Windows 10 Pro 10.0.19042 Build 19042
* Automatically selected the docker driver
* Starting control plane node minikube in cluster minikube
* Creating docker container (CPUs=8, Memory=8192MB) ...
* Preparing Kubernetes v1.20.2 on Docker 20.10.2 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

Then I try to open a tunnel:

```
minikube tunnel --alsologtostderr --v=8
```

But minikube hangs at:

```
I0204 14:33:54.536194   29884 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
```

If I kill the minikube process then I see the docker log file at C:\Users\\%USER%\AppData\Local\Docker shows the minikube process abnormally closes several sockets:
```
[14:36:45.632][GoBackendProcess  ][Info   ] error copying: read tcp 127.0.0.1:32779->127.0.0.1:57271: wsarecv: An existing connection was forcibly closed by the remote host.
[14:36:45.632][GoBackendProcess  ][Info   ] error copying: read tcp 127.0.0.1:32776->127.0.0.1:57273: wsarecv: An existing connection was forcibly closed by the remote host.
[14:36:45.632][GoBackendProcess  ][Info   ] error copying: read tcp 127.0.0.1:32776->127.0.0.1:57272: wsarecv: An existing connection was forcibly closed by the remote host.
[14:36:45.634][GoBackendProcess  ][Info   ] error copying: readfrom tcp 127.0.0.1:32776->127.0.0.1:57272: write tcp 127.0.0.1:32776->127.0.0.1:57272: wsasend: An existing connection was forcibly closed by the remote host.
[14:36:45.634][GoBackendProcess  ][Info   ] error copying: readfrom tcp 127.0.0.1:32776->127.0.0.1:57273: write tcp 127.0.0.1:32776->127.0.0.1:57273: wsasend: An existing connection was forcibly closed by the remote host.
```

If I run `minikube tunnel ...` again the docker log file shows minikube makes the same requests to the docker daemon again:
```
[14:36:46.722][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:46.724][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.0233ms)\n
[14:36:46.793][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:46.794][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.9723ms)\n
[14:36:46.857][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:46.859][ApiProxy          ][Info   ] proxy << HEAD /_ping (2.971ms)\n
[14:36:46.874][ApiProxy          ][Info   ] proxy >> GET /v1.40/containers/minikube/json\n
[14:36:46.876][ApiProxy          ][Info   ] proxy << GET /v1.40/containers/minikube/json (2.9679ms)\n
[14:36:46.887][LoggingMessageHandler][Info   ] [cc706348] <Server start> POST http://unix/usage/cli
[14:36:46.887][LoggingMessageHandler][Info   ] [cc706348] <Server end> POST http://unix/usage/cli -> 200 OK (took 0ms)
[14:36:46.887][GoBackendProcess  ][Info   ] cli: POST /usage 200 \"Go-http-client/1.1\" \"\
[14:36:46.966][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:46.968][ApiProxy          ][Info   ] proxy << HEAD /_ping (2.0005ms)\n
[14:36:47.040][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.041][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.0002ms)\n
[14:36:47.100][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.102][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.0032ms)\n
[14:36:47.117][ApiProxy          ][Info   ] proxy >> GET /v1.40/containers/minikube/json\n
[14:36:47.119][ApiProxy          ][Info   ] proxy << GET /v1.40/containers/minikube/json (1.9879ms)\n
[14:36:47.133][LoggingMessageHandler][Info   ] [6a174ff9] <Server start> POST http://unix/usage/cli
[14:36:47.133][LoggingMessageHandler][Info   ] [6a174ff9] <Server end> POST http://unix/usage/cli -> 200 OK (took 0ms)
[14:36:47.133][GoBackendProcess  ][Info   ] cli: POST /usage 200 \"Go-http-client/1.1\" \"\
[14:36:47.213][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.214][ApiProxy          ][Info   ] proxy << HEAD /_ping (2.0017ms)\n
[14:36:47.296][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.298][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.9752ms)\n
[14:36:47.363][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.365][ApiProxy          ][Info   ] proxy << HEAD /_ping (1.9779ms)\n
[14:36:47.381][ApiProxy          ][Info   ] proxy >> GET /v1.40/containers/minikube/json\n
[14:36:47.383][ApiProxy          ][Info   ] proxy << GET /v1.40/containers/minikube/json (2.004ms)\n
[14:36:47.398][LoggingMessageHandler][Info   ] [7716ba20] <Server start> POST http://unix/usage/cli
[14:36:47.398][LoggingMessageHandler][Info   ] [7716ba20] <Server end> POST http://unix/usage/cli -> 200 OK (took 0ms)
[14:36:47.398][GoBackendProcess  ][Info   ] cli: POST /usage 200 \"Go-http-client/1.1\" \"\
[14:36:47.646][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.648][ApiProxy          ][Info   ] proxy << HEAD /_ping (2.0036ms)\n
[14:36:47.728][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.730][ApiProxy          ][Info   ] proxy << HEAD /_ping (2.0188ms)\n
[14:36:47.794][ApiProxy          ][Info   ] proxy >> HEAD /_ping\n
[14:36:47.796][ApiProxy          ][Info   ] proxy << HEAD /_ping (998.6Âµs)\n
[14:36:47.811][ApiProxy          ][Info   ] proxy >> GET /v1.40/containers/minikube/json\n
[14:36:47.813][ApiProxy          ][Info   ] proxy << GET /v1.40/containers/minikube/json (2.0177ms)\n
[14:36:47.824][LoggingMessageHandler][Info   ] [6c31f8c1] <Server start> POST http://unix/usage/cli
[14:36:47.824][LoggingMessageHandler][Info   ] [6c31f8c1] <Server end> POST http://unix/usage/cli -> 200 OK (took 0ms)
[14:36:47.824][GoBackendProcess  ][Info   ] cli: POST /usage 200 \"Go-http-client/1.1\" \"\
```
But minikube hangs here again:
```
I0204 14:36:47.589421   31608 cli_runner.go:111] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube
```

If I run the `docker container inspect ...` command manually then it works fine:
```
> docker container inspect -f "'{{(index (index .NetworkSettings.Ports \""22/tcp\"") 0).HostPort}}'" minikube
'32779'
```

So it looks like minikube is *not* waiting on the docker deamon.

I'm using go 1.15.7 if that helps:

```
>go version
go version go1.15.7 windows/amd64
```

**Comment by krishnadce** [comment] 2021-07-04 12:54
I'm also facing the same issue.

It hangs at 
`I0704 18:09:05.300669    9752 cli_runner.go:115] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube`

**Comment by rachelis19** [comment] 2021-09-26 13:16
I'm also having the same trouble.
using minikube on windows 10

trying to use minikube tunnel command and it hangs..... can`t run external services

**Comment by klaases** [comment] 2022-01-26 19:45
Hi @thirdpartyusage, please try using another terminal to take advantage of the tunnel, especially if using the Docker driver. The terminal that is running the tunnel itself will hang, as it is used to maintain the tunnel connection.

**Comment by klaases** [comment] 2022-02-09 20:04
Hi @thirdpartyusage – please see the suggestion above. Also, feel free to re-open the issue by commenting with `/reopen`. This issue will be closed as additional information was unavailable and some time has passed. 

Thank you for sharing your experience!

**Closed by klaases** 2022-02-09 20:04 UTC
Labels: kind/support, lifecycle/rotten, long-term-support
