### ISSUE TITLE
How to test kubernetes changes with minikube

### ISSUE THREAD

**Issue by kellabyte** [kubernetes/minikube#903] opened 2016-12-09 16:32 UTC
I want to learn about making changes to kubernetes itself. Can I use minikube for this? I read some of the documentation but I'm not clear how I would make code changes to kubernetes source code and then test them with minikube.

Any help would be greatly appreciated!

**Comment by r2d4** [comment] 2016-12-12 17:39
Right now there isn't a good way to develop kubernetes changes on minikube.  Minikube provides a stable single node cluster and allows you to switch between released kubernetes versions.  Its really meant for giving you a good platform to test your own applications locally.

There is a script in the main kubernetes repo that you can use to bring up a local multinode cluster with your kubernetes changes.  https://github.com/kubernetes/kubernetes/blob/master/hack/local-up-cluster.sh. Note, that script will only run on linux and requires an active docker daemon.

You might find some more direction in the [kubernetes-dev](https://kubernetes.slack.com/messages/kubernetes-dev/) slack room.

**Comment by dlorenc** [comment] 2016-12-19 19:37
Ref https://github.com/kubernetes/kubernetes/pull/38975

**Comment by MHBauer** [comment] 2017-05-17 02:37
This and #903 look like dups of each other.

**Comment by r2d4** [comment] 2017-05-17 04:00
Closing this as a dupe of #558, we'll track it there

**Closed by r2d4** 2017-05-17 04:00 UTC
Labels: kind/support

**Comment by MHBauer** [comment] 2017-06-16 19:34
Is building kubernetes from source ever going to be a supported workflow with minikube? If it is not  it would be good to explicitly say that it is out of scope and will never be covered.
