### ISSUE TITLE
docker: service command emits inaccessible URL with WSL2 backend (Windows Home)

### ISSUE THREAD

**Issue by AmitVishwash** [kubernetes/minikube#9023] opened 2020-08-18 18:41 UTC
1. I  have  one seleniumgrid.yaml and one service.yaml for exposing the service. I am able to create the pods and service but  I am not able to see the requested resource when i hit the url with the port no.

PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl create -f seleniumgrid.yaml
pod/selenium-grid-pod created
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS              RESTARTS   AGE
selenium-grid-pod   0/1     ContainerCreating   0          10s
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS              RESTARTS   AGE
selenium-grid-pod   0/1     ContainerCreating   0          21s
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS              RESTARTS   AGE
selenium-grid-pod   0/1     ContainerCreating   0          37s
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS              RESTARTS   AGE
selenium-grid-pod   0/1     ContainerCreating   0          54s
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS              RESTARTS   AGE
selenium-grid-pod   0/1     ContainerCreating   0          56s
PS C:\Users\amitv\Downloads\Documents\seleniumgriddemo> kubectl get pod
NAME                READY   STATUS    RESTARTS   AGE
selenium-grid-pod   1/1     Running   0          5m41s

2. When i am accessing the url  it says the site cant be reached. I have tried to use  minikube-windows-amd64.exe also but it didnt work.

PS C:\Users\amitv\Downloads\Programs> .\minikube-windows-amd64.exe service selenium-srv
* Starting tunnel for service selenium-srv.
|-----------|--------------|-------------|------------------------|
| NAMESPACE |     NAME     | TARGET PORT |          URL           |
|-----------|--------------|-------------|------------------------|
| default   | selenium-srv |             | http://127.0.0.1:62274 |
|-----------|--------------|-------------|------------------------|
* Opening service default/selenium-srv in default browser...
! Because you are using a Docker driver on windows, the terminal needs to be open to run it.

**Comment by AmitVishwash** [comment] 2020-08-18 20:16
@Medya Ghazizadeh

**Comment by AmitVishwash** [comment] 2020-08-18 20:16
@medyagh please have a look

**Comment by tstromberg** [comment] 2020-08-18 20:25
@AmitVishwash - if you open http://127.0.0.1:62274  in your web browser while this is output, what happens?

I suspect that we need to do some trickery with WSL2 port forwards, which seem to be required by home edition?

**Comment by AmitVishwash** [comment] 2020-08-18 20:28
@tstromberg  when i used this command .\minikube-windows-amd64.exe service selenium-srv.. I got this 

Starting tunnel for service selenium-srv.
|-----------|--------------|-------------|------------------------|
| NAMESPACE | NAME | TARGET PORT | URL |
|-----------|--------------|-------------|------------------------|
| default | selenium-srv | | http://127.0.0.1:62274 |

After this the tab got opened with this url automatically but it said the site cant be reached.

**Comment by AmitVishwash** [comment] 2020-08-18 20:33
I have the minikube version 
minikube version: v1.12.3
and  I have docker desktop for windows and the engine version is   19.03.12...Is this related to some version issue @tstromberg @medyagh

**Comment by tstromberg** [comment] 2020-08-18 20:52
I'm guessing that `minikube service` is not yet compatible with the `Docker` and `Windows Home`.

As an alternative I suggest using `kubectl port-forward` instead. For instance `kubectl port-forward service/hello-minikube 7080:8080`. Please let me know if that works any better.

**Comment by AmitVishwash** [comment] 2020-08-18 22:24
@tstromberg ,  the minikube has an internal ip address of 
Addresses:
  InternalIP:  172.17.0.3
  Hostname:    minikube

and i have a service with nodePort 30001.

So you want me to run   kubectl port-forward service/selenium-srv 30001:8080  ?. I have tried this but it gives me error: timed out waiting for the condition.

by doing this ->   minikube service selenium-srv --url
* Starting tunnel for service selenium-srv.
|-----------|--------------|-------------|------------------------|
| NAMESPACE |     NAME     | TARGET PORT |          URL           |
|-----------|--------------|-------------|------------------------|
| default   | selenium-srv |             | http://127.0.0.1:51867 |
|-----------|--------------|-------------|------------------------|

but in this case also it says site  cant be reached

**Comment by medyagh** [comment] 2020-09-30 23:54
@AmitVishwash I think this is duplicate of this https://github.com/kubernetes/minikube/issues/9030

lets track the response in one place

**Closed by medyagh** 2020-09-30 23:54 UTC
Labels: co/docker-driver, co/service, os/windows, triage/needs-information, triage/support
