### ISSUE TITLE
Exiting due to GUEST_PROVISION: 

### ISSUE THREAD

**Issue by arunnair555** [kubernetes/minikube#12915] opened 2021-11-10 02:37 UTC
**Steps to reproduce the issue:** 

😿  Failed to start docker container. Running "minikube delete" may fix it: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: provisioning: Temporary Error: error getting ip during provisioning: IPs output should only be one line, got 2 lines

**Run `minikube logs --file=logs.txt` and drag and drop the log file into this issue**

**Full output of failed command if not `minikube start`:**
<details>

</details>

**Comment by spowelljr** [comment] 2021-11-15 16:03
Hi @arunnair555, thanks for reporting your issue with minikube!

This is a duplicate of https://github.com/kubernetes/minikube/issues/8409. There are suggestions in the issue such as https://github.com/kubernetes/minikube/issues/8409#issuecomment-907269490 and https://github.com/kubernetes/minikube/issues/8409#issuecomment-650565683. Try those out and see if that fixes your issue. I'm going to close this issue since it's a duplicate of https://github.com/kubernetes/minikube/issues/8409, but feel free to respond to  that issue, thanks!

**Closed by spowelljr** 2021-11-15 16:03 UTC
Labels: kind/support
