### ISSUE TITLE
minikube profile list

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#4493] opened 2019-06-15 01:41 UTC
currently there is no way to see list of all created minikube profiles... it would be nice to have command for it.

currently 
`minikube profile list`

configs minikube to set the profile name as "list" which could be confusing.

we could change the current command to

```minikube profile set p1```
and  another command
```minikube profile list```

**Comment by djmgit** [comment] 2019-06-16 16:30
@medyagh I would like to work on this.
I was thinking that can we create a command like ```minikube list-profiles``` or simply ```minikube profiles```. This way we will not require to change the existing ```profile``` command.

**Comment by tstromberg** [comment] 2019-07-12 22:44
Dupe of #1716

**Closed by tstromberg** 2019-07-12 22:44 UTC
Labels: priority/important-longterm, triage/discuss
