### ISSUE TITLE
--extra-config seems to be ignored for existing clusters

### ISSUE THREAD

**Issue by AquoDev** [kubernetes/minikube#8979] opened 2020-08-12 07:31 UTC
_If there's missing data, please let me know and I'll update the issue._

Possible duplicate of https://github.com/kubernetes/minikube/issues/8242, but I open this issue to show everything I could gather.

**Environment:**
Debian 10.5, installed via netinst ISO inside a VirtualBox VM.
```console
root@minikube:~# uname -a
Linux minikube 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux

root@minikube:~# env # Some values have been removed as they're not relevant for this issue
SHELL=/bin/bash
PWD=/root
XDG_SESSION_TYPE=tty
HOME=/root
LANG=es_ES.UTF-8
TERM=xterm-256color
SHLVL=2
PATH=/usr/local/sbin:/usr/sbin:/sbin:/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
SSH_TTY=/dev/pts/1
_=/usr/bin/env

root@minikube:~# cat install_script.sh # How I installed everything
# Install Docker (latest version)
curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
apt-get update
apt-get install -y docker-ce docker-ce-cli containerd.io

# Install kubectl (latest version, no hypervisor)
curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
echo "deb https://apt.kubernetes.io/ kubernetes-xenial main" | tee -a /etc/apt/sources.list.d/kubernetes.list
apt-get update
apt-get install -y kubectl

# Install Minikube (latest version)
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
chmod +x minikube
cp minikube /usr/local/bin/
rm minikube
```

Docker, Minikube and kubectl.

```console
root@minikube:~# docker version
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:50 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:21 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
root@minikube:~# minikube version
minikube version: v1.12.2
commit: be7c19d391302656d27f1f213657d925c4e1cfc2-dirty
root@minikube:~# kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-15T16:58:53Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Steps to reproduce the issue:** 

Hi, I seem to hit this problem everytime I try the following steps from a clean Debian, Docker and Minikube install:

1.  Start Minikube with vm-driver=none and **kubeadm init --skip-phases=addon/kube-proxy** as described in [official docs](https://kubernetes.io/docs/reference/setup-tools/kubeadm/kubeadm-init/). This works as expected for the first time. Output is saved as `minikube-start-ok.txt`.

```console
root@minikube:~# minikube start --vm-driver=none --extra-config=kubeadm.skip-phases=addon/kube-proxy --alsologtostderr
```

2. Confirm that `kube-proxy` hasn't been created. This is also expected.

```console
root@minikube:~# kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE
kube-system   coredns-66bff467f8-24knd           0/1     Running            0          3m22s
kube-system   etcd-minikube                      1/1     Running            0          3m21s
kube-system   kube-apiserver-minikube            1/1     Running            0          3m21s
kube-system   kube-controller-manager-minikube   1/1     Running            0          3m21s
kube-system   kube-scheduler-minikube            1/1     Running            0          3m21s
kube-system   storage-provisioner                0/1     CrashLoopBackOff   3          3m28s
```

- Run `minikube logs` and save that output as `minikube-logs-ok.txt`.

```console
root@minikube:~# minikube logs
```

3. Stop Minikube.

```console
root@minikube:~# minikube stop
✋  Stopping node "minikube"  ...
🛑  1 nodes stopped.
```

4. Repeat step 1, but this time it doesn't work as expected, because `kube-proxy` is created. Output is saved as `minikube-start-failed.txt`.

```console
root@minikube:~# minikube start --vm-driver=none --extra-config=kubeadm.skip-phases=addon/kube-proxy --alsologtostderr
```

5. Repeat step 2. Output is not as expected, because `kube-proxy` shouldn't have been created, as expected in step 2.

```console
root@minikube:~# kubectl get pods -A
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-66bff467f8-24knd           1/1     Running   1          18m
kube-system   etcd-minikube                      1/1     Running   1          18m
kube-system   kube-apiserver-minikube            1/1     Running   1          18m
kube-system   kube-controller-manager-minikube   1/1     Running   1          18m
kube-system   kube-proxy-tbj29                   1/1     Running   0          2m22s
kube-system   kube-scheduler-minikube            1/1     Running   1          18m
kube-system   storage-provisioner                1/1     Running   8          19m
```

- Run `minikube logs` and save that output as `minikube-logs-failed.txt`.

```console
root@minikube:~# minikube logs
```

**More details:**

- Behaviour is the same from steps 3 to 5 after running `rm -rf ~/.minikube/cache`.
- Behaviour is the same from steps 1 to 5 after running `minikube delete`.
- It should behave **the same from steps 1 to 3 repeated**.

**Full output of failed command:** 

- No failed command, but unexpected behaviour.

**Full output of `minikube start` command used, if not already included:**

- [minikube-start-ok.txt](https://github.com/kubernetes/minikube/files/5061222/minikube-start-ok.txt)
- [minikube-start-failed.txt](https://github.com/kubernetes/minikube/files/5061220/minikube-start-failed.txt)

**Optional: Full output of `minikube logs` command:**

- [minikube-logs-ok.txt](https://github.com/kubernetes/minikube/files/5061221/minikube-logs-ok.txt)
- [minikube-logs-failed.txt](https://github.com/kubernetes/minikube/files/5061219/minikube-logs-failed.txt)

**Comment by priyawadhwa** [comment] 2020-08-12 19:05
Hey @AquoDev thanks for opening this issue and for being so thorough. This is a dupe of #8242; would you mind if we moved the conversation there so everything is available in once place?

If you could comment on that issue that would be really helpful, and I'll go ahead and close this issue. Thank you!

**Closed by priyawadhwa** 2020-08-12 19:05 UTC
Labels: kind/bug

**Comment by AquoDev** [comment] 2020-08-13 05:30
Yeah sure. that's fine!
