### ISSUE TITLE
Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

### ISSUE THREAD

**Issue by dr3x** [kubernetes/minikube#3854] opened 2019-03-11 20:14 UTC
Working through the steps in this:
https://medium.com/@JockDaRock/openfaas-on-minikube-serverless-on-kubernetes-for-windows-10-3c7c7d68f47f

https://medium.com/@JockDaRock/minikube-on-windows-10-with-hyper-v-6ef0f4dc158c

C:\WINDOWS\system32>minikube start --vm-driver hyperv --hyperv-virtual-switch "Primary Virtual Switch"
o   minikube v0.35.0 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing hyperv VM for "minikube" ...
!   Unable to start VM: start: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

C:\WINDOWS\system32>minikube logs
!   command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

...>systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.17134 N/A Build 17134

**Comment by dr3x** [comment] 2019-03-11 23:27
Update:  switched from hyper-v to virtualbox and now minikube is running so I'm good for now but there appears to be an issue with hyper-v

**Comment by tstromberg** [comment] 2019-03-13 20:32
Thanks for the update! The HyperV issue appears to be a dupe of #3802

**Closed by tstromberg** 2019-03-13 20:32 UTC

**Comment by dr3x** [comment] 2019-03-13 22:33
Will do if I ever switch back to hyper-v

**Comment by lmurali89** [comment] 2020-02-27 06:21
@tstromberg : I did it instead of @dr3x  please help me to resolve the issue

C:\WINDOWS\system32>minikube start --vm-driver=hyperv --alsologtostderr -v=9
W0227 11:49:42.665216   10328 root.go:242] Error reading config file at C:\Users\Hp\.minikube\config\config.json: open C:\Users\Hp\.minikube\config\config.json: The system cannot find the file specified.
I0227 11:49:42.679220   10328 notify.go:125] Checking for updates...
I0227 11:49:42.833246   10328 start.go:249] hostinfo: {"hostname":"DESKTOP-05LIJNS","uptime":8266,"bootTime":1582776116,"procs":148,"os":"windows","platform":"Microsoft Windows 10 Pro","platformFamily":"Standalone Workstation","platformVersion":"10.0.18363 Build 18363","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"30874692-dd8a-418e-bc03-ff2aaff1ceb9"}
W0227 11:49:42.833246   10328 start.go:257] gopshost.Virtualization returned error: not implemented yet
* minikube v1.7.3 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
I0227 11:49:42.836220   10328 driver.go:211] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on user configuration
I0227 11:49:44.879309   10328 start.go:296] selected driver: hyperv
I0227 11:49:44.880196   10328 start.go:472] validating driver "hyperv" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.7.3.iso Memory:2000 CPUs:2 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch:MiniKube Switch HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false Downloader:<nil> DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.17.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false} Nodes:[{Name:minikube IP: Port:8443 KubernetesVersion:v1.17.3 ControlPlane:true Worker:true}] Addons:map[]}
I0227 11:49:44.880196   10328 start.go:478] status for hyperv: {Installed:false Healthy:false Error:C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:
 Fix:Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All' Doc:https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/}

! 'hyperv' driver reported an issue: C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-All -Online failed:

* Suggestion: Start PowerShell as Administrator, and run: 'Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V -All'
* Documentation: https://minikube.sigs.k8s.io/docs/reference/drivers/hyperv/

X hyperv does not appear to be installed, but is specified by an existing profile. Please run 'minikube delete' or install hyperv
