### ISSUE TITLE
Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

### ISSUE THREAD

**Issue by prakasa-tkpd** [kubernetes/minikube#4294] opened 2019-05-20 09:00 UTC
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:
➜  ~ minikube start
😄  minikube v1.0.1 on darwin (amd64)
🤹  Downloading Kubernetes v1.14.1 images in the background ...
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Re-using the currently running virtualbox VM for "minikube" ...
⌛  Waiting for SSH access ...
📶  "minikube" IP address is 192.168.99.100
🐳  Configuring Docker as the container runtime ...
🐳  Version of container runtime is 17.06.0-ce
⌛  Waiting for image downloads to complete ...
✨  Preparing Kubernetes environment ...
🚜  Pulling images required by Kubernetes v1.14.1 ...
🔄  Relaunching Kubernetes v1.14.1 using kubeadm ...
⌛  Waiting for pods: apiserver proxy
💣  Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The output of the `minikube logs` command**:

**The operating system version**:
macOS Mojave darwin (amd64)

**Comment by tstromberg** [comment] 2019-05-22 03:23
Thank you for sharing your experience! 

This issue appears to be a duplicate of #3843, so I will close this in preference to that issue so that we may centralize  the information around it. If you feel that this is not in fact a duplicate, please feel free to re-open this issue.

This should no longer be an issue with the newly released minikube v1.1.0 - I highly recommend upgrading to it.

**Closed** 2019-05-22 03:23 UTC
Labels: co/kube-proxy, triage/duplicate
