### ISSUE TITLE
hyperV exception windows datacenter

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8245] opened 2020-05-21 23:03 UTC
on that windows there is no virtualswtich by default

![remmina_mini-test-3_157 55 202 113_2020516-53418 985060](https://user-images.githubusercontent.com/4564227/82614417-a5e94680-9b7c-11ea-8bba-9d2354262e12.png)

**Comment by tstromberg** [comment] 2020-05-26 17:21
Duplicate of #2954

**Comment by sharifelgamal** [comment] 2020-07-28 21:20
Turns out this is a duplicate of #2954

**Closed by sharifelgamal** 2020-07-28 21:20 UTC
Labels: co/hyperv, help wanted, kind/bug
