### ISSUE TITLE
Error getting host status: state: machine does not exist 

### ISSUE THREAD

**Issue by tidpunrana** [kubernetes/minikube#3945] opened 2019-03-24 07:33 UTC

**Comment by SYM0920** [comment] 2019-03-25 06:44
getting the same error


😄  minikube v0.35.0 on linux (amd64)
🔥  Creating virtualbox VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
💣  Unable to start VM: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine


😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by sharifelgamal** [comment] 2019-04-04 19:23
Closing as dupe of #3864

**Closed by sharifelgamal** 2019-04-04 19:23 UTC
Labels: triage/duplicate
