### ISSUE TITLE
Exiting due to GUEST_PROVISION

### ISSUE THREAD

**Issue by danilsmirnov** [kubernetes/minikube#12825] opened 2021-10-30 12:50 UTC
Hi guys! Here's my comands running on MacBook Pro (Retina, 13-inch, Late 2013)
```
minikube start               
😄  minikube v1.23.2 on Darwin 11.4
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet16 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

🔄  Restarting existing virtualbox VM for "minikube" ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet17 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp


❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet17 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp
```
same result after `minikube delete`
logs are attached
l
[logs.txt](https://github.com/kubernetes/minikube/files/7446551/logs.txt)

**Comment by spowelljr** [comment] 2021-11-01 17:24
Hi @danilsmirnov, thanks  for reporting your issue with minikube!

I believe this is a duplicate of https://github.com/kubernetes/minikube/issues/12765.

**Comment by spowelljr** [comment] 2021-11-03 18:58
This is fixed by https://github.com/kubernetes/minikube/issues/12765 which will be included in the v1.24.0 release coming today or tomorrow, I'm going to close this issue.

**Closed by spowelljr** 2021-11-03 18:58 UTC
Labels: kind/support, co/virtualbox, triage/duplicate

**Comment by danilsmirnov** [comment] 2021-11-23 14:45
thx❤️
