### ISSUE TITLE
Minikube (vm-driver=none) starts with warning: Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory

### ISSUE THREAD

**Issue by athrane** [kubernetes/minikube#4028] opened 2019-03-31 14:05 UTC
Hi! 

I tried to install minikube 1.0.0 with the none-vm-driver in a VagrantBox with CentOS7.6 and the latest version of Docker CE. The installation succeeds with a warning.

I installed minikube using the the commands from the page: https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md:

```
curl -Lo minikube \
  https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
  && sudo install minikube /usr/local/bin/

kv=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
curl -Lo kubectl \
  https://storage.googleapis.com/kubernetes-release/release/$kv/bin/linux/amd64/kubectl \
  && sudo install kubectl /usr/local/bin/

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
export KUBECONFIG=$HOME/.kube/config

mkdir -p $HOME/.kube $HOME/.minikube
touch $KUBECONFIG

sudo -E minikube start --vm-driver=none
```

```
[vagrant@localhost ~]$ curl -Lo minikube \
>   https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 \
>   && sudo install minikube /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38.2M  100 38.2M    0     0  3039k      0  0:00:12  0:00:12 --:--:-- 2898k
[vagrant@localhost ~]$ kv=$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)
[vagrant@localhost ~]$ curl -Lo kubectl \
>   https://storage.googleapis.com/kubernetes-release/release/$kv/bin/linux/amd64/kubectl \
>   && sudo install kubectl /usr/local/bin/
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 41.1M  100 41.1M    0     0  2705k      0  0:00:15  0:00:15 --:--:-- 2658k
[vagrant@localhost ~]$ export MINIKUBE_WANTUPDATENOTIFICATION=false
[vagrant@localhost ~]$ export MINIKUBE_WANTREPORTERRORPROMPT=false
[vagrant@localhost ~]$ export MINIKUBE_HOME=$HOME
[vagrant@localhost ~]$ export CHANGE_MINIKUBE_NONE_USER=true
[vagrant@localhost ~]$ export KUBECONFIG=$HOME/.kube/config
[vagrant@localhost ~]$ mkdir -p $HOME/.kube $HOME/.minikube
[vagrant@localhost ~]$ touch $KUBECONFIG
[vagrant@localhost ~]$ sudo -E minikube start --vm-driver=none
sudo: minikube: command not found
[vagrant@localhost ~]$ sudo -E /usr/local/bin/minikube start --vm-driver=none
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
2019/03/31 19:10:53 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/31 19:10:53 No matching credentials were found, falling back on anonymous
-   "minikube" IP address is 10.0.2.15
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.09.4
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
@   Downloading kubelet v1.14.0
@   Downloading kubeadm v1.14.0
-   Pulling images required by Kubernetes v1.14.0 ...
-   Launching Kubernetes v1.14.0 using kubeadm ...
:   Waiting for pods: apiserver proxy etcd scheduler controller dns
-   Configuring cluster permissions ...
-   Verifying component health .....
>   Configuring local host environment ...

!   The 'none' driver provides limited isolation and may reduce system security and reliability.
!   For more information, see:
-   https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

+   kubectl is now configured to use "minikube"
i   For best results, install kubectl: https://kubernetes.io/docs/tasks/tools/install-kubectl/
=   Done! Thank you for using minikube!
	
```

The used OS is CentOS 7.6 in  a Vagrant box.
Docker version info:
```
Client:
 Version:           18.09.4
 API version:       1.39
 Go version:        go1.10.8
 Git commit:        d14af54266
 Built:             Wed Mar 27 18:34:51 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          18.09.4
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.8
  Git commit:       d14af54
  Built:            Wed Mar 27 18:04:46 2019
  OS/Arch:          linux/amd64
  Experimental:     false

```

**Comment by athrane** [comment] 2019-03-31 18:35
Created prematurely.

**Comment by athrane** [comment] 2019-03-31 20:08
:-)

**Comment by toprch** [comment] 2019-04-01 15:01
This also happens when using alternative runtimes, in my case with cri-o given as `--container-runtime` start parameter.

**Comment by afbjorklund** [comment] 2019-04-01 18:44
Duplicate of #4007, installation looks OK

**Closed by afbjorklund** 2019-04-01 18:44 UTC
