### ISSUE TITLE
Minikube hangs at "minikube addons enable ingress" steps

### ISSUE THREAD

**Issue by arjunsreepad** [kubernetes/minikube#11591] opened 2021-06-07 06:40 UTC
When I run 

> minikube addons enable ingress

system hangs and no response

**Comment by soluchok** [comment] 2021-06-07 13:18
I have the same problem, seems like it is related to the latest OS kernel.
 `Linux desktop 5.10.36-2-MANJARO`  - does not work.

**Comment by ishanjain28** [comment] 2021-06-09 17:02
Hey @arjunsreepad Does the system hang or is it the minikube process that appears to be stuck?

**Comment by spowelljr** [comment] 2021-06-09 20:00
Hi @arjunsreepad, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!

**Closed by spowelljr** 2021-06-09 20:00 UTC
Labels: addon/ingress, kind/support
