### ISSUE TITLE
DNS is broken in Minikube 0.12.1

### ISSUE THREAD

**Issue by jezell** [kubernetes/minikube#781] opened 2016-10-30 09:07 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.12.1

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **Docker version** (e.g. `docker -v`): 1.12.1
- **Install tools**:
- **Others**:

**What happened**:

Updated to 0.12.1 release, DNS fails to lookup hosts like github.com, google.com.

**What you expected to happen**:

DNS to work.

**How to reproduce it** (as minimally and precisely as possible):

Upgrade to 0.12.1

**Anything else do we need to know**:

Downgrading to 0.12.0 fixes problem.

Tried kube version 1.4.0 / 1.4.3 on 0.12.1, neither worked. Both work for me on 0.12.0.

**Comment by r2d4** [comment] 2016-10-30 17:48
The change in 0.12 -> 0.12.1 was that we are now running kube-dns as an addon rather than  vendoring in the code and running it as a goroutine.  What this means is that you'll have to wait for the pods to be ready before DNS works.  This usually is pretty quick but can take a long time if you're on a bad connection.  You can check the status of the rc to make sure kube-dns is up.

````
-> kubectl get rc --namespace=kube-system
NAME                   DESIRED   CURRENT   READY     AGE
kube-dns-v20           1         1         1         <invalid>
kubernetes-dashboard   1         1         1         <invalid>
```

One way you can test if DNS is working

Create a busybox pod
```
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
```

Wait for it to be ready
```
-> kubectl get po
NAME      READY     STATUS    RESTARTS   AGE
busybox   1/1       Running   0          <invalid>
```

Then run nslookup commands from inside the pod
```
-> kubectl exec busybox -- nslookup kubernetes.default
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      kubernetes.default
Address 1: 10.0.0.1 kubernetes.default.svc.cluster.local
[~]
-> kubectl exec busybox -- nslookup google.com
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:4005:801::200e nuq04s29-in-x0e.1e100.net
Address 2: 216.58.194.174 sfo07s13-in-f14.1e100.net
```

If you're still having trouble, please post the logs of the kube-dns pods and that can help us debug.

**Comment by dlorenc** [comment] 2016-10-30 17:55
I think that might be unrelated. From the initial report @jezell is having trouble resolving things like google.com, which should work before the DNS pod starts.

**Comment by r2d4** [comment] 2016-10-30 18:01
Maybe I misunderstood - although I was able to resolve google.com in the last command 

```
-> kubectl exec busybox -- nslookup google.com
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      google.com
Address 1: 2607:f8b0:4005:801::200e nuq04s29-in-x0e.1e100.net
Address 2: 216.58.194.174 sfo07s13-in-f14.1e100.net
```

as well as in the VM alone

```
docker@minikube:~$ nslookup google.com
Server:    192.168.122.1
Address 1: 192.168.122.1

Name:      google.com
Address 1: 216.58.194.174 sfo07s13-in-f14.1e100.net
Address 2: 2607:f8b0:4005:807::200e sfo07s16-in-x0e.1e100.net

```

**Comment by jezell** [comment] 2016-10-31 18:26
I did capture the logs from kube-dns and check that the pod was running. Didn't see anything obviously wrong in there, but not sure what to expect in those logs. Here's it is:

```
$ kubectl get pods --namespace=kube-system
NAME                          READY     STATUS    RESTARTS   AGE
kube-addon-manager-minikube   1/1       Running   2          6d
kube-dns-v20-t0j9d            3/3       Running   0          23m
kubernetes-dashboard-u518v    1/1       Running   10         31d
```

```
$ kubectl logs kube-dns-v20-t0j9d kubedns --namespace=kube-system
I1030 08:26:34.647842       1 server.go:94] Using https://10.0.0.1:443 for kubernetes master, kubernetes API: <nil>
I1030 08:26:34.648874       1 server.go:99] v1.5.0-alpha.0.1651+7dcae5edd84f06-dirty
I1030 08:26:34.648923       1 server.go:101] FLAG: --alsologtostderr="false"
I1030 08:26:34.648963       1 server.go:101] FLAG: --dns-port="10053"
I1030 08:26:34.648975       1 server.go:101] FLAG: --domain="cluster.local."
I1030 08:26:34.648988       1 server.go:101] FLAG: --federations=""
I1030 08:26:34.648994       1 server.go:101] FLAG: --healthz-port="8081"
I1030 08:26:34.649015       1 server.go:101] FLAG: --kube-master-url=""
I1030 08:26:34.649022       1 server.go:101] FLAG: --kubecfg-file=""
I1030 08:26:34.649033       1 server.go:101] FLAG: --log-backtrace-at=":0"
I1030 08:26:34.649068       1 server.go:101] FLAG: --log-dir=""
I1030 08:26:34.649083       1 server.go:101] FLAG: --log-flush-frequency="5s"
I1030 08:26:34.649115       1 server.go:101] FLAG: --logtostderr="true"
I1030 08:26:34.649123       1 server.go:101] FLAG: --stderrthreshold="2"
I1030 08:26:34.649128       1 server.go:101] FLAG: --v="0"
I1030 08:26:34.649133       1 server.go:101] FLAG: --version="false"
I1030 08:26:34.649139       1 server.go:101] FLAG: --vmodule=""
I1030 08:26:34.650453       1 server.go:138] Starting SkyDNS server. Listening on port:10053
I1030 08:26:34.650603       1 server.go:145] skydns: metrics enabled on : /metrics:
I1030 08:26:34.650682       1 dns.go:166] Waiting for service: default/kubernetes
I1030 08:26:34.650834       1 logs.go:41] skydns: ready for queries on cluster.local. for tcp://0.0.0.0:10053 [rcache 0]
I1030 08:26:34.650858       1 logs.go:41] skydns: ready for queries on cluster.local. for udp://0.0.0.0:10053 [rcache 0]
I1030 08:26:34.721585       1 server.go:107] Setting up Healthz Handler(/readiness, /cache) on port :8081
W1030 08:31:10.760194       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 2042944 (2047042)
W1030 08:46:28.813965       1 reflector.go:330] pkg/dns/dns.go:155: watch of *api.Service ended with: too old resource version: 2047043 (2048211)
```

**Comment by r2d4** [comment] 2016-11-01 17:49
It could possibly be related to these issues if you're using DnsPolicy:ClusterFirst

https://github.com/kubernetes/kubernetes/issues/17406
https://github.com/kubernetes/kubernetes/issues/35761

I will do some more digging

**Comment by brandon-bethke-neudesic** [comment] 2016-11-01 21:36
For what it's worth, I believe I am also experiencing this problem when running v0.12.2

root@www-8d4st:/usr/src/app# curl http://www.google.com
curl: (6) Could not resolve host: www.google.com

**Comment by grobie** [comment] 2016-11-01 22:52
I also ran into this issue. I can't reach the clusterIP of the DNS service from any pod, e.g. I can't ping `10.0.0.10` but have no problems reaching the kube-dns pod IP (`10.0.2.15` in my case).

I stopped minikube, deleted the virtualbox VM and started from scratch. This solved the issue.

**Comment by brandon-bethke-neudesic** [comment] 2016-11-02 16:14
I can confirm that re-creating the vm solved the issue. However, re-creating the vm is an expensive operation for us and not having to do this is preferred.

**Comment by wstrange** [comment] 2016-11-03 15:37
I believe I also saw this behaviour on 0.12.2 , but cant repro it right now. I think it happens after a stop / start.  Possibly the dns pod does not resume?

**Comment by r2d4** [comment] 2016-11-03 17:57
This is pretty unfortunate, but because of changing the DNS implementation between 0.12.0 and 0.12.1, you will need to recreate the VM.  We'll add something to the release notes about this and continue to look for the root cause.

**Comment by yissachar** [comment] 2016-11-08 17:45
I just hit this as well, and can confirm that recreating the VM fixed the issue. Really annoying to suddenly have things stop working with no indication of why, and also annoying to recreate the VM.

**Comment by r2d4** [comment] 2016-11-10 19:09
We're closing this, as recreating the VM fixes this issue. 

However, we're tracking a new, more general issue to add tests to make sure that minikube can be upgraded in place at #816

**Closed by r2d4** 2016-11-10 19:09 UTC
Labels: kind/bug
