### ISSUE TITLE
docker driver: windows does not support privlileged

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7954] opened 2020-04-30 23:45 UTC
on a fresh windows 2019 in azure, 
minikube start failed with hyperv error but it failed over to docker
but docker had this error:
![Screen Shot 2020-04-30 at 4 41 39 PM](https://user-images.githubusercontent.com/4564227/80769419-f7645f80-8b01-11ea-9314-f2660b9f3a5d.png)

**Comment by medyagh** [comment] 2020-04-30 23:56
the source of the problem is, the docker is installed by default with windows containers

```
PS C:\Users\jenkins> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 4
 Server Version: 19.03.5
 Storage Driver: windowsfilter
  Windows:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: process
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows Server 2019 Datacenter Version 1809 (OS Build 17763.1158)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 32GiB
 Name: mini-test-2
 ID: DGCI:WUR4:ID6U:GVAE:32OC:RIKO:UBFC:S7Q2:P76J:OXQZ:CCLG:QTRH
 Docker Root Dir: C:\ProgramData\docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

````

**Comment by medyagh** [comment] 2020-05-01 00:01
after switching to linux containers, I get 
```
PS C:\Users\jenkins> docker info
Client:
 Debug Mode: false
 Plugins:
  cluster: Manage Docker clusters (Docker Inc., v1.2.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.92GiB
 Name: docker-desktop
 ID: RUL5:3H7C:MT3O:QXKT:Y3D5:3G3A:JQFW:OTUD:JZ64:MVPQ:RH2J:RU3H
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 40
  Goroutines: 56
  System Time: 2020-05-01T00:00:15.497596456Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

PS C:\Users\jenkins> docker run hello-world
Unable to find image 'hello-world:latest' locally
latest: Pulling from library/hello-world
0e03bdcc26d7: Pull complete
Digest: sha256:8e3114318a995a1ee497790535e7b88365222a21771ae7e53687ad76563e8e76
Status: Downloaded newer image for hello-world:latest

```

**Comment by medyagh** [comment] 2020-05-01 00:02
should be easy to detect by os.type

**Comment by afbjorklund** [comment] 2020-05-01 07:16
Similar to #7352 and #7576 ?

**Comment by tstromberg** [comment] 2020-05-01 16:29
This issue appears to be a duplicate of #7352, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-01 16:29 UTC
Labels: co/docker-driver, needs-solution-message, os/windows, priority/important-soon
