### ISSUE TITLE
minikube is not working

### ISSUE THREAD

**Issue by norozmayar** [kubernetes/minikube#4901] opened 2019-07-28 13:33 UTC

**Comment by sharifelgamal** [comment] 2019-07-30 18:14
Could you provide the following details so we can better help with your issue?

**The exact command to reproduce the issue**:


**The full output of the command that failed**:


**The output of the `minikube logs` command**:


**The operating system version**:

**Comment by norozmayar** [comment] 2019-08-04 11:05
norozmayar@mcb:~$ minikube start
😄  minikube v1.2.0 on linux (amd64)
💣  Unable to load config: open /home/norozmayar/.minikube/profiles/minikube/config.json: permission denied
norozmayar@mcb:~$ sudo minikube start
[sudo] password for norozmayar: 
😄  minikube v1.2.0 on linux (amd64)
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0804 15:55:31.902729    3164 start.go:559] StartHost: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-generic.\n\n\t You will not be able to start VMs until this problem is fixed.\n5.2.18_Ubuntur123745". Please upgrade at https://www.virtualbox.org

💣  Unable to start VM
❌  Error:         [VBOX_DEVICE_MISSING] create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "WARNING: The character device /dev/vboxdrv does not exist.\n\t Please install the virtualbox-dkms package and the appropriate\n\t headers, most likely linux-headers-generic.\n\n\t You will not be able to start VMs until this problem is fixed.\n5.2.18_Ubuntur123745". Please upgrade at https://www.virtualbox.org
💡  Advice:        Run 'sudo modprobe vboxdrv' and reinstall VirtualBox if it fails.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3974

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new
norozmayar@mcb:~$

**Comment by norozmayar** [comment] 2019-08-04 11:27
updated virtual box, now getting this error.



norozmayar@mcb:~$ sudo minikube start
[sudo] password for norozmayar: 
😄  minikube v1.2.0 on linux (amd64)
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.
🔥  Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0804 16:23:06.580080   18404 start.go:559] StartHost: create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.366958 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))

💣  Unable to start VM
❌  Error:         [VBOX_VERR_VMX_NO_VMX] create: creating: Unable to start the VM: /usr/bin/VBoxManage startvm minikube --type headless failed:
VBoxManage: error: VT-x is not available (VERR_VMX_NO_VMX)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:00.366958 Power up failed (vrc=VERR_VMX_NO_VMX, rc=NS_ERROR_FAILURE (0X80004005))
💡  Advice:        Please check your BIOS, and ensure that you are running without HyperV or other nested virtualization that may interfere
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1994

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new
norozmayar@mcb:~$

**Comment by medyagh** [comment] 2019-08-14 16:27
@norozmayar I am curious are you running inside a VM ? And if not have you tried the advice that minikube have provided?

**Comment by tstromberg** [comment] 2019-08-15 18:25
Hey @norozmayar - Do you mind trying with minikube v1.3.1 without sudo and sharing the full output?

If that fails, I think you are going to have to enable virtualization in your BIOS.

**Comment by tstromberg** [comment] 2019-08-29 18:39
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Closed by tstromberg** 2019-08-29 18:39 UTC
Labels: priority/awaiting-more-evidence, triage/needs-information
