### ISSUE TITLE
 Error downloading checksum file: net/http: TLS handshake timeout

### ISSUE THREAD

**Issue by billlih** [kubernetes/minikube#5183] opened 2019-08-23 05:46 UTC
**The exact command to reproduce the issue**:  minikube start

**The full output of the command that failed**:<details>

* minikube v1.3.1 on Ubuntu 14.04
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
* Downloading VM boot image ...
* 
X Failed to cache ISO
* Error: [DOWNLOAD_IO_TIMEOUT] https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso: invalid checksum: Error downloading checksum file: Get https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso.sha256: net/http: TLS handshake timeout
* Suggestion: A firewall is likely blocking minikube from reaching the internet. You may need to configure minikube to use a proxy.
* Documentation: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
* Related issues:
  - https://github.com/kubernetes/minikube/issues/3846
* 
* If the above advice does not help, please let us know: 
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
VMware® Workstation 12 Pro --- Ubuntu14.04

**Comment by billlih** [comment] 2019-08-23 05:59
https://storage.googleapis.com/minikube/iso/minikube-v1.3.0.iso  

I can use my browser to download this file to my PC .

**Comment by tstromberg** [comment] 2019-08-24 17:35
It appears that your Ubuntu machine does not have full access to the internet. Are you running minikube from China by any chance?

**Comment by tstromberg** [comment] 2019-08-24 17:38
This issue appears to be a duplicate of #5182, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-08-24 17:38 UTC
Labels: cause/firewall-or-proxy, triage/needs-information, triage/support
