### ISSUE TITLE
minikube 

### ISSUE THREAD

**Issue by srehanpk** [kubernetes/minikube#5042] opened 2019-08-11 14:31 UTC
**minikube start**:

**The full output of the command that failed**:<😄  minikube v1.3.0 on Ubuntu 18.04
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0811 19:18:49.615441   19748 start.go:723] StartHost: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/srahmed/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/srahmed/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/srahmed/.minikube/machines/minikube/boot2docker.iso"

💣  Unable to start VM: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/srahmed/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/srahmed/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 191 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/srahmed/.minikube/machines/minikube/boot2docker.iso"

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Linux hp 5.0.0-23-generic #24~18.04.1-Ubuntu SMP Mon Jul 29 16:12:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tstromberg** [comment] 2019-08-13 17:03
This appears to be a dupe of #4992 

Please do the following:

1. Run `minikube delete`
2. Run `rm -Rf ~/.minikube/cache/iso` (or the Windows equivalent)
3. Upgrade to minikube v1.3.1 - which fixes the download issue

Thank you for the bug report!

**Closed by tstromberg** 2019-08-13 17:03 UTC
