### ISSUE TITLE
minikube start (v1.20.0) doesn't work on BigSur 11.3.1

### ISSUE THREAD

**Issue by nickgryg** [kubernetes/minikube#11417] opened 2021-05-15 00:43 UTC
~ (:|✔) minikube version
minikube version: v1.20.0
commit: c61663e942ec43b20e8e70839dcca52e44cd85ae

**Steps to reproduce the issue:** 

1. minikube config set driver virtualbox
2. minikube start

**Full output of `minikube logs` command:**
<details>

[minikube logs](https://github.com/kubernetes/minikube/files/6481648/full.log)

[lastStart.txt](https://github.com/kubernetes/minikube/files/6481651/lastStart.txt)
</details>

**Full output of failed command:**
```
 ~ (:|✔) minikube start
😄  minikube v1.20.0 on Darwin 11.3.1
✨  Using the virtualbox driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.6 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...\ E0514 16:08:25.153302   46565 start.go:132] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: timed out waiting for the condition

🔎  Verifying Kubernetes components...
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Unauthorized]
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.20.2

```

**Comment by medyagh** [comment] 2021-05-15 01:53
@nickgryg thanks for providing the full logs. I am curious why you chose virtual box over hyperkit or docker driver on MacOS?

And do you use it in a corp network?

**Comment by nickgryg** [comment] 2021-05-15 02:10
Actually, I got the same error both on hyperkit and virtualbox. I just have more experience with virtualbox. That's why I prefer to use it.
No, it's my personal laptop and just a home internet connection without any firewalls, proxies etc.

**Comment by walker-tom** [comment] 2021-06-22 15:49
I encountered the exact same problem with minikube v1.21.0 on Catalina 10.15.7 but with the docker driver.

Running `minikube delete --all --purge`, as suggested in #8844, and removing all existing docker images and containers solved this problem for me.

**Comment by spowelljr** [comment] 2021-09-08 20:03
This issue is a duplicate of #8765, since #8765 has been around longer and has more traffic I'm going to close this issue. Please feel free to follow along and contribute to #8765, thanks!

**Closed by spowelljr** 2021-09-08 20:03 UTC
Labels: kind/support, os/macos, co/virtualbox, long-term-support
