### ISSUE TITLE
Error restarting cluster: waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by youzeliang** [kubernetes/minikube#11830] opened 2021-06-30 06:09 UTC
I type it "minikube start --image-repository='registry.cn-hangzhou.aliyuncs.com/google_containers'" in terminal .
But it always time out 
I try to use different net

**Comment by spowelljr** [comment] 2021-06-30 18:47
Hi @youzeliang, thanks for reporting your issue!

This is a duplicate of #10544, in order to keep all discussion of this issue centralized I'm going to close this issue.

Please follow along with #10544 and contribute any findings there, thanks for your understanding!

**Closed by spowelljr** 2021-06-30 18:47 UTC

**Comment by youzeliang** [comment] 2021-07-01 01:33
ok，thank you
