### ISSUE TITLE
Introduce a minikube create command

### ISSUE THREAD

**Issue by rodcloutier** [kubernetes/minikube#775] opened 2016-10-29 03:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Feature requests

I think there is an opportunity to create a separation of concerns by introducing a `create` command in addition to the `start` command.

The expectation would then be to create a minikube machine/cluster and then start it. I have had report of people being a little confused with the implicit virtual machine creation on start as it is different from similar experience on docker-machine.

From my understanding, most parameters are only necessary on the first start, when the vm is created. Furthermore, the `stop` command specifies that all the file are left intact and the cluster can be restarted with a `start` command.

Finally, a `create` command would would be symmetrical with the `delete` command as the `start` is with the `stop`. The workflow would then be:
1. create
2. start
3. stop
4. delete

**Comment by r2d4** [comment] 2016-11-03 17:39
Dupe of #364

**Closed by r2d4** 2016-11-03 17:39 UTC
Labels: kind/feature
