### ISSUE TITLE
Minikube install documentation is misleading about prerequisites

### ISSUE THREAD

**Issue by redborian** [kubernetes/minikube#8137] opened 2020-05-13 19:50 UTC
https://kubernetes.io/docs/tasks/tools/install-minikube/
![image](https://user-images.githubusercontent.com/6260897/81858222-36d67700-9518-11ea-9ad4-c17a1e9a3794.png)
It seems that I need a hypervisor installed
This documentation doesn’t mention that this isn’t needed if I have docker installed.

**Comment by afbjorklund** [comment] 2020-05-13 19:56
That documentation is probably a bit outdated, the docker/podman driver part is "under construction"

**Comment by medyagh** [comment] 2020-05-13 19:57
@tstromberg has an issue for this milestone to conslidate the docs with kubernetes

**Comment by afbjorklund** [comment] 2020-05-13 19:57
We made a partial update (it's external to minikube), but more work needs to be done.

**Comment by sharifelgamal** [comment] 2020-06-24 18:15
I'm going to mark this as a duplicate of #5686 since that encompasses updating this documentation. 

In the meantime, feel free to use our documentation on [getting started](https://minikube.sigs.k8s.io/docs/start/)

**Closed by sharifelgamal** 2020-06-24 18:15 UTC
Labels: kind/documentation, priority/important-soon
