### ISSUE TITLE
vm-driver hyperv ignores setting for virtual hard disk location

### ISSUE THREAD

**Issue by Flyingmana** [kubernetes/minikube#5717] opened 2019-10-24 10:44 UTC
**The exact command to reproduce the issue**:
```
minikube config set vm-driver hyperv
minikube start
```

The general setting inside Hyper-V for "virtual hard disks" points to: `D:\Hyper-V\Virtual_Hard_Disks\`

**The full output of the command that failed**: no actual failure.

But the virtual hard disk location is `C:\Users\dfahl\.minikube\machines\minikube\` instead of the path defined in hyper-v config

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

Windows 10 - 1903

**Comment by medyagh** [comment] 2019-11-04 18:23
@blueelvis any idea on this ?

**Comment by blueelvis** [comment] 2019-11-04 19:48
Yes indeed. This is the default behavior. All the config and the machine (Minikube VM) related files (including snapshots and VHDs) are stored at that location. It doesn't matter what is set in Hyper-V as that is never taken into consideration.

Just curious, do you have less space on the C: drive and hence you have changed it to D: drive?

**Comment by medyagh** [comment] 2019-11-04 22:24
@Flyingmana it appears this is a duplicate of this issue https://github.com/kubernetes/minikube/issues/4802

currently on windows minikube has to be in C:\ Drive

if you don't mind to keep things in one place I will close this one, please subscribe to that other issue to get update when it is fixed

https://github.com/kubernetes/minikube/issues/4802

**Closed by medyagh** 2019-11-04 22:24 UTC
Labels: co/hyperv

**Comment by Flyingmana** [comment] 2019-11-04 23:41
I use the D: drive for this kind of stuff, as this is my NVMe disk, also I try to keep IO heavy stuff of my system disk.

The other Issue seems like it would solve mine indirectly.
Still I think its not good to overwrite system defaults
