### ISSUE TITLE
VM reuse: waiting for k8s-app=kube-proxy: timed out waiting for the condition

### ISSUE THREAD

**Issue by samuel-sujith** [kubernetes/minikube#3850] opened 2019-03-11 15:47 UTC
Command: `minikube start --vm-driver=virtualbox --docker-env=HTTP_PROXY=$HTTP_PROXY --docker-env HTTPS_PROXY=$HTTPS_PROXY --docker-env NO_PROXY=$NO_PROXY`

Output: 

```
o   minikube v0.35.0 on linux (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running virtualbox VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.99.100
o   Found network options:
    - HTTP_PROXY=XXXXX
    - HTTPS_PROXY=XXXXX
    - NO_PROXY=localhost,127.0.0.1,XXXXXXX
-   Configuring Docker as the container runtime ...
    - env HTTP_PROXY=XXXX
    - env HTTPS_PROXY=XXXX
    - env NO_PROXY=XXXXXXX
-   Preparing Kubernetes environment ...
-   Pulling images required by Kubernetes v1.13.4 ...
:   Relaunching Kubernetes v1.13.4 using kubeadm ...
:   Waiting for pods: apiserver proxy!   Error restarting cluster: wait: waiting for k8s-app=kube-proxy: timed out waiting for the condition
```
  - The output of the "minikube logs" command
Attached
  - Which operating system version was used
Ubuntu 16.04
[minikube_logs.txt](https://github.com/kubernetes/minikube/files/2952982/minikube_logs.txt)

**Comment by staticdev** [comment] 2019-03-11 17:40
Did it at #3843 (earlier issue)

**Comment by tstromberg** [comment] 2019-03-13 21:14
@samuel-sujith - Thanks for your bug report! I don't know why kube-proxy isn't coming up, but if you don't mind providing this log, I think it might help:

`minikube ssh docker logs $(docker ps -a -f name=k8s_kube-proxy --format={{.ID}})`

Thanks!

**Comment by SychevIgor** [comment] 2019-03-14 07:45
https://github.com/kubernetes/minikube/issues/3843

**Comment by kmpartner** [comment] 2019-03-21 18:34
After deleting all minikube from virtualbox and getting rid of any leftovers from previous experiments using the following command, I could launch a new minikube 
sudo rm -rf ~/.minikube; sudo rm -rf ~/.kub

**Comment by shenoyn** [comment] 2019-03-26 06:31
I too faced same issue on Mac due to system settings. I ended up re-installing VirtualBox too. 

Finally executed below steps to recover
1. minikube delete (Delete the VM and other states)
2. minikube start (This will create VM fresh)

**Comment by staticdev** [comment] 2019-03-27 13:32
Minikube delete also solved my problem.

**Comment by marcosdiez** [comment] 2019-04-04 15:25
Hi! I had a similar problem and my solution is here: https://github.com/kubernetes/minikube/pull/4052
Could you please try yourself and comment if the solution works for you as well ? Thank you!

**Comment by tstromberg** [comment] 2019-04-04 18:39
Thanks for the bug report! If you run into this with minikube v1.0.0, please attach the output of `minikube logs` so that we can help diagnose the issue further.

**Comment by tstromberg** [comment] 2019-04-11 17:57
Dupe of #3843

**Closed by tstromberg** 2019-04-11 17:57 UTC
Labels: co/kube-proxy, ev/kube-proxy-pod-timeout, priority/important-longterm, triage/needs-information
