### ISSUE TITLE
I have a issue when i run command  minikube start

### ISSUE THREAD

**Issue by r0g3r92** [kubernetes/minikube#18914] opened 2024-05-17 01:33 UTC
### What Happened?

When I try to run the command "minikube start" an error occurred 

 Habilitación de 'default-storageclass' devolvió un error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:45765/apis/storage.k8s.io/v1/storageclasses": dial tcp [::1]:45765: connect: connection refused]

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15342612/logs.txt)

### Operating System

Redhat/Fedora

### Driver

SSH

**Comment by medyagh** [comment] 2024-05-17 19:53
I think this is dupe of https://github.com/kubernetes/minikube/issues/18915

**Closed** 2024-05-17 19:53 UTC
