### ISSUE TITLE
getting error while starting minikube

### ISSUE THREAD

**Issue by Mdrehanalam2020** [kubernetes/minikube#14423] opened 2022-06-25 02:19 UTC
### What Happened?

* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 25 Jun 22 02:06 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 25 Jun 22 02:13 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/06/25 02:13:40
Running on machine: ip-172-31-29-195
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0625 02:13:40.122505    4399 out.go:296] Setting OutFile to fd 1 ...
I0625 02:13:40.122661    4399 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0625 02:13:40.122666    4399 out.go:309] Setting ErrFile to fd 2...
I0625 02:13:40.122673    4399 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0625 02:13:40.122891    4399 root.go:329] Updating PATH: /root/.minikube/bin
W0625 02:13:40.123019    4399 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0625 02:13:40.123127    4399 out.go:303] Setting JSON to false
I0625 02:13:40.123866    4399 start.go:115] hostinfo: {"hostname":"ip-172-31-29-195","uptime":738,"bootTime":1656122482,"procs":118,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.13.0-1029-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec22b394-58b9-640e-e674-60e1bbe09e07"}
I0625 02:13:40.123926    4399 start.go:125] virtualization: xen guest
I0625 02:13:40.126924    4399 out.go:177] * minikube v1.26.0 on Ubuntu 20.04 (xen/amd64)
W0625 02:13:40.129894    4399 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0625 02:13:40.130135    4399 notify.go:193] Checking for updates...
I0625 02:13:40.130193    4399 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0625 02:13:40.130580    4399 exec_runner.go:51] Run: systemctl --version
I0625 02:13:40.133063    4399 driver.go:360] Setting default libvirt URI to qemu:///system
I0625 02:13:40.135710    4399 out.go:177] * Using the none driver based on existing profile
I0625 02:13:40.137709    4399 start.go:284] selected driver: none
I0625 02:13:40.137725    4399 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.195 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0625 02:13:40.137826    4399 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0625 02:13:40.137849    4399 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0625 02:13:40.138325    4399 cni.go:95] Creating CNI manager for ""
I0625 02:13:40.138333    4399 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0625 02:13:40.138377    4399 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.195 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0625 02:13:40.140758    4399 out.go:177] * Starting control plane node minikube in cluster minikube
I0625 02:13:40.142688    4399 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0625 02:13:40.142904    4399 cache.go:208] Successfully downloaded all kic artifacts
I0625 02:13:40.142946    4399 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0625 02:13:40.143236    4399 start.go:356] acquired machines lock for "minikube" in 257.425µs
I0625 02:13:40.143257    4399 start.go:94] Skipping create...Using existing machine configuration
I0625 02:13:40.143265    4399 fix.go:55] fixHost starting: m01
W0625 02:13:40.143479    4399 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0625 02:13:40.143489    4399 api_server.go:165] Checking apiserver status ...
I0625 02:13:40.143516    4399 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0625 02:13:40.174088    4399 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0625 02:13:40.174135    4399 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0625 02:13:40.185217    4399 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0625 02:13:40.185237    4399 fix.go:129] unexpected machine state, will restart: <nil>
I0625 02:13:40.187504    4399 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0625 02:13:40.190712    4399 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0625 02:13:40.190860    4399 start.go:306] post-start starting for "minikube" (driver="none")
I0625 02:13:40.190869    4399 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0625 02:13:40.190923    4399 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0625 02:13:40.199212    4399 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0625 02:13:40.199233    4399 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0625 02:13:40.199246    4399 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0625 02:13:40.201944    4399 out.go:177] * OS release is Ubuntu 20.04.4 LTS
I0625 02:13:40.203972    4399 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0625 02:13:40.204015    4399 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0625 02:13:40.204035    4399 start.go:309] post-start completed in 13.165502ms
I0625 02:13:40.204044    4399 fix.go:57] fixHost completed within 60.780157ms
I0625 02:13:40.204050    4399 start.go:81] releasing machines lock for "minikube", held for 60.803944ms
I0625 02:13:40.204472    4399 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0625 02:13:40.204487    4399 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0625 02:13:40.224746    4399 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0625 02:13:40.485567    4399 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0625 02:13:40.724510    4399 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0625 02:13:40.971014    4399 exec_runner.go:51] Run: sudo systemctl restart docker
I0625 02:13:41.242573    4399 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0625 02:13:41.257659    4399 out.go:177]
W0625 02:13:41.260077    4399 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0625 02:13:41.260106    4399 out.go:239] *
W0625 02:13:41.261112    4399 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0625 02:13:41.263807    4399 out.go:177]

### Attach the log file

* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 25 Jun 22 02:06 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 25 Jun 22 02:13 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/06/25 02:13:40
Running on machine: ip-172-31-29-195
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0625 02:13:40.122505    4399 out.go:296] Setting OutFile to fd 1 ...
I0625 02:13:40.122661    4399 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0625 02:13:40.122666    4399 out.go:309] Setting ErrFile to fd 2...
I0625 02:13:40.122673    4399 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0625 02:13:40.122891    4399 root.go:329] Updating PATH: /root/.minikube/bin
W0625 02:13:40.123019    4399 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0625 02:13:40.123127    4399 out.go:303] Setting JSON to false
I0625 02:13:40.123866    4399 start.go:115] hostinfo: {"hostname":"ip-172-31-29-195","uptime":738,"bootTime":1656122482,"procs":118,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"20.04","kernelVersion":"5.13.0-1029-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec22b394-58b9-640e-e674-60e1bbe09e07"}
I0625 02:13:40.123926    4399 start.go:125] virtualization: xen guest
I0625 02:13:40.126924    4399 out.go:177] * minikube v1.26.0 on Ubuntu 20.04 (xen/amd64)
W0625 02:13:40.129894    4399 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0625 02:13:40.130135    4399 notify.go:193] Checking for updates...
I0625 02:13:40.130193    4399 config.go:178] Loaded profile config "minikube": Driver=none, ContainerRuntime=docker, KubernetesVersion=v1.24.1
I0625 02:13:40.130580    4399 exec_runner.go:51] Run: systemctl --version
I0625 02:13:40.133063    4399 driver.go:360] Setting default libvirt URI to qemu:///system
I0625 02:13:40.135710    4399 out.go:177] * Using the none driver based on existing profile
I0625 02:13:40.137709    4399 start.go:284] selected driver: none
I0625 02:13:40.137725    4399 start.go:805] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.195 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0625 02:13:40.137826    4399 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0625 02:13:40.137849    4399 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0625 02:13:40.138325    4399 cni.go:95] Creating CNI manager for ""
I0625 02:13:40.138333    4399 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0625 02:13:40.138377    4399 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:172.31.29.195 Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0625 02:13:40.140758    4399 out.go:177] * Starting control plane node minikube in cluster minikube
I0625 02:13:40.142688    4399 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0625 02:13:40.142904    4399 cache.go:208] Successfully downloaded all kic artifacts
I0625 02:13:40.142946    4399 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0625 02:13:40.143236    4399 start.go:356] acquired machines lock for "minikube" in 257.425µs
I0625 02:13:40.143257    4399 start.go:94] Skipping create...Using existing machine configuration
I0625 02:13:40.143265    4399 fix.go:55] fixHost starting: m01
W0625 02:13:40.143479    4399 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0625 02:13:40.143489    4399 api_server.go:165] Checking apiserver status ...
I0625 02:13:40.143516    4399 exec_runner.go:51] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0625 02:13:40.174088    4399 api_server.go:169] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0625 02:13:40.174135    4399 exec_runner.go:51] Run: sudo systemctl is-active --quiet service kubelet
I0625 02:13:40.185217    4399 fix.go:103] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0625 02:13:40.185237    4399 fix.go:129] unexpected machine state, will restart: <nil>
I0625 02:13:40.187504    4399 out.go:177] * Restarting existing none bare metal machine for "minikube" ...
I0625 02:13:40.190712    4399 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0625 02:13:40.190860    4399 start.go:306] post-start starting for "minikube" (driver="none")
I0625 02:13:40.190869    4399 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0625 02:13:40.190923    4399 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0625 02:13:40.199212    4399 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0625 02:13:40.199233    4399 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0625 02:13:40.199246    4399 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0625 02:13:40.201944    4399 out.go:177] * OS release is Ubuntu 20.04.4 LTS
I0625 02:13:40.203972    4399 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0625 02:13:40.204015    4399 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0625 02:13:40.204035    4399 start.go:309] post-start completed in 13.165502ms
I0625 02:13:40.204044    4399 fix.go:57] fixHost completed within 60.780157ms
I0625 02:13:40.204050    4399 start.go:81] releasing machines lock for "minikube", held for 60.803944ms
I0625 02:13:40.204472    4399 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0625 02:13:40.204487    4399 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0625 02:13:40.224746    4399 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0625 02:13:40.485567    4399 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0625 02:13:40.724510    4399 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0625 02:13:40.971014    4399 exec_runner.go:51] Run: sudo systemctl restart docker
I0625 02:13:41.242573    4399 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0625 02:13:41.257659    4399 out.go:177]
W0625 02:13:41.260077    4399 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0625 02:13:41.260106    4399 out.go:239] *
W0625 02:13:41.261112    4399 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0625 02:13:41.263807    4399 out.go:177]

### Operating System

Ubuntu

**Comment by spowelljr** [comment] 2022-07-27 18:57
Duplicate of https://github.com/kubernetes/minikube/issues/14410

Fix is to install cri-docker on your machine

Installation instructions: https://github.com/Mirantis/cri-dockerd#build-and-install

**Closed by spowelljr** 2022-07-27 18:57 UTC
Labels: kind/support
