### ISSUE TITLE
Volume mount causes minikube vm to become corrupted.

### ISSUE THREAD

**Issue by matthew-marchetti** [kubernetes/minikube#1601] opened 2017-06-16 20:33 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG REPORT

**Minikube version** (use `minikube version`): 0.19.1

**Environment**:
- **OS** (e.g. from /etc/os-release): OSX 10.12.5
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.18.0.iso
- **Install tools**: virtualbox: 5.1.22
- **Others**:

**What happened**:
When using the volume mount option in pods, the minikube vm appears to become corrupt at some point. Part of the problem appears to be  linked with attempting to use some broken volume mount configs during testing, but its not clear what exactly can cause this. I think it's somehow related to the minikube container not cleaning up a mount that was unsuccessful in kubernetes. The cluster will no longer boot up properly, and needs to be deleted.  I wish i could provide a bit more information around the specific cause, but it just seem to be random enough that a couple of broken mount config cause this issue.

Docker service no long starts
```
$ systemctl status docker.service
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
  Drop-In: /etc/systemd/system/docker.service.d
           └─10-machine.conf
   Active: failed (Result: exit-code) since Fri 2017-06-16 19:44:39 UTC; 5min ago
     Docs: https://docs.docker.com
           https://docs.docker.com
  Process: 3860 ExecStart=/usr/bin/docker daemon -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=virtualbox --label provider=virtualbox --label provider=virtualbox (code=exited, status=1/FAILURE)
 Main PID: 3860 (code=exited, status=1/FAILURE)
    Tasks: 8
   Memory: 4.2M
      CPU: 36ms
   CGroup: /system.slice/docker.service
           └─2843 docker-containerd -l /var/run/docker/libcontainerd/docker-containerd.sock --runtime docker-runc

Jun 16 19:44:39 minikube systemd[1]: Starting Docker Application Container Engine...
Jun 16 19:44:39 minikube docker[3860]: time="2017-06-16T19:44:39.671085821Z" level=info msg="previous instance of containerd still alive (2843)"
Jun 16 19:44:39 minikube docker[3860]: time="2017-06-16T19:44:39.674064640Z" level=info msg="[graphdriver] using prior storage driver \"overlay\""
Jun 16 19:44:39 minikube docker[3860]: time="2017-06-16T19:44:39.678941362Z" level=fatal msg="Error starting daemon: layer does not exist"
Jun 16 19:44:39 minikube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 19:44:39 minikube systemd[1]: Failed to start Docker Application Container Engine.
Jun 16 19:44:39 minikube systemd[1]: docker.service: Unit entered failed state.
Jun 16 19:44:39 minikube systemd[1]: docker.service: Failed with result 'exit-code'.
```
Journalctl output:
```
$ journalctl -f
-- Logs begin at Fri 2017-06-16 19:43:08 UTC. --
Jun 16 19:44:39 minikube docker[3860]: time="2017-06-16T19:44:39.674064640Z" level=info msg="[graphdriver] using prior storage driver \"overlay\""
Jun 16 19:44:39 minikube docker[3860]: time="2017-06-16T19:44:39.678941362Z" level=fatal msg="Error starting daemon: layer does not exist"
Jun 16 19:44:39 minikube systemd[1]: docker.service: Main process exited, code=exited, status=1/FAILURE
Jun 16 19:44:39 minikube systemd[1]: Failed to start Docker Application Container Engine.
Jun 16 19:44:39 minikube systemd[1]: docker.service: Unit entered failed state.
Jun 16 19:44:39 minikube systemd[1]: docker.service: Failed with result 'exit-code'.
Jun 16 19:44:39 minikube sshd[2821]: Received disconnect from 10.0.2.2 port 57470:11: disconnected by user
Jun 16 19:44:39 minikube sshd[2821]: Disconnected from 10.0.2.2 port 57470
Jun 16 19:45:11 minikube kernel: NFSD: Unable to end grace period: -110

```
Getting these in the console for virtualbox:
` ignoring noauto for root device`

minikube output:
```
Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

Temporary Error: ssh command error:
command : sudo systemctl -f start docker
err     : exit status 1
output  : Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.

```
**What you expected to happen**:
Mount volumes into multiple development pods for quicker development.

**How to reproduce it** (as minimally and precisely as possible):
Begin using volumes with hostpath mounts.

Working file that i've been using:
```
--- 
apiVersion: apps/v1beta1
kind: Deployment
metadata: 
  name: nginx-vol-deployment
  namespace: default
spec: 
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: web
    spec: 
      containers: 
        - image: "nginx:latest"
          name: web
          securityContext: 
            privileged: true
          volumeMounts: 
            - mountPath: "/usr/share/nginx/html"
              name: web
      volumes:
        - name: web
          hostPath: 
            path: "/Users/devel/"
```
As far as i can tell adding in some broken mount configs during testing cause it to get into this unrecoverable state.

**Anything else do we need to know**:
Nope.

**Comment by r2d4** [comment] 2017-06-29 17:58
We will try to reproduce this

**Comment by toddgardner** [comment] 2017-10-11 20:33
I'm having similar issues. The cluster starts fine, and runs for a bit and then sometime later (related to pod restarts?) the mount becomes corrupted:

- OS (e.g. from /etc/os-release): OSX 10.12.6
- VM Driver (e.g. cat ~/.minikube/machines/minikube/config.json | grep DriverName): virtualbox
- ISO version (e.g. cat ~/.minikube/machines/minikube/config.json | grep -i ISO or minikube ssh cat /etc/VERSION): minikube-v0.23.4.iso
- Install tools: virtualbox: 5.1.28

Similarly to above, we mount our git repository into minikube, then provide it as a host volume to several containers:

```
minikube start --kubernetes-version=v1.6.4 --mount --mount-string ${git_root}:/opt/path/mount --memory 4096
```

```yml
apiVersion: batch/v1
kind: Job
...
        volumeMounts:
        - mountPath: /usr/src/live_app
          name: src-code
...
      volumes:
      - name: src-code
        hostPath:
          path: ${git_root}
```

Initially the mount exists and is readable with proper permissions. However, after some pods crash and restart, the mount point goes away. I can see the minikube mount process still exists on the host machine's ps.

```
$ minikube ssh
                         _             _            
            _         _ ( )           ( )           
  ___ ___  (_)  ___  (_)| |/')  _   _ | |_      __  
/' _ ` _ `\| |/' _ `\| || , <  ( ) ( )| '_`\  /'__`\
| ( ) ( ) || || ( ) || || |\`\ | (_) || |_) )(  ___/
(_) (_) (_)(_)(_) (_)(_)(_) (_)`\___/'(_,__/'`\____)

$ ls -al /opt/path/mount      
ls: cannot access '/opt/path/mount': Input/output error
$ ls -al /opt/path         
ls: cannot access '/opt/path/mount': Input/output error
total 0
drwxr-xr-x 3 root root 0 Oct 11 19:32 .
drwxr-xr-x 4 root root 0 Oct 11 19:32 ..
d????????? ? ?    ?    ?            ? mount
```

I have not found any relevant logs to explain what's happening yet.

As a work around I'm moving to vbfs since I'm assuming the issue is in the 9p driver.

**Closed** 2018-03-12 23:34 UTC
Labels: area/mount, iso/minikube-iso, lifecycle/rotten
