### ISSUE TITLE
minikube start to annotate the Node with the output of `minikube ip` so that the external IP can be found

### ISSUE THREAD

**Issue by jstrachan** [kubernetes/minikube#544] opened 2016-09-02 08:48 UTC
Linking to the URL of a service (e.g. a web application) in kubernetes is quite complex depending on if using nodePorts, ingress, LoadBalancer (or openshift routes). If using nodePorts to be able to link to the service from, say, a browser you need to know the external IP address of the node.

When using, say, xhyve, the node.status.addresses for `type=LegacyHostIP` is the same as the `minikube ip`. However for vagrant its the internal IP and is not accessible from the host by default and is different to `minikube ip`.

So it'd be nice to annotate the Node with an annotation for the external ip. e.g. in pseudocode:

```
node.metadata.annotations['kubernetes.io/externalip'] = `minikube ip` 
```

Then tools can link correctly to nodeport links when folks don't run Ingress + ingress controllers; whether they use xhyve or virtual box.

For more background on this issue: https://github.com/fabric8io/exposecontroller/issues/1 FWIW we've a microservice which helps automatically create Ingress or Route instances on kubernetes or openshift if enabled and an ingress controller / router is running or enable/disabling of LoadBalancers depending on if on the public cloud etc https://github.com/fabric8io/exposecontroller which we'd like to also annotate the external URLs to things (whether nodePort, loadbalancer, ingress, route or something else)

**Comment by jstrachan** [comment] 2016-09-02 09:05
BTW I wonder if its worth adding a node annotation too to indicate that the cluster was created by minikube (and maybe a version)? I'm currently adding a little tool to help provision PersistentVolumes and knowing how to ssh into the host (minikube, vagrant or minishift et al) would be handy to know how the cluster was installed etc. e.g. installed via minikube 0.8.0 with xyhve as an annotation or two?

**Comment by jimmidyson** [comment] 2016-09-02 15:15
> However for vagrant its the internal IP and is not accessible from the host by default and is different to minikube ip.

There is no vagrant involved in minikube at all. I guess you mean VirtualBox? Node IP should be routable from the host. If not that is a bug in localkube & so we shouldn't have to annotate.

**Comment by jstrachan** [comment] 2016-09-02 15:16
@jimmidyson sorry meant VirtualBox :) But yes - seems there's a bug in localkube; there's no way to find the routable IP on VirtualBox it seems with minikube

**Comment by jimmidyson** [comment] 2016-09-02 15:16
Ah I fixed something similar in minishift I think - let me look.

**Comment by jimmidyson** [comment] 2016-09-02 15:17
No I didn't... still broken. The problem is the kubelet choosing the first non-local eth address. We should be able to specify that properly when starting the kubelet.

**Comment by amouat** [comment] 2016-09-07 10:20
I'm hitting this issue as well. I note the KVM driver seems to work correctly, if that helps anyone.

**Comment by jimmidyson** [comment] 2016-09-07 10:39
This should now be fixed in #548. Should be in next release.

**Comment by jimmidyson** [comment] 2016-09-07 10:39
When I say fixed, what I mean is the node address should now be a routeable IP that matches `minikube ip` & therefore we don't need the annotation requested.

**Closed by jimmidyson** 2016-09-07 10:39 UTC

**Comment by amouat** [comment] 2016-09-07 10:45
Ah, excellent thanks!

**Comment by jstrachan** [comment] 2017-10-26 15:51
@balboah I noticed there's now an annotation on the node that ends in `.kubernetes.io/provided-node-ip` which has the IP

**Comment by balboah** [comment] 2017-10-27 08:19
@jstrachan cool! this is a great backup for my discovery. thanks

**Comment by kaizamm** [comment] 2018-03-17 13:17
@jstrachan same issue,but cannot find what your mean,expect your detailly explain,3Q
@balboah it seems that you have solve it ,can you share your experience ? i have the same issue with you.

**Comment by balboah** [comment] 2018-03-19 09:06
@kaizamm I used the annotation mentioned above and then created a small helper https://github.com/joonix/k8s-externalip as an init container since the service I'm running needs to read this value from a file. It basically substitutes the placeholder with the real IP in the file
