### ISSUE TITLE
Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL) --no-vtx-check=true

### ISSUE THREAD

**Issue by soutmesa** [kubernetes/minikube#5280] opened 2019-09-06 03:06 UTC
**The exact command to reproduce the issue**:

`minikube start --no-vtx-check=true`
**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

* minikube v1.3.1 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Creating virtualbox VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
E0906 10:04:49.181155    6444 start.go:723] StartHost: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.881802 Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL (0X80004005))
*
X Unable to start VM: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: Call to WHvSetupPartition failed: ERROR_SUCCESS (Last=0xc000000d/87) (VERR_NEM_VM_CREATE_FAILED)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole

Details: 00:00:01.881802 Power up failed (vrc=VERR_NEM_VM_CREATE_FAILED, rc=E_FAIL (0X80004005))
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Host Name:                 DESKTOP-4LS7HBN
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.18362 N/A Build 18362
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows User
Registered Organization:
Product ID:                00331-10000-00001-AA320
Original Install Date:     8/30/2019, 10:01:37 AM
System Boot Time:          9/2/2019, 8:19:13 AM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 9020
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3301 Mhz

**Comment by tstromberg** [comment] 2019-09-06 16:34
It seems like VirtualBox does not work on your machine. Do you mind sharing the output of:

* `systeminfo`
* `vboxmanage --version`

My gut instincts says that this may be due to Virtualization not being enabled in BIOS, or a conflict with Hyper-V. These commands should confirm which one it is.

**Comment by tstromberg** [comment] 2019-09-20 20:51
This issue appears to be a duplicate of #4587, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-09-20 20:51 UTC
Labels: co/virtualbox, os/windows, triage/support
