### ISSUE TITLE
- /tmp/minikube_addons_fe32266e638f59808ba3af3559d61a6de6ad2bfc_0.log

### ISSUE THREAD

**Issue by RusAdrianC** [kubernetes/minikube#12114] opened 2021-08-04 07:12 UTC
**Steps to reproduce the issue:** 

1.minikube addons enable ingress

**Full output of `minikube logs` command:**
<details>
Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

</details>

**Full output of failed command:**
<details>

</details>

**Comment by RusAdrianC** [comment] 2021-08-04 07:38
Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭─────────────────────────────────────────────────────────────────────────────╮
│                                                                             │
│    😿  If the above advice does not help, please let us know:               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose             │
│                                                                             │
│    Please attach the following file to the GitHub issue:                    │
│    - /tmp/minikube_addons_fe32266e638f59808ba3af3559d61a6de6ad2bfc_0.log

**Comment by RusAdrianC** [comment] 2021-08-04 07:39
Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭─────────────────────────────────────────────────────────────────────────────╮
│                                                                             │
│    😿  If the above advice does not help, please let us know:               │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose             │
│                                                                             │
│    Please attach the following file to the GitHub issue:                    │
│    - /tmp/minikube_addons_fe32266e638f59808ba3af3559d61a6de6ad2bfc_0.log

**Comment by apupier** [comment] 2021-08-04 14:57
seems a duplicate of https://github.com/kubernetes/minikube/issues/10544

**Comment by spowelljr** [comment] 2021-08-04 18:43
Hi @RusAdrianC, thanks for reporting your issue with minikube! As @apupier stated, this is a duplicate of #10544. I'm going to close this issue, but please follow along with #10544, thank you!

**Closed by spowelljr** 2021-08-04 18:43 UTC
Labels: triage/needs-information
