### ISSUE TITLE
Minikube Cluster is not running

### ISSUE THREAD

**Issue by oliyavan** [kubernetes/minikube#2009] opened 2017-09-27 03:49 UTC
**Is this a BUG REPORT ** (choose one):

**Environment**:
v0.22.2
Windows 10
virtualbox
minikube-v0.23.4.iso

**What happened**:
When i try to start the minikube cluster with below command i am not seeing any issue ?
`minikube.exe start --kubernetes-version="v1.7.5" --vm-driver="virtualbox" --alsologtostderr
`
the command execution finished sucessfully, but still when we check the cluster status.
It is showing cluster stopped

Please check the below message for your reference.
```
PS C:\kubernetes> minikube.exe status
minikube: Running
cluster: Stopped
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.102

```
**What you expected to happen**:
it should show cluster is running 
```
minikube: Running
cluster: running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.102

```
**Output of `minikube logs` (if applicable)**:
check the attachment for your reference for logs
[error.log](https://github.com/kubernetes/minikube/files/1335734/error.log)

**Comment by r2d4** [comment] 2017-09-28 17:48
Closing as dupe of #1981

**Closed by r2d4** 2017-09-28 17:48 UTC
