### ISSUE TITLE
minikube 1.19.0 multinode restart via minikube start broken

### ISSUE THREAD

**Issue by kfox1111** [kubernetes/minikube#11153] opened 2021-04-19 22:21 UTC
1. start a multinode cluster with minikube start 
2. minikube status shows minikube, minikube-m02, minikube-m03
3. reboot the vms
4. minikube start #to get everything running again.
5. minikube ssh -n minikube-m02 broken

**Full output of failed command:** 

$ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

minikube-m03
type: Worker
host: Running
kubelet: Running

minikube-m03
type: Worker
host: Running
kubelet: Running

**Full output of `minikube start` command used, if not already included:**
minikube start --cni=calico --nodes=3 --memory=3g

**Comment by folkersj** [comment] 2021-05-12 18:33
I have the same issue.
During or after the start of the cluster the config.json is rewritten and the minikube-m02 is gone and instead there is a second m03 section. 

```
    "Nodes": [
        {
            "Name": "",
            "IP": "172.16.30.3",
            "Port": 8443,
            "KubernetesVersion": "v1.20.2",
            "ControlPlane": true,
            "Worker": true
        },
        {
            "Name": "m03",
            "IP": "172.16.30.5",
            "Port": 0,
            "KubernetesVersion": "v1.20.2",
            "ControlPlane": false,
            "Worker": true
        },
        {
            "Name": "m03",
            "IP": "172.16.30.5",
            "Port": 0,
            "KubernetesVersion": "v1.20.2",
            "ControlPlane": false,
            "Worker": true
        }
    ],
```

Manually changing on instance of m03 to m02 including the ip-address makes everything work again, until the next time Minikube Is started.

❯ minikube version
minikube version: v1.20.0
commit: c61663e942ec43b20e8e70839dcca52e44cd85ae

Problem happens with both VMware Fusion and VirtualBox.

**Comment by spowelljr** [comment] 2021-06-23 18:12
This is a duplicate of #11687 which is currently being fixed. I'm going to close this issue, please follow along there, thanks!

**Closed by spowelljr** 2021-06-23 18:12 UTC
Labels: co/multinode, kind/support
