### ISSUE TITLE
hyperv: Unable to start VM: start: exit status 1

### ISSUE THREAD

**Issue by sneevand** [kubernetes/minikube#4374] opened 2019-05-29 20:50 UTC
! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the hyperv driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

* Restarting existing hyperv VM for "minikube" ...
E0529 15:48:40.579626    5484 start.go:529] StartHost: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment] 2019-05-29 23:27
Do you mind sharing the output of:

`minikube start --alsologtostderr -v=8`

Thanks!

**Comment by sneevand** [comment] 2019-05-30 14:57
trying to install in windows 2012 r2 server

Error: unknown flag: --show-libmachine-logs
Usage:
  minikube start [flags]

Flags:
      --apiserver-ips ipSlice             A set of apiserver IP Addresses which are used in the generated certificate fo
r kubernetes.  This can be used if you want to make the apiserver available from outside the machine (default [])
      --apiserver-name string             The apiserver name which is used in the generated certificate for kubernetes.
 This can be used if you want to make the apiserver available from outside the machine (default "minikubeCA")
      --apiserver-names stringArray       A set of apiserver names which are used in the generated certificate for kuber
netes.  This can be used if you want to make the apiserver available from outside the machine
      --apiserver-port int                The apiserver listening port (default 8443)
      --cache-images                      If true, cache docker images for the current bootstrapper and load them into t
he machine. Always false with --vm-driver=none. (default true)
      --container-runtime string          The container runtime to be used (docker, crio, containerd) (default "docker")

      --cpus int                          Number of CPUs allocated to the minikube VM (default 2)
      --cri-socket string                 The cri socket path to be used
      --disable-driver-mounts             Disables the filesystem mounts provided by the hypervisors (vboxfs, xhyve-9p)
      --disk-size string                  Disk size allocated to the minikube VM (format: <number>[<unit>], where unit =
 b, k, m or g) (default "20g")
      --dns-domain string                 The cluster dns domain name used in the kubernetes cluster (default "cluster.l
ocal")
      --docker-env stringArray            Environment variables to pass to the Docker daemon. (format: key=value)
      --docker-opt stringArray            Specify arbitrary flags to pass to the Docker daemon. (format: key=value)
      --download-only                     If true, only download and cache files for later use - don't install or start
anything.
      --enable-default-cni                Enable the default CNI plugin (/etc/cni/net.d/k8s.conf). Used in conjunction w
ith "--network-plugin=cni"
      --extra-config ExtraOption          A set of key=value pairs that describe configuration that may be passed to dif
ferent components.
                                                        The key should be '.' separated, and the first part before the d
ot is the component to apply the configuration to.
                                                        Valid components are: kubelet, kubeadm, apiserver, controller-ma
nager, etcd, proxy, scheduler
                                                        Valid kubeadm parameters: ignore-preflight-errors, dry-run, kube
config, kubeconfig-dir, node-name, cri-socket, experimental-upload-certs, certificate-key, rootfs, pod-network-cidr
      --feature-gates string              A set of key=value pairs that describe feature gates for alpha/experimental fe
atures.
      --gpu                               Enable experimental NVIDIA GPU support in minikube (works only with kvm2 drive
r on Linux)
  -h, --help                              help for start
      --hidden                            Hide the hypervisor signature from the guest in minikube (works only with kvm2
 driver on Linux)
      --host-only-cidr string             The CIDR to be used for the minikube VM (only supported with Virtualbox driver
) (default "192.168.99.1/24")
      --hyperkit-vpnkit-sock string       Location of the VPNKit socket used for networking. If empty, disables Hyperkit
 VPNKitSock, if 'auto' uses Docker for Mac VPNKit connection, otherwise uses the specified VSock.
      --hyperkit-vsock-ports strings      List of guest VSock ports that should be exposed as sockets on the host (Only
supported on with hyperkit now).
      --hyperv-virtual-switch string      The hyperv virtual switch name. Defaults to first found. (only supported with
HyperV driver)
      --image-mirror-country string       Country code of the image mirror to be used. Leave empty to use the global one
. For Chinese mainland users, set it to cn
      --image-repository string           Alternative image repository to pull docker images from. This can be used when
 you have limited access to gcr.io. Set it to "auto" to let minikube decide one for you. For Chinese mainland users, you
 may use local gcr.io mirrors such as registry.cn-hangzhou.aliyuncs.com/google_containers
      --insecure-registry strings         Insecure Docker registries to pass to the Docker daemon.  The default service
CIDR range will automatically be added.
      --iso-url string                    Location of the minikube iso (default "https://storage.googleapis.com/minikube
/iso/minikube-v1.1.0.iso")
      --keep-context                      This will keep the existing kubectl context and will create a minikube context
.
      --kubernetes-version string         The kubernetes version that the minikube VM will use (ex: v1.2.3) (default "v1
.14.2")
      --kvm-network string                The KVM network name. (only supported with KVM driver) (default "default")
      --memory int                        Amount of RAM allocated to the minikube VM in MB (default 2048)
      --mount                             This will start the mount daemon and automatically mount files into minikube
      --mount-string string               The argument to pass the minikube mount command on start (default "C:\\Users\\
xyz:/minikube-host")
      --network-plugin string             The name of the network plugin
      --nfs-share strings                 Local folders to share with Guest via NFS mounts (Only supported on with hyper
kit now)
      --nfs-shares-root string            Where to root the NFS Shares (defaults to /nfsshares, only supported with hype
rkit now) (default "/nfsshares")
      --no-vtx-check                      Disable checking for the availability of hardware virtualization before the vm
 is started (virtualbox)
      --registry-mirror strings           Registry mirrors to pass to the Docker daemon
      --service-cluster-ip-range string   The CIDR to be used for service cluster IPs. (default "10.96.0.0/12")
      --uuid string                       Provide VM UUID to restore MAC address (only supported with Hyperkit driver).
      --vm-driver string                  VM driver is one of: [virtualbox parallels vmwarefusion kvm xhyve hyperv hyper
kit kvm2 vmware none] (default "virtualbox")
      --xhyve-disk-driver string          The disk driver to use [ahci-hd|virtio-blk] (only supported with xhyve driver)
 (default "ahci-hd")

Global Flags:
      --alsologtostderr                  log to standard error as well as files
  -b, --bootstrapper string              The name of the cluster bootstrapper that will set up the kubernetes cluster. (
default "kubeadm")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
  -p, --profile string                   The name of the minikube VM being used.
                                                This can be modified to allow for multiple minikube instances to be run
independently (default "minikube")
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging

**Comment by tstromberg** [comment] 2019-05-30 17:43
This issue appears to be a duplicate of #2954, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Comment by tstromberg** [comment] 2019-05-30 17:48
The root cause here is that HyperV has not been setup on the host. You may want to try the virtualbox driver instead.

**Comment by sgiovinetti** [comment] 2019-06-05 08:08
Please reopen the bug is still present.
Here below the log. It seems that minikube skip to create the VM even if it should be. (No minikube VM is present in Hv since it was delete before using minikube delete).

minikube start --vm-driver hyperv --hyperv-virtual-switch "MiniKube" --alsologtostderr -v=8
I0605 10:05:31.048076   20616 notify.go:128] Checking for updates...
* minikube v1.1.0 on windows (amd64)
I0605 10:05:31.439988   20616 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso
I0605 10:05:31.440737   20616 start.go:721] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "hyperv",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "MiniKube",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.14.2",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0605 10:05:31.442731   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.2 at F:\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.14.2
I0605 10:05:31.443733   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.2 at F:\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.14.2
I0605 10:05:31.445732   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at F:\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0605 10:05:31.443733   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.2 at F:\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.14.2
I0605 10:05:31.445732   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at F:\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0605 10:05:31.443733   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at F:\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0605 10:05:31.444741   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.2 at F:\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.14.2
I0605 10:05:31.444741   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at F:\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0605 10:05:31.444741   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/pause:3.1 at F:\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0605 10:05:31.444741   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at F:\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0605 10:05:31.444741   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at F:\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0605 10:05:31.445732   20616 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at F:\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0605 10:05:31.442731   20616 cache_images.go:307] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at F:\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0605 10:05:31.513733   20616 cluster.go:81] Skipping create...Using existing machine configuration
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
I0605 10:05:32.715624   20616 cache_images.go:304]
I0605 10:05:32.734628   20616 cache_images.go:304]
I0605 10:05:32.839622   20616 cache_images.go:304]
I0605 10:05:32.886626   20616 cache_images.go:304]
I0605 10:05:32.891629   20616 cache_images.go:304]
I0605 10:05:32.900623   20616 cache_images.go:304]
I0605 10:05:32.904625   20616 cache_images.go:304]
I0605 10:05:32.933626   20616 cache_images.go:304]
I0605 10:05:32.970630   20616 cache_images.go:304]
I0605 10:05:32.970630   20616 cache_images.go:304]
I0605 10:05:33.015622   20616 cache_images.go:304]
I0605 10:05:33.032622   20616 cache_images.go:304]
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".



E0605 10:05:35.578756   20616 start.go:529] StartHost: start: exit status 1
I0605 10:05:35.589747   20616 utils.go:122] non-retriable error: start: exit status 1
I0605 10:05:35.586748   20616 cache_images.go:304]
W0605 10:05:35.589747   20616 exit.go:100] Unable to start VM: start: exit status 1

X Unable to start VM: start: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by medyagh** [comment] 2019-06-05 21:49
I faced this issue in hyper on windows 10:

it seems to be minikube delete not working correctly, 
 minikube thinks there is a minikube vm on hyperv but there isnt any !

The exact command to reproduce the issue:
minikube delete

and

minikube start --vm-driver hyperv --hyperv-virtual-switch=primary-virtual-swtich

The full output of the command that failed (start output):

minikube start --vm-driver hyperv --hyperv-virtual-switch=primary-virtual-swtich --alsologtostderr -v=8
I0605 14:40:36.914362     984 notify.go:128] Checking for updates...
* minikube v1.1.0 on windows (amd64)
I0605 14:40:37.091641     984 downloader.go:60] Not caching ISO, using https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso
I0605 14:40:37.094636     984 start.go:721] Saving config:
{
    "MachineConfig": {
        "MinikubeISO": "https://storage.googleapis.com/minikube/iso/minikube-v1.1.0.iso",
        "Memory": 2048,
        "CPUs": 2,
        "DiskSize": 20000,
        "VMDriver": "hyperv",
        "ContainerRuntime": "docker",
        "HyperkitVpnKitSock": "",
        "HyperkitVSockPorts": [],
        "XhyveDiskDriver": "ahci-hd",
        "DockerEnv": null,
        "InsecureRegistry": null,
        "RegistryMirror": null,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HypervVirtualSwitch": "primary-virtual-swtich",
        "KvmNetwork": "default",
        "DockerOpt": null,
        "DisableDriverMounts": false,
        "NFSShare": [],
        "NFSSharesRoot": "/nfsshares",
        "UUID": "",
        "GPU": false,
        "Hidden": false,
        "NoVTXCheck": false
    },
    "KubernetesConfig": {
        "KubernetesVersion": "v1.14.2",
        "NodeIP": "",
        "NodePort": 8443,
        "NodeName": "minikube",
        "APIServerName": "minikubeCA",
        "APIServerNames": null,
        "APIServerIPs": null,
        "DNSDomain": "cluster.local",
        "ContainerRuntime": "docker",
        "CRISocket": "",
        "NetworkPlugin": "",
        "FeatureGates": "",
        "ServiceCIDR": "10.96.0.0/12",
        "ImageRepository": "",
        "ExtraOptions": null,
        "ShouldLoadCachedImages": true,
        "EnableDefaultCNI": false
    }
}
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.13 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\k8s-dns-kube-dns-amd64_1.14.13
I0605 14:40:37.113634     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.13 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13
I0605 14:40:37.114634     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.13 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\k8s-dns-dnsmasq-nanny-amd64_1.14.13
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-proxy:v1.14.2 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kube-proxy_v1.14.2
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-scheduler:v1.14.2 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kube-scheduler_v1.14.2
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-controller-manager:v1.14.2 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kube-controller-manager_v1.14.2
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-apiserver:v1.14.2 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kube-apiserver_v1.14.2
I0605 14:40:37.100685     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/pause:3.1 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\pause_3.1
I0605 14:40:37.113634     984 cache_images.go:307] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.1 at C:\Users\admin\.minikube\cache\images\gcr.io\k8s-minikube\storage-provisioner_v1.8.1
I0605 14:40:37.115664     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/coredns:1.3.1 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\coredns_1.3.1
I0605 14:40:37.115664     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.10.1 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kubernetes-dashboard-amd64_v1.10.1
I0605 14:40:37.115664     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/etcd:3.3.10 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\etcd_3.3.10
I0605 14:40:37.115664     984 cache_images.go:307] Attempting to cache image: k8s.gcr.io/kube-addon-manager:v9.0 at C:\Users\admin\.minikube\cache\images\k8s.gcr.io\kube-addon-manager_v9.0
I0605 14:40:37.117630     984 cluster.go:81] Skipping create...Using existing machine configuration
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
 
 
I0605 14:40:37.727393     984 cluster.go:100] Machine state:
* Restarting existing hyperv VM for "minikube" ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Start-VM minikube
[stdout =====>] :
[stderr =====>] : Hyper-V\Start-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Start-VM minikube
+ ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Start-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.StartVM
 
 
E0605 14:40:38.299426     984 start.go:529] StartHost: start: exit status 1
I0605 14:40:38.301395     984 utils.go:122] non-retriable error: start: exit status 1
W0605 14:40:38.307395     984 exit.go:100] Unable to start VM: start: exit status 1
 
X Unable to start VM: start: exit status 1
 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
The full output of the command that failed (delete output):

minikube delete --alsologtostderr -v=8
I0605 14:41:28.419401    8500 notify.go:128] Checking for updates...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
 
 
I0605 14:41:29.137685    8500 cluster.go:161] host is in state
* Deleting "minikube" from hyperv ...
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] :
[stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM
 
 
[executing ==>] : C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive Hyper-V\Remove-VM minikube -Force
[stdout =====>] :
[stderr =====>] : Hyper-V\Remove-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:1
+ Hyper-V\Remove-VM minikube -Force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (:) [Remove-VM], VirtualizationException
    + FullyQualifiedErrorId : ObjectNotFound,Microsoft.HyperV.PowerShell.Commands.RemoveVM
 
 
W0605 14:41:30.256764    8500 exit.go:100] Failed to delete cluster: exit status 1
 
X Failed to delete cluster: exit status 1
 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

The output of the minikube logs command:

minikube logs
 
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
 
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new
The operating system version:
windows 10 pro

**Comment by medyagh** [comment] 2019-06-05 21:53
@sgiovinetti @sneevand  I was able to bypass the issue by deleting the .minikube folder


could you please try to delete the folder under `C:\Users\medya\.minikube` and do `minikube delete` and `minikube start` ?

**Comment by sgiovinetti** [comment] 2019-06-06 06:56
@medyagh . Yes deleting the folder solved the issue.

**Comment by tstromberg** [comment] 2019-07-17 04:46
Closing, as `unable to find a virtual machine with name "minikube"` errors are not relevant to the original report.

**Closed** 2019-07-17 04:46 UTC
Labels: co/hyperv, priority/awaiting-more-evidence, triage/needs-information

**Comment by iohanhinokuma** [comment] 2019-09-13 20:40
Eu tive o mesmo problema, eu lembro de já ter instalado anteriormente o minikube e funcionou, nessa segunda vez que surgiu o problema, mas apagando a pasta .minikube resolveu, grato.

**Comment by lpcman** [comment] 2020-04-10 03:46
rerun `Enable-WindowsOptionalFeature-Online -FeatureName Microsoft-Hyper-V -All` and restart computer immediately base on the PowerShell cmd request, then run `minikue start --driver=hyperv` solved my problem  
minikube version: v1.9.2

**Comment by amit23071982** [comment] 2020-05-18 14:30
deleted .minikube folder  and ran minikube start not able to see virtual machine name minikube.
Below is output.

* minikube 1.10.1 is available! Download it: https://github.com/kubernetes/minikube/releases/tag/v1.10.1
* To disable this notice, run: 'minikube config set WantUpdateNotification false'

! minikube v1.9.2 on Microsoft Windows 10 Home Single Language 10.0.18362 Build 18362
* Automatically selected the hyperv driver
* Downloading VM boot image ...
    > minikube-v1.9.0.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 1s
    > minikube-v1.9.0.iso: 174.93 MiB / 174.93 MiB  100.00% 807.90 KiB p/s 3m42
* Starting control plane node m01 in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
panic: runtime error: index out of range [0] with length 0

goroutine 60 [running]:
github.com/docker/machine/drivers/hyperv.hypervAvailable(0xc0005eced0, 0xc000706ab0)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/powershell.go:64 +0x105
github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc00025e480, 0x0, 0x0)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/hyperv.go:171 +0x3b
k8s.io/minikube/pkg/minikube/machine.(*LocalClient).Create(0xc000734100, 0xc00025e4e0, 0x0, 0x0)
        /app/pkg/minikube/machine/client.go:229 +0x3f5
k8s.io/minikube/pkg/minikube/machine.timedCreateHost.func2(0x1e08b00, 0xc000734100, 0xc00025e4e0, 0xc00020daa0, 0xc0006e10a0)
        /app/pkg/minikube/machine/start.go:170 +0x42
created by k8s.io/minikube/pkg/minikube/machine.timedCreateHost
        /app/pkg/minikube/machine/start.go:169 +0x10e
