### ISSUE TITLE
Homebrew upgrade minikube 1.33.1 failed with tag SHA error

### ISSUE THREAD

**Issue by sh2sg** [kubernetes/minikube#18923] opened 2024-05-19 10:13 UTC
### What Happened?

Homebrew needs to pull the source code and compile it on macOS Big Sur. An error related to the tag SHA occurred during the upgrade process. Has it been re-tagged?

```
$ brew upgrade minikube
Warning: You are using macOS 11.
We (and Apple) do not provide support for this old version.
It is expected behaviour that some formulae will fail to build in this old version.
It is expected behaviour that Homebrew will be buggy and slow.
Do not create any issues about this on Homebrew's GitHub repositories.
Do not create any issues even if you think this message is unrelated.
Any opened issues will be immediately closed without response.
Do not ask for help from Homebrew or its maintainers on social media.
You may ask for help in Homebrew's discussions but are unlikely to receive a response.
Try to figure out the problem yourself and submit a fix as a pull request.
We will review it but may or may not accept it.

==> Upgrading 1 outdated package:
minikube 1.33.0 -> 1.33.1
==> Fetching minikube
==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/b6f558feb9c32e39e78bfb15d5c0fbfdf461ce84/Formul
Already downloaded: /Users/<user>/Library/Caches/Homebrew/downloads/e345dea467614fc7201bc91d4f6e62a8b8117644c61c31a2598502f6d54af833--minikube.rb
==> Cloning https://github.com/kubernetes/minikube.git
Updating /Users/<user>/Library/Caches/Homebrew/minikube--git
==> Checking out tag v1.33.1
HEAD is now at 5883c0921 Merge pull request #18879 from spowelljr/fixRPMBuild
HEAD is now at 5883c0921 Merge pull request #18879 from spowelljr/fixRPMBuild
Entering 'hack/benchmark/image-build/minikube-image-benchmark'
Entering 'hack/benchmark/time-to-k8s/time-to-k8s-repo'
Entering 'site/themes/docsy'
/Users/<user>/Library/Caches/Homebrew/minikube--git/hack/benchmark/image-build/minikube-image-benchmark
/Users/<user>/Library/Caches/Homebrew/minikube--git/hack/benchmark/time-to-k8s/time-to-k8s-repo
/Users/<user>/Library/Caches/Homebrew/minikube--git/site/themes/docsy
Error: v1.33.1 tag should be 248d1ec5b3f9be5569977749a725f47b018078ff
but is actually 5883c09216182566a63dff4c326a6fc9ed2982ff
```

### Attach the log file

Not required.

### Operating System

macOS (Default)

### Driver

HyperKit

**Comment by frenkysina** [comment] 2024-05-20 09:17
I also experienced a similar situation

**Comment by spowelljr** [comment] 2024-05-20 20:31
Hi @sh2sg, yes, there was a previous tag that was up for ~30 minutes, it seems the Homebrew automation pulled in the tag during the time, there was a RPM build issue causing release binaries to not build and required a PR to resolve ( https://github.com/kubernetes/minikube/pull/18879) so I deleted the tag. After the PR was merged I retagged and rebuilt the release, this looks like this is the cause of the issue. I'll look into getting this fixed in Homebrew

**Comment by spowelljr** [comment] 2024-05-20 21:55
This should be resolved as the SHA was updated in Homebrew, could you try again?

**Comment by spowelljr** [comment] 2024-05-21 17:27
Glad we got this resolved, I'll close the issue

**Closed by spowelljr** 2024-05-21 17:27 UTC
