### ISSUE TITLE
Error starting stopped host: Machine didn't return an IP after 120 seconds.

### ISSUE THREAD

**Issue by norbix** [kubernetes/minikube#3901] opened 2019-03-18 20:42 UTC
Hi guys,

I'm using CentOS7 and of course KVM hypervisor to install/setup minikube and I can't move forward because of this error:

[norbix@gamma ~]$ minikube start --vm-driver kvm2  
Starting local Kubernetes v1.13.2 cluster...
Starting VM ...
E0318 21:32:40.679351    6630 start.go:205] Error starting host: Error starting stopped host: Machine didn't return an IP after 120 seconds.
Retrying. 
E0318 21:32:40.679757    6630 start.go:211] Error starting host:  Error starting stopped host: Machine didn't return an IP after 120 seconds

minikube failed :( exiting with error code 1
[norbix@gamma ~]$ minikube version
minikube version: v0.33.1

[norbix@gamma ~]$ sudo virsh list --all|head -3
 Id    Name                           State
----------------------------------------------------
 25    minikube                       running
[norbix@gamma ~]$ 
[norbix@gamma ~]$ cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core) 
[norbix@gamma ~]$ uname -a 
Linux gamma 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[norbix@gamma ~]$

**Comment by tstromberg** [comment] 2019-03-22 01:53
It may not be a long-term solution, but you can probably work around this by running `minikube delete` to reset the local VM state. Please let me know if that helps!

**Comment by amouat** [comment] 2019-03-28 17:12
I have the same error with the kvm2 driver, but with minikube 1.0 and not on redhat. Would you like me to open a different issue? Deleting the VM doesn't seem to help. Is there a preferred kernel version btw?

```
$ uname -a
Linux marvin 4.16.7-041607-generic #201805021131 SMP Wed May 2 15:34:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by balopat** [comment] 2019-04-04 19:00
This might be a dupe of #3566 but that one was for debian - this is for centos. 

Can you run through the debug recommendations in: 

https://github.com/kubernetes/minikube/issues/3566#issuecomment-459078052

4.16 kernel should be fine.

**Comment by tstromberg** [comment] 2019-05-23 22:29
Marking as dupe of #3566

**Closed** 2019-05-23 22:28 UTC
Labels: co/kvm2, priority/awaiting-more-evidence, triage/support
