### ISSUE TITLE
virtualbox: Could not find matching IP for MAC address

### ISSUE THREAD

**Issue by koomalkc** [kubernetes/minikube#7917] opened 2020-04-26 23:15 UTC
Hi,
I'm having an issue while starting minikube in windows 10. 
So far, I have installed kubectl, minikube and Virtvirtualbox (ubunto-docker) in my local machine.
I have enable VM in BIOS setup, and  Hypervisor is pre installed  in my laptop. 
And, do I need to install Vitrtual box in my local machine despite having built in Hypervisior?

The command and it's error mesages are as follows: 
C:\kube>minikube start
* minikube v1.9.2 on Microsoft Windows 10 Home 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node m01 in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
* Updating the running virtualbox "minikube" VM ...
*
X Failed to start virtualbox VM. "minikube start" may fix it.: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08xxxxxxx
*

Any input/help is highly appreciated.
Thanks!
_kamal

**Comment by tstromberg** [comment] 2020-04-27 04:42
This issue appears to be a duplicate of #7725, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-27 04:42 UTC
