### ISSUE TITLE
minikube start failure

### ISSUE THREAD

**Issue by j75** [kubernetes/minikube#8220] opened 2020-05-20 15:59 UTC
**Steps to reproduce the issue:** 

1. minikube start

**Full output of `minikube start` command used, if not already included:**
😄  minikube v1.10.1 on Debian 10.4
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🤷  docker "minikube" container is missing, will recreate.
E0520 17:46:34.620324    8734 oci.go:79] docker daemon seems to be stuck. Please try restarting your docker. Will try to delete anyways: unknown state "minikube": docker inspect minikube --format={{.State.Status}}: exit status 1
stdout:

stderr:
Template parsing error: template: :1:8: executing "" at <.State.Status>: map has no entry for key "State"
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🤦  StartHost failed, but will try again: recreate: creating host: create: creating: prepare kic ssh: apply authorized_keys file ownership, output 
** stderr ** 
Error response from daemon: Container 0a1458abdbde52f03a6803a5cd340295ae7a45bd7de59801cf07786df4325195 is not running

** /stderr **: chown docker:docker /home/docker/.ssh/authorized_keys: exit status 1
stdout:

stderr:
Error response from daemon: Container 0a1458abdbde52f03a6803a5cd340295ae7a45bd7de59801cf07786df4325195 is not running

🔄  Restarting existing docker container for "minikube" ...
😿  Failed to start docker container. "minikube start" may fix it: provision: get ssh host-port: get port 22 for "minikube": docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .Networ...>: error calling index: index of untyped nil

💣  error provisioning host: Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .Networ...>: error calling index: index of untyped nil

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
...

**Optional: Full output of `minikube logs` command:**
<details>
🤷  The control plane node must be running for this command
👉  To fix this, run: "minikube start"
</details>

**Comment by afbjorklund** [comment] 2020-05-20 17:13
Seems like the same problem as in #8209

**Comment by tstromberg** [comment] 2020-05-28 17:20
This issue appears to be a duplicate of #8163, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-28 17:20 UTC
Labels: co/docker-driver, os/linux, triage/support

**Comment by j75** [comment] 2020-05-28 19:45
> do you mind if we move the conversation there?

Not at all, thank you for asking!

**Comment by jerryTJ** [comment] 2021-05-16 13:39
my Mac M1 start Minikube error 
VitualBox version 6.1.20
minikube start --vm-driver=virtualbox  --image-mirror-controy=cn
**error info**
😄  minikube v1.19.0 on Darwin 11.2.3 (arm64)
✨  Using the virtualbox driver based on user configuration

❌  Exiting due to DRV_UNSUPPORTED_OS: The driver 'virtualbox' is not supported on darwin/arm64

**Comment by afbjorklund** [comment] 2021-05-16 13:57
@jerryTJ please open a new issue.
