### ISSUE TITLE
LoadImages takes 10+ minutes on Virtualbox

### ISSUE THREAD

**Issue by ceeaspb** [kubernetes/minikube#7027] opened 2020-03-13 16:05 UTC
If you have several large images to cache then it can take 10-15 minutes to start minikube in virtualbox on Mac.
With hyperkit it LoadImages completes in seconds.

Virtualbox 5.2.32

```
😄  minikube v1.8.1 on Darwin 10.14.6
🔥  Creating virtualbox VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
...
I0313 14:36:27.918039    3404 ssh_runner.go:155] Checked if /var/lib/minikube/images/x exists, but got error: Process exited with status 1
I0313 14:36:28.020602    3404 ssh_runner.go:174] Transferring 315963904 bytes to /var/lib/minikube/images/busybox_1.31.1
I0313 14:36:28.039453    3404 ssh_runner.go:174] Transferring 315938304 bytes to /var/lib/minikube/images/b
I0313 14:36:28.039519    3404 ssh_runner.go:174] Transferring 153593856 bytes to /var/lib/minikube/images/c
I0313 14:36:28.173715    3404 ssh_runner.go:174] Transferring 842512384 bytes to /var/lib/minikube/images/d
I0313 14:36:31.500587    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/busybox_1.31.1: (4.452067681s)

I0313 14:36:31.500619    3404 cache_images.go:233] Transferred and loaded ~/.minikube/cache/images/busybox_1.31.1 from cache
I0313 14:36:32.239304    3404 ssh_runner.go:193] alpine_3.11.3: copied 3048448 bytes
I0313 14:36:32.815620    3404 docker.go:134] Loading image: /var/lib/minikube/images/alpine_3.11.3
I0313 14:36:32.815724    3404 ssh_runner.go:101] Run: docker load -i /var/lib/minikube/images/alpine_3.11.3
I0313 14:36:42.961286    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/alpine_3.11.3: (10.14596644s)
...
I0313 14:40:31.363699    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/a: (1m41.870551159s)
...
I0313 14:42:30.420590    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/docker-diffusion_6.4.2: (1m59.061752744s)
...
I0313 14:45:29.448213    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/cp-kafka_5.1.2: (2m59.035069167s)
...
I0313 14:45:31.655432    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/cp-zookeeper_5.1.2: (2.207166032s)
...
I0313 14:46:07.144068    3404 ssh_runner.go:141] Completed: docker load -i /var/lib/minikube/images/demos-kafka_kafka-connect-plugin-6.4.1: (35.489970419s)
I0313 14:46:07.144134    3404 cache_images.go:107] Successfully loaded all cached images
I0313 14:46:07.144141    3404 cache_images.go:78] LoadImages completed in 9m40.835089357s
```

Hyperkit:
```
I0313 16:00:57.959179    3898 cache_images.go:78] LoadImages completed in 1m12.691207197s
```

**Comment by afbjorklund** [comment] 2020-03-13 18:51
Seems like the Hyperkit log got truncated ? Was it the transferring that was faster there ?

**Comment by afbjorklund** [comment] 2020-03-13 21:59
Similar to issue #7031

**Comment by ceeaspb** [comment] 2020-03-14 09:00
> Seems like the Hyperkit log got truncated ? 

I only included the total time as the logs were the same except for faster times.

> Was it the transferring that was faster there ?

yes

**Comment by ceeaspb** [comment] 2020-03-14 11:23
I did a load of work investigating the file copy performance, but
I noticed that minikube has a shared folder to users, so the files are already available in the VM?
eg.
```
/usr/local/bin/VBoxManage sharedfolder add minikube --name Users --hostpath /Users --automount
```
Can the image load be short circuited? thanks

**Comment by afbjorklund** [comment] 2020-03-14 12:39
The vboxsf is only available for VirtualBox, but it could be interesting to measure differences between this file system and `cp` compared with the network interface and `scp`. Most likely this is some kind if bug with the virtuous driver though, so it would be great if you were able to test differences between different nic drivers ?

**Comment by ceeaspb** [comment] 2020-03-14 15:02
scp/network ~10mins
cp filesytem ~1min

```
# time find /Users/ceeaspb/.minikube/cache/images/ -type f |xargs -I {} cp {} /var/lib/minikube/images/

real	1m1.785s
user	0m0.069s
sys	0m40.743s
```
About 2GiB for the `cp` test as it just takes everything in cache/images.

I tested different nic drivers (https://www.virtualbox.org/manual/ch06.html) and found no material difference.

**Comment by tstromberg** [comment] 2020-03-18 18:51
I'm not quite sure what to do with this one.Do you mind checking with the latest release of VirtualBox?

Since the sharedfolder can be disabled, I'm not sure there is much we can do on the minikube side. 

Just curious - is there a reason for you to prefer virtualbox over the hyperkit driver?

**Comment by ceeaspb** [comment] 2020-03-18 20:53
Thanks, fair question, Virtualbox is more familiar to people and may already be installed therefore less friction.
hyperkit has become unresponsive at least a couple of times, and there are reports of "docker" high cpu unresponsive with hyperkit. So it is not without its own problems/risks.

I don't understand your comment on sharedfolder can be disabled - can you explain a little?

Given this appears to be a cpu issue in the VM we should ideally get some information on what that cpu is. I'd like to install `perf` into the VM. I am going down the route of building the iso, but if there is a quicker way or you have pre-canned steps as it's been done before that may avoid losing time on build/install issues.

**Comment by afbjorklund** [comment] 2020-03-18 21:09
We had other users report success with changing NIC type from "virtio" to "82540EM"

**Comment by afbjorklund** [comment] 2020-03-18 21:10
Normally you would use the `toolbox`, in order to run things (in a container) on the VM.

**Comment by ceeaspb** [comment] 2020-03-18 21:29
Thanks, `toolbox` looked promising but didn't work for me (possibly not using it right) as it's not running the same kernel as the VM-host - couldn't find the headers for linux 5.x(3?) - I don't have the exact logs to hand as I rebooted since.

I tested these nic types, with no improvement. Just to check are they the correct parameters to set?
```
#--nat-nic-type=82540EM --host-only-nic-type=82540EM
#--nat-nic-type=82545EM --host-only-nic-type=82545EM
#--nat-nic-type=82543GC --host-only-nic-type=82543GC
#--nat-nic-type=Am79C973 --host-only-nic-type=Am79C973
```

I looked at / tried nat nic tcp windows size, default 64, increased - no dice.
```
/usr/local/bin/VBoxManage showvminfo minikube --machinereadable
...
sockSnd="64"
sockRcv="64"
tcpWndSnd="64"
tcpWndRcv="64"
```

**Comment by afbjorklund** [comment] 2020-03-19 21:29
I guess the toolbox was mostly for running userspace tools, not so much for the kernel.
It's a bit weird that you are getting the host 5.x kernel in the virtualbox guest, though.

As long as the VM is re-created (as to actually pick up those changes), that should be it...
You can verify if it has taken effect with showvminfo, but I guess that it didn't help you then.

**Comment by tstromberg** [comment] 2020-04-19 19:34
This issue appears to be a duplicate of #7031, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-19 19:34 UTC
Labels: area/performance, co/virtualbox, priority/backlog, triage/support

**Comment by ceeaspb** [comment] 2020-04-27 08:21
Hi, here is a reproducer for additional information.

Dockerfile to reproduce a "large" docker image of a known size.
```
FROM debian:latest
RUN dd if=/dev/urandom of=data.out ibs=64M count=16 iflag=fullblock
CMD sleep infinity
```
Test start script
```
echo with Am79C973 network
minikube delete -p large-image-test
time minikube start --v=3 --alsologtostderr --kubernetes-version v1.17.3 --memory 8192 --cpus 4 -p large-image-test \
--nat-nic-type=Am79C973 --host-only-nic-type=Am79C973
echo  default network
minikube delete -p large-image-test
time minikube start --v=3 --alsologtostderr --kubernetes-version v1.17.3 --memory 8192 --cpus 4 -p large-image-test
```
