### ISSUE TITLE
minikube error

### ISSUE THREAD

**Issue by sarathchandrabhaskara** [kubernetes/minikube#4551] opened 2019-06-21 15:03 UTC
PS C:\Users\dell>  minikube start --vm-driver="hyperv" --hyperv-virtual-switch="Default Switch"
* minikube v1.1.1 on windows (amd64)
* Downloading Minikube ISO ...
 131.29 MB / 131.29 MB [============================================] 100.00% 0s
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0621 20:30:19.469462    3280 start.go:529] StartHost: create: precreate: Hyper-v commands have to be run as an Administrator

X Unable to start VM: create: precreate: Hyper-v commands have to be run as an Administrator

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment] 2019-06-24 05:26
Dupe of #4511

**Closed by tstromberg** 2019-06-24 05:26 UTC
