### ISSUE TITLE
minikube addons enable registry-creds Fails over version 1.15.1, 1.15.0

### ISSUE THREAD

**Issue by yossicohn** [kubernetes/minikube#9893] opened 2020-12-09 18:18 UTC
**Steps to reproduce the issue:** 

1. install Minikube  v1.15.1
2. `minikube addons enable registry-creds --alsologtostderr`
3. The command does not seem to finish, and the logs show an endless loop of error (see in Full output of failed command).
4. fix by rolling back to v1.14.2

**Full output of failed command:** 
`stderr:
error: error parsing /etc/kubernetes/addons/registry-creds-rc.yaml: error converting YAML to JSON: yaml: line 20: did not find expected key
I1209 18:23:26.320228   30270 ssh_runner.go:148] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/registry-creds-rc.yaml
W1209 18:23:26.485146   30270 addons.go:264] apply failed, will retry: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/registry-creds-rc.yaml: Process exited with status 1
`

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment] 2020-12-10 18:32
This issue appears to be a duplicate of #9722, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Comment by yossicohn-hs** [comment] 2020-12-13 07:20
@tstromberg sure, go ahead, I think this issue replicates itself over time.

**Comment by yossicohn-hs** [comment] 2020-12-13 07:21
Additional info:
The driver is not a factor, been using the default and hyperkit as well. the issue simulates in both cases.

**Closed** 2020-12-14 16:41 UTC
