### ISSUE TITLE
ingress timeout minikube 

### ISSUE THREAD

**Issue by moindev65** [kubernetes/minikube#12322] opened 2021-08-21 06:08 UTC
**Steps to reproduce the issue:** 

when I want to  enable ingress for minikube i face with below error
 Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by rdgacarvalho** [comment] 2021-08-23 09:37
I love minikube, however I am not using the ingress addon at all. 
I rather prefer to deploy my own ingress controller e.g: traefik, contour, nginx, skipper and etc.

Just install one of the one above via helm chart passing the --set externalIPs=$(minikube ip) paramenter. Update your /etc/hosts file with your minikube cluster ip + the dns_name and it is done.

**Comment by andriyDev** [comment] 2021-08-23 16:06
Duplicate of #10544. Working on it!

**Closed** 2021-08-23 16:15 UTC
Labels: triage/duplicate, addon/ingress
