### ISSUE TITLE
Minikube start with multi node failed with default name

### ISSUE THREAD

**Issue by azhao155** [kubernetes/minikube#9810] opened 2020-11-30 20:10 UTC
minikube start failed with multi nodes and default name, but it won't fail if i specify -p <name>

./out/minikube start -n 2 --alsologtostderr 

Please find the full log in the attachment. 
[output.txt](https://github.com/kubernetes/minikube/files/5618460/output.txt)

./out/minikube start -n 2 -p p1 works fine for me.

**Comment by azhao155** [comment] 2020-11-30 20:11
@medyagh 
@sharifelgamal

**Comment by sharifelgamal** [comment] 2020-11-30 20:18
Yeah I've seen this happen before, but I'm not sure what causes it. It's some sort of config corruption, which is usually fixed by `minikube delete --all --purge`. We should keep this open to investigate the root causes of this issue though.

**Comment by priyawadhwa** [comment] 2021-02-18 22:01
Still an issue in minikube 1.17

**Comment by medyagh** [comment] 2021-06-30 18:36
this seems to have been fixed

```
version_pkg ✓
$ ./out/minikube start -n 2
😄  minikube v1.21.0 on Darwin 11.4
✨  Automatically selected the docker driver. Other choices: hyperkit, parallels, virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.20.7 on Docker 20.10.7 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass

👍  Starting node minikube-m02 in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🌐  Found network options:
    ▪ NO_PROXY=192.168.49.2
🐳  Preparing Kubernetes v1.20.7 on Docker 20.10.7 ...
    ▪ env NO_PROXY=192.168.49.2
🔎  Verifying Kubernetes components...
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
14:35:30 medya/workspace/minikube
version_pkg ✓
$ kc get nodes -A
NAME           STATUS   ROLES                  AGE    VERSION
minikube       Ready    control-plane,master   114s   v1.20.7
minikube-m02   Ready    <none>                 46s    v1.20.7
14:36:13 medya/workspace/minikube
version_pkg ✓
$ mk profile list
|----------|-----------|---------|--------------|------|---------|---------|-------|
| Profile  | VM Driver | Runtime |      IP      | Port | Version | Status  | Nodes |
|----------|-----------|---------|--------------|------|---------|---------|-------|
| minikube | docker    | docker  | 192.168.49.2 | 8443 | v1.20.7 | Running |     2 |
|----------|-----------|---------|--------------|------|---------|---------|-------|
```

**Closed by medyagh** 2021-06-30 18:36 UTC
Labels: co/docker-driver, co/multinode, help wanted, kind/bug, lifecycle/rotten, priority/important-longterm
