### ISSUE TITLE
starthost failed: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'"

### ISSUE THREAD

**Issue by jetxu** [kubernetes/minikube#8394] opened 2020-06-06 03:50 UTC
Recently I start to use kubernetes, but it's tough for me to set working paltform, when I install minikube, I encounter below error after command minikube start, somebody help.

~$ minikube start
😄  minikube v1.11.0 on Ubuntu 20.04 (vbox/amd64)
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...
🤦  StartHost failed, but will try again: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

🔄  Restarting existing docker container for "minikube" ...
😿  Failed to start docker container. "minikube start" may fix it: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

💣  error provisioning host: Failed to start host: provision: get ssh host-port: get port 22 for "minikube": docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1
stdout:

stderr:
Template parsing error: template: :1:4: executing "" at <index (index .NetworkSettings.Ports "22/tcp") 0>: error calling index: index of untyped nil

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by afbjorklund** [comment] 2020-06-06 08:15
Can you try to delete it and start again, there is not enough information in the above log unfortunately

**Comment by priyawadhwa** [comment] 2020-08-12 18:57
Hey @jetxu this looks like a dupe of https://github.com/kubernetes/minikube/issues/8163 which was recently fixed. Could you trying with minikube v1.12.2 and see if that fixes your issue?

**Comment by medyagh** [comment] 2020-09-09 18:34
Hi @jetxu, I haven't heard back from you, I wonder if you still have this issue?
Regrettably, there isn't enough information in this issue to make it actionable, and a long enough duration has passed, so this issue is likely difficult to replicate. 

I will close this issue for now but please feel free to reopen whenever you feel ready to provide more information.

**Closed by medyagh** 2020-09-09 18:34 UTC
Labels: co/docker-driver, os/linux, triage/needs-information, triage/support
