### ISSUE TITLE
Minikube work from hard drive other than C: on windows

### ISSUE THREAD

**Issue by rmtmckenzie** [kubernetes/minikube#622] opened 2016-09-23 12:15 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
_BUG REPORT_

**Minikube version** (use `minikube version`): _v0.10.0_

**Environment**:
- **OS**: _Windows 10 64bit pro_
- **VM Driver**: _hyperv_
- **Docker version**: _1.12.1, build 23cf638_
- **Install tools**:
- **Others**:

**What happened**: 
_I tried running from a hard drive that wasn't C: as that's where do I most of my development_
_I got an error something like this half way through the startup process: Cannot find path /Users/...../.minikube/cache/iso/minikube-0.7.iso_
_I did check and the iso was at C:\Users\.....\....iso_

**What you expected to happen**: _the start command to work_

**How to reproduce it** (as minimally and precisely as possible): 
_Run minikube from a hard drive other than C:_

**Anything else do we need to know**:
_Work-around was simple, just run from C:. It took me a bit to realize what was going on though and it could definitely catch someone up._
_I did a quick scan through the source and it seems as though the problem can probably be traced back up to docker_machine but as I was trying to run minikube I thought it made more sense to open the bug here..._

**Comment by r2d4** [comment] 2016-09-23 17:32
possible dupe of #459

**Comment by dlorenc** [comment] 2016-09-23 17:40
Yeah, closing as a dup of that.

**Closed by dlorenc** 2016-09-23 17:40 UTC
Labels: kind/bug, platform/windows

**Comment by budhrg** [comment] 2017-09-13 06:08
@r2d4 @dlorenc , Is this issue of minikube start not working other than C: drive solved? 
If not, where are we tracking it? Seems like #459 is closed as well.
