### ISSUE TITLE
coredns一直CrashLoopBackOff，进虚拟机打印日志为空，在宿主机用kubectl打印日志报没有53端口权限

### ISSUE THREAD

**Issue by HuXinjing** [kubernetes/minikube#18999] opened 2024-06-01 09:36 UTC
-----------------------------------------------------------------------------------------------------------------------------
(base) [myname@localhost ~]# kubectl get pod -A
NAMESPACE     NAME                               READY   STATUS             RESTARTS         AGE
kube-system   coredns-7db6d8ff4d-9sggs           0/1     CrashLoopBackOff   17 (4m32s ago)   45m
kube-system   etcd-minikube                      1/1     Running            1 (31m ago)      45m
kube-system   kube-apiserver-minikube            1/1     Running            1 (31m ago)      45m
kube-system   kube-controller-manager-minikube   1/1     Running            1 (31m ago)      45m
kube-system   kube-proxy-7nqbx                   1/1     Running            1 (31m ago)      45m
kube-system   kube-scheduler-minikube            1/1     Running            1 (31m ago)      45m
kube-system   storage-provisioner                1/1     Running            3 (30m ago)      45m
-----------------------------------------------------------------------------------------------------------------------------
(base) [myname@localhost ~]# kubectl logs coredns-7db6d8ff4d-9sggs -n kube-system 
Listen: listen tcp :53: bind: permission denied
-----------------------------------------------------------------------------------------------------------------------------
(base) [lijiaxiang@localhost ~]# minikube ssh
docker@minikube:~$ docker ps |grep dns
794972ab8350   registry.k8s.io/pause:3.9   "/pause"                 38 minutes ago   Up 38 minutes             k8s_POD_coredns-7db6d8ff4d-9sggs_kube-system_33c33a6c-1200-4111-a103-a556f5fe5503_1
docker@minikube:~$ docker logs k8s_POD_coredns-7db6d8ff4d-9sggs_kube-system_33c33a6c-1200-4111-a103-a556f5fe5503_1
docker@minikube:~$

**重现问题所需的命令**：
(base) [myname@localhost ~]# kubectl get pod -A
(base) [myname@localhost ~]# kubectl logs coredns-7db6d8ff4d-9sggs -n kube-system 
(base) [lijiaxiang@localhost ~]# minikube ssh
docker@minikube:~$ docker ps |grep dns
docker@minikube:~$ docker logs k8s_POD_coredns-7db6d8ff4d-9sggs_kube-system_33c33a6c-1200-4111-a103-a556f5fe5503_1

**失败的命令的完整输出**：<details>
Listen: listen tcp :53: bind: permission denied

</details>

**`minikube logs`命令的输出**： <details>
没有logs

</details>

**使用的操作系统版本**：
centos 7

**Comment by medyagh** [comment] 2024-06-04 17:15
seems to be duplicate of https://github.com/kubernetes/minikube/issues/18950 closing this one, please track this issue 
https://github.com/kubernetes/minikube/issues/18950

**Closed by medyagh** 2024-06-04 17:15 UTC
Labels: l/zh-CN
