### ISSUE TITLE
Automatically create a PR to update kic-base when Dockerfile changes are merged

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9072] opened 2020-08-24 22:13 UTC
Automate PRs like this https://github.com/kubernetes/minikube/pull/9071

read @afbjorklund comment https://github.com/kubernetes/minikube/pull/9071#discussion_r476205846

**Comment by medyagh** [comment] 2021-02-08 20:51
The Bot should comment with new image and image sha for the contributor to update their code
and if the image build fails it should comment with with the logs from the image build failure

**Comment by sharifelgamal** [comment] 2021-02-09 22:06
The two issues are making sure we can trigger the jenkins job based on "ok-to-build-image" then figuring out why the docker build on the new kicbase dockerfile isn't working.

**Comment by sharifelgamal** [comment] 2021-02-10 17:17
The jenkins job is now triggering at the correct time, namely when a maintainer comments "ok-to-build-image", but the docker buildx command is failing where the docker build command isn't.

**Comment by sharifelgamal** [comment] 2021-02-10 17:25
```
------                                                                                                             
 > [linux/arm64  6/33] RUN echo "Ensuring scripts are executable ..."     && chmod +x /usr/local/bin/clean-install /usr/local/bin/entrypoint  && echo "Installing Packages ..."     && DEBIAN_FRONTEND=noninteractive clean-install       systemd       conntrack iptables iproute2 ethtool socat util-linux mount ebtables udev kmod       libseccomp2 pigz       bash ca-certificates curl rsync       nfs-common     && find /lib/systemd/system/sysinit.target.wants/ -name "systemd-tmpfiles-setup.service" -delete     && rm -f /lib/systemd/system/multi-user.target.wants/*     && rm -f /etc/systemd/system/*.wants/*     && rm -f /lib/systemd/system/local-fs.target.wants/*     && rm -f /lib/systemd/system/sockets.target.wants/*udev*     && rm -f /lib/systemd/system/sockets.target.wants/*initctl*     && rm -f /lib/systemd/system/basic.target.wants/*     && echo "ReadKMsg=no" >> /etc/systemd/journald.conf     && ln -s "$(which systemd)" /sbin/init  && echo "Ensuring /etc/kubernetes/manifests"     && mkdir -p /etc/kubernetes/manifests  && echo "Adjusting systemd-tmpfiles timer"     && sed -i /usr/lib/systemd/system/systemd-tmpfiles-clean.timer -e 's#OnBootSec=.*#OnBootSec=1min#'  && echo "Modifying /etc/nsswitch.conf to prefer hosts"     && sed -i /etc/nsswitch.conf -re 's#^(hosts:\s*).*#\1dns files#':
#11 0.176 Ensuring scripts are executable ...
#11 0.213 Installing Packages ...
#11 0.239 /bin/sh: 0: Can't open clean-install
```

Almost like the scripts aren't getting copied in correctly or something

**Comment by sharifelgamal** [comment] 2021-02-11 22:14
So, the scripts definitely exist in the image, the issue is when building the arm64 image. The error above is shell not being able to execute our package installation scripts. Changing that command to use bash instead of shell results in dpkg errors:
```
#10 24.58 Get:69 http://ports.ubuntu.com/ubuntu-ports focal/main arm64 socat arm64 1.7.3.3-2 [315 kB]
#10 25.56 debconf: delaying package configuration, since apt-utils is not installed
#10 25.68 Fetched 13.3 MB in 2s (6304 kB/s)
#10 25.77 Error while loading /usr/sbin/dpkg-split: No such file or directory
#10 25.77 Error while loading /usr/sbin/dpkg-deb: No such file or directory
#10 25.77 dpkg: error processing archive /tmp/apt-dpkg-install-Whh2wX/00-libapparmor1_2.13.3-7ubuntu5.1_arm64.deb (--unpack):
#10 25.77  dpkg-deb --control subprocess returned error exit status 1
```

**Comment by sharifelgamal** [comment] 2021-02-12 22:04
This was fixed by upgrading the machine we were building on from debian9 to debian10. This entire build process will be available once our jenkins infrastructure is back online.

**Comment by medyagh** [comment] 2021-02-26 21:40
done

**Closed** 2021-02-26 21:40 UTC
Labels: co/kic-base, kind/process, priority/important-longterm
