### ISSUE TITLE
none: [ERROR Port-2380]: Port 2380 is in use

### ISSUE THREAD

**Issue by Nit2879** [kubernetes/minikube#7156] opened 2020-03-23 10:57 UTC
**The exact command to reproduce the issue**:
minikube start --vm-driver=none
**The full output of the command that failed**:<details>
stderr:
W0323 06:56:07.655585   10307 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0323 06:56:07.655707   10307 validation.go:28] Cannot validate kubelet config - no validator is available
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Port-10250]: Port 10250 is in use
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

Ubuntu v18

**Comment by tstromberg** [comment] 2020-03-23 14:36
What is listening on port 2380? The output of `lsof -i :2380` would help.

It sounds like Kubernetes may already be running on this machine, but minikube is unaware of it's existence. Also, what version of minikube is this?

**Comment by tstromberg** [comment] 2020-03-25 18:34
This issue appears to be a duplicate of #6425, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-03-25 18:34 UTC
Labels: cause/port-conflict, co/none-driver, triage/support
