### ISSUE TITLE
Minikube Error

### ISSUE THREAD

**Issue by rohinidevops7** [kubernetes/minikube#14668] opened 2022-07-28 17:39 UTC
### What Happened?

* minikube v1.26.0 on Ubuntu 20.04
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 20.04.4 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
_**Failed to enable unit: Unit file cri-docker.socket does not exist.**_

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Attach the log file

root@ip-172-31-17-171:~# minikube start
* minikube v1.26.0 on Ubuntu 20.04
* Using the none driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing none bare metal machine for "minikube" ...
* OS release is Ubuntu 20.04.4 LTS

X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment] 2022-08-03 18:40
Duplicate of https://github.com/kubernetes/minikube/issues/14410, you need to install cri-dockerd (https://github.com/Mirantis/cri-dockerd#build-and-install)

https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503 has more in-depth about the issue.

**Closed by spowelljr** 2022-08-03 18:40 UTC
