### ISSUE TITLE
avoid re-download re-install hyperkit/hyperv drivers no minikube new version

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8775] opened 2020-07-20 18:30 UTC
if drivers didn't change, we shouldn't download a new one with only commit sha of the version change and make user enter their password each time.

**Comment by tstromberg** [comment] 2020-07-20 18:37
A simple alternative would be to simply encode the minimum hyperkit driver version.

AFAIK, the only drivers we download currently is hyperkit and kvm2, but we should probably extend this to vmware and parallels in the future.

**Comment by priyawadhwa** [comment] 2020-10-19 18:48
Closing as a dupe of https://github.com/kubernetes/minikube/issues/7422

**Closed by priyawadhwa** 2020-10-19 18:48 UTC
Labels: kind/process, priority/important-soon
