### ISSUE TITLE
Is there any prerequisite for executing 'make test' ?

### ISSUE THREAD

**Issue by anencore94** [kubernetes/minikube#8992] opened 2020-08-13 10:05 UTC
**Steps to reproduce the issue:** 

1. Trying to contribute
2. execute 'make test' in Makefile target
3. error occured in 'make lint' and 'make test'

**Full output of failed command:** 
```
MINIKUBE_LDFLAGS="-X k8s.io/minikube/pkg/version.version=v1.12.3 -X k8s.io/minikube/pkg/version.isoVersion=v1.12.2 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/pkg/version.gitCommitID="8655f1b958702e5ea3698877217635656a31267c" -X k8s.io/minikube/pkg/version.storageProvisionerVersion=v2" ./test.sh
= make lint =============================================================
WARN [runner] Can't run linter goanalysis_metalinter: S1030: failed prerequisites: [(inspect@k8s.io/minikube/cmd/drivers/kvm, isgenerated@k8s.io/minikube/cmd/drivers/kvm): analysis skipped: errors in package: [/home/kjy/git/minikube/cmd/drivers/kvm/main.go:26:2: could not import k8s.io/minikube/pkg/drivers/kvm (/home/kjy/git/minikube/pkg/drivers/kvm/domain.go:28:10: could not import github.com/libvirt/libvirt-go (/home/kjy/go/pkg/mod/github.com/libvirt/libvirt-go@v3.4.0+incompatible/callbacks.go:63:8: could not import C (cgo preprocessing failed)))]] 
WARN [runner] Can't run linter unused: buildir: failed to load package libvirt: could not load export data: no export data for "github.com/libvirt/libvirt-go" 
ERRO Running error: buildir: failed to load package libvirt: could not load export data: no export data for "github.com/libvirt/libvirt-go" 
Makefile:408: recipe for target 'lint-ci' failed
make[1]: *** [lint-ci] Error 3
= go mod ================================================================
ok
= boilerplate ===========================================================
ok
= schema_check ==========================================================
ok
= go test ===============================================================
# pkg-config --cflags  -- libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt libvirt
pkg-config: exec: "pkg-config": executable file not found in $PATH
ok  	k8s.io/minikube/cmd/minikube/cmd	3.295s	coverage: 18.7% of statements
ok  	k8s.io/minikube/cmd/minikube/cmd/config	0.180s	coverage: 21.5% of statements
ok  	k8s.io/minikube/pkg/addons	0.457s	coverage: 52.5% of statements
ok  	k8s.io/minikube/pkg/drivers	0.023s	coverage: 19.6% of statements
ok  	k8s.io/minikube/pkg/drivers/hyperkit	0.038s	coverage: 77.3% of statements
ok  	k8s.io/minikube/pkg/drivers/kic/oci	0.027s	coverage: 3.5% of statements
FAIL	k8s.io/minikube/pkg/drivers/kvm [build failed]
ok  	k8s.io/minikube/pkg/minikube/bootstrapper	0.504s	coverage: 55.7% of statements
ok  	k8s.io/minikube/pkg/minikube/bootstrapper/bsutil	0.113s	coverage: 62.4% of statements
ok  	k8s.io/minikube/pkg/minikube/bootstrapper/bsutil/ktmpl	0.025s	coverage: 100.0% of statements
ok  	k8s.io/minikube/pkg/minikube/bootstrapper/images	0.044s	coverage: 84.2% of statements
ok  	k8s.io/minikube/pkg/minikube/cluster	0.091s	coverage: 15.3% of statements
ok  	k8s.io/minikube/pkg/minikube/command	0.151s	coverage: 4.3% of statements
ok  	k8s.io/minikube/pkg/minikube/config	0.166s	coverage: 70.0% of statements
ok  	k8s.io/minikube/pkg/minikube/cruntime	0.017s	coverage: 36.7% of statements
ok  	k8s.io/minikube/pkg/minikube/docker	0.022s	coverage: 20.8% of statements
ok  	k8s.io/minikube/pkg/minikube/driver	0.013s	coverage: 33.9% of statements
ok  	k8s.io/minikube/pkg/minikube/extract	0.029s	coverage: 58.8% of statements
ok  	k8s.io/minikube/pkg/minikube/image	0.025s	coverage: 3.0% of statements
ok  	k8s.io/minikube/pkg/minikube/kubeconfig	0.338s	coverage: 77.0% of statements
ok  	k8s.io/minikube/pkg/minikube/localpath	0.002s	coverage: 43.8% of statements
ok  	k8s.io/minikube/pkg/minikube/logs	0.026s	coverage: 1.3% of statements
ok  	k8s.io/minikube/pkg/minikube/machine	1.591s	coverage: 39.5% of statements
ok  	k8s.io/minikube/pkg/minikube/mustload	0.026s	coverage: 10.5% of statements
ok  	k8s.io/minikube/pkg/minikube/notify	0.051s	coverage: 92.9% of statements
ok  	k8s.io/minikube/pkg/minikube/out	0.634s	coverage: 60.2% of statements
ok  	k8s.io/minikube/pkg/minikube/out/register	0.005s	coverage: 54.5% of statements
ok  	k8s.io/minikube/pkg/minikube/perf	4.474s	coverage: 33.8% of statements
ok  	k8s.io/minikube/pkg/minikube/problem	0.007s	coverage: 92.7% of statements
ok  	k8s.io/minikube/pkg/minikube/proxy	0.010s	coverage: 68.7% of statements
ok  	k8s.io/minikube/pkg/minikube/registry	0.042s	coverage: 75.5% of statements
ok  	k8s.io/minikube/pkg/minikube/service	0.023s	coverage: 84.2% of statements
ok  	k8s.io/minikube/pkg/minikube/shell	0.002s	coverage: 97.1% of statements
ok  	k8s.io/minikube/pkg/minikube/storageclass	0.100s	coverage: 100.0% of statements
ok  	k8s.io/minikube/pkg/minikube/sysinit	0.024s	coverage: 6.5% of statements
ok  	k8s.io/minikube/pkg/minikube/translate	0.008s	coverage: 10.5% of statements
ok  	k8s.io/minikube/pkg/minikube/tunnel	1.421s	coverage: 64.2% of statements
ok  	k8s.io/minikube/pkg/util	0.327s	coverage: 77.9% of statements
ok  	k8s.io/minikube/pkg/util/lock	0.003s	coverage: 18.2% of statements
ok  	k8s.io/minikube/pkg/util/retry	0.002s	coverage: 0.0% of statements
FAIL
Makefile:292: recipe for target 'test' failed
make: *** [test] Error 36
```

* my env info
  * ubuntu 18.04
  * go 1.14.4

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment] 2020-08-13 10:26
You need to install `libvirt-dev`, in order to build the libvirt ("kvm2") driver - which is unfortunately included in the main repository

#7794

**Comment by anencore94** [comment] 2020-08-13 10:37
Thanks :) It would be nice contributing docs have such prerequisites section written as #7794 !

**Comment by priyawadhwa** [comment] 2020-08-13 18:18
@anencore94 I totally agree that documentation around this would be great. I'm going to close this issue as a dupe of #7794 -- if you'd be interested in taking it on please let me know!

**Closed by priyawadhwa** 2020-08-13 18:18 UTC
Labels: kind/documentation
