### ISSUE TITLE
Minikube failing to start on v0.25.0 on Windows10 with Virtualbox

### ISSUE THREAD

**Issue by rayterrill** [kubernetes/minikube#2471] opened 2018-01-27 03:36 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT.

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.25.0
- **OS** (e.g. from /etc/os-release): Windows 10 (1709 16299.192)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): virtualbox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v0.25.1.iso
- **Install tools**:
- **Others**:

**What happened**:

Minikube fails to start.

```
PS C:\wip> ./minikube start --extra-config=apiserver.Authorization.Mode=RBAC
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
E0126 19:25:22.470270    1560 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: C:\Users\rayjo\.minikube\cache\localkube\localkube-v1.9.0: open C:\Users\rayjo\.minikube\cache\localkube\localkube-v1.9.0: The system cannot find the file specified.
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
y
```

**What you expected to happen**:

Minikube should start.

**How to reproduce it** (as minimally and precisely as possible):

minikube start

**Output of `minikube logs` (if applicable)**:

No entries.

**Anything else do we need to know**:

The directory C:\Users\rayjo\.minikube\cache\localkube\localkube-v1.9.0 referenced does not exist, and the C:\Users\rayjo\.minikube\cache\localkube directory is empty.

This exact same configuration (same OS version, same Virtualbox version) works without issue on v0.24.1 (I reverted back to v0.24.1 and I'm back to working).

**Comment by ex3ndr** [comment] 2018-01-27 08:48
Same here on MacOS

**Comment by mirkojahn** [comment] 2018-01-27 11:05
Same holds true for Windows 10 and Hyper-V

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by r2d4** [comment] 2018-01-27 19:55
Dupe of #2472, has been fixed

**Closed by r2d4** 2018-01-27 19:55 UTC

**Comment by rayterrill** [comment] 2018-01-27 21:08
Confirmed resolved in Win10. Thanks!
