### ISSUE TITLE
"minikube get-k8s-versions" does not include 1.9.6

### ISSUE THREAD

**Issue by podviaznikov** [kubernetes/minikube#3052] opened 2018-08-06 20:29 UTC
Bug report:

I can't use version k8s 1.9.6 with minikube 0.28.2(latest).
Because I can only have version 1.9.4 I see problem with `subpath` - https://github.com/kubernetes/minikube/issues/2642

**Environment**:

**Minikube version** (use `minikube version`):
- **OS** (e.g. from /etc/os-release): 0.28.2

<img width="729" alt="1__anton_podviaznikov_____zsh_" src="https://user-images.githubusercontent.com/429706/43739379-ab44e5ca-997c-11e8-8b93-89d1b40e8312.png">

**Comment by gtirloni** [comment] 2018-08-07 14:25
I don't remember what's the meaning of the [version list](https://github.com/kubernetes/minikube/commits/master/deploy/minikube/k8s_releases.json) (if it's only for supported releases that went through more testing) but you can try to specify 1.9.6 directly anyway and the bootstrapping code will figure out what to do:

```
$ minikube version
minikube version: v0.28.2

$ minikube start --kubernetes-version=v1.9.6
Starting local Kubernetes v1.9.6 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.9.6
Downloading kubelet v1.9.6
Finished Downloading kubelet v1.9.6
Finished Downloading kubeadm v1.9.6
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
Loading cached images from config file.

$ kubectl get node
NAME       STATUS    ROLES     AGE       VERSION
minikube   Ready     master    31s       v1.9.6
```

**Comment by afbjorklund** [comment] 2018-09-19 05:43
@tstromberg : this is not a bug, minikube didn't build localkube for 1.9.0 on purpose...
It was possible to build it yourself, but then you had to hack the version list: #2368

Since localkube is removed, this particular issue should probably be closed as well.

**Closed** 2018-09-19 21:04 UTC
Labels: kind/bug
