### ISSUE TITLE
minikube addons enable heapster does nothing

### ISSUE THREAD

**Issue by vromero** [kubernetes/minikube#1517] opened 2017-05-21 01:33 UTC
BUG REPORT

Brand new installation with:
- Ubuntu 17.04
- Docker 17.03.1-ce, build c6d412e
- kubectl : 
```
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersion:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.0", GitCommit:"fff5156092b56e6bd60fff75aad4dc9de6b6ef37", GitTreeState:"clean", BuildDate:"2017-05-09T23:19:49Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"linux/amd64"}
```
- minikube v0.19.0
- vmdriver: virtualbox

When I : 

```
minikube start
minikube addons enable heapster
sleep 600 # Just in case it takes time to download
minikube addons open heapster
```

I only get
```
minikube addons open heapster
Waiting, endpoint for service is not ready yet...
```

Instead of the browser I'm expecting.

```
root@victor-System-Product-Name:/home/victor/bin# kubectl get pods -w --all-namespaces
NAMESPACE   NAME                             READY     STATUS    RESTARTS   AGE
default     hello-minikube-938614450-5jrm0   1/1       Running   0          5m
default   loping-racoon-jenkins-1237124166-jsggx   1/1       Running   0         11m
kube-system   kube-addon-manager-minikube   1/1       Running   0         13m
kube-system   kube-dns-268032401-pcxtw   3/3       Running   0         13m
kube-system   kubernetes-dashboard-bhcmk   1/1       Running   0         13m
kube-system   tiller-deploy-1651596238-ppnvt   1/1       Running   0         12m
```

Notice the complete lack of `heapster-*` or `influxdb-grafana-*`. Network connectivity is fast, healthy and validated.

I've tried the same in MacOSX in a different computer with roughly same versions of dependencies with same results.

**Comment by vromero** [comment] 2017-05-21 01:41
Found this in the logs of `kube-addon-manager-minikube`

```
INFO: == Kubernetes addon reconcile completed at 2017-05-21T01:15:49+0000 ==
INFO: == Wait for addons to be spinned up at 2017-05-21T01:15:49+0000 ==
INFO: == Entering periodical apply loop at 2017-05-21T01:16:49+0000 ==
INFO: == Kubernetes addon ensure completed at 2017-05-21T01:16:50+0000 ==
INFO: == Reconciling with deprecated label ==
service "monitoring-grafana" created
Error from server (Invalid): error when creating "/etc/kubernetes/addons/heapster-rc.yaml": ReplicationController "heapster" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"heapster", "kubernetes.io/cluster-service":"true"}: `selector` does not match template `labels`
Error from server (Invalid): error when creating "/etc/kubernetes/addons/influxGrafana-rc.yaml": ReplicationController "influxdb-grafana" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"kubernetes.io/cluster-service":"true", "name":"influxGrafana"}: `selector` does not match template `labels`
service "heapster" created
service "monitoring-influxdb" created
INFO: == Reconciling with addon-manager label ==
INFO: == Kubernetes addon reconcile completed at 2017-05-21T01:16:50+0000 ==
INFO: == Kubernetes addon ensure completed at 2017-05-21T01:17:50+0000 ==
INFO: == Reconciling with deprecated label ==
Error from server (Invalid): error when creating "/etc/kubernetes/addons/heapster-rc.yaml": ReplicationController "heapster" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"k8s-app":"heapster", "kubernetes.io/cluster-service":"true"}: `selector` does not match template `labels`
Error from server (Invalid): error when creating "/etc/kubernetes/addons/influxGrafana-rc.yaml": ReplicationController "influxdb-grafana" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"kubernetes.io/cluster-service":"true", "name":"influxGrafana"}: `selector` does not match template `labels`
```

**Comment by vromero** [comment] 2017-05-21 01:49
Tried the very same thing just changing the minikube executable to 0.18 and it did work as expected.

**Comment by kvc-code** [comment] 2017-05-25 22:36
I found a different hack work-around:
```
(master) $ minikube ssh
$ sudo -s
$ cd /etc/kubernetes/addons/
$ vi heapster-rc.yaml
```
to `spec.template.metadata.labels` add another one `addonmanager.kubernetes.io/mode: Reconcile` making `.selector a subset of `.labels`.
Do the same thing for the file `influxGrafana-rc.yaml`.
Within a minute or two the errors will disappear from the logs as the retries can now succeed bringing up these pods.

This is not a satisfactory solution because it's ephemeral, you lose it when you bring down the minukube. But it is perhaps an illustrative clue as to where the real problem lies.

**Comment by kvc-code** [comment] 2017-05-25 22:52
Likely related to #1516 and #1513

**Comment by aaron-prindle** [comment] 2017-05-26 17:23
closing as dupe of #1516

**Closed by aaron-prindle** 2017-05-26 17:23 UTC
Labels: kind/bug
