### ISSUE TITLE
minikube - missing the Publisher Name on Windows

### ISSUE THREAD

**Issue by igorradovanov** [kubernetes/minikube#11710] opened 2021-06-21 08:09 UTC
The minikube installed via the Windows installer from the official source page found at https://minikube.sigs.k8s.io/docs/start/ is missing the **Publisher Name** which is causing Windows Defender to display a message that the app is not trusted and that it may put the PC at risk. This may be a blocker for new users who may want to try out minikube.

Screenshot: 
![image](https://user-images.githubusercontent.com/20539903/122728254-3a3e4500-d278-11eb-9179-7a0b14c41dd9.png)

minikube: **v1.21.0**
OS: **Windows 10 Version	10.0.19042 Build 19042**

**Comment by ilya-zuyev** [comment] 2021-06-21 17:42
@igorradovanov thanks for reporting this

**Comment by spowelljr** [comment] 2021-11-17 19:24
I believe this might be a duplicate of https://github.com/kubernetes/minikube/issues/4841

**Comment by spowelljr** [comment] 2021-11-17 19:27
I'm going to close this issue in favor of #4841, please follow along with the issue there, thanks!

**Closed by spowelljr** 2021-11-17 19:27 UTC
Labels: kind/bug, help wanted, os/windows, area/build-release, priority/important-longterm, lifecycle/frozen
