### ISSUE TITLE
Minikube not automatically added to PATH when using installer (Win7, PATH truncation?)

### ISSUE THREAD

**Issue by StarfallProjects** [kubernetes/minikube#3053] opened 2018-08-07 15:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

**Environment**: 

**Minikube version** (use `minikube version`): 0.28.2
- **OS** (e.g. from /etc/os-release): Windows 7
- **Install tools**: Windows installer

**What happened**:

I had not previously installed minikube.

I downloaded and ran the Windows installer (minikube-installer.exe)

The installer ran, and various files were added to C:\Program Files (x86)\Kubernetes\Minikube

minikube.exe was **not** added to my PATH.

**What you expected to happen**:

I expected minikube to be automatically added to my PATH, as per the installtion guide:

> Windows Installer [Experimental]
Download the minikube-installer.exe file, and execute the installer. This will automatically add minikube.exe to your path with an uninstaller available as well.

**How to reproduce it** (as minimally and precisely as possible):

Download and run the installer on Windows 7, for a fresh install.

**Comment by tstromberg** [comment] 2018-09-18 22:34
Possibly related: https://superuser.com/questions/387619/overcoming-the-1024-character-limit-with-setx

**Comment by tstromberg** [comment] 2018-09-19 21:01
@StarfallProjects - Do you mind sharing your current PATH value? I'm curious if truncation is coming into play for you.

**Comment by StarfallProjects** [comment] 2018-09-20 08:28
So I went and manually added it to get the thing working, so not sure if this is helpful - am a kubernetes noob. But this is everything in my PATH now:

C:\Users\Deborah\AppData\Local\Programs\Python\Python36-32\Scripts\;C:\Users\Deborah\AppData\Local\Programs\Python\Python36-32\;C:\Ruby24-x64\bin;C:\Users\Deborah\AppData\Local\GitHub\PortableGit_c7e0cbde92ba565cb218a521411d0e854079a28c\cmd\git.exe;C:\hugo\bin;C:\Progra~1\Java\jdk1.8.0_91;C:\Python27;C:\Users\Deborah\AppData\Local\Programs\Fiddler;C:\Program Files\Sublime Text 3;C:\PHP;C:\Users\Deborah\AppData\Roaming\Composer\vendor\bin;C:\SQLite;C:\Go;C:\Users\Deborah\Desktop\GoWorkspace\bin;C:\Program Files\Microsoft VS Code\bin;C:\Users\Deborah\AppData\Roaming\npm;C:\Program Files\Docker Toolbox;C:\Program Files\Java\jre1.8.0_151;C:\Program Files\Selenium\chromedriver.exe;C:\Program Files\MongoDB\Server\3.6\bin\;C:\Program Files\Maven\apache-maven-3.5.3\bin\;C:\MySQL\bin;C:\Users\Deborah\ngrok;C:\dep\bin;C:\Users\Deborah\AppData\Local\Programs\Python\Python36-32\Scripts;C:\kubeless;C:\Program Files (x86)\Kubernetes\Minikube;C:\Users\Deborah\AppData\Local\Yarn\bin;C:\Program Files\heroku\bin;C:\flutter\bin

Before I added it manually, it simply wasn't there at all (i.e. no part of C:\Program Files (x86)\Kubernetes\Minikube; got added)

**Comment by tstromberg** [comment] 2018-09-20 22:50
@StarfallProjects Thanks for sharing! It looks like your PATH is now 1021 characters, which may cause future breakage as the normal methods for updating environment variables are capped at 1024. 

Anways, this is a bug and we can do better here. Thanks for opening this issue!

**Comment by yarix** [comment] 2018-10-09 15:50
_FYI_ - I've encountered similar issue with `minikube-installer.exe v0.30.0` on `win10`.
after completing the installation, the PATH was not updated properly. instead of adding `C:\Program Files (x86)\Kubernetes\Minikube` to the PATH, it added just `C:\Prog`...
I've fixed the PATH manually and all works fine.

**Comment by tstromberg** [comment] 2019-01-24 18:01
Dupe of #2587

**Closed by tstromberg** 2019-01-24 18:01 UTC
Labels: good first issue, help wanted, kind/bug, os/windows, packaging/windows, priority/important-longterm

**Comment by kajariagrawal** [comment] 2020-04-09 08:03
Faced this issue on m windows 7. Again, path not added. I added it manually and it works now. My doubt is haven't they fixed it yet? the bug is reported a year back.

**Comment by Sweta-sweta** [comment] 2024-07-25 10:12
The term 'minikube' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the 
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ minikube start

I downloaded minikube.exe file and added it my systems path still this error is coming.
