### ISSUE TITLE
Following your instructions

### ISSUE THREAD

**Issue by Tonterias** [kubernetes/minikube#3954] opened 2019-03-25 09:38 UTC
usuario@DESKTOP-GTCQCAR /cygdrive/d/BasuraTemporal/Jhipster/jhipsterpress
$ minikube delete
x   Deleting "minikube" from virtualbox ...
-   The "minikube" cluster has been deleted.

usuario@DESKTOP-GTCQCAR /cygdrive/d/BasuraTemporal/Jhipster/jhipsterpress
$ minikube start
o   minikube v0.35.0 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
!   Unable to start VM: create: creating: open /OtherPrograms/cygwin64/home/usuario/.minikube/cache/iso/minikube-v0.35.0.iso: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

**Comment by afbjorklund** [comment] 2019-03-25 18:45
I think this is the problem when trying to run Minikube from the `D:\` partition...  (#1574)

**Comment by tstromberg** [comment] 2019-04-04 18:54
Closing as dupe of #1574

**Closed by tstromberg** 2019-04-04 18:54 UTC
Labels: os/windows
