### ISSUE TITLE
Issue with connecting to  Minikube VM

### ISSUE THREAD

**Issue by Lutando** [kubernetes/minikube#2012] opened 2017-09-27 09:39 UTC
**BUG REPORT**:

Please provide the following details:

**Environment**:

**Minikube version** : `v.0.22.2`
- **OS**: Windows 10 build `15063.608`
- **VM Driver**: HyperV

Virtual Switch

**What happened**:
`minikube start --vm-driver=hyperv --hyperv-virtual-switch=MinikubeNAT`
_and this was the output as expected_
```
Starting local Kubernetes v1.7.5 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.
```

after which I did the commands

`minikube dashboard` or `kubectl get po -all-namespaces`

**What you expected to happen**:
To get connect to the minikube dashboard or to get some cluster resource information

**Output of `minikube logs` (if applicable)**:

Here is console output

```
Could not find finalized endpoint being pointed to by kubernetes-dashboard: Error validating service: Error getting
ice kubernetes-dashboard: Get https://192.168.157.45:8443/api/v1/namespaces/kube-system/services/kubernetes-dashboa
ial tcp 192.168.157.45:8443: connectex: No connection could be made because the target machine actively refused it.
```

[Here is the pastebin of logs](https://pastebin.com/fbtRAYQf)

**Anything else do we need to know**:

[This is a screencap of my Virtual Switch Settings](https://i.imgur.com/FII5xhL.png)
I made the Virtual NAT and restarted my machine before doing any of this.

[I can also ping the web from within the minikube VM](https://i.imgur.com/WORvJQB.png)

I am quite new to this so I am just wondering what I am doing wrong.  Any help would be much appreciated

**Comment by bgehman** [comment] 2017-09-27 17:31
dupe of #1981 ?

**Comment by r2d4** [comment] 2017-09-28 17:48
Closing as a dupe of #1981

**Closed by r2d4** 2017-09-28 17:48 UTC
