### ISSUE TITLE
kvm2: Error defining domain xml: could not find capabilities for domaintype=kvm

### ISSUE THREAD

**Issue by VanitySoft** [kubernetes/minikube#4020] opened 2019-03-29 13:09 UTC
I followed these steps:
 https://www.server-world.info/en/note?os=CentOS_7&p=kubernetes&f=1

however, when attempting to start
using:  minikube start --vm-driver=kvm2

```
[twoen@k8smaster1 ~]$  minikube start --vm-driver=kvm2
o   minikube v1.0.0 on linux (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
>   Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...

!   Unable to start VM: create: Error creating machine: Error in driver during machine creation: creating domain: Error defining domain xml:
<domain type='kvm'>
  <name>minikube</name>
  <memory unit='MB'>2048</memory>
  <vcpu>2</vcpu>
  <features>
    <acpi/>
    <apic/>
    <pae/>

  </features>
  <cpu mode='host-passthrough'/>
  <os>
    <type>hvm</type>
    <boot dev='cdrom'/>
    <boot dev='hd'/>
    <bootmenu enable='no'/>
  </os>
  <devices>
    <disk type='file' device='cdrom'>
      <source file='/home/twoen/.minikube/machines/minikube/boot2docker.iso'/>
      <target dev='hdc' bus='scsi'/>
      <readonly/>
    </disk>
    <disk type='file' device='disk'>
      <driver name='qemu' type='raw' cache='default' io='threads' />
      <source file='/home/twoen/.minikube/machines/minikube/minikube.rawdisk'/>
      <target dev='hda' bus='virtio'/>
    </disk>
    <interface type='network'>
      <source network='default'/>
      <mac address='28:dd:8c:c3:65:7d'/>
      <model type='virtio'/>
    </interface>
    <interface type='network'>
      <source network='minikube-net'/>
      <mac address='2c:f7:69:07:e4:4e'/>
      <model type='virtio'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <rng model='virtio'>
      <backend model='random'>/dev/random</backend>
    </rng>

  </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:


```

I also noticed when doing a : kubectl version -o json  

i get 

```
{
  "clientVersion": {
    "major": "1",
    "minor": "14",
    "gitVersion": "v1.14.0",
    "gitCommit": "641856db18352033a0d96dbc99153fa3b27298e5",
    "gitTreeState": "clean",
    "buildDate": "2019-03-25T15:53:57Z",
    "goVersion": "go1.12.1",
    "compiler": "gc",
    "platform": "linux/amd64"
  }
}
The connection to the server localhost:8080 was refused - did you specify the right host or port?

**Comment by tstromberg** [comment] 2019-04-04 23:45
Thanks for the bug report! What happens if you run `virt-host-validate`?

**Comment by tstromberg** [comment] 2019-05-15 03:54
Dupe of #2991

**Closed by tstromberg** 2019-05-15 03:54 UTC
Labels: co/kvm2, priority/awaiting-more-evidence, triage/needs-information
