### ISSUE TITLE
 Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds

### ISSUE THREAD

**Issue by dileepdevops** [kubernetes/minikube#7154] opened 2020-03-23 04:21 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by priyawadhwa** [comment] 2020-03-25 17:37
Hey @dileepdevops -- I believe this issue is a duplicate of #7201, so I'm going to close this issue and consolidate there.

Could you also check  if this command-line from #6716 fixes it for you?

`minikube start --iso-url=http://storage.googleapis.com/minikube-builds/iso/HW_RANDOM_VIRTIO_7208.iso`

If not, please comment in #7201. Thank you!

**Closed by priyawadhwa** 2020-03-25 17:37 UTC
Labels: triage/support
