### ISSUE TITLE
hyper driver health: nil pointer 

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#8172] opened 2020-05-16 05:36 UTC
this nil pointer breaks minikube, so minikube wont be able to do checks for other drivers.
```
PS C:\Users\jenkins\Downloads> .\minikube-windows-amd64.exe start
* minikube v1.10.1 on Microsoft Windows Server 2019 Datacenter 10.0.17763 Build 17763
* Using the hyperv driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Creating hyperv VM (CPUs=2, Memory=6000MB, Disk=20000MB) ...
panic: runtime error: index out of range [0] with length 0

goroutine 132 [running]:
github.com/docker/machine/drivers/hyperv.hypervAvailable(0xc000398cc0, 0xc000258910)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/powershell.go:64 +0x105
github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc0003bf680, 0x0, 0x0)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/hyperv.go:171 +0x3b
k8s.io/minikube/pkg/minikube/machine.(*LocalClient).Create(0xc000351e00, 0xc0003bf6e0, 0x0, 0x0)
        /app/pkg/minikube/machine/client.go:221 +0x3f5
k8s.io/minikube/pkg/minikube/machine.timedCreateHost.func2(0x1e65f40, 0xc000351e00, 0xc0003bf6e0, 0xc000413720, 0xc00006e540)
        /app/pkg/minikube/machine/start.go:167 +0x42
created by k8s.io/minikube/pkg/minikube/machine.timedCreateHost
        /app/pkg/minikube/machine/start.go:166 +0x10e
PS C:\Users\jenkins\Downloads>
```

**Comment by tstromberg** [comment] 2020-05-26 17:23
Dupe of #2549

**Closed by tstromberg** 2020-05-26 17:23 UTC
Labels: kind/bug, priority/important-soon, triage/duplicate
