### ISSUE TITLE
wrong version string in kubernetes update notification

### ISSUE THREAD

**Issue by Valgard** [kubernetes/minikube#8123] opened 2020-05-13 11:58 UTC
if you start an existing minikube machine with an older kubernetes version you get an update notification with a hint to add the kubernetes-version parameter but in version string is missing the char v. If you than use the suggested parameter string you get a KUBERNETES_VERSION_MISSING_V error

**Steps to reproduce the issue:** 

1. minikube start
2. minikube start --kubernetes-version=1.18.2

**Full output of `minikube start` command:**
😄  [dedified] minikube v1.10.1 auf Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: **--kubernetes-version=1.18.2**
🆕  Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: **--kubernetes-version=1.18.2**
💿  Downloading VM boot image ...
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.10.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 22.49 MiB p/s 8s
👍  Starting control plane node dedified in cluster dedified
💾  Downloading Kubernetes v1.18.0 preload ...
    > preloaded-images-k8s-v3-v1.18.0-docker-overlay2-amd64.tar.lz4: 525.45 MiB
🔄  Restarting existing virtualbox VM for "dedified" ...
🐳  Vorbereiten von Kubernetes v1.18.0 auf Docker 19.03.8...
🌟  Enabled addons: default-storageclass, storage-provisioner
🏄  Done! kubectl is now configured to use "dedified"

**Full output of `minikube start --kubernetes-version=1.18.2` command:**
😄  [dedified] minikube v1.10.1 auf Ubuntu 18.04
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node dedified in cluster dedified
💾  Downloading Kubernetes v1.18.2 preload ...
    > preloaded-images-k8s-v3-v1.18.2-docker-overlay2-amd64.tar.lz4: 525.43 MiB
🔄  Restarting existing virtualbox VM for "dedified" ...
🐳  Vorbereiten von Kubernetes v1.18.2 auf Docker 19.03.8...
❌  Unable to load cached images: loading cached images: stat /home/valgard/.minikube/cache/images/k8s.gcr.io/kube-scheduler_v1.18.2: no such file or directory

❌  [KUBERNETES_VERSION_MISSING_V] Failed to update cluster updating node: generating kubeadm cfg: parsing Kubernetes version: strconv.ParseUint: parsing "": invalid syntax
💡  Suggestion: Check that your --kubernetes-version has a leading 'v'. For example: 'v1.1.14'

**Comment by afbjorklund** [comment] 2020-05-13 12:53
@Valgard : seems like the same issue as #8114 ?

**Comment by sharifelgamal** [comment] 2020-05-13 18:34
I'm going to close this as a duplicate of #8114

**Closed by sharifelgamal** 2020-05-13 18:34 UTC
Labels: triage/duplicate

**Comment by Valgard** [comment] 2020-05-13 19:29
Sorry, I probably used the wrong search terms before I created the ticket 🤪
