### ISSUE TITLE
Error parsing netrc file: permission denied

### ISSUE THREAD

**Issue by ymkarthik** [kubernetes/minikube#6113] opened 2019-12-18 11:14 UTC
minikube start
😄  minikube v1.6.1 on Ubuntu 16.04
✨  Automatically selected the 'virtualbox' driver (alternates: [none])
💿  Downloading VM boot image ...

💣  Failed to cache ISO: https://storage.googleapis.com/minikube/iso/minikube-v1.6.0.iso: invalid checksum: Error downloading checksum file: Error parsing netrc file at "/home/miracle/.netrc": open /home/miracle/.netrc: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by tstromberg** [comment] 2019-12-18 23:59
This issue appears to be a duplicate of #5643, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-18 23:59 UTC
