### ISSUE TITLE
Loading kicbase from cache to daemon outputs confusing loading progress

### ISSUE THREAD

**Issue by nagnampalli** [kubernetes/minikube#13509] opened 2022-01-28 10:36 UTC
### What Happened?

😄  minikube v1.25.1 on Darwin 11.6
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase: 0 B [___________________________] ?% ? p/s ?
    > gcr.io/k8s-minikube/kicbase: 0 B [___________________________] ?% ? p/s ?

### Attach the log file

😄  minikube v1.25.1 on Darwin 11.6
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
    > gcr.io/k8s-minikube/kicbase: 0 B [___________________________] ?% ? p/s ?
    > gcr.io/k8s-minikube/kicbase: 0 B [___________________________] ?% ? p/s ?

### Operating System

macOS (Default)

### Driver

Docker

**Comment by siikanen** [comment] 2022-02-23 13:24
Same issue here. Seems like there has been issues with minikube when it tries to connect to gcr.io. However seems the issue fixes itself by just waiting along

**Comment by floka94** [comment] 2022-03-03 13:36
Same issue here :-(

**Comment by siikanen** [comment] 2022-04-07 11:12
Usually just restarting minikube (or deleting it) couple of times fixes it. Defeneitly something related to minikube/docker(?) because   other applications seem to be functioning fine

**Comment by ckarageorgkaneen** [comment] 2022-04-12 17:24
I had the same issue with minikube v1.24.0. It was fixed after upgrading to v1.25.0. OS: Ubuntu 20.10

**Comment by spowelljr** [comment] 2022-05-18 18:39
@nagnampalli @siikanen @floka94 Can any of you confirm if updating to minikube v1.25.0 resolves this issue?

**Comment by ZCJ** [comment] 2022-06-26 15:35
@spowelljr I am on 1.26.0 and recently started seeing this issue 
![image](https://user-images.githubusercontent.com/1475845/175821860-19f67e6d-5029-44a2-979a-a7ffa68f8625.png)

**Comment by hemanthkotaprolu** [comment] 2022-08-25 05:18
Somebody help me here please!Did anyone able to get pass through this issue. Thanks

![Screenshot_20220825_104655](https://user-images.githubusercontent.com/92506047/186580856-1494bfc7-d7f6-44fe-9625-8be4d577e4a6.png)

**Comment by spowelljr** [comment] 2022-08-25 17:01
@hemanthkotaprolu it usually takes around 50 seconds for me, did it end up completing?

**Comment by afbjorklund** [comment] 2022-08-26 15:50
@spowelljr Currently the hack done by go-containerregistry only has network progress (and doesn't support podman)

https://github.com/google/go-containerregistry/blob/main/pkg/v1/tarball/write.go ("docker save", with progress)

https://github.com/google/go-containerregistry/blob/main/pkg/v1/daemon/write.go ("docker load", without progress)

I'm not sure they will fix it, so one workaround is to call the docker and podman clients directly instead of using `daemon`

**Comment by Nelgit007** [comment] 2022-10-04 22:11
> Somebody help me here please!Did anyone able to get pass through this issue. Thanks
> 
> ![Screenshot_20220825_104655](https://user-images.githubusercontent.com/92506047/186580856-1494bfc7-d7f6-44fe-9625-8be4d577e4a6.png)

Yeah. If its on windows like mine. You just have to wait a bit longer for it to begin pulling the image. 5 to 10min

**Comment by hemanthkotaprolu** [comment] 2022-10-09 13:34
> @hemanthkotaprolu it usually takes around 50 seconds for me, did it end up completing?

Thanks @spowelljr . After sometime it got worked. Thanks,

**Comment by emreigrek** [comment] 2022-12-09 11:11
took 2mins for me, thank you

**Comment by Elias-Yona** [comment] 2023-01-17 15:00
> took 2mins for me, thank you

20 mins for me. I almost deleted minikube.

**Comment by spowelljr** [comment] 2023-01-17 17:46
This is fixed by https://github.com/kubernetes/minikube/pull/15528

The problem is it was downloading the kicbase image twice.

**Closed by spowelljr** 2023-01-17 17:46 UTC
Labels: kind/bug, priority/backlog, co/kic-base
