### ISSUE TITLE
getting MAC address from UUID: vmnet: error from vmnet.framework: -1

### ISSUE THREAD

**Issue by anilsakr** [kubernetes/minikube#7673] opened 2020-04-15 04:27 UTC
anilreddy@Anils-MacBook-Air ~ % minikube start 
😄  minikube v1.9.0 on Darwin 10.15.4
✨  Using the hyperkit driver based on existing profile
🔄  Retarting existing hyperkit VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

🔄  Retarting existing hyperkit VM for "minikube" ...
❌  StartHost failed again: driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

👉  Run: "minikube delete", then "minikube start --alsologtostderr -v=1" to try again with more logging

E0415 09:52:48.660603     811 style.go:173] unable to parse "💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible\n": template: 💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible
:1: malformed character constant: 'minikube delete' - returning raw string.
💣  Unable to start VM after repeated tries. Please try {{'minikube delete' if possible
❌  Error: [HYPERKIT_VMNET_FRAMEWORK] driver start: getting MAC address from UUID: vmnet: error from vmnet.framework: -1

💡  Suggestion: Hyperkit networking is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6028
    ▪ https://github.com/kubernetes/minikube/issues/5594

**Comment by anilsakr** [comment] 2020-04-15 09:23
I removed the hyperkit from my mac 
and installed the VirtualBox

> minikube start --driver=virtualbox   

then it's working fine

**Comment by tstromberg** [comment] 2020-04-15 20:03
Did you try upgrading to the latest version of hyperkit?

Do you mind sharing the output of `hyperkit -version`?

**Comment by tstromberg** [comment] 2020-04-15 20:03
This issue appears to be a duplicate of #5594, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-15 20:03 UTC
Labels: co/hyperkit
