### ISSUE TITLE
none: docker info: panic: reflect: indirection through nil pointer to embedded struct

### ISSUE THREAD

**Issue by govinda1969** [kubernetes/minikube#10515] opened 2021-02-19 13:44 UTC
**Steps to reproduce the issue:** 

1.minikube start
2. 
3.

**Full output of failed command:** 

minikube v1.17.1 on Centos 8.3.2011
✨  Using the none driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing none bare metal machine for "minikube" ...
ℹ️  OS release is CentOS Linux 8
🐳  Preparing Kubernetes v1.20.2 on Docker  ...

❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: docker info --format : exit status 2
stdout:

stderr:
panic: reflect: indirection through nil pointer to embedded struct [recovered]
	panic: reflect: indirection through nil pointer to embedded struct

goroutine 1 [running]:
text/template.errRecover(0xc00056f2a8)
	/usr/local/go/src/text/template/exec.go:170 +0x1b5
panic(0x5623d108b0e0, 0x5623d13cc5a0)
	/usr/local/go/src/runtime/panic.go:679 +0x1b6
reflect.Value.FieldByIndex(0x5623d12443e0, 0xc0003de2c0, 0x99, 0xc0001943c0, 0x2, 0x2, 0x0, 0x5623d1483760, 0x5623d108b0e0)
	/usr/local/go/src/reflect/value.go:883 +0x39e
text/template.(*state).evalField(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0x7fffdc8ce371, 0xc, 0x5623d1454620, 0xc00036f500, 0xc00033e400, 0x1, ...)
	/usr/local/go/src/text/template/exec.go:605 +0x475
text/template.(*state).evalFieldChain(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0x5623d1454620, 0xc00036f500, 0xc00033e3f0, ...)
	/usr/local/go/src/text/template/exec.go:558 +0x222
text/template.(*state).evalFieldNode(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0xc00036f500, 0xc00033e400, 0x1, 0x1, 0x5623d1130060, 0x5623d2489668, ...)
	/usr/local/go/src/text/template/exec.go:522 +0x115
text/template.(*state).evalCommand(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0xc00036ef30, 0x5623d1130060, 0x5623d2489668, 0x99, 0xd0, 0x5623d1223fc0, ...)
	/usr/local/go/src/text/template/exec.go:460 +0x79c
text/template.(*state).evalPipeline(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0xc0002240c0, 0xc00010e038, 0xc0000c40d0, 0xc00056f0e0)
	/usr/local/go/src/text/template/exec.go:434 +0x11c
text/template.(*state).walk(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0x5623d14544a0, 0xc00036f620)
	/usr/local/go/src/text/template/exec.go:258 +0x49d
text/template.(*state).walk(0xc00056f228, 0x5623d12443e0, 0xc0003de2c0, 0x99, 0x5623d14546e0, 0xc00036eed0)
	/usr/local/go/src/text/template/exec.go:266 +0x144
text/template.(*Template).execute(0xc0003de040, 0x5623d13edf20, 0xc0001f3b00, 0x5623d12443e0, 0xc0003de2c0, 0x0, 0x0)
	/usr/local/go/src/text/template/exec.go:221 +0x20c
text/template.(*Template).Execute(...)
	/usr/local/go/src/text/template/exec.go:204
github.com/docker/cli/cli/command/system.formatInfo(0x5623d147e480, 0xc0003cc820, 0x0, 0xc0003a8300, 0x1, 0x1, 0xc0003dc320, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/docker/cli/cli/command/system/info.go:490 +0x1f5
github.com/docker/cli/cli/command/system.runInfo(0xc00041ab00, 0x5623d147e480, 0xc0003cc820, 0xc00032e790, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:87 +0x37c
github.com/docker/cli/cli/command/system.NewInfoCommand.func1(0xc00041ab00, 0xc00030a220, 0x0, 0x2, 0x0, 0x0)
	/go/src/github.com/docker/cli/cli/command/system/info.go:53 +0x48
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).execute(0xc00041ab00, 0xc000421750, 0x2, 0x2, 0xc00041ab00, 0xc000421750)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:850 +0x462
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0003da580, 0xc000421740, 0x3, 0x3)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:958 +0x34b
github.com/docker/cli/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/docker/cli/vendor/github.com/spf13/cobra/command.go:895
main.runDocker(0xc0003cc820, 0x5623d13f0540, 0xc000010020)
	/go/src/github.com/docker/cli/cmd/docker/docker.go:287 +0x1d3
main.main()
	/go/src/github.com/docker/cli/cmd/docker/docker.go:298 +0xf3

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment] 2021-02-19 15:11
Is docker running OK ? (`docker version`)

**Comment by afbjorklund** [comment] 2021-02-19 15:12
Similar to #10165

**Comment by tstromberg** [comment] 2021-03-24 19:17
Can you share the output of `docker version` and `docker info`?

**Comment by ilya-zuyev** [comment] 2021-04-28 18:28
Duplicate of https://github.com/kubernetes/minikube/issues/10588. Going to close this issue, please feel free to reopen it.

**Closed by ilya-zuyev** 2021-04-28 18:28 UTC
Labels: co/none-driver, kind/support, os/linux, triage/duplicate
