### ISSUE TITLE
various issues preventing minikube use on macOS

### ISSUE THREAD

**Issue by eliot1785** [kubernetes/minikube#3884] opened 2019-03-16 00:30 UTC
I have had several issues that are preventing me from using minikube on macOS. I'm new to Kubernetes and just following the Hello Minikube tutorial on the Kubernetes site.

Here are the steps I took, along with errors for each one as applicable:

1. Before I started this project, I installed Docker for Mac and VirtualBox because I was following the Docker tutorials.
2. Then I decided to install minikube, so I did it with `brew cask install minikube`. It installed properly, although I noticed that it couldn't install `kubectl` because I already had a copy (maybe from Docker for Mac?). I wasn't too happy about that because it was an earlier version, but I proceeded.
3. Then I ran `minikube start` and it was OK.
4. Then I ran `minikube dashboard` and I got a bunch of errors like "Temporary Error: unexpected response code: 503" so I couldn't launch the dashboard.
5. That led me to this StackOverflow question (https://stackoverflow.com/questions/52916548/minikube-dashboard-returns-503-error-on-macos). Deleting my minikube configuration didn't work (I got the same errors), so I decided to try the other idea (removing VirtualBox and installing hyperkit instead: `brew install docker-machine-driver-hyperkit`). (I ran into another issue w/ overlapping binaries when I did that: it was unable to overwrite Docker for Mac's `docker-machine` with my new one, but I ignored it).
6. Unfortunately that solution also does not work. I have been trying to start it with `minikube start --vm-driver=hyperkit`. The first time I tried that, I got a bunch of errors saying "Temporary Error: open /var/db/dhcpd_leases: no such file or directory." Then I ran `minikube delete` and tried again, and got a bunch of different errors saying "Temporary Error: Could not find an IP address for ee:f3:b0:c8:6f:10"

At this point I'm out of ideas and I don't want to make things even worse. Any idea how to proceed? I don't really care what hypervisor I use, I just want the simplest and most straightforward setup whatever that is (ideally such that I can continue to use both Docker and minikube on my Mac).

This is on macOS Mojave 10.14.3.

**Comment by afbjorklund** [comment] 2019-03-16 08:56
Seems like there are several different issues here, but this should probably be improved...

The IP vs MAC thing has a story: #3608 (for vbox, but anyway)

**Comment by tstromberg** [comment] 2019-04-04 18:45
The MAC issue is actually due to an obsolete and/or incompatible hyperkit driver. Here's a link to resolving the issue:

https://github.com/kubernetes/minikube/issues/1926#issuecomment-464296841

Marking this overall as a dupe of #3975 - as it has a clear action for resolving the hyperkit packaging headache.

**Closed by tstromberg** 2019-04-04 18:45 UTC
Labels: co/hyperkit, kind/documentation, os/macos, packaging
