### ISSUE TITLE
Unable to pull image from registry

### ISSUE THREAD

**Issue by kameshsampath** [kubernetes/minikube#4553] opened 2019-06-21 17:30 UTC
I have enabled the registry via `minikube addons enable registry`, I did build and push to `registry.kube-system.svc.cluster.local/example/demo` and when run the commmand `kubectl run demo --image=registry.kube-system.svc.cluster.local/example/demo` it fails with the error 

```1s          Warning   Failed                  pod/demo2-5c6b7dd5b5-r9dt6            Failed to pull image "registry.kube-system/rhdevelopers/pipeline-greeter:jvm": rpc error: code = Unknown desc = Error response from daemon: Get http://registry.kube-system/v2/: dial tcp: lookup registry.kube-system on 192.168.64.1:53: no such host```

I did also add the registry.kube-system to my minikube insecure registry like :

```
minikube start \
 --insecure-registry="10.0.0.0/24" \
 --insecure-registry="registry.kube-system.svc.cluster.local" \
 --insecure-registry="registry.kube-system.svc" \
 --insecure-registry="registry.kube-system" \
 --memory=8192 --cpus=6 --disk-size=50G \
 --extra-config=apiserver.enable-admission-plugins="LimitRanger,NamespaceExists,NamespaceLifecycle,ResourceQuota,ServiceAccount,DefaultStorageClass,MutatingAdmissionWebhook"
```
minikube version: minikube version: v1.1.1
OS: macOS Mojave

**Comment by Coderhypo** [comment] 2019-06-24 03:55
Hello, I suspect that there is a problem with dns，I am not sure if docker pull can use service name（I will check it later），

But you can use localhost as registry host，see：https://github.com/kubernetes/minikube/issues/4260

**Comment by kameshsampath** [comment] 2019-06-24 09:15
@Coderhypo - got a solution for it https://github.com/kameshsampath/minikube-helpers/tree/master/registry, its working. I am adding example for testing. 

Thoughts?

**Comment by Coderhypo** [comment] 2019-06-24 13:41
It seems that the solution is to bypass the dns by edit the hosts file.😀

**Comment by kameshsampath** [comment] 2019-06-24 13:44
yes, since its minikube and single vm its quite easy. But I hope this can work for multi nodes as etc host update is done via daemonset. But was thinking if its a good/viable solution how about adding it to minikube command or some thing like that

**Comment by Coderhypo** [comment] 2019-06-24 14:27
I got your point, but I think minikube is not a good choose for multi nodes cluster, kubeadm is better.

I think it‘s better to use host/vm ip as registry host for minikube，because we can push image outside the cluster. like this PR: https://github.com/kubernetes/minikube/pull/4539

**Comment by kameshsampath** [comment] 2019-06-24 14:30
how about adding some stuff from this approach to the PR ? Not sure how good it will be but just an idea.

**Comment by medyagh** [comment] 2019-06-25 20:26
I wonder if this is related to this https://github.com/kubernetes/minikube/issues/4547

**Comment by kameshsampath** [comment] 2019-06-26 04:26
@medyagh - how about us combining these issues and make a unified approach.  I was trying this in minikube v1.2.0 i see I get connection refused error to registry with both hyperkit and virtualbox. Wondering what could be issue.

**Comment by tstromberg** [comment] 2019-07-18 17:02
Marking as dupe of #4547

**Closed by tstromberg** 2019-07-18 17:02 UTC
