### ISSUE TITLE
failed to register layer: Error processing tar file(exit status 1): operation not supported , error: exit status 1

### ISSUE THREAD

**Issue by srinivasankr** [kubernetes/minikube#3803] opened 2019-03-06 09:35 UTC
If this is a bug report, please include:

- [ ] How to replicate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment] 2019-03-07 18:04
Do you mind including a bit more detail, such as the command-line used and the full output of the error? Thanks!

**Comment by tstromberg** [comment] 2019-03-08 17:31
Closing as dupe of #3786

**Closed by tstromberg** 2019-03-08 17:31 UTC
Labels: triage/needs-information
