### ISSUE TITLE
Issue while starting minikube

### ISSUE THREAD

**Issue by oman-kumar** [kubernetes/minikube#7614] opened 2020-04-11 06:46 UTC
**Steps to reproduce the issue:** 

1.C:\Kubernetes>minikube.exe start
* minikube v1.9.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Using the docker driver based on existing profile
* Starting control plane node m01 in cluster minikube
* Pulling base image ...
* docker "minikube" container is missing, will recreate.
* Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=2200MB (8075MB available) ...
! StartHost failed, but will try again: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: docker: Error response from daemon: Windows does not support privileged mode.
See 'docker run --help'.
: exit status 125
* docker "minikube" container is missing, will recreate.
* Creating Kubernetes in docker container with (CPUs=2) (4 available), Memory=2200MB (8075MB available) ...
*
X Failed to start docker container. "minikube start" may fix it.: recreate: creating host: create: creating: create kic node: create container: failed args: [run -d -t --privileged --security-opt seccomp=unconfined --tmpfs /tmp --tmpfs /run -v /lib/modules:/lib/modules:ro --hostname minikube --name minikube --label created_by.minikube.sigs.k8s.io=true --label name.minikube.sigs.k8s.io=minikube --label role.minikube.sigs.k8s.io= --label mode.minikube.sigs.k8s.io=minikube --volume minikube:/var --cpus=2 --memory=2200mb --expose 8443 --publish=127.0.0.1::8443 --publish=127.0.0.1::22 --publish=127.0.0.1::2376 gcr.io/k8s-minikube/kicbase:v0.0.8@sha256:2f3380ebf1bb0c75b0b47160fd4e61b7b8fef0f1f32f9def108d3eada50a7a81] output: docker: Error response from daemon: Windows does not support privileged mode.
See 'docker run --help'.
: exit status 125
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

2. 

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment] 2020-04-11 07:44
Same as #7352

**Comment by medyagh** [comment] 2020-04-15 19:28
this is a dupe of https://github.com/kubernetes/minikube/issues/7614 I will close this issue in order to track the infromation in same place

**Closed by medyagh** 2020-04-15 19:28 UTC
Labels: co/docker-driver, os/windows, triage/support
