### ISSUE TITLE
Can't stop minikube hyper-v VM

### ISSUE THREAD

**Issue by waynesi** [kubernetes/minikube#2944] opened 2018-06-28 13:35 UTC
**This is a BUG REPORT**:

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.28.0
- **OS** (e.g. from /etc/os-release): Windows 10 Pro 1709
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): Hyper-V
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): default
- **Install tools**: Portable binary
- **Others**:

**What happened**: 

I created the k8s cluster using the command 

`minikube start --vm-driver="hyperv" --hyperv-virtual-switch="minikube" --kubernetes-version="v1.9.4" --memory=4096`

It worked as expected - the VM was created and the cluster was up and running. 

Then I tried to shut down the cluster using 

`minikube stop`

The command was hang at 0% for ages and finally end up with the clash report. During the time of waiting, in the Hyper-V manager, I could see the status of the VM was changed to "Shutting down", but the CPU usage was quite low so it didn't look like doing anything. At the end I had to connect to the VM and use shutdown command to turn off the VM.

**What you expected to happen**:

The cluster should be shutdown as expected.

**How to reproduce it** (as minimally and precisely as possible):

Simply use the pair of "minikube start ..." and "minikube stop" with parameters as specified above.

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

Rolled back to v0.27.0 and deleted the VM and the %USERDATA%/.kube and .minikube folders to start from scratch. v0.27.0 just worked perfectly as expected.

**Comment by shahiddev** [comment] 2018-06-28 14:39
dupe of #2914

**Closed** 2018-06-28 14:45 UTC
