### ISSUE TITLE
minikube start --driver=qemu --network=builtin --memory=4Gb

### ISSUE THREAD

**Issue by mgthantzin** [kubernetes/minikube#18732] opened 2024-04-23 15:15 UTC
### What Happened?

❯ minikube start --driver qemu --network builtin --memory=4Gb
😄  minikube v1.33.0 on Darwin 14.4.1
✨  Using the qemu2 driver based on user configuration
❗  You are using the QEMU driver without a dedicated network, which doesn't support `minikube service` & `minikube tunnel` commands.
To try the dedicated network see: https://minikube.sigs.k8s.io/docs/drivers/qemu/#networking
💿  Downloading VM boot image ...
    > minikube-v1.33.0-amd64.iso....:  65 B / 65 B [---------] 100.00% ? p/s 0s
    > minikube-v1.33.0-amd64.iso:  314.16 MiB / 314.16 MiB  100.00% 10.72 MiB p
👍  Starting "minikube" primary control-plane node in "minikube" cluster
💾  Downloading Kubernetes v1.30.0 preload ...
    > preloaded-images-k8s-v18-v1...:  342.90 MiB / 342.90 MiB  100.00% 10.73 M
🔥  Creating qemu2 VM (CPUs=2, Memory=4096MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.30.0 on Docker 26.0.1 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
E0422 11:27:02.998606    7392 start.go:159] Unable to scale down deployment "coredns" in namespace "kube-system" to 1 replica: non-retryable failure while getting "coredns" deployment scale: Get "https://localhost:50875/apis/apps/v1/namespaces/kube-system/deployments/coredns/scale": dial tcp [::1]:50875: connect: connection refused
❗  Enabling 'default-storageclass' returned an error: running callbacks: [Error making standard the default storage class: Error listing StorageClasses: Get "https://localhost:50875/apis/storage.k8s.io/v1/storageclasses": dial tcp [::1]:50875: connect: connection refused]
🌟  Enabled addons: storage-provisioner

❌  Exiting due to GUEST_START: failed to start node: wait 6m0s for node: wait for healthy API server: apiserver healthz never reported healthy: context deadline exceeded

### Attach the log file

[logs.txt](https://github.com/kubernetes/minikube/files/15078938/logs.txt)

### Operating System

macOS (Default)

### Driver

QEMU

**Comment by spowelljr** [comment] 2024-07-03 19:22
We have a fix for this, going to close this as a duplicate of https://github.com/kubernetes/minikube/issues/19173 to centralize discussion, please follow there for updates, thank you!

**Closed by spowelljr** 2024-07-03 19:22 UTC
