### ISSUE TITLE
hyperv: waiting for apiserver: apiserver process never appeared

### ISSUE THREAD

**Issue by kvliet66** [kubernetes/minikube#6032] opened 2019-12-09 10:26 UTC
Starting minikube givers following error:

C:\WINDOWS\system32>minikube start
* minikube v1.5.2 on Microsoft Windows 10 Pro 10.0.18362 Build 18362
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing hyperv VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
* Relaunching Kubernetes using kubeadm ...
*
X Error restarting cluster: waiting for apiserver: apiserver process never appeared
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

LOGS:

C:\WINDOWS\system32>minikube logs
* ==> Docker <==
* -- Logs begin at Mon 2019-12-09 10:50:51 UTC, end at Mon 2019-12-09 12:32:04 UTC. --
* -- No entries --
*
* ==> container status <==
* time="2019-12-09T12:32:06Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
* CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES
*
* ==> dmesg <==
* [Dec 9 10:07] You have booted with nomodeset. This means your GPU drivers are DISABLED
* [  +0.000000] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
* [  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
* [  +0.074902] MDS CPU bug present and SMT on, data leak possible. See https://www.kernel.org/doc/html/latest/admin-guide/hw-vuln/mds.html for more details.
* [  +0.043611] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
* [  +0.012297] * Found PM-Timer Bug on the chipset. Due to workarounds for a bug,
*               * this clock source is slow. Consider trying other clock sources
* [Dec 9 10:09] Unstable clock detected, switching default tracing clock to "global"
*               If you want to keep using the local clock, then add:
*                 "trace_clock=local"
*               on the kernel command line
* [  +0.000051] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
* [  +0.426295] psmouse serio1: trackpoint: failed to get extended button data, assuming 3 buttons
* [  +2.467066] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
* [  +0.017539] systemd-fstab-generator[1207]: Ignoring "noauto" for root device
* [  +0.012081] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
* [  +0.000005] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
* [  +7.705488] vboxguest: loading out-of-tree module taints kernel.
* [  +0.005672] vboxguest: PCI device not found, probably running on physical hardware.
* [  +0.188080] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
* [ +20.940408] systemd-fstab-generator[2473]: Ignoring "noauto" for root device
* [Dec 9 10:10] systemd-fstab-generator[3123]: Ignoring "noauto" for root device
* [Dec 9 10:11] NFSD: Unable to end grace period: -110
* [Dec 9 10:18] hrtimer: interrupt took 4427348 ns
*
* ==> kernel <==
*  12:32:06 up  2:24,  0 users,  load average: 0.12, 0.21, 0.19
* Linux minikube 4.19.76 #1 SMP Tue Oct 29 14:56:42 PDT 2019 x86_64 GNU/Linux
* PRETTY_NAME="Buildroot 2019.02.6"
*
* ==> kubelet <==
* -- Logs begin at Mon 2019-12-09 10:50:51 UTC, end at Mon 2019-12-09 12:32:06 UTC. --
* Dec 09 12:32:03 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 09 12:32:03 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10637.
* Dec 09 12:32:03 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:03 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:03 minikube kubelet[30048]: F1209 12:32:03.455867   30048 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Dec 09 12:32:03 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Dec 09 12:32:03 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 09 12:32:04 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 09 12:32:04 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10638.
* Dec 09 12:32:04 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:04 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:04 minikube kubelet[30105]: F1209 12:32:04.378018   30105 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Dec 09 12:32:04 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Dec 09 12:32:04 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10639.
* Dec 09 12:32:05 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:05 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30148]: F1209 12:32:05.141627   30148 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10640.
* Dec 09 12:32:05 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:05 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Dec 09 12:32:05 minikube kubelet[30157]: F1209 12:32:05.912963   30157 server.go:196] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
* Dec 09 12:32:05 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
* Dec 09 12:32:06 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
* Dec 09 12:32:06 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 10641.
* Dec 09 12:32:06 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Dec 09 12:32:06 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.

**Comment by tstromberg** [comment] 2019-12-16 20:41
I believe we fixed this with #5916 which was merged into minikube v1.6. Do you mind checking with the most recent release?

**Comment by tstromberg** [comment] 2019-12-16 20:48
This issue appears to be a duplicate of #5905, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-16 20:48 UTC
Labels: co/apiserver, triage/needs-information, triage/support

**Comment by kvliet66** [comment] 2019-12-17 09:37
Hi Thomas, I tried and it indeed solved the issue.
Thanks
