### ISSUE TITLE
Delete on failure not working

### ISSUE THREAD

**Issue by vincentjocodes** [kubernetes/minikube#9372] opened 2020-10-01 22:03 UTC
**Steps to reproduce the issue:** 

1. Turn off Docker
2. Run `minikube start --delete-on-failure`
3. See errors but does not delete on failure

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

```
> minikube start --delete-on-failure
😄  minikube v1.13.1 on Darwin 10.15.6
🆕  Kubernetes 1.19.2 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.19.2
✨  Using the docker driver based on existing profile

💣  Exiting due to PROVIDER_DOCKER_NOT_RUNNING: "docker version --format -" exit status 1: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
💡  Suggestion: Start the Docker service
📘  Documentation: https://minikube.sigs.k8s.io/docs/drivers/docker/
```

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by vincentjocodes** [comment] 2020-10-08 15:59
@priyawadhwa Oh I see, so it's all to do with clusters? We expected to delete the profile since if the profile has a cluster it will delete the profile as well, is that correct?

**Comment by priyawadhwa** [comment] 2020-10-08 16:32
So my understanding is that `--delete-on-failure` will delete the cluster if `minikube start` fails, but only if the cluster is brand new. @sharifelgamal can you confirm?

**Comment by priyawadhwa** [comment] 2020-10-08 16:33
@vincentjocodes if you just want to delete the profile, then `minikube delete -p <profile name>` should work even if docker isn't running.

**Comment by medyagh** [comment] 2020-11-11 19:37
I will close this issue as a dupe of https://github.com/kubernetes/minikube/issues/9372
please feel free to add more details to that other issue.
we need to fix this

**Closed by medyagh** 2020-11-11 19:37 UTC
Labels: kind/support
