### ISSUE TITLE
Unable to read client-cert c:\.kube....

### ISSUE THREAD

**Issue by tmcginnisg** [kubernetes/minikube#4232] opened 2019-05-09 13:33 UTC
**The exact command to reproduce the issue**:
C:\Users\tmcginnis>set HOMEDRIVE=C:

C:\Users\tmcginnis>set MINIKUBE_HOME=\Users\tmcginnis\.minikube

C:\Users\tmcginnis>\bin\minikube start -p tim

**The full output of the command that failed**:
-   Pulling images required by Kubernetes v1.14.1 ...
X   Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /v
ar/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.1": output: Error response from daemon: Get https://k8s.gcr.io/v2/: x509: certificate signed by unknown authority
, error: exit status 1
: Process exited with status 1
-   Launching Kubernetes v1.14.1 using kubeadm ...
:   Waiting for pods:
!   Error starting cluster: wait: k8s client: Error creating kubeConfig: invalid configuration: [unable to read client-cert C:\.kube\Users\tmcginnis\.minikube\client.crt for tim du
e to open C:\.kube\Users\tmcginnis\.minikube\client.crt: The system cannot find the path specified., unable to read client-key C:\.kube\Users\tmcginnis\.minikube\client.key for tim
 due to open C:\.kube\Users\tmcginnis\.minikube\client.key: The system cannot find the path specified., unable to read certificate-authority C:\.kube\Users\tmcginnis\.minikube\ca.c
rt for tim due to open C:\.kube\Users\tmcginnis\.minikube\ca.crt: The system cannot find the path specified.]

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

C:\Users\tmcginnis>

**The output of the `minikube logs` command**:
C:\Users\tmcginnis>minikube logs

!   Error getting config: FindFirstFile \Users\tmcginnis\.minikube\profiles\minikube\config.json: The system cannot find the path specified.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

C:\Users\tmcginnis>

**The operating system version**:
Windows 7 Enterprise Service Pack 1

**Comment by tstromberg** [comment] 2019-05-16 19:03
Duplicate of #4053

**Closed by tstromberg** 2019-05-16 19:03 UTC
Labels: os/windows
