### ISSUE TITLE
the installation part of the web doc is missing

### ISSUE THREAD

**Issue by praisethejack** [kubernetes/minikube#9956] opened 2020-12-14 06:35 UTC
The installation portion of the web page documentation(https://minikube.sigs.k8s.io/docs/start/) is missing.
This confused me
Am I looking in the wrong place, or is there something really wrong?

**Comment by afbjorklund** [comment] 2020-12-14 07:00
Duplicate of #9835 (unfortunately)

**Comment by tstromberg** [comment] 2020-12-14 16:27
@praisethejack - I'm not sure what browser you are on - but could you please open up the browser's "Web Developer" console, reload the page, and cut and paste any errors you see here? Thanks!

**Closed** 2020-12-21 18:59 UTC
Labels: kind/documentation, kind/support, triage/duplicate
