### ISSUE TITLE
'start' fails silently when provided an invalid version to deploy

### ISSUE THREAD

**Issue by marun** [kubernetes/minikube#643] opened 2016-09-29 20:59 UTC
**Minikube version**: v0.10.0

**Environment**:
- **OS**: centos 7.2.1511
- **VM Driver**: kvm
- **Docker version**: 1.11.1

**What happened**:
Attempted to start a 1.4.0 cluster with ``minikube start --kubernetes-version=1.4.0``.  Command completed successfully but ``kubectl version`` was unable to connect to the configured server.  Ran ``docker ps`` on the minikube vm and it returned an empty list.  Checked ``minikube get-k8s-versions`` and realized 1.4.0 is not yet supported (only v1.4.0-beta.10).

**What you expected to happen**:

I expected ``minikube start`` to detect when deployment failed due to the specified version being invalid.

**Comment by r2d4** [comment] 2016-09-29 21:06
Thanks for the detailed report.

This is a dupe of #634

Additionally, kubernetes v1.4.0 is supported and I have now pushed the latest json file to reflect this. This was merged in with this https://github.com/kubernetes/minikube/pull/635.

Now you should see it reflected correctly

```
-> minikube get-k8s-versions
The following Kubernetes versions are available: 
	- v1.4.0
	- v1.3.7
	- v1.3.6
	- v1.3.5
	- v1.3.4
	- v1.3.3
	- v1.3.0
```

**Closed by r2d4** 2016-09-29 21:06 UTC
Labels: kind/bug
