### ISSUE TITLE
minikube start: crictl commands following containerd initialization almost always fail

### ISSUE THREAD

**Issue by kitt1987** [kubernetes/minikube#10650] opened 2021-02-28 18:17 UTC
**Steps to reproduce the issue:** 

1. Prepare an available but stopped minikube cluster w/ driver hyperkit and runtime containerd.
2. Start the cluster via command `minikube start -p containerd --preload=false --cache-images=false --alsologtostderr`. 

Since every required image exists in the data disk, our cluster should start normally. But it didn't. Even with preload enabled, it may also run into `Loading image from cache` because the command `sudo crictl images --output json` fails.

**Full output of failed command:** 

This is the most important part of the output. If necessary, I can also provide the whole text.

```
0301 01:05:42.706140   48881 ssh_runner.go:189] Completed: systemctl --version: (2.036989905s)
I0301 01:05:42.706172   48881 preload.go:97] Checking if preload exists for k8s version v1.20.0 and runtime containerd
W0301 01:05:42.706243   48881 out.go:181] ❗  This VM is having trouble accessing https://k8s.gcr.io
❗  This VM is having trouble accessing https://k8s.gcr.io
W0301 01:05:42.706300   48881 out.go:181] 💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
I0301 01:05:42.706376   48881 ssh_runner.go:149] Run: sudo systemctl is-active --quiet service crio
I0301 01:05:42.716008   48881 ssh_runner.go:149] Run: sudo systemctl stop -f crio
I0301 01:05:42.755552   48881 ssh_runner.go:149] Run: sudo systemctl is-active --quiet service crio
I0301 01:05:42.762077   48881 ssh_runner.go:149] Run: sudo systemctl is-active --quiet service docker
I0301 01:05:42.768392   48881 ssh_runner.go:149] Run: /bin/bash -c "sudo mkdir -p /etc && printf %s "runtime-endpoint: unix:///run/containerd/containerd.sock
image-endpoint: unix:///run/containerd/containerd.sock
" | sudo tee /etc/crictl.yaml"
I0301 01:05:42.777115   48881 ssh_runner.go:149] Run: /bin/bash -c "sudo mkdir -p /etc/containerd && printf %s "cm9vdCA9ICIvdmFyL2xpYi9jb250YWluZXJkIgpzdGF0ZSA9ICIvcnVuL2NvbnRhaW5lcmQiCm9vbV9zY29yZSA9IDAKCltncnBjXQogIGFkZHJlc3MgPSAiL3J1bi9jb250YWluZXJkL2NvbnRhaW5lcmQuc29jayIKICB1aWQgPSAwCiAgZ2lkID0gMAogIG1heF9yZWN2X21lc3NhZ2Vfc2l6ZSA9IDE2Nzc3MjE2CiAgbWF4X3NlbmRfbWVzc2FnZV9zaXplID0gMTY3NzcyMTYKCltkZWJ1Z10KICBhZGRyZXNzID0gIiIKICB1aWQgPSAwCiAgZ2lkID0gMAogIGxldmVsID0gIiIKClttZXRyaWNzXQogIGFkZHJlc3MgPSAiIgogIGdycGNfaGlzdG9ncmFtID0gZmFsc2UKCltjZ3JvdXBdCiAgcGF0aCA9ICIiCgpbcGx1Z2luc10KICBbcGx1Z2lucy5jZ3JvdXBzXQogICAgbm9fcHJvbWV0aGV1cyA9IGZhbHNlCiAgW3BsdWdpbnMuY3JpXQogICAgc3RyZWFtX3NlcnZlcl9hZGRyZXNzID0gIiIKICAgIHN0cmVhbV9zZXJ2ZXJfcG9ydCA9ICIxMDAxMCIKICAgIGVuYWJsZV9zZWxpbnV4ID0gZmFsc2UKICAgIHNhbmRib3hfaW1hZ2UgPSAiazhzLmdjci5pby9wYXVzZTozLjIiCiAgICBzdGF0c19jb2xsZWN0X3BlcmlvZCA9IDEwCiAgICBzeXN0ZW1kX2Nncm91cCA9IGZhbHNlCiAgICBlbmFibGVfdGxzX3N0cmVhbWluZyA9IGZhbHNlCiAgICBtYXhfY29udGFpbmVyX2xvZ19saW5lX3NpemUgPSAxNjM4NAogICAgW3BsdWdpbnMuY3JpLmNvbnRhaW5lcmRdCiAgICAgIHNuYXBzaG90dGVyID0gIm92ZXJsYXlmcyIKICAgICAgbm9fcGl2b3QgPSB0cnVlCiAgICAgIFtwbHVnaW5zLmNyaS5jb250YWluZXJkLmRlZmF1bHRfcnVudGltZV0KICAgICAgICBydW50aW1lX3R5cGUgPSAiaW8uY29udGFpbmVyZC5ydW50aW1lLnYxLmxpbnV4IgogICAgICAgIHJ1bnRpbWVfZW5naW5lID0gIiIKICAgICAgICBydW50aW1lX3Jvb3QgPSAiIgogICAgICBbcGx1Z2lucy5jcmkuY29udGFpbmVyZC51bnRydXN0ZWRfd29ya2xvYWRfcnVudGltZV0KICAgICAgICBydW50aW1lX3R5cGUgPSAiIgogICAgICAgIHJ1bnRpbWVfZW5naW5lID0gIiIKICAgICAgICBydW50aW1lX3Jvb3QgPSAiIgogICAgW3BsdWdpbnMuY3JpLmNuaV0KICAgICAgYmluX2RpciA9ICIvb3B0L2NuaS9iaW4iCiAgICAgIGNvbmZfZGlyID0gIi9ldGMvY25pL25ldC5kIgogICAgICBjb25mX3RlbXBsYXRlID0gIiIKICAgIFtwbHVnaW5zLmNyaS5yZWdpc3RyeV0KICAgICAgW3BsdWdpbnMuY3JpLnJlZ2lzdHJ5Lm1pcnJvcnNdCiAgICAgICAgW3BsdWdpbnMuY3JpLnJlZ2lzdHJ5Lm1pcnJvcnMuImRvY2tlci5pbyJdCiAgICAgICAgICBlbmRwb2ludCA9IFsiaHR0cHM6Ly9yZWdpc3RyeS0xLmRvY2tlci5pbyJdCiAgW3BsdWdpbnMuZGlmZi1zZXJ2aWNlXQogICAgZGVmYXVsdCA9IFsid2Fsa2luZyJdCiAgW3BsdWdpbnMubGludXhdCiAgICBzaGltID0gImNvbnRhaW5lcmQtc2hpbSIKICAgIHJ1bnRpbWUgPSAicnVuYyIKICAgIHJ1bnRpbWVfcm9vdCA9ICIiCiAgICBub19zaGltID0gZmFsc2UKICAgIHNoaW1fZGVidWcgPSBmYWxzZQogIFtwbHVnaW5zLnNjaGVkdWxlcl0KICAgIHBhdXNlX3RocmVzaG9sZCA9IDAuMDIKICAgIGRlbGV0aW9uX3RocmVzaG9sZCA9IDAKICAgIG11dGF0aW9uX3RocmVzaG9sZCA9IDEwMAogICAgc2NoZWR1bGVfZGVsYXkgPSAiMHMiCiAgICBzdGFydHVwX2RlbGF5ID0gIjEwMG1zIgo=" | base64 -d | sudo tee /etc/containerd/config.toml"
I0301 01:05:42.786252   48881 ssh_runner.go:149] Run: sudo sysctl net.bridge.bridge-nf-call-iptables
I0301 01:05:42.790431   48881 crio.go:119] couldn't verify netfilter by "sudo sysctl net.bridge.bridge-nf-call-iptables" which might be okay. error: sudo sysctl net.bridge.bridge-nf-call-iptables: Process exited with status 255
stdout:

stderr:
sysctl: cannot stat /proc/sys/net/bridge/bridge-nf-call-iptables: No such file or directory
I0301 01:05:42.790533   48881 ssh_runner.go:149] Run: sudo modprobe br_netfilter
I0301 01:05:42.799771   48881 ssh_runner.go:149] Run: sudo sh -c "echo 1 > /proc/sys/net/ipv4/ip_forward"
I0301 01:05:42.803963   48881 ssh_runner.go:149] Run: sudo systemctl daemon-reload
I0301 01:05:42.889708   48881 ssh_runner.go:149] Run: sudo systemctl restart containerd
I0301 01:05:42.918126   48881 ssh_runner.go:149] Run: containerd --version
I0301 01:05:43.049777   48881 out.go:119] 📦  Preparing Kubernetes v1.20.0 on containerd 1.4.3 ...
📦  Preparing Kubernetes v1.20.0 on containerd 1.4.3 ...
I0301 01:05:43.049948   48881 ssh_runner.go:149] Run: grep 192.168.64.1	host.minikube.internal$ /etc/hosts
I0301 01:05:43.052496   48881 ssh_runner.go:149] Run: /bin/bash -c "{ grep -v '\thost.minikube.internal$' /etc/hosts; echo "192.168.64.1	host.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts"
I0301 01:05:43.060154   48881 preload.go:97] Checking if preload exists for k8s version v1.20.0 and runtime containerd
I0301 01:05:43.060267   48881 ssh_runner.go:149] Run: sudo crictl info
I0301 01:05:43.126588   48881 out.go:119]

W0301 01:05:43.126725   48881 out.go:181] ❌  Exiting due to K8S_INSTALL_FAILED: updating control plane: generating kubeadm cfg: getting cgroup driver: get cri info: sudo crictl info: Process exited with status 1
stdout:

stderr:
```

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by krezovic** [comment] 2021-03-02 17:41
Looks like a duplicate of https://github.com/kubernetes/minikube/issues/10355 which isn't still properly fixed.

**Comment by ilya-zuyev** [comment] 2021-03-03 18:58
Duplicate

**Closed** 2021-03-03 18:58 UTC
