### ISSUE TITLE
localkube SIGSEGV 

### ISSUE THREAD

**Issue by Aleishus** [kubernetes/minikube#1960] opened 2017-09-14 04:04 UTC
os : 
    Static hostname: VM_140_42_centos
         Icon name: computer-vm
           Chassis: vm
        Machine ID: 8d13a50988cc5c4972347415eddf7d47
           Boot ID: 980d7d5154bb4cc4b8653fd601e9af97
    Virtualization: kvm
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 4.4.86-1.el7.elrepo.x86_64
      Architecture: x86-64
version:
       minikube version
minikube version: v0.22.1

/usr/local/bin/localkube
2017-09-14 12:00:23.838204 I | proto: duplicate proto type registered: google.protobuf.Any
2017-09-14 12:00:23.838372 I | proto: duplicate proto type registered: google.protobuf.Duration
2017-09-14 12:00:23.838372 I | proto: duplicate proto type registered: google.protobuf.Timestamp
Using these existing CA certs:  /var/lib/localkube/certs/ca.crt /var/lib/localkube/certs/ca.key /var/lib/localkube/certs/proxy-client-ca.crt /var/lib/localkube/certs/proxy-client-ca.key
Using these existing certs:  /var/lib/localkube/certs/apiserver.crt /var/lib/localkube/certs/apiserver.key /var/lib/localkube/certs/proxy-client.crt /var/lib/localkube/certs/proxy-client.key
2017-09-14 12:00:23.862209 I | embed: listening for peers on http://localhost:2380
2017-09-14 12:00:23.862313 I | embed: listening for client requests on localhost:2379
2017-09-14 12:00:23.863296 I | etcdserver: name = default
2017-09-14 12:00:23.863308 I | etcdserver: data dir = /var/lib/localkube/etcd
2017-09-14 12:00:23.863313 I | etcdserver: member dir = /var/lib/localkube/etcd/member
2017-09-14 12:00:23.863319 I | etcdserver: heartbeat = 100ms
2017-09-14 12:00:23.863323 I | etcdserver: election = 1000ms
2017-09-14 12:00:23.863326 I | etcdserver: snapshot count = 10000
2017-09-14 12:00:23.863337 I | etcdserver: advertise client URLs = http://localhost:2379
2017-09-14 12:00:23.863718 I | etcdserver: restarting member 8e9e05c52164694d in cluster cdf818194e3a8c32 at commit index 148
2017-09-14 12:00:23.863741 I | raft: 8e9e05c52164694d became follower at term 74
2017-09-14 12:00:23.863751 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 74, commit: 148, applied: 0, lastindex: 148, lastterm: 74]
2017-09-14 12:00:23.927884 I | etcdserver: starting server... [version: 3.1.5, cluster version: to_be_decided]
2017-09-14 12:00:23.928465 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
2017-09-14 12:00:23.928472 N | etcdserver/membership: set the initial cluster version to 3.1
2017-09-14 12:00:23.928500 I | etcdserver/api: enabled capabilities for version 3.1
2017-09-14 12:00:23.966065 I | raft: 8e9e05c52164694d is starting a new election at term 74
2017-09-14 12:00:23.966102 I | raft: 8e9e05c52164694d became candidate at term 75
2017-09-14 12:00:23.966136 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 75
2017-09-14 12:00:23.966159 I | raft: 8e9e05c52164694d became leader at term 75
2017-09-14 12:00:23.966175 I | raft: raft.node: 8e9e05c52164694d elected leader 8e9e05c52164694d at term 75
2017-09-14 12:00:23.978661 I | embed: ready to serve client requests
2017-09-14 12:00:23.978744 I | etcdserver: published {Name:default ClientURLs:[http://localhost:2379]} to cluster cdf818194e3a8c32
2017-09-14 12:00:23.979049 N | embed: serving insecure client requests on 127.0.0.1:2379, this is strongly discouraged!
localkube host ip address: 10.250.140.42
Starting apiserver...
Waiting for apiserver to be healthy...
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7fa7ac0b560d]

runtime stack:
runtime.throw(0x4a9944a, 0x2a)
        /usr/local/go/src/runtime/panic.go:596 +0x95
runtime.sigpanic()
        /usr/local/go/src/runtime/signal_unix.go:274 +0x2db

goroutine 245 [syscall, locked to thread]:
runtime.cgocall(0x3b5c1c0, 0xc42046fdd8, 0x4a91ada)
        /usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc42046fd98 sp=0xc42046fd58
net._C2func_getaddrinfo(0x7fa7940008c0, 0x0, 0xc42108e300, 0xc4211f6010, 0x0, 0x0, 0x0)
        net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc42046fdd8 sp=0xc42046fd98
net.cgoLookupIPCNAME.func2(0x7fa7940008c0, 0x0, 0xc42108e300, 0xc4211f6010, 0x4a29c23, 0x9, 0x4143c20)
        /usr/local/go/src/net/cgo_unix.go:151 +0x171 fp=0xc42046fe38 sp=0xc42046fdd8
net.cgoLookupIPCNAME(0x4a29c23, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/cgo_unix.go:151 +0x1bd fp=0xc42046ff38 sp=0xc42046fe38
net.cgoIPLookup(0xc420a36480, 0x4a29c23, 0x9)
        /usr/local/go/src/net/cgo_unix.go:203 +0x4d fp=0xc42046ffc8 sp=0xc42046ff38
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc42046ffd0 sp=0xc42046ffc8
created by net.cgoLookupIP
        /usr/local/go/src/net/cgo_unix.go:213 +0xb4

**Comment by r2d4** [comment] 2017-09-14 21:14
Can you add some steps to reproduce this?  Are you running localkube directly or through minikube?

**Comment by Aleishus** [comment] 2017-09-15 04:56
@r2d4  I use this command  
```bash
 minikune --vm-driver=none
```

**Comment by ernstp** [comment] 2017-09-18 08:08
Dupe of #1947 ?

**Comment by Aleishus** [comment] 2017-09-18 08:49
Yes,but I use centos7.3.

**Comment by dlorenc** [comment] 2017-10-10 12:56
Closing as a dupe. I think it's the same issue and should have a fix shortly.

**Closed by dlorenc** 2017-10-10 12:56 UTC
Labels: driver/none, kind/bug
