### ISSUE TITLE
Using local driver gets error 'localkube-v1.9.4: no such file or directory'

### ISSUE THREAD

**Issue by sabrehagen** [kubernetes/minikube#2629] opened 2018-03-22 02:29 UTC
**BUG REPORT**

**Minikube version** v0.25.1:
- **OS** Ubuntu 17.10:
- **VM Driver** (none):
- **ISO version** None (`cat ~/.minikube/machines/minikube/config.json | grep -i ISO` produced no result):

**What happened**:

```
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0322 12:18:47.974752   10867 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: /home/jackson/.minikube/cache/localkube/localkube-v1.9.4: open /home/jackson/.minikube/cache/localkube/localkube-v1.9.4: no such file or directory
```

**What you expected to happen**:

Minikube to start successfully with local driver

**How to reproduce it** (as minimally and precisely as possible):

Run the `Example with kubectl installation` in `README.md`:

```
curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube
curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl && chmod +x kubectl

export MINIKUBE_WANTUPDATENOTIFICATION=false
export MINIKUBE_WANTREPORTERRORPROMPT=false
export MINIKUBE_HOME=$HOME
export CHANGE_MINIKUBE_NONE_USER=true
mkdir $HOME/.kube || true
touch $HOME/.kube/config

export KUBECONFIG=$HOME/.kube/config
sudo -E ./minikube start --vm-driver=none

# this for loop waits until kubectl can access the api server that Minikube has created
for i in {1..150}; do # timeout for 5 minutes
   ./kubectl get po &> /dev/null
   if [ $? -ne 1 ]; then
      break
  fi
  sleep 2
done
```

**Comment by cyron** [comment] 2018-03-22 02:39
workaround I just took.
download files and rename to localkube-1.9.4

*localkube
*localkube.sha256

then copy to /home/jackson/.minikube/cache/localkube/

**Comment by svincen2** [comment] 2018-03-22 03:44
Is this a repeat of #2475 ?
I don't see 1.9.4 in the json: https://storage.googleapis.com/minikube/k8s_releases.json

**Comment by dlorenc** [comment] 2018-03-22 03:51
No, if anything this is the opposite. The GCS files were missing at first, but they got uploaded a few hours before this issue was opened. The releases json file hasn't been merged/uploaded yet

**Comment by ChoudharyS** [comment] 2018-03-22 07:33
Facing exactly same issue. After the workaround by @cyron cluser starts but dashboard goes on CrashLoopBackOff.

**Comment by pgoodjohn** [comment] 2018-03-22 07:48
+1 Happening on MacOS as well.

**Comment by ymesika** [comment] 2018-03-22 08:37
@pgoodjohn The workaround suggested by @cyron above worked for me on MacOS.
Just had to rename the two files to `localkube-v1.9.4` and `localkube-v1.9.4.sha256` (instead of localkube-1.9.4)

**Comment by pavolloffay** [comment] 2018-03-22 08:41
I have the same issue on fedora 27
```
minikube start --vm-driver=kvm --cpus 4 --memory=8000  
Starting local Kubernetes v1.9.4 cluster...
Starting VM...
Downloading Minikube ISO
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
WARNING: The kvm driver is now deprecated and support for it will be removed in a future release.
				Please consider switching to the kvm2 driver, which is intended to replace the kvm driver.
				See https://github.com/kubernetes/minikube/blob/master/docs/drivers.md#kvm2-driver for more information.
				To disable this message, run [minikube config set WantShowDriverDeprecationNotification false]
Getting VM IP address...
Moving files into cluster...
E0322 09:39:32.905121   21100 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: /home/ploffay/.minikube/cache/localkube/localkube-v1.9.4: open /home/ploffay/.minikube/cache/localkube/localkube-v1.9.4: no such file or directory
```

**Comment by pappnase99** [comment] 2018-03-22 10:13
Same issue on Windows, downloading localkube as suggested by @cyron solved it.

**Comment by theevocater** [comment] 2018-03-22 14:38
Was running into this myself and I can confirm that loading the latest kubernetes version listed in the json still works. If you are simply trying to get something started you can always pass the kubernetes version. The latest valid one is 1.9.0.

Try: 

```
minikube start --kubernetes-version=v1.9.0
```

**Comment by svincen2** [comment] 2018-03-22 14:55
@theevocater interesting.  I tried that and I kept getting an error saying downgrade wasn't allowed, and it defaulted back to 1.9.4.  @cyron workaround worked for me (mac high sierra)

**Comment by theevocater** [comment] 2018-03-22 15:26
@svincen2 Ah yeah I didn't need my minikube (this was my first use of it) so I just blew away ~/.minikube and started over. Because the new cluster never actually boots, I bet you could twiddle with the `.minikube/profiles/minikube/config.json` safely. However, use at your own risk, etc etc heh.

**Comment by schlomo** [comment] 2018-03-22 15:50
`minikube get-k8s-versions` doesn't show anything and problem still persist on OSX:
![image](https://user-images.githubusercontent.com/101384/37781495-1b404a9c-2df1-11e8-854d-987311331405.png)

Is this part of the same problem?

**Comment by dlorenc** [comment] 2018-03-22 15:56
Maybe a transient issue? It works for me.

**Comment by schlomo** [comment] 2018-03-22 16:17
@dlorenc what is the expected output of `get-k8s-versions`?

**Comment by dlorenc** [comment] 2018-03-22 16:18
```shell
- v1.9.4
	- v1.9.0
	- v1.8.0
	- v1.7.5
	- v1.7.4
	- v1.7.3
	- v1.7.2
	- v1.7.0
	- v1.7.0-rc.1
	- v1.7.0-alpha.2
	- v1.6.4
	- v1.6.3
	- v1.6.0
	- v1.6.0-rc.1
	- v1.6.0-beta.4
	- v1.6.0-beta.3
	- v1.6.0-beta.2
	- v1.6.0-alpha.1
	- v1.6.0-alpha.0
	- v1.5.3
	- v1.5.2
	- v1.5.1
	- v1.4.5
	- v1.4.3
	- v1.4.2
	- v1.4.1
	- v1.4.0
	- v1.3.7
	- v1.3.6
	- v1.3.5
	- v1.3.4
	- v1.3.3
	- v1.3.0
```

**Comment by schlomo** [comment] 2018-03-22 16:23
Thanks, now I get the same. 👍

**Closed** 2018-03-22 22:51 UTC
