### ISSUE TITLE
Unable to start VM: Error getting state for host: machine does not exist

### ISSUE THREAD

**Issue by Tonterias** [kubernetes/minikube#3925] opened 2019-03-21 17:56 UTC
usuario@DESKTOP-GTCQCAR ~
$ minikube start
o   minikube v0.35.0 on windows (amd64)
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
!   Unable to start VM: Error getting state for host: machine does not exist

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new

usuario@DESKTOP-GTCQCAR ~

Windows 10 Home

**Comment by tstromberg** [comment] 2019-03-22 01:49
Your system no longer knows about the VM previously created by minikube. Run 'minikube delete' to reset your local state. 

I hope this helps!

**Comment by tstromberg** [comment] 2019-03-22 03:32
Dupe of #3864

**Closed by tstromberg** 2019-03-22 03:32 UTC
Labels: needs-solution-message, priority/awaiting-more-evidence, triage/support

**Comment by tstromberg** [comment] 2019-05-14 16:48
Duplicate of #3864

**Comment by ramakrishna1225** [comment] 2020-02-13 04:57
I have done minikube delete and minikube start.

But i got **umount: /mount-awv: no mount point specified.** ERROR
