### ISSUE TITLE
Hard coded SystemD cmds in vm-driver=none 

### ISSUE THREAD

**Issue by elacheche** [kubernetes/minikube#3174] opened 2018-09-27 11:50 UTC
**BUG REPORT**

**Environment**:

**Minikube version** (use `minikube version`): v0.28.2
- **OS** (e.g. from /etc/os-release): Gentoo
- **VM Driver** : none
- **Install tools**: sudo emerge -a minikube
- **Others**: Same result if I use the pre-compiled binary from [github](https://github.com/kubernetes/minikube/releases)

**What happened**: 

``` sudo minikube --vm-driver=none start

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0927 12:40:20.428534    7852 start.go:258] Error updating cluster:  starting kubelet: running command:
sudo systemctl daemon-reload &&
sudo systemctl enable kubelet &&
sudo systemctl start kubelet
: exit status 1
```
**What you expected to happen**: start minikube

**How to reproduce it** (as minimally and precisely as possible): Use a distro that don't use SystemD, I use OpenRC with Gentoo, but I suppose that running this on Devuan will result the same

**Output of `minikube logs` (if applicable)**: 

```sudo minikube logs

2018/09/27 12:44:29 Error getting machine logs: getting cluster logs: running command: sudo journalctl  -u kubelet
 output: sudo: journalctl: command not found
: running command: sudo journalctl  -u kubelet
.: exit status 1
```

**Comment by tstromberg** [comment] 2018-09-27 22:12
Closing as a dupe of #2704 

I agree that this situation sucks, but it's also not yet a top priority for us. If you end up finding a workable solution, I'm all ears and would happily review a patch for it.

**Closed by tstromberg** 2018-09-27 22:12 UTC
