### ISSUE TITLE
Error getting state for host: exit status 126

### ISSUE THREAD

**Issue by waprin** [kubernetes/minikube#519] opened 2016-08-24 22:34 UTC
**Minikube version** (use `minikube version`):
minikube version: v0.8.0

**Environment**:
- **OS** (e.g. from /etc/os-release): OS X El Capitan 10.11.6 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`):
    "DriverName": "virtualbox",

- **Docker version** (e.g. `docker -v`):
Docker version 1.12.0, build 8eab29e

(Docker for Mac)

- **Install tools**: OS X binary package

**What happened**:

(docsamples10) waprin-macbookpro:django_postgres_redis waprin$ minikube start --vm-driver=xhyve
E0824 15:32:51.389622   30129 start.go:89] Error starting host:  Error getting state for host: exit status 126
Error getting state for host: exit status 126
(docsamples10) waprin-macbookpro:django_postgres_redis waprin$ minikube docker-env
E0824 15:23:04.955046   29839 env.go:247] Error setting machine env variable(s): exit status 126

**What you expected to happen**:

* Don't get errors or get errors that make it clear how to fix.
* Make it clearer how to blow away any config that might be breaking things

**How to reproduce it** (as minimally and precisely as possible):

OS X, Docker for Mac, download minikube OS X binary and do minikube start

**Anything else do we need to know**:

I think minikube start might have succeeded the first time and then all the commands started giving the 126, but I'm having problems digging up the bash history. Either way now start fails right away.

**Comment by waprin** [comment] 2016-08-24 22:38
I do see that my minikube config file has the VirtualBox driver, which isn't good because I deleted VirtualBox to get Docker for Mac to install correctly. But unclear the best way to change that config file (just edit it?)

**Comment by r2d4** [comment] 2016-08-24 22:52
It looks like minikube did not delete gracefully.  A `minikube delete` should wipe the config file, and then a subsequent `minikube start --vm-driver=xhyve` should work properly.

Sometimes the `minikube start` command is not clear.  We should add a check to see if the driver flag passed in matches the known configuration that would require a restart or deletion.

**Comment by dlorenc** [comment] 2016-08-24 22:52
Running minikube delete should get you back to a happy place. Docker for Mac and minikube don't actually interact, but deleting virtualbox will cause trouble.

Could you delete, then run minikube start --vm-driver xhyve ?

That will create a minikube machine using xhyve, the same underlying tech as Docker for Mac.

**Comment by waprin** [comment] 2016-08-24 22:52
minikube delete
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  exit status 126

**Comment by waprin** [comment] 2016-08-24 22:53
Oh that might have gotten me back to a happy place now, now looking for xhyve, ok.

**Comment by waprin** [comment] 2016-08-24 22:56
(docsamples10) waprin-macbookpro:minikube waprin$ minikube start --vm-driver xhyve 
E0824 15:56:09.338261   32907 start.go:89] Error starting host:  Error creating. Error with pre-create check: "Error detecting VBox version: exit status 126"
Error creating. Error with pre-create check: "Error detecting VBox version: exit status 126

**Comment by r2d4** [comment] 2016-08-24 22:57
@waprin `minikube start --vm-driver=xhyve`

dont forget the =

**Comment by waprin** [comment] 2016-08-24 22:57
Doesn't change anything: 
(docsamples10) waprin-macbookpro:minikube waprin$ minikube start --vm-driver=xhyve 
Starting local Kubernetes cluster...
E0824 15:57:28.977326   32935 start.go:83] Error starting host: Error creating. Error with pre-create check: "Error detecting VBox version: exit status 126". Retrying.

**Comment by r2d4** [comment] 2016-08-24 23:03
It looks like a bad catch 22, `minikube delete` isn't working because of the config its trying to delete.  

Can you try a `minikube delete --v=10 --show-libmachine-logs --alsologtostderr` so we can possibly get some more verbose output?

**Comment by dlorenc** [comment] 2016-08-24 23:06
This is a silly bug in the xhyve driver, caused by how you removed virtualbox.

xhyve had some known issues with older versions of virtualbox which would result in kernel panics. Virtualbox fixed these issues. The driver of checking the virtualbox version, so it doesn't cause a kernel panic.

It looks like you partially removed virtualbox, but not fully.

**Comment by dlorenc** [comment] 2016-08-24 23:06
The driver is smart enough to proceed if it doesn't see a vbxmanage binary on your path, but if you have one the driver requires a version check.

**Comment by waprin** [comment] 2016-08-24 23:35
(docsamples10) waprin-macbookpro:minikube waprin$  minikube delete --v=10 --show-libmachine-logs --alsologtostderr
W0824 16:35:08.376960   35129 root.go:93] Error reading config file at /Users/waprin/.minikube/config: Unsupported Config Type ""
Deleting local Kubernetes cluster...
Errors occurred deleting machine:  Host does not exist: "minikubeVM"

And ok will try to purge virtualbox more fully, I don' t have a vbxmanage on my paht though AFAICT.

**Comment by dlorenc** [comment] 2016-08-24 23:40
Sorry, vboxmanage. and since this is osx case matters. I think it's VBoxManage

**Comment by waprin** [comment] 2016-08-25 00:05
Ah ty, now it works! Hooray. Feel free to close.

**Comment by dlorenc** [comment] 2016-08-25 00:07
You're the second person to run into this xhyve bug, we should try to make the error clearer at least, or change this case to a warning in the driver.

**Comment by dlorenc** [comment] 2016-09-01 21:21
Closing, this will be fixed upstream in the driver.

**Closed by dlorenc** 2016-09-01 21:21 UTC
Labels: kind/bug

**Comment by dutronlabs** [comment] 2016-09-09 19:55
As a referential point for anyone who run into this issue on El Capitan and found this via Google (like I did):

If you partially removed VirtualBox, most likely the files you need to "fully" remove it are `/usr/local/bin/VBox*` and `/usr/local/bin/vbox*`

Removing those and then `minikube start --vm-driver=xhyve` got me up and running.

**Comment by yuchen16** [comment] 2017-03-07 08:54
I met this problem on windows7 and I used virtualbox as vm-driver. solved it by following steps :
delete the .minikube folder whitch under "C:\Users\USER_NAME"
then 
minikube start

**Comment by Artie313** [comment] 2017-06-16 16:26
Perhaps we could have @dutronlabs 's comment in the documentation for either **Minikube** or **GoFabric**. I found @dutronlabs solution after hours of digging off the internet. Could be useful to have it under the **Troubleshoot** sections.

**Comment by r2d4** [comment] 2017-06-16 16:30
@Artie313 thats a great idea 👍 .  Feel free to send a PR with some updated documentation where you think it should be.

**Comment by zoidbergwill** [comment] 2017-06-26 13:38
Could we maybe make:

> E0626 15:22:55.006606   63390 start.go:133] Error starting host:  Error creating host: Error with pre-create check: "Error detecting VBox version: exit status 126"

Also mention something about how you probably tried to remove VirtualBox unsuccesfully and need to do:

```
rm -rf /usr/local/bin/{VBox,vbox}*
```

**Comment by eggie5** [comment] 2017-07-17 18:39
Yes, I can confirm that a sloppy VirtualBox uninstall left these files in `/usr/local/bin`

```
VBoxAutostart
 VBoxBalloonCtrl
VBoxDTrace
VBoxHeadless
VBoxManage
VBoxVRDP
VirtualBox
Wand-config
```

After removing them, `minikube start --vm-driver=xhyve` works as expected.

**Comment by voyalab** [comment] 2017-07-28 13:15
Thanks for a solution it worked for me.

`rm -rf /usr/local/bin/{VBox,vbox}* 
`
is the necessary step to do.

**Comment by Wicht1** [comment] 2017-07-30 23:30
I have the same Error 

Try to:

fuckup:~ USERNAME$ minishift start
Starting local OpenShift cluster using 'xhyve' hypervisor...
E0731 01:25:17.913134    9843 start.go:282] Error starting the VM: Error creating the VM. Error with pre-create check: "Error detecting VBox version: exit status 126". Retrying.

but i have no vBox, or i can't find it anywhere on my Mac. And i don't remember to install it.

Some Idea whats happened?

I Installed Brewer, than i Install xhyves, than Minishift. Then the driver (was also an error). Then i do this:
sudo chown root:wheel $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve
after that:
sudo chmod u+s $(brew --prefix)/opt/docker-machine-driver-xhyve/bin/docker-machine-driver-xhyve

And now i don't find a solution :D

**Comment by Wicht1** [comment] 2017-07-31 19:44
run the VirtualBox.uninstall.tool -> That fixed the Problem

**Comment by psanders** [comment] 2019-05-24 19:40
Wiping the config files worked for me:

`rm -rf ~/.minikube`

**Comment by thanhgb** [comment] 2019-09-30 15:25
> Wiping the config files worked for me:
> 
> `rm -rf ~/.minikube`

This works for me, thanks @psanders
