### ISSUE TITLE
hyperv: cannot use "fe80::215:5dff:fe2b:530f" as the bind address for the API Server

### ISSUE THREAD

**Issue by kshmaniram** [kubernetes/minikube#4693] opened 2019-07-05 14:42 UTC
* Configuring environment for Kubernetes v1.14.3 on Docker 18.09.6
* Pulling images ...
* Unable to pull images, which may be OK: running cmd: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml: command failed: sudo kubeadm config images pull --config /var/lib/kubeadm.yaml
stdout:
stderr: failed to pull image "k8s.gcr.io/kube-apiserver:v1.14.3": output: Error response from daemon: Get https://k8s.gcr.io/v2/: dial tcp: lookup k8s.gcr.io on [2001:4860:4860::8888]:53: dial udp [2001:4860:4860::8888]:53: connect: network is unreachable
, error: exit status 1
: Process exited with status 1
* Launching Kubernetes ...

X Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
cannot use "fe80::215:5dff:fe2b:530f" as the bind address for the API Server

: Process exited with status 1

**Comment by tstromberg** [comment] 2019-07-16 20:53
This issue appears to be a duplicate of #3963, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed by tstromberg** 2019-07-16 20:53 UTC
Labels: co/hyperv
