### ISSUE TITLE
Issues About Starting Minikube

### ISSUE THREAD

**Issue by Liuzhou-Railway-Bureau** [kubernetes/minikube#6319] opened 2020-01-15 02:14 UTC
**The exact command to reproduce the issue**:
minikube start --vm-driver=virtualbox

**The full output of the command that failed**:<details>
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x12ee976]

</details>

**The output of the `minikube logs` command**:<details>
goroutine 32 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc000430e20, 0xa, 0xc000430e2b, 0xa, 0xc000430e36, 0x7, 0x0, 0x0, 0xc0003b3c58, ...)
        /go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x136
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc000430e20, 0x1d, 0xc0005d74f0, 0x4b, 0x0, 0x0)
        /app/pkg/minikube/machine/cache_images.go:395 +0x615
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc00014bf68, 0x1)
        /app/pkg/minikube/machine/cache_images.go:85 +0xed
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0004a3950, 0xc0004a3980)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x6b
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x6d
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x12ee976]

goroutine 33 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc000129590, 0xa, 0xc00012959b, 0xe, 0xc0001295aa, 0x7, 0x0, 0x0, 0xc000429c58, ...)
        /go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x136
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc000129590, 0x21, 0xc0005d7720, 0x4f, 0x0, 0x0)
        /app/pkg/minikube/machine/cache_images.go:395 +0x615
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0004b1f68, 0xb)
        /app/pkg/minikube/machine/cache_images.go:85 +0xed
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0004a3950, 0xc0004a39b0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x6b
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x6d

</details>

**The operating system version**:
minikube v1.6.2 on Microsoft Windows Server 2016 Datacenter 10.0.14393 Build 14393
Selecting 'virtualbox' driver from user configuration (alternates: [hyperv])

**Comment by medyagh** [comment] 2020-01-22 02:50
Thank you for sharing your experience! If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by sharifelgamal** [comment] 2020-02-05 19:46
This should be fixed with minikube 1.7, can you upgrade and retry?

Closing as a duplicate of #6147

**Closed by sharifelgamal** 2020-02-05 19:46 UTC
Labels: co/virtualbox, triage/needs-information, triage/support
