### ISSUE TITLE
Installing minikube on Chrome OS

### ISSUE THREAD

**Issue by donangelodev** [kubernetes/minikube#10431] opened 2021-02-10 02:28 UTC
**Steps to reproduce the issue:** 

penguin:~$ minikube start
😄  minikube v1.17.1 on Debian 10.8 (amd64)
✨  Using the docker driver based on existing profile
💨  For improved Docker performance, enable the overlay Linux kernel module using 'modprobe overlay'
❗  docker is currently using the btrfs storage driver, consider switching to overlay2 for better performance
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing docker container for "minikube" ...

💢  The minikube docker container exited unexpectedly.
💡  If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:

        - Prune unused docker images, volumes, networks and abandoned containers.

                                docker system prune --volumes

        - Restart your docker service

        - Delete and recreate minikube cluster
                minikube delete
                minikube start --driver=docker
🤦  StartHost failed, but will try again: driver start: container name "minikube": log: 2021-02-10T02:13:12.163523989Z  + echo 'INFO: remounting /sys read-only'
2021-02-10T02:13:12.163584510Z  INFO: remounting /sys read-only
2021-02-10T02:13:12.163594117Z  + mount -o remount,ro /sys
2021-02-10T02:13:12.165320277Z  mount: /sys: permission denied.: container exited unexpectedly
🔄  Restarting existing docker container for "minikube" ...

💢  The minikube docker container exited unexpectedly.
💡  If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:

        - Prune unused docker images, volumes, networks and abandoned containers.

                                docker system prune --volumes

        - Restart your docker service

        - Delete and recreate minikube cluster
                minikube delete
                minikube start --driver=docker
😿  Failed to start docker container. Running "minikube delete" may fix it: driver start: container name "minikube": log: 2021-02-10T02:13:57.404031663Z  + echo 'INFO: remounting /sys read-only'
2021-02-10T02:13:57.404037380Z  INFO: remounting /sys read-only
2021-02-10T02:13:57.404041954Z  + mount -o remount,ro /sys
2021-02-10T02:13:57.405942337Z  mount: /sys: permission denied.: container exited unexpectedly

💢  The minikube docker container exited unexpectedly.
💡  If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:

        - Prune unused docker images, volumes, networks and abandoned containers.

                                docker system prune --volumes

        - Restart your docker service

        - Delete and recreate minikube cluster
                minikube delete
                minikube start --driver=docker

❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: container name "minikube": log: 2021-02-10T02:13:57.404031663Z  + echo 'INFO: remounting /sys read-only'
2021-02-10T02:13:57.404037380Z  INFO: remounting /sys read-only
2021-02-10T02:13:57.404041954Z  + mount -o remount,ro /sys
2021-02-10T02:13:57.405942337Z  mount: /sys: permission denied.: container exited unexpectedly

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
penguin:~$ cat /etc/os-release

PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

penguin:~$ minikube version
minikube version: v1.17.1
commit: 043bdca07e54ab6e4fc0457e3064048f34133d7e

penguin:~$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 22
 Server Version: 20.10.3
 Storage Driver: btrfs
  Build Version: Btrfs v4.20.1 
  Library Version: 102
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.74-10576-gb6cc41974db3
 Operating System: Debian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 6.484GiB
 Name: penguin
 ID: LYG7:IOFY:I2DH:USUK:OUC5:RANN:HTKP:WXDW:2NNV:RQYP:TTV2:GFLT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No blkio weight support
WARNING: No blkio weight_device support

</details>

**Comment by eddyjlhaigh** [comment] 2021-02-18 12:08
It is a duplicate, but I'd be keen to know when this will be fixed/implemented?

**Comment by afbjorklund** [comment] 2021-02-18 12:12
Currently it is more a question of "if" (Chrome OS will allow for nested containers, or virtualization)

**Comment by eddyjlhaigh** [comment] 2021-02-18 16:44
Looks like they suggest it was fixed in ChromeOS kernel 4.19

My system is running `Linux penguin 5.4.74-10576-gb6cc41974db3` so assuming ChromeOS Kernel Version == Linux penguin version, this should be fixed? In which case, could we re-open that issue? And if it's not, any idea on the release date of 4.19? 

I'm wondering if I need to fork out for a Macbook to run this, or if I can carry on with my trusty Pixelbook.

**Comment by eddyjlhaigh** [comment] 2021-02-18 16:45
Oh I'm sorry, for some reason I thought you worked for Google on containers but that was @tstromberg in the other issue! 😬

**Comment by afbjorklund** [comment] 2021-02-18 16:49
I don't own any Pixelbook myself, but am using Raspberry Pi.

**Comment by vinchi777** [comment] 2021-02-21 12:16
I'm also getting this issue after `minikube start`. I'm using PopOs Linux.
``` 
INFO: remounting /sys read-only
+ mount -o remount,ro /sys
mount: /sys: permission denied.: container exited unexpectedly
```

**Comment by afbjorklund** [comment] 2021-02-21 15:35
@vinchi777 : I think Pop!OS is a more normal Ubuntu-based distro, so probably open an issue on that ?

<https://en.wikipedia.org/wiki/Pop!_OS>

**Comment by tstromberg** [comment] 2021-03-24 18:43
This issue appears to be a duplicate of #6411, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2021-03-24 18:43 UTC
Labels: co/docker-driver, kind/support, triage/duplicate
