### ISSUE TITLE
ec2-ubuntu driver issue for minikube

### ISSUE THREAD

**Issue by mukeshmcitp** [kubernetes/minikube#14510] opened 2022-07-04 15:53 UTC
### What Happened?

install minikube on ubuntu

### Attach the log file

Failed to enable unit: Unit file cri-docker.socket does not exist.

*
╭───────────────────────────────────────────────────────────────────────────────                                          ──────────────╮
│                                                                                                                                       │
│    * If the above advice does not help, please let us know:                                                                           │
│      https://github.com/kubernetes/minikube/issues/new/choose                                                                         │
│                                                                                                                                       │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the Git                                          Hub issue.    │
│                                                                                                                                       │
╰───────────────────────────────────────────────────────────────────────────────                                          ──────────────╯

### Operating System

Ubuntu

### Driver

Docker

**Comment by spowelljr** [comment] 2022-07-13 18:30
Hi @mukeshmcitp, thanks for reporting your issue with minikube. This is a duplicate of https://github.com/kubernetes/minikube/issues/14410. I have a detailed comment (https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503) that outlines what steps you should take depending on what driver you're using.

As a quick overview, if you're using the `docker` driver simply delete the minikube instance and recreate it and it should resolve your issue. If you're using the `none` driver follow the instructions on how to install cri-docker https://github.com/Mirantis/cri-dockerd#build-and-install.

I'm going to close this issue as it's a duplicate, but feel free to follow along with https://github.com/kubernetes/minikube/issues/14410, thanks!

**Closed by spowelljr** 2022-07-13 18:30 UTC
