### ISSUE TITLE
minikube start --driver=ssh --ssh-ip-address=vm.example.com

### ISSUE THREAD

**Issue by sharonngetich** [kubernetes/minikube#11255] opened 2021-05-02 16:41 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of `minikube logs` command:**
<details>

</details>

**Full output of failed command:**
<details>

</details>

**Comment by medyagh** [comment] 2021-05-02 17:37
Hi @sharonngetich it is not clear what the issue is,do u mind sharing the fulll output of `minikube logs`
Are yo trying to run minikube on a remote machine using SSH ?

**Comment by sharonngetich** [comment] 2021-05-02 18:11
> Hi @sharonngetich it is not clear what the issue is,do u mind sharing the fulll output of `minikube logs`
> Are yo trying to run minikube on a remote machine using SSH ?

@medyagh yes i'm trying to run it

**Comment by medyagh** [comment] 2021-05-03 20:04
@sharonngetich do u mind sharing the full logs ? or mind sharing what verison of minikube and what OS are you using ?

for SSH driver you would need acess to a remote machine with ip

but I am curious is there a reason you dont use the Docker driver ?

**Comment by sharifelgamal** [comment] 2021-06-02 18:11
Hey @sharonngetich  – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release

* The exact minikube start command line used

* The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.

* The full output of minikube logs

Thank you for sharing your experience!

**Closed by sharifelgamal** 2021-06-02 18:11 UTC
Labels: kind/support, triage/needs-information

**Comment by sharonngetich** [comment] 2021-07-28 12:51
> Hey @sharonngetich – hopefully it’s OK if I close this - there wasn’t enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.
> 
> Here is additional information that may be helpful to us:
> 
> * Whether the issue occurs with the latest minikube release
> * The exact minikube start command line used
> * The full output of the minikube start command, preferably with --alsologtostderr -v=3 for extra logging.
> * The full output of minikube logs
> 
> Thank you for sharing your experience!
kindly close it
