### ISSUE TITLE
Compiling Minikube failing on Fedora 25

### ISSUE THREAD

**Issue by LalatenduMohanty** [kubernetes/minikube#1531] opened 2017-05-26 06:44 UTC
**BUG REPORT** 

--> Compiling Minikube ( i.e. `$ make`) on Fedora 25.  

**Minikube version** (use `minikube version`): NA 

As I am trying to build  on latest master i.e. https://github.com/kubernetes/minikube/commit/37f698549943fb9b4c2282c87aef0e666c591830

**Environment**:
- **OS**: Fedora 25
- **VM Driver** : NA
- Go version: go version go1.7.5 linux/amd64
```
$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/lmohanty/GoCode"
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build615070760=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

```
**What happened**:
I am trying to compile Minikube on Fedora 25 

```
$ make clean
rm -rf /home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath
rm -rf ./out
rm -f pkg/minikube/assets/assets.go

$ make
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
mkdir -p /home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io
ln -s -f /home/lmohanty/GoCode/src/github.com/kubernetes/minikube /home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io
CGO_ENABLED=1 go build -tags static_build -ldflags="-X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=0480917b552be33e2dba47386e51decb1a211df6 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.6.3 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.buildDate=2017-05-26T12:02:01Z -X k8s.io/minikube/pkg/version.version=v0.19.0 -X k8s.io/minikube/pkg/version.isoVersion=v0.18.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -s -w -extldflags '-static'" -o ./out/localkube ./cmd/localkube
# _/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/cmd/localkube
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

Makefile:73: recipe for target 'out/localkube' failed
make: *** [out/localkube] Error 2
```

**What you expected to happen**:
We should be able to compile it on Fedora

**How to reproduce it** (as minimally and precisely as possible):
1. Clone the git repository of Minikube in $GOPATH/src/github.com/kubernetes/minikube
2. $ cd minikube ; $ make

**Anything else do we need to know**:

**Comment by gbraad** [comment] 2017-05-26 07:01
Able to reproduce on a stock F25

```
$ sudo dnf install -y golang golang-src golang-bin glide
$ cd /var/workspaces/minikube/src/github.com/minikube/src/kubernetes/minikube
$ cd /war/workspaces/
$ mkdir minikube
$ cd minikube
$ mkdir pkg src bin
$ cd src
$ mkdir kubernetes
$ cd kubernetes
$ git clone https://github.com/kubernetes/minikube.git
Cloning into 'minikube'...
remote: Counting objects: 38764, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 38764 (delta 4), reused 3 (delta 0), pack-reused 38745
Receiving objects: 100% (38764/38764), 33.06 MiB | 1.02 MiB/s, done.
Resolving deltas: 100% (21724/21724), done.
Checking connectivity... done.
$ cd minikube
$ export GOPATH=/var/workspaces/minikube
$ export PATH=$PATH:$GOPATH/bin
$ make
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
        /usr/lib/golang/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
        /usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
        /usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
        /usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
        /usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
        /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
mkdir -p /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io
ln -s -f /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube /media/storage/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/_gopath/src/k8s.io
CGO_ENABLED=1 go build -tags static_build -ldflags="-X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=0480917b552be33e2dba47386e51decb1a211df6 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.6.3 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.buildDate=2017-05-26T14:54:10Z -X k8s.io/minikube/pkg/version.version=v0.19.0 -X k8s.io/minikube/pkg/version.isoVersion=v0.18.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -s -w -extldflags '-static'" -o ./out/localkube ./cmd/localkube
# _/var/workspaces/minishift/src/github.com/minikube/src/kubernetes/minikube/cmd/localkube
/usr/lib/golang/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/bin/ld: cannot find -lpthread
/bin/ld: cannot find -ldl
/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

Makefile:73: recipe for target 'out/localkube' failed
make: *** [out/localkube] Error 2
```

**Comment by gbraad** [comment] 2017-05-26 07:21
As suggested by @praveenkumar, this caused by https://github.com/kubernetes/minikube/blob/master/Makefile#L42. I remember we had the same issue with minishift

**Comment by praveenkumar** [comment] 2017-05-26 07:34
I can understand below part because this is due to Makefile rule , it set $GOPATH to `<your_cloned_directory>/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd` and that it put this output but this shouldn't case build error.

```
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
	/usr/lib/golang/src/k8s.io/minikube/pkg/provision (from $GOROOT)
	/home/lmohanty/GoCode/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube
```

**Comment by gbraad** [comment] 2017-05-26 07:52
The error is similar to when we started to use partial builds... I remember @hferentschik pushed a fix for this

**Comment by r2d4** [comment] 2017-06-09 16:41
We can remove the fake _gopath.  Its probably unnecessary now.

**Comment by budhrg** [comment] 2017-06-13 17:29
I am not able to reproduce it in Fedora 25 though. 

```
$ make clean
rm -rf /home/budhram/gowork/src/kubernetes/minikube/_gopath
rm -rf ./out
rm -f pkg/minikube/assets/assets.go

$ make
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
  /home/budhram/go/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
  /home/budhram/go/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/provision (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
  /home/budhram/go/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/provision (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
can't load package: package k8s.io/minikube/cmd/minikube/cmd: cannot find package "k8s.io/minikube/cmd/minikube/cmd" in any of:
  /home/budhram/go/src/k8s.io/minikube/cmd/minikube/cmd (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/minikube/cmd (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/constants: cannot find package "k8s.io/minikube/pkg/minikube/constants" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/constants (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/constants (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/minikube/machine: cannot find package "k8s.io/minikube/pkg/minikube/machine" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/minikube/machine (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/minikube/machine (from $GOPATH)
can't load package: package k8s.io/minikube/pkg/provision: cannot find package "k8s.io/minikube/pkg/provision" in any of:
  /home/budhram/go/src/k8s.io/minikube/pkg/provision (from $GOROOT)
  /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io/minikube/pkg/provision (from $GOPATH)
mkdir -p /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io
ln -s -f /home/budhram/gowork/src/kubernetes/minikube /home/budhram/gowork/src/kubernetes/minikube/_gopath/src/k8s.io
CGO_ENABLED=1 go build -tags static_build -ldflags="-X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=0480917b552be33e2dba47386e51decb1a211df6 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.6.3 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.buildDate=2017-06-13T22:33:27Z -X k8s.io/minikube/pkg/version.version=v0.19.0 -X k8s.io/minikube/pkg/version.isoVersion=v0.18.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -s -w -extldflags '-static'" -o ./out/localkube ./cmd/localkube
GOBIN=/home/budhram/gowork/src/kubernetes/minikube/_gopath/bin go get github.com/jteeuwen/go-bindata/...
/home/budhram/gowork/src/kubernetes/minikube/_gopath/bin/go-bindata -nomemcopy -o pkg/minikube/assets/assets.go -pkg assets ./out/localkube deploy/addons/...
CGO_ENABLED=1 GOARCH=amd64 GOOS=linux go build --installsuffix cgo -ldflags="-X k8s.io/minikube/pkg/version.version=v0.19.0 -X k8s.io/minikube/pkg/version.isoVersion=v0.18.0 -X k8s.io/minikube/pkg/version.isoPath=minikube/iso -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitCommit=0480917b552be33e2dba47386e51decb1a211df6 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitVersion=v1.6.3 -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.gitTreeState=clean -X k8s.io/minikube/vendor/k8s.io/kubernetes/pkg/version.buildDate=2017-06-13T22:33:27Z" -a -o ./out/minikube-linux-amd64 k8s.io/minikube/cmd/minikube
cp ./out/minikube-linux-amd64 ./out/minikube


$ ./out/minikube version
minikube version: v0.19.0

$ go version
go version go1.7 linux/amd64
```

Might be possible that some dependent package is missing here.

**Comment by gbraad** [comment] 2017-06-14 08:38
The issue on Lalatendu's and my machine is related to the linking step.
```
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lc
```
Are we missing dependencies? I have installed devel packages...

**Comment by LalatenduMohanty** [comment] 2017-06-14 08:42
@gbraad you are right.

```
$ make
can't load package: package k8s.io/minikube/cmd/localkube/cmd: cannot find package "k8s.io/minikube/cmd/localkube/cmd" in any of:
	/usr/lib/golang/src/k8s.io/minikube/cmd/localkube/cmd (from $GOROOT)
	/home/lmohanty/GOPATH/src/github.com/kubernetes/minikube/_gopath/src/k8s.io/minikube/cmd/localkube/cmd (from $GOPATH)
*************************************************
/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -ldl
/usr/bin/ld: cannot find -lc
collect2: error: ld returned 1 exit status

Makefile:73: recipe for target 'out/localkube' failed
make: *** [out/localkube] Error 2

```

**Comment by LalatenduMohanty** [comment] 2017-06-15 09:57
So I was missing `glibc-static` and after installing it the compilation works.
```
$ dnf install @development-tools
$ dnf install glibc-static
```

**Comment by budhrg** [comment] 2017-06-18 05:16
I think with the merge of https://github.com/kubernetes/minikube/pull/1590 , it should be closed now. 

WDYT @dlorenc @r2d4 ?

**Comment by dlorenc** [comment] 2017-06-18 15:20
Sounds right.

**Closed by dlorenc** 2017-06-18 15:20 UTC
Labels: kind/bug
