### ISSUE TITLE
Configure the minikube ip

### ISSUE THREAD

**Issue by alexef** [kubernetes/minikube#1331] opened 2017-04-06 08:45 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
This is a Feature Request.

**Minikube version** (use `minikube version`):
v0.17.1

**Environment**:
- **OS** (e.g. from /etc/os-release): Mac OS X 10.12.4
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): xhyve
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): minikube-v1.0.7.iso
- **Install tools**: - 
- **Others**: -

**What happened**:
We are using minikube as a developer machine for our web application.

According to the documentation, _the IP  is dynamic and can change. It can be retrieved with minikube ip._

**What you expected to happen**:
We would like to be able to configure this IP to a fixed value, so that we can assign a DNS name to the machine, and that name should be available across all developer machines.

**How to reproduce it** (as minimally and precisely as possible):
Starting/stopping minikube will some times assign a different ip.

**Comment by aaron-prindle** [comment] 2017-04-06 16:04
Related: #951

**Comment by r2d4** [comment] 2017-04-06 16:18
Closing as a dupe of #951, we'll track it there

**Closed by r2d4** 2017-04-06 16:18 UTC
Labels: kind/feature
