### ISSUE TITLE
Unable to start minikube v0.28 using audit logging

### ISSUE THREAD

**Issue by tavyy** [kubernetes/minikube#2934] opened 2018-06-25 20:11 UTC
**BUG REPORT**

**Environment**:

**Minikube version** (use `minikube version`): **v0.28.0**
- **OS** (e.g. from /etc/os-release): **MacOS High Sierra 10.13.5**
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): **VirtualBox 5.2.12 r122591 (Qt5.6.3)**
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): **Boot2DockerURL": "file:///Users/123456/.minikube/cache/iso/minikube-v0.28.0.iso**
- **Install tools**:  **curl -Lo minikube https://storage.googleapis.com/minikube/releases/v0.28.0/minikube-darwin-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/**
[minikube.log](https://github.com/kubernetes/minikube/files/2134583/minikube.log)

**What happened**:

When I try to start minikube using one of these commands:

`minikube start --extra-config=apiserver.Authorization.Mode=RBAC --extra-config=apiserver.Audit.LogOptions.Path=/var/log/audit.log --extra-config=apiserver.Audit.PolicyFile=/etc/kubernetes/addons/audit-policy.yaml`

or

`minikube start --extra-config=apiserver.authorization-mode=RBAC --extra-config=apiserver.audit-log-path=/var/log/audit.log --extra-config=apiserver.audit-policy-file=/etc/kubernetes/addons/audit-policy.yaml`

The content of **audit-policy.yaml** being:

 **apiVersion**: audit.k8s.io/v1beta1
**kind**: Policy
**rules**:
       - **level**: Metadata
 

it's end up by hanging the minikube in the line: `Starting cluster components...` and in the end I get this error:
`E0625 21:34:15.410946   54396 start.go:299] Error restarting cluster:  restarting kube-proxy: waiting for kube-proxy to be up for configmap update: timed out waiting for the condition
`

**What you expected to happen**: to start minikube with the audit logging 

**How to reproduce it** (as minimally and precisely as possible): stop the minikube and start it using one of the above commands.

**Output of `minikube logs` (if applicable)**: [minikube.log](https://github.com/kubernetes/minikube/files/2134599/minikube.log)

**Comment by kairen** [comment] 2018-06-30 19:13
Hi @tavyy and @Rouche, I added #2951 to support feature gate for Kubeadm. This feature can help you to enable auditing log in Minikube:
```sh
$ minikube start --kubeadm-feature-gates=Auditing=true
```

![](https://i.imgur.com/NTfdXjM.png)

**Comment by Rouche** [comment] 2018-07-03 16:43
Hopefully it gets merged for next version. never tryed to build minikube "yet".

**Comment by cxhercules** [comment] 2018-08-10 21:35
@kairen how did you manage to place the audit file in `/etc/kubernetes/audit/audit.yaml`? Also I still get the timeout, and I am using version v0.28.2.

I see this in logs:
```
Aug 10 21:17:04 minikube kubelet[2737]: E0810 21:17:04.897435    2737 kubelet_node_status.go:106] Unable to register node "minikube"
with API server: Post https://localhost:8443/api/v1/nodes: dial tcp 127.0.0.1:8443: getsockopt: connection refused
Aug 10 21:17:05 minikube kubelet[2737]: E0810 21:17:05.394666    2737 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460:
 Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0:
 dial tcp 127.0.0.1:8443: getsockopt: connection refused
Aug 10 21:17:05 minikube kubelet[2737]: E0810 21:17:05.395483    2737 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserve
r.go:47: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVers
ion=0: dial tcp 127.0.0.1:8443: getsockopt: connection refused
Aug 10 21:17:05 minikube kubelet[2737]: E0810 21:17:05.397465    2737 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451:
 Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: getsock
opt: connection refused
Aug 10 21:17:06 minikube kubelet[2737]: E0810 21:17:06.185236    2737 eviction_manager.go:246] eviction manager: failed to get get su
mmary stats: failed to get node info: node "minikube" not found
Aug 10 21:17:06 minikube kubelet[2737]: E0810 21:17:06.396190    2737 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/kubelet.go:460:
 Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0:
 dial tcp 127.0.0.1:8443: getsockopt: connection refused
Aug 10 21:17:06 minikube kubelet[2737]: E0810 21:17:06.397382    2737 reflector.go:205] k8s.io/kubernetes/pkg/kubelet/config/apiserve
```

**Comment by tstromberg** [comment] 2018-09-19 04:43
Probably a dupe of #2852 - please re-open if not.

**Closed by tstromberg** 2018-09-19 04:43 UTC
