### ISSUE TITLE
stop fails: "yaml: control characters are not allowed" + garbage text

### ISSUE THREAD

**Issue by TristansCloud** [kubernetes/minikube#5513] opened 2019-10-01 13:56 UTC
**The exact command to reproduce the issue**:
minikube stop

**The full output of the command that failed**:<details>
Large amounts of non human readable code, and:
 yaml: control characters are not allowed
💡  Suggestion: Run minikube from the C: drive.
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/1574

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:36745: connect: connection refused

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Ubuntu 19.04

**Comment by TristansCloud** [comment] 2019-10-01 13:57
Happened when running minikube on bare metal and with a vitualbox VM

**Comment by TristansCloud** [comment] 2019-10-01 13:58
However, minikube did successfully stop it just also gave these errors

**Comment by medyagh** [comment] 2019-10-01 18:43
Thanks for sharing this experience with us !

that is a flaw on our side that we are suggesting running on C: while you are trying to stop a minikube in ubuntu !
```
💡 Suggestion: Run minikube from the C: drive.
```

does this happen everytime ? what driver do you use ? (virtualbox ? or none ? )
what version of minikube do you use?

**Comment by TristansCloud** [comment] 2019-10-02 13:13
Happens every time unfortunately, and it happened both without a virtual machine (--vm-driver=none) and with virtualbox. I'm running minikube v1.4.0 and kubectl v1.16.0.

**Comment by TristansCloud** [comment] 2019-10-02 13:58
Tried again and for the first time it didn't do it. minikube logs after this sucessful minikube stop says 
"command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:36745: connect: connection refused" 
Not sure if that is related, I haven't done anything on minikube yet, only minikube start and minikube stop so haven't configured anything in the cluster yet.

**Comment by TristansCloud** [comment] 2019-10-02 20:24
I have forticlient VPN installed, but minikube seems to functioning fine now, not that I did anything.. minikube status says 
host: Running
kubelet: Running
apiserver: Running
kubectl: Correctly Configured: pointing to minikube-vm at 192.168.99.100
and I no longer have strange messages upon minikube stop, just "Stopping "minikube" in virtualbox" and "minikube" stopped." Not sure what happened, but if there is anything else I could help with please let me know.

**Comment by tstromberg** [comment] 2019-10-02 22:58
This issue appears to be a duplicate of #5499, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-10-02 22:58 UTC
Labels: area/networking, cause/vm-networking, kind/bug

**Comment by TristansCloud** [comment] 2019-10-03 19:17
Sure no problem
