### ISSUE TITLE
none: support for non-systemd distributions ("sudo service docker start")

### ISSUE THREAD

**Issue by ceasarchen** [kubernetes/minikube#5327] opened 2019-09-12 09:41 UTC
minikube failed to start because it tries to start docker by "sudo systemctl start docker", but in many linux distributions it's "sudo service docker start".

make it smart. 

**The exact command to reproduce the issue**:
sudo /usr/local/bin/minikube start --vm-driver=none

**The full output of the command that failed**:<details>
X Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
* minikube v1.3.1 on Amazon 2018.03
* Running on localhost (CPUs=2, Memory=3887MB, Disk=7997MB) ...
* OS release is Amazon Linux AMI 2018.03

**Comment by sharifelgamal** [comment] 2019-09-20 19:54
Closing as a dupe of #2704

**Closed by sharifelgamal** 2019-09-20 19:54 UTC
Labels: co/none-driver, help wanted, kind/feature, priority/backlog
