### ISSUE TITLE
Error restarting cluster: kubeadm init phase certs: Process exited with status 1

### ISSUE THREAD

**Issue by roxax19** [kubernetes/minikube#5897] opened 2019-11-13 09:12 UTC
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:

😄  minikube v1.5.2 on Ubuntu 18.04
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running kvm2 "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.09.9' ...
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: running cmd: /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml": Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The output of the `minikube logs` command**:<details>

==> Docker <==
-- Logs begin at Wed 2019-11-13 08:59:32 UTC, end at Wed 2019-11-13 09:08:01 UTC. --
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183173314Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183185953Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183199090Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183211649Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183223294Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183235446Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183400392Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183555338Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.183990094Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184031312Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184087896Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184101852Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184113434Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184124366Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184134748Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184145960Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184156635Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184167360Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184178123Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184229717Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184245956Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184258076Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184269110Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184387885Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184430263Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.184438930Z" level=info msg="containerd successfully booted in 0.228362s"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.190696315Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00012bda0, READY" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.193383268Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194075377Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194165238Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194305397Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194347119Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194386497Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005d1520, CONNECTING" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194518478Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194701567Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194808437Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005d1520, READY" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194911287Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194939548Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.194964750Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005d1800, CONNECTING" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.195640123Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005d1800, READY" module=grpc
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.884223174Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.884761963Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.884904688Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.884993712Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.885088339Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.885174505Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.885257562Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Nov 13 08:59:43 minikube dockerd[2059]: time="2019-11-13T08:59:43.885896159Z" level=info msg="Loading containers: start."
Nov 13 08:59:44 minikube dockerd[2059]: time="2019-11-13T08:59:44.284197262Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Nov 13 08:59:44 minikube dockerd[2059]: time="2019-11-13T08:59:44.482620050Z" level=info msg="Loading containers: done."
Nov 13 08:59:44 minikube dockerd[2059]: time="2019-11-13T08:59:44.488755658Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Nov 13 08:59:44 minikube dockerd[2059]: time="2019-11-13T08:59:44.573461331Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
Nov 13 08:59:44 minikube dockerd[2059]: time="2019-11-13T08:59:44.573740084Z" level=info msg="Daemon has completed initialization"
Nov 13 08:59:46 minikube dockerd[2059]: time="2019-11-13T08:59:46.130573446Z" level=info msg="API listen on /var/run/docker.sock"
Nov 13 08:59:46 minikube systemd[1]: Started Docker Application Container Engine.
Nov 13 08:59:46 minikube dockerd[2059]: time="2019-11-13T08:59:46.132138925Z" level=info msg="API listen on [::]:2376"
Nov 13 09:01:52 minikube dockerd[2059]: time="2019-11-13T09:01:52.242768648Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Nov 13 09:01:52 minikube dockerd[2059]: time="2019-11-13T09:01:52.283558022Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Nov 13 09:01:52 minikube dockerd[2059]: time="2019-11-13T09:01:52.316473345Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Nov 13 09:01:52 minikube dockerd[2059]: time="2019-11-13T09:01:52.568260091Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"

==> container status <==
time="2019-11-13T09:08:03Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[Nov13 08:59] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000000] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000001] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.021235] acpi PNP0A03:00: fail to add MMCONFIG information, can't access extended PCI configuration space under this bridge.
[ +20.864119] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +1.069008] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.006765] systemd-fstab-generator[1127]: Ignoring "noauto" for root device
[  +0.001289] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +1.265189] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +3.690985] vboxguest: loading out-of-tree module taints kernel.
[  +0.003609] vboxguest: PCI device not found, probably running on physical hardware.
[  +2.022084] systemd-fstab-generator[1974]: Ignoring "noauto" for root device
[Nov13 09:01] NFSD: Unable to end grace period: -110
[  +3.897478] systemd-fstab-generator[2612]: Ignoring "noauto" for root device
[ +12.220200] systemd-fstab-generator[2968]: Ignoring "noauto" for root device
[Nov13 09:05] systemd-fstab-generator[6443]: Ignoring "noauto" for root device
[ +14.528174] systemd-fstab-generator[6955]: Ignoring "noauto" for root device

==> kernel <==
 09:08:03 up 8 min,  0 users,  load average: 0.20, 0.53, 0.35
Linux minikube 4.19.76 #1 SMP Tue Oct 29 14:56:42 PDT 2019 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.6"

==> kubelet <==
-- Logs begin at Wed 2019-11-13 08:59:32 UTC, end at Wed 2019-11-13 09:08:03 UTC. --
Nov 13 09:08:01 minikube kubelet[9639]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:01 minikube kubelet[9639]: I1113 09:08:01.651887    9639 server.go:410] Version: v1.16.2
Nov 13 09:08:01 minikube kubelet[9639]: I1113 09:08:01.652080    9639 plugins.go:100] No cloud provider specified.
Nov 13 09:08:01 minikube kubelet[9639]: I1113 09:08:01.652104    9639 server.go:773] Client rotation is on, will bootstrap in background
Nov 13 09:08:01 minikube kubelet[9639]: F1113 09:08:01.652139    9639 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Nov 13 09:08:01 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 13 09:08:01 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 13 09:08:02 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Nov 13 09:08:02 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 492.
Nov 13 09:08:02 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 13 09:08:02 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:02 minikube kubelet[9652]: I1113 09:08:02.394057    9652 server.go:410] Version: v1.16.2
Nov 13 09:08:02 minikube kubelet[9652]: I1113 09:08:02.394227    9652 plugins.go:100] No cloud provider specified.
Nov 13 09:08:02 minikube kubelet[9652]: I1113 09:08:02.394248    9652 server.go:773] Client rotation is on, will bootstrap in background
Nov 13 09:08:02 minikube kubelet[9652]: F1113 09:08:02.394280    9652 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Nov 13 09:08:02 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 13 09:08:02 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.
Nov 13 09:08:03 minikube systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Nov 13 09:08:03 minikube systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 493.
Nov 13 09:08:03 minikube systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Nov 13 09:08:03 minikube systemd[1]: Started kubelet: The Kubernetes Node Agent.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Nov 13 09:08:03 minikube kubelet[9665]: I1113 09:08:03.150860    9665 server.go:410] Version: v1.16.2
Nov 13 09:08:03 minikube kubelet[9665]: I1113 09:08:03.151850    9665 plugins.go:100] No cloud provider specified.
Nov 13 09:08:03 minikube kubelet[9665]: I1113 09:08:03.151911    9665 server.go:773] Client rotation is on, will bootstrap in background
Nov 13 09:08:03 minikube kubelet[9665]: F1113 09:08:03.151978    9665 server.go:271] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Nov 13 09:08:03 minikube systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Nov 13 09:08:03 minikube systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**: Ubuntu 18.04.3 LTS

**Comment by tstromberg** [comment] 2019-11-15 02:35
Do you mind sharing the output of `minikube start --alsologtostderr -v=1` as well as:

`minikube ssh 'sudo env PATH=/var/lib/minikube/binaries/v1.16.2:$PATH kubeadm init phase certs all --config /var/tmp/minikube/kubeadm.yaml'`

Thanks!

My guess is that `minikube delete` will probably get passed this issue, but I am curious about the root cause.

**Comment by sharifelgamal** [comment] 2020-01-29 19:54
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

**Closed by sharifelgamal** 2020-01-29 19:54 UTC
Labels: triage/support
