### ISSUE TITLE
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

### ISSUE THREAD

**Issue by pabitrab** [kubernetes/minikube#3859] opened 2019-03-12 10:22 UTC
Hi,
I have installed minikube and kubernetes-cli in Windows 10 Enterprise OS using choco install 

After installing the same and restarting, when I am trying to create the VM, it is giving error: Unable to install as HyperV is already enabled. When I am disabling the HyperV feature and trying it once again after restart, below error is coming
C:\WINDOWS\system32>minikube start
o   minikube v0.35.0 on windows (amd64)
>   Creating virtualbox VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
!   Unable to start VM: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualBox\VBoxManage.exe startvm minikube --type headless failed:
VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedly during startup with exit code -1073741819 (0xc0000005).  More details may be available in 'C:\Users\pabitra_b\.minikube\machines\minikube\minikube\Logs\VBoxHardening.log'
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap, interface IMachine

Also note output pf below commands:
C:\WINDOWS\system32>minikube delete
x   Deleting "minikube" from virtualbox ...
-   The "minikube" cluster has been deleted.

C:\WINDOWS\system32>kubectl config use-context minikube
error: no context exists with the name: "minikube".
C:\WINDOWS\system32>minikube status
host:
kubelet:
apiserver:
kubectl:

**Comment by tstromberg** [comment] 2019-03-13 20:25
What version of VirtualBox are you runinng? I am curious if you could try using the latest stable release (6.0.4) to see if it helps.

https://stackoverflow.com/questions/30837998/oracle-virtualbox-terminated-unexpectedly-wihttps://stackoverflow.com/questions/30837998/oracle-virtualbox-terminated-unexpectedly-with-exit-code-1073741819-0xc000000/32310186th-exit-code-1073741819-0xc000000/32310186 has some more information about this issue.

Thank you!

**Comment by tstromberg** [comment] 2019-03-13 20:26
Also, if updating VirtualBox doesn't help, could you please attach C:\Users\pabitra_b.minikube\machines\minikube\minikube\Logs\VBoxHardening.log ? 

Thank you for your help.

**Comment by tstromberg** [comment] 2019-05-03 18:40
Dupe of #3845

**Closed by tstromberg** 2019-05-03 18:40 UTC
Labels: co/virtualbox, kind/bug, os/windows, priority/awaiting-more-evidence, triage/needs-information

**Comment by luisrojas17** [comment] 2021-11-08 14:38
Nothing that you recommend works. I do not have any antivirus and I still have the same problem.

    Failed to start virtualbox VM. Running "minikube delete" may fix it: creating
    host: create: creating: Unable to start the VM: C:\Program Files\Oracle\VirtualB
    ox\VBoxManage.exe startvm minikube --type headless failed:
    VBoxManage.exe: error: The virtual machine 'minikube' has terminated unexpectedl
    y during startup with exit code 1 (0x1). More details may be available in 'C:\U
    sers\BereniceRE.minikube\machines\minikube\minikube\Logs\VBoxHardening.log'
    VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component MachineWrap,
    interface IMachine

I have intalled windows 8.1 and VirtualBox 6.1.28.
