### ISSUE TITLE
How to uninstall minikube and kubectl completely (Including config files) ?

### ISSUE THREAD

**Issue by akshay-r-1996** [kubernetes/minikube#4765] opened 2019-07-16 03:31 UTC
Can someone help me with uninstalling minikube and kubectl completely?

OS: RHEL 7.2 ( AWS EC2 instance)
Minikube version: minikube version: v1.2.0
Kubectl: Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-19T16:40:16Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}

**Comment by afbjorklund** [comment] 2019-07-16 07:54
Currently there is no automated way to stop minikube or to remove minikube, for the `none` driver.
For the normal drivers we just stop or destroy the VM, which also stop or removes minikube.

Basically one would have to stop/delete the various components, and then clean up containers/images.
The final and smallest step is removing the actual minikube and kubectl binaries in the path.

**Comment by tstromberg** [comment] 2019-07-16 19:49
This issue appears to be a duplicate of #3372, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

For the none driver specifically, https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md has some information about what files get written to.

Thank you for reporting this!

**Closed by tstromberg** 2019-07-16 19:49 UTC
Labels: co/none-driver, kind/feature

**Comment by sanjaygeeky** [comment] 2020-01-10 05:18
Hello
Please refer to page https://minikube.sigs.k8s.io/docs/reference/uninstalling_minikube/
For linux 
In the shell, type in minikube delete to delete the minikube cluster. - Remove the binary using 
rm /usr/local/bin/minikube 
- Remove the directory containing the minikube configuration 
rm -rf ~/.minikube

**Comment by vyom-soft** [comment] 2020-08-12 12:55
Yes agree with sanjaygeeky, also delete .kube, .minikube from $HOME and kubectl etc from /usr/local/bin

**Comment by gitsofian** [comment] 2024-06-30 17:49
> Hello Please refer to page https://minikube.sigs.k8s.io/docs/reference/uninstalling_minikube/ For linux In the shell, type in minikube delete to delete the minikube cluster. - Remove the binary using rm /usr/local/bin/minikube
> 
> * Remove the directory containing the minikube configuration
>   rm -rf ~/.minikube

Great!
