### ISSUE TITLE
How to access postgres running on host OS from inside minikube VM?

### ISSUE THREAD

**Issue by inzem77** [kubernetes/minikube#3095] opened 2018-08-27 20:14 UTC
Hello!
I can't to connect to postgres on my local machine from minikube.  I also try to clear all firewall rules (iptables -F, iptables -t nat -F) on local machine and host machine.

```
$ telnet 192.168.99.1 5432
Connection closed by foreign host
$ ping 192.168.99.1
PING 192.168.99.1 (192.168.99.1): 56 data bytes
64 bytes from 192.168.99.1: seq=0 ttl=64 time=0.305 ms
```

```
cat ~/.minikube/machines/minikube/config.json
{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "192.168.99.100",
        "MachineName": "minikube",
        "SSHUser": "docker",
        "SSHPort": 33905,
        "SSHKeyPath": "/home/inzem/.minikube/machines/minikube/id_rsa",
        "StorePath": "/home/inzem/.minikube",
        "SwarmMaster": false,
        "SwarmHost": "",
        "SwarmDiscovery": "",
        "VBoxManager": {},
        "HostInterfaces": {},
        "CPU": 2,
        "Memory": 2048,
        "DiskSize": 20000,
        "NatNicType": "82540EM",
        "Boot2DockerURL": "file:///home/inzem/.minikube/cache/iso/minikube-v0.20.0.iso",
        "Boot2DockerImportVM": "",
        "HostDNSResolver": false,
        "HostOnlyCIDR": "192.168.99.1/24",
        "HostOnlyNicType": "82540EM",
        "HostOnlyPromiscMode": "deny",
        "UIType": "headless",
        "HostOnlyNoDHCP": false,
        "NoShare": false,
        "DNSProxy": true,
        "NoVTXCheck": false,
        "ShareFolder": ""
    },
    "DriverName": "virtualbox",
    "HostOptions": {  
        "Driver": "",                                                                                                                                                                                  
        "Memory": 0,
        "Disk": 0,
        "EngineOptions": {
            "ArbitraryFlags": null,
            "Dns": null,
            "GraphDir": "",
            "Env": null,
            "Ipv6": false,
            "InsecureRegistry": [
                "10.0.0.0/24"
            ],
            "Labels": null,
            "LogLevel": "",
            "StorageDriver": "",
            "SelinuxEnabled": false,
            "TlsVerify": false,
            "RegistryMirror": null,
            "InstallURL": ""
        },
        "SwarmOptions": {
            "IsSwarm": false,
            "Address": "",
            "Discovery": "",
            "Agent": false,
            "Master": false,
            "Host": "",
            "Image": "",
            "Strategy": "",
            "Heartbeat": 0,
            "Overcommit": 0,
            "ArbitraryFlags": null,
            "ArbitraryJoinFlags": null,
            "Env": null,
            "IsExperimental": false
        },
        "AuthOptions": {
            "CertDir": "/home/inzem/.minikube",
            "CaCertPath": "/home/inzem/.minikube/certs/ca.pem",
            "CaPrivateKeyPath": "/home/inzem/.minikube/certs/ca-key.pem",
            "CaCertRemotePath": "",
            "ServerCertPath": "/home/inzem/.minikube/machines/server.pem",
            "ServerKeyPath": "/home/inzem/.minikube/machines/server-key.pem",
            "ClientKeyPath": "/home/inzem/.minikube/certs/key.pem",
            "ServerCertRemotePath": "",
            "ServerKeyRemotePath": "",
            "ClientCertPath": "/home/inzem/.minikube/certs/cert.pem",
            "ServerCertSANs": null,
            "StorePath": "/home/inzem/.minikube"
        }
    },
    "Name": "minikube"
}
```

Environment:
minikube version: v0.20.0
DriverName: "virtualbox"
iso: minikube-v0.20.0.iso

**Comment by inzem77** [comment] 2018-08-28 04:13
And from my local machine Ubuntu 18.04 i have access to postgres
telnet 192.168.99.1 5432
Trying 192.168.99.1...
Connected to 192.168.99.1.
Escape character is '^]'.

**Comment by tstromberg** [comment] 2018-09-19 16:55
Dupe of #2735

**Closed by tstromberg** 2018-09-19 16:55 UTC
Labels: area/networking, drivers/virtualbox/linux, kind/documentation, platform/linux
