### ISSUE TITLE
Failed to setup kubeconfig: writing kubeconfig

### ISSUE THREAD

**Issue by r77s** [kubernetes/minikube#6056] opened 2019-12-11 11:51 UTC
**The exact command to reproduce the issue**:
minikube start -p cluster1

**The full output of the command that failed**:<details>
C:\Users\renes>minikube start -p cluster1
* [cluster1] minikube v1.6.0 on Microsoft Windows 10 Pro 10.0.18363 Build 18363
* Selecting 'virtualbox' driver from user configuration (alternates: [])
* Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
*
X Failed to setup kubeconfig: writing kubeconfig: Error writing file C:\Users\renes/.kube/config: error acquiring lock for C:\Users\renes/.kube/config: timeout acquiring mutex
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
*
X Error getting config: CreateFile C:\Users\renes\.minikube\profiles\minikube\config.json: Das System kann den angegebenen Pfad nicht finden.
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

Version 6.0.14 r133895 (Qt5.6.2)

**Comment by tstromberg** [comment] 2019-12-11 15:32
This issue appears to be a duplicate of #6058, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-11 15:32 UTC
