### ISSUE TITLE
Unable to Install Ingress Addon in Minikube v1.19.0 on Mac OS 10.15.7

### ISSUE THREAD

**Issue by bpb54321** [kubernetes/minikube#11115] opened 2021-04-16 16:17 UTC
**Steps to reproduce the issue:** 

1. `minikube config set driver hyperkit`
2. `minikube start`
3. `minikube addons enable ingress`

**Full output of failed command:** 
`blosserb@C02Z92BRLVDL ~ % minikube addons enable ingress --alsologtostderr
I0416 12:10:16.623621    2468 out.go:278] Setting OutFile to fd 1 ...
I0416 12:10:16.623906    2468 out.go:330] isatty.IsTerminal(1) = true
I0416 12:10:16.623912    2468 out.go:291] Setting ErrFile to fd 2...
I0416 12:10:16.623916    2468 out.go:330] isatty.IsTerminal(2) = true
I0416 12:10:16.624002    2468 root.go:317] Updating PATH: /Users/blosserb/.minikube/bin
I0416 12:10:16.627467    2468 addons.go:55] Setting ingress=true in profile "minikube"
I0416 12:10:16.627661    2468 addons.go:131] Setting addon ingress=true in "minikube"
I0416 12:10:16.628153    2468 host.go:66] Checking if "minikube" exists ...
I0416 12:10:16.630305    2468 main.go:126] libmachine: Found binary path at /Users/blosserb/.minikube/bin/docker-machine-driver-hyperkit
I0416 12:10:16.632001    2468 main.go:126] libmachine: Launching plugin server for driver hyperkit
I0416 12:10:16.662663    2468 main.go:126] libmachine: Plugin server listening at address 127.0.0.1:55278
I0416 12:10:16.665315    2468 main.go:126] libmachine: () Calling .GetVersion
I0416 12:10:16.668638    2468 main.go:126] libmachine: Using API Version  1
I0416 12:10:16.668662    2468 main.go:126] libmachine: () Calling .SetConfigRaw
I0416 12:10:16.669290    2468 main.go:126] libmachine: () Calling .GetMachineName
I0416 12:10:16.669742    2468 main.go:126] libmachine: Found binary path at /Users/blosserb/.minikube/bin/docker-machine-driver-hyperkit
I0416 12:10:16.669780    2468 main.go:126] libmachine: Launching plugin server for driver hyperkit
I0416 12:10:16.678348    2468 main.go:126] libmachine: Plugin server listening at address 127.0.0.1:55284
I0416 12:10:16.678971    2468 main.go:126] libmachine: () Calling .GetVersion
I0416 12:10:16.679505    2468 main.go:126] libmachine: Using API Version  1
I0416 12:10:16.679531    2468 main.go:126] libmachine: () Calling .SetConfigRaw
I0416 12:10:16.679848    2468 main.go:126] libmachine: () Calling .GetMachineName
I0416 12:10:16.679996    2468 main.go:126] libmachine: (minikube) Calling .GetState
I0416 12:10:16.680208    2468 main.go:126] libmachine: (minikube) DBG | exe=/Users/blosserb/.minikube/bin/docker-machine-driver-hyperkit uid=0
I0416 12:10:16.681410    2468 main.go:126] libmachine: (minikube) DBG | hyperkit pid from json: 94788
I0416 12:10:16.684032    2468 main.go:126] libmachine: (minikube) Calling .DriverName
I0416 12:10:16.714085    2468 out.go:157]     ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
I0416 12:10:16.740030    2468 out.go:157]     ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
I0416 12:10:16.766888    2468 out.go:157]     ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
I0416 12:10:16.767216    2468 addons.go:261] installing /etc/kubernetes/addons/ingress-configmap.yaml
I0416 12:10:16.768515    2468 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/ingress-configmap.yaml (1865 bytes)
I0416 12:10:16.768877    2468 main.go:126] libmachine: (minikube) Calling .GetSSHHostname
I0416 12:10:16.769070    2468 main.go:126] libmachine: (minikube) Calling .GetSSHPort
I0416 12:10:16.769166    2468 main.go:126] libmachine: (minikube) Calling .GetSSHKeyPath
I0416 12:10:16.769261    2468 main.go:126] libmachine: (minikube) Calling .GetSSHUsername
I0416 12:10:16.769648    2468 sshutil.go:53] new ssh client: &{IP:192.168.64.5 Port:22 SSHKeyPath:/Users/blosserb/.minikube/machines/minikube/id_rsa Username:docker}
I0416 12:10:16.820113    2468 addons.go:261] installing /etc/kubernetes/addons/ingress-rbac.yaml
I0416 12:10:16.820137    2468 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/ingress-rbac.yaml (6005 bytes)
I0416 12:10:16.829579    2468 addons.go:261] installing /etc/kubernetes/addons/ingress-dp.yaml
I0416 12:10:16.829599    2468 ssh_runner.go:316] scp memory --> /etc/kubernetes/addons/ingress-dp.yaml (9125 bytes)
I0416 12:10:16.839849    2468 ssh_runner.go:149] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.20.2/kubectl apply -f /etc/kubernetes/addons/ingress-configmap.yaml -f /etc/kubernetes/addons/ingress-rbac.yaml -f /etc/kubernetes/addons/ingress-dp.yaml
I0416 12:10:17.155196    2468 main.go:126] libmachine: Making call to close driver server
I0416 12:10:17.155216    2468 main.go:126] libmachine: (minikube) Calling .Close
I0416 12:10:17.155444    2468 main.go:126] libmachine: (minikube) DBG | Closing plugin on server side
I0416 12:10:17.155470    2468 main.go:126] libmachine: Successfully made call to close driver server
I0416 12:10:17.155480    2468 main.go:126] libmachine: Making call to close connection to plugin binary
I0416 12:10:17.155490    2468 main.go:126] libmachine: Making call to close driver server
I0416 12:10:17.155498    2468 main.go:126] libmachine: (minikube) Calling .Close
I0416 12:10:17.155695    2468 main.go:126] libmachine: (minikube) DBG | Closing plugin on server side
I0416 12:10:17.155739    2468 main.go:126] libmachine: Successfully made call to close driver server
I0416 12:10:17.155754    2468 main.go:126] libmachine: Making call to close connection to plugin binary
I0416 12:10:17.155768    2468 addons.go:299] Verifying addon ingress=true in "minikube"
I0416 12:10:17.183193    2468 out.go:157] 🔎  Verifying ingress addon...
🔎  Verifying ingress addon...
I0416 12:10:17.212524    2468 kapi.go:75] Waiting for pod with label "app.kubernetes.io/name=ingress-nginx" in ns "ingress-nginx" ...
I0416 12:10:17.237259    2468 kapi.go:86] Found 3 Pods for label selector app.kubernetes.io/name=ingress-nginx
I0416 12:10:17.237273    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:17.744143    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:18.245470    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:18.745013    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:19.244857    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:19.744685    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:20.247990    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:20.744229    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:21.247578    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:21.742609    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:22.248951    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:22.744788    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:23.246277    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:23.743966    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:24.246100    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:24.740377    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:25.244110    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:25.744590    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:26.246720    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:26.744157    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:27.244204    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:27.744483    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:28.245728    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:28.744065    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:29.245954    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:29.743687    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:30.243457    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:30.744305    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:31.242030    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:31.744186    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:32.244382    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:32.745396    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:33.247336    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:33.741069    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:34.240940    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:34.745446    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:35.243222    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:35.744852    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:36.246133    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:36.744358    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:37.243890    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:37.743242    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:38.248224    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:38.744339    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:39.243244    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:39.744072    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:40.243930    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:40.744875    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:41.243306    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:41.744235    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:42.249544    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:42.743813    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:43.243338    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:43.743985    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:44.248560    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:44.745368    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:45.241264    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:45.747406    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:46.245838    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:46.745068    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:47.245402    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:47.743581    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:48.246315    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:48.744794    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:49.243437    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:49.744493    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:50.244881    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:50.745858    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:51.243311    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:51.744825    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:52.248304    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:52.743920    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:53.243104    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:53.740669    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0416 12:10:54.240967    2468 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose
`

**Full output of `minikube start` command used, if not already included:**
blosserb@C02Z92BRLVDL ~ % minikube start
😄  minikube v1.19.0 on Darwin 10.15.7
✨  Using the hyperkit driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing hyperkit VM for "minikube" ...
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.20.2 on Docker 20.10.4 ...
🔎  Verifying Kubernetes components...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by spowelljr** [comment] 2021-04-19 22:29
@bpb54321 Someone had this same issue #11147 they deleted ~/.minikube and their issue was fixed. Did you update from an older version of minikube before v1.19.0?

**Comment by medyagh** [comment] 2021-04-24 16:32
thank you everyone for reporting this bug, this seems to be side effect of this PR #10879 that we tried to update the ingress to new version, unfortunately our integration test did not catch this problem,
Please stay tuned, we will create a fix for this and hopefully by adding an integration test this should never happen again.

meanwhile could you try

```
kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
```

and see if that fixes the problem ?

I suspect this is dupe of #11121 if you dont mind I will close this to track it one location  https://github.com/kubernetes/minikube/issues/11121

**Closed** 2021-04-24 16:33 UTC
Labels: addon/ingress, kind/support

**Comment by iketiunn** [comment] 2021-04-28 02:40
> @bpb54321
> thank you everyone for reporting this bug, this seems to be side effect of this PR #10879 that we tried to update the ingress to new version, unfortunately our integration test did not catch this problem,
> Please stay tuned, we will create a fix for this and hopefully by adding an integration test this should never happen again.
> 
> meanwhile could you try
> 
> ```
> kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
> ```
> 
> and see if that fixes the problem ?
> 
> I suspect this is dupe of #11121 if you dont mind I will close this to track it one location #11121

This command fixed my problem below after upgrade to `1.19.0`:
```
[fatal]  error deploying: error deploying dasiot: Unable to deploy helm chart: error during 'helm upgrade dasiot ./charts/dasiot --namespace dev --values /var/folders/3w/xp5s6nds4lx8yrhpymrr89lr0000gn/T/581844760 --install --kube-context minikube': Error: UPGRADE FAILED: failed to create resource: Internal error occurred: failed calling webhook "validate.nginx.ingress.kubernetes.io": an error on the server ("") has prevented the request from succeeding
```
