### ISSUE TITLE
8443

### ISSUE THREAD

**Issue by pretham** [kubernetes/minikube#5474] opened 2019-09-26 17:28 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by medyagh** [comment] 2019-09-26 19:02
Hi @pretham I couldn't figure out what the issue is, If you don't mind, could you please provide:

- The exact command-lines used, so that we may replicate the issue
- The full output of the command that failed
- The full output of the "minikube logs" command
- Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment] 2019-09-28 15:47
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Closed by tstromberg** 2019-09-28 15:47 UTC
Labels: triage/needs-information
