### ISSUE TITLE
minikube tunnel -> X

### ISSUE THREAD

**Issue by deepdad** [kubernetes/minikube#4937] opened 2019-08-01 08:49 UTC
The readme says:

> "Minikube today only exposes a single IP address for all cluster and VM communication. This effectively requires users to connect to any running Pods, Services or LoadBalancers over ClusterIPs, which can require modifications to workflows when compared to developing against a production cluster.
> 
> A main goal of Minikube is to minimize the differences required in code and configuration between development and production, so this is not ideal. "

This is not really true. The NodePorts can be exposed to the host (when minikube uses the VirtualBox hypervisor) by adding port forwarding to the NAT network adapter or Sloka or Rodriguez' work arounds. You would expect that they are then reachable from the internet when port forwarding on your gateway (router). However, for some reason, the ports remain limited to the user (not root).
./ncat -l -p 8080 --sh-exec "./ncat 127.0.0.1 8080"
bypasses this without sudo. I guess `sudo route` can make this permanent. Of course this looks silly; forwarding port 8080 to port 8080.
My guess is the NGINX that controls the NAT access to the cluster is the NGINX one but I don't know how to check this. I also don't know how to get other pods (services) on that NAT adapter. I also don't know if Redriguez' work around makes the Load Balancer he adds internet accessible or just to the user on the Host.

I think that if you want minikube to resemble a production setup, then ingress like Traefik and Ambassador minikube tutorials should really fork minikube and replace whatever (nginx) is blocking the stuff or you make the minikube NGINX instance that is gatekeeping, itself amenable to internet access ( I think Traefik does this with a Helm chart but my understanding is so far limited).

* You should also remove the standard Shared Folder on VirtualBox and guide users how and when to use it.

**Comment by afbjorklund** [comment] 2019-08-01 11:07
> * You should also remove the standard Shared Folder on VirtualBox and guide users how and when to use it.

Please open a separate issue about this, it's a standard machine feature (that can be turned off)

```go
	DisableDriverMounts bool               // Only used by virtualbox
```
It's controlled by a flag to `minikube start`:

     --disable-driver-mounts             Disables the filesystem mounts provided by the hypervisors (vboxfs, xhyve-9p)

**Comment by tstromberg** [comment] 2019-08-01 18:33
I don't quite understand what the issue is here? I understand that this is in reference to a design doc: https://github.com/kubernetes/minikube/blob/master/docs/tunnel.md

PR's are welcome.

**Comment by tstromberg** [comment] 2019-09-20 22:05
Closing as there isn't a clear path to resolution here. PR's welcome!

**Closed by tstromberg** 2019-09-20 22:05 UTC
Labels: kind/documentation, priority/awaiting-more-evidence
