### ISSUE TITLE
مشکل در ایجاد کلید برای تایم زون های مثبت

### ISSUE THREAD

**Issue by Cinorid** [kubernetes/minikube#13778] opened 2022-03-13 06:26 UTC
به نظر میرسد که Certificate ایجاد شده و تاریخ و تایم زون ماشین مجازی با هم مطابقت ندارند و خطای معتبور نبودن Certificate  را میدهد.
Timezone: +4:30

**کامندی که مشکل را به وجود می آورد**: 
1. minikube start --driver vmware
2. minikube stop
3. minikube start

**خروجی کامل کامند مورد مشکل:**:
<details>
minikube start
😄  minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19043 Build 19043
✨  Using the vmware driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing vmware VM for "minikube" ...
🐳  Preparing Kubernetes v1.23.3 on Docker 20.10.12 ...
    ▪ kubelet.housekeeping-interval=5m
    ▪ Generating certificates and keys ...
💢  initialization failed, will try again: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:22.721303    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:23.718792    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:23.719661    3974 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:23Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

    ▪ Generating certificates and keys ...

💣  Error starting cluster: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:24.013181    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:24.544839    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:24.545194    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:24Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

❌  Exiting due to GUEST_START: wait: /bin/bash -c "sudo env PATH="/var/lib/minikube/binaries/v1.23.3:$PATH" kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,Mem": Process exited with status 1
stdout:
[init] Using Kubernetes version: v1.23.3
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[certs] Using certificateDir folder "/var/lib/minikube/certs"
[certs] Using existing ca certificate authority
[certs] Using existing apiserver certificate and key on disk
[certs] Using existing apiserver-kubelet-client certificate and key on disk
[certs] Using existing front-proxy-ca certificate authority

stderr:
W0313 06:25:24.013181    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy CA: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
        [WARNING DirAvailable--var-lib-minikube-etcd]: /var/lib/minikube/etcd is not empty
W0313 06:25:24.544839    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-ca: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2032-03-10 09:34:34 +0000 UTC
W0313 06:25:24.545194    4085 certs.go:524] WARNING: could not validate bounds for certificate front-proxy-client: the certificate is not valid yet: NotBefore: 2022-03-13 09:34:34 +0000 UTC, NotAfter: 2023-03-13 09:34:35 +0000 UTC
error execution phase certs/front-proxy-client: [certs] certificate front-proxy-client not signed by CA certificate front-proxy-ca: x509: certificate has expired or is not yet valid: current time 2022-03-13T06:25:24Z is before 2022-03-13T09:34:34Z
To see the stack trace of this error execute with --v=5 or higher

╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯

</details>

**سیستم عامل مورد استفاده با ذکر ورژن**:
minikube v1.25.2 on Microsoft Windows 10 Enterprise 10.0.19043 Build 19043

**Comment by spowelljr** [comment] 2022-03-24 22:57
Hi @Cinorid, I believe this issue is a duplicate of https://github.com/kubernetes/minikube/issues/13779 which you also created, but this one is in Persian. I'm going to close this issue, but if there's a reason to keep this one open feel free to state your reason and reopen it, thanks!

-----

سلام @Cinorid، من فکر می کنم این شماره تکراری از https://github.com/kubernetes/minikube/issues/13779 است که شما هم ساختید، اما این یکی فارسی است. من قصد دارم این موضوع را ببندم، اما اگر دلیلی برای باز نگه داشتن این موضوع وجود دارد، دلیل خود را بیان کنید و آن را دوباره باز کنید، متشکرم!

**Closed by spowelljr** 2022-03-24 22:57 UTC
Labels: l/fa
