### ISSUE TITLE
minikube start -- allow additional arguments to --mount-string

### ISSUE THREAD

**Issue by cmeyertons** [kubernetes/minikube#3529] opened 2019-01-12 12:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
I'm leaning towards bug report as I would expect `--mount-string` to mimic `minikube mount`

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.32.0
- **OS** (e.g. from /etc/os-release): Windows 10
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.32.0
- **Install tools**:

**What happened**:
Additional `mount` arguments passed into `--mount-string` are ignored
Ran 
```
minikube start --mount --mount-string="C:\mydrive:/mydrive --uid 911 --gid 911 --9p-version=9p2000.L"
minikube ssh
ls -l /mydrive
```

**What you expected to happen**:
expected it to properly set ownership of `/mydrive` to 911 as a workaround to #2290 

**How to reproduce it** (as minimally and precisely as possible): see what happened

**Comment by tstromberg** [comment] 2019-01-23 17:43
Dupe of #3327

**Closed** 2019-02-19 23:59 UTC
Labels: area/mount, help wanted, kind/bug, os/windows, priority/awaiting-more-evidence
