### ISSUE TITLE
virtualbox: Failed to start host: recreate: creating host: create: creating: write |1: The pipe has been ended.

### ISSUE THREAD

**Issue by r1k2v** [kubernetes/minikube#8791] opened 2020-07-21 09:49 UTC
**Steps to reproduce the issue:** 

1. I am starting minikube.
2. I have written code  "minikube start --driver=virtualbox" on window 10.
3. I got given error " Failed to start host: recreate: creating host: create: creating: write |1: The pipe has been ended."

**Full output of failed command:** 
 minikube v1.11.0 on Microsoft Windows 10 Home Single Language 10.0.19041 Build 19041
* Using the virtualbox driver based on user configuration
* Downloading VM boot image ...
    > minikube-v1.11.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.11.0.iso: 174.99 MiB / 174.99 MiB [ 100.00% 2.87 MiB p/s 1m1s
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
! StartHost failed, but will try again: creating host: create host timed out in 240.000000 seconds
* virtualbox "minikube" VM is missing, will recreate.
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start virtualbox VM. "minikube start" may fix it: recreate: creating host: create: creating: write |1: The pipe has been ended.
*
X error provisioning host: Failed to start host: recreate: creating host: create: creating: write |1: The pipe has been ended.
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by tstromberg** [comment] 2020-07-22 17:50
This issue appears to be a duplicate of #7298, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

In the mean-time, you may be able to get further by specifying `--disk-size=10g`. 

Thank you for reporting this!

**Closed** 2020-08-12 18:57 UTC
Labels: co/virtualbox, triage/support
