### ISSUE TITLE
--dns-domain has no effect

### ISSUE THREAD

**Issue by iMartyn** [kubernetes/minikube#2191] opened 2017-11-14 11:24 UTC
Please provide the following details:

**Environment**: 
OS:
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

VM driver:
    "DriverName": "virtualbox",

ISO version
        "Boot2DockerURL": "file:///home/ranyardm/.minikube/cache/iso/minikube-v0.23.6.iso",

**What happened**:
```minikube start --dns-domain cluster.minikube``` still uses `cluster.local` as the root of cluster dns records.

**What you expected to happen**:
Cluster should use `cluster.minikube` as the root of dns records (e.g. `kube-dns.kube-system.svc.cluster.minikube`)

**How to reproduce it** (as minimally and precisely as possible):
```
minikube start --dns-domain cluster.minikube
minikube ssh
nslookup kube-dns.kube-system.svc.cluster.local 10.0.0.10 (bug, returns ip, should return NXDOMAIN)
nslookup kube-dns.kube-system.svc.cluster.minikube 10.0.0.10 (bug, returns NXDOMAIN, should return 10.0.0.10)
```

**Output of `minikube logs` (if applicable)**:
n/a

**Anything else do we need to know**:
As per https://pastebin.com/Suy2MeJY, localkube does get passed `--dns-domain=cluster.minikube` so the bug is in localkube rather than minikube I fear.

**Comment by r2d4** [comment] 2017-11-14 17:48
I'm going to close this as a dupe of #1674.  This is a known issue.

**Closed by r2d4** 2017-11-14 17:48 UTC
