### ISSUE TITLE
minikube addons enable ingress failed

### ISSUE THREAD

**Issue by sruby** [kubernetes/minikube#12071] opened 2021-07-29 01:45 UTC
**重现问题所需的命令**：
`minikube addons enable ingress`
**失败的命令的完整输出**：<details>
`Using image k8s.gcr.io/ingress-nginx/controller:v0.44.0
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Using image docker.io/jettech/kube-webhook-certgen:v1.5.1
🔎  Verifying ingress addon...

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

╭─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                                                         │
│    😿  If the above advice does not help, please let us know:                                                           │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                                                         │
│                                                                                                                         │
│    Please attach the following file to the GitHub issue:                                                                │
│    - /var/folders/0c/yx5vrh2145vc89d7l2gtqbqh0000gn/T/minikube_addons_6e4c6de46d86f50bb3ee2b2eb678cef24aeb54a2_0.log    │
│                                                                                                                         │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

`

</details>

**`minikube logs`命令的输出**： <details>
There are no logs after executing minikube addons enable ingress, these are history  logs.
`Jul 28 20:57:34 minikube kubelet[3807]: E0728 20:57:34.192733    3807 pod_workers.go:191] Error syncing pod 0e512a2b-4c63-4d4b-b608-06c3878b11d1 ("ingress-nginx-controller-5d88495688-w6zz8_ingress-nginx(0e512a2b-4c63-4d4b-b608-06c3878b11d1)"), skipping: failed to "StartContainer" for "controller" with ImagePullBackOff: "Back-off pulling image \"k8s.gcr.io/ingress-nginx/controller:v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a\""
Jul 28 20:57:49 minikube kubelet[3807]: E0728 20:57:49.190773    3807 pod_workers.go:191] Error syncing pod 0e512a2b-4c63-4d4b-b608-06c3878b11d1 ("ingress-nginx-controller-5d88495688-w6zz8_ingress-nginx(0e512a2b-4c63-4d4b-b608-06c3878b11d1)"), skipping: failed to "StartContainer" for "controller" with ImagePullBackOff: "Back-off pulling image \"k8s.gcr.io/ingress-nginx/controller:v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a\""
Jul 28 20:58:00 minikube kubelet[3807]: E0728 20:58:00.192760    3807 pod_workers.go:191] Error syncing pod 0e512a2b-4c63-4d4b-b608-06c3878b11d1 ("ingress-nginx-controller-5d88495688-w6zz8_ingress-nginx(0e512a2b-4c63-4d4b-b608-06c3878b11d1)"), skipping: failed to "StartContainer" for "controller" with ImagePullBackOff: "Back-off pulling image \"k8s.gcr.io/ingress-nginx/controller:v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a\""
Jul 28 20:58:14 minikube kubelet[3807]: E0728 20:58:14.190542    3807 pod_workers.go:191] Error syncing pod 0e512a2b-4c63-4d4b-b608-06c3878b11d1 ("ingress-nginx-controller-5d88495688-w6zz8_ingress-nginx(0e512a2b-4c63-4d4b-b608-06c3878b11d1)"), skipping: failed to "StartContainer" for "controller" with ImagePullBackOff: "Back-off pulling image \"k8s.gcr.io/ingress-nginx/controller:v0.44.0@sha256:3dd0fac48073beaca2d67a78c746c7593f9c575168a17139a9955a82c63c4b9a\""

==> storage-provisioner [252921564eff] <==
I0728 19:53:16.718777       1 storage_provisioner.go:116] Initializing the minikube storage provisioner...
I0728 19:53:16.799412       1 storage_provisioner.go:141] Storage provisioner initialized, now starting service!
I0728 19:53:16.799764       1 leaderelection.go:243] attempting to acquire leader lease kube-system/k8s.io-minikube-hostpath...
I0728 19:53:34.977952       1 leaderelection.go:253] successfully acquired lease kube-system/k8s.io-minikube-hostpath
I0728 19:53:34.983904       1 event.go:282] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"kube-system", Name:"k8s.io-minikube-hostpath", UID:"295b2409-7cd2-4b15-84f2-ccf31408ca1e", APIVersion:"v1", ResourceVersion:"3014", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' minikube_e75d9602-5d5a-4df9-a716-467198783744 became leader
I0728 19:53:34.987390       1 controller.go:835] Starting provisioner controller k8s.io/minikube-hostpath_minikube_e75d9602-5d5a-4df9-a716-467198783744!
I0728 19:53:35.491736       1 controller.go:884] Started provisioner controller k8s.io/minikube-hostpath_minikube_e75d9602-5d5a-4df9-a716-467198783744!

==> storage-provisioner [77afce2c93ff] <==
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc0001af300, 0x18b3d60, 0xc0001b1440, 0x1, 0xc000082540)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:156 +0x9b
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0001af300, 0x3b9aca00, 0x0, 0x1, 0xc000082540)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:133 +0x98
k8s.io/apimachinery/pkg/util/wait.Until(0xc0001af300, 0x3b9aca00, 0xc000082540)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/wait/wait.go:90 +0x4d
created by sigs.k8s.io/sig-storage-lib-external-provisioner/v6/controller.(*ProvisionController).Run.func1
	/Users/medya/go/pkg/mod/sigs.k8s.io/sig-storage-lib-external-provisioner/v6@v6.3.0/controller/controller.go:881 +0x3d6

goroutine 4563 [sync.Cond.Wait, 6 minutes]:
sync.runtime_notifyListWait(0xc000207220, 0xc000000000)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc000207210)
	/usr/local/go/src/sync/cond.go:56 +0x99
golang.org/x/net/http2.(*pipe).Read(0xc000207208, 0xc000399a00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/Users/medya/go/pkg/mod/golang.org/x/net@v0.0.0-20201224014010-6772e930b67b/http2/pipe.go:65 +0x97
golang.org/x/net/http2.transportResponseBody.Read(0xc0002071e0, 0xc000399a00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/Users/medya/go/pkg/mod/golang.org/x/net@v0.0.0-20201224014010-6772e930b67b/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc0002074a0, 0x2, 0x7f701e23d858)
	/usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc0002074a0, 0x0, 0x0, 0x152aee0)
	/usr/local/go/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc0002074a0, 0x154a160, 0xc0002fa0f0, 0x203000, 0x203000)
	/usr/local/go/src/encoding/json/stream.go:63 +0x7c
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc00014ed80, 0xc000200c00, 0x400, 0x400, 0x40, 0x38, 0x15b0440)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/framer/framer.go:152 +0x1a8
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0004a4190, 0x0, 0x18bc168, 0xc00055b240, 0xffffffffffffffff, 0xff00000000000020, 0xc000056cd0, 0x8c0686, 0x179f200)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0000754c0, 0xc0004e6cc0, 0xc000056cd0, 0x8c0613, 0x179f1c8, 0x0, 0xc000056f32)
	/Users/medya/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/watch/decoder.go:49 +0x6e
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00055b200)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/watch/streamwatcher.go:71 +0xbe

goroutine 4793 [sync.Cond.Wait, 5 minutes]:
sync.runtime_notifyListWait(0xc00035c720, 0xc000000000)
	/usr/local/go/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc00035c710)
	/usr/local/go/src/sync/cond.go:56 +0x99
golang.org/x/net/http2.(*pipe).Read(0xc00035c708, 0xc000659e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/Users/medya/go/pkg/mod/golang.org/x/net@v0.0.0-20201224014010-6772e930b67b/http2/pipe.go:65 +0x97
golang.org/x/net/http2.transportResponseBody.Read(0xc00035c6e0, 0xc000659e00, 0x200, 0x200, 0x0, 0x0, 0x0)
	/Users/medya/go/pkg/mod/golang.org/x/net@v0.0.0-20201224014010-6772e930b67b/http2/transport.go:2108 +0xaf
encoding/json.(*Decoder).refill(0xc00035c9a0, 0x2, 0x7f701e2a7ec0)
	/usr/local/go/src/encoding/json/stream.go:165 +0xeb
encoding/json.(*Decoder).readValue(0xc00035c9a0, 0x0, 0x0, 0x152aee0)
	/usr/local/go/src/encoding/json/stream.go:140 +0x1ff
encoding/json.(*Decoder).Decode(0xc00035c9a0, 0x154a160, 0xc0003c9c50, 0x203000, 0x203000)
	/usr/local/go/src/encoding/json/stream.go:63 +0x7c
k8s.io/apimachinery/pkg/util/framer.(*jsonFrameReader).Read(0xc0002058c0, 0xc000380400, 0x400, 0x400, 0x40, 0x38, 0x15b0440)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/util/framer/framer.go:152 +0x1a8
k8s.io/apimachinery/pkg/runtime/serializer/streaming.(*decoder).Decode(0xc0001b9b30, 0x0, 0x18bc168, 0xc00055b940, 0xffffffffffffffff, 0xff00000000000020, 0xc0005dc4d0, 0x8c0686, 0x179f200)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/runtime/serializer/streaming/streaming.go:77 +0x89
k8s.io/client-go/rest/watch.(*Decoder).Decode(0xc0002f5ca0, 0xc0001d3980, 0xc0005dc4d0, 0x8c0613, 0x179f1c8, 0x0, 0xc0005dc732)
	/Users/medya/go/pkg/mod/k8s.io/client-go@v0.20.5/rest/watch/decoder.go:49 +0x6e
k8s.io/apimachinery/pkg/watch.(*StreamWatcher).receive(0xc00055b900)
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/watch/streamwatcher.go:104 +0x14a
created by k8s.io/apimachinery/pkg/watch.NewStreamWatcher
	/Users/medya/go/pkg/mod/k8s.io/apimachinery@v0.20.5/pkg/watch/streamwatcher.go:71 +0xbe`
</details>

**使用的操作系统版本**：
macOS Big Sur 11.4

**other try**
I already load image into minikube, but minikube always pull image from remote, how change pull image policy? let it use local image.
`$ docker images
REPOSITORY                                TAG        IMAGE ID       CREATED         SIZE
k8s.gcr.io/kube-proxy                     v1.20.7    ff54c88b8ecf   2 months ago    118MB
k8s.gcr.io/kube-controller-manager        v1.20.7    22d1a2072ec7   2 months ago    116MB
k8s.gcr.io/kube-apiserver                 v1.20.7    034671b24f0f   2 months ago    122MB
k8s.gcr.io/kube-scheduler                 v1.20.7    38f903b54010   2 months ago    47.3MB
gcr.io/k8s-minikube/storage-provisioner   v5         6e38f40d628d   4 months ago    31.5MB
k8s.gcr.io/ingress-nginx/controller       v0.44.0    435df390f367   5 months ago    279MB
kubernetesui/dashboard                    v2.1.0     9a07b5b4bfac   7 months ago    226MB
jettech/kube-webhook-certgen              v1.5.1     a013daf8730d   8 months ago    44.7MB
k8s.gcr.io/etcd                           3.4.13-0   0369cf4303ff   11 months ago   253MB
k8s.gcr.io/coredns                        1.7.0      bfe3a36ebd25   13 months ago   45.2MB
kubernetesui/metrics-scraper              v1.0.4     86262685d9ab   16 months ago   36.9MB
k8s.gcr.io/pause                          3.2        80d28bedfe5d   17 months ago   683kB`

**Comment by apupier** [comment] 2021-07-29 12:29
potential duplicate of https://github.com/kubernetes/minikube/issues/10544

**Comment by spowelljr** [comment] 2021-07-30 21:10
@apupier is right, this is a duplicate of #10544. I'm going to close this issue, but please follow along with #10544, thank you!

**Closed by spowelljr** 2021-07-30 21:10 UTC
Labels: l/zh-CN
