### ISSUE TITLE
IPV6 does not resolve when running on osx/virtualbox

### ISSUE THREAD

**Issue by santouras** [kubernetes/minikube#10339] opened 2021-02-02 05:29 UTC
**Steps to reproduce the issue:** 

1. minikube start
2. eval $(minikube docker-env)
3. docker run --rm -ti alpine:3.13 /bin/ash
4. nslookup google.com
5. echo $?

**Full output of failed command:** 
```
 ➜ docker run -ti --rm alpine:3.13 /bin/ash
/ # nslookup google.com
Server:         10.0.2.3
Address:        10.0.2.3:53

Non-authoritative answer:
Name:   google.com
Address: 172.217.167.78

** server can't find google.com: NXDOMAIN

/ #
```

Adding a Nat Network with IPV6 enabled and adding it to the VM fixes this issue
![image](https://user-images.githubusercontent.com/358368/106556377-86137a80-6573-11eb-840b-0530ece30f2b.png)

![image](https://user-images.githubusercontent.com/358368/106556404-988db400-6573-11eb-8ceb-7a7e74f75220.png)

```
 ➜ docker run -ti --rm alpine:3.13 /bin/ash
/ # nslookup google.com
Server:         10.34.172.6
Address:        10.34.172.6:53

Non-authoritative answer:
Name:   google.com
Address: 2404:6800:4006:80a::200e

Non-authoritative answer:
Name:   google.com
Address: 172.217.167.78

/ #
```

**Comment by sharifelgamal** [comment] 2021-05-05 18:33
Yeah, we don't support IPv6 in minikube at all: https://github.com/kubernetes/minikube/issues/8535

It's on the roadmap, we just don't have the bandwidth to implement it currently.

I'll go ahead and close this as a dupe of the general IPv6 issue.

**Closed by sharifelgamal** 2021-05-05 18:33 UTC
Labels: co/virtualbox, kind/support, triage/long-term-support
