### ISSUE TITLE
downloading binaries: wsasend: An existing connection was forcibly closed by the remote host.

### ISSUE THREAD

**Issue by sivakrishna34** [kubernetes/minikube#4037] opened 2019-04-02 13:25 UTC
Installing Minikube v1.0.0 locally with Kubernetes version 1.14.0 and tried with 1.8.0 , but ending up with above exception of downloading binaries. Please assist. 

Thank you in advance, 
Regards,

**Comment by tstromberg** [comment] 2019-04-05 00:04
Thanks for opening this issue! Do you mind providing the following information:

*  The exact command-lines used so that we can replicate the issue
*  The output of the "minikube logs" command

Thanks!

**Comment by tstromberg** [comment] 2019-04-05 00:05
NOTE: This may be a dupe of #1766

**Closed** 2019-05-14 16:53 UTC
Labels: os/windows, triage/duplicate, triage/needs-information
