### ISSUE TITLE
error getting ssh client: No connection could be made  because the target machine actively refused it.

### ISSUE THREAD

**Issue by pmaheshgupta** [kubernetes/minikube#2866] opened 2018-06-04 09:07 UTC
I am trying to set up minikube on windows10  pro 64bit and hyper-v

Downloaded minikube from [here](https://github.com/kubernetes/minikube#windows).

later trying to start using the following command

> minikube start --vm-driver hyperv --hyperv-virtual-switch "vSwitchKubernetes"

**vSwitchKubernetes**  is an external vswitch created in hyper v.

I am unable to connect to minikube and getting the following errors 

```
minikube : E0601 15:41:56.250187   13560 start.go:159] Error starting host: Error creating host: Error executing step: Provisioning VM.
At line:1 char:1
+ minikube start --vm-driver hyperv --hyperv-virtual-switch "vSwitchKub ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (E0601 15:41:56....rovisioning VM.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
: Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it..
 Retrying.
E0601 15:41:58.120926   13560 start.go:165] Error starting host:  Error creating host: Error executing step: Provisioning VM.
: Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it.
Temporary Error: provisioning: error getting ssh client: Error dialing tcp via ssh client: dial tcp 172.16.49.99:22: connectex: No connection could be made 
because the target machine actively refused it. 
 
```

Tried different options like deleting minikube and starting again,  disabling ipv6 etc..
VT support in bios is enabled.

Any suggestions on how to make it work would be greatly helpful.

Thanks..

**Comment by dlorenc** [comment] 2018-06-04 16:36
Are you running some kind of firewall?

**Comment by suineglive13** [comment] 2018-06-10 11:41
I have exactly the same issue on Win 10 Enterprise build 1709. I've tried to reinstall minikube several times using different ways: minikube-install, chocolatey etc. Also I've tried it with win 10 openssh(with it the error differs). 
I've found some advices to play around with hyperv VM settings, such as RAM and NIC parameters and when I tried'em I just got another errors. So reverted all values to default but still get "refused" at 22 port

**Comment by pmaheshgupta** [comment] 2018-06-12 17:45
after taking the help of admin dept found that I am getting same ip address for both host machine and minikube VM, they said that might be the issue and minikube doesnt have wifi resolving capability.

So tried with LAN, surprisingly it worked.
No I get different IP address for host and VM.

**Comment by tstromberg** [comment] 2018-09-19 17:47
There are indeed some quirks around getting hyperv to a virtual switch on a wifi adapter: https://giritharan.com/configure-hyper-v-to-use-the-wireless-in-a-windows-10-computer/

**Comment by gbraad** [comment] 2018-09-19 22:54
@tstromberg Wireless does not have to be the problem. We are using this to great success with Minishift... so it is likely a different problem. (Note: especially as you refer to using a doc that uses an internal switch instead and NAT, which leads to other issues that need to be solved if using with Minikube as you can not do a static IP).

Active refused most likely means it got blocked... and this can be local system policies if in a corporate environment, but also an application firewall (like antivirus).

**Comment by francisapel** [comment] 2018-11-06 13:28
Same issue as everyone else. Has anyone found a resolution?

**Comment by gerryg80** [comment] 2018-11-21 02:37
I got this same error.  I have a surface tablet / wifi all the time.  I have an Ubuntu 18.04 server running in Hyper-V that I can access from other machines on my network so there's no general Hyper-V issue with wifi.

First time trying minikube I got "connection actively refused" and it was trying 192.168.1.16.  I suspected IP address conflict so I shutdown the minikube VM and 192.168.1.16 was still responding to pings.  192.168.1.16 was actually the IP assigned to my surface / the Hyper-V host.  I started back up the minikube vm and used connect in the Hyper-V admin and confirmed the VM was also attempting to run on 192.168.1.16. So the "connection actively refused" was probably coming from my Surface itself.

A little snooping in the file system and I found this file:  

C:\Users\gerry\.minikube\machines\minikube\config.json

With this content near the top:

{
    "ConfigVersion": 3,
    "Driver": {
        "IPAddress": "",

All I had to do was add an IP address here that is within my network but outside my dhcp range so there's no chance of conflict.  I used 192.168.1.102.

That solved it for me at least -- minikube started with no issues after that.

**Closed** 2018-12-21 02:41 UTC
Labels: area/networking, drv/hyperv, failed/local-networking, firewall-or-proxy-interference, lifecycle/rotten, os/windows, svc/sshd

**Comment by epgeroy** [comment] 2019-01-06 10:48
Restarting the vEthernet "Switch" will make that DHCP assigns a new IP address and it won't be same. This worked for me.

**Comment by cloudmustafa** [comment] 2019-06-06 15:46
Any resolution of this? I keep getting **Error dialing TCP: dial tcp 192.168.34.60:22: connectex: No connection could be made because the target machine actively refused it.** I am starting the Minikube with the Hyper-v virtual switch on Windows 10

**Comment by Diggsey** [comment] 2020-03-05 16:17
I believe this happens with the OOM killer runs. Because the kubernetes supervisor gets killed it doesn't restart, and often the SSH daemon is killed too.

**Comment by dayyehm** [comment] 2020-06-12 20:37
After switching to my wireless connection which is active ,I was connected to VPN and once I disconnected ( I stopped getting forbidden tcp socket messages and the error dialing TCP, of course I disabled ipv6)


[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.0.103

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive ( Hyper-V\Get-VM minikube ).state
[stdout =====>] : Running

[stderr =====>] :
[executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive (( Hyper-V\Get-VM minikube ).networkadapters[0]).ipaddresses[0]
[stdout =====>] : 192.168.0.103

[stderr =====>] :
Moving files into cluster...
I0612 22:33:25.637011   51884 kubeadm.go:220] Container runtime flag provided with no value, using defaults.
Downloading kubelet v1.10.2
Downloading kubeadm v1.10.2


10000 years later .... 

I0612 22:36:33.979541   51884 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: dial tcp 192.168.0.103:8443: connectex: No connection could be made because the target machine actively refused it.]
I0612 22:36:34.471537   51884 round_trippers.go:383] GET https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0612 22:36:34.471537   51884 round_trippers.go:390] Request Headers:
I0612 22:36:34.476541   51884 round_trippers.go:393]     Accept: application/json, */*
I0612 22:36:34.477541   51884 round_trippers.go:393]     User-Agent: minikube.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I0612 22:36:44.479691   51884 round_trippers.go:408] Response Status:  in 10002 milliseconds
I0612 22:36:44.479691   51884 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: net/http: TLS handshake timeout]
I0612 22:36:44.972693   51884 round_trippers.go:383] GET https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0612 22:36:44.972693   51884 round_trippers.go:390] Request Headers:
I0612 22:36:44.974701   51884 round_trippers.go:393]     Accept: application/json, */*
I0612 22:36:44.976703   51884 round_trippers.go:393]     User-Agent: minikube.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I0612 22:36:54.979435   51884 round_trippers.go:408] Response Status:  in 10002 milliseconds
I0612 22:36:54.979435   51884 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: net/http: TLS handshake timeout]
I0612 22:36:55.488804   51884 round_trippers.go:383] GET https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0612 22:36:55.506804   51884 round_trippers.go:390] Request Headers:
I0612 22:36:55.508801   51884 round_trippers.go:393]     Accept: application/json, */*
I0612 22:36:55.540803   51884 round_trippers.go:393]     User-Agent: minikube.exe/v0.0.0 (windows/amd64) kubernetes/$For

I0612 22:37:05.570090   51884 round_trippers.go:408] Response Status:  in 10017 milliseconds
I0612 22:37:05.571092   51884 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: net/http: TLS handshake timeout]
I0612 22:37:05.971738   51884 round_trippers.go:383] GET https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0612 22:37:05.971738   51884 round_trippers.go:390] Request Headers:
I0612 22:37:05.974740   51884 round_trippers.go:393]     Accept: application/json, */*
I0612 22:37:05.980738   51884 round_trippers.go:393]     User-Agent: minikube.exe/v0.0.0 (windows/amd64) kubernetes/$Format
I0612 22:37:15.998155   51884 round_trippers.go:408] Response Status:  in 10012 milliseconds
I0612 22:37:15.999154   51884 kubernetes.go:119] error getting Pods with label selector "k8s-app=kube-proxy" [Get https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy: net/http: TLS handshake timeout]
I0612 22:37:16.473166   51884 round_trippers.go:383] GET https://192.168.0.103:8443/api/v1/namespaces/kube-system/pods?labelSelector=k8s-app%3Dkube-proxy
I0612 22:37:16.473166   51884 round_trippers.go:390] Request Headers:
I0612 22:37:16.474153   51884 round_trippers.go:393]     Accept: application/json, */*
I0612 22:37:16.476157   51884 round_trippers.go:393]     User-Agent: minikube.exe/v0.0.0 (windows/amd64) kubernetes/$For
