### ISSUE TITLE
Unable start minikube 0.25 in macOs High Sierra

### ISSUE THREAD

**Issue by serrodcal** [kubernetes/minikube#2475] opened 2018-01-27 17:25 UTC
**This is a BUG Report**.

**Environment**:

**Minikube version**: v0.25.0
- **OS**: macOS 10.13.3
- **VM Driver**: "DriverName": "virtualbox",
- **ISO version**: minikube-v0.25.1.iso
- **Install tools**: 
- **Others**:

**What happened**:

Minikube fails to start.

```
$ minikube start
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E0127 18:21:42.199759    4382 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: ~/.minikube/cache/localkube/localkube-v1.9.0: open ~/.minikube/cache/localkube/localkube-v1.9.0: no such file or directory
```

**What you expected to happen**:

Minikube should start.

**How to reproduce it**: 

`$ minikube start`.

**Output of `minikube logs` (if applicable)**: 

No entries.

**Anything else do we need to know**:

Minikube has been installed using brew cask.

And the directory ~/.minikube/cache/localkube/localkube-v1.9.0 referenced does not exist, and the ~/.minikube/cache/localkube directory is empty.

**Comment by afbjorklund** [comment] 2018-01-27 19:12
Duplicate of #2472

**Closed** 2018-01-27 19:52 UTC
