### ISSUE TITLE
macOS catalina: Error in driver during machine creation: hyperkit crashed

### ISSUE THREAD

**Issue by stherrien** [kubernetes/minikube#5780] opened 2019-10-30 01:31 UTC
**The exact command to reproduce the issue**:
minikube start
😄  minikube v1.5.1 on Darwin 10.15
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**The full output of the command that failed**:<details>

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:

**Comment by ebokov** [comment] 2019-10-31 09:34
Have same exception. I'm working with Virtual VM  - not with hyperkit. Ading --vm-driver=virtualbox solved the issue for me.

**Comment by scalaster** [comment] 2019-10-31 16:57
Had the same exception. Here are the things I had to do to fix it. 

1. I had installed hyperkit using the instructions on their github repo. I uninstalled hyperkit and reinstalled it using homebrew. I guess the instructions on github didn't install a compatible version whereas homebrew did it. 
2. I deleted ~/.minikube and ran `minikube start` again. 

I had other unrelated errors coz I was behind the proxy. I followed the instructions in the documentation here https://minikube.sigs.k8s.io/docs/reference/networking/proxy/ except I had to add one more CIDR in NO_PROXY environment variable: 192.168.64.0/24 because hyperkit kept assigning IP to VM in that range

**Comment by vvuibert** [comment] 2019-10-31 17:24
@scalaster your solution also worked for me. thanks!

**Comment by ubozov** [comment] 2019-11-02 15:32
I had the same errors that was solved after the `docker` upgrade.

**Comment by medyagh** [comment] 2019-11-04 23:24
@stherrien  @ebokov @scalaster @vvuibert 

this is a duplicate issue of https://github.com/kubernetes/minikube/issues/5594#issuecomment-548583815

the problem is the hyperkit bug, and hyperkit needs to be upgraded see https://github.com/kubernetes/minikube/issues/5594#issuecomment-548583815

closing this.

**Comment by tstromberg** [comment] 2019-11-06 19:35
This is related to #5594 - but has a different signature.

**Comment by SaberMyKing** [comment] 2020-01-23 04:29
Just try this:
```
brew link --overwrite hyperkit
```
Then everything will be ok.

**Comment by medyagh** [comment] 2020-03-04 19:46
@stherrien do you mind trying the solution provided in the comment ? https://github.com/kubernetes/minikube/issues/5780#issuecomment-577498912

**Comment by tstromberg** [comment] 2020-04-15 23:52
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Closed by tstromberg** 2020-04-15 23:52 UTC
Labels: long-term-support, os/macos, top-10-issues, triage/needs-information, triage/support

**Comment by oyemeLife** [comment] 2020-05-20 14:01
> Just try this:
> 
> ```
> brew install hyperkit  # skip if installed
> brew link --overwrite hyperkit
> ```
> 
> Then everything will be ok.

thanks, It's just worked.

**Comment by yhyecho** [comment] 2020-07-10 11:13
> Just try this:
> 
> ```
> brew install hyperkit  # skip if installed
> brew link --overwrite hyperkit
> ```
> 
> Then everything will be ok.

thanks it's ok

**Comment by gayatrisarnobat** [comment] 2025-03-11 05:52
We can use the default Docker driver for Minikube on macOS Apple Silicon chips. To do this, we need to install the arm64 version of Minikube and start it with the default Docker driver.

1. First uninstall the existing Minikube setup by executing 
`brew uninstall minikube`

2. Remove the ".minikube" directory:
`rm -rf ~/.minikube`

3. Install the arm64 version of Minikube:
`curl -LO https://github.com/kubernetes/minikube/releases/latest/download/minikube-darwin-arm64 && sudo install minikube-darwin-arm64 /usr/local/bin/minikube`

4. Run Minikube:
`minikube start --driver=docker`

The above setup works on macOS Sequoia Version 15.0.1, Apple M2 Chip.
