### ISSUE TITLE
docker inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" minikube: exit status 1

### ISSUE THREAD

**Issue by hasibh64** [kubernetes/minikube#8739] opened 2020-07-17 01:07 UTC
I am unable to start minikube on my oracle virtualbox with guest ubuntu.
i got following error screenshot.

![image](https://user-images.githubusercontent.com/42130524/87737170-96ede000-c81d-11ea-9a57-69895e70437b.png)

**Comment by priyawadhwa** [comment] 2020-07-17 15:01
Hey @hasibh64 this error happens because of a race condition when mounting the "/var" directory. We have an issue open for that here: 

https://github.com/kubernetes/minikube/issues/8179

and we recently closed a duplicate of this issue here: https://github.com/kubernetes/minikube/issues/8163

I merged a temporary fix for v1.12.0 -- could you try upgrading and see if that fixes the issue?

**Comment by tstromberg** [comment] 2020-07-23 20:21
This issue appears to be a duplicate of #8179, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-07-23 20:21 UTC
Labels: triage/needs-information, triage/support
