### ISSUE TITLE
Show progress bar when pulling docker base image

### ISSUE THREAD

**Issue by zerefwayne** [kubernetes/minikube#9492] opened 2020-10-19 16:06 UTC
**Steps to reproduce the issue:** 

1. minikube start --driver=docker

**Full output**
```
~ » minikube start --driver=docker                          
😄  minikube v1.14.0 on Ubuntu 20.04
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
```

**Issue**

The terminal shows no output of the download progress while downloading the docker image. This issue can also be because `docker pull` starts to works in the background and the terminal process has no way of knowing the progress. I wish there was some output about the progress here because the user might think that the process is stuck.

<details>
OS: Ubuntu 20.04 LTS
Minikube Version: 1.14
</details>

**Comment by zerefwayne** [comment] 2020-10-19 16:18
![image](https://user-images.githubusercontent.com/28949397/96477977-c1a06800-1254-11eb-8efc-1a000b0416d0.png)

The size of the image is close to 800MB which can take a lot of time.

**Comment by afbjorklund** [comment] 2020-10-20 16:26
Same request as #7012, but unfortunately no progress has been made since

**Comment by afbjorklund** [comment] 2020-10-20 16:28
The workaround is doing `docker pull` on the kicbase image first.

**Comment by tstromberg** [comment] 2020-10-21 00:14
This issue appears to be a duplicate of #7012, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-10-21 00:14 UTC
Labels: co/docker-driver, kind/feature, triage/duplicate
