### ISSUE TITLE
minikube failed to start on Ubuntu 18.04 with VirtualBox

### ISSUE THREAD

**Issue by indraindrajit71** [kubernetes/minikube#6206] opened 2020-01-04 04:11 UTC
I am trying to run "minikube start" on ubuntu 18.04 with Oracle VirtualBox setup.
initially it gave error when I executed "minikube start" with root priveleges.
Later I ran "minikube start --vm-driver=none" but now it says "docker" executable not found.

**The exact command to reproduce the issue**:
minikube start --vm-driver=none

**The full output of the command that failed**:<details>

minikube start --vm-driver=none
😄  minikube v1.6.2 on Ubuntu 18.04
✨  Selecting 'none' driver from user configuration (alternates: [kvm2 virtualbox])
🤹  Running on localhost (CPUs=2, Memory=11499MB, Disk=467460MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible: create: precreate: exec: "docker": executable file not found in $PATH

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

minikube logs

💣  api load: filestore "minikube": Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
 lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.3 LTS
Release:	18.04
Codename:	bionic

**Comment by indraindrajit71** [comment] 2020-01-04 05:17
Please note that I am not running this inside a VM.
Even though I use the below command, it fails

minikube start
😄  minikube v1.6.2 on Ubuntu 18.04
✨  Selecting 'virtualbox' driver from user configuration (alternates: [kvm2 none])
🛑  The "virtualbox" driver should not be used with root privileges.
💡  If you are running minikube within a VM, consider using --vm-driver=none:
📘    https://minikube.sigs.k8s.io/docs/reference/drivers/none/

**Comment by priyawadhwa** [comment] 2020-01-06 21:18
Hey @indraindrajit71 thanks for opening this issue.

It looks like you're running minikube with root privileges, but minikube+virtualbox shouldn't be run with root privileges. Running `minikube start` defaults to virtualbox, so you could try running `minikube start` without root privileges.

If you want to use the none driver, it looks like the issue is that minikube can't find docker on your PATH. Is docker installed on your machine and under PATH?

**Comment by indraindrajit71** [comment] 2020-01-14 06:16
thanks @priyawadhwa 
well I am doing this inside a VM which and have installed minikube on it.Howevr what I understood is this that we dont need to install docker manually when done on a single VM with minikube as it takes care of those later.

Let me try this again and will get back.

thanks

**Comment by afbjorklund** [comment] 2020-01-14 06:46
You need to use `virtualbox` driver without sudo, and `none` driver with sudo.

If you want to use the none driver, you will also need to install docker yourself.

**Comment by afbjorklund** [comment] 2020-01-14 06:50
See also https://help.ubuntu.com/community/RootSudo for more details why you should **not** log in as root (to your desktop)

**Comment by medyagh** [comment] 2020-03-04 20:03
@indraindrajit71  I will close this issue due to no update, and sorry to hear you had this issue, please feel free to reopen.

meanwhile I recommend to give our newest driver a try in latest release

minikube start --vm-driver=docker
that might solve your issue !

**Closed by medyagh** 2020-03-04 20:03 UTC
Labels: co/none-driver, triage/support
