### ISSUE TITLE
virtualbox: The host-only adapter we just created is not visible.

### ISSUE THREAD

**Issue by gyanprakashsahu** [kubernetes/minikube#4163] opened 2019-04-26 05:50 UTC
💣  Unable to start VM: start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**Comment by tstromberg** [comment] 2019-05-02 18:43
Thank you for sharing your experience!  To help us fix this problem, could you please include:

*  The exact command-lines used so that we can replicate the issue
*  The full output of the command that failed
*  Which operating system version was used

This will also show more logs:

`minikube start --alsologtostderr -v=8`

**Comment by tstromberg** [comment] 2019-05-02 18:44
Depending on the follow-up, this is probably a dupe of #3614

**Comment by tstromberg** [comment] 2019-05-02 18:49
Also, please let me know if rebooting your host fixes this problem.

**Comment by tstromberg** [comment] 2019-05-02 23:49
Duplicate of #3614

**Closed by tstromberg** 2019-05-02 23:49 UTC
Labels: co/virtualbox, triage/needs-information
