### ISSUE TITLE
spark jobs hang: could not find the request resource: get services heapster

### ISSUE THREAD

**Issue by nvijayap** [kubernetes/minikube#4403] opened 2019-06-01 19:08 UTC
I am on Mac ...

```
ProductName:	Mac OS X
ProductVersion:	10.14.5
BuildVersion:	18F132
```

I am using this current/latest version of minikube ...

```
minikube version: v1.1.0
```

I have setup spark on minikube.

I have then submitted a spark job to minikube.

The job hung.

minikube logs reveal this ...

```
2019/06/01 19:06:15 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.
```

**Comment by yechnlin** [comment] 2019-07-03 01:26
same issue encountered.

**Comment by medyagh** [comment] 2019-07-03 21:04
I am wondering, have you checked if your pods are healthy ?
what is the output of ?
`kubectl get pods --all-namespaces`

**Comment by tstromberg** [comment] 2019-07-16 22:28
That error message might be a red herring.

Could you provide some reproduction instructions so we can check it out here?

**Comment by tstromberg** [comment] 2019-08-23 00:08
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

*  The exact command-lines used to replicate the problem.
 * The full output of `minikube logs` (on minikube v1.3.1 or higher)

Thank you for sharing your experience!

**Closed by tstromberg** 2019-08-23 00:08 UTC
Labels: triage/needs-information, triage/support
