### ISSUE TITLE
localkube 404 with Kubernetes 1.7.4

### ISSUE THREAD

**Issue by swestcott** [kubernetes/minikube#1892] opened 2017-08-26 20:58 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug report

Please provide the following details:

**Environment**:

**Minikube version**: v0.21.0
- **OS**: OS X
- **VM Driver**: virtualbox
- **ISO version**: minikube-v1.0.7.iso
- **Install tools**: Downloaded direct from GCS
- **Others**:

**What happened**:

404 error downloading localkube with Kubernetes 1.7.4

**What you expected to happen**:

`minikube start` to successfully start a Kubernetes 1.7.4 cluster

**How to reproduce it** (as minimally and precisely as possible):

```
▶ minikube get-k8s-versions
The following Kubernetes versions are available:
	- v1.7.4
	- v1.7.3
	- v1.7.2
	- v1.7.0
<snip>
▶ minikube config set kubernetes-version v1.7.4

▶ minikube config get kubernetes-version
v1.7.4

▶ minikube start --logtostderr
I0826 21:50:42.294230   17204 notify.go:112] Checking for updates...
I0826 21:50:42.525357   17204 kubernetes_versions.go:84] [{v1.7.4} {v1.7.3} {v1.7.2} {v1.7.0} {v1.7.0-rc.1} {v1.7.0-alpha.2} {v1.6.4} {v1.6.3} {v1.6.0} {v1.6.0-rc.1} {v1.6.0-beta.4} {v1.6.0-beta.3} {v1.6.0-beta.2} {v1.6.0-alpha.1} {v1.6.0-alpha.0} {v1.5.3} {v1.5.2} {v1.5.1} {v1.4.5} {v1.4.3} {v1.4.2} {v1.4.1} {v1.4.0} {v1.3.7} {v1.3.6} {v1.3.5} {v1.3.4} {v1.3.3} {v1.3.0}]
Starting local Kubernetes v1.7.4 cluster...
Starting VM...
I0826 21:50:42.525753   17204 cluster.go:71] Machine exists!
I0826 21:50:42.623594   17204 cluster.go:78] Machine state:  Running
Getting VM IP address...
Moving files into cluster...
I0826 21:50:46.236584   17204 kubernetes_versions.go:84] [{v1.7.4} {v1.7.3} {v1.7.2} {v1.7.0} {v1.7.0-rc.1} {v1.7.0-alpha.2} {v1.6.4} {v1.6.3} {v1.6.0} {v1.6.0-rc.1} {v1.6.0-beta.4} {v1.6.0-beta.3} {v1.6.0-beta.2} {v1.6.0-alpha.1} {v1.6.0-alpha.0} {v1.5.3} {v1.5.2} {v1.5.1} {v1.4.5} {v1.4.3} {v1.4.2} {v1.4.1} {v1.4.0} {v1.3.7} {v1.3.6} {v1.3.5} {v1.3.4} {v1.3.3} {v1.3.0}]
Downloading localkube binary
E0826 21:50:46.491445   17204 start.go:158] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:

* received invalid status code: 404 (expected 200)
```

**Output of `minikube logs` (if applicable)**:
n/a

**Anything else do we need to know**:

Using `minikube config set kubernetes-version v1.7.3` works fine

**Comment by xerobuffer** [comment] 2017-08-26 23:38
same on windows.
and "wget https://storage.googleapis.com/minikube/k8sReleases/v1.7.4/localkube-linux-amd64" ---> get 404 error

**Comment by gugahoi** [comment] 2017-08-28 04:22
This can be reproduced with a single command:

```bash
❯ minikube start --kubernetes-version v1.7.4
Starting local Kubernetes v1.7.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading localkube binary
E0828 14:20:02.622297    1488 start.go:158] Error updating cluster:  Error updating localkube from uri: Error attempting to download and cache localkube: failed to download: failed to download to temp file: download failed: 1 error(s) occurred:
```
Interestingly `1.7.3` works:

```bash
❯ minikube start --kubernetes-version v1.7.3
Starting local Kubernetes v1.7.3 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Downloading localkube binary
 138.65 MB / 138.65 MB [============================================] 100.00% 0s
Setting up certs...
Starting cluster components...
Connecting to cluster...
Setting up kubeconfig...
Kubectl is now configured to use the cluster.
```

```
❯ minikube version
minikube version: v0.21.0
```

**Comment by chris-fung** [comment] 2017-08-28 09:22
same on mac os x

**Comment by r2d4** [comment] 2017-08-28 17:09
I've uploaded it now, but since we turned off insecure serving and changed the way we generate certs, localkube 1.7.3 and above won't be compatible with older minikube versions.  You'll have to wait for a new release of minikube or a grab a version at head.  You can grab a version from any PR at 
```
$ gsutil ls gs://minikube-builds/1874/
gs://minikube-builds/1874/build_iso.sh
gs://minikube-builds/1874/common.sh
gs://minikube-builds/1874/e2e-darwin-amd64
gs://minikube-builds/1874/e2e-linux-amd64
gs://minikube-builds/1874/e2e-windows-amd64
gs://minikube-builds/1874/linux_integration_tests_kvm.sh
gs://minikube-builds/1874/linux_integration_tests_kvm_alt.sh
gs://minikube-builds/1874/linux_integration_tests_none.sh
gs://minikube-builds/1874/linux_integration_tests_virtualbox.sh
gs://minikube-builds/1874/localkube
gs://minikube-builds/1874/minikube-darwin-amd64
gs://minikube-builds/1874/minikube-linux-amd64
gs://minikube-builds/1874/minikube-windows-amd64.exe
gs://minikube-builds/1874/minikube_cross_build_and_upload.sh
gs://minikube-builds/1874/minikube_set_pending.sh
gs://minikube-builds/1874/osx_integration_tests_virtualbox.sh
gs://minikube-builds/1874/osx_integration_tests_xhyve.sh
gs://minikube-builds/1874/print-debug-info.sh
gs://minikube-builds/1874/release_build_and_upload.sh
gs://minikube-builds/1874/release_github_page.sh
gs://minikube-builds/1874/release_update_installers.sh
gs://minikube-builds/1874/release_update_releases_json.sh
gs://minikube-builds/1874/windows_integration_test_hyperv.ps1
gs://minikube-builds/1874/testdata/
```

but we should also be doing a release soon.

**Comment by r2d4** [comment] 2017-09-07 20:47
This should be fixed with the latest release.  1.7.3, 1.7.4, and 1.7.5 should all work with the current release.

**Closed by r2d4** 2017-09-07 20:47 UTC
Labels: kind/bug
