### ISSUE TITLE
cann't access kubectl from windows prompt

### ISSUE THREAD

**Issue by technicalpriyanka** [kubernetes/minikube#13647] opened 2022-02-21 15:44 UTC
### What Happened?

access issue

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8110507/log.txt)

### Operating System

Windows

### Driver

VirtualBox

**Comment by spowelljr** [comment] 2022-02-22 05:55
Hi @technicalpriyanka, thanks for reporting your issue with minikube!

This seems to be a duplicate of https://github.com/kubernetes/minikube/issues/13626.

Would you mind trying my suggestion in this comment and seeing if that resolves your issue, thanks!

**Closed** 2022-07-22 07:02 UTC
Labels: lifecycle/rotten
