### ISSUE TITLE
重启 cluster 时出错

### ISSUE THREAD

**Issue by yunpengzju** [kubernetes/minikube#6001] opened 2019-12-01 04:20 UTC
**重现问题所需的命令**：minikube start

**失败的命令的完整输出**：<details>
😄  Darwin 10.15 上的 minikube v1.5.2
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing hyperkit VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
⚠️  VM is unable to access k8s.gcr.io, you may need to configure a proxy or set --image-repository
🐳  正在 Docker '18.09.9' 中准备 Kubernetes v1.16.2…
🔄  Relaunching Kubernetes using kubeadm ...

💣  重启 cluster 时出错: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
</details>

**`minikube logs`命令的输出**： <details>
==> Docker <==
-- Logs begin at Sun 2019-12-01 04:05:57 UTC, end at Sun 2019-12-01 04:17:57 UTC. --
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950597477Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950699631Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950749570Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950787504Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950828289Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950868315Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950906836Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950943390Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.950978980Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951063759Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951174759Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951454129Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951509029Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951562631Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951603070Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951640204Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951675846Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951727667Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951776193Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951817174Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951856211Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951896551Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.951957257Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952017648Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952058974Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952095420Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952202501Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952295752Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.952345447Z" level=info msg="containerd successfully booted in 0.007647s"
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.958170239Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005c6dc0, READY" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.960278364Z" level=info msg="systemd-resolved is running, so using resolvconf: /run/systemd/resolve/resolv.conf"
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.961878397Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.961919715Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962016445Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962055447Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962080672Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005c7220, CONNECTING" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962387040Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962417364Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962471891Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005c7220, READY" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962566930Z" level=info msg="ccResolverWrapper: sending new addresses to cc: [{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}]" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962630267Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962653332Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005c7500, CONNECTING" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.962913695Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0005c7500, READY" module=grpc
Dec 01 04:08:25 minikube dockerd[1913]: time="2019-12-01T04:08:25.968199252Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.003601638Z" level=info msg="Graph migration to content-addressability took 0.00 seconds"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.003846190Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.003897574Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.003936119Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.003972128Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.004013595Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.004050825Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.004416205Z" level=info msg="Loading containers: start."
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.098805636Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.130469453Z" level=info msg="Loading containers: done."
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.138764465Z" level=warning msg="failed to retrieve runc version: unknown output format: runc version commit: 425e105d5a03fabd737a126ad93d62a9eeede87f\nspec: 1.0.1-dev\n"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.145984660Z" level=info msg="Docker daemon" commit=039a7df9ba graphdriver(s)=overlay2 version=18.09.9
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.146486579Z" level=info msg="Daemon has completed initialization"
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.154125968Z" level=info msg="API listen on /var/run/docker.sock"
Dec 01 04:08:26 minikube systemd[1]: Started Docker Application Container Engine.
Dec 01 04:08:26 minikube dockerd[1913]: time="2019-12-01T04:08:26.154199222Z" level=info msg="API listen on [::]:2376"

==> container status <==
time="2019-12-01T04:17:59Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[Dec 1 04:05] ERROR: earlyprintk= earlyser already used
[  +0.000000] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000000] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.005060] ACPI BIOS Warning (bug): Incorrect checksum in table [DSDT] - 0xC0, should be 0x1D (20180810/tbprint-177)
[ +14.731138] ACPI Error: Could not enable RealTimeClock event (20180810/evxfevnt-184)
[  +0.000002] ACPI Warning: Could not enable fixed event - RealTimeClock (4) (20180810/evxface-620)
[  +0.005814] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +1.676263] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.005650] systemd-fstab-generator[1083]: Ignoring "noauto" for root device
[  +0.002774] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +0.939695] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.023379] vboxguest: loading out-of-tree module taints kernel.
[  +0.002361] vboxguest: PCI device not found, probably running on physical hardware.
[Dec 1 04:06] systemd-fstab-generator[1838]: Ignoring "noauto" for root device
[Dec 1 04:07] NFSD: Unable to end grace period: -110
[Dec 1 04:08] systemd-fstab-generator[2305]: Ignoring "noauto" for root device

</details>

**使用的操作系统版本**：mac os 10.15

**Comment by tstromberg** [comment] 2019-12-16 20:52
This issue appears to be a duplicate of #5905, do you mind if we move the conversation there? This should have been fixed in minikube v1.6.0, so please try upgrading if you have not already.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-16 20:52 UTC
Labels: l/zh-CN
