### ISSUE TITLE
minikube uses Polish partially translated strings

### ISSUE THREAD

**Issue by vanmash** [kubernetes/minikube#12361] opened 2021-08-27 12:18 UTC
`minikube` uses Polish partially translated strings.
How to set `minikube` to use English only?

**Steps to reproduce the issue:** 

1. minikube

**Full output of `minikube logs` command:**
<details>
*
* ==> Audyt <==
* |---------|------|----------|-----------|---------|--------------------------------|--------------------------------|
| Command | Args | Profile  |   User    | Version |           Start Time           |            End Time            |
|---------|------|----------|-----------|---------|--------------------------------|--------------------------------|
| config  |      | minikube | I04\vd374 | v1.22.0 | Fri, 27 Aug 2021 14:11:48 CEST | Fri, 27 Aug 2021 14:11:48 CEST |
|---------|------|----------|-----------|---------|--------------------------------|--------------------------------|

*
* ==> Ostatni start <==
* Last start log file not found at C:\Users\vd374\.minikube\logs\lastStart.txt
*
* Profile "minikube" not found. Run "minikube profile list" to view all profiles.
  To start a cluster, run: "minikube start"

</details>

**Full output of failed command:**
<details>

</details>

**Comment by spowelljr** [comment] 2021-08-30 18:56
Hi @vanmash, if you want minikube to use English you can set the environmental variable `LC_ALL` to `C`.

```
// for all commands going forward
export LC_ALL="C"
minikube start

or 

// for just this command
LC_ALL="C" minikube start
```

Let me know if this solves your issue, thanks!

**Comment by vanmash** [comment] 2021-08-30 19:30
Hi @spowelljr, thank you!

for Windows something like this should work

powershell
```powershell
$env:LC_ALL="C"
minikube
```

cmd
```cmd
set LC_ALL="C"
minikube
```

**Comment by spowelljr** [comment] 2021-08-30 21:37
@vanmash That is correct! I believe you issue has been resolved so I'm going to close this issue, but feel free to re-open if you have further questions, thanks!

**Comment by vanmash** [comment] 2021-08-31 05:18
Perhaps `minikube` could use English as default?

**Comment by spowelljr** [comment] 2021-08-31 17:08
It grabs the OS set language by default as seen here:
https://github.com/kubernetes/minikube/blob/master/pkg/minikube/translate/translate.go#L64

Seems that something on your OS is pointing to Polish, unless something set `LC_ALL` to Polish.

**Comment by vanmash** [comment] 2021-09-02 10:11
There was nothing strange/specific in my environment variables. However changing `Regional format` to English (UK) in Windows 10 settings --> region makes `minikube` display in English.
The thing is that `minikube` is the only tool doing this.

**Comment by spowelljr** [comment] 2021-09-08 20:00
If you set the `Regional format` to what you had set before does the issue still persist?

**Comment by vanmash** [comment] 2021-09-09 08:54
@spowelljr Yes, that's right.

`Regional format` set to "Polish"
```
PS > minikube
minikube dostarcza lokalne klastry Kubernetesa zoptymalizowane do celów rozwoju oprogramowania oraz zarządza nimi
```

`Regional format` set to "English"

```
PS > minikube
minikube provisions and manages local Kubernetes clusters optimized for development workflows.
```

**Comment by spowelljr** [comment] 2021-09-09 16:52
From my point of view minikube is actually doing what is expected of it. When you have the `Region format` set to "Polish" minikube is detecting that and using its Polish translations. Like we previously talked about you can override minikube's language detection using `LC_ALL` but everything seems to be working as expected from my point of view.

**Comment by vanmash** [comment] 2021-09-09 17:16
You are probably right. The thing is that `minikube` is the only tool which behaves that way (at least for me). I guess this issue might be closed. Thank you!

**Comment by spowelljr** [comment] 2021-09-09 17:28
It's possible that the language detecting library that minikube is using is more optimized for Windows than other programs, that's my guess. Glad to help! I'll close this issue but feel free to comment and/or re-open the issue if needed.

**Closed by spowelljr** 2021-09-09 17:28 UTC
Labels: kind/support

**Comment by greschd** [comment] 2022-10-12 09:41
I think "Regional Format" is the wrong Windows setting to use for the display language. It's described in the settings as

> Windows and some apps format dates and times based on your regional format

Instead, "Windows Display Language" should be used to determine the UI language:

> Windows features like Settings and File Explorer will appear in this language

I stumbled upon this issue by having "Regional Format" set to `German (Switzerland)` to get the correct date / time settings, but display language `English (US)`. On that machine, all other apps appear in English, but `minikube` uses the German translation.

**Comment by spowelljr** [comment] 2022-10-12 18:43
Hi @greschd, thanks for the information! Since my last response I have updated the language detection to use a different method, is it still the case that it's using the regional format? And if so could you tell me what version of minikube you're using.

**Comment by greschd** [comment] 2022-10-12 18:59
I'm away from that Windows machine right now, but I can confirm that I was seeing that with the Stable Windows `.exe` downloaded today.
Will come back with the exact version later.

**Comment by greschd** [comment] 2022-10-17 11:56
Here's the version info:

```
> minikube.exe version
minikube version: v1.27.1
commit: fe869b5d4da11ba318eb84a3ac00f336411de7ba
```
