### ISSUE TITLE
Pods get assigned the same IP on different nodes (multi-node)

### ISSUE THREAD

**Issue by R-omk** [kubernetes/minikube#7589] opened 2020-04-10 15:32 UTC
**Steps to reproduce the issue:** 

1. minikube start  -n 3 --driver=docker
2. \# deploy multiple pods to cluster
3. kubectl get pods -o wide 

<details>

minikube version: v1.9.2
commit: 93af9c1e43cab9618e301bc9fa720c63d5efa393

</details>

**Comment by tstromberg** [comment] 2020-04-10 20:07
I believe this is because there is no CNI enabled in this reproduction case: https://minikube.sigs.k8s.io/docs/tutorials/multi_node/

/cc @sharifelgamal

**Comment by R-omk** [comment] 2020-04-10 21:02
Yes, it looks like it is. 
I believe this should be enabled by default for multi node mode, for example, as an addon enabled by default.

**Comment by sharifelgamal** [comment] 2020-04-10 21:04
Yes, we have an issue open to enable CNI by default for multinode: https://github.com/kubernetes/minikube/issues/7459

**Comment by priyawadhwa** [comment] 2020-04-15 18:25
Hey @R-omk I'm going to go ahead and close this issue and it seems to be a duplicate of #7459, and we can consolidate this conversation in that issue.

If you feel this isn't a dupe or have additional information, feel free to reopen this issue at any time by including `/reopen` in your comment.

**Closed by priyawadhwa** 2020-04-15 18:25 UTC
Labels: co/multinode, triage/support
