### ISSUE TITLE
none: Too many retries waiting for SSH to be available

### ISSUE THREAD

**Issue by torsten-liermann** [kubernetes/minikube#6684] opened 2020-02-19 15:50 UTC
Hi,

I am desperate. I have to work on a restricted, reduced Windows 10 and need a simple Kubernetes cluster for local development.

Why does minikube start wait for ssh by vm-driver none?

And a small question by the way: How can I teach minikubeto use the SSL connection for downloading kubectl etc. to insecure? "My" http proxy is hacking SSL connections. :-(

Many Thanks for support.

**The exact command to reproduce the issue**:

minikube start --vm-driver none --kubernetes-version v1.17.2 

**The full output of the command that failed**:<details>
with shell trace

 minikube -v=7 start --vm-driver none --v=7 --alsologtostderr
* minikube v1.7.2 on Debian 10.3
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - MINIKUBE_HOME=/root/.minikube
  - MINIKUBE_WANTUPDATENOTIFICATION=false
* Using the none driver based on user configuration
* Reconfiguring existing host ...
* Starting existing none VM for "minikube" ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: detecting provisioner: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
+ minikube start --vm-driver none -v=7 --alsologtostderr
W0219 16:40:24.165736   10448 root.go:244] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0219 16:40:24.187867   10448 start.go:259] hostinfo: {"hostname":"debian","uptime":96132,"bootTime":1582030692,"procs":165,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"10.3","kernelVersion":"4.19.0-8-amd64","virtualizationSystem":"","virtualizationRole":"","hostid":"84e1cf93-ac6e-a745-a449-c1d5f1b677ca"}
I0219 16:40:24.188125   10448 start.go:269] virtualization:
* minikube v1.7.2 on Debian 10.3
  - MINIKUBE_WANTREPORTERRORPROMPT=false
  - MINIKUBE_HOME=/root/.minikube
  - MINIKUBE_WANTUPDATENOTIFICATION=false
I0219 16:40:24.188418   10448 driver.go:199] Setting default libvirt URI to qemu:///system
* Using the none driver based on user configuration
I0219 16:40:24.188467   10448 start.go:306] selected driver: none
I0219 16:40:24.188473   10448 start.go:612] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.7.0.iso Memory:2000 CPUs:2 DiskSize:20000 VMDriver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[NO_PROXY=172.18.146.182 HTTP_PROXY=XXXXXXXXXXXXXXXX HTTPS_PROXY=http://XXXXXXX InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false Downloader:<nil> DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.17.2 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: ExtraOptions:[{Component:kubelet Key:cgroup-driver Value:cgroupfs}] ShouldLoadCachedImages:false EnableDefaultCNI:false} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.17.2 ControlPlane:true Worker:true}] Addons:map[]}
I0219 16:40:24.188507   10448 start.go:618] status for none: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0219 16:40:24.188904   10448 profile.go:100] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0219 16:40:24.189063   10448 start.go:215] acquiring machines lock for minikube: {Name:mka00e65579c2b557a802898fd1cf03ec4ab30a1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0219 16:40:24.189141   10448 start.go:219] acquired machines lock for "minikube" in 59.3µs
I0219 16:40:24.189155   10448 start.go:84] Skipping create...Using existing machine configuration
* Reconfiguring existing host ...
I0219 16:40:24.189173   10448 fix.go:54] fixHost starting: minikube
I0219 16:40:24.189259   10448 none.go:130] GetState called
I0219 16:40:24.190059   10448 kverify.go:126] Checking apiserver status ...
W0219 16:40:24.195316   10448 kverify.go:130] unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0219 16:40:24.195342   10448 kverify.go:186] Checking kubelet status ...
W0219 16:40:24.206756   10448 kverify.go:190] sudo systemctl is-active kubelet returned error: sudo systemctl is-active kubelet: exit status 3
stdout:
inactive

stderr:
I0219 16:40:24.206786   10448 kverify.go:193] kubelet is-active: inactive
* Starting existing none VM for "minikube" ...
I0219 16:40:24.207636   10448 fix.go:84] Detecting provisioner ...
I0219 16:40:24.207685   10448 main.go:110] libmachine: Waiting for SSH to be available...
I0219 16:40:24.207700   10448 main.go:110] libmachine: Getting to WaitForSSH function...
I0219 16:40:24.207713   10448 main.go:110] libmachine: Error getting ssh command 'exit 0' : driver does not support ssh commands
I0219 16:40:27.208028   10448 main.go:110] libmachine: Getting to WaitForSSH function...

</details>

**The operating system version**:
debian 10.3

**Comment by tstromberg** [comment] 2020-02-19 19:47
This appears to be a dupe of #4132 - for which the root cause is unknown. `minikube delete` may fix this once, but it may reintroduce itself later. 

I would personally recommend just running minikube on Windows if possible, which will allow it to manage it's own Hyper-V VM instead. Alternatively, you may also try the experimental `--vm-driver=docker` either within the VM, or directly on Windows.

**Comment by tstromberg** [comment] 2020-02-19 19:47
This issue appears to be a duplicate of #4132, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-02-19 19:47 UTC
