### ISSUE TITLE
Flake: Failed to setup certs: certificate symlinks: calculate hash for cacert

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7200] opened 2020-03-24 12:29 UTC
TestStartStop/group/old-docker  :

```
W0324 01:16:49.987152   21735 exit.go:101] Failed to setup certs: certificate symlinks: calculate hash for cacert /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: exit status 1
stdout:
stderr:
unable to load certificate
140322467374272:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
* 
X Failed to setup certs: certificate symlinks: calculate hash for cacert /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: openssl x509 -hash -noout -in /usr/share/ca-certificates/6279.pem: exit status 1
stdout:
```

as seen in 
https://storage.googleapis.com/minikube-builds/logs/7173/67bd258/Docker_Linux.html#fail_TestStartStop%2fgroup%2fold-docker

**Comment by tstromberg** [comment] 2020-03-26 18:36
Dupe of #6956

**Closed by tstromberg** 2020-03-26 18:36 UTC
Labels: kind/failing-test, kind/flake, priority/important-soon
