### ISSUE TITLE
[gramesh@master-node ~]$ minikube logs I0502 22:09:13.153534  550531 out.go:278] Setting OutFile to fd 1 ... log: exiting because of error: log: unable to create log: open /tmp/minikube_logs_0b5043027108b187e81d1003439d254eaa120884_0.log: no such file or directory

### ISSUE THREAD

**Issue by Rameshgangaa** [kubernetes/minikube#11254] opened 2021-05-02 16:39 UTC
**Steps to reproduce the issue:** 

1.minikube start

2. 
3.

**Full output of `minikube logs` command:**
<details>
minikube v1.19.0 on Centos 7.9.2009
✨  Using the docker driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🤦  StartHost failed, but will try again: boot lock: no such file or directory
😿  Failed to start docker container. Running "minikube delete" may fix it: boot lock: no such file or directory
[gramesh@master-node ~]$ minikube logs
I0502 22:09:13.153534  550531 out.go:278] Setting OutFile to fd 1 ...
log: exiting because of error: log: unable to create log: open /tmp/minikube_logs_0b5043027108b187e81d1003439d254eaa120884_0.log: no such file or directory

</details>

**Full output of failed command:**
<details>
[gramesh@master-node ~]$ minikube logs
I0502 22:09:13.153534  550531 out.go:278] Setting OutFile to fd 1 ...
log: exiting because of error: log: unable to create log: open /tmp/minikube_logs_0b5043027108b187e81d1003439d254eaa120884_0.log: no such file or directory

</details>

**Comment by vigothehacker** [comment] 2021-05-03 19:18
Hi , I am facing this exact same error. I have set the /tmp directory to the 1777 mode . Deleting the dir /tmp and then remaking it from the same user makes it work for the current user but fails again when running minikube from a different user.

**Comment by vigothehacker** [comment] 2021-05-03 19:27
https://github.com/kubernetes/minikube/issues/11205

**Comment by spowelljr** [comment] 2021-05-03 20:34
As @vigothehacker noted this is a duplicate of an existing issue #11205. I'm going to close this issue, feel free to comment on that issue if you have any updates.

**Closed by spowelljr** 2021-05-03 20:34 UTC
Labels: triage/duplicate
