### ISSUE TITLE
hyperv is not stopping when using minikube  stop

### ISSUE THREAD

**Issue by csuryac** [kubernetes/minikube#3782] opened 2019-03-02 17:47 UTC
If this is a bug report, please include:

- [ ] How to replic:\windows\system32>minikube stop
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
:   Stopping "minikube" in hyperv ...
!   Unable to stop VM: Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1
Temporary Error: Stop: minikube: exit status 1ate the error, including the exact command-lines used.
- [ ] The full output of the command that failed
- [ ] The operating system name and version used

**Comment by tstromberg** [comment] 2019-03-08 15:55
Dupe of #3492

**Closed by tstromberg** 2019-03-08 15:55 UTC
