### ISSUE TITLE
Failed to enable unit: Unit file cri-docker.socket does not exist

### ISSUE THREAD

**Issue by ShaikSaleem123** [kubernetes/minikube#14616] opened 2022-07-21 06:21 UTC
### What Happened?

unable to run minikube .
it is throwing this issue 

### Attach the log file

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 21 Jul 22 05:54 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/07/21 05:54:47
Running on machine: ip-172-31-47-191
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0721 05:54:47.553587    3275 out.go:296] Setting OutFile to fd 1 ...
I0721 05:54:47.553813    3275 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0721 05:54:47.553819    3275 out.go:309] Setting ErrFile to fd 2...
I0721 05:54:47.553825    3275 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0721 05:54:47.554079    3275 root.go:329] Updating PATH: /root/.minikube/bin
W0721 05:54:47.554215    3275 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0721 05:54:47.554391    3275 out.go:303] Setting JSON to false
I0721 05:54:47.555132    3275 start.go:115] hostinfo: {"hostname":"ip-172-31-47-191","uptime":1216,"bootTime":1658381671,"procs":118,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"22.04","kernelVersion":"5.15.0-1011-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec2da95d-07fc-ec56-e2b1-cb0589275743"}
I0721 05:54:47.555210    3275 start.go:125] virtualization: xen guest
I0721 05:54:47.558034    3275 out.go:177] * minikube v1.26.0 on Ubuntu 22.04 (xen/amd64)
I0721 05:54:47.559934    3275 driver.go:360] Setting default libvirt URI to qemu:///system
W0721 05:54:47.559955    3275 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0721 05:54:47.561718    3275 out.go:177] * Using the none driver based on user configuration
I0721 05:54:47.560163    3275 notify.go:193] Checking for updates...
I0721 05:54:47.563379    3275 start.go:284] selected driver: none
I0721 05:54:47.563393    3275 start.go:805] validating driver "none" against <nil>
I0721 05:54:47.563407    3275 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0721 05:54:47.563454    3275 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0721 05:54:47.563646    3275 start_flags.go:296] no existing cluster config was found, will generate one from the flags
I0721 05:54:47.563910    3275 start_flags.go:377] Using suggested 2200MB memory alloc based on sys=3922MB, container=0MB
I0721 05:54:47.564042    3275 start_flags.go:835] Wait components to verify : map[apiserver:true system_pods:true]
I0721 05:54:47.564058    3275 cni.go:95] Creating CNI manager for ""
I0721 05:54:47.564065    3275 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0721 05:54:47.564073    3275 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0721 05:54:47.566067    3275 out.go:177] * Starting control plane node minikube in cluster minikube
I0721 05:54:47.567970    3275 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0721 05:54:47.567999    3275 lock.go:35] WriteFile acquiring /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0721 05:54:47.568326    3275 cache.go:208] Successfully downloaded all kic artifacts
I0721 05:54:47.568355    3275 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0721 05:54:47.568439    3275 start.go:356] acquired machines lock for "minikube" in 71.44µs
I0721 05:54:47.568463    3275 start.go:91] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:} &{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}
I0721 05:54:47.568523    3275 start.go:131] createHost starting for "m01" (driver="none")
I0721 05:54:47.570652    3275 out.go:177] * Running on localhost (CPUs=2, Memory=3922MB, Disk=7764MB) ...
I0721 05:54:47.572343    3275 exec_runner.go:51] Run: systemctl --version
I0721 05:54:47.574494    3275 start.go:165] libmachine.API.Create for "minikube" (driver="none")
I0721 05:54:47.574527    3275 client.go:168] LocalClient.Create starting
I0721 05:54:47.574646    3275 main.go:134] libmachine: Creating CA: /root/.minikube/certs/ca.pem
I0721 05:54:47.654886    3275 main.go:134] libmachine: Creating client certificate: /root/.minikube/certs/cert.pem
I0721 05:54:48.215178    3275 client.go:171] LocalClient.Create took 640.628106ms
I0721 05:54:48.215230    3275 start.go:173] duration metric: libmachine.API.Create for "minikube" took 640.729114ms
I0721 05:54:48.215239    3275 start.go:306] post-start starting for "minikube" (driver="none")
I0721 05:54:48.215246    3275 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0721 05:54:48.215296    3275 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0721 05:54:48.226555    3275 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0721 05:54:48.226589    3275 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0721 05:54:48.226601    3275 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0721 05:54:48.229322    3275 out.go:177] * OS release is Ubuntu 22.04 LTS
I0721 05:54:48.231323    3275 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0721 05:54:48.231394    3275 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0721 05:54:48.231422    3275 start.go:309] post-start completed in 16.173584ms
I0721 05:54:48.232090    3275 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0721 05:54:48.232290    3275 start.go:134] duration metric: createHost completed in 663.75754ms
I0721 05:54:48.232301    3275 start.go:81] releasing machines lock for "minikube", held for 663.851605ms
I0721 05:54:48.232707    3275 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0721 05:54:48.232754    3275 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0721 05:54:48.259491    3275 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0721 05:54:48.567663    3275 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0721 05:54:48.833798    3275 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0721 05:54:49.098522    3275 exec_runner.go:51] Run: sudo systemctl restart docker
I0721 05:54:49.437191    3275 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0721 05:54:49.454337    3275 out.go:177]
W0721 05:54:49.456117    3275 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0721 05:54:49.456142    3275 out.go:239] *
W0721 05:54:49.457174    3275 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0721 05:54:49.460683    3275 out.go:177]

*

### Operating System

Ubuntu

**Comment by afbjorklund** [comment] 2022-07-21 08:09
Same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by spowelljr** [comment] 2022-07-25 17:29
Hi @ShaikSaleem123, as @afbjorklund pointed out, this is a duplicate of https://github.com/kubernetes/minikube/issues/14410, to see how to resolve this issue please see https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503. I'm going to close this issue.

**Closed by spowelljr** 2022-07-25 17:29 UTC
Labels: co/runtime/docker, co/none-driver, triage/duplicate
