### ISSUE TITLE
VBOX_HOST_ADAPTER: The host-only adapter we just created is not visible.

### ISSUE THREAD

**Issue by dodalovic** [kubernetes/minikube#4457] opened 2019-06-10 09:22 UTC
![image](https://user-images.githubusercontent.com/6358061/59185906-e9b48d00-8b71-11e9-97d2-56569d79978a.png)

![image](https://user-images.githubusercontent.com/6358061/59185936-fdf88a00-8b71-11e9-8fb9-8ecd29cc0411.png)

---

minikube start
😄  minikube v1.1.1 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing virtualbox VM for "minikube" ...
E0610 11:20:55.579060    8232 start.go:529] StartHost: start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue

💣  Unable to start VM
❌  Error:         [VBOX_HOST_ADAPTER] start: Error setting up host only network on machine start: The host-only adapter we just created is not visible. This is a well known VirtualBox bug. You might want to uninstall it and reinstall at least version 5.0.12 that is is supposed to fix this issue
💡  Advice:        Reboot to complete VirtualBox installation, and verify that VirtualBox is not blocked by your system
📘  Documentation: https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/3614
    ▪ https://github.com/kubernetes/minikube/issues/4222

😿  If the above advice does not help, please let us know:

**Comment by medyagh** [comment] 2019-06-15 04:28
Thank you for sharing your experience! I am curious have you followed the advice in the link ?

 https://stackoverflow.com/questions/52277019/how-to-fix-vm-issue-with-minikube-start

**Comment by lucas-paes-movile** [comment] 2019-06-19 14:28
Getting same exact issue on Ubuntu 18.04 LTS.
Using VirtualBox 6.0.8 r130520 (Qt 5.9.5). The UEFI Secure Boot is enabled but the kernel is signed.
Using Minikube v1.1.1

I have already tried doing ```minikube delete && rm -rf .minikube``` and then rebooting to start fresh.

**Comment by tstromberg** [comment] 2019-07-16 22:58
I believe this is a sign of a VirtualBox installation that is blocked by security checks. Please check your `System Preferences` application, specifically within `Security & Privacy` and ensure that Oracle/VirtualBox is allowed.

If this doesn't help, please provide the output of `miinkube start --alsologtostderr -v=8`. Thank you!

**Comment by evgenijrenke** [comment] 2019-08-22 09:12
I had the same issue. It was caused by a not complete successful VirtualBox installation.
After reinstall VirtualBox complete correctly, minikube works perfect.

VirtualBox Version: 6.0.10 r132072 (Qt5.6.3)
minikube version: v1.3.1

**Comment by talolierwork** [comment] 2019-09-03 10:45
Same here, see how to install VBox correctly here:
https://matthewpalmer.net/blog/2017/12/10/install-virtualbox-mac-high-sierra/index.html

**Comment by tstromberg** [comment] 2019-09-20 05:05
Closing, as a reinstall appears to fix the issue.

**Closed by tstromberg** 2019-09-20 05:05 UTC
Labels: co/virtualbox, os/macos, triage/needs-information
