### ISSUE TITLE
none: Unable to start VM: start: No default routes

### ISSUE THREAD

**Issue by halulunyan** [kubernetes/minikube#6083] opened 2019-12-13 12:48 UTC
[root@minikube ~]# minikube start
* minikube v1.2.0 on linux (amd64)
! Please don't run minikube as root or with 'sudo' privileges. It isn't necessary.

! Ignoring --vm-driver=virtualbox, as the existing "minikube" VM was created using the none driver.
! To switch drivers, you may create a new VM using `minikube start -p <name> --vm-driver=virtualbox`
! Alternatively, you may delete the existing VM using `minikube delete -p minikube`

* Restarting existing none VM for "minikube" ...
E1213 21:46:51.300947    4901 start.go:559] StartHost: start: No default routes.

X Unable to start VM: start: No default routes.

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by halulunyan** [comment] 2019-12-13 12:52
[varlog.log](https://github.com/kubernetes/minikube/files/3960851/varlog.log)

**Comment by halulunyan** [comment] 2019-12-15 17:13
--vm-driver=virtualbox これがいらねーかもな

**Comment by tstromberg** [comment] 2019-12-16 18:09
This is likely a duplicate of #5636 - Kubernetes requires a default route to identify which IP to use. 

Do you mind upgrading to a more recent release of minikube? It's difficult to tell with such an old version, as the error message has likely changed.

**Closed** 2019-12-19 23:32 UTC
Labels: co/none-driver, failed/local-networking, triage/duplicate, triage/needs-information, triage/support
