### ISSUE TITLE
X error provisioning host: Failed to start host: creating host: create: precreate: Hyper-V PowerShell Module is not available

### ISSUE THREAD

**Issue by 4v4l0s** [kubernetes/minikube#9059] opened 2020-08-22 00:02 UTC
**Steps to reproduce the issue:** 

1.! StartHost failed, but will try again: creating host: create: precreate: Hyper-V PowerShell Module is not available
* Creating hyperv VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Failed to start hyperv VM. "minikube start" may fix it: creating host: create: precreate: Hyper-V PowerShell Module is not available

<>----

**Comment by sharifelgamal** [comment] 2020-08-27 21:39
This means you need to install the Hyper-V PowerShell module, you can go [here](https://www.altaro.com/hyper-v/install-hyper-v-powershell-module/) for instructions on how.

**Comment by tstromberg** [comment] 2020-09-03 16:17
This issue appears to be a duplicate of #9040, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-09-03 16:17 UTC
Labels: os/windows, priority/awaiting-more-evidence, triage/support

**Comment by JoseEsquivel07** [comment] 2023-09-15 17:21
try with 
Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Hyper-V-Tools-All -All
