### ISSUE TITLE
minkube start issue 

### ISSUE THREAD

**Issue by Shivanandlc** [kubernetes/minikube#6064] opened 2019-12-11 19:32 UTC
facing a following issue while executing the command "minikube start".  
![Capture](https://user-images.githubusercontent.com/24352003/70653576-c383bd00-1c7a-11ea-86eb-adee80e8a4fd.PNG)

please let me know what needs to be done if anyone knows. 

**The operating system version**:

**Comment by tstromberg** [comment] 2019-12-11 21:07
v1.6.1 is now available with this bug fixed: https://github.com/kubernetes/minikube/releases/tag/v1.6.1

Thank you for your patience!

Dupe of #6058

**Closed by tstromberg** 2019-12-11 21:07 UTC

**Comment by Shivanandlc** [comment] 2019-12-14 16:29
> v1.6.1 is now available with this bug fixed: https://github.com/kubernetes/minikube/releases/tag/v1.6.1
> 
> Thank you for your patience!
> 
> Dupe of #6058

**Comment by Shivanandlc** [comment] 2019-12-14 16:29
Thanks @tstromberg 👍
