### ISSUE TITLE
Error "minikube start --extra-config=apiserver.Authorization.Mode=RBAC"

### ISSUE THREAD

**Issue by dalayza** [kubernetes/minikube#5234] opened 2019-08-30 19:54 UTC
Hi, i need help. I need start auth apiserver mode in minikube but this command throws multiple error messages. The whole procedure is to make the fission route available. Thanks for al help me.

**The exact command to reproduce the issue**:
minikube start --extra-config=apiserver.Authorization.Mode=RBAC

**The full output of the command that failed**:<details>
😄  minikube v1.3.1 on Darwin 10.15
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🐳  Preparing Kubernetes v1.15.2 on Docker 18.09.8 ...
    ▪ apiserver.Authorization.Mode=RBAC
🚜  Pulling images ...
🚀  Launching Kubernetes ... 

💣  Error starting cluster: cmd failed: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--data-minikube,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap
[init] Using Kubernetes version: v1.15.2
[preflight] Running pre-flight checks
	[WARNING Service-Docker]: docker service is not enabled, please run 'systemctl enable docker.service'
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/var/lib/minikube/certs/"
[certs] Using existing ca certificate authority
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Using existing apiserver certificate and key on disk
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [minikube localhost] and IPs [192.168.99.111 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [minikube localhost] and IPs [192.168.99.111 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[kubelet-check] Initial timeout of 40s passed.

Unfortunately, an error has occurred:
	timed out waiting for the condition
error ex
Thecutiiosn pha se waerrori t-cis likoentrly caoused l-plby:
ane: couldn't initialize a Kubernetes cluster
	- The kubelet is not running
	- The kubelet is unhealthy due to a misconfiguration of the node in some way (required cgroups disabled)

If you are on a systemd-powered system, you can try to troubleshoot the error with the following commands:
	- 'systemctl status kubelet'
	- 'journalctl -xeu kubelet'

Additionally, a control plane component may have crashed or exited when started by the container runtime.
To troubleshoot, list all containers using your preferred container runtimes CLI, e.g. docker.
Here is one example how you may list all Kubernetes containers running in docker:
	- 'docker ps -a | grep kube | grep -v pause'
	Once you have found the failing container, you can inspect its logs with:
	- 'docker logs CONTAINERID'

: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-apiserver:
    error: unknown flag: --Authorization.Mode
❌  Problems detected in kube-addon-manager:
    error: unable to recognize "STDIN": Get httpWs://localRhost:8443N/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused
    error: unable to recWRogN:ni == Eze "STDIN"rr: or geGet htting dttefaulps:t servi//loccealhos at:cc8443/ouapint,?timeout=3 r2set: rydial tcp  i12n 7.0.0.05 s.1:8443econd : conne==ct
    error: unable to recognize "STDIN": Get https://localhost:8443/api?timeout=32s: dial tcp 127.0.0.1:8443: connect: connection refused

</details>

**The output of the `minikube logs` command**:<details>
limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
Aug 30 19:50:42 minikube kubelet[3878]: E0830 19:50:42.130633    3878 kubelet.go:2248] node "minikube" not found
Aug 30 19:50:42 minikube kubelet[3878]: I0830 19:50:42.151354    3878 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Aug 30 19:50:42 minikube kubelet[3878]: E0830 19:50:42.236126    3878 kubelet.go:2248] node "minikube" not found

</details>

**The operating system version**:
minikube version: v1.3.1
commit: ca60a424ce69a4d79f502650199ca2b52f29e631

**Comment by tstromberg** [comment] 2019-08-30 20:15
Do you mind including the entirety of the `minikube logs` command? Only 2.5 lines came through.

I believe this may be a dupe of #4536 -  do you mind checking if it helps to specify the config 
 option in lower-case:

`minikube start --extra-config=apiserver.authorization-mode=RBAC`

**Comment by tstromberg** [comment] 2019-08-30 20:19
I see it now in the output:

`❌ Problems detected in kube-apiserver:
error: unknown flag: --Authorization.Mode`

I'm going mark this as a duplicate of #4536 - where did you see the flag specified this way? I'd like to update the documentation.

**Comment by dalayza** [comment] 2019-08-30 20:35
Use these command line but when trying to execute a fission function, for example that appears in the helloWorld documentation, I get the error message:

Fatal error: Failed to execute HTTP request: Get http://127.0.0.1:51045/fission-function/hello: context deadline exceeded

At the end of the day I want to make this function available and generate your route services.

**Comment by tstromberg** [comment] 2019-09-20 17:35
Closing dupe. As far as the "context deadline exceeded" error, I recommend checking the output of `kubectl get po -A` and checking the logs for the service. If you still need help, please open a new issue so that it may be tracked appropriately.

**Closed** 2019-09-20 17:34 UTC
Labels: cause/apiserver-flags, triage/duplicate, triage/support
