### ISSUE TITLE
Minikube hanged on (Starting cluster components...) and stopped with an error (E0628).

### ISSUE THREAD

**Issue by wudongyin** [kubernetes/minikube#2945] opened 2018-06-28 22:23 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
**BUG REPORT**

Please provide the following details:

**Environment**: 

**Minikube version** (use `minikube version`):
- **OS**: Windows 10
- **VM Driver** : "DriverName": "hyperv",
- **ISO version** : "Boot2DockerURL": minikube-v0.28.0.iso
- **Install tools**: 
- **Others**: new installation, 1st time running

**What happened**:
The following command 
"minikube start --vm-driver=hyperv --hyperv-virtual-switch="Minikube_Virtual_Switch" --memory=2048" hanged on  
"Starting cluster components..."
and was followed by an error 
"E0628"

**What you expected to happen**:
Start minikube.

**How to reproduce it** (as minimally and precisely as possible):
Run the command again.

**Output of `minikube logs` (if applicable)**:
$ minikube start --vm-driver=hyperv --hyperv-virtual-switch="Minikube_Virtual_Sw                                                                                                                                                                                               itch" --memory=2048
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB  100.00% 0ss
Getting VM IP address...
Moving files into cluster...
Downloading kubeadm v1.10.0
Downloading kubelet v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...

E0628 17:03:10.410052   23512 start.go:294] Error starting cluster:  kubeadm ini                                                                                                                                                                                               t error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-prefl                                                                                                                                                                                               ight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=Dir                                                                                                                                                                                               Available--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight                                                                                                                                                                                               -errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-pre                                                                                                                                                                                               flight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --igno                                                                                                                                                                                               re-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-mana                                                                                                                                                                                               ger.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.                                                                                                                                                                                               yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running comma                                                                                                                                                                                               nd: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml                                                                                                                                                                                                --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-prefl                                                                                                                                                                                               ight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --i                                                                                                                                                                                               gnore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.ya                                                                                                                                                                                               ml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiser                                                                                                                                                                                               ver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-                                                                                                                                                                                               controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-                                                                                                                                                                                               manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI                                                                                                                                                                                               
.: Process exited with status 1

An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false

**Anything else do we need to know**:

**Comment by iBoonz** [comment] 2018-07-05 12:55
+1

**Comment by shivakumargn** [comment] 2018-08-10 14:07
+1 facing the same

**Comment by tstromberg** [comment] 2018-09-19 03:15
Dupe of #2493

**Closed by tstromberg** 2018-09-19 03:15 UTC
