### ISSUE TITLE
windows:  creating host: create host timed out in 120.000000 seconds

### ISSUE THREAD

**Issue by vivekaglawe** [kubernetes/minikube#6895] opened 2020-03-05 17:36 UTC
**The exact command to reproduce the issue**:
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful,

**The full output of the command that failed**:<details>

X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful,

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
windows 10 home (single language)

**Comment by Smolevich** [comment] 2020-03-10 12:15
Os: Macos Mojave 10.14.6
Minikube version: 1.8.1
Error: `command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 127.0.0.1:22: connect: connection refused`

**Comment by AlexandreDusseault** [comment] 2020-03-15 20:47
@vivekaglawe You didn't put a lot of details. I don't know it this can help you, I've just setup Minikube and I had the same error message. I've uninstalled Minikube and installed the version 1.7.2 (solution of another thread for another problem). I was then prompted with a new error. Found out it was the version 6.0 of Virtual Box that was the issue. I've installed version 6.1.4 of Virtual Box and it works now. I haven't try another time with the latest version of Minikube. If you do, let me know. Thanks,

**Comment by tstromberg** [comment] 2020-03-18 17:45
@vivekaglawe - Where is the "The full output of the command that failed"? I can't tell what version of minikube or what hypervisor you are using :(

**Comment by sashiakula** [comment] 2020-03-24 07:35
minikube start --driver=hyperv
* minikube v1.8.2 on Microsoft Windows 10 Enterprise 10.0.18363 Build 18363
* Using the hyperv driver based on existing profile
* Creating hyperv VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
*
X Unable to start VM. Please investigate and run 'minikube delete' if possible: creating host: create host timed out in 120.000000 seconds
*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by lunmatu101** [comment] 2020-04-01 15:22
I was facing the same problem and I found a root cause. 
Cause your hyper-v virtual switch is not correct for minikube (minikube chose a default from your).
So you need to create a new hyper-v virtual switch from Hyper-V manager with connection type is an external network.
Afterward, you need to add a param to your minikube cli like below:
`minikube start --driver=hyperv --hyperv-virtual-switch=minikube-switch`

**Comment by tstromberg** [comment] 2020-04-19 19:31
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it by replying `/reopen`

If someone sees a similar issue to this one, please re-open it as replies to closed issues are unlikely to be noticed.

Thank you for opening the issue!

**Closed** 2020-04-19 19:30 UTC
Labels: needs-solution-message, os/windows, triage/needs-information, triage/support

**Comment by vivekaglawe** [comment] 2020-04-20 11:21
thank you for your support sorry i am do not reply youthank you for help
