### ISSUE TITLE
--help shows incorrect  command for "a list of global command-line options"

### ISSUE THREAD

**Issue by schemacs** [kubernetes/minikube#5036] opened 2019-08-10 11:21 UTC
There is no invocation such as `minikube profile options`, but both `kubectl --help` and `kubectl <command> --help`, take `label` command for example, give correct help messages: `Use "kubectl options" for a list of global command-line options (applies to all commands).`. Maybe this pr #4879 is to be blamed?

**The exact command to reproduce the issue**:
`minikube profile --help 2>&1 |tail -n 2`

**The full output of the command that failed**:<details>
```
Use "minikube <command> --help" for more information about a given command.
Use "minikube profile options" for a list of global command-line options (applies to all commands).
```
</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
Ubuntu 18.04.2 LTS

**minikube version**:
minikube version: v1.3.0
commit: 43969594266d77b555a207b0f3e9b3fa1dc92b1f

**Comment by tstromberg** [comment] 2019-08-13 17:02
@medyagh - any context here?

**Comment by schemacs** [comment] 2019-08-14 05:43
Maybe cobra is not configured correctly?

**Comment by tstromberg** [comment] 2019-09-20 03:47
Still a bug in v1.4.

**Comment by ryanhanks** [comment] 2019-10-22 00:29
I'm also seeing this on v1.4.0. Let me know if you're struggling with steps to reproduce.

**Comment by tstromberg** [comment] 2019-10-30 18:54
Still exists in v1.5. Help wanted!

**Comment by tstromberg** [comment] 2019-10-30 18:57
@sharifelgamal may have some context here.

Also affects other commands, such as `minikube  service --help`

**Comment by andylibrian** [comment] 2019-11-07 13:46
This bug is introduced in 165c1afd331765aaa94d8db684b0045fb0713cc9

https://github.com/kubernetes/minikube/blob/master/cmd/minikube/cmd/root.go#L223

Since that commit, rootCmd reuses kubectl templates, which expects there is an options cmd.

https://github.com/kubernetes/kubectl/blob/master/pkg/util/templates/templater.go#L197-L209

@medyagh 

I created a sample option cmd, and the last line says `Use "minikube options" for a list of global command-line options (applies to all commands)` instead of `Use "minikube profile options"`

See this commit in my branch : https://github.com/andylibrian/minikube/commit/32bef17bb51733bd647f55c39dc7ad95b43ae250

```
$ ./out/minikube profile --help
profile sets the current minikube profile, or gets the current profile if no arguments are provided.  This is used to
run and manage multiple minikube instance.  You can return to the default minikube profile by running `minikube profile
default`

Available Commands:
  list        Lists all minikube profiles.

Usage:
  minikube profile [MINIKUBE_PROFILE_NAME].  You can return to the default minikube profile by running `minikube profile
default` [flags] [options]

Use "minikube <command> --help" for more information about a given command.
Use "minikube options" for a list of global command-line options (applies to all commands).
```

```
$ ./out/minikube options
The following options can be passed to any command:
```

So, the solution could be implementing optionsCmd or not reusing kubectl templates.

**Comment by medyagh** [comment] 2019-12-16 22:16
@andylibrian  that sounds good ! could you please make a PR ? I will be happy to review it.

**Comment by andylibrian** [comment] 2019-12-21 04:35
@medyagh I've just sent a PR for this: https://github.com/kubernetes/minikube/pull/6144

**Comment by medyagh** [comment] 2019-12-24 09:57
@andylibrian thank you for the PR. merged.

**Closed** 2019-12-24 09:57 UTC
Labels: help wanted, kind/bug, priority/backlog
