### ISSUE TITLE
hyperkit: with Cisco AnyConnect VPN on Mac: Unable to connect to outside world

### ISSUE THREAD

**Issue by jkholtzman** [kubernetes/minikube#9504] opened 2020-10-20 21:34 UTC
Cannot start basic test pod through kubectl with VPN active. Shows 0/1 ready. Have tried hyperkit and docker drivers. Exact same configuration runs when VPN disabled. Have checked the "allow local LAN" box in Cisco, has no effect.

MacOS 10.15.7 Catalina latest
minikube version: v1.14.0
Cisco AnyConnect Secure Mobility Client Version 4.8.03036
Kubectl: Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"darwin/amd64"}

**Comment by tstromberg** [comment] 2020-10-21 00:43
I don’t yet have a clear way to replicate this issue. Do you mind adding some additional details? Here is additional information that would be helpful:

*  The exact `minikube start` command line used
*  The full output of the `minikube start` command
*  The full output of `minikube status`
*  The full output of `minikube logs`

Ultimately, this may come down to a VPN configuration issue: https://minikube.sigs.k8s.io/docs/handbook/vpn_and_proxy/#vpn - it'd be nice to understand what the underlying failure is.

**Comment by jkholtzman** [comment] 2020-10-21 14:10
The following is with Cisco VPN running. You can see I added a no proxy entry for the minikube network 192.168.64.0/24.

$ minikube start
😄  minikube v1.14.0 on Darwin 10.15.7
✨  Using the hyperkit driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=20000MB) ...
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.64.0/24
❗  This VM is having trouble accessing https://k8s.gcr.io
💡  To pull new external images, you may need to configure a proxy: https://minikube.sigs.k8s.io/docs/reference/networking/proxy/
🐳  Preparing Kubernetes v1.19.2 on Docker 19.03.12 ...
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24,192.168.64.0/24
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" by default
[06-simplek8s] $ minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured


Following is the log output.

[minikube_logs.txt](https://github.com/kubernetes/minikube/files/5416464/minikube_logs.txt)

Thanks for looking into it.

**Comment by tstromberg** [comment] 2020-10-21 16:03
So, minikube looks healthy -- when you try to start your test pod -- what happens?

The output of `kubectl describe <pod>` and `kubectl logs <pod>` would be helpful.

Based on this message: `This VM is having trouble accessing https://k8s.gcr.io` -- I suspect that the issue may come down to the Cisco VPN not allowing outgoing access to the internet from Docker by default. As a quick test, can you confirm the following command works withy our VPN:

`docker run -it ubuntu apt update`

That will let us know if this problem needs to be solved within Docker/Cisco VPN, or within minikube.

**Comment by jkholtzman** [comment] 2020-10-21 17:15
[06-simplek8s] $ kubectl apply -f client-pod.yaml
pod/client-pod created
[06-simplek8s] $ kubectl apply -f client-node-port.yaml
service/client-node-port created
[06-simplek8s] $ kubectl get pods
NAME         READY   STATUS             RESTARTS   AGE
client-pod   0/1     ImagePullBackOff   0          40s

[06-simplek8s] $ kubectl describe client-pod
error: the server doesn't have a resource type "client-pod"
[06-simplek8s] $ kubectl logs client-pod
Error from server (BadRequest): container "client" in pod "client-pod" is waiting to start: trying and failing to pull image

[06-simplek8s] $ minikube delete
🔥  Deleting "minikube" in hyperkit ...
💀  Removed all traces of the "minikube" cluster.

[06-simplek8s] $ docker run -it ubuntu apt update
Unable to find image 'ubuntu:latest' locally
latest: Pulling from library/ubuntu
d72e567cc804: Pull complete
0f3630e5ff08: Pull complete
b6a83d81d1f4: Pull complete
Digest: sha256:bc2f7250f69267c9c6b66d7b6a81a54d3878bb85f1ebb5f951c896d13e6ba537
Status: Downloaded newer image for ubuntu:latest
Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]
Get:2 http://archive.ubuntu.com/ubuntu focal InRelease [265 kB]
Get:3 http://security.ubuntu.com/ubuntu focal-security/main amd64 Packages [428 kB]
Get:4 http://security.ubuntu.com/ubuntu focal-security/restricted amd64 Packages [84.4 kB]
Get:5 http://security.ubuntu.com/ubuntu focal-security/multiverse amd64 Packages [1170 B]
Get:6 http://security.ubuntu.com/ubuntu focal-security/universe amd64 Packages [630 kB]
Get:7 http://archive.ubuntu.com/ubuntu focal-updates InRelease [111 kB]
Get:8 http://archive.ubuntu.com/ubuntu focal-backports InRelease [98.3 kB]
Get:9 http://archive.ubuntu.com/ubuntu focal/main amd64 Packages [1275 kB]
Get:10 http://archive.ubuntu.com/ubuntu focal/multiverse amd64 Packages [177 kB]
Get:11 http://archive.ubuntu.com/ubuntu focal/restricted amd64 Packages [33.4 kB]
Get:12 http://archive.ubuntu.com/ubuntu focal/universe amd64 Packages [11.3 MB]
Get:13 http://archive.ubuntu.com/ubuntu focal-updates/multiverse amd64 Packages [21.6 kB]
Get:14 http://archive.ubuntu.com/ubuntu focal-updates/restricted amd64 Packages [103 kB]
Get:15 http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages [782 kB]
Get:16 http://archive.ubuntu.com/ubuntu focal-updates/universe amd64 Packages [840 kB]
Get:17 http://archive.ubuntu.com/ubuntu focal-backports/universe amd64 Packages [4277 B]
Fetched 16.3 MB in 3s (5788 kB/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
4 packages can be upgraded. Run 'apt list --upgradable' to see them.

Thanks again.

**Comment by tstromberg** [comment] 2020-10-21 17:31
Oh, sorry I had missed that detail. From what I've seen, Docker has built-in support to work with Cisco AnyConnect, so it should workaround this issue. Hyperkit does not. It's worth noting that Docker *does* use Hyperkit underneath, but also uses VPNKit, as it's automatically provided by Docker.

**Comment by tstromberg** [comment] 2020-10-21 17:32
This issue appears to be a duplicate of #6296, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-10-21 17:32 UTC
Labels: cause/vpn, kind/support, triage/needs-information
