### ISSUE TITLE
minicub start error

### ISSUE THREAD

**Issue by tushar453030** [kubernetes/minikube#14528] opened 2022-07-08 09:02 UTC
### What Happened?

```minikube v1.26.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000
Using the docker driver based on existing profile
Starting control plane node minikube in cluster minikube
Pulling base image ...
Updating the running docker "minikube" container ...
X Exiting due to RUNTIME_ENABLE: sudo service cri-docker.socket start: Process exited with status 5
stdout:

stderr:
Failed to start cri-docker.socket.service: Unit cri-docker.socket.service not found.```

I am having this error can anybody solve

### Attach the log file

minikube v1.26.0 on Microsoft Windows 11 Home Single Language 10.0.22000 Build 22000
Using the docker driver based on existing profile
Starting control plane node minikube in cluster minikube
Pulling base image ...
Updating the running docker "minikube" container ...
X Exiting due to RUNTIME_ENABLE: sudo service cri-docker.socket start: Process exited with status 5
stdout:

stderr:
Failed to start cri-docker.socket.service: Unit cri-docker.socket.service not found.

I am having this error can anybody solve

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment] 2022-07-13 18:59
Hi @tushar453030, thanks for reporting your issue with minikube.

This is a duplicate of https://github.com/kubernetes/minikube/issues/14410, I left a detailed comment solution for anyone experiencing problems https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503.

Since you're using the Docker driver, running `minikube delete` and starting minikube again should resolve your issue.

I'm going to close this issue as it's a duplicate, but if you have following questions or want to read more about the problem check out https://github.com/kubernetes/minikube/issues/14410, thanks!

**Closed by spowelljr** 2022-07-13 18:59 UTC
