### ISSUE TITLE
ENV for matching CRI runtime

### ISSUE THREAD

**Issue by vbatts** [kubernetes/minikube#3024] opened 2018-07-27 18:32 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): BUG?

**Environment**:

**Minikube version** (use `minikube version`): v0.28.2
- **OS** (e.g. from /etc/os-release): fedora 28
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): VirtualBox
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`): v0.28.1.iso
- **Install tools**:
- **Others**:

**What happened**: 
Started minikube with `minikube start --vm-driver=virtualbox --container-runtime=crio`
Then:
```shell
$> minikube ssh
$> sudo su -
#> crictl ps
FATA[0000] listing containers failed: rpc error: code = Unavailable desc = grpc: the connection is unavailable 
```

**What you expected to happen**:
See the running containers

**the issue and resolution**:
with no `--runtime-endpoint` flag or `$CONTAINER_RUNTIME_ENDPOINT` env variable, then crictl defaults to `"unix:///var/run/dockershim.sock"`. _*BUT*_ since we've specified crio then there ought to be a system env variable like `CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock"`.

In the meantime, using `crictl -r unix:///var/run/crio/crio.sock ps` works fine, but must be used on every command (or just `export CONTAINER_RUNTIME_ENDPOINT="unix:///var/run/crio/crio.sock"`)

**Comment by prabhatsharma** [comment] 2018-09-04 16:42
I had to run below to make it work
`$sudo crictl -r unix:///var/run/containerd/containerd.sock ps`

**Comment by tstromberg** [comment] 2018-09-18 23:10
Dupe of #3043

**Closed by tstromberg** 2018-09-18 23:10 UTC
