### ISSUE TITLE
v1.11.0 with linux+docker failing on inspecting IP bridge network

### ISSUE THREAD

**Issue by tariqajyusuf** [kubernetes/minikube#8345] opened 2020-06-01 17:28 UTC
**Steps to reproduce the issue:** 

1. Update from 1.9.2.
2. `minikube delete`
3. `minikube start`

**Full output of failed command:** 

```
yusuft@stormyweather:~$ minikube start
😄  minikube v1.11.0 on Debian rodete
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v3-v1.18.3-docker-overlay2-amd64.tar.lz4: 526.01 MiB
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
E0601 09:21:37.989349   37401 start.go:94] Unable to get host IP: inspect IP bridge network "ee686e111dd4\n98b7bd9fcd08".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" ee686e111dd4
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such network: ee686e111dd4
98b7bd9fcd08

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "ee686e111dd4\n98b7bd9fcd08".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" ee686e111dd4
98b7bd9fcd08: exit status 1
stdout:


stderr:
Error: No such network: ee686e111dd4
98b7bd9fcd08


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```

Current workaround is to downgrade back to v1.9.2.

**Optional: Full output of `minikube logs` command:**
<details>

Some `dmesg` logs are redacted for privacy

```
yusuft@stormyweather:~$ minikube logs
==> Docker <==
-- Logs begin at Mon 2020-06-01 17:21:23 UTC, end at Mon 2020-06-01 17:24:29 UTC. --
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.667058280Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.667160998Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007e3a90, CONNECTING" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.667196946Z" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.667822415Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0007e3a90, READY" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669281861Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669322973Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669351883Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669380827Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669524413Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000744840, CONNECTING" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.669552509Z" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.670044954Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000744840, READY" module=grpc
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.673437418Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.705769773Z" level=warning msg="Your kernel does not support swap memory limit"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.705829481Z" level=warning msg="Your kernel does not support cgroup rt period"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.705851756Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.705864842Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.705876950Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.706148528Z" level=info msg="Loading containers: start."
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.805586715Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 01 17:21:23 minikube dockerd[116]: time="2020-06-01T17:21:23.870665171Z" level=info msg="Loading containers: done."
Jun 01 17:21:34 minikube dockerd[116]: time="2020-06-01T17:21:34.946126745Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
Jun 01 17:21:34 minikube dockerd[116]: time="2020-06-01T17:21:34.946318676Z" level=info msg="Daemon has completed initialization"
Jun 01 17:21:35 minikube dockerd[116]: time="2020-06-01T17:21:35.008480790Z" level=info msg="API listen on /run/docker.sock"
Jun 01 17:21:35 minikube systemd[1]: Started Docker Application Container Engine.
Jun 01 17:21:36 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Jun 01 17:21:36 minikube systemd[1]: Stopping Docker Application Container Engine...
Jun 01 17:21:36 minikube dockerd[116]: time="2020-06-01T17:21:36.627838390Z" level=info msg="Processing signal 'terminated'"
Jun 01 17:21:36 minikube dockerd[116]: time="2020-06-01T17:21:36.629158062Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Jun 01 17:21:36 minikube dockerd[116]: time="2020-06-01T17:21:36.629935500Z" level=info msg="Daemon shutdown complete"
Jun 01 17:21:36 minikube dockerd[116]: time="2020-06-01T17:21:36.630008339Z" level=info msg="stopping event stream following graceful shutdown" error="context canceled" module=libcontainerd namespace=plugins.moby
Jun 01 17:21:36 minikube systemd[1]: docker.service: Succeeded.
Jun 01 17:21:36 minikube systemd[1]: Stopped Docker Application Container Engine.
Jun 01 17:21:36 minikube systemd[1]: Starting Docker Application Container Engine...
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.689295138Z" level=info msg="Starting up"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.691781500Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.691825835Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.691848645Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.691863170Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.691959384Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00013f680, CONNECTING" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.692382664Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc00013f680, READY" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.693360595Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.693389063Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.693414804Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.693433393Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.693519263Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001eb380, CONNECTING" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.694004802Z" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0001eb380, READY" module=grpc
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.697913960Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710324522Z" level=warning msg="Your kernel does not support swap memory limit"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710378244Z" level=warning msg="Your kernel does not support cgroup rt period"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710387034Z" level=warning msg="Your kernel does not support cgroup rt runtime"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710395228Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710409780Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.710591034Z" level=info msg="Loading containers: start."
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.840358309Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.894043723Z" level=info msg="Loading containers: done."
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.964078725Z" level=info msg="Docker daemon" commit=6a30dfca03 graphdriver(s)=overlay2 version=19.03.2
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.964185814Z" level=info msg="Daemon has completed initialization"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.991632722Z" level=info msg="API listen on /var/run/docker.sock"
Jun 01 17:21:36 minikube dockerd[347]: time="2020-06-01T17:21:36.991632720Z" level=info msg="API listen on [::]:2376"
Jun 01 17:21:36 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2020-06-01T17:24:31Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0601 09:24:31.834306   39488 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"

==> dmesg <==
[  +0.010136] <REDACTED>
[  +0.007222] <REDACTED>
[  +0.015593] <REDACTED>
[  +4.594025] kauditd_printk_skb: 98 callbacks suppressed
[  +0.499401] systemd[1]: Another IMA custom policy has already been loaded, ignoring: No such file or directory
[  +2.975633] systemd[1]: /lib/systemd/system/logrotate.service:19: Unknown key name 'ProtectClock' in section 'Service', ignoring.
[  +2.645839] kauditd_printk_skb: 29 callbacks suppressed
[  +3.684613] ext2 filesystem being mounted at /boot supports timestamps until 2038 (0x7fffffff)
[  +1.379134] kauditd_printk_skb: 122 callbacks suppressed
[ +17.431188] linhelmk: loading out-of-tree module taints kernel.
[Jun 1 17:17] kmem.limit_in_bytes is deprecated and will be removed. Please report your usecase to linux-mm@kvack.org if you depend on this functionality.
[ +21.598716] ------------[ cut here ]------------
[  +0.000002] rq->tmp_alone_branch != &rq->leaf_cfs_rq_list
[  +0.000017] WARNING: CPU: 4 PID: 0 at kernel/sched/fair.c:380 enqueue_task_fair+0x340/0x4c0
[  +0.000001] Modules linked in: iptable_mangle(E) xt_comment(E) xt_nat(E) veth(E) vxlan(E) ip6_udp_tunnel(E) udp_tunnel(E) xt_policy(E) xt_mark(E) xt_u32(E) xt_tcpudp(E) xt_conntrack(E) xt_MASQUERADE(E) nf_conntrack_netlink(E) xfrm_user(E) xfrm_algo(E) xt_addrtype(E) nft_compat(E) br_netfilter(E) bridge(E) stp(E) llc(E) tcp_diag(E) inet_diag(E) rfkill(E) overlay(E) nft_chain_nat(E) nft_counter(E) iptable_nat(E) nf_nat(E) nf_conntrack(E) nf_defrag_ipv6(E) nf_defrag_ipv4(E) iptable_filter(E) nf_tables(E) nfnetlink(E) cpufreq_powersave(E) linhelmk(OE) cpufreq_userspace(E) cpufreq_conservative(E) fuse(E) binfmt_misc(E) intel_rapl_msr(E) intel_rapl_common(E) sb_edac(E) sg(E) virtio_balloon(E) serio_raw(E) pvpanic(E) evdev(E) intel_rapl_perf(E) parport_pc(E) ppdev(E) lp(E) parport(E) tcp_bbr(E) sunrpc(E) virtio_rng(E) rng_core(E) ip_tables(E) x_tables(E) autofs4(E) ext4(E) crc16(E) mbcache(E) jbd2(E) btrfs(E) blake2b_generic(E) xor(E) zstd_decompress(E) zstd_compress(E) raid6_pq(E) libcrc32c(E)
[  +0.000035]  crc32c_generic(E) dm_mod(E) crct10dif_pclmul(E) crc32_pclmul(E) crc32c_intel(E) ghash_clmulni_intel(E) sd_mod(E) virtio_scsi(E) virtio_net(E) net_failover(E) scsi_mod(E) failover(E) aesni_intel(E) crypto_simd(E) virtio_pci(E) virtio_ring(E) cryptd(E) glue_helper(E) psmouse(E) virtio(E) i2c_piix4(E) button(E)
[  +0.000013] CPU: 4 PID: 0 Comm: swapper/4 Tainted: G           OE     5.5.17-1rodete4-amd64 #1 Debian 5.5.17-1rodete4
[  +0.000001] <REDACTED>
[  +0.000002] RIP: 0010:enqueue_task_fair+0x340/0x4c0
[  +0.000002] Code: 60 09 00 00 0f 84 45 fe ff ff 80 3d 65 08 04 01 00 0f 85 38 fe ff ff 48 c7 c7 d8 8a 8d 88 c6 05 51 08 04 01 01 e8 62 04 fc ff <0f> 0b e9 1e fe ff ff 49 8b 9f 48 01 00 00 49 8d 97 40 01 00 00 4c
[  +0.000001] RSP: 0018:ffffabf140160e30 EFLAGS: 00010086
[  +0.000001] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 0000000000000000
[  +0.000001] RDX: 000000000000002d RSI: ffffffff890483ed RDI: 0000000000000046
[  +0.000000] RBP: ffff8c4c5fd2cb40 R08: 000006d7718ee82f R09: 000000000000002d
[  +0.000001] R10: 0000000000000000 R11: 0000000000000001 R12: ffff8c4c5fd2cac0
[  +0.000001] R13: ffff8c4c5fd2cac0 R14: 0000000000000000 R15: ffff8c4c5fd2cac0
[  +0.000001] FS:  0000000000000000(0000) GS:ffff8c4c5fd00000(0000) knlGS:0000000000000000
[  +0.000001] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  +0.000001] CR2: 00007ffb84000010 CR3: 00000005da5f0006 CR4: 00000000003606e0
[  +0.000003] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[  +0.000000] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[  +0.000001] Call Trace:
[  +0.000003]  <IRQ>
[  +0.000007]  activate_task+0x7a/0x160
[  +0.000001]  ttwu_do_activate+0x45/0x60
[  +0.000002]  try_to_wake_up+0x1f1/0x670
[  +0.000003]  ? kmem_cache_free+0x27f/0x2a0
[  +0.000004]  ? hrtimer_init_sleeper+0x90/0x90
[  +0.000002]  hrtimer_wakeup+0x1e/0x30
[  +0.000002]  __hrtimer_run_queues+0xf6/0x270
[  +0.000001]  hrtimer_interrupt+0x10e/0x240
[  +0.000005]  smp_apic_timer_interrupt+0x6c/0x130
[  +0.000002]  apic_timer_interrupt+0xf/0x20
[  +0.000002]  </IRQ>
[  +0.000003] RIP: 0010:native_safe_halt+0xe/0x10
[  +0.000001] Code: cc cc cc cc cc cc cc cc cc cc cc cc e9 07 00 00 00 0f 00 2d 26 56 42 00 f4 c3 66 90 e9 07 00 00 00 0f 00 2d 16 56 42 00 fb f4 <c3> cc 0f 1f 44 00 00 41 54 55 53 e8 42 1b 92 ff 65 8b 2d 33 f1 e2
[  +0.000001] RSP: 0018:ffffabf14008feb0 EFLAGS: 00000246 ORIG_RAX: ffffffffffffff13
[  +0.000001] RAX: ffffffff881e2f10 RBX: 0000000000000004 RCX: 0000000000000001
[  +0.000000] RDX: 0000000000c59b42 RSI: ffffabf14008fe58 RDI: 000006d78c38b438
[  +0.000001] RBP: 0000000000000004 R08: 0000000000000001 R09: ffff8c4c5c2071c8
[  +0.000001] R10: 0000000000e9d7fe R11: 0000000000000000 R12: ffff8c4547ea8000
[  +0.000000] R13: 0000000000000000 R14: 0000000000000000 R15: ffff8c4547ea8000
[  +0.000002]  ? __sched_text_end+0x2/0x2
[  +0.000004]  default_idle+0x1a/0x140
[  +0.000003]  do_idle+0x202/0x280
[  +0.000002]  ? do_idle+0xb/0x280
[  +0.000002]  cpu_startup_entry+0x19/0x20
[  +0.000002]  start_secondary+0x15f/0x1b0
[  +0.000004]  secondary_startup_64+0xa4/0xb0
[  +0.000002] ---[ end trace 91a0949a4f9dabd1 ]---

==> kernel <==
 17:24:31 up  2:12,  0 users,  load average: 0.21, 0.81, 0.58
Linux minikube 5.5.17-1rodete4-amd64 #1 SMP Debian 5.5.17-1rodete4 (2020-05-08 > 2018) x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 19.10"

==> kubelet <==
-- Logs begin at Mon 2020-06-01 17:21:23 UTC, end at Mon 2020-06-01 17:24:31 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes
```

</details>

**Comment by afbjorklund** [comment] 2020-06-01 17:33
Most likely a duplicate of #8131, like if having enabled docker swarm or creating a bridge network

**Comment by tariqajyusuf** [comment] 2020-06-01 22:42
Confirmed. Followed the workaround in https://github.com/kubernetes/minikube/issues/8131#issuecomment-628529660 and it resolved the issue.

**Comment by sharifelgamal** [comment] 2020-06-02 21:06
I'm going to go ahead and close this as a duplicate. If anything comes back up, feel free to reopen.

**Closed by sharifelgamal** 2020-06-02 21:06 UTC
Labels: co/docker-driver, os/linux, triage/duplicate
