### ISSUE TITLE
cann't access kubectl from windows prompt

### ISSUE THREAD

**Issue by technicalpriyanka** [kubernetes/minikube#13646] opened 2022-02-21 15:43 UTC
### What Happened?

access issue

### Attach the log file

[log.txt](https://github.com/kubernetes/minikube/files/8110507/log.txt)

**Comment by spowelljr** [comment] 2022-02-22 05:44
Duplicate of https://github.com/kubernetes/minikube/issues/13647, closing

**Closed by spowelljr** 2022-02-22 05:44 UTC
