### ISSUE TITLE
signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd70f

### ISSUE THREAD

**Issue by spursy** [kubernetes/minikube#6173] opened 2019-12-29 13:43 UTC
**I encounter the followed issue:**

```
 minikube start
😄  Darwin 10.14.6 上的 minikube v1.6.2
✨  Selecting 'virtualbox' driver from user configuration (alternates: [hyperkit])
🔥  正在创建 virtualbox 虚拟机（CPUs=2，Memory=2000MB, Disk=20000MB）...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x4ecd70f]

goroutine 87 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0xc00069c5d0, 0xa, 0xc00069c5db, 0x12, 0xc00069c5ee, 0x6, 0x0, 0x0, 0xc000567c68, ...)
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x12f
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc00069c5d0, 0x24, 0xc00069e1e0, 0x47, 0x0, 0x0)
	/private/tmp/minikube-20191220-77113-wmp8w9/pkg/minikube/machine/cache_images.go:395 +0x5df
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc00005d768, 0x0)
	/private/tmp/minikube-20191220-77113-wmp8w9/pkg/minikube/machine/cache_images.go:85 +0x124
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc0005f6120, 0xc0005f62a0)
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/private/tmp/minikube-20191220-77113-wmp8w9/.brew_home/go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```
**My Go Version:**

```bash
➜  ~ go version && go env
go version go1.13.4 darwin/amd64
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/user/Library/Caches/go-build"
GOENV="/Users/user/Library/Application Support/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GONOPROXY=""
GONOSUMDB=""
GOOS="darwin"
GOPATH="/Volumes/yy/Go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
AR="ar"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/tf/0c44q9293rvdv495h4bd5d6m0000gn/T/go-build259632854=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

**Comment by tanzhongyibidu** [comment] 2020-01-06 05:00
I meet same problem when start minikube on mac with hyperkit vm driver

**Comment by tstromberg** [comment] 2020-01-08 20:06
This issue appears to be a duplicate of #6147, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-01-08 20:06 UTC
