### ISSUE TITLE
Service nginx-service was not found in "default" 

### ISSUE THREAD

**Issue by ramesh-kumarjha** [kubernetes/minikube#7106] opened 2020-03-19 10:43 UTC
service.yaml
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: my-nam
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31567 

getting thhis error    Error opening service: Service nginx-service was not found in "default" namespace. You may select another namespace by using 'minikube service nginx-service -n <namespace>: Temporary Error: Error getting service nginx-service: services "nginx-service" not found

**Comment by ramesh-kumarjha** [comment] 2020-03-19 10:44
error

**Comment by tstromberg** [comment] 2020-03-19 20:35
Can you share the command-line you used?

This should be`minikube service nginx-service -n my-nam`.

**Comment by ramesh-kumarjha** [comment] 2020-03-19 20:47
> Can you share the command-line you used?
> 
> This should be`minikube service nginx-service -n my-nam`.

I am using the same command

**Comment by ramesh-kumarjha** [comment] 2020-03-19 20:48
I am using the same command which you have mentioned

**Comment by priyawadhwa** [comment] 2020-03-25 18:33
Hey @ramesh-kumarjha I tried to reproduce the error at HEAD by running:

```
kubectl create ns my-nam
kubectl apply -f service.yaml
```

where service.yaml is:

```yaml
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
    namespace: my-nam
spec:
    selector:
        app: nginx
    type: NodePort
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31567
```

and then running:

```
$ minikube service nginx-service -n my-nam
|-----------|---------------|-------------|-----------------------------|
| NAMESPACE |     NAME      | TARGET PORT |             URL             |
|-----------|---------------|-------------|-----------------------------|
| my-nam    | nginx-service |             | http://192.168.64.149:31567 |
|-----------|---------------|-------------|-----------------------------|
🎉  Opening service my-nam/nginx-service in default browser...
```

which worked as expected with the hyperkit driver on mac OS. 

Could you try upgrading to the latest version of minikube and provide:

* What operating system you're running on
* What driver you're using with minikube
* The output of `kubectl get svc -A`

**Comment by ramesh-kumarjha** [comment] 2020-03-27 05:39
hyperkit: v0.20190802-4-g97f091

Homepage: https://github.com/docker/hyperkit
License: BSD
os - macOS
driver hyperkit
kubectl output..
default                kubernetes                  ClusterIP   .....      <none>        443/TCP                  7d20h
kube-system            kube-dns                    ClusterIP   ......     <none>        53/UDP,53/TCP,9153/TCP   57d
kubernetes-dashboard   dashboard-metrics-scraper   ClusterIP   ......  <none>        8000/TCP                 57d
kubernetes-dashboard   kubernetes-dashboard        ClusterIP   .......   <none>        80/TCP                   57d
my-nam           nginx-servic                NodePort    .......   <none>        80:31563/TCP             7d17h

**Comment by medyagh** [comment] 2020-04-08 18:54
@ramesh-kumarjha do you mind pasting the output again ? the fomratting seems to be missing something

**Comment by priyawadhwa** [comment] 2020-06-03 18:25
Hey @ramesh-kumarjha are you still seeing this issue with minikube [v1.11.0](https://github.com/kubernetes/minikube/releases/tag/v1.11.0)?

**Comment by ramesh-kumarjha** [comment] 2020-06-03 18:41
Hi
 No i fixed that issues and now its working fine

**Comment by priyawadhwa** [comment] 2020-06-03 18:55
Great, I'll go ahead and close this issue.

**Closed by priyawadhwa** 2020-06-03 18:55 UTC
Labels: co/service, triage/needs-information, triage/not-reproducible, triage/support
