### ISSUE TITLE
Error creating host: Error creating machine: The system cannot find the path specified

### ISSUE THREAD

**Issue by Alber70g** [kubernetes/minikube#822] opened 2016-11-15 11:48 UTC
**BUG REPORT**

**Minikube version** (use `minikube version`):
v0.12.2

**Environment**:
- **OS**: windows 7
- **VM Driver**: virtualbox
- **Docker version** (e.g. `docker -v`): 1.10.2, build c3959b1
- **Install tools**: 
- **Others**: I'm running it on a work environment. This is why there's a network disk what is the home-directory `~`. This causes problems when minikube tries to reference the iso. 

**What happened**:
Running `minikube start` will result in this error:

```
Error creating host: Error creating machine: Error in driver during machine creation: open /.minikube/cache/iso/minikube-0.7.iso: The system cannot find the path specified.
```

**What you expected to happen**:
To install the iso in the virtual box

**How to reproduce it** (as minimally and precisely as possible):
Have a share where your personal folders reside

**Anything else do we need to know**:

# **SOLUTION**
Do the following: 
- run `minikube delete` (to clean up what is here now)
- run `minikube start --show-libmachine-logs` so you know where the file is stored
- move the file that is downloaded to `C:/.minikube/cache/iso/minikube-0.7.iso`
- run `minikube delete` again and retry installing with `minikube start`

**Comment by r2d4** [comment] 2016-11-15 17:59
Hey thanks for the detailed bug report.  We should fix this issue because its pretty common to be running minikube in a work environmnet.  This is actually a known issue already and its being tracked here https://github.com/kubernetes/minikube/issues/459

I'm going to close this as a dupe of #459 but we should take another look into fixing this

**Closed by r2d4** 2016-11-15 17:59 UTC
Labels: kind/bug, platform/windows

**Comment by Alber70g** [comment] 2016-11-15 22:02
Thank you vary much. Good to close it. I did a quick search and I din't find it, my bad. 

There should probably be a way to define a working directory for the minikube so that it doesn't use the home directory (which can be a network share).

**Comment by rsantunes** [comment] 2017-06-28 12:12
Hi,

I had the same issue that was described here, but in my case the root cause was the fact that my minikube was installed in a different partition (D:) than the ISO file downloaded during the start process (C:). 
The solution in my case was to move the minikube to a folder inside the C: partition
