### ISSUE TITLE
delete config after failed start

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9567] opened 2020-10-27 20:07 UTC
example

windows with windows container on data center windows

minikbue skips docker driver since os type is windows
then tries hyperv and it is failed

better to delete that config
so when user switches os type to linux, they can re-use docker driver not be stuck with hyperv

**Comment by sharifelgamal** [comment] 2020-11-09 19:15
Closing as a dupe of #9397

**Closed by sharifelgamal** 2020-11-09 19:15 UTC
Labels: kind/bug, priority/important-soon
