### ISSUE TITLE
AUR package should be named "minikube-bin" instead of "minikube"

### ISSUE THREAD

**Issue by eli-schwartz** [kubernetes/minikube#2974] opened 2018-07-12 15:18 UTC
Added in #1642 but the package name is erroneous. It should be "minikube-bin" for prebuilt upstream binaries, and "minikube" only for built-from-source recipes.

Another Arch Trusted User discussed this on the comments page, then deleted the "minikube" package and merged the comments/votes into the existing "minikube-bin" namespace. However, I guess none of the bot's controllers were actually paying attention to the thing they created?

This is kind of not very nice. :(

...

Your bot was even added as a comaintainer to the "minikube-bin" package.

Please either decommission your bot or tell it to update the right package instead of re-uploading one which was deleted by the administrators.

You may also consider writing a PKGBUILD which builds minikube from source code, and maintaining that as "minikube" instead of or in addition to the "minikube-bin" package

**Comment by eli-schwartz** [comment] 2018-09-05 16:33
Since you've continued to ignore me, please contact me when you wish your AUR account's suspension to be lifted.

**Comment by tstromberg** [comment] 2018-09-18 23:58
Thanks for the bug report! We admittedly haven't had anyone watching the issues lately, so we missed this.   Not sure yet when we'll get a chance to get this one fixed.

**Comment by tstromberg** [comment] 2018-09-19 10:07
Dupe of #2640

**Closed by tstromberg** 2018-09-19 10:07 UTC
Labels: kind/bug, packaging, packaging/aur
