### ISSUE TITLE
enable failed: run callbacks: heapster is not a valid addon

### ISSUE THREAD

**Issue by KellerKnebel** [kubernetes/minikube#8523] opened 2020-06-20 23:05 UTC
</details>

**A saída do comando `minikube logs`**:<details>

enable failed: run callbacks: heapster is not a valid addon

</details>

**A versão do sistema operacional usado**:

**Comment by tstromberg** [comment] 2020-06-24 17:34
`heapster` was deprecated in favor of `metrics-server`.

The next release will have an alias.

Duplicate of #6115 and #8360 

Hope this helps!

**Closed** 2020-06-24 17:35 UTC
Labels: l/pt-BR, triage/duplicate, triage/support
