### ISSUE TITLE
docker: Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#9409] opened 2020-10-06 23:26 UTC
in this embeded use case, minikube detected that DiskSpace is full but when it exited, it gave the exit code RV_CP_ENDPOINT which is not correct, we should improve the exit code to reflect the real reason

```
Failed to start minikube: Error while starting Minikube. Error: ! minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3, but successfully downloaded gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3 as a fallback image
,X Docker is nearly out of disk space, which may cause deployments to fail! (90% of capacity)
,* Suggestion: 

    Try at least one of the following to free up space on the device:
    
    1. Run "docker system prune" to remove unused docker data
    2. Increase the amount of memory allocated to Docker for Desktop via
    Docker icon > Preferences > Resources > Disk Image Size
    3. Run "minikube ssh -- docker system prune" if using the docker container runtime
* Related issue: https://github.com/kubernetes/minikube/issues/9024
,X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
,* 
,* If the above advice does not help, please let us know: 
,  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by tstromberg** [comment] 2020-10-07 02:36
I don't think this is correct. 90% of capacity should not cause a failure, or exit prematurely. Could you help me to see  connection between the warning and the inability to determine what IP to use?

That said, there is room for an additional check if the total available disk space is under say, 500MB, but I don't think that is likely what happened here.

**Comment by priyawadhwa** [comment] 2020-10-07 18:28
Yah @medyagh I think the disk space is just a warning at 90%. I think we can close this issue?

**Comment by tstromberg** [comment] 2020-10-08 17:29
As seen on Cloud Run:

```
I1006 22:33:51.377450   48191 translate.go:64] Getting system locale failed: Could not detect Language
I1006 22:33:51.378058   48191 translate.go:106] Setting Language to en-US ...
I1006 22:33:51.378421   48191 out.go:184] Setting OutFile to fd 1 ...
I1006 22:33:51.378433   48191 out.go:231] TERM=,COLORTERM=, which probably does not support color
I1006 22:33:51.378437   48191 out.go:197] Setting ErrFile to fd 2...
I1006 22:33:51.378441   48191 out.go:231] TERM=,COLORTERM=, which probably does not support color
I1006 22:33:51.378590   48191 root.go:278] Updating PATH: /google/minikube/.minikube/bin
I1006 22:33:51.379003   48191 out.go:191] Setting JSON to false
I1006 22:33:51.450351   48191 start.go:102] hostinfo: {"hostname":"cs-211886294761-default-boost3-mf6l4","uptime":3876,"bootTime":1602019755,"procs":92,"os":"linux","platform":"debian","platformFamily":"debian","platformVersion":"10.5","kernelVersion":"5.4.49+","virtualizationSystem":"","virtualizationRole":"","hostid":"c31eea55-a294-3153-5ff0-1de94bdcf5cf"}
I1006 22:33:51.450957   48191 start.go:112] virtualization:  
I1006 22:33:51.454697   48191 out.go:109] * [cloud-run-dev-internal] minikube v1.13.1 on Debian 10.5
I1006 22:33:51.454900   48191 notify.go:126] Checking for updates...
I1006 22:33:51.457116   48191 out.go:109]   - MINIKUBE_FORCE_SYSTEMD=true
I1006 22:33:51.459366   48191 out.go:109]   - MINIKUBE_HOME=/google/minikube
I1006 22:33:51.460086   48191 driver.go:287] Setting default libvirt URI to qemu:///system
I1006 22:33:51.544007   48191 docker.go:98] docker version: linux-19.03.13
I1006 22:33:51.544049   48191 docker.go:130] overlay module found
I1006 22:33:51.547034   48191 out.go:109] * Using the docker driver based on existing profile
I1006 22:33:51.547070   48191 start.go:246] selected driver: docker
I1006 22:33:51.547076   48191 start.go:653] validating driver "docker" against &{Name:cloud-run-dev-internal KeepContext:true EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:cloud-run-dev-internal APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I1006 22:33:51.547207   48191 start.go:664] status for docker: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Fix: Doc:}
I1006 22:33:51.547371   48191 cli_runner.go:110] Run: docker system info --format "{{json .}}"
I1006 22:33:51.686400   48191 cli_runner.go:110] Run: docker system info --format "{{json .}}"
I1006 22:33:51.809851   48191 start_flags.go:348] config:
{Name:cloud-run-dev-internal KeepContext:true EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b Memory:4000 CPUs:2 DiskSize:20000 VMDriver: Driver:docker HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.19.2 ClusterName:cloud-run-dev-internal APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.19.2 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s}
I1006 22:33:51.813665   48191 out.go:109] * Starting control plane node cloud-run-dev-internal in cluster cloud-run-dev-internal
I1006 22:33:51.863153   48191 cache.go:119] Beginning downloading kic base image for docker with docker
I1006 22:33:51.865845   48191 out.go:109] * Pulling base image ...
I1006 22:33:51.865903   48191 preload.go:97] Checking if preload exists for k8s version v1.19.2 and runtime docker
I1006 22:33:51.865955   48191 preload.go:105] Found local preload: /google/minikube/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v6-v1.19.2-docker-overlay2-amd64.tar.lz4
I1006 22:33:51.865961   48191 cache.go:53] Caching tarball of preloaded images
I1006 22:33:51.865973   48191 preload.go:131] Found /google/minikube/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v6-v1.19.2-docker-overlay2-amd64.tar.lz4 in cache, skipping download
I1006 22:33:51.865978   48191 cache.go:56] Finished verifying existence of preloaded tar for  v1.19.2 on docker
I1006 22:33:51.866113   48191 profile.go:150] Saving config to /google/minikube/.minikube/profiles/cloud-run-dev-internal/config.json ...
I1006 22:33:53.845952   48191 cache.go:136] successfully loaded gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3@sha256:1d687ba53e19dbe5fafe4cc18aa07f269ecc4b7b622f2251b5bf569ddb474e9b from cached tarball
W1006 22:33:53.846066   48191 out.go:145] ! minikube was unable to download gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3, but successfully downloaded gcr.io/k8s-minikube/kicbase:v0.0.12-snapshot3 as a fallback image
I1006 22:33:53.846469   48191 cache.go:182] Successfully downloaded all kic artifacts
I1006 22:33:53.846504   48191 start.go:314] acquiring machines lock for cloud-run-dev-internal: {Name:mk9f49636438ab4fea0a71a65c92781d0a6f8c2b Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
I1006 22:33:53.849461   48191 start.go:318] acquired machines lock for "cloud-run-dev-internal" in 2.921755ms
I1006 22:33:53.849498   48191 start.go:94] Skipping create...Using existing machine configuration
I1006 22:33:53.849512   48191 fix.go:54] fixHost starting: 
I1006 22:33:53.850175   48191 cli_runner.go:110] Run: docker container inspect cloud-run-dev-internal --format={{.State.Status}}
I1006 22:33:53.909154   48191 fix.go:107] recreateIfNeeded on cloud-run-dev-internal: state=Running err=<nil>
W1006 22:33:53.909171   48191 fix.go:133] unexpected machine state, will restart: <nil>
I1006 22:33:53.913932   48191 out.go:109] * Updating the running docker "cloud-run-dev-internal" container ...
I1006 22:33:53.913979   48191 machine.go:88] provisioning docker machine ...
I1006 22:33:53.914001   48191 ubuntu.go:166] provisioning hostname "cloud-run-dev-internal"
I1006 22:33:53.914142   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:53.977824   48191 main.go:115] libmachine: Using SSH client type: native
I1006 22:33:53.978046   48191 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x7b9850] 0x7b9820 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I1006 22:33:53.978064   48191 main.go:115] libmachine: About to run SSH command:
sudo hostname cloud-run-dev-internal && echo "cloud-run-dev-internal" | sudo tee /etc/hostname
I1006 22:33:54.131669   48191 main.go:115] libmachine: SSH cmd err, output: <nil>: cloud-run-dev-internal

I1006 22:33:54.131833   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:54.189692   48191 main.go:115] libmachine: Using SSH client type: native
I1006 22:33:54.189935   48191 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x7b9850] 0x7b9820 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I1006 22:33:54.189963   48191 main.go:115] libmachine: About to run SSH command:

		if ! grep -xq '.*\scloud-run-dev-internal' /etc/hosts; then
			if grep -xq '127.0.1.1\s.*' /etc/hosts; then
				sudo sed -i 's/^127.0.1.1\s.*/127.0.1.1 cloud-run-dev-internal/g' /etc/hosts;
			else 
				echo '127.0.1.1 cloud-run-dev-internal' | sudo tee -a /etc/hosts; 
			fi
		fi
I1006 22:33:54.327094   48191 main.go:115] libmachine: SSH cmd err, output: <nil>: 
I1006 22:33:54.327123   48191 ubuntu.go:172] set auth options {CertDir:/google/minikube/.minikube CaCertPath:/google/minikube/.minikube/certs/ca.pem CaPrivateKeyPath:/google/minikube/.minikube/certs/ca-key.pem CaCertRemotePath:/etc/docker/ca.pem ServerCertPath:/google/minikube/.minikube/machines/server.pem ServerKeyPath:/google/minikube/.minikube/machines/server-key.pem ClientKeyPath:/google/minikube/.minikube/certs/key.pem ServerCertRemotePath:/etc/docker/server.pem ServerKeyRemotePath:/etc/docker/server-key.pem ClientCertPath:/google/minikube/.minikube/certs/cert.pem ServerCertSANs:[] StorePath:/google/minikube/.minikube}
I1006 22:33:54.327161   48191 ubuntu.go:174] setting up certificates
I1006 22:33:54.327177   48191 provision.go:82] configureAuth start
I1006 22:33:54.327349   48191 cli_runner.go:110] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" cloud-run-dev-internal
I1006 22:33:54.381007   48191 provision.go:131] copyHostCerts
I1006 22:33:54.381137   48191 exec_runner.go:98] cp: /google/minikube/.minikube/certs/cert.pem --> /google/minikube/.minikube/cert.pem (1078 bytes)
I1006 22:33:54.381281   48191 exec_runner.go:98] cp: /google/minikube/.minikube/certs/key.pem --> /google/minikube/.minikube/key.pem (1675 bytes)
I1006 22:33:54.381390   48191 exec_runner.go:98] cp: /google/minikube/.minikube/certs/ca.pem --> /google/minikube/.minikube/ca.pem (1038 bytes)
I1006 22:33:54.381447   48191 provision.go:105] generating server cert: /google/minikube/.minikube/machines/server.pem ca-key=/google/minikube/.minikube/certs/ca.pem private-key=/google/minikube/.minikube/certs/ca-key.pem org=unknown.cloud-run-dev-internal san=[172.18.0.3 localhost 127.0.0.1 minikube cloud-run-dev-internal]
I1006 22:33:54.589557   48191 provision.go:159] copyRemoteCerts
I1006 22:33:54.589656   48191 ssh_runner.go:148] Run: sudo mkdir -p /etc/docker /etc/docker /etc/docker
I1006 22:33:54.589730   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:54.639976   48191 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/google/minikube/.minikube/machines/cloud-run-dev-internal/id_rsa Username:docker}
I1006 22:33:54.733410   48191 ssh_runner.go:215] scp /google/minikube/.minikube/certs/ca.pem --> /etc/docker/ca.pem (1038 bytes)
I1006 22:33:54.756451   48191 ssh_runner.go:215] scp /google/minikube/.minikube/machines/server.pem --> /etc/docker/server.pem (1184 bytes)
I1006 22:33:54.778593   48191 ssh_runner.go:215] scp /google/minikube/.minikube/machines/server-key.pem --> /etc/docker/server-key.pem (1679 bytes)
I1006 22:33:54.799697   48191 provision.go:85] duration metric: configureAuth took 472.505826ms
I1006 22:33:54.799716   48191 ubuntu.go:190] setting minikube options for container-runtime
I1006 22:33:54.800001   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:54.850491   48191 main.go:115] libmachine: Using SSH client type: native
I1006 22:33:54.850684   48191 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x7b9850] 0x7b9820 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I1006 22:33:54.850693   48191 main.go:115] libmachine: About to run SSH command:
df --output=fstype / | tail -n 1
I1006 22:33:54.983712   48191 main.go:115] libmachine: SSH cmd err, output: <nil>: overlay

I1006 22:33:54.983731   48191 ubuntu.go:71] root file system type: overlay
I1006 22:33:54.983913   48191 provision.go:290] Updating docker unit: /lib/systemd/system/docker.service ...
I1006 22:33:54.984053   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:55.035331   48191 main.go:115] libmachine: Using SSH client type: native
I1006 22:33:55.035508   48191 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x7b9850] 0x7b9820 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I1006 22:33:55.035600   48191 main.go:115] libmachine: About to run SSH command:
sudo mkdir -p /lib/systemd/system && printf %s "[Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify



# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.

# NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
# container runtimes. If left unlimited, it may result in OOM issues with MySQL.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 
ExecReload=/bin/kill -s HUP $MAINPID

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target
" | sudo tee /lib/systemd/system/docker.service.new
I1006 22:33:55.179148   48191 main.go:115] libmachine: SSH cmd err, output: <nil>: [Unit]
Description=Docker Application Container Engine
Documentation=https://docs.docker.com
BindsTo=containerd.service
After=network-online.target firewalld.service containerd.service
Wants=network-online.target
Requires=docker.socket

[Service]
Type=notify



# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
# The base configuration already specifies an 'ExecStart=...' command. The first directive
# here is to clear out that command inherited from the base configuration. Without this,
# the command from the base configuration and the command specified here are treated as
# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
# will catch this invalid input and refuse to start the service with an error like:
#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.

# NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
# container runtimes. If left unlimited, it may result in OOM issues with MySQL.
ExecStart=
ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 
ExecReload=/bin/kill -s HUP 

# Having non-zero Limit*s causes performance problems due to accounting overhead
# in the kernel. We recommend using cgroups to do container-local accounting.
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity

# Uncomment TasksMax if your systemd version supports it.
# Only systemd 226 and above support this version.
TasksMax=infinity
TimeoutStartSec=0

# set delegate yes so that systemd does not reset the cgroups of docker containers
Delegate=yes

# kill only the docker process, not all processes in the cgroup
KillMode=process

[Install]
WantedBy=multi-user.target

I1006 22:33:55.179289   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:55.231854   48191 main.go:115] libmachine: Using SSH client type: native
I1006 22:33:55.232035   48191 main.go:115] libmachine: &{{{<nil> 0 [] [] []} docker [0x7b9850] 0x7b9820 <nil>  [] 0s} 127.0.0.1 32771 <nil> <nil>}
I1006 22:33:55.232058   48191 main.go:115] libmachine: About to run SSH command:
sudo diff -u /lib/systemd/system/docker.service /lib/systemd/system/docker.service.new || { sudo mv /lib/systemd/system/docker.service.new /lib/systemd/system/docker.service; sudo systemctl -f daemon-reload && sudo systemctl -f enable docker && sudo systemctl -f restart docker; }
I1006 22:33:55.848139   48191 main.go:115] libmachine: SSH cmd err, output: <nil>: --- /lib/systemd/system/docker.service	2020-03-10 19:42:48.000000000 +0000
+++ /lib/systemd/system/docker.service.new	2020-10-06 22:33:55.176606639 +0000
@@ -8,24 +8,22 @@
 
 [Service]
 Type=notify
-# the default is not to use systemd for cgroups because the delegate issues still
-# exists and systemd currently does not support the cgroup feature set required
-# for containers run by docker
-ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
-ExecReload=/bin/kill -s HUP $MAINPID
-TimeoutSec=0
-RestartSec=2
-Restart=always
-
-# Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
-# Both the old, and new location are accepted by systemd 229 and up, so using the old location
-# to make them work for either version of systemd.
-StartLimitBurst=3
-
-# Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
-# Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
-# this option work for either version of systemd.
-StartLimitInterval=60s
+
+
+
+# This file is a systemd drop-in unit that inherits from the base dockerd configuration.
+# The base configuration already specifies an 'ExecStart=...' command. The first directive
+# here is to clear out that command inherited from the base configuration. Without this,
+# the command from the base configuration and the command specified here are treated as
+# a sequence of commands, which is not the desired behavior, nor is it valid -- systemd
+# will catch this invalid input and refuse to start the service with an error like:
+#  Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services.
+
+# NOTE: default-ulimit=nofile is set to an arbitrary number for consistency with other
+# container runtimes. If left unlimited, it may result in OOM issues with MySQL.
+ExecStart=
+ExecStart=/usr/bin/dockerd -H tcp://0.0.0.0:2376 -H unix:///var/run/docker.sock --default-ulimit=nofile=1048576:1048576 --tlsverify --tlscacert /etc/docker/ca.pem --tlscert /etc/docker/server.pem --tlskey /etc/docker/server-key.pem --label provider=docker --insecure-registry 10.96.0.0/12 
+ExecReload=/bin/kill -s HUP 
 
 # Having non-zero Limit*s causes performance problems due to accounting overhead
 # in the kernel. We recommend using cgroups to do container-local accounting.
@@ -33,9 +31,10 @@
 LimitNPROC=infinity
 LimitCORE=infinity
 
-# Comment TasksMax if your systemd version does not support it.
-# Only systemd 226 and above support this option.
+# Uncomment TasksMax if your systemd version supports it.
+# Only systemd 226 and above support this version.
 TasksMax=infinity
+TimeoutStartSec=0
 
 # set delegate yes so that systemd does not reset the cgroups of docker containers
 Delegate=yes

I1006 22:33:55.848162   48191 machine.go:91] provisioned docker machine in 1.934176563s
I1006 22:33:55.848172   48191 start.go:268] post-start starting for "cloud-run-dev-internal" (driver="docker")
I1006 22:33:55.848177   48191 start.go:278] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I1006 22:33:55.848290   48191 ssh_runner.go:148] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I1006 22:33:55.848385   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:55.896610   48191 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/google/minikube/.minikube/machines/cloud-run-dev-internal/id_rsa Username:docker}
I1006 22:33:55.990673   48191 ssh_runner.go:148] Run: cat /etc/os-release
I1006 22:33:55.994347   48191 main.go:115] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I1006 22:33:55.994370   48191 main.go:115] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I1006 22:33:55.994384   48191 main.go:115] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I1006 22:33:55.994390   48191 info.go:100] Remote host: Ubuntu 20.04 LTS
I1006 22:33:55.994399   48191 filesync.go:118] Scanning /google/minikube/.minikube/addons for local assets ...
I1006 22:33:55.997183   48191 filesync.go:118] Scanning /google/minikube/.minikube/files for local assets ...
I1006 22:33:55.998214   48191 start.go:271] post-start completed in 150.031386ms
I1006 22:33:55.998347   48191 ssh_runner.go:148] Run: sh -c "df -h /var | awk 'NR==2{print $5}'"
I1006 22:33:55.998421   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:56.046647   48191 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/google/minikube/.minikube/machines/cloud-run-dev-internal/id_rsa Username:docker}
I1006 22:33:56.136729   48191 fix.go:56] fixHost completed within 2.287210828s
I1006 22:33:56.136746   48191 start.go:81] releasing machines lock for "cloud-run-dev-internal", held for 2.287268591s
I1006 22:33:56.136887   48191 cli_runner.go:110] Run: docker container inspect -f "{{range .NetworkSettings.Networks}}{{.IPAddress}},{{.GlobalIPv6Address}}{{end}}" cloud-run-dev-internal
I1006 22:33:56.186212   48191 ssh_runner.go:148] Run: systemctl --version
I1006 22:33:56.186250   48191 ssh_runner.go:148] Run: curl -sS -m 2 https://k8s.gcr.io/
I1006 22:33:56.186421   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:56.186430   48191 cli_runner.go:110] Run: docker container inspect -f "'{{(index (index .NetworkSettings.Ports "22/tcp") 0).HostPort}}'" cloud-run-dev-internal
I1006 22:33:56.240569   48191 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/google/minikube/.minikube/machines/cloud-run-dev-internal/id_rsa Username:docker}
I1006 22:33:56.242887   48191 sshutil.go:44] new ssh client: &{IP:127.0.0.1 Port:32771 SSHKeyPath:/google/minikube/.minikube/machines/cloud-run-dev-internal/id_rsa Username:docker}
I1006 22:33:56.332661   48191 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service containerd
I1006 22:33:56.368174   48191 ssh_runner.go:148] Run: sudo systemctl cat docker.service
I1006 22:33:56.382631   48191 cruntime.go:193] skipping containerd shutdown because we are bound to it
I1006 22:33:56.382822   48191 ssh_runner.go:148] Run: sudo systemctl is-active --quiet service crio
I1006 22:33:56.398446   48191 docker.go:288] Forcing docker to use systemd as cgroup manager...
I1006 22:33:56.398461   48191 ssh_runner.go:215] scp memory --> /etc/docker/daemon.json (143 bytes)
I1006 22:33:56.418436   48191 ssh_runner.go:148] Run: sudo systemctl daemon-reload
I1006 22:33:56.553260   48191 ssh_runner.go:148] Run: sudo systemctl restart docker
I1006 22:33:56.892978   48191 ssh_runner.go:148] Run: docker version --format {{.Server.Version}}
I1006 22:33:56.962074   48191 out.go:109] * Preparing Kubernetes v1.19.2 on Docker 19.03.8 ...
I1006 22:33:56.962252   48191 cli_runner.go:110] Run: docker network ls --filter name=bridge --format {{.ID}}
I1006 22:33:57.011205   48191 cli_runner.go:110] Run: docker network inspect 7096f62f7bf8 -f "{{range $k, $v := .Containers}}{{$v.Name}} {{end}}"
I1006 22:33:57.060171   48191 cli_runner.go:110] Run: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 7096f62f7bf8
I1006 22:33:57.108652   48191 network.go:106] got host ip for mount in container by inspect docker network: <nil>
I1006 22:33:57.108818   48191 ssh_runner.go:148] Run: grep <nil>	host.minikube.internal$ /etc/hosts
I1006 22:33:57.112675   48191 ssh_runner.go:148] Run: /bin/bash -c "{ grep -v '\thost.minikube.internal$' /etc/hosts; echo "<nil>	host.minikube.internal"; } > /tmp/h.$$; sudo cp /tmp/h.$$ /etc/hosts"
I1006 22:33:57.126712   48191 out.go:109] 
W1006 22:33:57.126850   48191 out.go:145] X Exiting due to DRV_CP_ENDPOINT: failed to parse ip for ""
W1006 22:33:57.126897   48191 out.go:145] * 
W1006 22:33:57.126931   48191 out.go:145] * If the above advice does not help, please let us know: 
W1006 22:33:57.126977   48191 out.go:145]   - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by medyagh** [comment] 2020-10-08 17:55
there is a possibility that the disk space which is at warnning level, becomes 100% full and take down docker.

**Comment by tstromberg** [comment] 2020-10-08 18:43
@medyagh - perhaps, but the relationship between disk space and networking isn't obvious to me. The log I just posted had no disk space warnings (it'd be nice if we logged the amount if it was under 90%) .

**Comment by priyawadhwa** [comment] 2020-10-08 19:17
@tstromberg I know that we output a warning if it's >80%, so we can assume that it was at least <80%

**Comment by medyagh** [comment] 2020-10-08 20:08
just for logsI just tried creating 20 clusters on a vm with 20 GB disk, interestingly all minikube commands fail to respond (inlucding delete --all) when the disk is 100% full

```

ubuntu@ip-172-31-11-133:~$ minikube profile list
I1008 20:06:16.839087  809857 translate.go:106] Setting Language to en-US ...
log: exiting because of error: write /tmp/minikube.ip-172-31-11-133.ubuntu.log.INFO.20201008-200616.809857: no space left on device
ubuntu@ip-172-31-11-133:~$ minikube version
I1008 20:06:22.906897  809941 translate.go:106] Setting Language to en-US ...
log: exiting because of error: write /tmp/minikube.ip-172-31-11-133.ubuntu.log.INFO.20201008-200622.809941: no space left on device
ubuntu@ip-172-31-11-133:~$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        20G   20G     0 100% /
devtmpfs        3.9G     0  3.9G   0% /dev
tmpfs           3.9G  168K  3.9G   1% /dev/shm
tmpfs           796M   30M  767M   4% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop0       97M   97M     0 100% /snap/core/9804
/dev/loop1       56M   56M     0 100% /snap/core18/1885
/dev/loop2       71M   71M     0 100% /snap/lxd/16922
/dev/loop3       29M   29M     0 100% /snap/amazon-ssm-agent/2012
/dev/loop4       98M   98M     0 100% /snap/core/9993
tmpfs           796M  4.0K  796M   1% /run/user/1000
ubuntu@ip-172-31-11-133:~$ minikube delete --all
I1008 20:06:51.273388  810336 translate.go:106] Setting Language to en-US ...
log: exiting because of error: write /tmp/minikube.ip-172-31-11-133.ubuntu.log.INFO.20201008-200651.810336: no space left on device
ubuntu@ip-172-31-11-133:~$ 

```

I agree this bug does NOT seem to be related to disk space.

**Comment by tstromberg** [comment] 2020-10-09 19:33
The root cause is unknown, but this error is brought on because the following line emitted no output, though still an exit code of 0:

`docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 7096f62f7bf8`

**Closed** 2021-01-20 19:52 UTC
Labels: kind/support, priority/important-longterm
