### ISSUE TITLE
package architecture (arm64) does not match system (amd64) even while using amd64 debian

### ISSUE THREAD

**Issue by pnutmath** [kubernetes/minikube#10001] opened 2020-12-18 10:39 UTC
**Steps to reproduce the issue:** 

1. Fire bellow commands
```
curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb
```

**Full output of failed command:** 
package architecture (arm64) does not match system (amd64)

**Full output of `minikube start` command used, if not already included:**

```
➜  ~ curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
sudo dpkg -i minikube_latest_amd64.deb

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 19.6M  100 19.6M    0     0  1780k      0  0:00:11  0:00:11 --:--:-- 1886k
dpkg: error processing archive minikube_latest_amd64.deb (--install):
 package architecture (arm64) does not match system (amd64)
Errors were encountered while processing:
 minikube_latest_amd64.deb
```

**Comment by marcaureln** [comment] 2020-12-18 11:02
Duplicate of #9995

**Comment by afbjorklund** [comment] 2020-12-18 11:49
Sorry about that, you can use the workaround meanwhile:

sudo dpkg -i --force-architecture minikube_1.16.0-0_amd64.deb

**Closed** 2020-12-18 15:31 UTC
Labels: packaging/apt, triage/duplicate
