### ISSUE TITLE
kvm2: qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory

### ISSUE THREAD

**Issue by mfaridi1394** [kubernetes/minikube#3634] opened 2019-02-06 04:25 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

Please provide the following details:

**Environment**:
ubunut on vmware 
**Minikube version** (use `minikube version`):
minikube version: v0.33.1

- **OS** (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"

- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
"DriverName": "kvm2",
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh 
cat /etc/VERSION`):
"Boot2DockerURL": "file:///home/mostafa/.minikube/cache/iso/minikube-v0.33.1.iso",
        "ISO": "/home/mostafa/.minikube/machines/minikube/boot2docker.iso",
- **Install tools**:
- **Others**:
The above can be generated in one go with the following commands (can be copied and pasted directly into your terminal):
```

```

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:

I use linux mint and install vmware and run ubuntu 18.0.4 and update it and install everything is need for run minikube
I want run start minikube by KVM.
In ubunut server is swap off and run it without Swap.
when I want run minikube by kvm I see this error
`mostafa@minikube:~$ sudo minikube start --vm-driver kvm2
Starting local Kubernetes v1.13.2 cluster...
Starting VM...
E0206 03:59:52.856502    1930 start.go:205] Error starting host: Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-02-06T03:59:52.382469Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory').

 Retrying.
E0206 03:59:52.863823    1930 start.go:211] Error starting host:  Error starting stopped host: Error creating VM: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2019-02-06T03:59:52.382469Z qemu-system-x86_64: cannot set up guest memory 'pc.ram': Cannot allocate memory')
`

**Comment by tstromberg** [comment] 2019-02-12 23:44
Hey @mfaridi1394 - Do you mind sharing the output of `virt-host-validate` and `free`?

It sounds like kvm2 can't allocate memory on your host, but I'm not sure why. It needs about 2GB of free RAM to setup a VM, but I'm not convinced that it's running low on memory here.

**Comment by mfaridi1394** [comment] 2019-02-13 05:00
Thanks tstromberg, how I set kvm2 use 1GB of RAM ?
.

**Comment by jahentao** [comment] 2019-05-03 12:36
> Thanks @tstromberg, how I set kvm2 use 1GB of RAM ?
> I have RAM limitation
> .

I have the same question. After searching, I think this [issue](https://github.com/kubernetes/minikube/issues/3173) may be helpful for you.

**Comment by shaheem007** [comment] 2019-05-19 16:54
limbo_compat_filesystem.c: Could not fopen: /data/user/0/com.limbo.emu.main/cache/limbo//usr/local/etc/qemu/qemu.conf, r, 0x0
05-19 18:50:48.544 30713 30995 E limbo_logutils.h: libqemu-system-x86_64.so:
05-19 18:50:48.544 30713 30995 E limbo_logutils.h:  
05-19 18:50:48.544 30713 30995 E limbo_logutils.h: cannot set up guest memory 'pc.ram': Out of memory
05-19 18:50:48.544 30713 30995 E limbo_logutils.h 


im useing limbo 86 
arm7l
android 9

**Comment by tstromberg** [comment] 2019-05-22 23:48
If you run into this issue, you have run out of system memory. You can try setting  `--memory` for a lower number, but I suspect you can't get much lower than 1.9GB and still have a usable cluster.

**Comment by tstromberg** [comment] 2019-05-22 23:48
Duplicate of #3173

**Closed by tstromberg** 2019-05-22 23:48 UTC
Labels: cause/vm-driver, co/kvm2, kind/bug, priority/awaiting-more-evidence, triage/needs-information

**Comment by zenaan** [comment] 2019-09-13 10:45
Similar error text is solved here: https://forum.siduction.org/index.php?topic=7474.0 with the following command:

    echo 3 |  tee /proc/sys/vm/drop_caches

**Comment by vedvarshith** [comment] 2020-10-17 06:12
![android+linux](https://user-images.githubusercontent.com/70155237/96329803-d4a51380-106d-11eb-9453-10aeeae76fff.jpeg)

**Comment by vedvarshith** [comment] 2020-10-17 06:19
please help me i have the same prob.
