### ISSUE TITLE
minikube start for kubernetes to use with Eclipse CHE

### ISSUE THREAD

**Issue by venkateshkolisetty** [kubernetes/minikube#6189] opened 2020-01-01 17:31 UTC
**The exact command to reproduce the issue**:
sudo minikube start --vm-driver=none

**The full output of the command that failed**:<details>
* minikube v1.6.2 on Centos 7.7.1908
* Selecting 'none' driver from user configuration (alternates: [kvm2])
* Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
* Starting existing none VM for "minikube" ...
* Waiting for the host to be provisioned ...
* Preparing Kubernetes v1.17.0 on Docker '19.03.5' ...
* Launching Kubernetes ...
*
X Error starting cluster: init failed. cmd: "/bin/bash -c \"sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap\"": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.0:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.0
[preflight] Running pre-flight checks

stderr:
W0101 22:54:16.278275   22046 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0101 22:54:16.280772   22046 common.go:77] your configuration file uses a deprecated API spec: "kubeadm.k8s.io/v1beta1". Please use 'kubeadm config migrate --old-config old.yaml --new-config new.yaml', which will write the new, similar spec using a newer API version.
W0101 22:54:16.287023   22046 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0101 22:54:16.287141   22046 validation.go:28] Cannot validate kubelet config - no validator is available
        [WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
        [WARNING Swap]: running with swap on is not supported. Please disable swap
        [WARNING FileExisting-socat]: socat not found in system path
        [WARNING Hostname]: hostname "minikube" could not be reached
        [WARNING Hostname]: hostname "minikube": lookup minikube on 125.22.47.125:53: no such host
        [WARNING Service-Kubelet]: kubelet service is not enabled, please run 'systemctl enable kubelet.service'
error execution phase preflight: [preflight] Some fatal errors occurred:
        [ERROR FileContent--proc-sys-net-bridge-bridge-nf-call-iptables]: /proc/sys/net/bridge/bridge-nf-call-iptables contents are not set to 1
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

*
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

* ==> Docker <==
* -- Logs begin at Wed 2020-01-01 21:57:23 IST, end at Wed 2020-01-01 22:57:01 IST. --
* Jan 01 21:57:47 VENKATESH-NUC systemd[1]: Starting Docker Application Container Engine...
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.131046258+05:30" level=info msg="Starting up"
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.175572881+05:30" level=info msg="parsed scheme: \"unix\"" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.176442761+05:30" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.177161063+05:30" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.177876552+05:30" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.194320754+05:30" level=info msg="parsed scheme: \"unix\"" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.195583380+05:30" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.197147948+05:30" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.198604415+05:30" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.396462190+05:30" level=info msg="[graphdriver] using prior storage driver: overlay2"
* Jan 01 21:57:49 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:49.827032259+05:30" level=info msg="Loading containers: start."
* Jan 01 21:57:53 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:53.816310684+05:30" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
* Jan 01 21:57:55 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:55.464813808+05:30" level=info msg="Loading containers: done."
* Jan 01 21:57:55 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:55.845296009+05:30" level=info msg="Docker daemon" commit=633a0ea graphdriver(s)=overlay2 version=19.03.5
* Jan 01 21:57:55 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:55.851729539+05:30" level=info msg="Daemon has completed initialization"
* Jan 01 21:57:56 VENKATESH-NUC systemd[1]: Started Docker Application Container Engine.
* Jan 01 21:57:56 VENKATESH-NUC dockerd[1575]: time="2020-01-01T21:57:56.026170363+05:30" level=info msg="API listen on /var/run/docker.sock"
*
* ==> container status <==
* sudo: crictl: command not found
* CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS               NAMES
* 952c13979e13        hello-world                                 "/hello"                 5 months ago        Exited (0) 5 months ago                         dreamy_albattani
* cd4b42ec5d8c        store/oracle/database-enterprise:12.2.0.1   "/bin/sh -c '/bin/ba…"   5 months ago        Exited (137) 5 months ago                       mevenk_oracle-db
* b3d37fd25189        mysql                                       "docker-entrypoint.s…"   5 months ago        Exited (0) 5 months ago                         mevenk_mysql
* 47deca49c476        mysql                                       "docker-entrypoint.s…"   5 months ago        Exited (0) 5 months ago                         mevenk_mysql_140720191558
* f32994305442        mysql                                       "docker-entrypoint.s…"   5 months ago        Exited (1) 5 months ago                         wizardly_mendel
* bbb18137189b        eclipse/che-server                          "/entrypoint.sh"         5 months ago        Exited (130) 5 months ago                       build_che-10072019-0820_run_785fe566d5b7
* f20a77fb8952        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (130) 5 months ago                       build_che-10072019-0820_run_be396b448f19
* 57317de12270        eclipse/che-server:5.1.2                    "/entrypoint.sh start"   5 months ago        Exited (130) 5 months ago                       dazzling_volhard
* 30a93304a877        eclipse/che-server:5.1.2                    "/entrypoint.sh start"   5 months ago        Exited (130) 5 months ago                       cranky_swirles
* 0f6c3dfe365d        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (130) 5 months ago                       build_che-10072019-0820_run_4820d32a53d6
* 2e88206ceba3        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (130) 5 months ago                       build_che-10072019-0820_run_52baa6ab9004
* f54a036b7f94        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (0) 5 months ago                         build_che-10072019-0820_run_8aec0b0c428f
* 6185eca31925        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (0) 5 months ago                         build_che-10072019-0820_run_ecd9b8b06b0e
* a9f016cbbef0        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (0) 5 months ago                         build_che-10072019-0820_run_3765b8d3a835
* 7eadf8a7f6fd        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (0) 5 months ago                         build_che-10072019-0820_run_f28acfd29f3c
* 54a2e2e0217c        eclipse/che-server:5.1.2                    "/entrypoint.sh"         5 months ago        Exited (137) 5 months ago                       build_che-10072019_run_f344896d4bc6
* d6879c37404a        tomcat                                      "catalina.sh run"        5 months ago        Exited (143) 5 months ago                       amazing_mclaren
* ecaa5118d7da        hello-world                                 "/hello"                 5 months ago        Exited (0) 5 months ago                         festive_williamson
* 5907bef4b27c        hello-world                                 "/hello"                 5 months ago        Exited (0) 5 months ago                         boring_diffie
*
* ==> dmesg <==
* dmesg: invalid option -- '='
*
* Usage:
*  dmesg [options]
*
* Options:
*  -C, --clear                 clear the kernel ring buffer
*  -c, --read-clear            read and clear all messages
*  -D, --console-off           disable printing messages to console
*  -d, --show-delta            show time delta between printed messages
*  -e, --reltime               show local time and time delta in readable format
*  -E, --console-on            enable printing messages to console
*  -F, --file <file>           use the file instead of the kernel log buffer
*  -f, --facility <list>       restrict output to defined facilities
*  -H, --human                 human readable output
*  -k, --kernel                display kernel messages
*  -L, --color                 colorize messages
*  -l, --level <list>          restrict output to defined levels
*  -n, --console-level <level> set level of messages printed to console
*  -P, --nopager               do not pipe output into a pager
*  -r, --raw                   print the raw message buffer
*  -S, --syslog                force to use syslog(2) rather than /dev/kmsg
*  -s, --buffer-size <size>    buffer size to query the kernel ring buffer
*  -T, --ctime                 show human readable timestamp (could be
*                                inaccurate if you have used SUSPEND/RESUME)
*  -t, --notime                don't print messages timestamp
*  -u, --userspace             display userspace messages
*  -w, --follow                wait for new messages
*  -x, --decode                decode facility and level to readable string
*
*  -h, --help     display this help and exit
*  -V, --version  output version information and exit
*
* Supported log facilities:
*     kern - kernel messages
*     user - random user-level messages
*     mail - mail system
*   daemon - system daemons
*     auth - security/authorization messages
*   syslog - messages generated internally by syslogd
*      lpr - line printer subsystem
*     news - network news subsystem
*
* Supported log levels (priorities):
*    emerg - system is unusable
*    alert - action must be taken immediately
*     crit - critical conditions
*      err - error conditions
*     warn - warning conditions
*   notice - normal but significant condition
*     info - informational
*    debug - debug-level messages
*
*
* For more details see dmesg(q).
*
* ==> kernel <==
*  22:57:02 up 59 min,  3 users,  load average: 1.13, 1.30, 1.38
* Linux VENKATESH-NUC 3.10.0-1062.9.1.el7.x86_64 #1 SMP Fri Dec 6 15:49:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
* PRETTY_NAME="CentOS Linux 7 (Core)"
*
* ==> kubelet <==
* -- Logs begin at Wed 2020-01-01 21:57:23 IST, end at Wed 2020-01-01 22:57:02 IST. --
* Jan 01 22:56:57 VENKATESH-NUC systemd[1]: kubelet.service failed.
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:58 VENKATESH-NUC kubelet[23723]: F0101 22:56:58.591705   23723 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: Unit kubelet.service entered failed state.
* Jan 01 22:56:58 VENKATESH-NUC systemd[1]: kubelet.service failed.
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:56:59 VENKATESH-NUC kubelet[23732]: F0101 22:56:59.733479   23732 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: Unit kubelet.service entered failed state.
* Jan 01 22:56:59 VENKATESH-NUC systemd[1]: kubelet.service failed.
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:00 VENKATESH-NUC kubelet[23750]: F0101 22:57:00.609193   23750 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: Unit kubelet.service entered failed state.
* Jan 01 22:57:00 VENKATESH-NUC systemd[1]: kubelet.service failed.
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: Started kubelet: The Kubernetes Node Agent.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
* Jan 01 22:57:01 VENKATESH-NUC kubelet[23815]: F0101 22:57:01.606635   23815 server.go:198] failed to load Kubelet config file /var/lib/kubelet/config.yaml, error failed to read kubelet config file "/var/lib/kubelet/config.yaml", error: open /var/lib/kubelet/config.yaml: no such file or directory
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: kubelet.service: main process exited, code=exited, status=255/n/a
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: Unit kubelet.service entered failed state.
* Jan 01 22:57:01 VENKATESH-NUC systemd[1]: kubelet.service failed.
* Jan 01 22:57:02 VENKATESH-NUC systemd[1]: kubelet.service holdoff time over, scheduling restart.
* Jan 01 22:57:02 VENKATESH-NUC systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
* Jan 01 22:57:02 VENKATESH-NUC systemd[1]: Started kubelet: The Kubernetes Node Agent.

</details>

**The operating system version**:
         Icon name: computer-desktop
           Chassis: desktop
  Operating System: CentOS Linux 7 (Core)
       CPE OS Name: cpe:/o:centos:centos:7
            Kernel: Linux 3.10.0-1062.9.1.el7.x86_64
      Architecture: x86-64

**Comment by afbjorklund** [comment] 2020-01-02 09:10
Sounds similar to #6166 ?

**Comment by venkateshkolisetty** [comment] 2020-01-02 15:37
> Sounds similar to #6166 ?

yes

**Comment by tstromberg** [comment] 2020-01-22 19:59
This issue appears to be a duplicate of #6166, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-01-22 19:59 UTC
Labels: co/none-driver, kind/documentation, priority/important-longterm
