### ISSUE TITLE
cache with quay.io issues: Docker-Content-Digest and 405 Method Not Allowed

### ISSUE THREAD

**Issue by cvila84** [kubernetes/minikube#4016] opened 2019-03-28 13:38 UTC
Hello,

With minikube 1.0.0 on windows, I am not able to cache images from quay.io docker repository.

```
$ minikube cache add quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0
2019/03/28 14:30:05 No matching credentials were found, falling back on anonymous

!   Failed to cache and load images: caching images: caching image C:\Programs\Cygwin\home\cvila\.minikube\cache\images\quay.io\kubernetes-ingress-controller\nginx-ingress-controller_0.23.0: manifest digest: "sha256:603b7018c941b1117da4eb980c8043992ad37abdde3636fcbae1f34bcfff443f" does not match Docker-Content-Digest: "sha256:e1292564ba5f1fd75005a4575778523d3309fb5d5d57f6597234c0b1567641f6" for "quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0"

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

From what I understood, it comes from https://github.com/google/go-containerregistry/issues/119, which has been recently fixed (beg March) by https://github.com/google/go-containerregistry/pull/387. Maybe we just need to make sure we compile minikube with the latest release of go-containerregistry ?

Side question, is there a way to avoid the `No matching credentials were found, falling back on anonymous`, when we put in cache a public image (which does not require any credentials to be passed)

Thanks !

**Comment by afbjorklund** [comment] 2019-03-28 18:02
This would be been fixed with PR #3899, which updates google/go-containerregistry (for another reason)

**Comment by afbjorklund** [comment] 2019-03-28 18:10
Hmm, or maybe not. Are you sure that update fixes this issue ?
```
💣  Failed to cache and load images: caching images: caching image /home/anders/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0: unsupported status code 405; body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

It works OK with `docker pull`, so I guess the issue is somewhere in google/go-containerregistry ...

**Comment by afbjorklund** [comment] 2019-03-28 18:20
Upgrading google/go-containerregistry  to `master` (note: it doesn't have any releases) gives:

`💣  Failed to cache and load images: caching images: caching image /home/anders/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0: fetching remote image: unsupported MediaType: https://github.com/google/go-containerregistry/issues/377
`

**Comment by afbjorklund** [comment] 2019-03-28 18:28
@cvila84 : unfortunately there seems to be no away to avoid the spam from google/gcr:

``` go
		if auth == authn.Anonymous {
			log.Println("No matching credentials were found, falling back on anonymous")
		}
```

**Comment by cvila84** [comment] 2019-03-28 23:02
@afbjorklund you are right, the root cause does not come from the issue [#119](https://github.com/google/go-containerregistry/issues/119)  (according to this [comment](https://github.com/google/go-containerregistry/issues/119#issuecomment-412218490))
I guess we have to wait for compatible images pushed on quay.io but they do not seem to be worried about that (since they recently pushed images with old format)
For the spam, I guess I have to open an issue directly on google/gcr then...

**Comment by afbjorklund** [comment] 2019-03-30 07:51
It's a bug in the library IMHO, waiting for external parties to upgrade doesn't seem like a good approach

**Comment by cvila84** [comment] 2019-03-30 09:30
Agree.

But the guy closed the [issue](https://github.com/google/go-containerregistry/issues/377) and in this [comment](https://github.com/google/go-containerregistry/issues/377#issuecomment-471662167), he is quite clear : 

> I guess I'm reluctant to enable people to continue to depend on schema 1 images, because people should basically never be depending on schema 1 images, except for quay, which I think is being fixed.

So he is relying on quay.io to ensure next images pushed on this repo will be compatible with schema 2...

**Comment by afbjorklund** [comment] 2019-03-30 13:02
There are other image libraries, that might work better... We don't _have_ to use google/gcr.
We moved away* from containers/image, but could consider going back if it works better...

* in #2730

**Comment by aakarshg** [comment] 2019-04-01 18:23
This is not an issue specific to v1.0.0 as I notice the same issue with v0.35.0.

**Comment by tstromberg** [comment] 2019-05-23 23:28
I believe this issue was fixed in minikube v1.1. That said, the example still fails:

```
minikube cache add quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0 --alsologtostderr -v=8
I0523 16:21:54.215412   80236 notify.go:128] Checking for updates...
I0523 16:21:54.418000   80236 cache_images.go:307] Attempting to cache image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0 at /usr/local/google/home/tstromberg/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0
I0523 16:21:54.873611   80236 cache_images.go:331] OPENING:  /usr/local/google/home/tstromberg/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0


I0523 16:24:24.189035   80236 cache_images.go:304] 2019/05/23 16:21:54 Unable to read "/usr/local/google/home/tstromberg/.docker/config.json": open /usr/local/google/home/tstromberg/.docker/config.json: no such file or directory
2019/05/23 16:21:54 No matching credentials were found, falling back on anonymous
W0523 16:24:24.189239   80236 exit.go:100] Failed to cache and load images: caching images: caching image /usr/local/google/home/tstromberg/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0: unsupported status code 405; body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>

💣  Failed to cache and load images: caching images: caching image /usr/local/google/home/tstromberg/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0: unsupported status code 405; body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>
```

However, `docker pull` works just fine.

**Comment by reegnz** [comment] 2019-06-28 16:43
I am also getting the issue on minikube 1.2.0:
```
~ minikube cache add quay.io/dexidp/dex:v2.14.0

💣  Failed to cache and load images: caching images: caching image /Users/csreegn/.minikube/cache/images/quay.io/dexidp/dex_v2.14.0: unsupported status code 405; body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>


😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by AdnanHodzic** [comment] 2019-08-01 06:23
Are there any updates on this issue? I'm getting the same error:

```
minikube cache add quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0

💣  Failed to cache and load images: caching images: caching image /Users/xyz/.minikube/cache/images/quay.io/kubernetes-ingress-controller/nginx-ingress-controller_0.23.0: unsupported status code 405; body: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>


😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```

**Comment by tstromberg** [comment] 2019-09-20 21:36
This was fixed in minikube v1.4:

`minikube cache add quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.23.0`

**Closed by tstromberg** 2019-09-20 21:36 UTC
Labels: help wanted, kind/bug, priority/backlog, r/2019q2

**Comment by chris-free** [comment] 2019-11-07 16:22
I am getting the same ```does not match Docker-Content-Digest``` error as above in minikube 1.4.0 and 1.5.2

**Comment by tstromberg** [comment] 2019-11-07 17:10
I assume this is an issue with the go-containerregistry library we use. Has
anyone tried updating to the latest version in the go.mod file?

**Comment by chris-free** [comment] 2019-11-16 22:34
Commit https://github.com/google/go-containerregistry/commit/e3df2a4fd30e0756e8fc2031f5a02c5c0b25f10d removes the docker digest check.

Using this version Minikube `make` then gives:
`/home/chris/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180823182406-e3df2a4fd30e/pkg/v1/daemon/image.go:80:5: cli.NegotiateAPIVersion undefined (type *client.Client has no field or method NegotiateAPIVersion)
/home/chris/go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180823182406-e3df2a4fd30e/pkg/v1/daemon/write.go:43:5: cli.NegotiateAPIVersion undefined (type *client.Client has no field or method NegotiateAPIVersion)`

Could be wrong here - but this looks to be a dependency conflict whereby `go-containerregistry@e3df2a4` expects a different version of `docker/docker`

**Comment by tstromberg** [comment] 2019-11-17 03:13
@chris-free - Thanks for looking into this. We don't directly depend on docker, so it shouldn't be a problem to update our dependency on `docker/docker` with whatever version `go-containerregistry` looks for. 

Hopefully there isn't a `libmachine` conflict, anyways =)

**Comment by cvila84** [comment] 2019-11-18 13:08
Hello, i also tried @chris-free approach with same results. 

If I put the latest version of go-containerregistry AND remove the indirect dependency on docker/docker 1.13.1 in go.mod, a "go mod tidy" command will restore the dependency to 1.13.1...

I tried "go mod graph" to understand which other component may require this version 1.13.1 but did not find anything, so I'm a bit lost here.

BTW, why is this issue closed ?
