### ISSUE TITLE
minikube v1.30.0 states that `Image was not built for the current minikube` on Docker

### ISSUE THREAD

**Issue by jpjsm** [kubernetes/minikube#16225] opened 2023-04-03 20:09 UTC
### What Happened?

```text
C:\Users\juan_pablo_jofre>minikube start --cert-expiration=26280h --kubernetes-version=v1.26.3
* minikube v1.30.0 on Microsoft Windows 10 Enterprise 10.0.19042.2728 Build 19042.2728
* Automatically selected the docker driver. Other choices: hyperv, ssh
* Using Docker Desktop driver with root privileges
* Starting control plane node minikube in cluster minikube
* Pulling base image ...
    > gcr.io/k8s-minikube/kicbase...:  373.53 MiB / 373.53 MiB  100.00% 2.11 Mi
* Creating docker container (CPUs=2, Memory=8100MB) ...
! Image was not built for the current minikube version. To resolve this you can delete and recreate your minikube cluster using the latest images. Expected minikube version: v1.29.0 -> Actual minikube version: v1.30.0
* Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Configuring bridge CNI (Container Networking Interface) ...
  - Using image gcr.io/k8s-minikube/storage-provisioner:v5
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

### Attach the log file

[mikikube-log.txt](https://github.com/kubernetes/minikube/files/11142016/mikikube-log.txt)

### Operating System

Windows

### Driver

Docker

**Comment by spowelljr** [comment] 2023-04-03 20:50
Thanks for the issue report @jpjsm, we know the cause and are investigating it

**Comment by rafariossaa** [comment] 2023-04-04 14:59
This same happens to me under linux:
```
$ minikube start
😄  minikube v1.30.0 on Ubuntu 22.10
✨  Automatically selected the docker driver. Other choices: virtualbox, ssh
📌  Using Docker driver with root privileges
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
🔥  Creating docker container (CPUs=2, Memory=7900MB) ...
❗  Image was not built for the current minikube version. To resolve this you can delete and recreate your minikube cluster using the latest images. Expected minikube version: v1.29.0 -> Actual minikube version: v1.30.0
🐳  Preparing Kubernetes v1.26.3 on Docker 23.0.2 ...
    ▪ Generating certificates and keys ...
    ▪ Booting up control plane ...
    ▪ Configuring RBAC rules ...
🔗  Configuring bridge CNI (Container Networking Interface) ...
    ▪ Using image gcr.io/k8s-minikube/storage-provisioner:v5
🔎  Verifying Kubernetes components...
🌟  Enabled addons: storage-provisioner, default-storageclass
🏄  Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default
```

**Comment by spowelljr** [comment] 2023-04-05 04:25
This has been fixed in the v1.30.1 release

**Closed by spowelljr** 2023-04-05 04:25 UTC
Labels: kind/bug, co/docker-driver, co/kic-base

**Comment by rafariossaa** [comment] 2023-04-05 07:33
Thanks !

**Comment by robrich** [comment] 2023-04-26 15:40
I still see this message in Minikube 1.30.1.

**Comment by spowelljr** [comment] 2023-04-26 20:08
> I still see this message in Minikube 1.30.1. I'm using Minikube with Hyper-V on Windows 11.

Make sure `minikube delete` the existing cluster, it might just me that you started the cluster with a previous version of minikube and the message is expected.

**Comment by robrich** [comment] 2023-04-27 02:11
> > I still see this message in Minikube 1.30.1. I'm using Minikube with Hyper-V on Windows 11.
> 
> Make sure you `minikube delete` the existing cluster, it might just be that you started the cluster with a previous version of minikube and the message is expected.

Does this mean that with every new update, I need to delete my cluster, recreate it, re-download all the images, and re-configure all the addons, helm charts, secrets, volumes, etc? This seems like an awful waste of bandwidth and time. If this is the path forward, I'll likely update much less frequently. Please say it isn't so.

**Comment by spowelljr** [comment] 2023-04-27 02:25
You don't have to do anything, it's just a cautionary warning that the version of minikube the cluster was created with doesn't match the current binary version. The goal of the message is to assist users that update from old versions of minikube and try to do something that the new binary supports but the old cluster itself doesn't, instead of them not able to get it to work and then open a GitHub issue.

**Comment by robrich** [comment] 2023-04-27 04:37
Ah, so an inspirational message rather than a cautionary message. Then I'd
recommend modifying this message to highlight new capabilities rather than
suggesting the inevitable disaster, and then create a flag or config
setting to disable it.
