### ISSUE TITLE
Cannot start minikube on Centos 8

### ISSUE THREAD

**Issue by stevendonline** [kubernetes/minikube#6025] opened 2019-12-06 13:49 UTC
Hi, I was trying to install the minikube on my laptop without VM. I have installed Docker and verified it is working fine (download images, start container etc.).

**The exact command to reproduce the issue**:
sudo minikube start --vm-driver=none

**The full output of the command that failed**:
😄  minikube v1.5.2 on Centos 8.0.1905
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running none "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.2 on Docker '18.06.3-ce' ...
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: apiserver process never appeared

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

</details>

**The output of the `minikube logs` command**:<details>

💣  Error getting config: stat /home/sd/.minikube/profiles/minikube/config.json: no such file or directory

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

</details>

**The operating system version**:
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

**Comment by afbjorklund** [comment] 2019-12-09 18:20
Did you disable SELinux ? (we should probably add that step to a solution checklist)

**Comment by afbjorklund** [comment] 2019-12-09 18:22
More details in #5532

**Comment by tstromberg** [comment] 2019-12-16 20:55
This issue appears to be a duplicate of #6014, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-12-16 20:55 UTC
Labels: co/none-driver, co/runtime/docker, needs-solution-message, priority/important-longterm
