### ISSUE TITLE
Linux VirtualBox TestStartStop: failure loading etcd/ca certificate authority: the certificate is not valid yet

### ISSUE THREAD

**Issue by balopat** [kubernetes/minikube#3433] opened 2018-12-08 22:02 UTC
This seems similar to https://github.com/kubernetes/minikube/issues/3196: 

```, output: [init] Using Kubernetes version: v1.10.0
    		[init] Using Authorization modes: [Node RBAC]
    		[preflight] Running pre-flight checks.
    			[WARNING SystemVerification]: docker version is greater than the most recently validated version. Docker version: 18.06.1-ce. Max validated version: 17.03
    			[WARNING Swap]: running with swap on is not supported. Please disable swap
    		Flag --admission-control has been deprecated, Use --enable-admission-plugins or --disable-admission-plugins instead. Will be removed in a future version.
    		[certificates] Using the existing ca certificate and key.
    		[certificates] Using the existing apiserver certificate and key.
    		[certificates] Generated apiserver-kubelet-client certificate and key.
    		[certificates] Generated etcd/ca certificate and key.
    		[certificates] Generated etcd/server certificate and key.
    		failure loading etcd/ca certificate authority: the certificate is not valid yet
    		[certificates] etcd/server serving cert is signed for DNS names [localhost] and IPs [127.0.0.1]
```

Example: https://storage.googleapis.com/minikube-builds/logs/3432/Linux-VirtualBox.txt

**Comment by tstromberg** [comment] 2018-12-10 17:59
FYI, I think this might be because when guest VM is synced against a different time source than the host VM. 

When possible for sanity sake, the guest should sync against the host.  I think I noticed code that syncs against time?.google.com

**Comment by tstromberg** [comment] 2018-12-11 02:01
Dupe of #2749

**Closed by tstromberg** 2018-12-11 02:01 UTC
Labels: kind/flake
