### ISSUE TITLE
hyperv: Process exited with status 137 from signal KILL (OOM'd)

### ISSUE THREAD

**Issue by SvenLauterbach** [kubernetes/minikube#4017] opened 2019-03-28 13:41 UTC
Hi,

I tried starting a minikube cluster:
```
PS C:\WINDOWS\system32> minikube start --vm-driver hyperv --hyperv-virtual-switch "Wifi"
o   minikube v1.0.0 on windows (amd64)
$   Downloading Kubernetes v1.14.0 images in the background ...
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Re-using the currently running hyperv VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.178.43
-   Configuring Docker as the container runtime ...
-   Version of container runtime is 18.06.2-ce
:   Waiting for image downloads to complete ...
-   Preparing Kubernetes environment ...
X   Unable to load cached images: loading cached images: loading image C:\Users\SvenLauterbach\.minikube\cache\images\k8s.gcr.io\k8s-dns-sidecar-amd64_1.14.13: Docker load /tmp/k8s-dns-sidecar-amd64_1.14.13: command failed: docker load -i /tmp/k8s-dns-sidecar-amd64_1.14.13
stdout:
stderr: : Process exited with status 137 from signal KILL

!   Failed to update cluster: downloading binaries: copy: pre-copy: NewSession: write tcp 192.168.178.31:52945->192.168.178.43:22: wsasend: An existing connection was forcibly closed by the remote host.

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
``` 

minikub logs:

```
PS C:\WINDOWS\system32> minikube logs
==> dmesg <==
[  +0.000002]  __handle_mm_fault+0x429/0xa70
[  +0.000002]  handle_mm_fault+0xa5/0x1f0
[  +0.000003]  __do_page_fault+0x235/0x4b0
[  +0.000002]  ? syscall_slow_exit_work+0xba/0xc0
[  +0.000001]  ? page_fault+0x36/0x60
[  +0.000001]  page_fault+0x4c/0x60
[  +0.000002] RIP: 0033:0x45c509
[  +0.000001] RSP: 002b:00007f3ac6c8dc40 EFLAGS: 00010246
[  +0.000002] Mem-Info:
[  +0.000007] active_anon:12069 inactive_anon:58097 isolated_anon:0
               active_file:25 inactive_file:27 isolated_file:0
               unevictable:116613 dirty:9 writeback:0 unstable:0
               slab_reclaimable:4956 slab_unreclaimable:6266
               mapped:16025 shmem:61169 pagetables:426 bounce:0
               free:3147 free_pcp:309 free_cma:0
[  +0.000002] Node 0 active_anon:48276kB inactive_anon:232388kB active_file:100kB inactive_file:108kB unevictable:466452kB isolated(anon):0kB isolated(file):0kB mapped:64100kB dirty:36kB writeback:0kB shmem:244676kB writeback_tmp:0kB unstable:0kB all_unreclaimable? yes
[  +0.000001] Node 0 DMA free:7348kB min:44kB low:56kB high:68kB active_anon:364kB inactive_anon:8064kB active_file:0kB inactive_file:0kB unevictable:0kB writepending:0kB present:15992kB managed:15908kB mlocked:0kB kernel_stack:4kB pagetables:12kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB
[  +0.000004] lowmem_reserve[]: 0 1826 1826 1826
[  +0.000002] Node 0 DMA32 free:5240kB min:5444kB low:7312kB high:9180kB active_anon:47744kB inactive_anon:224324kB active_file:100kB inactive_file:112kB unevictable:466452kB writepending:36kB present:2080704kB managed:2011528kB mlocked:0kB kernel_stack:2972kB pagetables:1692kB bounce:0kB free_pcp:1236kB local_pcp:476kB free_cma:0kB
[  +0.000003] lowmem_reserve[]: 0 0 0 0
[  +0.000001] Node 0 DMA: 7*4kB (UME) 3*8kB (UE) 2*16kB (UM) 5*32kB (UE) 3*64kB (UE) 0*128kB 3*256kB (UME) 2*512kB (ME) 3*1024kB (UME) 1*2048kB (E) 0*4096kB = 7348kB
[  +0.000008] Node 0 DMA32: 15*4kB (UE) 52*8kB (UEH) 38*16kB (UE) 20*32kB (UMEH) 8*64kB (UME) 3*128kB (UM) 2*256kB (UM) 2*512kB (ME) 1*1024kB (U) 0*2048kB 0*4096kB = 5180kB
[  +0.000008] 177835 total pagecache pages
[  +0.000001] 0 pages in swap cache
[  +0.000001] Swap cache stats: add 0, delete 0, find 0/0
[  +0.000000] Free swap  = 0kB
[  +0.000001] Total swap = 0kB
[  +0.000000] 524174 pages RAM
[  +0.000000] 0 pages HighMem/MovableOnly
[  +0.000001] 17315 pages reserved
[  +0.000028] Out of memory: Kill process 3484 (sshd) score 2 or sacrifice child
[  +0.000020] Killed process 3582 (sshd) total-vm:23808kB, anon-rss:2048kB, file-rss:1456kB, shmem-rss:0kB
[  +0.003666] Out of memory: Kill process 3484 (sshd) score 2 or sacrifice child
[  +0.000068] Killed process 3517 (scp) total-vm:21492kB, anon-rss:312kB, file-rss:2288kB, shmem-rss:0kB
[  +0.024077] Out of memory: Kill process 3482 (sshd) score 2 or sacrifice child
[  +0.000005] Killed process 3484 (sshd) total-vm:22560kB, anon-rss:928kB, file-rss:2656kB, shmem-rss:0kB
[  +0.002227] Out of memory: Kill process 3086 (sshd) score 2 or sacrifice child
[  +0.000096] Killed process 3088 (sshd) total-vm:22116kB, anon-rss:432kB, file-rss:2544kB, shmem-rss:0kB
[  +1.058472] Out of memory: Kill process 2907 (systemd-resolve) score 1 or sacrifice child
[  +0.000047] Killed process 2907 (systemd-resolve) total-vm:34136kB, anon-rss:368kB, file-rss:3552kB, shmem-rss:0kB
[  +0.011193] systemd[1]: systemd-resolved.service: Main process exited, code=killed, status=9/KILL
[  +0.000237] systemd[1]: systemd-resolved.service: Failed with result 'signal'.
[  +0.029618] Out of memory: Kill process 3586 ((resolved)) score 2 or sacrifice child
[  +0.000063] Killed process 3586 ((resolved)) total-vm:121284kB, anon-rss:1760kB, file-rss:2992kB, shmem-rss:0kB
[  +0.001293] systemd[1]: systemd-resolved.service: Main process exited, code=killed, status=9/KILL
[  +0.000355] systemd[1]: systemd-resolved.service: Failed with result 'signal'.
[  +0.000584] systemd[1]: Failed to start Network Name Resolution.
[  +0.129976] systemd[3589]: systemd-resolved.service: Failed to connect stdout to the journal socket, ignoring: Connection refused
[Mar28 13:30] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Mar28 13:35] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.

==> kernel <==
 13:36:29 up 11 min,  0 users,  load average: 0.01, 0.08, 0.08
Linux minikube 4.15.0 #1 SMP Tue Mar 26 02:53:14 UTC 2019 x86_64 GNU/Linux

==> kubelet <==
-- Logs begin at Thu 2019-03-28 13:25:10 UTC, end at Thu 2019-03-28 14:25:09 UTC. --
-- No entries --
```

I'm using Windows 10 17763.379

**Comment by afbjorklund** [comment] 2019-03-28 18:41
Seems like it ran out of memory

**Comment by tstromberg** [comment] 2019-04-04 23:50
Thanks for the bug report! I'm closing as dupe of #1766. The workaround here is to disable dynamic memory in HyperV. Please let me know if you think this is something different.

**Closed by tstromberg** 2019-04-04 23:50 UTC
Labels: co/hyperv
