### ISSUE TITLE
TestRunningBinaryUpgrade:

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#11839] opened 2021-06-30 19:56 UTC
Example:

https://storage.googleapis.com/minikube-builds/logs/11811/861d81b/Docker_Linux.html

**Comment by spowelljr** [comment] 2022-01-12 19:40
Duplicate of https://github.com/kubernetes/minikube/issues/12218, closing

**Closed by spowelljr** 2022-01-12 19:40 UTC
Labels: priority/important-longterm, lifecycle/rotten, kind/flake, kind/failing-test
