### ISSUE TITLE
windows defender blocks minikube-installer.exe

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7979] opened 2020-05-02 23:12 UTC
on a fresh windows machine if you use the [minikube-installer.exe](https://github.com/kubernetes/minikube/releases/download/v1.10.0-beta.2/minikube-installer.exe) 
(instead of choco install)

![Screen Shot 2020-05-02 at 4 11 22 PM](https://user-images.githubusercontent.com/4564227/80894425-b1d59d00-8c8f-11ea-86e0-e5b495f46dbe.png)

without any button that says Lets do it anyway.
unless you click on More Info, then there will be a a link revleaing. (I bet most ppl would not click on that to get there)

PS. 
this doesn't happen if you install minikube with choco. but that would require you to install choco.

**Comment by afbjorklund** [comment] 2020-05-03 08:47
I think that this is a known issue: #6735 

Minikube is blocked on _every_ platform:
* Apple Gatekeeper
* Microsoft Smartscreen
* Ubuntu Software

**Comment by sharifelgamal** [comment] 2020-05-04 16:10
Closing as a dupe of #6735

**Closed by sharifelgamal** 2020-05-04 16:10 UTC
Labels: os/windows, packaging, packaging/windows, priority/important-soon, triage/duplicate
