### ISSUE TITLE
Minikube not starting 

### ISSUE THREAD

**Issue by sachinjoshi72** [kubernetes/minikube#11888] opened 2021-07-02 16:57 UTC
C:\Users\KetanJoshi>minikube start
* minikube v1.21.0 on Microsoft Windows 10 Home Single Language 10.0.18363 Build 18363
* Using the virtualbox driver based on existing profile
* Starting control plane node minikube in cluster minikube
* Restarting existing virtualbox VM for "minikube" ...
! StartHost failed, but will try again: driver start: Maximum number of retries (5) exceeded
* Updating the running virtualbox "minikube" VM ...
* Failed to start virtualbox VM. Running "minikube delete" may fix it: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002735a360

X Exiting due to GUEST_PROVISION: Failed to start host: provision: Temporary Error: error getting ip during provisioning: Could not find matching IP for MAC address 08002735a360
*
╭──────────────────────────────────────────────────────────────────╮
│                                                                  │
│    * If the above advice does not help, please let us know:      │
│      https://github.com/kubernetes/minikube/issues/new/choose    │
│                                                                  │
│    * Please attach the following file to the GitHub issue:       │
│    * - C:\Users\KetanJoshi\.minikube\logs\lastStart.txt          │
│                                                                  │
╰──────────────────────────────────────────────────────────────────╯

**Comment by spowelljr** [comment] 2021-07-02 18:23
Hi @sachinjoshi72, thank you for reporting your issue!

This is a duplicate of #11801, I'm going to close this issue in favor of #11801, but please follow along and feel free to add any new discoveries there.

Thanks for using minikube!

**Closed by spowelljr** 2021-07-02 18:23 UTC
