### ISSUE TITLE
hyperv: Default to disabling dynamic memory (pass --hyperv-disable-dynamic-memory to driver)

### ISSUE THREAD

**Issue by AceHack** [kubernetes/minikube#2331] opened 2017-12-18 03:42 UTC
I keep running into issues the first time I do minikube start with kubeadm and hyper-v.  It seems to be releated to dynamic memory.  I can stop things, disable dynamic memory, then restart but I think it's messed up by then.  I'm tyring to work though it now.

**Comment by kwaazaar** [comment] 2018-01-06 14:12
I can confirm that dynamic memory enabled causes problems. Everything starts fine, but after a while it just stops working. See my own issue here: https://github.com/kubernetes/minikube/issues/2298

**Comment by alexandervantrijffel** [comment] 2018-02-20 22:24
It would be nice if minikube start supports an option to disable dynamic memory for hyper-v.

**Comment by shahiddev** [comment] 2018-05-03 09:49
Hi, I've been bitten by this problem a few times so would like to implement this.
I'm having a few issues trying to build the source code (wsl on Windows machine), trying to follow the contrib guide. 
I'm at Kubecon, if someone could give me a few pointers that would be awesome, I'm probably just being a noob :/

**Comment by dlorenc** [comment] 2018-05-03 09:54
I'm here as well, come by the Minikube Intro session this afternoon and we can get your build sorted out :)

**Comment by shahiddev** [comment] 2018-05-03 09:56
Fantastic, I am attending that session and was going to ask you :-)

**Comment by dlorenc** [comment] 2018-05-03 14:18
Hey @shahiddev, could you try doing the build with:

```MINIKUBE_BUILD_IN_DOCKER=y make```

My guess is that we're not building in docker because WSL looks like linux, but it doesn't look enough like it to actually work. That flag should force the build to run in a container.

**Comment by shahiddev** [comment] 2018-05-03 15:20
Hi @dlorenc that still fails

```
shahid@SI-SP4:~/projects/go/src/k8s.io/minikube$ MINIKUBE_BUILD_IN_DOCKER=y make
docker run --rm -e IN_DOCKER=1 --user 1000:1000 -w /go/src/k8s.io/minikube -v /home/shahid/projects/go:/go --entrypoint /bin/bash k8s.gcr.io/kube-cross:v1.9.1-1 -c '/usr/bin/make out/minikube-linux-amd64'
make: *** No rule to make target 'out/minikube-linux-amd64'.  Stop.
Makefile:120: recipe for target 'out/minikube-linux-amd64' failed
make: *** [out/minikube-linux-amd64] Error 2
```

**Comment by shahiddev** [comment] 2018-05-03 20:53
Thanks, that's a useful hint, I can dig a bit deeper to figure that out.
I'll update the docs once I get to the bottom of it.

**Comment by shahiddev** [comment] 2018-05-06 19:19
Seems like I can get minikube building in the Windows Subsystem for Linux now without needing to use the docker approach.

I'm trying to build the Windows binaries using `GOOS=windows make` which isn't working, is this the correct way to build the windows binaries? Output I get is this:
```
$ GOOS=windows make
make: *** No rule to make target 'out/minikube-windows-amd64".exe"', needed by 'out/minikube".exe"'.  Stop.
```

**Comment by shahiddev** [comment] 2018-05-08 11:50
I got a way to test what I've been doing that's fine for now.

I have a question about best approach for implementing. 
At the moment I'm implementing this as an optional flag to disable the dynamic memory option, this way current behaviour is unchanged, I would prefer to enable it by default but feels like giving the option for disable first is better before making a potentially breaking change by setting the default to be disabled.

Does that sound like a sensible approach?

**Comment by AceHack** [comment] 2018-12-05 04:18
Please keep active

**Comment by penrique** [comment] 2018-12-19 22:09
This would be really useful, I'm going through this right now too

**Comment by tstromberg** [comment] 2019-01-23 18:05
I'd never heard of dynamic memory before, but read up a little on it:

https://blogs.technet.microsoft.com/virtualization/2015/05/26/when-to-use-hyper-v-dynamic-memory-versus-runtime-memory-resize/

I don't know much about HyperV, but I would definitely be happy to help someone implement this if they want to tackle it. It seems like the --hyperv-disable-dynamic-memory option is supported already by the hyperv driver:

https://docs.docker.com/machine/drivers/hyper-v/#4-create-the-nodes-with-docker-machine-and-the-microsoft-hyper-v-driver

**Comment by tstromberg** [comment] 2019-01-24 05:18
Dupe of #1766

**Closed by tstromberg** 2019-01-24 05:18 UTC
Labels: co/hyperv, good first issue, help wanted, kind/feature, os/windows, priority/important-longterm, triage/duplicate
