### ISSUE TITLE
none: lz4 not found -> Port 10257 is in use

### ISSUE THREAD

**Issue by gurukodi** [kubernetes/minikube#6976] opened 2020-03-10 14:20 UTC
Exact command:
sudo minikube start --vm-driver=none

Output:
 minikube v1.8.1 on Ubuntu 16.04
✨  Using the none driver based on user configuration
🤹  Running on localhost (CPUs=16, Memory=32153MB, Disk=906534MB) ...
ℹ️   OS release is Ubuntu 16.04.6 LTS
E0310 19:45:26.935762    8872 config.go:71] Failed to preload container runtime Docker: extracting tarball: 
** stderr ** 
tar (child): lz4: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now

** /stderr **: sudo tar -I lz4 -C /var -xvf /preloaded.tar.lz4: exit status 2
stdout:

stderr:
tar (child): lz4: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
, falling back to caching images
🐳  Preparing Kubernetes v1.17.3 on Docker 19.03.4 ...
🚀  Launching Kubernetes ... 
💾  Downloading preloaded images tarball for k8s v1.17.3 ...
    > preloaded-images-k8s-v1-v1.17.3-docker-overlay2.tar.lz4: 366.98 MiB / 499
💣  Error starting cluster: init failed. output: "-- stdout --\n[init] Using Kubernetes version: v1.17.3\n[preflight] Running pre-flight checks\n\n-- /stdout --\n** stderr ** \nW0310 19:45:28.688284    9194 validation.go:28] Cannot validate kube-proxy config - no validator is available\nW0310 19:45:28.688326    9194 validation.go:28] Cannot validate kubelet config - no validator is available\n\t[WARNING IsDockerSystemdCheck]: detected \"cgroupfs\" as the Docker cgroup driver. The recommended driver is \"systemd\". Please follow the guide at https://kubernetes.io/docs/setup/cri/\n\t[WARNING Swap]: running with swap on is not supported. Please disable swap\n\t[WARNING Port-10250]: Port 10250 is in use\nerror execution phase preflight: [preflight] Some fatal errors occurred:\n\t[ERROR Port-10259]: Port 10259 is in use\n\t[ERROR Port-10257]: Port 10257 is in use\n\t[ERROR Port-2379]: Port 2379 is in use\n\t[ERROR Port-2380]: Port 2380 is in use\n[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`\nTo see the stack trace of this error execute with --v=5 or higher\n\n** /stderr **": /bin/bash -c "sudo env PATH=/var/lib/minikube/binaries/v1.17.3:$PATH kubeadm init --config /var/tmp/minikube/kubeadm.yaml  --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests,DirAvailable--var-lib-minikube,DirAvailable--var-lib-minikube-etcd,FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml,FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml,FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml,FileAvailable--etc-kubernetes-manifests-etcd.yaml,Port-10250,Swap,SystemVerification": exit status 1
stdout:
[init] Using Kubernetes version: v1.17.3
[preflight] Running pre-flight checks

stderr:
W0310 19:45:28.688284    9194 validation.go:28] Cannot validate kube-proxy config - no validator is available
W0310 19:45:28.688326    9194 validation.go:28] Cannot validate kubelet config - no validator is available
	[WARNING IsDockerSystemdCheck]: detected "cgroupfs" as the Docker cgroup driver. The recommended driver is "systemd". Please follow the guide at https://kubernetes.io/docs/setup/cri/
	[WARNING Swap]: running with swap on is not supported. Please disable swap
	[WARNING Port-10250]: Port 10250 is in use
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR Port-10259]: Port 10259 is in use
	[ERROR Port-10257]: Port 10257 is in use
	[ERROR Port-2379]: Port 2379 is in use
	[ERROR Port-2380]: Port 2380 is in use
[preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
To see the stack trace of this error execute with --v=5 or higher

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

OS and minikube:
ubuntu 16.04 and minikube 1.8.1

**Comment by afbjorklund** [comment] 2020-03-10 17:53
Looks like the ports are already in use... Do you have another minikube running in the background perhaps?

**Comment by tstromberg** [comment] 2020-03-18 18:40
I believe we fixed at least part of this problem in v1.8.2. Do you mind upgrading and running `minikube delete` and `minikube start` to confirm?

**Comment by tstromberg** [comment] 2020-03-25 18:35
This issue appears to be a duplicate of #6425 - do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-03-25 18:35 UTC
Labels: co/none-driver, triage/needs-information, triage/support
