### ISSUE TITLE
hyperkit: machine creation: hyperkit crashed! 

### ISSUE THREAD

**Issue by subratasen** [kubernetes/minikube#5811] opened 2019-11-01 14:02 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:<details>

💿  Downloading VM boot image ...
    > minikube-v1.5.1.iso.sha256: 65 B / 65 B [--------------] 100.00% ? p/s 0s
    > minikube-v1.5.1.iso: 143.76 MiB / 143.76 MiB [] 100.00% 14.11 MiB p/s 10s
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...
🔥  Creating hyperkit VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
🔄  Retriable failure: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
🔥  Deleting "minikube" in hyperkit ...

💣  Unable to start VM: create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
macOS Mojave version 10.14.6

**Comment by ubozov** [comment] 2019-11-02 15:25
@subratasen  please try to update your `docker`

I had the same problem that was solved after the `docker` upgrade.

`docker version` after upgrade
```
Client: Docker Engine - Community
 Version:           19.03.4
 API version:       1.40
 Go version:        go1.12.10
 Git commit:        9013bf5
 Built:             Thu Oct 17 23:44:48 2019
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.4
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.10
  Git commit:       9013bf5
  Built:            Thu Oct 17 23:50:38 2019
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by govargo** [comment] 2019-11-03 13:38
Maybe related to #5610

If so, this issue is resolved by installing latest hyperkit.
hyperkit is installed with docker for mac together.
So, if you upgrade docker for mac to latest version, this issue may be resolved.

I'm going to add version check of hyperkit to prevent this.

**Comment by afbjorklund** [comment] 2019-11-03 16:17
You shouldn't need to install docker, just to run minikube.

**Comment by medyagh** [comment] 2019-11-04 22:53
@subratasen could you please check if upgrading your Hyperv would fix this ?
https://github.com/kubernetes/minikube/issues/5594#issuecomment-548583815

**Comment by burdiyan** [comment] 2019-12-13 19:19
Looks like hyperkit driver for minikube doesn't work without Docker for Mac, even with hyperkit installed with Homebrew. I've been doing lots of tests with that, and no luck, unless you install Docker for Mac.

**Comment by burdiyan** [comment] 2019-12-13 19:25
Perhaps, `vpnkit` is what Minikube also want with hyperkit driver? Because that seems to be the only piece missing without Docker for Mac. And you can't install vpnkit with brew apparently.

**Comment by priyawadhwa** [comment] 2020-01-29 19:35
Hey @subratasen are you still seeing this issue? It seems that doing the following might help:

- upgrading docker if you have it installed
- upgrading to the latest version of hyperkit
- upgrading to the [latest version](https://minikube.sigs.k8s.io/docs/start/) of minikube

Please let us know if that doesn't help!

**Comment by nicknovitski** [comment] 2020-01-29 21:55
I can confirm that the issue is still present with the latest versions of hyperkit and minikube, on macOS catalina.
<details>
```
😄  minikube v1.6.2 on Darwin 10.15.2
✨  Selecting 'hyperkit' driver from user configuration (alternates: [])
🔥  Creating hyperkit VM (CPUs=2, Memory=4000MB, Disk=64000MB) ...

💣  Unable to start VM. Please investigate and run 'minikube delete' if possible
❌  Error: [HYPERKIT_CRASHED] create: Error creating machine: Error in driver during machine creation: hyperkit crashed! command line:
  hyperkit loglevel=3 console=ttyS0 console=tty0 noembed nomodeset norestore waitusb=10 systemd.legacy_systemd_cgroup_controller=yes random.trust_cpu=on hw_rng_model=virtio base host=minikube
💡  Suggestion: Hyperkit is broken. Upgrade to the latest hyperkit version and/or Docker for Desktop. Alternatively, you may choose an alternate --vm-driver
⁉️   Related issues:
    ▪ https://github.com/kubernetes/minikube/issues/6079
    ▪ https://github.com/kubernetes/minikube/issues/5780

😿  If the above advice does not help, please let us know:
👉  https://github.com/kubernetes/minikube/issues/new/choose
```
</details>

As @burdiyan has said, the workaround is to install Docker for Desktop, which stinks.

**Comment by ylathouris** [comment] 2020-02-12 22:58
I am having this issue as well:

- **docker-19.03.5** 
- **hyperkit-0.20190802**
- **minikube-1.7.2**

**Comment by mjgallag** [comment] 2020-03-09 23:46
New version of `hyperkit` with Cataline fix is finally available on `Homebrew`, see https://github.com/Homebrew/homebrew-core/pull/50655 & https://github.com/moby/hyperkit/issues/267 for details.

**Comment by tstromberg** [comment] 2020-04-15 23:52
I'm closing this issue as it hasn't seen activity in awhile, and it's unclear if this issue still exists. If this issue does continue to exist in the most recent release of minikube, please feel free to re-open it. 

Thank you for opening the issue!

**Closed by tstromberg** 2020-04-15 23:52 UTC
Labels: co/hyperkit, os/macos, triage/needs-information, triage/support

**Comment by nicknovitski** [comment] 2020-05-06 17:10
I am no longer able to reproduce the issue, so I believe it has been resolved with newer minikube and/or hyperkit releases.
