### ISSUE TITLE
Error configuring auth on host: OS type not recognized.

### ISSUE THREAD

**Issue by WandyLau** [kubernetes/minikube#3952] opened 2019-03-25 07:03 UTC
minikube start --vm-driver=kvm2

Starting local Kubernetes v1.10.0 cluster...
Starting VM...
E0325 06:58:54.415931    6255 start.go:174] Error starting host: Temporary Error: Error configuring auth on host: OS type not recognized.

x86_64 x86_64 x86_64 GNU/Linux: ubuntu 16.04

**Comment by tstromberg** [comment] 2019-03-25 19:00
Would you mind upgrading minikube first? This version seems very very old.

**Comment by WandyLau** [comment] 2019-03-26 05:13
thanks for the reply. I just updated my kubemini version to 0.35.
But I got the error as: 
`minikube v0.35.0 on linux (amd64)`
`🏃  Re-using the currently running kvm2 VM for "my" ...`
`⌛  Waiting for SSH access ...`
`🏃  Re-using the currently running kvm2 VM for "my" ...`
`⌛  Waiting for SSH access ...`
`🏃  Re-using the currently running kvm2 VM for "my" ...`
`⌛  Waiting for SSH access ...`
`💣  Unable to start VM: Temporary Error: Error configuring auth on host: OS type not recognized`
`Temporary Error: Error configuring auth on host: OS type not recognized`
`Temporary Error: Error configuring auth on host: OS type not recognized`

But I can start this with `minikube start --vm-driver=none`

Maybe some wrong with kvm2. I will keep looking at it. If any clue, please share it. Thanks.

**Comment by tstromberg** [comment] 2019-03-26 05:46
Please try: `minikube delete`' , and then `minikube start`.

I think your kvm2 VM was in a bad state.

**Comment by WandyLau** [comment] 2019-03-26 08:35
I followed the doc to install kvm2. Now I get this error. How can I verify if my libvirt is in good state?

`Unable to start VM: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds`

**Comment by WandyLau** [comment] 2019-03-28 01:37
Is this a bug?

**Comment by WandyLau** [comment] 2019-03-30 06:52
Even I updated to the latest minikube 1.0, I still got this error.
: `Unable to start VM: create: Error creating machine: Error in driver during machine creation: Machine didn't return an IP after 120 seconds`

And before this error I got `
06:47:38 Unable to read "/root/.docker/config.json": open /root/.docker/config.json: no such file or directory
2019/03/30 06:47:38 No matching credentials were found, falling back on anonymous`

Did I miss some config?

**Comment by WandyLau** [comment] 2019-03-30 06:54
`systemctl status libvirtd.service`  got error as below:

`2019-03-30 06:50:39.375+0000: 24715: error : virNetSocketReadWire:`

**Comment by afbjorklund** [comment] 2019-03-30 09:01
The config.json error is unrelated, and the "did not return an IP" means that SSH didn't start properly...

Maybe something like https://wiki.libvirt.org/page/Troubleshooting can help you get the hypervisor up ?

**Comment by WandyLau** [comment] 2019-04-03 06:35
No. I got no luck. I am not sure what was going on there.

**Comment by tstromberg** [comment] 2019-04-04 18:31
Reluctantly marking as a dupe of #3566 - not exactly sure what else to do here, but it seems very similar.

**Closed by tstromberg** 2019-04-04 18:31 UTC
Labels: co/kvm2, kind/bug, triage/support
