### ISSUE TITLE
Communication with service name is not possible

### ISSUE THREAD

**Issue by ReneWerner87** [kubernetes/minikube#2438] opened 2018-01-19 19:19 UTC
Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): v0.24.1
- **OS**: Linux Mint 18.3
- **VM Driver**: virtualbox
- **ISO version**: minikube-v0.23.6.iso

**What happened**:
The communication between nginx and php container with service name is not possible and runs in a timeout.

**What you expected to happen**:
The communication between nginx and php container by service name should be possible.

**How to reproduce it** (as minimally and precisely as possible):
look in the demo project -> https://github.com/ReneWerner87/minikube_issue

**Anything else do we need to know**:
Please read the README.md of the https://github.com/ReneWerner87/minikube_issue repository and look in the kubernetes yml to reproduct the issue.

![communication_test](https://raw.githubusercontent.com/ReneWerner87/minikube_issue/master/service_communication.gif "communication test")

**Comment by ReneWerner87** [comment] 2018-01-19 20:09
i think the comment https://github.com/kubernetes/minikube/issues/1568#issuecomment-308674617 is the solution, but it should be fixed

**Comment by r2d4** [comment] 2018-01-23 22:56
Closing this as a duplicate of #1568, we'll track it there

**Closed by r2d4** 2018-01-23 22:56 UTC
