### ISSUE TITLE
The connection to the server localhost:8443 was refused - did you specify the right host or port?

### ISSUE THREAD

**Issue by vaibsharma** [kubernetes/minikube#13317] opened 2022-01-08 12:32 UTC
### What Happened?

[log.txt](https://github.com/kubernetes/minikube/files/7833202/log.txt)
 
Unable top install minikube on MacOS Big Sur M1.

Attached the log file. Please have a look.  

### Attach the log file

0108 17:56:34.111454   41158 logs.go:190] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.22.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
The connection to the server localhost:8443 was refused - did you specify the right host or port?
 output: "\n** stderr ** \nThe connection to the server localhost:8443 was refused - did you specify the right host or port?\n\n** /stderr **"

❗  unable to fetch logs for: describe nodes

### Operating System

macOS (Default)

### Driver

Docker

**Comment by spowelljr** [comment] 2022-01-25 19:29
Hi @vaibsharma, thanks for reporting your issue with minikube!

This is a duplicate of https://github.com/kubernetes/minikube/issues/12274.

The fix for now is outlined here: https://github.com/kubernetes/minikube/issues/12274#issuecomment-1006201978

I'm going to close this issue, is you have further questions please ask them in https://github.com/kubernetes/minikube/issues/12274 to centralize information, thank you!

**Closed by spowelljr** 2022-01-25 19:29 UTC
