### ISSUE TITLE
Can't start minikube-- permissions on Linux

### ISSUE THREAD

**Issue by evanspiatt** [kubernetes/minikube#4349] opened 2019-05-24 17:18 UTC
**The exact command to reproduce the issue**:
[devans@sundae ~]$ minikube start -p Dan1 --vm-driver=none
😄  minikube v1.1.0 on linux (amd64)
🔥  Creating none VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
🐳  Configuring environment for Kubernetes v1.14.2 on Docker 18.09.6
❌  Unable to load cached images: loading cached images: loading image /home/devans/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.2: stat /home/devans/.minikube/cache/images/k8s.gcr.io/kube-controller-manager_v1.14.2: no such file or directory

💣  Failed to update cluster: downloading binaries: copying kubeadm: copy: error creating file at /usr/bin/kubeadm: open /usr/bin/kubeadm: permission denied

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new

**The full output of the command that failed**:
(see above)
**The output of the `minikube logs` command**:
==> dmesg <==
dmesg: invalid option -- '='

Usage:
 dmesg [options]

Options:
 -C, --clear                 clear the kernel ring buffer
 -c, --read-clear            read and clear all messages
 -D, --console-off           disable printing messages to console
 -d, --show-delta            show time delta between printed messages
 -e, --reltime               show local time and time delta in readable format
 -E, --console-on            enable printing messages to console
 -F, --file <file>           use the file instead of the kernel log buffer
 -f, --facility <list>       restrict output to defined facilities
 -H, --human                 human readable output
 -k, --kernel                display kernel messages
 -L, --color                 colorize messages
 -l, --level <list>          restrict output to defined levels
 -n, --console-level <level> set level of messages printed to console
 -P, --nopager               do not pipe output into a pager
 -r, --raw                   print the raw message buffer
 -S, --syslog                force to use syslog(2) rather than /dev/kmsg
 -s, --buffer-size <size>    buffer size to query the kernel ring buffer
 -T, --ctime                 show human readable timestamp (could be 
                               inaccurate if you have used SUSPEND/RESUME)
 -t, --notime                don't print messages timestamp
 -u, --userspace             display userspace messages
 -w, --follow                wait for new messages
 -x, --decode                decode facility and level to readable string

 -h, --help     display this help and exit
 -V, --version  output version information and exit

Supported log facilities:
    kern - kernel messages
    user - random user-level messages
    mail - mail system
  daemon - system daemons
    auth - security/authorization messages
  syslog - messages generated internally by syslogd
     lpr - line printer subsystem
    news - network news subsystem

Supported log levels (priorities):
   emerg - system is unusable
   alert - action must be taken immediately
    crit - critical conditions
     err - error conditions
    warn - warning conditions
  notice - normal but significant condition
    info - informational
   debug - debug-level messages

For more details see dmesg(q).

==> kernel <==
 10:09:44 up 76 days, 18:34,  1 user,  load average: 0.00, 0.01, 0.05
Linux sundae 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

==> kubelet <==
-- No entries --

**The operating system version**:
CentOS 7.6.1810

**Added NOTE**
There is no /home/devans/.minikube/cache/images/ directory.  There is a /home/devans/.minikube/cache/v1.14.2/ that contains kubeadm and kubelet.  Kubectl and minikube were both installed using curl to get a Linux binary.

**Comment by tstromberg** [comment] 2019-05-24 17:24
The "none" driver currently requires sudo: https://github.com/kubernetes/minikube/blob/master/docs/vmdriver-none.md

**Comment by tstromberg** [comment] 2019-05-24 17:25
This issue appears to be a duplicate of #3760, so I will close this one so that we may centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please feel free to re-open it. 

Thank you for reporting this!

**Closed by tstromberg** 2019-05-24 17:25 UTC
