### ISSUE TITLE
Could not get the storage format of the medium 'boot2docker.iso' (VERR_NOT_SUPPORTED)

### ISSUE THREAD

**Issue by HeeZJee** [kubernetes/minikube#5039] opened 2019-08-10 15:47 UTC
😄  minikube v1.3.0 on Ubuntu 18.04
⚠️  Please don't run minikube as root or with 'sudo' privileges. It isn't necessary with virtualbox driver.
🔥  Creating virtualbox VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
E0810 20:44:35.296957   19123 start.go:723] StartHost: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/heezjee/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/heezjee/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/heezjee/.minikube/machines/minikube/boot2docker.iso"

💣  Unable to start VM: create: creating: /usr/bin/VBoxManage storageattach minikube --storagectl SATA --port 0 --device 0 --type dvddrive --medium /home/heezjee/.minikube/machines/minikube/boot2docker.iso failed:
VBoxManage: error: Could not get the storage format of the medium '/home/heezjee/.minikube/machines/minikube/boot2docker.iso' (VERR_NOT_SUPPORTED)
VBoxManage: error: Details: code VBOX_E_IPRT_ERROR (0x80bb0005), component MediumWrap, interface IMedium, callee nsISupports
VBoxManage: error: Context: "OpenMedium(Bstr(pszFilenameOrUuid).raw(), enmDevType, enmAccessMode, fForceNewUuidOnOpen, pMedium.asOutParam())" at line 179 of file VBoxManageDisk.cpp
VBoxManage: error: Invalid UUID or filename "/home/heezjee/.minikube/machines/minikube/boot2docker.iso"

**Comment by tstromberg** [comment] 2019-08-13 17:06
This appears to be a dupe of #4992 

Please do the following:

1. Run `minikube delete`
2. Run `rm -Rf ~/.minikube/cache/iso` (or the Windows equivalent)
3. Upgrade to minikube v1.3.1 - which fixes the download issue

Thank you for the bug report!

**Closed by tstromberg** 2019-08-13 17:06 UTC
