### ISSUE TITLE
Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver

### ISSUE THREAD

**Issue by wangcrazy1** [kubernetes/minikube#9251] opened 2020-09-15 01:57 UTC
**重现问题所需的命令**： minikube start --driver=vmwarefusion

**失败的命令的完整输出**：<details>
😄  minikube v1.13.0 on Darwin 10.14.5
✨  Using the vmwarefusion driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🏃  Updating the running vmwarefusion "minikube" VM ...
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
🐳  Preparing Kubernetes v1.19.0 on Docker 19.03.12 ...
    ▪ env NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.99.0/24,192.168.39.0/24
E0915 09:52:49.731178   98183 start.go:99] Unable to get host IP: HostIP not yet implemented for "vmwarefusion" driver

❌  Exiting due to GUEST_START: Failed to setup kubeconfig: HostIP not yet implemented for "vmwarefusion" driver

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**`minikube logs`命令的输出**： <details>
==> Docker <==
-- Logs begin at Mon 2020-09-14 16:23:16 UTC, end at Tue 2020-09-15 01:55:48 UTC. --
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.321817882Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.native"..." type=io.containerd.snapshotter.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.322174735Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.overlayfs"..." type=io.containerd.snapshotter.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.322479345Z" level=info msg="loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.322901831Z" level=info msg="skip loading plugin "io.containerd.snapshotter.v1.zfs"..." type=io.containerd.snapshotter.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.322974704Z" level=info msg="loading plugin "io.containerd.metadata.v1.bolt"..." type=io.containerd.metadata.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.323027166Z" level=warning msg="could not use snapshotter btrfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.btrfs must be a btrfs filesystem to be used with the btrfs snapshotter"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.323071484Z" level=warning msg="could not use snapshotter aufs in metadata plugin" error="modprobe aufs failed: "modprobe: FATAL: Module aufs not found in directory /lib/modules/4.19.114\n": exit status 1"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.323112605Z" level=warning msg="could not use snapshotter zfs in metadata plugin" error="path /var/lib/docker/containerd/daemon/io.containerd.snapshotter.v1.zfs must be a zfs filesystem to be used with the zfs snapshotter: skip plugin"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.323888802Z" level=info msg="loading plugin "io.containerd.differ.v1.walking"..." type=io.containerd.differ.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.323962730Z" level=info msg="loading plugin "io.containerd.gc.v1.scheduler"..." type=io.containerd.gc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324387860Z" level=info msg="loading plugin "io.containerd.service.v1.containers-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324453787Z" level=info msg="loading plugin "io.containerd.service.v1.content-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324501416Z" level=info msg="loading plugin "io.containerd.service.v1.diff-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324568610Z" level=info msg="loading plugin "io.containerd.service.v1.images-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324630492Z" level=info msg="loading plugin "io.containerd.service.v1.leases-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324684590Z" level=info msg="loading plugin "io.containerd.service.v1.namespaces-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324735964Z" level=info msg="loading plugin "io.containerd.service.v1.snapshots-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324785654Z" level=info msg="loading plugin "io.containerd.runtime.v1.linux"..." type=io.containerd.runtime.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324884658Z" level=info msg="loading plugin "io.containerd.runtime.v2.task"..." type=io.containerd.runtime.v2
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.324965634Z" level=info msg="loading plugin "io.containerd.monitor.v1.cgroups"..." type=io.containerd.monitor.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.325645134Z" level=info msg="loading plugin "io.containerd.service.v1.tasks-service"..." type=io.containerd.service.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.325717961Z" level=info msg="loading plugin "io.containerd.internal.v1.restart"..." type=io.containerd.internal.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.325984104Z" level=info msg="loading plugin "io.containerd.grpc.v1.containers"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326062003Z" level=info msg="loading plugin "io.containerd.grpc.v1.content"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326120363Z" level=info msg="loading plugin "io.containerd.grpc.v1.diff"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326194138Z" level=info msg="loading plugin "io.containerd.grpc.v1.events"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326474537Z" level=info msg="loading plugin "io.containerd.grpc.v1.healthcheck"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326542498Z" level=info msg="loading plugin "io.containerd.grpc.v1.images"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326631410Z" level=info msg="loading plugin "io.containerd.grpc.v1.leases"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326685034Z" level=info msg="loading plugin "io.containerd.grpc.v1.namespaces"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326733084Z" level=info msg="loading plugin "io.containerd.internal.v1.opt"..." type=io.containerd.internal.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.326806390Z" level=info msg="loading plugin "io.containerd.grpc.v1.snapshots"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.327106289Z" level=info msg="loading plugin "io.containerd.grpc.v1.tasks"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.327234124Z" level=info msg="loading plugin "io.containerd.grpc.v1.version"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.327288159Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.328538008Z" level=info msg=serving... address="/var/run/docker/containerd/containerd-debug.sock"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.328656739Z" level=info msg=serving... address="/var/run/docker/containerd/containerd.sock"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.328714869Z" level=info msg="containerd successfully booted in 0.015659s"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.348638494Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.348681507Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.348702994Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.348717117Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.351523366Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.351642550Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.351715560Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///var/run/docker/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.351782897Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399470399Z" level=warning msg="Your kernel does not support cgroup blkio weight"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399519257Z" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399550323Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_bps_device"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399556448Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_bps_device"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399565165Z" level=warning msg="Your kernel does not support cgroup blkio throttle.read_iops_device"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.399570742Z" level=warning msg="Your kernel does not support cgroup blkio throttle.write_iops_device"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.400404632Z" level=info msg="Loading containers: start."
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.517602274Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.552882282Z" level=info msg="Loading containers: done."
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.606831923Z" level=info msg="Docker daemon" commit=48a66213fe graphdriver(s)=overlay2 version=19.03.12
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.606962760Z" level=info msg="Daemon has completed initialization"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.624533242Z" level=info msg="API listen on /var/run/docker.sock"
Sep 15 01:52:47 minikube dockerd[6161]: time="2020-09-15T01:52:47.624634436Z" level=info msg="API listen on [::]:2376"
Sep 15 01:52:47 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2020-09-15T01:55:51Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0915 09:55:51.820911   98252 logs.go:181] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.19.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.19.0/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"

==> dmesg <==
[Sep14 21:33] You have booted with nomodeset. This means your GPU drivers are DISABLED
[  +0.000001] Any video related functionality will be severely degraded, and you may not even be able to suspend the system properly
[  +0.000000] Unless you actually understand what nomodeset does, you should reboot without enabling it
[  +0.677306] core: CPUID marked event: 'cpu cycles' unavailable
[  +0.000001] core: CPUID marked event: 'instructions' unavailable
[  +0.000000] core: CPUID marked event: 'bus cycles' unavailable
[  +0.000001] core: CPUID marked event: 'cache references' unavailable
[  +0.000000] core: CPUID marked event: 'cache misses' unavailable
[  +0.000000] core: CPUID marked event: 'branch instructions' unavailable
[  +0.000000] core: CPUID marked event: 'branch misses' unavailable
[  +0.016918] pmd_set_huge: Cannot satisfy [mem 0xf0000000-0xf0200000] with a huge-page mapping due to MTRR override.
[  +8.638066] sd 0:0:0:0: [sda] Assuming drive cache: write through
[  +0.152050] platform regulatory.0: Direct firmware load for regulatory.db failed with error -2
[  +5.425968] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[  +0.018448] systemd-fstab-generator[2603]: Ignoring "noauto" for root device
[  +0.004559] systemd[1]: File /usr/lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[  +0.000002] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[  +1.598620] NFSD: the nfsdcld client tracking upcall will be removed in 3.10. Please transition to using nfsdcltrack.
[  +0.359425] vboxguest: loading out-of-tree module taints kernel.
[  +0.003582] vboxguest: PCI device not found, probably running on physical hardware.
[  +8.923768] systemd-fstab-generator[4722]: Ignoring "noauto" for root device
[  +0.122119] systemd-fstab-generator[4732]: Ignoring "noauto" for root device
[Sep14 21:35] NFSD: Unable to end grace period: -110
[Sep14 21:37] systemd-fstab-generator[4914]: Ignoring "noauto" for root device
[Sep14 22:02] systemd-fstab-generator[5050]: Ignoring "noauto" for root device
[Sep15 00:07] hrtimer: interrupt took 6068554 ns
[Sep15 00:14] systemd-fstab-generator[5188]: Ignoring "noauto" for root device
[  +1.407228] kauditd_printk_skb: 65 callbacks suppressed
[  +0.216775] systemd-fstab-generator[5348]: Ignoring "noauto" for root device
[Sep15 01:31] systemd-fstab-generator[5469]: Ignoring "noauto" for root device
[ +17.428261] systemd-fstab-generator[5583]: Ignoring "noauto" for root device
[ +22.426663] systemd-fstab-generator[5698]: Ignoring "noauto" for root device
[Sep15 01:33] systemd-fstab-generator[5814]: Ignoring "noauto" for root device
[Sep15 01:35] systemd-fstab-generator[5928]: Ignoring "noauto" for root device
[Sep15 01:44] systemd-fstab-generator[6045]: Ignoring "noauto" for root device
[Sep15 01:55] systemd-fstab-generator[6137]: Ignoring "noauto" for root device
[  +0.083835] systemd-fstab-generator[6147]: Ignoring "noauto" for root device
[  +1.602659] kauditd_printk_skb: 107 callbacks suppressed
[  +2.137710] systemd-fstab-generator[6336]: Ignoring "noauto" for root device

==> kernel <==
 01:55:52 up  4:22,  0 users,  load average: 0.00, 0.02, 0.00
Linux minikube 4.19.114 #1 SMP Wed Sep 2 16:52:19 PDT 2020 x86_64 GNU/Linux
PRETTY_NAME="Buildroot 2019.02.11"

==> kubelet <==
-- Logs begin at Mon 2020-09-14 16:23:16 UTC, end at Tue 2020-09-15 01:55:52 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes

</details>

**使用的操作系统版本**：
Macos Majave 10.14.5

**Comment by sharifelgamal** [comment] 2020-09-15 23:31
不建议使用vmwarefusion驱动程序，请改用vmware驱动程序。我们应该有比这更好的错误消息。
---
The vmwarefusion driver is deprecated, try the vmware driver instead. We should have a better error message than this though.

**Comment by tstromberg** [comment] 2020-10-07 02:32
Duplicate of #8374

**Closed by tstromberg** 2020-10-07 02:32 UTC
Labels: kind/support, l/zh-CN, priority/awaiting-more-evidence
