### ISSUE TITLE
waiting for apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by saurabharora80** [kubernetes/minikube#5597] opened 2019-10-11 13:51 UTC
**The exact command to reproduce the issue**:
minikube start

**The full output of the command that failed**:<details>
minikube v1.4.0 on Darwin 10.14.6
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.0 on Docker 18.09.9 ...
🔄  Relaunching Kubernetes using kubeadm ... 

💣  Error restarting cluster: waiting for apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager [9d295b0acd6e]:
    error: no obje label ==
    error: no == Kubernetes addobjects passed toon reconcile completed at 2019-10-11T12:38:24+00:00 apply
    error: no obje019-10-11T12:38:27+00:00 ==

</details>

**The output of the `minikube logs` command**:<details>
==> kubelet <==
-- Logs begin at Fri 2019-10-11 10:08:12 UTC, end at Fri 2019-10-11 13:49:48 UTC. --
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.376701   15525 server.go:1065] Started kubelet
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.376892   15525 server.go:145] Starting to listen on 0.0.0.0:10250
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.378103   15525 server.go:354] Adding debug handlers to kubelet server.
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.379504   15525 kubelet.go:1302] Image garbage collection failed once. Stats initialization may not have completed yet: failed to get imageFs info: unable to find data in memory cache
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.381721   15525 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.381781   15525 status_manager.go:156] Starting to sync pod status with apiserver
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.381795   15525 kubelet.go:1822] Starting kubelet main sync loop.
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.382206   15525 kubelet.go:1839] skipping pod synchronization - [container runtime status check may not have completed yet, PLEG is not healthy: pleg has yet to be successful]
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.386137   15525 volume_manager.go:249] Starting Kubelet Volume Manager
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.391487   15525 desired_state_of_world_populator.go:131] Desired state populator starts to run
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.484006   15525 kubelet.go:1839] skipping pod synchronization - container runtime status check may not have completed yet
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.490154   15525 kubelet_node_status.go:286] Setting node annotation to enable volume controller attach/detach
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.497213   15525 kubelet_node_status.go:72] Attempting to register node minikube
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.513603   15525 kubelet_node_status.go:114] Node minikube was previously registered
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.515218   15525 kubelet_node_status.go:75] Successfully registered node minikube
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.521334   15525 setters.go:539] Node became not ready: {Type:Ready Status:False LastHeartbeatTime:2019-10-11 12:29:19.5213183 +0000 UTC m=+5.440866375 LastTransitionTime:2019-10-11 12:29:19.5213183 +0000 UTC m=+5.440866375 Reason:KubeletNotReady Message:container runtime status check may not have completed yet}
Oct 11 12:29:19 minikube kubelet[15525]: W1011 12:29:19.555367   15525 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-5644d7b6d9-flpqg through plugin: invalid network status for
Oct 11 12:29:19 minikube kubelet[15525]: W1011 12:29:19.583959   15525 docker_sandbox.go:394] failed to read pod IP from plugin/docker: Couldn't find network status for kube-system/coredns-5644d7b6d9-wzphn through plugin: invalid network status for
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.628859   15525 cpu_manager.go:161] [cpumanager] starting with none policy
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.628997   15525 cpu_manager.go:162] [cpumanager] reconciling every 10s
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.629039   15525 policy_none.go:42] [cpumanager] none policy: Start
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.635060   15525 plugin_manager.go:116] Starting Kubelet Plugin Manager
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.697619   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/c18ee741ac4ad7b2bfda7d88116f3047-kubeconfig") pod "kube-scheduler-minikube" (UID: "c18ee741ac4ad7b2bfda7d88116f3047")
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.707676   15525 kubelet.go:1664] Failed creating a mirror pod for "kube-addon-manager-minikube_kube-system(c3e29047da86ce6690916750ab69c40b)": pods "kube-addon-manager-minikube" already exists
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.710165   15525 kubelet.go:1664] Failed creating a mirror pod for "kube-scheduler-minikube_kube-system(c18ee741ac4ad7b2bfda7d88116f3047)": pods "kube-scheduler-minikube" already exists
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.710844   15525 kubelet.go:1664] Failed creating a mirror pod for "etcd-minikube_kube-system(d49369ff2d367c2df350b5a43d5711f6)": pods "etcd-minikube" already exists
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.719902   15525 kubelet.go:1664] Failed creating a mirror pod for "kube-apiserver-minikube_kube-system(d507513a415ee72bdbd9a4a95a658047)": pods "kube-apiserver-minikube" already exists
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.740853   15525 kubelet.go:1647] Trying to delete pod kube-controller-manager-minikube_kube-system 0bc3ef8a-e433-42f8-ba7e-60838b6de7d7
Oct 11 12:29:19 minikube kubelet[15525]: E1011 12:29:19.790665   15525 kubelet.go:1664] Failed creating a mirror pod for "kube-controller-manager-minikube_kube-system(38d78cbd438e068d417c11c848b26f09)": pods "kube-controller-manager-minikube" already exists
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798075   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/d507513a415ee72bdbd9a4a95a658047-ca-certs") pod "kube-apiserver-minikube" (UID: "d507513a415ee72bdbd9a4a95a658047")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798196   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "ca-certs" (UniqueName: "kubernetes.io/host-path/1c6c9b6af7527fe2935b9ed4fe29c4b2-ca-certs") pod "kube-controller-manager-minikube" (UID: "1c6c9b6af7527fe2935b9ed4fe29c4b2")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798239   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-certs" (UniqueName: "kubernetes.io/host-path/d49369ff2d367c2df350b5a43d5711f6-etcd-certs") pod "etcd-minikube" (UID: "d49369ff2d367c2df350b5a43d5711f6")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798310   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "etcd-data" (UniqueName: "kubernetes.io/host-path/d49369ff2d367c2df350b5a43d5711f6-etcd-data") pod "etcd-minikube" (UID: "d49369ff2d367c2df350b5a43d5711f6")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798329   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy" (UniqueName: "kubernetes.io/configmap/31f28598-91f9-4132-9915-5cc2e56e4781-kube-proxy") pod "kube-proxy-jcrjf" (UID: "31f28598-91f9-4132-9915-5cc2e56e4781")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798343   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/31f28598-91f9-4132-9915-5cc2e56e4781-xtables-lock") pod "kube-proxy-jcrjf" (UID: "31f28598-91f9-4132-9915-5cc2e56e4781")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798457   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/31f28598-91f9-4132-9915-5cc2e56e4781-lib-modules") pod "kube-proxy-jcrjf" (UID: "31f28598-91f9-4132-9915-5cc2e56e4781")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798511   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/d507513a415ee72bdbd9a4a95a658047-usr-share-ca-certificates") pod "kube-apiserver-minikube" (UID: "d507513a415ee72bdbd9a4a95a658047")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798530   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "addons" (UniqueName: "kubernetes.io/host-path/c3e29047da86ce6690916750ab69c40b-addons") pod "kube-addon-manager-minikube" (UID: "c3e29047da86ce6690916750ab69c40b")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798546   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-94w4s" (UniqueName: "kubernetes.io/secret/7998644d-5117-4472-a9d1-064bfa790410-coredns-token-94w4s") pod "coredns-5644d7b6d9-flpqg" (UID: "7998644d-5117-4472-a9d1-064bfa790410")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798562   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/1ed01024-8908-42a9-a50e-29b5d75be262-config-volume") pod "coredns-5644d7b6d9-wzphn" (UID: "1ed01024-8908-42a9-a50e-29b5d75be262")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798576   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "coredns-token-94w4s" (UniqueName: "kubernetes.io/secret/1ed01024-8908-42a9-a50e-29b5d75be262-coredns-token-94w4s") pod "coredns-5644d7b6d9-wzphn" (UID: "1ed01024-8908-42a9-a50e-29b5d75be262")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798589   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "tmp" (UniqueName: "kubernetes.io/host-path/3232e3f0-b803-42fd-9755-b83668556627-tmp") pod "storage-provisioner" (UID: "3232e3f0-b803-42fd-9755-b83668556627")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798627   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "storage-provisioner-token-46dlg" (UniqueName: "kubernetes.io/secret/3232e3f0-b803-42fd-9755-b83668556627-storage-provisioner-token-46dlg") pod "storage-provisioner" (UID: "3232e3f0-b803-42fd-9755-b83668556627")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798681   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/1c6c9b6af7527fe2935b9ed4fe29c4b2-kubeconfig") pod "kube-controller-manager-minikube" (UID: "1c6c9b6af7527fe2935b9ed4fe29c4b2")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798701   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "usr-share-ca-certificates" (UniqueName: "kubernetes.io/host-path/1c6c9b6af7527fe2935b9ed4fe29c4b2-usr-share-ca-certificates") pod "kube-controller-manager-minikube" (UID: "1c6c9b6af7527fe2935b9ed4fe29c4b2")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798716   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/d507513a415ee72bdbd9a4a95a658047-k8s-certs") pod "kube-apiserver-minikube" (UID: "d507513a415ee72bdbd9a4a95a658047")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798729   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kubeconfig" (UniqueName: "kubernetes.io/host-path/c3e29047da86ce6690916750ab69c40b-kubeconfig") pod "kube-addon-manager-minikube" (UID: "c3e29047da86ce6690916750ab69c40b")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798744   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "kube-proxy-token-lnkbn" (UniqueName: "kubernetes.io/secret/31f28598-91f9-4132-9915-5cc2e56e4781-kube-proxy-token-lnkbn") pod "kube-proxy-jcrjf" (UID: "31f28598-91f9-4132-9915-5cc2e56e4781")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798760   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "flexvolume-dir" (UniqueName: "kubernetes.io/host-path/1c6c9b6af7527fe2935b9ed4fe29c4b2-flexvolume-dir") pod "kube-controller-manager-minikube" (UID: "1c6c9b6af7527fe2935b9ed4fe29c4b2")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798773   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "k8s-certs" (UniqueName: "kubernetes.io/host-path/1c6c9b6af7527fe2935b9ed4fe29c4b2-k8s-certs") pod "kube-controller-manager-minikube" (UID: "1c6c9b6af7527fe2935b9ed4fe29c4b2")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798821   15525 reconciler.go:207] operationExecutor.VerifyControllerAttachedVolume started for volume "config-volume" (UniqueName: "kubernetes.io/configmap/7998644d-5117-4472-a9d1-064bfa790410-config-volume") pod "coredns-5644d7b6d9-flpqg" (UID: "7998644d-5117-4472-a9d1-064bfa790410")
Oct 11 12:29:19 minikube kubelet[15525]: I1011 12:29:19.798829   15525 reconciler.go:154] Reconciler: start to sync state
Oct 11 12:29:20 minikube kubelet[15525]: W1011 12:29:20.600692   15525 pod_container_deletor.go:75] Container "2b24df6d556bd84c9b8dc1ca4b45ddd09ae64bf2dc27800fc6ff061d181e9e7c" not found in pod's containers
Oct 11 12:29:20 minikube kubelet[15525]: W1011 12:29:20.761645   15525 prober.go:108] No ref for container "docker://c0c5330acb8ba2fcbf9bfcb618c55e49ffff8474b206c9fc1dce9ae3f4ba1055" (kube-controller-manager-minikube_kube-system(38d78cbd438e068d417c11c848b26f09):kube-controller-manager)
Oct 11 12:29:20 minikube kubelet[15525]: E1011 12:29:20.921865   15525 secret.go:198] Couldn't get secret kube-system/storage-provisioner-token-46dlg: failed to sync secret cache: timed out waiting for the condition
Oct 11 12:29:20 minikube kubelet[15525]: E1011 12:29:20.921981   15525 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/secret/3232e3f0-b803-42fd-9755-b83668556627-storage-provisioner-token-46dlg\" (\"3232e3f0-b803-42fd-9755-b83668556627\")" failed. No retries permitted until 2019-10-11 12:29:21.421950091 +0000 UTC m=+7.341498173 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"storage-provisioner-token-46dlg\" (UniqueName: \"kubernetes.io/secret/3232e3f0-b803-42fd-9755-b83668556627-storage-provisioner-token-46dlg\") pod \"storage-provisioner\" (UID: \"3232e3f0-b803-42fd-9755-b83668556627\") : failed to sync secret cache: timed out waiting for the condition"
Oct 11 12:29:21 minikube kubelet[15525]: W1011 12:29:21.196590   15525 kubelet.go:1651] Deleted mirror pod "kube-controller-manager-minikube_kube-system(0bc3ef8a-e433-42f8-ba7e-60838b6de7d7)" because it is outdated
Oct 11 12:29:21 minikube kubelet[15525]: W1011 12:29:21.409199   15525 kubelet_getters.go:292] Path "/var/lib/kubelet/pods/38d78cbd438e068d417c11c848b26f09/volumes" does not exist
Oct 11 12:31:22 minikube kubelet[15525]: E1011 12:31:22.791304   15525 kubelet.go:1682] Unable to attach or mount volumes for pod "kube-controller-manager-minikube_kube-system(38d78cbd438e068d417c11c848b26f09)": unmounted volumes=[ca-certs k8s-certs kubeconfig usr-share-ca-certificates], unattached volumes=[ca-certs k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition; skipping pod
Oct 11 12:31:22 minikube kubelet[15525]: E1011 12:31:22.791375   15525 pod_workers.go:191] Error syncing pod 38d78cbd438e068d417c11c848b26f09 ("kube-controller-manager-minikube_kube-system(38d78cbd438e068d417c11c848b26f09)"), skipping: unmounted volumes=[ca-certs k8s-certs kubeconfig usr-share-ca-certificates], unattached volumes=[ca-certs k8s-certs kubeconfig usr-share-ca-certificates]: timed out waiting for the condition

</details>

**The operating system version**:
MacOS Majave 10.14.16

**Comment by tstromberg** [comment] 2019-10-21 21:37
This issue appears to be a duplicate of #4540, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2019-10-21 21:37 UTC
