### ISSUE TITLE
minikube fails to start with extra-config=kubelet.max-pods=5

### ISSUE THREAD

**Issue by robertvoliva** [kubernetes/minikube#3632] opened 2019-02-05 22:28 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
BUG REPORT

Please provide the following details:

**Environment**:

minikube version: v0.32.0

OS:

NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

VM driver:
~/.minikube/machines/minikube/config.json doesn't exist, machine isn't created due to issue

ISO version
~/.minikube/machines/minikube/config.json doesn't exist, machine isn't created due to issue

**What happened**:
Command: 
minikube start --extra-config=kubelet.max-pods=5
It hangs on this output:

Starting local Kubernetes v1.12.4 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Stopping extra container runtimes...
Starting cluster components...

and then eventually errors out - usually with this RBAC error:
E0205 16:25:19.743682    3910 start.go:343] Error starting cluster:  timed out waiting to elevate kube-system RBAC privileges: Temporary Error: creating clusterrolebinding: Post https://192.168.99.100:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?timeout=1m0s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
creating clusterrolebinding: Post https://192.168.99.100:8443/apis/rbac.authorization.k8s.io/v1beta1/clusterrolebindings?timeout=1m0s: dial tcp 192.168.99.100:8443: connect: connection refused

**What you expected to happen**:
Minikube to be up and running

**How to reproduce it** (as minimally and precisely as possible):
minikube start --extra-config=kubelet.max-pods=5

**Output of `minikube logs` (if applicable)**:
The logs are pretty full, but is the bottom few lines from the logs:
Feb 05 22:26:26 minikube kubelet[3258]: E0205 22:26:26.923057    3258 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: dial tcp 127.0.0.1:8443: connect: connection refused
Feb 05 22:26:37 minikube kubelet[3258]: E0205 22:26:37.125236    3258 reflector.go:134] object-"kube-system"/"kube-proxy-token-rmndg": Failed to list *v1.Secret: Get https://localhost:8443/api/v1/namespaces/kube-system/secrets?fieldSelector=metadata.name%3Dkube-proxy-token-rmndg&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Feb 05 22:26:37 minikube kubelet[3258]: E0205 22:26:37.377507    3258 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:451: Failed to list *v1.Node: Get https://localhost:8443/api/v1/nodes?fieldSelector=metadata.name%3Dminikube&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Feb 05 22:26:37 minikube kubelet[3258]: E0205 22:26:37.524155    3258 reflector.go:134] object-"kube-system"/"kube-proxy": Failed to list *v1.ConfigMap: Get https://localhost:8443/api/v1/namespaces/kube-system/configmaps?fieldSelector=metadata.name%3Dkube-proxy&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Feb 05 22:26:37 minikube kubelet[3258]: E0205 22:26:37.725241    3258 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://localhost:8443/api/v1/pods?fieldSelector=spec.nodeName%3Dminikube&limit=500&resourceVersion=0: net/http: TLS handshake timeout
Feb 05 22:26:37 minikube kubelet[3258]: E0205 22:26:37.925856    3258 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:442: Failed to list *v1.Service: Get https://localhost:8443/api/v1/services?limit=500&resourceVersion=0: net/http: TLS handshake timeout
Feb 05 22:26:38 minikube kubelet[3258]: W0205 22:26:38.127505    3258 status_manager.go:485] Failed to get status for pod "kube-apiserver-minikube_kube-system(f331044f1da489c1e5b819d8751b46b6)": Get https://localhost:8443/api/v1/namespaces/kube-system/pods/kube-apiserver-minikube: net/http: TLS handshake timeout
Feb 05 22:26:38 minikube kubelet[3258]: E0205 22:26:38.326204    3258 kubelet.go:1637] Failed creating a mirror pod for "kube-apiserver-minikube_kube-system(f331044f1da489c1e5b819d8751b46b6)": Post https://localhost:8443/api/v1/namespaces/kube-system/pods: net/http: TLS handshake timeout
Feb 05 22:26:40 minikube kubelet[3258]: E0205 22:26:40.479966    3258 event.go:212] Unable to write event: 'Post https://localhost:8443/api/v1/namespaces/kube-system/events: net/http: TLS handshake timeout' (may retry after sleeping)
Feb 05 22:26:40 minikube kubelet[3258]: E0205 22:26:40.480076    3258 event.go:147] Unable to write event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"etcd-minikube.158098033c799e72", GenerateName:"", Namespace:"kube-system", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Initializers:(*v1.Initializers)(nil), Finalizers:[]string(nil), ClusterName:""}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"kube-system", Name:"etcd-minikube", UID:"400930335566057521570dcbaf3dbb0b", APIVersion:"v1", ResourceVersion:"", FieldPath:"spec.containers{etcd}"}, Reason:"Killing", Message:"Killing container with id docker://etcd:Need to kill Pod", Source:v1.EventSource{Component:"kubelet", Host:"minikube"}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbf0ea118dcc08072, ext:33454596494, loc:(*time.Location)(0x65b5120)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbf0ea118dcc08072, ext:33454596494, loc:(*time.Location)(0x65b5120)}}, Count:1, Type:"Normal", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}' (retry limit exceeded!)
Feb 05 22:26:44 minikube kubelet[3258]: E0205 22:26:44.343173    3258 kubelet_node_status.go:377] Error updating node status, will retry: error getting node "minikube": Get https://localhost:8443/api/v1/nodes/minikube?resourceVersion=0&timeout=10s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Anything else do we need to know**:
Doing a "minikube start" without the "--extra-config" works fine.  I've tried a few of the kubelet properties, and they all produce the same result.  The particular property that I'm really looking to set is the "kubelet.streaming-connection-idle-timeout" property, but I thought I'd try something simple like max-pods in case the one I wanted wasn't supported.

**Comment by tstromberg** [comment] 2019-02-05 23:41
Probably a dupe of #3532

**Comment by robertvoliva** [comment] 2019-02-05 23:51
> Probably a dupe of #3532

Thanks.  If that's the case, what do you think the invalid/incompatible flag is?  Also, I ran the command you recommended in that issue but it didn't produce any output:

:~$ minikube ssh 'docker logs $(docker ps -a -f name=k8s_kube-api --format={{.ID}})' | egrep -i 'error:|fatal:'
:~$

**Comment by tstromberg** [comment] 2019-02-20 00:49
Do you mind trying again with minikube v0.34.1? I haven't been able to replicate the issue:

```
%  minikube start --extra-config=kubelet.max-pods=5  --vm-driver=kvm2                                                               
😄  minikube v0.34.1 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
📶  "minikube" IP address is 192.168.39.129
🌐  Found network options:
    ▪ NO_PROXY=localhost,127.0.0.1,10.96.0.0/12,192.168.0.0/16
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ kubelet.max-pods=5
🚜  Pulling images required by Kubernetes v1.13.3 ...
🚀  Launching Kubernetes v1.13.3 using kubeadm ... 
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```

**Comment by robertvoliva** [comment] 2019-03-18 14:55
minikube (v0.35.0) won't start with any "extra-config" options.  I tried with & without the cpu & memory settings, thinking the VM maybe needed more resources to start/initialize the api server.

```
rvoliva@madcrmv5s2922q6:~$ minikube stop
✋  Stopping "minikube" in kvm2 ...
🛑  "minikube" stopped.
rvoliva@madcrmv5s2922q6:~$ minikube delete
🔥  Deleting "minikube" from kvm2 ...
💔  The "minikube" cluster has been deleted.
rvoliva@madcrmv5s2922q6:~$ rm -rf .minikube/
rvoliva@madcrmv5s2922q6:~$ minikube start --extra-config=kubelet.max-pods=5 --cpus=4 --memory=8192 --vm-driver=kvm2
😄  minikube v0.35.0 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.39.21
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
    ▪ kubelet.max-pods=5
💾  Downloading kubeadm v1.13.4
💾  Downloading kubelet v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver💣  Error starting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
```
If I do the exact same process without the extra-config options, it starts up just fine:

```
rvoliva@madcrmv5s2922q6:~$ minikube stop
✋  Stopping "minikube" in kvm2 ...
🛑  "minikube" stopped.
rvoliva@madcrmv5s2922q6:~$ minikube delete
🔥  Deleting "minikube" from kvm2 ...
💔  The "minikube" cluster has been deleted.
rvoliva@madcrmv5s2922q6:~$ rm -rf .minikube/
rvoliva@madcrmv5s2922q6:~$ minikube start --cpus=4 --memory=8192 --vm-driver=kvm2
😄  minikube v0.35.0 on linux (amd64)
🔥  Creating kvm2 VM (CPUs=4, Memory=8192MB, Disk=20000MB) ...
💿  Downloading Minikube ISO ...
 184.42 MB / 184.42 MB [============================================] 100.00% 0s
📶  "minikube" IP address is 192.168.39.191
🐳  Configuring Docker as the container runtime ...
✨  Preparing Kubernetes environment ...
💾  Downloading kubeadm v1.13.4
💾  Downloading kubelet v1.13.4
🚜  Pulling images required by Kubernetes v1.13.4 ...
🚀  Launching Kubernetes v1.13.4 using kubeadm ... 
⌛  Waiting for pods: apiserver proxy etcd scheduler controller addon-manager dns
🔑  Configuring cluster permissions ...
🤔  Verifying component health .....
💗  kubectl is now configured to use "minikube"
🏄  Done! Thank you for using minikube!
```

**Comment by tstromberg** [comment] 2019-05-23 00:05
I believe the problem here is that minikube requires more than 5 pods to start up successfully. Setting the value to `--extra-config=kubelet.max-pods=10` works, although for instance, the addons I have refuse to startup because it exceeds the selected pod count:

```
 kubectl get pods --all-namespaces --show-labels            2.8m  Wed 22 May 2019 05:03:34 PM PDT
NAMESPACE     NAME                                    READY   STATUS      RESTARTS   AGE     LABELS
default       busybox                                 1/1     Running     0          2m21s   <none>
default       busybox-68977b4474-kkkp7                0/1     Pending     0          55s     pod-template-hash=68977b4474,run=busybox
kube-system   coredns-fb8b8dccf-lxvrd                 1/1     Running     0          2m22s   k8s-app=kube-dns,pod-template-hash=fb8b8dccf
kube-system   coredns-fb8b8dccf-mmgw2                 1/1     Running     0          2m22s   k8s-app=kube-dns,pod-template-hash=fb8b8dccf
kube-system   etcd-minikube                           1/1     Running     0          74s     component=etcd,tier=control-plane
kube-system   gvisor                                  0/1     OutOfpods   0          2m21s   addonmanager.kubernetes.io/mode=Reconcile,kubernetes.io/minikube-addons=gvisor
kube-system   kube-addon-manager-minikube             1/1     Running     0          85s     component=kube-addon-manager,kubernetes.io/minikube-addons=addon-manager,version=v9.0
kube-system   kube-apiserver-minikube                 1/1     Running     0          81s     component=kube-apiserver,tier=control-plane
kube-system   kube-controller-manager-minikube        1/1     Running     0          64s     component=kube-controller-manager,tier=control-plane
kube-system   kube-proxy-82wxw                        1/1     Running     0          2m21s   controller-revision-hash=6c5f45759d,k8s-app=kube-proxy,pod-template-generation=1
kube-system   kube-scheduler-minikube                 1/1     Running     0          81s     component=kube-scheduler,tier=control-plane
kube-system   kubernetes-dashboard-79dd6bfc48-trl8l   1/1     Running     0          2m21s   addonmanager.kubernetes.io/mode=Reconcile,app=kubernetes-dashboard,pod-template-hash=79dd6bfc48,version=v1.10.1
kube-system   storage-provisioner                     0/1     OutOfpods   0          2m20s   addonmanager.kubernetes.io/mode=Reconcile,integration-test=storage-provisioner
```

I'm going to leave this open, because it doesn't fail in a particularly graceful way.

**Comment by tstromberg** [comment] 2019-09-20 23:02
Closing, as there is a workaround: don't specify `pods=5`, as it's too small to run Kubernetes.

**Closed by tstromberg** 2019-09-20 23:02 UTC
Labels: co/kubelet, kind/bug, lifecycle/frozen, priority/awaiting-more-evidence, r/2019q2
