### ISSUE TITLE
minikube start failed to create vm with error "panic: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by q98027** [kubernetes/minikube#6428] opened 2020-01-29 23:30 UTC
**The exact command to reproduce the issue**:
 minikube start --vm-driver=hyperv

**The full output of the command that failed**:<details>
PS C:\windows\system32> minikube start --vm-driver=hyperv
! minikube v1.6.2 on Microsoft Windows 10 Enterprise 10.0.16299 Build 16299
* Selecting 'hyperv' driver from user configuration (alternates: [])
* Creating hyperv VM (CPUs=2, Memory=2000MB, Disk=20000MB) ...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x28 pc=0x12ee976]

goroutine 94 [running]:
github.com/google/go-containerregistry/pkg/v1/tarball.Write(0x0, 0x0, 0x0, 0xc0000357d0, 0x1c, 0xc0000357ed, 0x6, 0x0, 0x0, 0xc000025c58, ...)
        /go/pkg/mod/github.com/google/go-containerregistry@v0.0.0-20180731221751-697ee0b3d46e/pkg/v1/tarball/write.go:57 +0x136
k8s.io/minikube/pkg/minikube/machine.CacheImage(0xc0000357d0, 0x23, 0xc0005a9860, 0x4a, 0x0, 0x0)
        /app/pkg/minikube/machine/cache_images.go:395 +0x615
k8s.io/minikube/pkg/minikube/machine.CacheImages.func1(0xc0004a7f68, 0x0)
        /app/pkg/minikube/machine/cache_images.go:85 +0xed
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000478090, 0xc0004782a0)
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x6b
created by golang.org/x/sync/errgroup.(*Group).Go
        /go/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x6d

</details>

**The output of the `minikube logs` command**:<details>

</details>

**The operating system version**:
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.16299 N/A Build 16299
OS Manufacturer:           Microsoft Corporation

**Comment by sharifelgamal** [comment] 2020-02-05 19:47
This should be fixed with minikube 1.7, can you upgrade and retry?

Closing as a duplicate of #6147

**Closed by sharifelgamal** 2020-02-05 19:47 UTC
Labels: co/hyperv, os/windows, triage/support
