### ISSUE TITLE
minikube error on Amazon 2018.03 without systemd

### ISSUE THREAD

**Issue by yphulke** [kubernetes/minikube#8927] opened 2020-08-05 19:18 UTC
**Steps to reproduce the issue:** 
# minikube start --alsologtostderr
I0805 19:06:05.461636   20368 out.go:170] Setting JSON to false
I0805 19:06:05.462400   20368 start.go:101] hostinfo: {"hostname":"ip-10-229-19-113","uptime":97735,"bootTime":1596556630,"procs":143,"os":"linux","platform":"amazon","platformFamily":"rhel","platformVersion":"2018.03","kernelVersion":"4.14.186-110.268.amzn1.x86_64","virtualizationSystem":"vbox","virtualizationRole":"host","hostid":"ec239f47-e05a-3098-18f3-3bf3e358c6fd"}
I0805 19:06:05.462694   20368 start.go:111] virtualization: vbox host
😄  minikube v1.12.1 on Amazon 2018.03
I0805 19:06:05.465334   20368 driver.go:257] Setting default libvirt URI to qemu:///system
I0805 19:06:05.465620   20368 exec_runner.go:49] Run: systemctl --version
✨  Using the none driver based on existing profile
I0805 19:06:05.469166   20368 start.go:217] selected driver: none
I0805 19:06:05.469181   20368 start.go:621] validating driver "none" against &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2048 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.229.19.113 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
I0805 19:06:05.469289   20368 start.go:632] status for none: {Installed:true Healthy:true NeedsImprovement:false Error:<nil> Fix: Doc:}
I0805 19:06:05.469400   20368 start_flags.go:340] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:2048 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP:10.229.19.113 Port:8443 KubernetesVersion:v1.18.3 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]}
👍  Starting control plane node minikube in cluster minikube
I0805 19:06:05.471458   20368 profile.go:150] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0805 19:06:05.471615   20368 cache.go:178] Successfully downloaded all kic artifacts
I0805 19:06:05.471657   20368 start.go:241] acquiring machines lock for minikube: {Name:mka00e65579c2b557a802898fd1cf03ec4ab30a1 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0805 19:06:05.471998   20368 start.go:245] acquired machines lock for "minikube" in 174.764µs
I0805 19:06:05.472019   20368 start.go:89] Skipping create...Using existing machine configuration
I0805 19:06:05.472030   20368 fix.go:53] fixHost starting: m01
W0805 19:06:05.472201   20368 none.go:130] unable to get port: "minikube" does not appear in /root/.kube/config
I0805 19:06:05.472355   20368 api_server.go:146] Checking apiserver status ...
I0805 19:06:05.472390   20368 exec_runner.go:49] Run: sudo pgrep -xnf kube-apiserver.*minikube.*
W0805 19:06:05.480069   20368 api_server.go:150] stopped: unable to get apiserver pid: sudo pgrep -xnf kube-apiserver.*minikube.*: exit status 1
stdout:

stderr:
I0805 19:06:05.480091   20368 system_pods.go:161] Checking kubelet status ...
I0805 19:06:05.480124   20368 exec_runner.go:49] Run: sudo service kubelet status
I0805 19:06:05.494800   20368 fix.go:105] recreateIfNeeded on minikube: state=Stopped err=<nil>
W0805 19:06:05.494826   20368 fix.go:131] unexpected machine state, will restart: <nil>
🔄  Restarting existing none bare metal machine for "minikube" ...
I0805 19:06:05.499741   20368 profile.go:150] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0805 19:06:05.499850   20368 start.go:204] post-start starting for "minikube" (driver="none")
I0805 19:06:05.499864   20368 start.go:214] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0805 19:06:05.499911   20368 exec_runner.go:49] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0805 19:06:05.505761   20368 main.go:115] libmachine: Couldn't set key CPE_NAME, no corresponding struct field found
ℹ️  OS release is Amazon Linux AMI 2018.03
I0805 19:06:05.508153   20368 filesync.go:118] Scanning /root/.minikube/addons for local assets ...
I0805 19:06:05.508203   20368 filesync.go:118] Scanning /root/.minikube/files for local assets ...
I0805 19:06:05.508238   20368 start.go:207] post-start completed in 8.364764ms
I0805 19:06:05.508258   20368 fix.go:92] none is local, skipping auth/time setup (requires ssh)
I0805 19:06:05.508265   20368 fix.go:55] fixHost completed within 36.238615ms
I0805 19:06:05.508272   20368 start.go:76] releasing machines lock for "minikube", held for 36.259515ms
I0805 19:06:05.508789   20368 exec_runner.go:49] Run: sudo service containerd status
I0805 19:06:05.508860   20368 exec_runner.go:49] Run: curl -sS -m 2 https://k8s.gcr.io/
I0805 19:06:05.530538   20368 exec_runner.go:49] Run: sudo service docker status
I0805 19:06:05.561147   20368 exec_runner.go:49] Run: docker version --format {{.Server.Version}}
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.6-ce ...
I0805 19:06:05.636017   20368 exec_runner.go:49] Run: grep 127.0.0.1	host.minikube.internal$ /etc/hosts
I0805 19:06:05.637131   20368 preload.go:95] Checking if preload exists for k8s version v1.18.3 and runtime docker
I0805 19:06:05.637162   20368 preload.go:103] Found local preload: /root/.minikube/cache/preloaded-tarball/preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4
I0805 19:06:05.637212   20368 exec_runner.go:49] Run: docker images --format {{.Repository}}:{{.Tag}}
I0805 19:06:05.697858   20368 docker.go:381] Got preloaded images: 
I0805 19:06:05.697984   20368 docker.go:386] k8s.gcr.io/kube-proxy:v1.18.3 wasn't preloaded
I0805 19:06:05.698028   20368 exec_runner.go:49] Run: sudo cat /var/lib/docker/image/overlay2/repositories.json
I0805 19:06:05.705676   20368 exec_runner.go:49] Run: which lz4
I0805 19:06:05.706263   20368 kubeadm.go:748] prelaoding failed, will try to load cached images: lz4
I0805 19:06:05.706316   20368 exec_runner.go:49] Run: docker info --format {{.CgroupDriver}}
I0805 19:06:05.779221   20368 cni.go:74] Creating CNI manager for ""
I0805 19:06:05.779244   20368 cni.go:117] CNI unnecessary in this configuration, recommending no CNI
I0805 19:06:05.779254   20368 kubeadm.go:84] Using pod CIDR: 
I0805 19:06:05.779271   20368 kubeadm.go:150] kubeadm options: {CertDir:/var/lib/minikube/certs ServiceCIDR:10.96.0.0/12 PodSubnet: AdvertiseAddress:10.229.19.113 APIServerPort:8443 KubernetesVersion:v1.18.3 EtcdDataDir:/var/lib/minikube/etcd EtcdExtraArgs:map[] ClusterName:minikube NodeName:ip-10-229-19-113 DNSDomain:cluster.local CRISocket: ImageRepository: ComponentOptions:[{Component:apiServer ExtraArgs:map[enable-admission-plugins:NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota] Pairs:map[certSANs:["127.0.0.1", "localhost", "10.229.19.113"]]}] FeatureArgs:map[] NoTaintMaster:true NodeIP:10.229.19.113 CgroupDriver:cgroupfs ClientCAFile:/var/lib/minikube/certs/ca.crt StaticPodPath:/etc/kubernetes/manifests ControlPlaneAddress:control-plane.minikube.internal KubeProxyOptions:map[]}
I0805 19:06:05.779446   20368 kubeadm.go:154] kubeadm config:
apiVersion: kubeadm.k8s.io/v1beta2
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: 10.229.19.113
  bindPort: 8443
bootstrapTokens:
  - groups:
      - system:bootstrappers:kubeadm:default-node-token
    ttl: 24h0m0s
    usages:
      - signing
      - authentication
nodeRegistration:
  criSocket: /var/run/dockershim.sock
  name: "ip-10-229-19-113"
  kubeletExtraArgs:
    node-ip: 10.229.19.113
  taints: []
---
apiVersion: kubeadm.k8s.io/v1beta2
kind: ClusterConfiguration
apiServer:
  certSANs: ["127.0.0.1", "localhost", "10.229.19.113"]
  extraArgs:
    enable-admission-plugins: "NamespaceLifecycle,LimitRanger,ServiceAccount,DefaultStorageClass,DefaultTolerationSeconds,NodeRestriction,MutatingAdmissionWebhook,ValidatingAdmissionWebhook,ResourceQuota"
certificatesDir: /var/lib/minikube/certs
clusterName: mk
controlPlaneEndpoint: control-plane.minikube.internal:8443
dns:
  type: CoreDNS
etcd:
  local:
    dataDir: /var/lib/minikube/etcd
controllerManager:
  extraArgs:
    "leader-elect": "false"
scheduler:
  extraArgs:
    "leader-elect": "false"
kubernetesVersion: v1.18.3
networking:
  dnsDomain: cluster.local
  podSubnet: ""
  serviceSubnet: 10.96.0.0/12
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
authentication:
  x509:
    clientCAFile: /var/lib/minikube/certs/ca.crt
cgroupDriver: cgroupfs
clusterDomain: "cluster.local"
# disable disk resource management by default
imageGCHighThresholdPercent: 100
evictionHard:
  nodefs.available: "0%"
  nodefs.inodesFree: "0%"
  imagefs.available: "0%"
failSwapOn: false
staticPodPath: /etc/kubernetes/manifests
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
clusterCIDR: ""
metricsBindAddress: 10.229.19.113:10249

I0805 19:06:05.779588   20368 kubeadm.go:787] kubelet [Unit]
Wants=docker.socket

[Service]
ExecStart=
ExecStart=/var/lib/minikube/binaries/v1.18.3/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime=docker --hostname-override=ip-10-229-19-113 --kubeconfig=/etc/kubernetes/kubelet.conf --node-ip=10.229.19.113

[Install]
 config:
{KubernetesVersion:v1.18.3 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:}
I0805 19:06:05.779663   20368 exec_runner.go:49] Run: sudo ls /var/lib/minikube/binaries/v1.18.3
I0805 19:06:05.785636   20368 binaries.go:43] Found k8s binaries, skipping transfer
I0805 19:06:05.785782   20368 exec_runner.go:49] Run: sudo mkdir -p /etc/systemd/system/kubelet.service.d /lib/systemd/system /var/tmp/minikube /var/lib/minikube /etc/init.d
I0805 19:06:05.790692   20368 exec_runner.go:91] found /etc/systemd/system/kubelet.service.d/10-kubeadm.conf, removing ...
I0805 19:06:05.790757   20368 exec_runner.go:98] cp: memory --> /etc/systemd/system/kubelet.service.d/10-kubeadm.conf (343 bytes)
I0805 19:06:05.790833   20368 exec_runner.go:91] found /lib/systemd/system/kubelet.service, removing ...
I0805 19:06:05.790868   20368 exec_runner.go:98] cp: memory --> /lib/systemd/system/kubelet.service (349 bytes)
I0805 19:06:05.790920   20368 exec_runner.go:91] found /var/tmp/minikube/kubeadm.yaml.new, removing ...
I0805 19:06:05.791057   20368 exec_runner.go:98] cp: memory --> /var/tmp/minikube/kubeadm.yaml.new (1750 bytes)
I0805 19:06:05.791299   20368 exec_runner.go:91] found /var/lib/minikube/openrc-restart-wrapper.sh, removing ...
I0805 19:06:05.791337   20368 exec_runner.go:98] cp: memory --> /var/lib/minikube/openrc-restart-wrapper.sh (233 bytes)
I0805 19:06:05.791394   20368 exec_runner.go:91] found /etc/init.d/kubelet, removing ...
I0805 19:06:05.791425   20368 exec_runner.go:98] cp: memory --> /etc/init.d/kubelet (839 bytes)
I0805 19:06:05.791501   20368 exec_runner.go:49] Run: grep 10.229.19.113	control-plane.minikube.internal$ /etc/hosts
I0805 19:06:05.792624   20368 exec_runner.go:49] Run: sudo service kubelet status
I0805 19:06:05.807932   20368 exec_runner.go:49] Run: sudo service kubelet start
I0805 19:06:05.824078   20368 openrc.go:110] start output: 
** stderr ** 
/etc/init.d/kubelet: line 9: start-stop-daemon: command not found

** /stderr **
I0805 19:06:05.824187   20368 exit.go:58] WithError(Failed to update cluster)=updating control plane: sudo service kubelet start: exit status 127
stdout:

stderr:
/etc/init.d/kubelet: line 9: start-stop-daemon: command not found
 called from:
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
k8s.io/minikube/pkg/minikube/exit.WithError(0x1ba98b3, 0x18, 0x1eb8320, 0xc000931540)
	/app/pkg/minikube/exit/exit.go:58 +0x34
k8s.io/minikube/pkg/minikube/node.setupKubeAdm(0x1f180c0, 0xc000592480, 0xc00075a688, 0x8, 0x0, 0x0, 0x0, 0xc00041e3f0, 0x6b, 0x800, ...)
	/app/pkg/minikube/node/start.go:298 +0x50e
k8s.io/minikube/pkg/minikube/node.Start(0x1ef59a0, 0x2cff560, 0x1, 0x1f180c0, 0xc000592480, 0xc000769f80, 0xc000598000, 0xc000592280, 0xc000545380, 0xc000592401, ...)
	/app/pkg/minikube/node/start.go:112 +0x40b
k8s.io/minikube/cmd/minikube/cmd.startWithDriver(0x1ef59a0, 0x2cff560, 0x1, 0x1f180c0, 0xc000592480, 0xc000769f80, 0xc000598000, 0xc000592280, 0xc000545380, 0xc0004e4a80, ...)
	/app/cmd/minikube/cmd/start.go:283 +0x7c
k8s.io/minikube/cmd/minikube/cmd.runStart(0x2cb86a0, 0xc00004c2a0, 0x0, 0x1)
	/app/cmd/minikube/cmd/start.go:203 +0x3bf
github.com/spf13/cobra.(*Command).execute(0x2cb86a0, 0xc00004c290, 0x1, 0x1, 0x2cb86a0, 0xc00004c290)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x2cb76e0, 0x0, 0x1, 0xc0007875e0)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
k8s.io/minikube/cmd/minikube/cmd.Execute()
	/app/cmd/minikube/cmd/root.go:106 +0x72c
main.main()
	/app/cmd/minikube/main.go:71 +0x11f
W0805 19:06:05.824386   20368 out.go:232] Failed to update cluster: updating control plane: sudo service kubelet start: exit status 127
stdout:

stderr:
/etc/init.d/kubelet: line 9: start-stop-daemon: command not found

💣  Failed to update cluster: updating control plane: sudo service kubelet start: exit status 127
stdout:

stderr:
/etc/init.d/kubelet: line 9: start-stop-daemon: command not found

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by afbjorklund** [comment] 2020-08-05 19:36
Duplicate of #8333

**Comment by medyagh** [comment] 2020-08-12 19:00
closing this in favor of Duplicate of #8333

**Closed by medyagh** 2020-08-12 19:00 UTC
Labels: co/none-driver, os/linux, triage/duplicate
