### ISSUE TITLE
Failed to setup kubeconfig: inspect IP bridge network: No such network: xxx

### ISSUE THREAD

**Issue by rcdmoreno** [kubernetes/minikube#9041] opened 2020-08-20 15:06 UTC
**Os comandos necessários para reproduzir o problema**: minikube start
 
**A saída completa do comando que apresentou falha**:
E0820 12:01:34.175077   25620 start.go:97] Unable to get host IP: inspect IP bridge network "82af4ec5a3e9\n5da7c2441967".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 82af4ec5a3e9
5da7c2441967: exit status 1
stdout:

stderr:
Error: No such network: 82af4ec5a3e9
5da7c2441967

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "82af4ec5a3e9\n5da7c2441967".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 82af4ec5a3e9
5da7c2441967: exit status 1
stdout:

stderr:
Error: No such network: 82af4ec5a3e9
5da7c2441967

**A saída do comando `minikube logs`**:<details>

-- Logs begin at Thu 2019-04-11 13:28:36 -03, end at Thu 2020-08-20 12:06:02 -03. --
ago 20 10:34:43 ubuntu sudo[2931]: rcdmoreno : TTY=pts/0 ; PWD=/home/rcdmoreno ; USER=root ; COMMAND=/usr/bin/apt remove minikube
ago 20 10:35:49 ubuntu sudo[4192]: rcdmoreno : TTY=pts/0 ; PWD=/home/rcdmoreno ; USER=root ; COMMAND=/usr/bin/rm -rf /usr/local/bin/minikube
ago 20 10:50:10 ubuntu sudo[9343]: rcdmoreno : TTY=pts/0 ; PWD=/home/rcdmoreno ; USER=root ; COMMAND=/usr/bin/mv ./minikube /usr/local/bin/

</details>

**A versão do sistema operacional usado**: 
Linux ubuntu 5.3.0-64-generic #58-Ubuntu SMP Fri Jul 10 19:33:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by tstromberg** [comment] 2020-08-20 21:18
Obrigado pelo relatório. Você poderia compartilhar a saída de:

* `minikube start -v = 1`
* `docker network ls`

Além disso, confirme se a versão mais recente do minikube (v1.12.3) está sendo usada.

**Comment by rcdmoreno** [comment] 2020-08-21 00:32
saida minikube -v 1
E0820 21:29:52.049607    4506 start.go:97] Unable to get host IP: inspect IP bridge network "a7e9779d92e9\n5da7c2441967".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" a7e9779d92e9
5da7c2441967: exit status 1
stdout:


stderr:
Error: No such network: a7e9779d92e9
5da7c2441967

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "a7e9779d92e9\n5da7c2441967".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" a7e9779d92e9
5da7c2441967: exit status 1
stdout:


stderr:
Error: No such network: a7e9779d92e9
5da7c2441967

saido docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
a7e9779d92e9        bridge              bridge              local
5da7c2441967        docker_gwbridge     bridge              local
45c864283eac        host                host                local
e7b7999b8911        kind                bridge             local
1a8ebf349317        none                null                 local

**Comment by rcdmoreno** [comment] 2020-08-21 00:35
acabei de executar o seguinte comando para apagar seguintes networks:
docker network rm docker_gwbridge kind

E agora funcionou corretamente.

**Comment by rcdmoreno** [comment] 2020-08-21 00:35
minikube status
minikube
type: Control Plane
host: Running
kubelet: Running
apiserver: Running
kubeconfig: Configured

valeu Thomas

**Comment by apagac2** [comment] 2020-08-21 07:37
Also hitting this.

**minikube start command:**  minikube start --driver=docker

**Steps to reproduce the issue:** 

1. Have docker installed
2. Run "minikube start --driver=docker"

**Full output of failed command:** 

😄  minikube v1.12.3 on Centos 7.8.2003
✨  Using the docker driver based on user configuration
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
🔥  Creating docker container (CPUs=2, Memory=8000MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0821 09:03:30.335870    1583 start.go:97] Unable to get host IP: inspect IP bridge network "a1b4c383d0d1\ndc182a4ef41e".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" a1b4c383d0d1
dc182a4ef41e: exit status 1
stdout:


stderr:
Error: No such network: a1b4c383d0d1
dc182a4ef41e

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "a1b4c383d0d1\ndc182a4ef41e".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" a1b4c383d0d1
dc182a4ef41e: exit status 1
stdout:


stderr:
Error: No such network: a1b4c383d0d1
dc182a4ef41e


😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**

minikube logs
<details>
==> Docker <==
-- Logs begin at Fri 2020-08-21 07:03:23 UTC, end at Fri 2020-08-21 07:27:51 UTC. --
Aug 21 07:03:23 minikube systemd[1]: Starting Docker Application Container Engine...
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.024906901Z" level=info msg="Starting up"
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.029044349Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.029101769Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.029176089Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.029208459Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.031847747Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.031882437Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.031917037Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.031940727Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.474050254Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.520841268Z" level=info msg="Loading containers: start."
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.616945973Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 21 07:03:24 minikube dockerd[172]: time="2020-08-21T07:03:24.658879529Z" level=info msg="Loading containers: done."
Aug 21 07:03:25 minikube dockerd[172]: time="2020-08-21T07:03:25.089276762Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
Aug 21 07:03:25 minikube dockerd[172]: time="2020-08-21T07:03:25.089709002Z" level=info msg="Daemon has completed initialization"
Aug 21 07:03:25 minikube dockerd[172]: time="2020-08-21T07:03:25.129981919Z" level=info msg="API listen on /run/docker.sock"
Aug 21 07:03:25 minikube systemd[1]: Started Docker Application Container Engine.
Aug 21 07:03:28 minikube systemd[1]: docker.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Aug 21 07:03:28 minikube systemd[1]: Stopping Docker Application Container Engine...
Aug 21 07:03:28 minikube dockerd[172]: time="2020-08-21T07:03:28.684779605Z" level=info msg="Processing signal 'terminated'"
Aug 21 07:03:28 minikube dockerd[172]: time="2020-08-21T07:03:28.686601784Z" level=info msg="stopping event stream following graceful shutdown" error="<nil>" module=libcontainerd namespace=moby
Aug 21 07:03:28 minikube dockerd[172]: time="2020-08-21T07:03:28.689687382Z" level=info msg="Daemon shutdown complete"
Aug 21 07:03:28 minikube systemd[1]: docker.service: Succeeded.
Aug 21 07:03:28 minikube systemd[1]: Stopped Docker Application Container Engine.
Aug 21 07:03:28 minikube systemd[1]: Starting Docker Application Container Engine...
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.974822639Z" level=info msg="Starting up"
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.979681456Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.979735946Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.979785186Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.979820446Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.982866864Z" level=info msg="parsed scheme: \"unix\"" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.982948734Z" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.983027034Z" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] <nil>}" module=grpc
Aug 21 07:03:28 minikube dockerd[392]: time="2020-08-21T07:03:28.983094454Z" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.010496119Z" level=info msg="[graphdriver] using prior storage driver: overlay2"
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.023745051Z" level=info msg="Loading containers: start."
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.154791766Z" level=info msg="Default bridge (docker0) is assigned with an IP address 172.18.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.206820716Z" level=info msg="Loading containers: done."
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.232495062Z" level=info msg="Docker daemon" commit=afacb8b7f0 graphdriver(s)=overlay2 version=19.03.8
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.232567062Z" level=info msg="Daemon has completed initialization"
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.259356186Z" level=info msg="API listen on /var/run/docker.sock"
Aug 21 07:03:29 minikube dockerd[392]: time="2020-08-21T07:03:29.259361766Z" level=info msg="API listen on [::]:2376"
Aug 21 07:03:29 minikube systemd[1]: Started Docker Application Container Engine.

==> container status <==
time="2020-08-21T07:27:53Z" level=fatal msg="failed to connect: failed to connect, make sure you are running as root and the runtime has been started: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> describe nodes <==
E0821 09:27:54.016759    9558 logs.go:178] command /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig" failed with error: /bin/bash -c "sudo /var/lib/minikube/binaries/v1.18.3/kubectl describe nodes --kubeconfig=/var/lib/minikube/kubeconfig": Process exited with status 1
stdout:

stderr:
error: stat /var/lib/minikube/kubeconfig: no such file or directory
 output: "\n** stderr ** \nerror: stat /var/lib/minikube/kubeconfig: no such file or directory\n\n** /stderr **"

==> dmesg <==
[  +0.000000] ACPI: APIC 00000000dda1ed48 0015E (v03 ALASKA   A M I  01072009 AMI  00010013)
[  +0.000000] ACPI: FPDT 00000000dda1eea8 00044 (v01 ALASKA   A M I  01072009 AMI  00010013)
[  +0.000000] ACPI: FIDT 00000000dda1eef0 0009C (v01 ALASKA    A M I 01072009 AMI  00010013)
[  +0.000000] ACPI: SSDT 00000000dda1ef90 000FC (v02 ALASKA  CPUSSDT 01072009 AMI  01072009)
[  +0.000000] ACPI: SSDT 00000000dda1f090 08C98 (v02    AMD AMD ALIB 00000002 MSFT 04000000)
[  +0.000000] ACPI: SSDT 00000000dda27d28 03076 (v01    AMD  AMD AOD 00000001 INTL 20120913)
[  +0.000000] ACPI: MCFG 00000000dda2ada0 0003C (v01 ALASKA    A M I 01072009 MSFT 00010013)
[  +0.000000] ACPI: HPET 00000000dda2ade0 00038 (v01 ALASKA    A M I 01072009 AMI  00000005)
[  +0.000000] ACPI: SSDT 00000000dda2ae18 00024 (v01 AMDFCH    FCHZP 00001000 INTL 20120913)
[  +0.000000] ACPI: UEFI 00000000dda2ae40 00042 (v01 ALASKA   A M I  00000002      01000013)
[  +0.000000] ACPI: IVRS 00000000dda2ae88 000D0 (v02  AMD   AMD IVRS 00000001 AMD  00000000)
[  +0.000000] ACPI: SSDT 00000000dda2af58 02314 (v01    AMD  AMD CPU 00000001 AMD  00000001)
[  +0.000000] ACPI: CRAT 00000000dda2d270 00F50 (v01    AMD AMD CRAT 00000001 AMD  00000001)
[  +0.000000] ACPI: CDIT 00000000dda2e1c0 00029 (v01    AMD AMD CDIT 00000001 AMD  00000001)
[  +0.000000] ACPI: BGRT 00000000dda2e1f0 00038 (v01 ALASKA   A M I  01072009 AMI  00010013)
[  +0.000000] ACPI: SSDT 00000000dda2e228 01CE5 (v01    AMD AmdTable 00000001 INTL 20120913)
[  +0.000000] ACPI: SSDT 00000000dda2ff10 000BF (v01    AMD   AMD PT 00001000 INTL 20120913)
[  +0.000000] ACPI: WSMT 00000000dda2ffd0 00028 (v01 ALASKA   A M I  01072009 AMI  00010013)
[  +0.000000] ACPI: SSDT 00000000dda2fff8 010AF (v01    AMD AmdTable 00000001 INTL 20120913)
[  +0.000000] Zone ranges:
[  +0.000000]   DMA      [mem 0x00001000-0x00ffffff]
[  +0.000000]   DMA32    [mem 0x01000000-0xffffffff]
[  +0.000000]   Normal   [mem 0x100000000-0x81f37ffff]
[  +0.000000] Movable zone start for each node
[  +0.000000] Early memory node ranges
[  +0.000000]   node   0: [mem 0x00001000-0x0009ffff]
[  +0.000000]   node   0: [mem 0x00100000-0x09d7ffff]
[  +0.000000]   node   0: [mem 0x0a000000-0x0a1fffff]
[  +0.000000]   node   0: [mem 0x0a20b000-0x0affffff]
[  +0.000000]   node   0: [mem 0x0b020000-0xdd393fff]
[  +0.000000]   node   0: [mem 0xdd501000-0xdd683fff]
[  +0.000000]   node   0: [mem 0xde6da000-0xdeffffff]
[  +0.000000]   node   0: [mem 0x100000000-0x81f37ffff]
[  +0.000000] Detected CPU family 17h model 8
[  +0.000000] Warning: AMD Processor - this hardware has not undergone upstream testing. Please consult http://wiki.centos.org/FAQ for more information
[  +0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 8245083
[  +0.000000] Policy zone: Normal
[  +0.000000] tsc: Fast TSC calibration failed
[  +0.000000] ACPI: All ACPI Tables successfully acquired
[  +0.436803] ACPI: Executed 2 blocks of module-level executable AML code
[  +0.006026] ACPI: Enabled 2 GPEs in block 00 to 1F
[  +0.027032] Expanded resource reserved due to conflict with PCI Bus 0000:00
[  +0.295662]  PPR NX GT IA GA PC GA_vAPIC
[  +0.024159] Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[  +0.520013] nvme nvme0: missing or invalid SUBNQN field.
[  +0.643226] nvidia: loading out-of-tree module taints kernel.
[  +0.000007] nvidia: module license 'NVIDIA' taints kernel.
[  +0.000001] Disabling lock debugging due to kernel taint
[  +0.222577] NVRM: loading NVIDIA UNIX x86_64 Kernel Module  440.82  Wed Apr  1 20:04:33 UTC 2020
[  +1.375605] FAT-fs (nvme0n1p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[  +0.817934] VBoxNetFlt: Successfully started.
[  +0.003658] VBoxNetAdp: Successfully started.
[ +11.202061] resource sanity check: requesting [mem 0x000c0000-0x000fffff], which spans more than PCI Bus 0000:00 [mem 0x000c0000-0x000dffff window]
[  +0.000082] caller os_map_kernel_space.part.7+0x85/0xb0 [nvidia] mapping multiple BARs
[Aug 4 08:02] TECH PREVIEW: Overlay filesystem may not be fully supported.
              Please review provided documentation for limitations.
[Aug 5 09:32] perf: interrupt took too long (2506 > 2500), lowering kernel.perf_event_max_sample_rate to 79000
[Aug13 05:44] TCP: enp24s0: Driver has suspect GRO implementation, TCP performance may be compromised.
[Aug13 07:58] overlayfs: Warning: Copying up diversions, but open R/O on fd 4 which will cease to be coherent [pid=8116 dpkg-divert]
[Aug13 13:56] perf: interrupt took too long (3184 > 3132), lowering kernel.perf_event_max_sample_rate to 62000

==> kernel <==
 07:27:54 up 16 days, 23:27,  0 users,  load average: 0.57, 0.80, 0.89
Linux minikube 3.10.0-1127.el7.x86_64 #1 SMP Tue Mar 31 23:36:51 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
PRETTY_NAME="Ubuntu 20.04 LTS"

==> kubelet <==
-- Logs begin at Fri 2020-08-21 07:03:23 UTC, end at Fri 2020-08-21 07:27:54 UTC. --
-- No entries --

❗  unable to fetch logs for: describe nodes
</details>

**Additional info:**

docker network ls
NETWORK ID          NAME                                    DRIVER              SCOPE
8205b2fee2bc        angular-flask-docker-skeleton_default   bridge              local
a1b4c383d0d1        bridge                                  bridge              local
dc182a4ef41e        docker_gwbridge                         bridge              local
9b7c57bce010        host                                    host                local
3kqdng4mqsu6        ingress                                 overlay             swarm
b425eb068920        jenkins                                 bridge              local
os103bzamm0w        portainer_agent_network                 overlay             swarm

It seems to me that for some reason we are trying to inspect two docker networks at the same time, see:

`Unable to get host IP: inspect IP bridge network "a1b4c383d0d1\ndc182a4ef41e"`

Note the `\n`. Both `a1b4c383d0d1` and `dc182a4ef41e` are valid network IDs.

I don't believe deleting 'docker_gwbridge' network is the correct solution to this problem.

**Comment by tstromberg** [comment] 2020-09-02 17:22
This issue appears to be a duplicate of #8131, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-09-02 17:22 UTC
Labels: l/pt-BR, os/linux, triage/needs-information, triage/support
