### ISSUE TITLE
Unable to use minikube as go dependency: vm_assets: undefined: Asset

### ISSUE THREAD

**Issue by ichekrygin** [kubernetes/minikube#3124] opened 2018-09-10 23:08 UTC
Feature Request: Generate & Check-in Minikube `assets.go`

I am working on some automation tools that include `minikube` operations. To that end, I am trying to use `minikube` as a `go` dependency:
```
[[constraint]]
  name = "k8s.io/minikube"
  version = "0.28.2"
```

This results in "incomplete" `minikube` vendor dependency. Most likely due to the `minikube` dependency on `go-bindata` need to generate additional (assets related) `go` files,(see [this issue](https://github.com/kubernetes/minikube/issues/2656) for additional context).

It appears that w/out `go-bindata` - `minikube` source code is not buildable/usable in the context of `go` dependency, and results in:
```
# github.com/user/project/vendor/k8s.io/minikube/pkg/minikube/assets
vendor/k8s.io/minikube/pkg/minikube/assets/vm_assets.go:153:19: undefined: Asset
```

**Comment by tstromberg** [comment] 2018-09-19 16:50
This appears to be a dupe of #2656

**Closed by tstromberg** 2018-09-19 16:50 UTC
Labels: area/dependencies, kind/bug
