### ISSUE TITLE
Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

### ISSUE THREAD

**Issue by vipmaha1** [kubernetes/minikube#12062] opened 2021-07-27 06:31 UTC
**Steps to reproduce the issue:** 

1.minikube start --vm=true
2. 
3.

**Full output of `minikube logs` command:**
<details>
I0727 11:50:35.938065    9064 ssh_runner.go:149] Run: sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.21.2/kubectl apply -f /etc/kubernetes/addons/ingress-configmap.yaml -f /etc/kubernetes/addons/ingress-rbac.yaml -f /etc/kubernetes/addons/ingress-dp.yaml
I0727 11:50:36.517823    9064 main.go:130] libmachine: Making call to close driver server
I0727 11:50:36.517868    9064 main.go:130] libmachine: (minikube) Calling .Close
I0727 11:50:36.518118    9064 main.go:130] libmachine: (minikube) DBG | Closing plugin on server side
I0727 11:50:36.518150    9064 main.go:130] libmachine: Successfully made call to close driver server
I0727 11:50:36.518165    9064 main.go:130] libmachine: Making call to close connection to plugin binary
I0727 11:50:36.518253    9064 main.go:130] libmachine: Making call to close driver server
I0727 11:50:36.518259    9064 main.go:130] libmachine: (minikube) Calling .Close
I0727 11:50:36.518519    9064 main.go:130] libmachine: Successfully made call to close driver server
I0727 11:50:36.518522    9064 main.go:130] libmachine: (minikube) DBG | Closing plugin on server side
I0727 11:50:36.518529    9064 main.go:130] libmachine: Making call to close connection to plugin binary
I0727 11:50:36.518900    9064 addons.go:313] Verifying addon ingress=true in "minikube"
I0727 11:50:36.539887    9064 out.go:165] 🔎  Verifying ingress addon...
I0727 11:50:36.575977    9064 kapi.go:75] Waiting for pod with label "app.kubernetes.io/name=ingress-nginx" in ns "ingress-nginx" ...
I0727 11:50:36.615582    9064 kapi.go:86] Found 3 Pods for label selector app.kubernetes.io/name=ingress-nginx
I0727 11:50:36.615593    9064 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
:::::::
I0727 11:56:36.628035    9064 kapi.go:96] waiting for pod "app.kubernetes.io/name=ingress-nginx", current state: Pending: [<nil>]
I0727 11:56:36.628049    9064 kapi.go:108] duration metric: took 6m0.05567944s to wait for app.kubernetes.io/name=ingress-nginx ...
I0727 11:56:36.649398    9064 out.go:165]

</details>

**Full output of failed command:**
<details>

Exiting due to MK_ADDON_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
</details>

**Comment by Tibor17** [comment] 2021-07-28 14:37
I have the same problem with `minikube addons enable ingress`.

**Comment by apupier** [comment] 2021-07-29 12:28
sounds duplicate of https://github.com/kubernetes/minikube/issues/10544

**Comment by spowelljr** [comment] 2021-07-30 20:56
@apupier is right, this is a duplicate of #10544. I'm going to close this issue, but please follow along with #10544, thank you!

**Closed by spowelljr** 2021-07-30 20:56 UTC
