### ISSUE TITLE
Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

### ISSUE THREAD

**Issue by huguesalary** [kubernetes/minikube#4217] opened 2019-05-07 02:14 UTC
When starting `minikube` on an OS with a running `docker` server, but without a `systemctl` binary, I get the following error: `Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1`

Of course, it can't start `docker` via `systemctl`, `docker` is already running, and, `systemctl` is not valid binary on my synology drive.

`minikube start --v=7  --memory 1000 --cpus 1 --disk-size=120000MB --vm-driver=none`

```
o   minikube v1.0.1 on linux (amd64)
-   minikube will upgrade the local cluster from Kubernetes 1.12.5 to 1.14.1
i   Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
:   Restarting existing none VM for "minikube" ...
:   Waiting for SSH access ...
-   "minikube" IP address is 192.168.86.23
-   Configuring Docker as the container runtime ...

!   Failed to enable container runtime: running command: sudo systemctl start docker: exit status 1

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
-   https://github.com/kubernetes/minikube/issues/new
```

Is it possible to bypass the use of `systemctl` (and `journalctl`)?

**Comment by afbjorklund** [comment] 2019-05-07 14:56
This is a known issue, systemd is currently required: #2704 #3174 #3748

**Comment by tstromberg** [comment] 2019-05-14 17:49
Duplicate of #2704

**Closed by tstromberg** 2019-05-14 17:49 UTC
Labels: co/none-driver, triage/duplicate

**Comment by dianaabv** [comment] 2019-11-05 13:25
rm -rf ~/snap/docker

> It is recommended to use the apt installation of docker from (Docker, when using the none driver. The snap installation of docker does not work with minikube.

**Comment by eskuai** [comment] 2020-01-10 11:49
@dianaabv .  Yes, in my case,  the snapd is the problem.
tx
