### ISSUE TITLE
Support CoreOS as the ISO image

### ISSUE THREAD

**Issue by philips** [kubernetes/minikube#187] opened 2016-06-09 05:26 UTC
I want to see CoreOS as an image option for minikube. It should be trivial as we build images for vagrant for VMWare, Virtualbox, etc. But, I need to dig into what the Boot2Docker ISO is actually doing.

Does anyone have a good pointer doc so I can dig in and understand before I go spelunking on my own?

**Comment by runseb** [comment] 2016-06-09 07:45
@philips you most likely saw how the iso is built from `https://github.com/kubernetes/minikube/tree/master/deploy/iso`

I think @dlorenc got inspired by my boot2k8s `https://github.com/skippbox/boot2k8s`

The base docker file is at `https://github.com/boot2docker/boot2docker/blob/master/Dockerfile`
Jessie based.

not sure if that's what you were after.

**Comment by dlorenc** [comment] 2016-06-09 16:56
I *think* you might not have to do anything. libmachine has a concept of OS "provisioners", where the code runs and attempts to detect what OS is on the running VM, then executes steps to start everything up appropriately for that OS. libmachine has a coreos provisioner already: https://github.com/docker/machine/blob/master/libmachine/provision/coreos.go

How small of an ISO can we get?

**Comment by philips** [comment] 2016-06-09 23:13
@dlorenc I guess I don't know enough about how the ISO works. How does the OS get installed to the actual disk with boot2docker?

I will dig.

**Comment by jimmidyson** [comment] 2016-07-02 06:51
I think it just runs completely from RAM.

**Comment by r2d4** [comment] 2016-09-22 18:58
Closing this as a dupe of #571

**Comment by philips** [comment] 2016-09-22 19:11
FWIW, this isn't a dupe. That ISO is custom-built for minikube.

**Comment by r2d4** [comment] 2016-09-22 19:49
apologies, reopening

**Comment by pgray** [comment] 2016-11-11 22:52
Any movement on this?
I'd be really interested in trying to help out if it's stalled a bit.

**Comment by dlorenc** [comment] 2016-11-11 22:54
I don't think anyone is working on this. What's the use case you're hoping to use coreOS for?

**Comment by pgray** [comment] 2016-11-11 23:41
We'd like to be able to run the same coreOS version on developer laptops as in production with minikube to setup the kubernetes version and other pieces.
We have some legacy services built directly on top of coreOS that we might keep or replace, but having coreos available in minikube would allow us to test transitioning pretty thoroughly.

**Closed** 2018-02-16 16:02 UTC
Labels: kind/feature, lifecycle/rotten
