### ISSUE TITLE
panic on minikube start

### ISSUE THREAD

**Issue by andrewgdavis** [kubernetes/minikube#514] opened 2016-08-24 00:24 UTC
**Minikube version** (use `minikube version`): v0.8.0  with kubernetes/kubernetes#30948 cherrypicked...

**Environment**:
- **OS** (e.g. from /etc/os-release): osx
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`): xhyve
- **Docker version** (e.g. `docker -v`): Docker version 1.10.3, build 20f81dd

**What happened**:
```
> minikube start
... lots of pods / rcs / jobs / petsets / services deployed
... removed all running pods / services
> minikube stop
> minikube start
> eval $(minikube docker-env)
> minikube status
Running
> kubectl version
Client Version: version.Info{Major:"1", Minor:"3", GitVersion:"v1.3.5", GitCommit:"b0deb2eb8f4037421077f77cb163dbb4c0a2a9f5", GitTreeState:"clean", BuildDate:"2016-08-11T20:29:08Z", GoVersion:"go1.6.2", Compiler:"gc", Platform:"darwin/amd64"}
The connection to the server 192.168.64.7:8443 was refused - did you specify the right host or port?
```

looking into the localkube.out logs:
```
016-08-24 00:00:24.064005 I | etcdserver: heartbeat = 100ms
2016-08-24 00:00:24.064011 I | etcdserver: election = 1000ms
2016-08-24 00:00:24.064017 I | etcdserver: snapshot count = 10000
2016-08-24 00:00:24.064047 I | etcdserver: advertise client URLs = http://localhost:49090
2016-08-24 00:00:24.064099 W | wal: ignored file 0.tmp in wal
W0824 00:00:24.114953    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Namespace ended with: 401: The event in requested index is outdated and cleared (the requested history has bee
W0824 00:00:24.115095    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.ReplicationController ended with: 401: The event in requested index is outdated and cleared (the requested his
W0824 00:00:24.142826    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.PersistentVolume ended with: 401: The event in requested index is outdated and cleared (the requested history
W0824 00:00:24.145044    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *batch.Job ended with: 401: The event in requested index is outdated and cleared (the requested history has been cl
W0824 00:00:24.145431    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.PodTemplate ended with: 401: The event in requested index is outdated and cleared (the requested history has b
W0824 00:00:24.145932    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.ReplicationController ended with: 401: The event in requested index is outdated and cleared (the requested his
W0824 00:00:24.146000    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.ConfigMap ended with: 401: The event in requested index is outdated and cleared (the requested history has bee
W0824 00:00:24.146462    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.PersistentVolumeClaim ended with: 401: The event in requested index is outdated and cleared (the requested his
W0824 00:00:24.147845    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *extensions.Deployment ended with: 401: The event in requested index is outdated and cleared (the requested history
W0824 00:00:24.147936    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Service ended with: 401: The event in requested index is outdated and cleared (the requested history has been
W0824 00:00:24.159164    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Node ended with: 401: The event in requested index is outdated and cleared (the requested history has been cle
W0824 00:00:24.160405    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Endpoints ended with: 401: The event in requested index is outdated and cleared (the requested history has bee
W0824 00:00:24.160587    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *autoscaling.HorizontalPodAutoscaler ended with: 401: The event in requested index is outdated and cleared (the req
W0824 00:00:24.160600    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *autoscaling.HorizontalPodAutoscaler ended with: 401: The event in requested index is outdated and cleared (the req
W0824 00:00:24.161107    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.LimitRange ended with: 401: The event in requested index is outdated and cleared (the requested history has be
W0824 00:00:24.161203    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Pod ended with: 401: The event in requested index is outdated and cleared (the requested history has been clea
W0824 00:00:24.161777    1361 reflector.go:334] pkg/storage/cacher.go:163: watch of *api.Secret ended with: 401: The event in requested index is outdated and cleared (the requested history has been c
E0824 00:00:24.187997    1361 event.go:207] Unable to write event: 'Post http://127.0.0.1:8080/api/v1/namespaces/default/events: dial tcp 127.0.0.1:8080: getsockopt: connection refused' (may retry af
2016-08-24 00:00:24.287309 I | etcdserver: restarting member 6429d4ab4d8a33da in cluster d3c354cfe77b0b70 at commit index 66695
2016-08-24 00:00:24.288075 I | raft: 6429d4ab4d8a33da became follower at term 2
2016-08-24 00:00:24.288103 I | raft: newRaft 6429d4ab4d8a33da [peers: [6429d4ab4d8a33da], term: 2, commit: 66695, applied: 60006, lastindex: 66695, lastterm: 2]
2016-08-24 00:00:24.289964 I | membership: added member 6429d4ab4d8a33da [http://localhost:9256] to cluster d3c354cfe77b0b70 from store
2016-08-24 00:00:24.289982 I | membership: set the cluster version to 2.3 from store
panic: listen tcp 127.0.0.1:49090: bind: address already in use

goroutine 1 [running]:
panic(0x342a040, 0xc8251e7ea0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
k8s.io/minikube/pkg/localkube.createListenersOrPanic(0xc820090e00, 0x1, 0x1, 0x0, 0x0, 0x0)
        /go/src/k8s.io/minikube/pkg/localkube/etcd.go:141 +0x14d
k8s.io/minikube/pkg/localkube.(*EtcdServer).Start(0xc82007ade0)
        /go/src/k8s.io/minikube/pkg/localkube/etcd.go:98 +0x20f
k8s.io/minikube/pkg/localkube.(*DNSServer).Start(0xc820162340)
        /go/src/k8s.io/minikube/pkg/localkube/dns.go:127 +0x213
k8s.io/minikube/pkg/localkube.Servers.StartAll(0xc82029ee80, 0x7, 0x8)
        /go/src/k8s.io/minikube/pkg/localkube/servers.go:41 +0x1ac
k8s.io/minikube/cmd/localkube/cmd.StartLocalkube()
        /go/src/k8s.io/minikube/cmd/localkube/cmd/start.go:49 +0x225
k8s.io/minikube/cmd/localkube/cmd.glob.func1(0x56b24a0, 0xc820291ce0, 0x0, 0x2)
        /go/src/k8s.io/minikube/cmd/localkube/cmd/root.go:31 +0x14
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).execute(0x56b24a0, 0xc82000a100, 0x2, 0x2, 0x0, 0x0)
        /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:565 +0x85a
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x56b24a0, 0x56b24a0, 0x0, 0x0)
        /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:651 +0x55c
k8s.io/minikube/vendor/github.com/spf13/cobra.(*Command).Execute(0x56b24a0, 0x0, 0x0)
        /go/src/k8s.io/minikube/vendor/github.com/spf13/cobra/command.go:610 +0x2d
main.main()
        /go/src/k8s.io/minikube/cmd/localkube/main.go:32 +0x54
```

**What you expected to happen**:
no panic on start!

**How to reproduce it** (as minimally and precisely as possible):
unknown reproduction at this point.

**Anything else do we need to know**:

**Comment by dlorenc** [comment] 2016-08-24 02:22
Hey, thanks for following the template :)

Sorry you ran into trouble. Could you attach the output of this command (from when the issue is repro'ing):
`minikube ssh "netstat -tulpn | grep 49090"`

**Comment by aaron-prindle** [comment] 2016-09-08 21:41
Ping, please attach the output of `minikube ssh "netstat -tulpn | grep 49090"`.

**Comment by andrewgdavis** [comment] 2016-09-08 21:51
sorry, no repro yet.

**Comment by aaron-prindle** [comment] 2016-10-27 17:57
Closing for now, please re-open if you encounter the issue again.

**Closed by aaron-prindle** 2016-10-27 17:57 UTC
Labels: kind/bug
