### ISSUE TITLE
support minikube in systems without systemctl

### ISSUE THREAD

**Issue by matti** [kubernetes/minikube#3392] opened 2018-12-03 12:35 UTC
In https://github.com/kubernetes/minikube/issues/2134

>Decide if we still want to support non-systemd systems (complicates the configuration for the kubeadm kubelet)

I guess the decission was no because now in Google Cloud Shell machine:

```
$ minikube version
minikube version: v0.30.0
```

```
$ sudo minikube start --vm-driver none
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
E1203 14:31:34.930104   16261 start.go:254] Error updating cluster:  starting kubelet: running command:
sudo systemctl daemon-reload &&
sudo systemctl enable kubelet &&
sudo systemctl start kubelet
: exit status 1
```

Can I somehow run minikube in this environment?

**Comment by matti** [comment] 2018-12-03 15:40
related: https://github.com/kubernetes/minikube/issues/2704

**Comment by tstromberg** [comment] 2018-12-03 18:43
This is essentially a dupe of #2704. minikube runs great in Google Compute Engine, with VM's (KVM, Virtualbox) or in None mode, but I'm not sure of what limitations Google Cloud Shell has in place.

Changing this will likely mean sending patches into kubeadm, but if there is anything we can do on the minikube side, we'll happily review any PR to make this situation better.

**Closed by tstromberg** 2018-12-03 18:43 UTC
Labels: bootstrapper/kubeadm, drv/none

**Comment by matti** [comment] 2018-12-04 21:23
@tsrromberg Google cloud shell is based on debian (?) and the systemctl is not present there.

But yes, agreed that this is essentially a dup of #2704 - although I want to point out that google cloud shell default image ships with older minikube that works, because it does not require systemd.
