### ISSUE TITLE
Issue installing istio on minikube

### ISSUE THREAD

**Issue by shastrula** [kubernetes/minikube#10029] opened 2020-12-23 02:19 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

minikube addons enable istio

❌  Exiting due to MK_ENABLE: run callbacks: running callbacks: [sudo KUBECONFIG=/var/lib/minikube/kubeconfig /var/lib/minikube/binaries/v1.19.4/kubectl apply -f /etc/kubernetes/addons/istio-default-profile.yaml: Process exited with status 1
stdout:
namespace/istio-system unchanged

stderr:
error: unable to recognize "/etc/kubernetes/addons/istio-default-profile.yaml": no matches for kind "IstioOperator" in version "install.istio.io/v1alpha1"
]

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by priyawadhwa** [comment] 2020-12-23 19:40
Hey @shastrula -- this issue appears to be a duplicate of https://github.com/kubernetes/minikube/issues/9311. I'm going to close this issue so we can centralize the discussion in one place. Could you please comment on that issue with the errors you're seeing?

It seems like users in that thread successfully ran:

```
minikube addons enable istio-provisioner
minikube addons enable istio
```

could you please give that a try? Thank you!

**Closed by priyawadhwa** 2020-12-23 19:40 UTC
Labels: kind/support

**Comment by shastrula** [comment] 2020-12-24 22:49
It worked! Thank you!

**Comment by Lettino** [comment] 2020-12-25 06:48
Thanks!!!! It worked

**Comment by reply2future** [comment] 2022-03-31 09:20
Update to v1.25.2 and solved it.
