### ISSUE TITLE
is it possible to use minikube for development?

### ISSUE THREAD

**Issue by pacuna** [kubernetes/minikube#329] opened 2016-07-13 13:37 UTC
I'm not sure if it's possible to run an app and mount the source code so changes are reflected immediately without rebuilding the image. Any thoughts on this? Maybe this is not one of the purposes of Minikube and is just for testing ?

Thanks in advance.

**Comment by moondev** [comment] 2016-07-13 15:29
It's possible with hostpath volumes. If you run `minikube ssh` and then cd to /Users you should see your home directory. You can then create a k8s volume that mounts to a path in your home directory.


However I think using plain docker is better for development do to ease of use. You could then setup a ci pipeline to push your container to test in your k8s cluster.

**Comment by pacuna** [comment] 2016-07-13 15:35
@moondev the thing with Docker is that most of my team uses OS X and Docker for Mac doesn't work very well with bigger projects at the moment. Right now we're using Vagrant and nginx-proxy for routing to all of our different projects so I was thinking maybe we could replace that with Minikube and have a more unified dev-prod ecosystem.

**Comment by dlorenc** [comment] 2016-07-13 16:45
Hey,

@moondev is right about how to do local development now. This isn't a terribly smooth approach, but this is one of the main goals of Minikube so we'll be working on making it much easier over time.

It would definitely be helpful if you could share more information on how your team does local development.

In the case where you're mounting your local FS into the Docker container, are you running something to watch/restart your process on file changes?

**Comment by pacuna** [comment] 2016-07-13 18:09
@dlorenc thanks for the answer. We have a shared folder in our VM with all of our projects. Then for each project we have a compose file that mounts and builds the project source code. On top of that we have nginx-proxy so we can access all of the projects by using more friendly urls. We don't need to watch or restart anything in order to see the changes. Just compose up and start working.

**Comment by aaron-prindle** [comment] 2016-09-08 21:47
Closing as dupe of #266

**Closed by aaron-prindle** 2016-09-08 21:47 UTC
Labels: kind/documentation

**Comment by pchico83** [comment] 2018-10-25 11:43
It is more performance to synchronize the local and the minikube filesystem using syncthing than using shared folders. We built an open source tool that follows this approach in case it helps:
https://github.com/okteto/cnd
