### ISSUE TITLE
minikube start with kvm-qemu-uri still fails due to non-existent "default" network

### ISSUE THREAD

**Issue by ge79so** [kubernetes/minikube#9190] opened 2020-09-05 10:25 UTC
**Steps to reproduce the issue:** 

_On Debian stable 10.5_
_NB. KVM is installed and working with virt-manager_

`$ minikube start --kvm-qemu-uri qemu:///session`

**Full output of failed command:** 

🔄  Restarting existing kvm2 VM for "minikube" ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: creating network: network default doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: creating network: network default doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

`$ user@pc:/usr/local/bin$ minikube delete`

🔥  Removing /home/user/.minikube/machines/minikube ...
💀  Removed all traces of the "minikube" cluster.

user@pc:/usr/local/bin$ minikube start --kvm-qemu-uri qemu:///session

😄  minikube v1.13.0 on Debian 10.5
✨  Automatically selected the kvm2 driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating kvm2 VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: Error creating machine: Error in driver during machine creation: creating network: network default doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')
🔄  Restarting existing kvm2 VM for "minikube" ...
😿  Failed to start kvm2 VM. Running "minikube delete" may fix it: driver start: creating network: network default doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: creating network: network default doesn't exist: virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'default'')

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>
$ minikube logs

❌  Exiting due to GUEST_KVM2_NO_DOMAIN: state: getting connection: looking up domain: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching name 'minikube'')
💡  Suggestion: The VM that minikube is configured for no longer exists. Run 'minikube delete'
🍿  Related issue: https://github.com/kubernetes/minikube/issues/3636

</details>

**Comment by afbjorklund** [comment] 2020-09-05 14:47
It is not possible to run the libvirt driver (kvm2) as user, due to the missing network. See ~#4288~

Duplicated request in #9009

**Comment by tstromberg** [comment] 2020-09-05 20:44
This issue appears to be a duplicate of #9009 do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-09-05 20:44 UTC
Labels: co/kvm2, kind/feature
