### ISSUE TITLE
hyperv: StartHost: create: creating: exit status 1

### ISSUE THREAD

**Issue by diogo-caetano** [kubernetes/minikube#4824] opened 2019-07-19 20:32 UTC
minikube start --vm-driver=hyperv
* minikube v1.2.0 on windows (amd64)
* Creating hyperv VM (CPUs=2, Memory=2048MB, Disk=20000MB) ...
E0719 17:12:26.915779    7408 start.go:559] StartHost: create: creating: exit status 1

X Unable to start VM: create: creating: exit status 1

* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new

**Comment by blueelvis** [comment] 2019-07-21 14:41
@diogo-caetano - Thanks for reporting the issue! I think the issue is because you are not passing the virtual switch to bind to using the `--hyperv-virtual-switch` parameter and passing a value of the Virtual switch which is already there in Hyper-V. Could you please try that?

If it still doesn't work, could you please paste back the output of the command you are trying to run and add `--alsologtostderr -v=8`.

/label triage/needs-information

**Comment by tstromberg** [comment] 2019-08-08 21:11
To follow up on this we will need the output of `minikube start --alsologtostderr -v=8`

**Comment by tstromberg** [comment] 2019-09-19 22:14
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding `/reopen` to your comment.

Here is additional information that may be helpful to us:

*  Whether this issue exists with the latest minikube release (v1.4)
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=4` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Closed by tstromberg** 2019-09-19 22:14 UTC
Labels: co/hyperv, triage/needs-information
