### ISSUE TITLE
Unable to start minikube with 0.25 on VBoxManage

### ISSUE THREAD

**Issue by KowalczykBartek** [kubernetes/minikube#2474] opened 2018-01-27 17:23 UTC
Hi minikube experts ! unfortunately I have problem with minikube 

**This is a BUG REPORT**

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):  v0.25.0 (installed as described here https://github.com/kubernetes/minikube/releases) 
- **OS** : macOS High Sierra 10.13.1
- **VM Driver**: "DriverName": "virtualbox"
- **ISO version** : "Boot2DockerURL": "file:///var/root/.minikube/cache/iso/minikube-v0.25.1.iso",
- **Install tools**:
-- vboxmanage version : 5.2.6r120293
-- Docker : Version 18.02.0-ce-rc1-mac50 (22256)

**What happened**:
Not able to run `minikube` because 
```
E0127 18:06:10.412619   10730 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: /var/root/.minikube/cache/localkube/localkube-v1.9.0: open /var/root/.minikube/cache/localkube/localkube-v1.9.0: no such file or directory
```

This happens even if I start with "clear environment", so, I perform following steps (found in internet that it should help, but doesn't :/ )

`minikube delete`
`rm -rf /var/root/.minikube`

and I deleted existing vm 

```
sh-3.2# /usr/local/bin/VBoxManage list vms
"<inaccessible>" {328bacfb-4e0a-4ca3-80d3-b77d5fcd7bc5}
"<inaccessible>" {7ad7cedf-78cc-419a-8577-514387bc32a6}
"<inaccessible>" {19ccab2c-677d-43f3-9839-78fbc097897a}
"<inaccessible>" {8d14f2eb-32ff-4d31-abf1-d63bdf0aeddd}
"<inaccessible>" {1cbc6694-5738-4825-b61e-9ab802b69f6c}
"minikube" {12e36788-6ecc-4a31-91a7-e10895a5efdd}
```

```
vboxmanage unregistervm 12e36788-6ecc-4a31-91a7-e10895a5efdd --delete
```

**What you expected to happen**:

I expect that I am start `minikube` or at least get more info to troubleshoot problem closer. 

**How to reproduce it** (as minimally and precisely as possible):

N/A

**Output of `minikube logs` (if applicable)**:

```
sh-3.2# minikube start --alsologtostderr
W0127 18:04:34.404274   10730 root.go:148] Error reading config file at /var/root/.minikube/config/config.json: open /var/root/.minikube/config/config.json: no such file or directory
I0127 18:04:34.405496   10730 notify.go:109] Checking for updates...
I0127 18:04:34.590620   10730 cache_images.go:292] Attempting to cache image: gcr.io/k8s-minikube/storage-provisioner:v1.8.0 at /var/root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0
I0127 18:04:34.590629   10730 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.5 at /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.5
I0127 18:04:34.590674   10730 cache_images.go:292] Attempting to cache image: k8s.gcr.io/kubernetes-dashboard-amd64:v1.8.1 at /var/root/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.8.1
Starting local Kubernetes v1.9.0 cluster...
Starting VM...
I0127 18:04:34.590719   10730 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.5 at /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.5
I0127 18:04:34.590729   10730 cache_images.go:292] Attempting to cache image: k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.5 at /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 18:04:34.590760   10730 cache_images.go:292] Attempting to cache image: gcr.io/google-containers/kube-addon-manager:v6.5 at /var/root/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.5
I0127 18:04:34.590816   10730 cache_images.go:292] Attempting to cache image: k8s.gcr.io/pause-amd64:3.0 at /var/root/.minikube/cache/images/k8s.gcr.io/pause-amd64_3.0
I0127 18:04:34.590841   10730 cluster.go:70] Machine does not exist... provisioning new machine
I0127 18:04:34.590859   10730 cluster.go:71] Provisioning machine with config: {MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v0.25.1.iso Memory:2048 CPUs:2 DiskSize:20000 VMDriver:virtualbox XhyveDiskDriver:ahci-hd DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: KvmNetwork:default Downloader:{} DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID:}
Downloading Minikube ISO
 24.11 MB / 142.22 MB [=======>----------------------------------]  16.95% 1m41sI0127 18:04:55.684985   10730 cache_images.go:79] Successfully cached all images.
 142.22 MB / 142.22 MB [============================================] 100.00% 0s
I0127 18:06:08.151374   10730 ssh_runner.go:57] Run: sudo rm -f /etc/docker/ca.pem
I0127 18:06:08.158148   10730 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
I0127 18:06:08.168481   10730 ssh_runner.go:57] Run: sudo rm -f /etc/docker/server.pem
I0127 18:06:08.174122   10730 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
I0127 18:06:08.182933   10730 ssh_runner.go:57] Run: sudo rm -f /etc/docker/server-key.pem
I0127 18:06:08.189997   10730 ssh_runner.go:57] Run: sudo mkdir -p /etc/docker
Getting VM IP address...
Moving files into cluster...
I0127 18:06:10.272333   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0
I0127 18:06:10.272355   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.8.1
I0127 18:06:10.272362   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 18:06:10.272341   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.5
I0127 18:06:10.272379   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.5
I0127 18:06:10.272433   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/k8s.gcr.io/pause-amd64_3.0
I0127 18:06:10.272472   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/storage-provisioner_v1.8.0
I0127 18:06:10.272337   10730 cache_images.go:194] Loading image from cache at  /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.5
I0127 18:06:10.272473   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/kubernetes-dashboard-amd64_v1.8.1
I0127 18:06:10.272565   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/pause-amd64_3.0
I0127 18:06:10.272568   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/kube-addon-manager_v6.5
I0127 18:06:10.272494   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 18:06:10.272501   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-sidecar-amd64_1.14.5
I0127 18:06:10.272682   10730 ssh_runner.go:57] Run: sudo rm -f /tmp/k8s-dns-kube-dns-amd64_1.14.5
I0127 18:06:10.279083   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.281576   10730 kubernetes_versions.go:88] [{v1.9.0} {v1.8.0} {v1.7.5} {v1.7.4} {v1.7.3} {v1.7.2} {v1.7.0} {v1.7.0-rc.1} {v1.7.0-alpha.2} {v1.6.4} {v1.6.3} {v1.6.0} {v1.6.0-rc.1} {v1.6.0-beta.4} {v1.6.0-beta.3} {v1.6.0-beta.2} {v1.6.0-alpha.1} {v1.6.0-alpha.0} {v1.5.3} {v1.5.2} {v1.5.1} {v1.4.5} {v1.4.3} {v1.4.2} {v1.4.1} {v1.4.0} {v1.3.7} {v1.3.6} {v1.3.5} {v1.3.4} {v1.3.3} {v1.3.0}]
I0127 18:06:10.284002   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.287215   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.288000   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.289682   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.292005   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.292194   10730 ssh_runner.go:57] Run: sudo mkdir -p /tmp
I0127 18:06:10.353121   10730 ssh_runner.go:57] Run: docker load -i /tmp/pause-amd64_3.0
W0127 18:06:10.412560   10730 localkube_caching.go:70] Unable to check localkube checksum... continuing.
I0127 18:06:10.412577   10730 localkube_caching.go:144] Using cached localkube
E0127 18:06:10.412619   10730 start.go:234] Error updating cluster:  Error updating localkube from uri: Error creating localkube asset from url: Error opening file asset: /var/root/.minikube/cache/localkube/localkube-v1.9.0: open /var/root/.minikube/cache/localkube/localkube-v1.9.0: no such file or directory
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
  minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]: 
I0127 18:06:11.066092   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/pause-amd64_3.0
I0127 18:06:11.147366   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/k8s.gcr.io/pause-amd64_3.0 from cache
I0127 18:06:11.854868   10730 ssh_runner.go:57] Run: docker load -i /tmp/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 18:06:12.528920   10730 ssh_runner.go:57] Run: docker load -i /tmp/k8s-dns-sidecar-amd64_1.14.5
I0127 18:06:12.805365   10730 ssh_runner.go:57] Run: docker load -i /tmp/k8s-dns-kube-dns-amd64_1.14.5
I0127 18:06:13.759356   10730 ssh_runner.go:57] Run: docker load -i /tmp/kube-addon-manager_v6.5
I0127 18:06:13.861449   10730 ssh_runner.go:57] Run: docker load -i /tmp/storage-provisioner_v1.8.0
I0127 18:06:14.784853   10730 ssh_runner.go:57] Run: docker load -i /tmp/kubernetes-dashboard-amd64_v1.8.1
I0127 18:06:16.994240   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/k8s-dns-sidecar-amd64_1.14.5
I0127 18:06:17.002073   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-sidecar-amd64_1.14.5 from cache
I0127 18:06:17.283997   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/k8s-dns-dnsmasq-nanny-amd64_1.14.5
I0127 18:06:17.289844   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64_1.14.5 from cache
I0127 18:06:17.301843   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/k8s-dns-kube-dns-amd64_1.14.5
I0127 18:06:17.307659   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/k8s.gcr.io/k8s-dns-kube-dns-amd64_1.14.5 from cache
I0127 18:06:19.209019   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/storage-provisioner_v1.8.0
I0127 18:06:19.215184   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/gcr.io/k8s-minikube/storage-provisioner_v1.8.0 from cache
I0127 18:06:19.495268   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/kube-addon-manager_v6.5
I0127 18:06:19.500847   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/gcr.io/google-containers/kube-addon-manager_v6.5 from cache
I0127 18:06:19.915041   10730 ssh_runner.go:57] Run: sudo rm -rf /tmp/kubernetes-dashboard-amd64_v1.8.1
I0127 18:06:19.922892   10730 cache_images.go:220] Successfully loaded image /var/root/.minikube/cache/images/k8s.gcr.io/kubernetes-dashboard-amd64_v1.8.1 from cache
I0127 18:06:19.922935   10730 cache_images.go:99] Successfully loaded all cached images.
```
**Anything else do we need to know**:

I had minikube installed already (some time ago, for testing purposes and I was able to start it), getting back to K8S I updated minikube and now problem that I reported occurs.

**Comment by KowalczykBartek** [comment] 2018-01-27 17:26
I see that probably this is duplicated Issue to #2473 - sorry, guess that this can be removed :/

**Comment by afbjorklund** [comment] 2018-01-27 19:13
Actually #2472 but yeah

**Comment by r2d4** [comment] 2018-01-27 19:53
Duplicate of #2472

**Closed by r2d4** 2018-01-27 19:53 UTC
