### ISSUE TITLE
localkube leaks wc zombies

### ISSUE THREAD

**Issue by errordeveloper** [kubernetes/minikube#952] opened 2016-12-29 18:19 UTC
```console
ilya@laptop $ minikube version
minikube version: v0.14.0
ilya@laptop $ minikube ssh
                        ##         .
                  ## ## ##        ==
               ## ## ## ## ##    ===
           /"""""""""""""""""\___/ ===
      ~~~ {~~ ~~~~ ~~~ ~~~~ ~~~ ~ /  ===- ~~~
           \______ o           __/
             \    \         __/
              \____\_______/
 _                 _   ____     _            _
| |__   ___   ___ | |_|___ \ __| | ___   ___| | _____ _ __
| '_ \ / _ \ / _ \| __| __) / _` |/ _ \ / __| |/ / _ \ '__|
| |_) | (_) | (_) | |_ / __/ (_| | (_) | (__|   <  __/ |
|_.__/ \___/ \___/ \__|_____\__,_|\___/ \___|_|\_\___|_|
Boot2Docker version 1.11.1, build master : 901340f - Fri Jul  1 22:52:19 UTC 2016
Docker version 1.11.1, build 5604cbe
docker@minikube:~$ uptime
 18:09:26 up  5:18,  2 users,  load average: 18.59, 9.88, 5.35
docker@minikube:~$ date; pgrep -c wc 
Thu Dec 29 18:09:31 UTC 2016
1280
docker@minikube:~$ date; pgrep -c wc 
Thu Dec 29 18:09:33 UTC 2016
1281
docker@minikube:~$ date; pgrep -c wc 
Thu Dec 29 18:09:49 UTC 2016
1281
docker@minikube:~$ date; pgrep -c wc 
Thu Dec 29 18:10:48 UTC 2016
1283
docker@minikube:~$ ps -f -C wc | head
UID        PID  PPID  C STIME TTY          TIME CMD
root       311  1700  0 13:07 ?        00:00:00 [wc] <defunct>
root       353  1700  0 13:07 ?        00:00:00 [wc] <defunct>
root       358  1700  0 13:07 ?        00:00:00 [wc] <defunct>
root       477  1700  0 15:34 ?        00:00:00 [wc] <defunct>
root       549  1700  0 13:51 ?        00:00:00 [wc] <defunct>
root       559  1700  0 13:07 ?        00:00:00 [wc] <defunct>
root       685  1700  0 16:03 ?        00:00:00 [wc] <defunct>
root       724  1700  0 13:07 ?        00:00:00 [wc] <defunct>
root       730  1700  0 13:07 ?        00:00:00 [wc] <defunct>
docker@minikube:~$ ps -f 1700
UID        PID  PPID  C STIME TTY      STAT   TIME CMD
root      1700     1 12 12:51 ?        Sl    41:17 /usr/local/bin/localkube --generate-certs=false --logtostderr=true --enable-dns=false --node-ip=192.168.99.100
docker@minikube:~$ 
```

**Comment by r2d4** [comment] 2016-12-29 18:24
Closing as a dupe of #940 
See https://github.com/kubernetes/minikube/issues/940#issuecomment-268332173 for an explanation

**Closed by r2d4** 2016-12-29 18:24 UTC
