### ISSUE TITLE
Minikube v1.4.0 fails to start on macOS

### ISSUE THREAD

**Issue by dbamaster** [kubernetes/minikube#5504] opened 2019-09-30 19:27 UTC
I recently updated minikube to the latest version for macOS. I have been not able to start minikube again since the update, the problem seem to be related to a symlink.
```
[dba mastery] $  minikube version
minikube version: v1.4.0
commit: 7969c25a98a018b94ea87d949350f3271e9d64b6

[dba mastery] $  minikube start
😄  minikube v1.4.0 on Darwin 10.14.6
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🏃  Using the running virtualbox "minikube" VM ...
⌛  Waiting for the host to be provisioned ...
🐳  Preparing Kubernetes v1.16.0 on Docker 17.12.1-ce ...
🔄  Relaunching Kubernetes using kubeadm ... 

__E0930 13:21:23.045110    2878 kubeadm.go:415] failed to create compat symlinks: cmd failed: sudo ln -s /data/minikube /var/lib/minikube/etcd
ln: failed to create symbolic link '/var/lib/minikube/etcd/minikube': File exists

: Process exited with status 1

💣  Error restarting cluster: addon phase: command failed: sudo env PATH=/var/lib/minikube/binaries/v1.16.0:$PATH kubeadm init phase addon all --config /var/tmp/minikube/kubeadm.yaml
stdout: 
stderr: error execution phase addon/coredns: unable to fetch CoreDNS current installed version and ConfigMap.: multiple DNS addon deployments found: [{{ } {coredns  kube-system /apis/apps/v1/namespaces/kube-system/deployments/coredns cd50a390-db14-4eee-86ed-5ab487edf2da 176502 5 2019-08-09 04:40:25 +0000 UTC <nil> <nil> map[k8s-app:kube-dns] map[deployment.kubernetes.io/revision:1] [] []  []} {0xc000577618 &LabelSelector{MatchLabels:map[string]string{k8s-app: kube-dns,},MatchExpressions:[]LabelSelectorRequirement{},} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[k8s-app:kube-dns] map[] [] []  []} {[{config-volume {nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil &ConfigMapVolumeSource{LocalObjectReference:LocalObjectReference{Name:coredns,},Items:[]KeyToPath{KeyToPath{Key:Corefile,Path:Corefile,Mode:nil,},},DefaultMode:*420,Optional:nil,} nil nil nil nil nil nil nil nil nil}}] [] [{coredns k8s.gcr.io/coredns:1.3.1 [] [-conf /etc/coredns/Corefile]  [{dns 0 53 UDP } {dns-tcp 0 53 TCP } {metrics 0 9153 TCP }] [] [] {map[memory:{{178257920 0} {<nil>} 170Mi BinarySI}] map[cpu:{{100 -3} {<nil>} 100m DecimalSI} memory:{{73400320 0} {<nil>} 70Mi BinarySI}]} [{config-volume true /etc/coredns  <nil> }] [] &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8080 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/health,Port:{0 8080 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:0,TimeoutSeconds:1,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} nil nil /dev/termination-log File IfNotPresent &SecurityContext{Capabilities:&Capabilities{Add:[NET_BIND_SERVICE],Drop:[all],},Privileged:nil,SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:*true,AllowPrivilegeEscalation:*false,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,} false false false}] [] Always 0xc000577980 <nil> Default map[beta.kubernetes.io/os:linux] coredns coredns <nil>  false false false <nil> &PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,} []   nil default-scheduler [{CriticalAddonsOnly Exists   <nil>} {node-role.kubernetes.io/master   NoSchedule <nil>}] [] system-cluster-critical <nil> nil [] <nil> <nil> <nil> map[] []}} {RollingUpdate &RollingUpdateDeployment{MaxUnavailable:1,MaxSurge:25%,}} 0 0xc000577aa0 false 0xc000577aa4} {5 2 2 2 2 0 [{Progressing True 2019-08-09 04:40:59 +0000 UTC 2019-08-09 04:40:47 +0000 UTC NewReplicaSetAvailable ReplicaSet "coredns-5c98db65d4" has successfully progressed.} {Available True 2019-09-30 18:45:51 +0000 UTC 2019-09-30 18:45:51 +0000 UTC MinimumReplicasAvailable Deployment has minimum availability.}] <nil>}} {{ } {kube-dns  kube-system /apis/apps/v1/namespaces/kube-system/deployments/kube-dns 87d070cc-e7c6-11e8-b79a-0800271b0d5b 175405 1 2018-11-14 04:34:10 +0000 UTC <nil> <nil> map[k8s-app:kube-dns] map[deployment.kubernetes.io/revision:1] [] []  []} {0xc000577b8c &LabelSelector{MatchLabels:map[string]string{k8s-app: kube-dns,},MatchExpressions:[]LabelSelectorRequirement{},} {{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[k8s-app:kube-dns] map[] [] []  []} {[{kube-dns-config {nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil nil &ConfigMapVolumeSource{LocalObjectReference:LocalObjectReference{Name:kube-dns,},Items:[]KeyToPath{},DefaultMode:*420,Optional:*true,} nil nil nil nil nil nil nil nil nil}}] [] [{kubedns k8s.gcr.io/k8s-dns-kube-dns-amd64:1.14.8 [] [--domain=cluster.local. --dns-port=10053 --config-dir=/kube-dns-config --v=2]  [{dns-local 0 10053 UDP } {dns-tcp-local 0 10053 TCP } {metrics 0 10055 TCP }] [] [{PROMETHEUS_PORT 10055 nil}] {map[memory:{{178257920 0} {<nil>} 170Mi BinarySI}] map[cpu:{{100 -3} {<nil>} 100m DecimalSI} memory:{{73400320 0} {<nil>} 70Mi BinarySI}]} [{kube-dns-config false /kube-dns-config  <nil> }] [] &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthcheck/kubedns,Port:{0 10054 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,} &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/readiness,Port:{0 8081 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:3,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:3,} nil nil /dev/termination-log File IfNotPresent nil false false false} {dnsmasq k8s.gcr.io/k8s-dns-dnsmasq-nanny-amd64:1.14.8 [] [-v=2 -logtostderr -configDir=/etc/k8s/dns/dnsmasq-nanny -restartDnsmasq=true -- -k --cache-size=1000 --no-negcache --log-facility=- --server=/cluster.local/127.0.0.1#10053 --server=/in-addr.arpa/127.0.0.1#10053 --server=/ip6.arpa/127.0.0.1#10053]  [{dns 0 53 UDP } {dns-tcp 0 53 TCP }] [] [] {map[] map[cpu:{{150 -3} {<nil>} 150m DecimalSI} memory:{{20971520 0} {<nil>} 20Mi BinarySI}]} [{kube-dns-config false /etc/k8s/dns/dnsmasq-nanny  <nil> }] [] &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthcheck/dnsmasq,Port:{0 10054 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,} nil nil nil /dev/termination-log File IfNotPresent nil false false false} {sidecar k8s.gcr.io/k8s-dns-sidecar-amd64:1.14.8 [] [--v=2 --logtostderr --probe=kubedns,127.0.0.1:10053,kubernetes.default.svc.cluster.local,5,SRV --probe=dnsmasq,127.0.0.1:53,kubernetes.default.svc.cluster.local,5,SRV]  [{metrics 0 10054 TCP }] [] [] {map[] map[cpu:{{10 -3} {<nil>} 10m DecimalSI} memory:{{20971520 0} {<nil>} 20Mi BinarySI}]} [] [] &Probe{Handler:Handler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/metrics,Port:{0 10054 },Host:,Scheme:HTTP,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,},InitialDelaySeconds:60,TimeoutSeconds:5,PeriodSeconds:10,SuccessThreshold:1,FailureThreshold:5,} nil nil nil /dev/termination-log File IfNotPresent nil false false false}] [] Always 0xc000278410 <nil> Default map[] kube-dns kube-dns <nil>  false false false <nil> &PodSecurityContext{SELinuxOptions:nil,RunAsUser:nil,RunAsNonRoot:nil,SupplementalGroups:[],FSGroup:nil,RunAsGroup:nil,Sysctls:[]Sysctl{},WindowsOptions:nil,} []   &Affinity{NodeAffinity:&NodeAffinity{RequiredDuringSchedulingIgnoredDuringExecution:&NodeSelector{NodeSelectorTerms:[]NodeSelectorTerm{NodeSelectorTerm{MatchExpressions:[]NodeSelectorRequirement{NodeSelectorRequirement{Key:beta.kubernetes.io/arch,Operator:In,Values:[amd64],},},MatchFields:[]NodeSelectorRequirement{},},},},PreferredDuringSchedulingIgnoredDuringExecution:[]PreferredSchedulingTerm{},},PodAffinity:nil,PodAntiAffinity:nil,} default-scheduler [{CriticalAddonsOnly Exists   <nil>} {node-role.kubernetes.io/master   NoSchedule <nil>}] []  <nil> nil [] <nil> <nil> <nil> map[] []}} {RollingUpdate &RollingUpdateDeployment{MaxUnavailable:0,MaxSurge:10%,}} 0 0xc0002785f0 false 0xc0002785f4} {1 1 1 1 1 0 [{Progressing True 2018-11-14 04:35:24 +0000 UTC 2018-11-14 04:34:15 +0000 UTC NewReplicaSetAvailable ReplicaSet "kube-dns-86f4d74b45" has successfully progressed.} {Available True 2019-09-30 18:45:28 +0000 UTC 2019-09-30 18:45:28 +0000 UTC MinimumReplicasAvailable Deployment has minimum availability.}] <nil>}}]
To see the stack trace of this error execute with --v=5 or higher
: Process exited with status 1

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose
❌  Problems detected in kube-addon-manager [2b7ba8f1508f]:
    error: no objects passed trics-scraper uto apply__
```

**Comment by afbjorklund** [comment] 2019-09-30 19:39
This is the same as #5440, we should come up with a fix (maybe check exists, before symlinking?

**Comment by medyagh** [comment] 2019-10-02 19:58
I confirm this is a dupe of  https://github.com/kubernetes/minikube/issues/5440
I will close this, @dbamaster please follow this other issue for any update

**Closed by medyagh** 2019-10-02 19:58 UTC
Labels: triage/duplicate

**Comment by dbamaster** [comment] 2019-10-26 07:34
> I confirm this is a dupe of #5440
> I will close this, @dbamaster please follow this other issue for any update

Awesome, thanks!
