### ISSUE TITLE
Minikube ssh stops working.

### ISSUE THREAD

**Issue by kramarz** [kubernetes/minikube#569] opened 2016-09-12 10:53 UTC
**Minikube version** (use `minikube version`): v0.9.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Ubuntu 16.04 LTS
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikubeVM/config.json | grep DriverName`):virtualbox
- **Docker version** (e.g. `docker -v`): 1.11.2, build b9f10c9

**What happened**:
After working with minikube for short time `minikube ip`/`docker-env`/`ssh` commands stops working:
```
$:~/dev/socialwifi$ minikube ssh
E0912 12:27:41.302155    2138 ssh.go:39] Error attempting to ssh into machine:  exit status 255
```
At the same time I can still ssh to minikube using 
```
ssh docker@192.168.99.101 -i ~/.minikube/machines/minikubeVM/id_rsa
```
Also kubectl still works.

**How to reproduce it** (as minimally and precisely as possible):
I have used minikube for few hours. I called `minikube docker-env` many times from my scripts (ie. to transfer some images from local docker to minikube), Then suddenly command result in 
```
E0912 12:14:53.938589    1399 env.go:247] Error setting machine env variable(s): Something went wrong running an SSH command!
command : ip addr show
err     : exit status 255
output  : 
```

**Anything else do we need to know**:
 Sometimes it just starts to work for some time, then issue happens again.  Restarting machine also helps in the same way.

**Comment by yissachar** [comment] 2016-09-16 14:56
Seems similar to what I reported [here](https://github.com/kubernetes/minikube/issues/569), which I am still experiencing.

**Comment by kramarz** [comment] 2016-09-19 07:40
@yissachar Your link points to this issue. Can you fix it? 
BTW I am still experiencing this issue on v0.10.0

**Comment by jellonek** [comment] 2016-09-19 12:51
Looks like correct url should point to #497

**Comment by yissachar** [comment] 2016-09-19 18:15
That's the correct URL, thanks @jellonek.

I'm also still experiencing it on v10. I've deleted my VM and recreated from scratch, but that didn't help.

**Comment by r2d4** [comment] 2016-09-22 18:52
Closing as a dupe of #497

**Closed by r2d4** 2016-09-22 18:52 UTC
Labels: kind/bug
