### ISSUE TITLE
minikube hangs during start - conflicts with dnsmasq

### ISSUE THREAD

**Issue by mpern** [kubernetes/minikube#3104] opened 2018-08-31 08:56 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):

BUG REPORT

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`):
minikube version: v0.28.2
- **OS** (e.g. from /etc/os-release):
macOS 10.13.6 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`):
DriverName": "hyperkit"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
minikube-v0.28.1.iso
- **Install tools**:
- **Others**:

**What happened**:
minikube doesn't successfully start / hangs

**What you expected to happen**:
Minikube starts

**How to reproduce it** (as minimally and precisely as possible):
I've tried basically every variation:
```
minikube start -vm-driver hyperkit
minikube start --vm-driver hyperkit --bootstrapper=localkube
minikube start --vm-driver xhyve
minikube start --vm-driver xhyve --bootstrapper=localkube
minikube start --vm-driver virtualbox
minikube start --vm-driver virtualbox  --bootstrapper=localkube
```

**Output of `minikube logs` (if applicable)**:
see attachment
[minikube-logs.zip](https://github.com/kubernetes/minikube/files/2339380/minikube-logs.zip)

**Anything else do we need to know**:

~~when using `localkube` it tries to pull `k8s.gcr.io/pause-amd64:3.1`, which cannot work:~~
~~kubernetes/kubeadm#962~~
~~(check `journalctl-localkube.log` in the zip)~~

I have stopped, deleted the minikube VM and also deleted `~/.minikube` and `~/.kube` between runs.

I've only attached log files from hyperkit, the same issues pop up when using the other drivers.

**Comment by mpern** [comment] 2018-08-31 08:57
downgrading to `0.25.2` also doesnt help because of the localkube issue.

Is there any way to get minikube running on macOs??
I give up.

**Comment by mpern** [comment] 2018-08-31 09:37
so, turns out that `dnsmasq` will f*** everything up for `localkube`

```
sudo brew services stop dnsmasq
brew uninstall dnsmasq
```

at least I can now start minikube with `--bootstrapper=localkube`

**Comment by tpischke-bedag** [comment] 2018-09-05 13:38
I have the same issue with Windows 7 and VirtualBox

**Comment by tstromberg** [comment] 2018-09-19 22:18
This appears to be a dupe of #2456 - please re-open if that is not the case.

**Closed by tstromberg** 2018-09-19 22:18 UTC
Labels: dns, hung-start, kind/bug, os/macos
