### ISSUE TITLE
Error starting Minikube with Docker driver

### ISSUE THREAD

**Issue by etanshaul** [kubernetes/minikube#8893] opened 2020-07-30 17:39 UTC
Minikube 1.12.1, on OSX using the docker driver
Using Cloud Run workflows from the IDE.

**What happened**
- I was successfully running through the Cloud Run local workflows from Cloud Code: Minikube was paused, I'd start the dev session, and Minikube would successfully unpause and things worked great
- I then wanted to test out things from scratch, so I issued on the command line against my Cloud Code managed minikube binary: `minikube delete --all --purge`.
- I reran the session and got the output shown at the bottom (full verbose output: https://paste.googleplex.com/6439869599449088)

**What I tried**
- I tried running `docker system prune -a`, same error

**Docker Desktop Setup**
- 2 CPUs
- 8GB memory

```
/Users/eshaul/Library/Application Support/google-cloud-tools-java/managed-cloud-sdk/LATEST/google-cloud-sdk/bin/minikube start --profile cloud-code-minikube --keep-context true --wait false --vm-driver docker --interactive false --delete-on-failure
* [cloud-code-minikube] minikube v1.12.1 on Darwin 10.15.5
  - MINIKUBE_WANTUPDATENOTIFICATION=false
* Using the docker driver based on user configuration
* Starting control plane node cloud-code-minikube in cluster cloud-code-minikube
* Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v4-v1.18.3-docker-overlay2-amd64.tar.lz4: 2.42 MiB ...
* Stopping "cloud-code-minikube" in docker ...
* Deleting "cloud-code-minikube" in docker ...
! StartHost failed, but will try again: creating host: create: creating: create kic node: container name "cloud-code-minikube": container exited unexpectedly
* Creating docker container (CPUs=2, Memory=7918MB) ...
* Failed to start docker container. "minikube start -p cloud-code-minikube" may fix it: creating host: create: creating: create kic node: container name "cloud-code-minikube": container exited unexpectedly

! The minikube docker container exited unexpectedly.
* If you are still interested to make docker driver work. The following suggestions might help you get passed this issue:
* 
	- Prune unused docker images, volumes and abandoned containers.
* 
	- Restart your docker service
* 
	- Ensure your docker daemon has access to enough CPU/memory resources. 
* 
	- Docs https://docs.docker.com/docker-for-mac/#resources
* 
	- Delete and recreate minikube cluster
		minikube delete
		minikube start --driver=docker
* 
X error provisioning host: Failed to start host: creating host: create: creating: create kic node: container name "cloud-code-minikube": container exited unexpectedly
* 
* minikube is exiting due to an error. If the above message is not useful, open an issue:
  - https://github.com/kubernetes/minikube/issues/new/choose
```

**Comment by medyagh** [comment] 2020-07-30 17:52
this is a dupe of the update-alternative issue that been fixed by this PR on the HEAD and will be released this week

**Comment by medyagh** [comment] 2020-07-30 17:56
https://github.com/kubernetes/minikube/pull/8864

**Closed** 2020-07-30 17:56 UTC

**Comment by etanshaul** [comment] 2020-07-30 18:00
thanks @medyagh . Assuming I say in this state with minikube 1.12.1, I assume that on upgrade once the new minikube version is released it will transition smoothly into a working state?
