### ISSUE TITLE
minikube start fails to recognize VirtualBox 6.1

### ISSUE THREAD

**Issue by MarkAJanney** [kubernetes/minikube#9210] opened 2020-09-09 21:51 UTC
**Steps to reproduce the issue:** 

1. Install Oracle VirtualBox 6.1
2. Install minikube 1.13.0
3. Execute: minikube start

To judge from the output  (below) minikube is not recognizing the installed VirtualBox.

**Full output of failed command:** 
See below

**Full output of `minikube start` command used, if not already included:**
tinkerboy@rafiki56-desktop:~$ minikube start
😄  minikube v1.13.0 on Ubuntu 18.04
✨  Automatically selected the virtualbox driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
🤦  StartHost failed, but will try again: creating host: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "USER: tinkerboy VBOX_USER_HOME:\n6.1.14r140239". Please upgrade at https://www.virtualbox.org
🔥  Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: creating host: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "USER: tinkerboy VBOX_USER_HOME:\n6.1.14r140239". Please upgrade at https://www.virtualbox.org

❌  Exiting due to GUEST_PROVISION: Failed to start host: creating host: create: precreate: We support Virtualbox starting with version 5. Your VirtualBox install is "USER: tinkerboy VBOX_USER_HOME:\n6.1.14r140239". Please upgrade at https://www.virtualbox.org

😿  If the above advice does not help, please let us know: 
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Optional: Full output of `minikube logs` command:**
<details>
tinkerboy@rafiki56-desktop:~$ minikube logs
🤷  The control plane node "" does not exist.
👉  To fix this, run: "minikube start"
</details>

**Comment by afbjorklund** [comment] 2020-09-10 06:14
VirtualBox 6.1 is supported, but your installation looks weird - that was supposed to be `VBoxManage --version` output

It works fine with the standard Ubuntu `virtualbox` installation, so maybe something change in the Oracle installation ?

**Comment by afbjorklund** [comment] 2020-09-10 06:23
Nope it looks fine too.

```console
$ VBoxManage --version
6.1.14r140239
```

Wonder where this extra "USER: tinkerboy VBOX_USER_HOME:\n" output is coming from ?

**Comment by MarkAJanney** [comment] 2020-09-10 16:11
This is the standard Ubuntu installation of VirtualBox performed using
the Synaptic GUI

When I run the VirtualBox shell script it emits a line on stdout that
look similar:
	USER: tinkerboy VBOX_USER_HOME:

-----Original Message-----

**Comment by afbjorklund** [comment] 2020-09-10 17:59
Sorry, cannot reproduce. The default system version is 5.2, while you seem to have vendor version 6.1.14r140239 (from Oracle) ?

`5.2.42_Ubuntur137960`

`6.1.14r140239`

Neither has that extra output.

**Comment by medyagh** [comment] 2020-10-28 18:39
Meanwhile have you tried out newest driver Docker Driver with latest version of minikube?
you could try
minikube delete
minikube start --driver=docker

for more information on the docker driver checkout:
https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by ilya-zuyev** [comment] 2020-11-25 19:35
@MarkAJanney any update on this issue?

**Comment by tstromberg** [comment] 2020-12-09 19:18
Hopefully it's OK if I close this - there wasn't enough information to make it actionable, and some time has already passed. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Here is additional information that may be helpful to us:

* Whether the issue occurs with the latest minikube release
*  The exact `minikube start` command line used
*  The full output of the `minikube start` command, preferably with `--alsologtostderr -v=3` for extra logging.
 * The full output of `minikube logs`

Thank you for sharing your experience!

**Closed by tstromberg** 2020-12-09 19:18 UTC
Labels: co/virtualbox, kind/support, os/linux, triage/needs-information
