### ISSUE TITLE
docker: Pod evictions! Failed to admit pod <name>: node has conditions: [DiskPressure]

### ISSUE THREAD

**Issue by JuergenSimon** [kubernetes/minikube#7073] opened 2020-03-17 12:49 UTC
**The exact command to reproduce the issue**:
No command. Running a minikube and deploying a small deployment consisting of:
* A postgres instance
* A redis instance
* One application with two containers and one post-deploy hook

**The full output of the command that failed**:<details>
The application does not deploy. The pods keep getting evicted. I started the minikube with the following command to make sure enough memory and disk space are available: `minikube start --driver=docker --disk-size="30 GB" --memory="5Gb"`

Nevertheless this keeps happening. Since the hyperkit driver is also completely broken for OSX, I'm now basically at a complete standstill with minikube. 

</details>

**The output of the `minikube logs` command**:<details>
==> kubelet <==
-- Logs begin at Tue 2020-03-17 12:39:02 UTC, end at Tue 2020-03-17 12:48:35 UTC. --
Mar 17 12:44:46 minikube kubelet[2278]: W0317 12:44:46.790798    2278 eviction_manager.go:159] Failed to admit pod kindnet-jpzzf_kube-system(b63b1ee0-0fc6-428f-8e67-e357464f579c) - node has conditions: [DiskPressure]
Mar 17 12:44:46 minikube kubelet[2278]: I0317 12:44:46.988062    2278 eviction_manager.go:566] eviction manager: pod kindnet-kbjg6_kube-system(bedefb46-10cd-48ea-b8f6-325be17b6657) is evicted successfully
Mar 17 12:44:46 minikube kubelet[2278]: I0317 12:44:46.988112    2278 eviction_manager.go:190] eviction manager: pods kindnet-kbjg6_kube-system(bedefb46-10cd-48ea-b8f6-325be17b6657) evicted, waiting for pod to be cleaned up
Mar 17 12:44:47 minikube kubelet[2278]: W0317 12:44:47.029041    2278 pod_container_deletor.go:75] Container "d43937d1a4c3c92c8f08f00706520cc11667f292323f86f47a9bc58a45410599" not found in pod's containers
Mar 17 12:44:47 minikube kubelet[2278]: W0317 12:44:47.843863    2278 status_manager.go:546] Failed to update status for pod "kindnet-jpzzf_kube-system(b63b1ee0-0fc6-428f-8e67-e357464f579c)": failed to patch status "{\"metadata\":{\"uid\":\"b63b1ee0-0fc6-428f-8e67-e357464f579c\"}}" for pod "kube-system"/"kindnet-jpzzf": pods "kindnet-jpzzf" not found
Mar 17 12:44:47 minikube kubelet[2278]: W0317 12:44:47.869746    2278 eviction_manager.go:159] Failed to admit pod kindnet-v66fb_kube-system(ca0ba34d-6735-4656-ad66-4059887a3311) - node has conditions: [DiskPressure]
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.704682    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-lib-modules") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657")
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.704813    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "kindnet-token-zgqgv" (UniqueName: "kubernetes.io/secret/bedefb46-10cd-48ea-b8f6-325be17b6657-kindnet-token-zgqgv") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657")
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.704846    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "cni-cfg" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-cni-cfg") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657")
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.704971    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-xtables-lock") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657")
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.705221    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-lib-modules" (OuterVolumeSpecName: "lib-modules") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657"). InnerVolumeSpecName "lib-modules". PluginName "kubernetes.io/host-path", VolumeGidValue ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.705370    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-cni-cfg" (OuterVolumeSpecName: "cni-cfg") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657"). InnerVolumeSpecName "cni-cfg". PluginName "kubernetes.io/host-path", VolumeGidValue ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.705644    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-xtables-lock" (OuterVolumeSpecName: "xtables-lock") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657"). InnerVolumeSpecName "xtables-lock". PluginName "kubernetes.io/host-path", VolumeGidValue ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.727233    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/bedefb46-10cd-48ea-b8f6-325be17b6657-kindnet-token-zgqgv" (OuterVolumeSpecName: "kindnet-token-zgqgv") pod "bedefb46-10cd-48ea-b8f6-325be17b6657" (UID: "bedefb46-10cd-48ea-b8f6-325be17b6657"). InnerVolumeSpecName "kindnet-token-zgqgv". PluginName "kubernetes.io/secret", VolumeGidValue ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.805444    2278 reconciler.go:303] Volume detached for volume "cni-cfg" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-cni-cfg") on node "m01" DevicePath ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.805510    2278 reconciler.go:303] Volume detached for volume "xtables-lock" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-xtables-lock") on node "m01" DevicePath ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.805524    2278 reconciler.go:303] Volume detached for volume "lib-modules" (UniqueName: "kubernetes.io/host-path/bedefb46-10cd-48ea-b8f6-325be17b6657-lib-modules") on node "m01" DevicePath ""
Mar 17 12:44:48 minikube kubelet[2278]: I0317 12:44:48.805534    2278 reconciler.go:303] Volume detached for volume "kindnet-token-zgqgv" (UniqueName: "kubernetes.io/secret/bedefb46-10cd-48ea-b8f6-325be17b6657-kindnet-token-zgqgv") on node "m01" DevicePath ""
Mar 17 12:44:49 minikube kubelet[2278]: W0317 12:44:49.457608    2278 kubelet_getters.go:297] Path "/var/lib/kubelet/pods/bedefb46-10cd-48ea-b8f6-325be17b6657/volumes" does not exist
Mar 17 12:44:49 minikube kubelet[2278]: W0317 12:44:49.941155    2278 status_manager.go:546] Failed to update status for pod "kindnet-v66fb_kube-system(ca0ba34d-6735-4656-ad66-4059887a3311)": failed to patch status "{\"metadata\":{\"uid\":\"ca0ba34d-6735-4656-ad66-4059887a3311\"}}" for pod "kube-system"/"kindnet-v66fb": pods "kindnet-v66fb" not found
Mar 17 12:44:49 minikube kubelet[2278]: W0317 12:44:49.953485    2278 eviction_manager.go:159] Failed to admit pod kindnet-z7vcs_kube-system(d228d315-f1c8-46ea-86ba-a8750c9686cb) - node has conditions: [DiskPressure]
Mar 17 12:44:53 minikube kubelet[2278]: W0317 12:44:53.984354    2278 status_manager.go:546] Failed to update status for pod "kindnet-z7vcs_kube-system(d228d315-f1c8-46ea-86ba-a8750c9686cb)": failed to patch status "{\"metadata\":{\"uid\":\"d228d315-f1c8-46ea-86ba-a8750c9686cb\"}}" for pod "kube-system"/"kindnet-z7vcs": pods "kindnet-z7vcs" not found
Mar 17 12:44:54 minikube kubelet[2278]: W0317 12:44:54.002002    2278 eviction_manager.go:159] Failed to admit pod kindnet-gr4z4_kube-system(65b34975-27ea-46d1-b2ba-14a49c822c63) - node has conditions: [DiskPressure]
Mar 17 12:44:59 minikube kubelet[2278]: I0317 12:44:59.282613    2278 image_gc_manager.go:300] [imageGCManager]: Disk usage on image filesystem is at 86% which is over the high threshold (85%). Trying to free 3211083776 bytes down to the low threshold (80%).
Mar 17 12:44:59 minikube kubelet[2278]: E0317 12:44:59.299849    2278 kubelet.go:1298] Image garbage collection failed multiple times in a row: failed to garbage collect required amount of images. Wanted to free 3211083776 bytes, but freed 0 bytes
Mar 17 12:45:02 minikube kubelet[2278]: W0317 12:45:02.026029    2278 kubelet_getters.go:297] Path "/var/lib/kubelet/pods/65b34975-27ea-46d1-b2ba-14a49c822c63/volumes" does not exist
Mar 17 12:45:02 minikube kubelet[2278]: W0317 12:45:02.048876    2278 eviction_manager.go:159] Failed to admit pod kindnet-gm5s6_kube-system(b2e60da0-fed9-41f9-8fca-4f0e28494384) - node has conditions: [DiskPressure]
Mar 17 12:45:02 minikube kubelet[2278]: W0317 12:45:02.055673    2278 status_manager.go:561] Failed to delete status for pod "kindnet-gr4z4_kube-system(65b34975-27ea-46d1-b2ba-14a49c822c63)": pods "kindnet-gr4z4" not found
Mar 17 12:45:16 minikube kubelet[2278]: W0317 12:45:16.967287    2278 eviction_manager.go:395] eviction manager: timed out waiting for pods kindnet-kbjg6_kube-system(bedefb46-10cd-48ea-b8f6-325be17b6657) to be cleaned up
Mar 17 12:45:17 minikube kubelet[2278]: W0317 12:45:17.000196    2278 eviction_manager.go:330] eviction manager: attempting to reclaim ephemeral-storage
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.000267    2278 container_gc.go:85] attempting to delete unused containers
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.015352    2278 image_gc_manager.go:317] attempting to delete unused images
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.026491    2278 image_gc_manager.go:371] [imageGCManager]: Removing image "sha256:aa67fec7d7ef71445da9a84e9bc88afca2538e9a0aebcba6ef9509b7cf313d17" to free 78486107 bytes
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.120742    2278 eviction_manager.go:341] eviction manager: must evict pod(s) to reclaim ephemeral-storage
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.121010    2278 eviction_manager.go:359] eviction manager: pods ranked for eviction: kube-controller-manager-m01_kube-system(383600d5a5a800bd3691e94db5ea25cc), kube-apiserver-m01_kube-system(e6cd06b3d06392a262c0cef19b318176), etcd-m01_kube-system(3ec997b76fb6ed3b78da8e0b5676dac4), kube-scheduler-m01_kube-system(e3025acd90e7465e66fa19c71b916366), storage-provisioner_kube-system(a2b3dab6-631c-4fff-b7f3-ad02fdc998ad), coredns-6955765f44-m2dgq_kube-system(8b6a68b5-437f-4968-9e87-6131712fe984), coredns-6955765f44-mp55k_kube-system(aba70960-3106-4c53-b5da-9e3720fe75e5), kube-proxy-9mnqk_kube-system(bb395503-3fe6-4c03-b802-3264a8f8002f)
Mar 17 12:45:17 minikube kubelet[2278]: E0317 12:45:17.121045    2278 eviction_manager.go:551] eviction manager: cannot evict a critical pod kube-controller-manager-m01_kube-system(383600d5a5a800bd3691e94db5ea25cc)
Mar 17 12:45:17 minikube kubelet[2278]: E0317 12:45:17.121062    2278 eviction_manager.go:551] eviction manager: cannot evict a critical pod kube-apiserver-m01_kube-system(e6cd06b3d06392a262c0cef19b318176)
Mar 17 12:45:17 minikube kubelet[2278]: E0317 12:45:17.121075    2278 eviction_manager.go:551] eviction manager: cannot evict a critical pod etcd-m01_kube-system(3ec997b76fb6ed3b78da8e0b5676dac4)
Mar 17 12:45:17 minikube kubelet[2278]: E0317 12:45:17.121086    2278 eviction_manager.go:551] eviction manager: cannot evict a critical pod kube-scheduler-m01_kube-system(e3025acd90e7465e66fa19c71b916366)
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.495328    2278 eviction_manager.go:566] eviction manager: pod storage-provisioner_kube-system(a2b3dab6-631c-4fff-b7f3-ad02fdc998ad) is evicted successfully
Mar 17 12:45:17 minikube kubelet[2278]: I0317 12:45:17.495379    2278 eviction_manager.go:190] eviction manager: pods storage-provisioner_kube-system(a2b3dab6-631c-4fff-b7f3-ad02fdc998ad) evicted, waiting for pod to be cleaned up
Mar 17 12:45:18 minikube kubelet[2278]: W0317 12:45:18.082494    2278 status_manager.go:546] Failed to update status for pod "kindnet-gm5s6_kube-system(b2e60da0-fed9-41f9-8fca-4f0e28494384)": failed to patch status "{\"metadata\":{\"uid\":\"b2e60da0-fed9-41f9-8fca-4f0e28494384\"}}" for pod "kube-system"/"kindnet-gm5s6": pods "kindnet-gm5s6" not found
Mar 17 12:45:18 minikube kubelet[2278]: W0317 12:45:18.103283    2278 eviction_manager.go:159] Failed to admit pod kindnet-k7lrh_kube-system(04524076-3420-49c6-ae14-053fac0b083f) - node has conditions: [DiskPressure]
Mar 17 12:45:18 minikube kubelet[2278]: E0317 12:45:18.245588    2278 kubelet_pods.go:1362] Pod attempted illegal phase transition from Failed to Running: &PodStatus{Phase:Running,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:172.17.0.2,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:storage-provisioner,State:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:2,Signal:0,Reason:Error,Message:,StartedAt:2020-03-17 12:40:20.275764402 +0000 UTC,FinishedAt:2020-03-17 12:45:17.192924256 +0000 UTC,ContainerID:docker://29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547,},},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:gcr.io/k8s-minikube/storage-provisioner:v1.8.1,ImageID:docker-pullable://gcr.io/k8s-minikube/storage-provisioner@sha256:088daa9fcbccf04c3f415d77d5a6360d2803922190b675cb7fc88a9d2d91985a,ContainerID:docker://29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547,Started:nil,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:172.17.0.2,},},EphemeralContainerStatuses:[]ContainerStatus{},}
Mar 17 12:45:18 minikube kubelet[2278]: E0317 12:45:18.245926    2278 kubelet_pods.go:1362] Pod attempted illegal phase transition from Failed to Running: &PodStatus{Phase:Running,Conditions:[]PodCondition{},Message:,Reason:,HostIP:,PodIP:172.17.0.2,StartTime:<nil>,ContainerStatuses:[]ContainerStatus{ContainerStatus{Name:storage-provisioner,State:ContainerState{Waiting:nil,Running:nil,Terminated:&ContainerStateTerminated{ExitCode:2,Signal:0,Reason:Error,Message:,StartedAt:2020-03-17 12:40:20.275764402 +0000 UTC,FinishedAt:2020-03-17 12:45:17.192924256 +0000 UTC,ContainerID:docker://29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547,},},LastTerminationState:ContainerState{Waiting:nil,Running:nil,Terminated:nil,},Ready:false,RestartCount:0,Image:gcr.io/k8s-minikube/storage-provisioner:v1.8.1,ImageID:docker-pullable://gcr.io/k8s-minikube/storage-provisioner@sha256:088daa9fcbccf04c3f415d77d5a6360d2803922190b675cb7fc88a9d2d91985a,ContainerID:docker://29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547,Started:nil,},},QOSClass:BestEffort,InitContainerStatuses:[]ContainerStatus{},NominatedNodeName:,PodIPs:[]PodIP{PodIP{IP:172.17.0.2,},},EphemeralContainerStatuses:[]ContainerStatus{},}
Mar 17 12:45:18 minikube kubelet[2278]: E0317 12:45:18.266439    2278 remote_runtime.go:295] ContainerStatus "29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547" from runtime service failed: rpc error: code = Unknown desc = Error: No such container: 29db16064d5f659341560836e9da59a70113673d0d686f1cc93a268078add547
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.262710    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "tmp" (UniqueName: "kubernetes.io/host-path/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-tmp") pod "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad" (UID: "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad")
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.262806    2278 reconciler.go:183] operationExecutor.UnmountVolume started for volume "storage-provisioner-token-9gz6v" (UniqueName: "kubernetes.io/secret/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-storage-provisioner-token-9gz6v") pod "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad" (UID: "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad")
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.263259    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/host-path/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-tmp" (OuterVolumeSpecName: "tmp") pod "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad" (UID: "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad"). InnerVolumeSpecName "tmp". PluginName "kubernetes.io/host-path", VolumeGidValue ""
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.270192    2278 operation_generator.go:713] UnmountVolume.TearDown succeeded for volume "kubernetes.io/secret/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-storage-provisioner-token-9gz6v" (OuterVolumeSpecName: "storage-provisioner-token-9gz6v") pod "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad" (UID: "a2b3dab6-631c-4fff-b7f3-ad02fdc998ad"). InnerVolumeSpecName "storage-provisioner-token-9gz6v". PluginName "kubernetes.io/secret", VolumeGidValue ""
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.363136    2278 reconciler.go:303] Volume detached for volume "tmp" (UniqueName: "kubernetes.io/host-path/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-tmp") on node "m01" DevicePath ""
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.363192    2278 reconciler.go:303] Volume detached for volume "storage-provisioner-token-9gz6v" (UniqueName: "kubernetes.io/secret/a2b3dab6-631c-4fff-b7f3-ad02fdc998ad-storage-provisioner-token-9gz6v") on node "m01" DevicePath ""
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.496240    2278 eviction_manager.go:403] eviction manager: pods storage-provisioner_kube-system(a2b3dab6-631c-4fff-b7f3-ad02fdc998ad) successfully cleaned up
Mar 17 12:45:19 minikube kubelet[2278]: W0317 12:45:19.507237    2278 eviction_manager.go:330] eviction manager: attempting to reclaim ephemeral-storage
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.507292    2278 container_gc.go:85] attempting to delete unused containers
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.533198    2278 image_gc_manager.go:317] attempting to delete unused images
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.544645    2278 image_gc_manager.go:371] [imageGCManager]: Removing image "sha256:4689081edb103a9e8174bf23a255bfbe0b2d9ed82edc907abab6989d1c60f02c" to free 80815640 bytes
Mar 17 12:45:19 minikube kubelet[2278]: I0317 12:45:19.570517    2278 eviction_manager.go:337] eviction manager: able to reduce ephemeral-storage pressure without evicting pods.
Mar 17 12:45:50 minikube kubelet[2278]: W0317 12:45:50.133749    2278 eviction_manager.go:159] Failed to admit pod kindnet-247wb_kube-system(a649ef87-06f1-44b7-a64f-dbd11c49c393) - node has conditions: [DiskPressure]
Mar 17 12:46:54 minikube kubelet[2278]: W0317 12:46:54.138169    2278 eviction_manager.go:159] Failed to admit pod kindnet-cp5nm_kube-system(7ccce0e8-a7f6-4425-90d6-86ce14a37e58) - node has conditions: [DiskPressure]

</details>

**The operating system version**:
macOS High Sierra 10.13.6 (17G9016)

**Comment by tstromberg** [comment] 2020-03-18 14:51
It looks like the Docker environment is out of disk space:

```
Mar 17 12:44:46 minikube kubelet[2278]: W0317 12:44:46.790798 2278 eviction_manager.go:159] Failed to admit pod kindnet-jpzzf_kube-system(b63b1ee0-0fc6-428f-8e67-e357464f579c) - node has conditions: [DiskPressure]
```

I'm not yet familiar with the Docker driver, but maybe @medyagh @josedonizetti  @priyawadhwa have advice here. Naivelly, I might try selecting a larger `--disk` size or trying to prune Docker images on your macOS host:

https://docs.docker.com/engine/reference/commandline/image_prune/

**Comment by tstromberg** [comment] 2020-03-18 17:17
I'm pretty surre this is a dupe of #6820

Can you run `docker system prune` to see if it helps?

**Comment by tstromberg** [comment] 2020-04-01 21:02
This issue appears to be a duplicate of #6820, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-04-01 21:02 UTC
Labels: cause/resource-exhaustion, co/docker-driver, co/docker-env, ev/eviction, triage/support
