### ISSUE TITLE
enable ingress

### ISSUE THREAD

**Issue by daddykeba** [kubernetes/minikube#10448] opened 2021-02-11 13:51 UTC
**Steps to reproduce the issue:** 

1.
2. 
3.

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**

**Optional: Full output of `minikube logs` command:**
<details>

</details>

**Comment by sharifelgamal** [comment] 2021-02-12 22:32
Closing as duplicate of #10447

**Closed by sharifelgamal** 2021-02-12 22:32 UTC
