### ISSUE TITLE
minikube

### ISSUE THREAD

**Issue by vivek625** [kubernetes/minikube#14594] opened 2022-07-15 18:57 UTC
### What Happened?

minikube logs --file=log.txt

### Attach the log file

minikube logs --file=log.txt

**Comment by spowelljr** [comment] 2022-07-15 21:06
Thank you for sharing your experience!

Could you please run `minikube logs --file=logs.txt` and drag and drop the file into this issue.

This will help us isolate the problem further, thank you!

**Comment by vivek625** [comment] 2022-07-16 04:50
same problem

**Comment by spowelljr** [comment] 2022-07-25 17:47
Duplicate of https://github.com/kubernetes/minikube/issues/14595, closing

**Closed by spowelljr** 2022-07-25 17:47 UTC
Labels: kind/support, triage/needs-information
