### ISSUE TITLE
Unable to start minikube with VirtualBox

### ISSUE THREAD

**Issue by akgowda** [kubernetes/minikube#13411] opened 2022-01-20 19:09 UTC
### What Happened?
host only interface not created within range of cidr

```
 minikube start --driver=virtualbox --host-only-cidr='192.168.56.1/24'
😄  minikube v1.25.0 on Darwin 12.1
🆕  Kubernetes 1.23.1 is now available. If you would like to upgrade, specify: --kubernetes-version=v1.23.1
✨  Using the virtualbox driver based on existing profile
👍  Starting control plane node minikube in cluster minikube
🔄  Restarting existing virtualbox VM for "minikube" ...
🤦  StartHost failed, but will try again: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet0 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp

🔄  Restarting existing virtualbox VM for "minikube" ...
😿  Failed to start virtualbox VM. Running "minikube delete" may fix it: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet1 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp


❌  Exiting due to GUEST_PROVISION: Failed to start host: driver start: Error setting up host only network on machine start: /usr/local/bin/VBoxManage hostonlyif ipconfig vboxnet1 --ip 192.168.99.1 --netmask 255.255.255.0 failed:
VBoxManage: error: Code E_ACCESSDENIED (0x80070005) - Access denied (extended info not available)
VBoxManage: error: Context: "EnableStaticIPConfig(Bstr(pszIp).raw(), Bstr(pszNetmask).raw())" at line 242 of file VBoxManageHostonly.cpp


╭───────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                           │
│    😿  If the above advice does not help, please let us know:                             │
│    👉  https://github.com/kubernetes/minikube/issues/new/choose                           │
│                                                                                           │
│    Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                           │
╰───────────────────────────────────────────────────────────────────────────────────────────╯
```

### Attach the log file

unable to get logs

### Operating System

macOS (Default)

### Driver

VirtualBox

**Comment by akgowda** [comment] 2022-01-20 19:11
I've tried reinstall of virtualbox and minikube. Both are not working.

**Comment by afbjorklund** [comment] 2022-01-20 22:14
Looks like https://www.virtualbox.org/ticket/20626

**Comment by afbjorklund** [comment] 2022-01-20 22:20
Duplicate of:

* #12765

**Comment by spowelljr** [comment] 2022-01-25 19:25
Hi @akgowda, as noted in the PR @afbjorklund lined, `192.168.56.1/24` is no longer in the range allowed since VirtualBox 6.1.28.

You can try a different allowed range such as `minikube start --driver=virtualbox --host-only-cidr='192.168.59.1/24'`.

I'm going to close this issue, but you have more questions feel free to respond and reopen the issue, thanks!

**Closed by spowelljr** 2022-01-25 19:25 UTC
Labels: kind/bug, co/virtualbox, triage/duplicate
