### ISSUE TITLE
 Cannot start a kubernetes cluster with --feature-gates=AllAlpha=true

### ISSUE THREAD

**Issue by taherv** [kubernetes/minikube#3131] opened 2018-09-14 17:02 UTC
https://github.com/kubernetes/minikube/issues/1962#issuecomment-421334852

This is still a problem, why can't I enable all FeatureGates in minikube ?

**Comment by tstromberg** [comment] 2018-09-18 20:37
Duplicate of #1962 1962

**Closed by tstromberg** 2018-09-18 20:37 UTC
