### ISSUE TITLE
minikube fails to start...minikube vm waiting for login..macOS 10.12.6 VMWareFusion 8.5.8

### ISSUE THREAD

**Issue by evillgenius75** [kubernetes/minikube#1826] opened 2017-08-16 13:17 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
Bug Report

Please provide the following details:

**Environment**:

**Minikube version** (use `minikube version`): minikube version: v0.21.0
- **OS** (e.g. from /etc/os-release): macOS 10.12.6 (16G29)
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): "DriverName": "vmwarefusion"
- **ISO version** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep -i ISO` or `minikube ssh cat /etc/VERSION`):
"ISO": "/Users/edvilla/.minikube/machines/minikube/boot2docker.iso",
        "Boot2DockerURL": "file:///Users/edvilla/.minikube/cache/iso/minikube-v0.23.0.iso",
        "ConfigDriveISO": "",
- **Install tools**:
- **Others**:

**What happened**:
After first install vm boots completely and kubectl is registered and works with no issues. After a successful minikube stop, after trying to start again, the VM will stop at asking for login. The terminal shows as follows:
`➜ minikube start --vm-driver=vmwarefusion
Starting local Kubernetes v1.7.0 cluster...
Starting VM...
E0816 09:00:48.144984   11457 start.go:129] Error starting host: Temporary Error: Error configuring auth on host: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded.

 Retrying.`

**What you expected to happen**:
minikube vm auto logs in and SSH tunnel is established
**How to reproduce it** (as minimally and precisely as possible):

**Output of `minikube logs` (if applicable)**:

**Anything else do we need to know**:
If I delete the ~/.minikube directory and delete the vm manually from VMware fusion, I can launch again with no issues, just first run.

**Comment by cbandy** [comment] 2017-09-01 15:13
Related to #1382, maybe?

**Comment by joshk0** [comment] 2017-09-15 14:49
Yes, it is almost certainly a duplicate.

**Comment by r2d4** [comment] 2017-09-15 22:40
closing as a dupe of #1382

**Closed by r2d4** 2017-09-15 22:40 UTC
Labels: driver/vmwarefusion, kind/bug
