### ISSUE TITLE
i have this kind of issue but i did everything by instructions on websyte

### ISSUE THREAD

**Issue by JakhongirAlimov** [kubernetes/minikube#14213] opened 2022-05-23 14:01 UTC
StartHost failed, but will try again: creating host: create: precreate: This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...

**Comment by spowelljr** [comment] 2022-06-09 18:47
Duplicate of https://github.com/kubernetes/minikube/issues/14212

**Closed by spowelljr** 2022-06-09 18:47 UTC
