### ISSUE TITLE
Unable to start Minikube on Ubuntu 20.04.3 LTS

### ISSUE THREAD

**Issue by MartinFuerstenau** [kubernetes/minikube#12347] opened 2021-08-24 16:55 UTC
I followed the starter  https://minikube.sigs.k8s.io/docs/start/
Trying to start minikube results in

`Exiting due to GUEST_START: wait 6m0s for node: wait for healthy API server: controlPlane never updated to v1.22.0` 

**Steps to reproduce the issue:** 

1. minikube start --alsologtostderr -v=4

**Full output of `minikube logs` command:**
[minikube.logs.txt](https://github.com/kubernetes/minikube/files/7040763/minikube.logs.txt)

**Full output of failed command:**
[lastStart.txt](https://github.com/kubernetes/minikube/files/7040749/lastStart.txt)

**Comment by RA489** [comment] 2021-08-25 04:32
@MartinFuerstenau could you please install latest version of minikube?

**Comment by spowelljr** [comment] 2021-08-30 21:40
Hi @MartinFuerstenau, thanks for reporting your issue with minikube!

This is an existing issue we're aware of (#8765) but have not yet fixed. The current work around is to run minikube delete --all --purge which will clear out the minikube configuration files.

Let me know if that solves your issue, thanks!

**Comment by spowelljr** [comment] 2021-09-08 20:06
Since this issue is a duplicate of #8765 I'm going to close this one. Please feel free to follow along and contribute to #8765, thanks!

**Closed by spowelljr** 2021-09-08 20:06 UTC
Labels: triage/duplicate
