### ISSUE TITLE
Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition

### ISSUE THREAD

**Issue by veterancj** [kubernetes/minikube#4725] opened 2019-07-10 01:50 UTC
Error restarting cluster: wait: waiting for component=kube-apiserver: timed out waiting for the condition? rese

**Comment by tstromberg** [comment] 2019-07-16 20:25
Thank you for sharing your experience! If you don't mind, could you please provide:

*  The exact command-lines used, so that we may replicate the issue 
*  The full output of the command that failed
*  The full output of the "minikube logs" command
*  Which operating system version was used

This will help us isolate the problem further. Thank you!

**Comment by tstromberg** [comment] 2019-07-16 20:27
Likely a dupe of #4272 / #4366

**Comment by tstromberg** [comment] 2019-08-23 00:02
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!

**Closed by tstromberg** 2019-08-23 00:02 UTC
Labels: ev/apiserver-timeout, triage/needs-information
