### ISSUE TITLE
hyperkit post reboot: dial tcp ip:22: connect: operation timed out

### ISSUE THREAD

**Issue by CelloFlaut** [kubernetes/minikube#3957] opened 2019-03-25 13:45 UTC
scenario:
  fully functional Minikube, working for some time.  Love it, thanks for creating!

command-line: 
  AFTER reboot of MAC, just a normal start from a pre-existing system

  $  minikube start  

output:
😄  minikube v0.35.0 on darwin (amd64)
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Restarting existing hyperkit VM for "minikube" ...
⌛  Waiting for SSH access ...

(Note: this hangs indefinitely)

$ minikube logs
  (Waits a long time, then)
💣  command runner: getting ssh client for bootstrapper: Error dialing tcp via ssh client: dial tcp 192.168.64.4:22: connect: operation timed out

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new
$ minikube status
  (waits a long time, then)
$ minikube status
host: Stopped
kubelet:
apiserver:
kubectl:

Output of "config.json"
{
    "cpus": 3,
    "memory": 4096,
    "registry-creds": true,
    "vm-driver": "hyperkit"
}
setup: 
  MacOS, Mojave 10.14.3, minikube installed with brew, version v0.35.0... MIGHT be related to Mojave update, but it usually fails after reboot, even with out Mojave Update.

Note:
  Removing the existing cluster, and starting again does work, but that means all work I have done needs to be reproduced from scratch.  It would be nicer if it started with existing data.
  I have tried with VMWare versions as well, same thing.
  If no one else has this problem, then it might be with some low level Mac network data not being stored on my particular machine on reboot? 
Thanks,

**Comment by paultiplady** [comment] 2019-03-25 18:24
I'm seeing this too, also on hyperkit driver.

**Comment by tstromberg** [comment] 2019-03-25 18:53
I suspect this may be due to an old or incompatible hyperkit driver. Do you mind running:

`ls -la /usr/local/bin/docker-machine-driver-hyperkit`

Usually this can be fixed by installing our latest minikube hyperkit driver - please let me know if it helps for you:

`curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \ && sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/`

Thanks for the feedback!

**Comment by paultiplady** [comment] 2019-03-25 23:24
`-rwsr-xr-x  1 root  wheel  27219380 Nov 16 09:40 /usr/local/bin/docker-machine-driver-hyperkit`

**Comment by paultiplady** [comment] 2019-03-25 23:25
I'll give that a spin

**Comment by tstromberg** [comment] 2019-03-26 02:03
Any luck?

**Comment by CelloFlaut** [comment] 2019-03-26 12:31
lrwxr-xr-x  1 jg1555  admin  81 Feb 20 14:33 /usr/local/bin/docker-machine-driver-hyperkit -> ../Cellar/docker-machine-driver-hyperkit/1.0.0/bin/docker-machine-driver-hyperkit

**Comment by CelloFlaut** [comment] 2019-03-26 13:45
Yes, thank you very much.  Was forced a reboot, so I tried this while I was at it.  Minikube came right up.  Thanks so much!

**Comment by tstromberg** [comment] 2019-03-26 13:54
The awkward and embarrassing part here is that there are 3 implementations of docker-machine-driver-hyperkit, that all install to the same path:

- The version that ships with Docker for Desktop
- The machine-drivers fork (last updated in March 2018, which brew installs)
- The minikube fork (last updated 19 days ago)

#3939 will at least combine the latter two, and #3975 should make the experience more user-friendly. Your feedback on if this upgrade will let me know if we are barking up the right tree here.

**Comment by CelloFlaut** [comment] 2019-03-26 13:55
Good.  And this is great stuff.  Really appreciate your work.

**Comment by tstromberg** [comment] 2019-03-26 16:16
The feedback I'd like to know is if this command resolves the problem:

```
curl -LO https://storage.googleapis.com/minikube/releases/latest/docker-machine-driver-hyperkit \
  && sudo install -o root -g wheel -m 4755 docker-machine-driver-hyperkit /usr/local/bin/
```

**Comment by paultiplady** [comment] 2019-03-26 19:03
Yep, can confirm that installing the new hyperkit driver fixes the problem for me.

Wonder if it's worth doing a compatibility check on `minikube start`, to catch this? It's a pretty opaque / confusing failure from the user's perspective (especially since the cluster started correctly first time round).

Thanks for the quick support!

**Comment by balopat** [comment] 2019-04-04 23:14
Thank you!! 
Marking this overall as a dupe of #3975 - as it has a clear action for resolving the hyperkit packaging headache.

**Closed by balopat** 2019-04-04 23:14 UTC
Labels: co/hyperkit
