### ISSUE TITLE
minikube start issue in ubuntu 20.04

### ISSUE THREAD

**Issue by shramikawale** [kubernetes/minikube#8860] opened 2020-07-28 03:48 UTC
😄  minikube v1.11.0 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.2 ...
E0728 09:30:38.000600    8982 start.go:94] Unable to get host IP: inspect IP bridge network "54cc310d3638\n90986ed497e5".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 54cc310d3638
90986ed497e5: exit status 1
stdout:

stderr:
Error: No such network: 54cc310d3638
90986ed497e5

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "54cc310d3638\n90986ed497e5".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 54cc310d3638
90986ed497e5: exit status 1
stdout:

stderr:
Error: No such network: 54cc310d3638
90986ed497e5

**Comment by afbjorklund** [comment] 2020-08-05 21:06
Duplicate of #8131

**Closed** 2020-08-07 12:12 UTC
Labels: co/docker-driver, triage/duplicate
