### ISSUE TITLE
Impossible to enable ingress addon

### ISSUE THREAD

**Issue by MrMic** [kubernetes/minikube#12002] opened 2021-07-19 09:47 UTC
**Steps to reproduce the issue:** 

$> minikube start

-> kubernetes = 1.21.2

**Full output of `minikube logs` command:**
$> minikube addons enable ingress

    ▪ Utilisation de l'image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Utilisation de l'image docker.io/jettech/kube-webhook-certgen:v1.5.1
    ▪ Utilisation de l'image k8s.gcr.io/ingress-nginx/controller:v0.44.0
🔎  Vérification du module ingress...

❌  Fermeture en raison de MK_ADDON_ENABLE : run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]

[minikube_addons_ad4707d14c7527e8b492788efa251872a7cd24ef_0.log](https://github.com/kubernetes/minikube/files/6839721/minikube_addons_ad4707d14c7527e8b492788efa251872a7cd24ef_0.log)

**Comment by coolamiy** [comment] 2021-07-23 00:03
Try with minimube start —vm=true

**Comment by MrMic** [comment] 2021-07-23 07:43
That does not solve the issue ... :/

**Comment by coolamiy** [comment] 2021-07-23 09:03
try  the following commands 
minikube delete --all 
minikube start --vm=true 
minikube addons enable ingress

**Comment by MrMic** [comment] 2021-07-23 09:50
In fact, I have deleted all and start from scratch.
$> rm -rf .minikube/

But unfortunately, I got the same issue!!!
I join the log to help to troubleshoot.

[minikube_addons_ad4707d14c7527e8b492788efa251872a7cd24ef_0.log](https://github.com/kubernetes/minikube/files/6867920/minikube_addons_ad4707d14c7527e8b492788efa251872a7cd24ef_0.log)

**Comment by apupier** [comment] 2021-07-29 12:27
sounds duplicate of https://github.com/kubernetes/minikube/issues/10544

**Comment by MrMic** [comment] 2021-07-29 15:04
After restarting my computer, seems to work now ...
If it still works in a few days, I will close the issue.
Do not know what happened ...
Weird.

**Comment by spowelljr** [comment] 2021-08-06 19:03
Hi @MrMic, since you haven't responded I'm going to assume that it's continuing to work, so I'm going to close this issue. If the problem comes back feel free to reopen, thanks!

**Closed by spowelljr** 2021-08-06 19:03 UTC
Labels: kind/support

**Comment by MrMic** [comment] 2021-08-06 19:20
Hi,

- I was just waiting if It still works.
- It is OK.
- Indeed, you can close the ticket.

Sorry to have not updated this more recently.
My bad.
Rgds,
