### ISSUE TITLE
minikube crash

### ISSUE THREAD

**Issue by aditama2019** [kubernetes/minikube#4246] opened 2019-05-13 08:32 UTC
**The exact command to reproduce the issue**:

**The full output of the command that failed**:

**The output of the `minikube logs` command**:

**The operating system version**:

**Comment by aditama2019** [comment] 2019-05-13 08:33
minikube start --vm-driver kvm2 

out put
 </devices>
</domain>
: virError(Code=8, Domain=44, Message='invalid argument: could not find capabilities for domaintype=kvm ')

*   Sorry that minikube crashed. If this was unexpected, we would love to hear from you:

**Comment by RA489** [comment] 2019-05-14 05:32
@aditama2019  Do you mind attaching
1. Which operating system version was used?
2. The output of the "minikube logs" command?

**Comment by tstromberg** [comment] 2019-05-15 03:54
Dupe of #4247

**Closed by tstromberg** 2019-05-15 03:54 UTC
