### ISSUE TITLE
hostNetwork & ClusterFirstWithHostNet issue when using --vm-driver=none

### ISSUE THREAD

**Issue by gustavomassa** [kubernetes/minikube#4484] opened 2019-06-13 19:18 UTC
SO: Linux Mint 19.1 Cinnamon
Linux Kernel: 5.0.5-050005-generic
Minikube version: 1.1.0
![image](https://user-images.githubusercontent.com/16235598/59461051-de25c800-8df6-11e9-8282-845b57dfea7a.png)

minikube start --vm-driver=none

When using minikube with none driver, setting hostNetwork and ClusterFirstWithHostNet result on dns lookup error. Removing the dns policy and setting just the hostNetwork works fine.

`Error: getaddrinfo EAI_AGAIN`

Documentation: https://kubernetes.io/docs/concepts/services-networking/dns-pod-service/
![image](https://user-images.githubusercontent.com/16235598/59461331-876cbe00-8df7-11e9-977f-8b7fd36b9071.png)

**Comment by tstromberg** [comment] 2019-07-17 22:40
Thanks for reporting this! Do you mind clarifying exactly how to reproduce this environment and error message? I don't quite follow.

Also, please include the output of `minikube logs`

**Comment by tstromberg** [comment] 2019-08-23 00:05
Regrettably, there isn't enough information in this issue to make it actionable. Since some time has passed, I'm going to close this issue. If you are able to provide additional details, you may reopen it at any point by adding /reopen to your comment.

Thank you for sharing your experience!

**Closed by tstromberg** 2019-08-23 00:05 UTC
Labels: area/dns, co/none-driver, triage/needs-information
