### ISSUE TITLE
Failed to setup kubeconfig: writing kubeconfig: Error writing file : open : no such file or directory

### ISSUE THREAD

**Issue by cs-wang** [kubernetes/minikube#5268] opened 2019-09-05 10:16 UTC
**The exact command to reproduce the issue**:
# minikube start -v 8 -p hostcluster --kubernetes-version='v1.14.0'  --vm-driver=none

**The full output of the command that failed**:<details>
* [hostcluster] minikube v1.3.1 on Centos 7.6.1810 (vbox/amd64)
* Running on localhost (CPUs=4, Memory=3789MB, Disk=37861MB) ...
Reading certificate data from /root/.minikube/certs/ca.pem
Decoding PEM data...
Parsing certificate...
Reading certificate data from /root/.minikube/certs/cert.pem
Decoding PEM data...
Parsing certificate...
Couldn't set key CPE_NAME, no corresponding struct field found
Couldn't set key , no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT, no corresponding struct field found
Couldn't set key CENTOS_MANTISBT_PROJECT_VERSION, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT, no corresponding struct field found
Couldn't set key REDHAT_SUPPORT_PRODUCT_VERSION, no corresponding struct field found
Couldn't set key , no corresponding struct field found
* OS release is CentOS Linux 7 (Core)
* Preparing Kubernetes v1.14.0 on Docker 18.09.6 ...
*
X Failed to setup kubeconfig: writing kubeconfig: Error writing file : open : no such file or directory
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>
*
X Error getting config: stat /root/.minikube/profiles/minikube/config.json: no such file or directory
*
* Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
  - https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The operating system version**:
Linux localhost.localdomain 3.10.0-957.el7.x86_64 #1 SMP Thu Nov 8 23:39:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

the /var/log/message
Sep  5 17:37:44 localhost systemd: Started Kubernetes systemd probe.
Sep  5 17:37:44 localhost kubelet: I0905 17:37:44.834372    8748 server.go:417] Version: v1.14.0
Sep  5 17:37:44 localhost kubelet: I0905 17:37:44.835739    8748 plugins.go:103] No cloud provider specified.
Sep  5 17:37:44 localhost kubelet: F0905 17:37:44.835854    8748 server.go:265] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Sep  5 17:37:44 localhost systemd: kubelet.service: main process exited, code=exited, status=255/n/a
Sep  5 17:37:44 localhost systemd: Unit kubelet.service entered failed state.
Sep  5 17:37:44 localhost systemd: kubelet.service failed.

**Comment by tstromberg** [comment] 2019-09-05 16:52
I believe this is a dupe of #4100 - which is fixed at head. I suspect this is because there is an invalid KUBECONFIG environment variable set.

Do you mind sharing:

- The exact command line you used to start minikube
- The output of `env | grep KUBE` (if you are using minikube with `sudo`, then use `sudo env | grep KUBE`

Please let me know if this helps.

**Comment by cs-wang** [comment] 2019-09-06 02:10
great, problem resolved after unset KUBECONFIG, thanks a lot!!!

**Closed** 2019-09-06 02:11 UTC
Labels: triage/support

**Comment by muctarr-rahim** [comment] 2019-09-24 17:06
How do you unset kubeconfig
