### ISSUE TITLE
none: StartHost: detecting provisioner: Too many retries waiting for SSH to be available

### ISSUE THREAD

**Issue by songdongsheng** [kubernetes/minikube#5265] opened 2019-09-05 05:25 UTC
**The exact command to reproduce the issue**:

minikube start --vm-driver=none --kubernetes-version='v1.15.3'

**The full output of the command that failed**:<details>

# minikube start --vm-driver=none --kubernetes-version='v1.15.3'
😄  minikube v1.3.1 on Debian 10.1
💡  Tip: Use 'minikube start -p <name>' to create a new cluster, or 'minikube delete' to delete this one.
🔄  Starting existing none VM for "minikube" ...
⌛  Waiting for the host to be provisioned ...
E0905 13:20:37.185867  141745 start.go:723] StartHost: detecting provisioner: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

💣  Unable to start VM: detecting provisioner: Too many retries waiting for SSH to be available.  Last error: Maximum number of retries (60) exceeded

😿  Sorry that minikube crashed. If this was unexpected, we would love to hear from you:
👉  https://github.com/kubernetes/minikube/issues/new/choose

</details>

**The output of the `minikube logs` command**:<details>

# minikube logs
==> Docker <==
-- Logs begin at Fri 2019-08-30 21:34:29 CST, end at Thu 2019-09-05 19:23:42 CST. --
Sep 05 11:46:49 k8s-buster systemd[1]: Failed to start Docker Application Container Engine.
Sep 05 11:46:51 k8s-buster systemd[1]: Starting Docker Application Container Engine...
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.409108300+08:00" level=info msg="Starting up"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.409571000+08:00" level=warning msg="[!] DON'T BIND ON ANY IP ADDRESS WITHOUT setting --tlsverify IF YOU DON'T KNOW WHAT YOU'RE DOING [!]"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.410867800+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.411075200+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.411191900+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.411316100+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.411554200+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008195a0, CONNECTING" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.411640500+08:00" level=info msg="blockingPicker: the picked transport is not ready, loop back to repick" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412291500+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc0008195a0, READY" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412818300+08:00" level=info msg="parsed scheme: \"unix\"" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412842300+08:00" level=info msg="scheme \"unix\" not registered, fallback to default scheme" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412873200+08:00" level=info msg="ccResolverWrapper: sending update to cc: {[{unix:///run/containerd/containerd.sock 0  <nil>}] }" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412881100+08:00" level=info msg="ClientConn switching balancer to \"pick_first\"" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.412918400+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000906bb0, CONNECTING" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.413263900+08:00" level=info msg="pickfirstBalancer: HandleSubConnStateChange: 0xc000906bb0, READY" module=grpc
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.445650400+08:00" level=warning msg="Your kernel does not support swap memory limit"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.445902800+08:00" level=warning msg="Your kernel does not support cgroup rt period"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.446028600+08:00" level=warning msg="Your kernel does not support cgroup rt runtime"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.446135400+08:00" level=warning msg="Your kernel does not support cgroup blkio weight"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.446242800+08:00" level=warning msg="Your kernel does not support cgroup blkio weight_device"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.446478600+08:00" level=info msg="Loading containers: start."
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.738443100+08:00" level=info msg="Default bridge (docker0) is assigned with an IP address 172.17.0.0/16. Daemon option --bip can be used to set a preferred IP address"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.809791100+08:00" level=info msg="Loading containers: done."
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.849805700+08:00" level=info msg="Docker daemon" commit=6a30dfc graphdriver(s)=overlay2 version=19.03.2
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.850225200+08:00" level=info msg="Daemon has completed initialization"
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.875162800+08:00" level=info msg="API listen on [::]:2375"
Sep 05 11:46:51 k8s-buster systemd[1]: Started Docker Application Container Engine.
Sep 05 11:46:51 k8s-buster dockerd[33951]: time="2019-09-05T11:46:51.875220500+08:00" level=info msg="API listen on /var/run/docker.sock"

==> container status <==
time="2019-09-05T13:24:19+08:00" level=fatal msg="failed to connect: failed to connect: context deadline exceeded"
CONTAINER ID        IMAGE               COMMAND             CREATED             STATUS              PORTS               NAMES

==> dmesg <==
[  +0.017714] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 11:55] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.010886] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:00] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.003392] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:05] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.005993] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:10] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.004703] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:15] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.003734] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:20] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.002727] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:25] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.001916] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:30] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.012723] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:35] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.011577] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:40] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.002459] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:45] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.005046] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:50] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[  +0.000572] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 12:55] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 13:00] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 13:05] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 13:10] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.
[Sep 5 13:15] hv_balloon: Balloon request will be partially fulfilled. Balloon floor reached.

==> kernel <==
 13:24:19 up  2:03,  1 user,  load average: 0.13, 0.18, 0.18
Linux k8s-buster 5.2.0-0.bpo.2-amd64 #1 SMP Debian 5.2.9-2~bpo10+1 (2019-08-25) x86_64 GNU/Linux
PRETTY_NAME="Debian GNU/Linux 10 (buster)"

==> kubelet <==
-- Logs begin at Fri 2019-08-30 21:34:29 CST, end at Thu 2019-09-05 19:23:42 CST. --
Sep 05 13:24:18 k8s-buster systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Sep 05 13:24:18 k8s-buster systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:18 k8s-buster kubelet[148011]: I0905 13:24:18.355049  148011 server.go:425] Version: v1.15.3
Sep 05 13:24:18 k8s-buster kubelet[148011]: I0905 13:24:18.355220  148011 plugins.go:103] No cloud provider specified.
Sep 05 13:24:18 k8s-buster kubelet[148011]: F0905 13:24:18.355244  148011 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Sep 05 13:24:18 k8s-buster systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 05 13:24:18 k8s-buster systemd[1]: kubelet.service: Failed with result 'exit-code'.
Sep 05 13:24:19 k8s-buster systemd[1]: kubelet.service: Service RestartSec=600ms expired, scheduling restart.
Sep 05 13:24:19 k8s-buster systemd[1]: kubelet.service: Scheduled restart job, restart counter is at 9520.
Sep 05 13:24:19 k8s-buster systemd[1]: Stopped kubelet: The Kubernetes Node Agent.
Sep 05 13:24:19 k8s-buster systemd[1]: Started kubelet: The Kubernetes Node Agent.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --authorization-mode has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --cgroup-driver has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --client-ca-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --cluster-dns has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --cluster-domain has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --fail-swap-on has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: Flag --pod-manifest-path has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See https://kubernetes.io/docs/tasks/administer-cluster/kubelet-config-file/ for more information.
Sep 05 13:24:19 k8s-buster kubelet[148021]: I0905 13:24:19.122021  148021 server.go:425] Version: v1.15.3
Sep 05 13:24:19 k8s-buster kubelet[148021]: I0905 13:24:19.122531  148021 plugins.go:103] No cloud provider specified.
Sep 05 13:24:19 k8s-buster kubelet[148021]: F0905 13:24:19.122585  148021 server.go:273] failed to run Kubelet: unable to load bootstrap kubeconfig: stat /etc/kubernetes/bootstrap-kubelet.conf: no such file or directory
Sep 05 13:24:19 k8s-buster systemd[1]: kubelet.service: Main process exited, code=exited, status=255/EXCEPTION
Sep 05 13:24:19 k8s-buster systemd[1]: kubelet.service: Failed with result 'exit-code'.

</details>

**The operating system version**:

    # cat /etc/debian_version
    10.1

**Comment by tstromberg** [comment] 2019-09-05 17:05
This issue appears to be a duplicate of #4132, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed** 2019-09-05 17:05 UTC
Labels: triage/duplicate
