### ISSUE TITLE
enabling CNI is broken coreDNS doesnt come up.

### ISSUE THREAD

**Issue by medyagh** [kubernetes/minikube#7466] opened 2020-04-07 01:28 UTC
CNI is broken on head:

after adding ew wait component in this PR https://github.com/kubernetes/minikube/pull/7460
it was revealed that after we start mnikube with these CNI/ args
```
--network-plugin=cni 
--extra-config=kubelet.network-plugin=cni
--extra-config=kubeadm.pod-network-cidr=192.168.111.111/16 
```

the coreDNS never comes up becuase it says network is not ready.

https://storage.googleapis.com/minikube-builds/logs/7460/b880469/KVM_Linux.html#fail_TestStartStop%2fgroup%2fnewest-cni

I replicated this on hyperkit:

```

./out minikube start -p newest-cni-20200406T232337.63805791-16483 --memory=2200 --alsologtostderr -v=3 --wait=true --feature-gates ServerSideApply=true --network-plugin=cni --extra-config=kubelet.network-plugin=cni --extra-config=kubeadm.pod-network-cidr=192.168.111.111/16 --driver=hyperkit  --kubernetes-version=v1.18.0

```

the kubectl describe node says: node netwrok is not ready.
```


```

**Comment by tstromberg** [comment] 2020-04-07 17:24
Dupe of #7354

**Closed by tstromberg** 2020-04-07 17:24 UTC
