### ISSUE TITLE
minikube installation problum on ubuntu 20.4

### ISSUE THREAD

**Issue by srehanpk** [kubernetes/minikube#8142] opened 2020-05-13 21:51 UTC
$ minikube start
😄  minikube v1.10.1 on Ubuntu 20.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🔥  Creating docker container (CPUs=2, Memory=2200MB) ...
🐳  Preparing Kubernetes v1.18.2 on Docker 19.03.2 ...
E0514 02:49:02.495954   10122 start.go:95] Unable to get host IP: inspect IP bridge network "c2a3bf2a8820\n13c6d9205f9b\nddec7237ba08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" c2a3bf2a8820
13c6d9205f9b
ddec7237ba08: exit status 1
stdout:

stderr:
Error: No such object: c2a3bf2a8820
13c6d9205f9b
ddec7237ba08

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "c2a3bf2a8820\n13c6d9205f9b\nddec7237ba08".: docker inspect --format "{{(index .IPAM.Config 0).Gateway}}" c2a3bf2a8820
13c6d9205f9b
ddec7237ba08: exit status 1
stdout:

stderr:
Error: No such object: c2a3bf2a8820
13c6d9205f9b
ddec7237ba08

😿  minikube is exiting due to an error. If the above message is not useful, open an issue:
👉  https://github.com/kubernetes/minikube/issues/new/choose

**Comment by srehanpk** [comment] 2020-05-13 21:53
$ docker ps -a | grep minikube
5c6e45aadacd        gcr.io/k8s-minikube/kicbase:v0.0.10   "/usr/local/bin/entr…"   5 minutes ago       Up 4 minutes        127.0.0.1:32779->22/tcp, 127.0.0.1:32778->2376/tcp, 127.0.0.1:32777->5000/tcp, 127.0.0.1:32776->8443/tcp   minikube

**Comment by srehanpk** [comment] 2020-05-13 22:03
$ docker network ls
NETWORK ID          NAME                               DRIVER              SCOPE
c2a3bf2a8820        bridge                             bridge              local
13c6d9205f9b        docker_gwbridge                    bridge              local
ee09a402584e        host                               host                local
kkt9paw3w988        my-attachable-multi-host-network   overlay             swarm
p4gmsc0utlwq        my-attachable-overlay              overlay             swarm
tp5lozv8nmkk        my-ingress                         overlay             swarm
ebf37jp8dbix        my-overlay                         overlay             swarm
ddec7237ba08        mybridge                           bridge              local
7c859310e263        none                               null                loca

**Comment by afbjorklund** [comment] 2020-05-13 23:01
Duplicate of #8131

**Comment by medyagh** [comment] 2020-05-13 23:17
closing this in favor of https://github.com/kubernetes/minikube/issues/8131

**Closed by medyagh** 2020-05-13 23:17 UTC
Labels: triage/duplicate
