### ISSUE TITLE
Windows, error logged from `minikube status`

### ISSUE THREAD

**Issue by gashcrumb** [kubernetes/minikube#600] opened 2016-09-16 14:29 UTC
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Bug Report

**Minikube version** (use `minikube version`): 0.10.0

**Environment**:
- **OS** (e.g. from /etc/os-release): Windows 10 
- **VM Driver** (e.g. `cat ~/.minikube/machines/minikube/config.json | grep DriverName`): hyperv
- **Docker version** (e.g. `docker -v`): 1.9.1
- **Install tools**: 
- **Others**: cygwin

**What happened**: Run `minikube status` and it shows as running but also shows error output:

```
PS C:\Users\gashcrumb> minikube status
E0916 10:21:50.127668   10348 status.go:57] Error getting machine status: Error: Unrecognize output from GetLocalkubeStatus: cat: can't open '/var/run/localkube.pid': No such file or directory
Running
```

**What you expected to happen**: To just see `Running` printed.  This was the case in previous versions.

**How to reproduce it** (as minimally and precisely as possible): Run `minikube status`.  I had just rebooted my desktop, not sure if that's applicable.

**Anything else do we need to know**: It all appears to be running fine, so I suspect this issue is mostly just cosmetic.

**Comment by r2d4** [comment] 2016-09-16 15:07
Yup I think this is just UI.  Looks like we default to that path for writing the PID, which isn't valid on windows :)  Thanks for finding this, we'll get a fix in

**Comment by aaron-prindle** [comment] 2016-09-16 15:47
We recently added localkube status to `minikube status` as well which is why the output is different then it used to be.
This path `/var/run/localkube.pid` is in the VM itself which runs Linux so it should not be an issue with the path.  This file `/var/run/localkube.pid` is created in the VM on `minikube start` and then used during `minikube status`  Can you verify that the file is missing by running:
`minikube ssh cat /var/run/localkube.pid`
I do not know why this file would be missing, the file should be created on `minikube start`, if it is missing then I would recommend restarting the VM using `minikube start` in the hopes that it will create the file and then rerunning the above ssh command.  Please try the above and let me know if the file was-missing/was-created, thanks.

**Comment by gashcrumb** [comment] 2016-09-16 19:09
Have rebooted a couple times today to try and get the issue to reproduce, and of course I can't get it to happen now.  I'm going to leave this overnight and try rebooting tomorrow to see if that makes any difference, as that was the circumstance earlier today where I saw this.

**Comment by gashcrumb** [comment] 2016-09-17 11:45
Still unable to reproduce, not sure of anything else related that could lead up to hitting the problem.

**Comment by r2d4** [comment] 2016-09-17 14:06
Hey @gashcrumb I'm going to close this for now, but feel free to reopen if you're able to reproduce it.  Thanks!

**Closed by r2d4** 2016-09-17 14:06 UTC
Labels: kind/bug, platform/windows

**Comment by gashcrumb** [comment] 2016-09-17 14:13
Sounds good, thanks!
