### ISSUE TITLE
Unable to get host IP: inspect IP bridge network

### ISSUE THREAD

**Issue by RoSk0** [kubernetes/minikube#9153] opened 2020-09-02 05:17 UTC
**Steps to reproduce the issue:** 

1.  $ docker network ls
```
NETWORK ID          NAME                              DRIVER              SCOPE
57d1b92ea7c6        bridge                            bridge              local
8a7df846eb4f        lando_bridge_network              bridge              local
```

2. minikube start

**Full output of failed command:** 

```
$ minikube start
😄  minikube v1.12.3 on Ubuntu 18.04
✨  Automatically selected the docker driver
👍  Starting control plane node minikube in cluster minikube
🚜  Pulling base image ...
💾  Downloading Kubernetes v1.18.3 preload ...
    > preloaded-images-k8s-v5-v1.18.3-docker-overlay2-amd64.tar.lz4: 510.91 MiB
🔥  Creating docker container (CPUs=2, Memory=5900MB) ...
🐳  Preparing Kubernetes v1.18.3 on Docker 19.03.8 ...
E0902 16:57:35.346938   21750 start.go:97] Unable to get host IP: inspect IP bridge network "57d1b92ea7c6\n8a7df846eb4f".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 57d1b92ea7c6
8a7df846eb4f: exit status 1
stdout:


stderr:
Error: No such network: 57d1b92ea7c6
8a7df846eb4f

💣  failed to start node: startup failed: Failed to setup kubeconfig: inspect IP bridge network "57d1b92ea7c6\n8a7df846eb4f".: docker network inspect --format "{{(index .IPAM.Config 0).Gateway}}" 57d1b92ea7c6
8a7df846eb4f: exit status 1
stdout:


stderr:
Error: No such network: 57d1b92ea7c6
8a7df846eb4f

```

It looks like network name match is done in a "contains" way rather then "equals".

**Comment by tstromberg** [comment] 2020-09-02 17:21
This issue appears to be a duplicate of #8131, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-09-02 17:21 UTC
