### ISSUE TITLE
Start with --profile causes crash

### ISSUE THREAD

**Issue by javajon** [kubernetes/minikube#2952] opened 2018-07-01 02:19 UTC
BUG REPORT

Environment:

Minikube version: v0.28.0

OS: Microsoft Windows [Version 10.0.16299.431]
VM Driver: virtualbox
ISO version : "Boot2DockerURL": "file://C:/Users/User/.minikube/cache/iso/minikube-v0.28.0.iso"
Install tools: minikube-windows-amd64.exe renamed to minikube.exe
Others: VirtualBox Version 5.2.12 r122591 (Qt5.6.2)

What happened:

```
$ minikube profile workshop
minikube profile was successfully set to workshop

$ minikube start --profile workshop
Starting local Kubernetes v1.10.0 cluster...
Starting VM...
Downloading Minikube ISO
 153.08 MB / 153.08 MB [============================================] 100.00% 0s
Getting VM IP address...
Moving files into cluster...
Downloading kubelet v1.10.0
Downloading kubeadm v1.10.0
Finished Downloading kubelet v1.10.0
Finished Downloading kubeadm v1.10.0
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
E0630 22:05:40.615900   18976 start.go:294] Error starting cluster:  kubeadm init error sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI  running command: : running command: sudo /usr/bin/kubeadm init --config /var/lib/kubeadm.yaml --ignore-preflight-errors=DirAvailable--etc-kubernetes-manifests --ignore-preflight-errors=DirAvailable--data-minikube --ignore-preflight-errors=Port-10250 --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-scheduler.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-apiserver.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-kube-controller-manager.yaml --ignore-preflight-errors=FileAvailable--etc-kubernetes-manifests-etcd.yaml --ignore-preflight-errors=Swap --ignore-preflight-errors=CRI
.: Process exited with status 1
================================================================================
An error has occurred. Would you like to opt in to sending anonymized crash
information to minikube to help prevent future errors?
To opt out of these messages, run the command:
        minikube config set WantReportErrorPrompt false
================================================================================
Please enter your response [Y/n]:
Y
```

**What you expected to happen**:
Start normally, no errors

**How to reproduce it** (as minimally and precisely as possible):

delete ~/.kube
delete ~/.minikube
install minikube.exe
minikube profile workshop
minikube start --profile workshop

Error is consistently repeatable.

**Output of `minikube logs` (if applicable)**:

`F0630 22:15:29.886153     816 logs.go:50] Error getting cluster bootstrapper: getting kubeadm bootstrapper: getting api client: Error loading host from store: Docker machine "minikube" does not exist. Use "docker-machine ls" to list machines. Use "docker-machine create" to add a new one.`

**Anything else do we need to know**:

Workaround is to use deprecated boostrapper called localkube

`minikube start --bootstrapper localkube --profile workshop`

This bug report is hopefully cleaner than #2818 and supports #2717

**Comment by Marlinc** [comment] 2018-07-10 07:07
I have the same issue on Ubuntu 16.04 with VirtualBox

**Comment by tstromberg** [comment] 2018-09-19 03:38
Dupe of #2574

**Closed by tstromberg** 2018-09-19 03:38 UTC
