### ISSUE TITLE
Failed to enable unit: Unit file cri-docker.socket does not exist.

### ISSUE THREAD

**Issue by pratiiik** [kubernetes/minikube#14601] opened 2022-07-16 07:55 UTC
### What Happened?

Trying to start minikube using --vm-driver=None.

logs are below:

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:29 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:35 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:47 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/07/16 07:47:59
Running on machine: ip-172-31-31-224
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0716 07:47:59.959304    1906 out.go:296] Setting OutFile to fd 1 ...
I0716 07:47:59.959431    1906 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0716 07:47:59.959437    1906 out.go:309] Setting ErrFile to fd 2...
I0716 07:47:59.959443    1906 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0716 07:47:59.961579    1906 root.go:329] Updating PATH: /root/.minikube/bin
W0716 07:47:59.962156    1906 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0716 07:47:59.963228    1906 out.go:303] Setting JSON to false
I0716 07:47:59.963995    1906 start.go:115] hostinfo: {"hostname":"ip-172-31-31-224","uptime":365,"bootTime":1657957315,"procs":111,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec205303-e588-91fa-210f-dccc3a64fdab"}
I0716 07:47:59.964057    1906 start.go:125] virtualization: xen guest
I0716 07:47:59.967144    1906 out.go:177] * minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
I0716 07:47:59.970506    1906 notify.go:193] Checking for updates...
I0716 07:47:59.974918    1906 driver.go:360] Setting default libvirt URI to qemu:///system
I0716 07:47:59.977196    1906 out.go:177] * Using the none driver based on user configuration
W0716 07:47:59.975959    1906 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0716 07:47:59.979463    1906 start.go:284] selected driver: none
I0716 07:47:59.979475    1906 start.go:805] validating driver "none" against <nil>
I0716 07:47:59.979488    1906 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0716 07:47:59.979512    1906 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0716 07:47:59.980308    1906 start_flags.go:296] no existing cluster config was found, will generate one from the flags
I0716 07:47:59.980561    1906 start_flags.go:377] Using suggested 2200MB memory alloc based on sys=3929MB, container=0MB
I0716 07:47:59.980677    1906 start_flags.go:835] Wait components to verify : map[apiserver:true system_pods:true]
I0716 07:47:59.980697    1906 cni.go:95] Creating CNI manager for ""
I0716 07:47:59.980703    1906 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0716 07:47:59.980712    1906 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0716 07:47:59.983313    1906 out.go:177] * Starting control plane node minikube in cluster minikube
I0716 07:47:59.985631    1906 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0716 07:47:59.985660    1906 lock.go:35] WriteFile acquiring /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0716 07:47:59.986915    1906 cache.go:208] Successfully downloaded all kic artifacts
I0716 07:47:59.986943    1906 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0716 07:47:59.987038    1906 start.go:356] acquired machines lock for "minikube" in 67.461µs
I0716 07:47:59.987727    1906 start.go:91] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:} &{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}
I0716 07:47:59.987794    1906 start.go:131] createHost starting for "m01" (driver="none")
I0716 07:47:59.990553    1906 out.go:177] * Running on localhost (CPUs=2, Memory=3929MB, Disk=9749MB) ...
I0716 07:47:59.992612    1906 exec_runner.go:51] Run: systemctl --version
I0716 07:47:59.995548    1906 start.go:165] libmachine.API.Create for "minikube" (driver="none")
I0716 07:47:59.995599    1906 client.go:168] LocalClient.Create starting
I0716 07:47:59.996357    1906 main.go:134] libmachine: Creating CA: /root/.minikube/certs/ca.pem
I0716 07:48:00.293910    1906 main.go:134] libmachine: Creating client certificate: /root/.minikube/certs/cert.pem
I0716 07:48:00.456141    1906 client.go:171] LocalClient.Create took 460.528584ms
I0716 07:48:00.456184    1906 start.go:173] duration metric: libmachine.API.Create for "minikube" took 460.631523ms
I0716 07:48:00.456193    1906 start.go:306] post-start starting for "minikube" (driver="none")
I0716 07:48:00.456199    1906 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0716 07:48:00.456240    1906 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0716 07:48:00.501896    1906 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0716 07:48:00.501917    1906 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0716 07:48:00.501929    1906 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0716 07:48:00.505267    1906 out.go:177] * OS release is Ubuntu 18.04.6 LTS
I0716 07:48:00.507272    1906 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0716 07:48:00.507835    1906 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0716 07:48:00.508396    1906 start.go:309] post-start completed in 52.190632ms
I0716 07:48:00.509111    1906 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0716 07:48:00.509256    1906 start.go:134] duration metric: createHost completed in 521.453226ms
I0716 07:48:00.509267    1906 start.go:81] releasing machines lock for "minikube", held for 522.219145ms
I0716 07:48:00.509612    1906 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0716 07:48:00.510645    1906 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0716 07:48:00.524764    1906 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0716 07:48:00.671205    1906 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0716 07:48:00.816378    1906 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0716 07:48:00.966033    1906 exec_runner.go:51] Run: sudo systemctl restart docker
I0716 07:48:01.220810    1906 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0716 07:48:01.234000    1906 out.go:177]
W0716 07:48:01.236257    1906 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0716 07:48:01.236285    1906 out.go:239] *
W0716 07:48:01.237280    1906 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0716 07:48:01.239210    1906 out.go:177]

*
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

### Attach the log file

*
* ==> Audit <==
* |---------|------------------|----------|------|---------|---------------------|----------|
| Command |       Args       | Profile  | User | Version |     Start Time      | End Time |
|---------|------------------|----------|------|---------|---------------------|----------|
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:29 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:35 UTC |          |
| start   | --vm-driver=none | minikube | root | v1.26.0 | 16 Jul 22 07:47 UTC |          |
|---------|------------------|----------|------|---------|---------------------|----------|

*
* ==> Last Start <==
* Log file created at: 2022/07/16 07:47:59
Running on machine: ip-172-31-31-224
Binary: Built with gc go1.18.3 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
I0716 07:47:59.959304    1906 out.go:296] Setting OutFile to fd 1 ...
I0716 07:47:59.959431    1906 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0716 07:47:59.959437    1906 out.go:309] Setting ErrFile to fd 2...
I0716 07:47:59.959443    1906 out.go:343] TERM=xterm,COLORTERM=, which probably does not support color
I0716 07:47:59.961579    1906 root.go:329] Updating PATH: /root/.minikube/bin
W0716 07:47:59.962156    1906 root.go:307] Error reading config file at /root/.minikube/config/config.json: open /root/.minikube/config/config.json: no such file or directory
I0716 07:47:59.963228    1906 out.go:303] Setting JSON to false
I0716 07:47:59.963995    1906 start.go:115] hostinfo: {"hostname":"ip-172-31-31-224","uptime":365,"bootTime":1657957315,"procs":111,"os":"linux","platform":"ubuntu","platformFamily":"debian","platformVersion":"18.04","kernelVersion":"5.4.0-1078-aws","kernelArch":"x86_64","virtualizationSystem":"xen","virtualizationRole":"guest","hostId":"ec205303-e588-91fa-210f-dccc3a64fdab"}
I0716 07:47:59.964057    1906 start.go:125] virtualization: xen guest
I0716 07:47:59.967144    1906 out.go:177] * minikube v1.26.0 on Ubuntu 18.04 (xen/amd64)
I0716 07:47:59.970506    1906 notify.go:193] Checking for updates...
I0716 07:47:59.974918    1906 driver.go:360] Setting default libvirt URI to qemu:///system
I0716 07:47:59.977196    1906 out.go:177] * Using the none driver based on user configuration
W0716 07:47:59.975959    1906 preload.go:295] Failed to list preload files: open /root/.minikube/cache/preloaded-tarball: no such file or directory
I0716 07:47:59.979463    1906 start.go:284] selected driver: none
I0716 07:47:59.979475    1906 start.go:805] validating driver "none" against <nil>
I0716 07:47:59.979488    1906 start.go:816] status for none: {Installed:true Healthy:true Running:false NeedsImprovement:false Error:<nil> Reason: Fix: Doc: Version:}
I0716 07:47:59.979512    1906 start.go:1541] auto setting extra-config to "kubelet.resolv-conf=/run/systemd/resolve/resolv.conf".
I0716 07:47:59.980308    1906 start_flags.go:296] no existing cluster config was found, will generate one from the flags
I0716 07:47:59.980561    1906 start_flags.go:377] Using suggested 2200MB memory alloc based on sys=3929MB, container=0MB
I0716 07:47:59.980677    1906 start_flags.go:835] Wait components to verify : map[apiserver:true system_pods:true]
I0716 07:47:59.980697    1906 cni.go:95] Creating CNI manager for ""
I0716 07:47:59.980703    1906 cni.go:149] Driver none used, CNI unnecessary in this configuration, recommending no CNI
I0716 07:47:59.980712    1906 start_flags.go:310] config:
{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:}
I0716 07:47:59.983313    1906 out.go:177] * Starting control plane node minikube in cluster minikube
I0716 07:47:59.985631    1906 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0716 07:47:59.985660    1906 lock.go:35] WriteFile acquiring /root/.minikube/profiles/minikube/config.json: {Name:mk270d1b5db5965f2dc9e9e25770a63417031943 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0716 07:47:59.986915    1906 cache.go:208] Successfully downloaded all kic artifacts
I0716 07:47:59.986943    1906 start.go:352] acquiring machines lock for minikube: {Name:mkc8ab01ad3ea83211c505c81a7ee49a8e3ecb89 Clock:{} Delay:500ms Timeout:13m0s Cancel:<nil>}
I0716 07:47:59.987038    1906 start.go:356] acquired machines lock for "minikube" in 67.461µs
I0716 07:47:59.987727    1906 start.go:91] Provisioning new machine with config: &{Name:minikube KeepContext:false EmbedCerts:false MinikubeISO: KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.32@sha256:9190bd2393eae887316c97a74370b7d5dad8f0b2ef91ac2662bc36f7ef8e0b95 Memory:2200 CPUs:2 DiskSize:20000 VMDriver: Driver:none HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] ContainerVolumeMounts:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.59.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false KVMNUMACount:1 APIServerPort:0 DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio SSHIPAddress: SSHUser:root SSHKey: SSHPort:22 KubernetesConfig:{KubernetesVersion:v1.24.1 ClusterName:minikube Namespace:default APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: CustomIngressCert: RegistryAliases: ExtraOptions:[{Component:kubelet Key:resolv-conf Value:/run/systemd/resolve/resolv.conf}] ShouldLoadCachedImages:false EnableDefaultCNI:false CNI: NodeIP: NodePort:8443 NodeName:} Nodes:[{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}] Addons:map[] CustomAddonImages:map[] CustomAddonRegistries:map[] VerifyComponents:map[apiserver:true system_pods:true] StartHostTimeout:6m0s ScheduledStop:<nil> ExposedPorts:[] ListenAddress: Network: Subnet: MultiNodeRequested:false ExtraDisks:0 CertExpiration:26280h0m0s Mount:false MountString:/root:/minikube-host Mount9PVersion:9p2000.L MountGID:docker MountIP: MountMSize:262144 MountOptions:[] MountPort:0 MountType:9p MountUID:docker BinaryMirror: DisableOptimizations:false DisableMetrics:false CustomQemuFirmwarePath:} &{Name:m01 IP: Port:8443 KubernetesVersion:v1.24.1 ContainerRuntime:docker ControlPlane:true Worker:true}
I0716 07:47:59.987794    1906 start.go:131] createHost starting for "m01" (driver="none")
I0716 07:47:59.990553    1906 out.go:177] * Running on localhost (CPUs=2, Memory=3929MB, Disk=9749MB) ...
I0716 07:47:59.992612    1906 exec_runner.go:51] Run: systemctl --version
I0716 07:47:59.995548    1906 start.go:165] libmachine.API.Create for "minikube" (driver="none")
I0716 07:47:59.995599    1906 client.go:168] LocalClient.Create starting
I0716 07:47:59.996357    1906 main.go:134] libmachine: Creating CA: /root/.minikube/certs/ca.pem
I0716 07:48:00.293910    1906 main.go:134] libmachine: Creating client certificate: /root/.minikube/certs/cert.pem
I0716 07:48:00.456141    1906 client.go:171] LocalClient.Create took 460.528584ms
I0716 07:48:00.456184    1906 start.go:173] duration metric: libmachine.API.Create for "minikube" took 460.631523ms
I0716 07:48:00.456193    1906 start.go:306] post-start starting for "minikube" (driver="none")
I0716 07:48:00.456199    1906 start.go:316] creating required directories: [/etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs]
I0716 07:48:00.456240    1906 exec_runner.go:51] Run: sudo mkdir -p /etc/kubernetes/addons /etc/kubernetes/manifests /var/tmp/minikube /var/lib/minikube /var/lib/minikube/certs /var/lib/minikube/images /var/lib/minikube/binaries /tmp/gvisor /usr/share/ca-certificates /etc/ssl/certs
I0716 07:48:00.501896    1906 main.go:134] libmachine: Couldn't set key PRIVACY_POLICY_URL, no corresponding struct field found
I0716 07:48:00.501917    1906 main.go:134] libmachine: Couldn't set key VERSION_CODENAME, no corresponding struct field found
I0716 07:48:00.501929    1906 main.go:134] libmachine: Couldn't set key UBUNTU_CODENAME, no corresponding struct field found
I0716 07:48:00.505267    1906 out.go:177] * OS release is Ubuntu 18.04.6 LTS
I0716 07:48:00.507272    1906 filesync.go:126] Scanning /root/.minikube/addons for local assets ...
I0716 07:48:00.507835    1906 filesync.go:126] Scanning /root/.minikube/files for local assets ...
I0716 07:48:00.508396    1906 start.go:309] post-start completed in 52.190632ms
I0716 07:48:00.509111    1906 profile.go:148] Saving config to /root/.minikube/profiles/minikube/config.json ...
I0716 07:48:00.509256    1906 start.go:134] duration metric: createHost completed in 521.453226ms
I0716 07:48:00.509267    1906 start.go:81] releasing machines lock for "minikube", held for 522.219145ms
I0716 07:48:00.509612    1906 exec_runner.go:51] Run: /bin/bash -c "sudo mkdir -p /etc && printf %!s(MISSING) "runtime-endpoint: unix:///var/run/cri-dockerd.sock
image-endpoint: unix:///var/run/cri-dockerd.sock
" | sudo tee /etc/crictl.yaml"
I0716 07:48:00.510645    1906 exec_runner.go:51] Run: curl -sS -m 2 https://k8s.gcr.io/
I0716 07:48:00.524764    1906 exec_runner.go:51] Run: sudo systemctl unmask docker.service
I0716 07:48:00.671205    1906 exec_runner.go:51] Run: sudo systemctl enable docker.socket
I0716 07:48:00.816378    1906 exec_runner.go:51] Run: sudo systemctl daemon-reload
I0716 07:48:00.966033    1906 exec_runner.go:51] Run: sudo systemctl restart docker
I0716 07:48:01.220810    1906 exec_runner.go:51] Run: sudo systemctl enable cri-docker.socket
I0716 07:48:01.234000    1906 out.go:177]
W0716 07:48:01.236257    1906 out.go:239] X Exiting due to RUNTIME_ENABLE: sudo systemctl enable cri-docker.socket: exit status 1
stdout:

stderr:
Failed to enable unit: Unit file cri-docker.socket does not exist.

W0716 07:48:01.236285    1906 out.go:239] *
W0716 07:48:01.237280    1906 out.go:239] ╭─────────────────────────────────────────────────────────────────────────────────────────────╮
│                                                                                             │
│    * If the above advice does not help, please let us know:                                 │
│      https://github.com/kubernetes/minikube/issues/new/choose                               │
│                                                                                             │
│    * Please run `minikube logs --file=logs.txt` and attach logs.txt to the GitHub issue.    │
│                                                                                             │
╰─────────────────────────────────────────────────────────────────────────────────────────────╯
I0716 07:48:01.239210    1906 out.go:177]

*
* The control plane node must be running for this command
  To start a cluster, run: "minikube start"

### Operating System

Ubuntu

**Comment by afbjorklund** [comment] 2022-07-16 08:01
Same as:
* https://github.com/kubernetes/minikube/issues/14410

**Comment by spowelljr** [comment] 2022-07-25 17:28
Hi @pratiiik, as @afbjorklund pointed out, this is a duplicate of https://github.com/kubernetes/minikube/issues/14410, to see how to resolve this issue please see https://github.com/kubernetes/minikube/issues/14410#issuecomment-1171741503. I'm going to close this issue.

**Closed by spowelljr** 2022-07-25 17:28 UTC
Labels: co/runtime/docker, co/none-driver, triage/duplicate
