### ISSUE TITLE
Values of the option --v

### ISSUE THREAD

**Issue by cmoulliard** [kubernetes/minikube#346] opened 2016-07-15 07:28 UTC
Hi,

- What are the values possible to configure the logging level ?
- Do they correspond (= value) to log INFO, DEBUG, WARN, FATAL, ... ?

**Comment by luxas** [comment] 2016-07-17 11:18
Values are numeric (1=little, 9=much logging), but I don't think much code is really utilizing it (there isn't so much code in localkube).
All log entries start with a character: I for info, W for warning and F for fatal.

**Comment by aaron-prindle** [comment] 2016-09-08 21:53
Closed as dupe of #399.  We will add more info about v level in the troubleshooting guide.

**Closed** 2016-09-08 21:53 UTC
Labels: kind/documentation
