### ISSUE TITLE
hyperv: The memory value assigned ('4019' MB) is not properly aligned

### ISSUE THREAD

**Issue by henryodinaka** [kubernetes/minikube#6973] opened 2020-03-10 09:22 UTC
I am new to k8s and trying to start minikube but kept seeing the error below.

**The exact command to reproduce the issue**:   minikube start --driver=hyperv

**The full output of the command that failed**:<details>

 Hyper-V\New-VM : Failed to modify device 'Memory'.
Invalid memory value assigned for 'minikube'. Memory values must be properly aligned.
'minikube' failed to modify device 'Memory'. (Virtual machine ID 2BFC2B6D-BB10-4492-9C37-E36F134A22F6)
Invalid memory value assigned for 'minikube'. The memory value assigned ('4019' MB) is not properly aligned. Try again with a memory value that is properly aligned. (Virtual machine ID 2BFC2B6D-BB10-4492-9C37-E36F134A22F6)
At line:1 char:1

</details>

**The output of the `minikube logs` command**:<details>

E0310 10:20:15.208507    6448 main.go:106] libmachine: [stderr =====>] : Hyper-V\Get-VM : Hyper-V was unable to find a virtual machine with name "minikube".
At line:1 char:3
+ ( Hyper-V\Get-VM minikube ).state
+   ~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (minikube:String) [Get-VM], VirtualizationException
    + FullyQualifiedErrorId : InvalidParameter,Microsoft.HyperV.PowerShell.Commands.GetVM

*
X command runner: getting ssh client for bootstrapper: Error creating new ssh host from driver: Error getting ssh host name for driver: Host is not running
*

</details>

**The operating system version**:  Windows 10 pro

**Comment by tstromberg** [comment] 2020-03-10 16:55
I strongly suspect this has to do with v1.8's new automatic memory size selection.

Can you confirm if running `minikube delete` and then adding `--memory=4000` to your minikube start flag fixes the issue?

I'm really curious what the rules for hyperv memory alignment are.

**Comment by afbjorklund** [comment] 2020-03-10 20:36
Similar to #6964, apparently it only supports even numbers - not odd ones like 4019

**Comment by tstromberg** [comment] 2020-03-10 21:58
This issue appears to be a duplicate of #6964, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-03-10 21:58 UTC
Labels: co/hyperv, kind/bug, priority/important-soon

**Comment by henryodinaka** [comment] 2020-03-11 13:14
> I strongly suspect this has to do with v1.8's new automatic memory size selection.
> 
> Can you confirm if running `minikube delete` and then adding `--memory=4000` to your minikube start flag fixes the issue?
> 
> I'm really curious what the rules for hyperv memory alignment are.

Thank you. @tstromberg 
adding `--memory=4000`  solved the issue.
I ran the command below and everything went fine.
 'minikube start --vm-driver=hyperv --memory=4000'
