### ISSUE TITLE
The Minikube's README on the quickstart section seems to be outdated

### ISSUE THREAD

**Issue by yamishi13** [kubernetes/minikube#1553] opened 2017-06-04 06:39 UTC
**this a BUG REPORT** :

The Minikube's README on the quickstart section seems to be outdated (or incorrect) since it is asking you to input commands that kubectl marks as incorrect:

"kubectl expose deployment hello-minikube --type=NodePort"

Also the output of the commands seems to be either outdated or just not very descriptive.

Please check the changes I made on PR #1552 

**Minikube version** : v0.19.1

**Environment**:
- **OS** : MacOS 10.12.5
- **VM Driver** : xhyve
- **ISO version** :v0.18.0
- **Install tools**: brew

**Comment by aaron-prindle** [comment] 2017-06-05 16:19
I ran the quickstart with kubectl v1.6.4 and everything seems to work properly with the following output:

```
$ kubectl run hello-minikube --image=gcr.io/
google_containers/echoserver:1.4 --port=8080
deployment "hello-minikube" created
$ kubectl expose deployment hello-minikube --type=NodePort
service "hello-minikube" exposed
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538
d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-05-19T18:44:27Z", GoVersio
n:"go1.7.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538
d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean", BuildDate:"2017-06-05T09:06:30Z", GoVersio
n:"go1.7.3", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by yamishi13** [comment] 2017-06-05 16:43
Ok so the version of kubectl I'm running is old 
`$ kubectl version
Client Version: version.Info{Major:"1", Minor:"0", GitVersion:"v1.0.1", GitCommit:"6a5c06e3d1eb27a6310a09270e4a5fb1afa93e74", GitTreeState:"clean"}
Server Version: version.Info{Major:"1", Minor:"6", GitVersion:"v1.6.4", GitCommit:"d6f433224538d4f9ca2f7ae19b252e6fcb66a3ae", GitTreeState:"clean"}`

And the reason for this is that for any reason homebrew is failing to update my kubectl client version. I'll take a look at that instead. For now I just tried in a linux machine with kubectl 1.6.4 and it works with the documentation commands so I guess its safe to say that both this issue and the PR can be closed. Sorry for the time lost.

**Comment by aaron-prindle** [comment] 2017-06-05 16:51
No problem, glad the issue is resolved.  Closing.

**Closed by aaron-prindle** 2017-06-05 16:51 UTC
