### ISSUE TITLE
Windows Installer does not add to PATH on Windows 10

### ISSUE THREAD

**Issue by blueelvis** [kubernetes/minikube#4275] opened 2019-05-16 20:08 UTC
**The operating system version**:
Windows 10 v1809

I just downloaded the installer for Minikube from this page and after executing and installing, I closed the PowerShell process window and opened again but I was not able to interact with `minikube` cli. Also, I checked both the System and User environment's `PATH` variables and the path of installation (C:\Program Files\Kubernetes\Minikube) is not there.

Additional questions --
1. Why do I get "Unknown Publisher" and a warning from "Windows Smartscreen" that the installer is not trusted?
2. Is there any process on how these installers are generated?

Thanks,
Pranav

**Comment by cbuchacher** [comment] 2019-05-17 06:30
Furthermore, after running the installer, AWS CLI is _removed_ from the PATH.

**Comment by tstromberg** [comment] 2019-05-22 03:39
Thank you for sharing your experience!

This issue appears to be a duplicate of #2587, so I will close this in preference to that issue so that we may centralize the information around it. If you feel that this is not in fact a duplicate, please feel free to re-open this issue.

**Closed by tstromberg** 2019-05-22 03:39 UTC
