### ISSUE TITLE
Can't change ServiceClusterIPRange

### ISSUE THREAD

**Issue by felipejfc** [kubernetes/minikube#1323] opened 2017-04-03 19:12 UTC
Hi, I'm trying to change ServiceClusterIPRange with the "--extra-config" flag without success, this is my start line:
```
minikube start --extra-config=apiserver.GenericServerRunOptions.ServiceClusterIPRange=10.1.0.1/16 --vm-driver=xhyve
```

when I get services:
```
➜  manifests git:(master) ✗ kubectl get svc
NAME         CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   10.0.0.1     <none>        443/TCP   9m
```

am I doing anything wrong?

@dlorenc @r2d4 

Additional Info: I'm running on a mac

**Comment by r2d4** [comment] 2017-04-06 17:58
Can you output `minikube logs | grep feature`?  Which version of kubernetes are you running?

**Comment by r2d4** [comment] 2017-04-10 22:48
dupe of https://github.com/kubernetes/minikube/issues/1006#issuecomment-274176335 https://github.com/kubernetes/minikube/issues/1359

**Closed by r2d4** 2017-04-10 22:48 UTC
Labels: kind/bug

**Comment by felipejfc** [comment] 2017-04-12 15:03
Just to leave as reference, the corrent is:

```
minikube start --extra-config=apiserver.ServiceClusterIPRange=10.1.0.1/16 --vm-driver=xhyve
```
