### ISSUE TITLE
Ingress addon problem again

### ISSUE THREAD

**Issue by AndreyIvshin** [kubernetes/minikube#10153] opened 2021-01-15 16:55 UTC
After Docker driver minikube cannot be created after enabling ingress addon #10151 https://github.com/kubernetes/minikube/issues/10151 and Ingress addon problem #10152 https://github.com/kubernetes/minikube/issues/10152

<><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><>
1. Deleted .minikube and .kube and start minikube
<><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><>

$ minikube start
* minikube v1.16.0 on Microsoft Windows 10 Home Single Language 10.0.19041 Build 19041
* Automatically selected the virtualbox driver
* Downloading VM boot image ...
    > minikube-v1.16.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.16.0.iso: 212.62 MiB / 212.62 MiB  100.00% 684.80 KiB p/s 5m1
* Starting control plane node minikube in cluster minikube
* Downloading Kubernetes v1.20.0 preload ...
    > preloaded-images-k8s-v8-v1....: 491.00 MiB / 491.00 MiB  100.00% 431.76 K
* Creating virtualbox VM (CPUs=2, Memory=2200MB, Disk=20000MB) ...
* Found network options:
  - NO_PROXY=192.168.99.100
  - no_proxy=192.168.99.100
* Preparing Kubernetes v1.20.0 on Docker 20.10.0 ...
  - env NO_PROXY=192.168.99.100
  - Generating certificates and keys ...
  - Booting up control plane ...
  - Configuring RBAC rules ...
* Verifying Kubernetes components...
* Enabled addons: storage-provisioner, default-storageclass
* Done! kubectl is now configured to use "minikube" cluster and "default" namespace by default

<><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><>
2. Trying to enable ingress addon
<><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><><><><>><><>

$ minikube addons enable ingress
* Verifying ingress addon...

X Exiting due to MK_ENABLE: run callbacks: running callbacks: [waiting for app.kubernetes.io/name=ingress-nginx pods: timed out waiting for the condition]
*
* If the above advice does not help, please let us know:
  - https://github.com/kubernetes/minikube/issues/new/choose

**Comment by priyawadhwa** [comment] 2021-02-03 19:14
Hey @AndreyIvshin thank you for opening this issue, I'm going to close it as a dupe of https://github.com/kubernetes/minikube/issues/10152 so that we can centralize the conversation there.

**Closed by priyawadhwa** 2021-02-03 19:14 UTC
Labels: kind/support, triage/duplicate
