### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by marcusm** [kubernetes/minikube#8248] opened 2020-05-22 03:27 UTC
**Steps to reproduce the issue:** 

1. Start on a clean windows 10 machine with HyperV setup
2.  Attempt to start minikube using the command below

**Full output of failed command:** 

**Full output of `minikube start` command used, if not already included:**
▶ minikube start --driver=hyperv --cpus=4 --memory=4096 --kubernetes-version=1.16.5 --alsologtostderr -v=8
W0521 20:18:10.115442   10228 root.go:252] Error reading config file at C:\Users\marcmar\.minikube\config\config.json: open C:\Users\marcmar\.minikube\config\config.json: The system cannot find the path specified.
I0521 20:18:10.141182   10228 start.go:99] hostinfo: {"hostname":"REDROCKWILLOW","uptime":5192,"bootTime":1590112298,"procs":289,"os":"windows","platform":"Microsoft Windows 10 Enterprise","platformFamily":"Standalone Workstation","platformVersion":"10.0.19041 Build 19041","kernelVersion":"","virtualizationSystem":"","virtualizationRole":"","hostid":"d91e6027-4619-408c-8a6f-60613859f716"}
W0521 20:18:10.147984   10228 start.go:107] gopshost.Virtualization returned error: not implemented yet
* minikube v1.10.1 on Microsoft Windows 10 Enterprise 10.0.19041 Build 19041
I0521 20:18:10.153994   10228 notify.go:125] Checking for updates...
I0521 20:18:10.153994   10228 driver.go:253] Setting default libvirt URI to qemu:///system
* Using the hyperv driver based on user configuration
I0521 20:18:11.324858   10228 start.go:215] selected driver: hyperv
I0521 20:18:11.325859   10228 start.go:594] validating driver "hyperv" against <nil>
I0521 20:18:11.325859   10228 start.go:600] status for hyperv: {Installed:true Healthy:true Error:<nil> Fix: Doc:}
I0521 20:18:11.325859   10228 start_flags.go:217] no existing cluster config was found, will generate one from the flags

I0521 20:18:11.325859   10228 start_flags.go:558] Wait components to verify : map[apiserver:true system_pods:true]
* Kubernetes 1.18.2 is now available. If you would like to upgrade, specify: --kubernetes-version=1.18.2
I0521 20:18:11.327860   10228 iso.go:118] acquiring lock: {Name:mkaad513ba51b5d32f06e77eef046d69a849efbc Clock:{} Delay:500ms Timeout:10m0s Cancel:<nil>}
* Downloading VM boot image ...
I0521 20:18:11.329858   10228 download.go:73] Downloading: https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso?checksum=file:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso.sha256 -> C:\Users\marcmar\.minikube\cache\iso\minikube-v1.10.0.iso
    > minikube-v1.10.0.iso.sha256: 65 B / 65 B [-------------] 100.00% ? p/s 0s
    > minikube-v1.10.0.iso: 174.99 MiB / 174.99 MiB [] 100.00% 44.25 MiB p/s 4s
* Starting control plane node minikube in cluster minikube
I0521 20:18:16.929411   10228 preload.go:81] Checking if preload exists for k8s version v1.16.5 and runtime docker
I0521 20:18:17.069897   10228 preload.go:113] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4
I0521 20:18:17.070342   10228 cache.go:48] Caching tarball of preloaded images
I0521 20:18:17.071341   10228 preload.go:81] Checking if preload exists for k8s version v1.16.5 and runtime docker
I0521 20:18:17.255212   10228 preload.go:113] Found remote preload: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4
* Downloading Kubernetes v1.16.5 preload ...
I0521 20:18:17.267083   10228 download.go:73] Downloading: https://storage.googleapis.com/minikube-preloaded-volume-tarballs/preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4 -> C:\Users\marcmar\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4
    > preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4: 455.03 MiB
I0521 20:18:27.613502   10228 preload.go:151] saving checksum for preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4 ...
I0521 20:18:27.838652   10228 preload.go:168] verifying checksumm of C:\Users\marcmar\.minikube\cache\preloaded-tarball\preloaded-images-k8s-v3-v1.16.5-docker-overlay2-amd64.tar.lz4 ...
I0521 20:18:28.713780   10228 cache.go:51] Finished verifying existence of preloaded tar for  v1.16.5 on docker
I0521 20:18:28.714781   10228 profile.go:156] Saving config to C:\Users\marcmar\.minikube\profiles\minikube\config.json ...
I0521 20:18:28.715784   10228 lock.go:35] WriteFile acquiring C:\Users\marcmar\.minikube\profiles\minikube\config.json: {Name:mk2eedacdd451e047ab9ddcf1932d803cd069488 Clock:{} Delay:500ms Timeout:1m0s Cancel:<nil>}
I0521 20:18:28.719781   10228 cache.go:132] Successfully downloaded all kic artifacts
I0521 20:18:28.719781   10228 start.go:223] acquiring machines lock for minikube: {Name:mkdc88dd536260eb226974ab0baa47eac34eeee7 Clock:{} Delay:500ms Timeout:15m0s Cancel:<nil>}
I0521 20:18:28.720783   10228 start.go:227] acquired machines lock for "minikube" in 0s
I0521 20:18:28.720783   10228 start.go:83] Provisioning new machine with config: {Name:minikube KeepContext:false EmbedCerts:false MinikubeISO:https://storage.googleapis.com/minikube/iso/minikube-v1.10.0.iso KicBaseImage:gcr.io/k8s-minikube/kicbase:v0.0.10@sha256:f58e0c4662bac8a9b5dda7984b185bad8502ade5d9fa364bf2755d636ab51438 Memory:4096 CPUs:4 DiskSize:20000 Driver:hyperv HyperkitVpnKitSock: HyperkitVSockPorts:[] DockerEnv:[] InsecureRegistry:[] RegistryMirror:[] HostOnlyCIDR:192.168.99.1/24 HypervVirtualSwitch: HypervUseExternalSwitch:false HypervExternalAdapter: KVMNetwork:default KVMQemuURI:qemu:///system KVMGPU:false KVMHidden:false DockerOpt:[] DisableDriverMounts:false NFSShare:[] NFSSharesRoot:/nfsshares UUID: NoVTXCheck:false DNSProxy:false HostDNSResolver:true HostOnlyNicType:virtio NatNicType:virtio KubernetesConfig:{KubernetesVersion:v1.16.5 ClusterName:minikube APIServerName:minikubeCA APIServerNames:[] APIServerIPs:[] DNSDomain:cluster.local ContainerRuntime:docker CRISocket: NetworkPlugin: FeatureGates: ServiceCIDR:10.96.0.0/12 ImageRepository: LoadBalancerStartIP: LoadBalancerEndIP: ExtraOptions:[] ShouldLoadCachedImages:true EnableDefaultCNI:false NodeIP: NodePort:8443 NodeName:} Nodes:[{Name: IP: Port:8443 KubernetesVersion:v1.16.5 ControlPlane:true Worker:true}] Addons:map[] VerifyComponents:map[apiserver:true system_pods:true]} {Name: IP: Port:8443 KubernetesVersion:v1.16.5 ControlPlane:true Worker:true}
I0521 20:18:28.721784   10228 start.go:104] createHost starting for "" (driver="hyperv")
* Creating hyperv VM (CPUs=4, Memory=4096MB, Disk=20000MB) ...
I0521 20:18:28.734909   10228 start.go:140] libmachine.API.Create for "minikube" (driver="hyperv")
I0521 20:18:28.734909   10228 client.go:161] LocalClient.Create starting
I0521 20:18:28.734909   10228 main.go:110] libmachine: Creating CA: C:\Users\marcmar\.minikube\certs\ca.pem
I0521 20:18:28.865903   10228 main.go:110] libmachine: Creating client certificate: C:\Users\marcmar\.minikube\certs\cert.pem
I0521 20:18:29.039901   10228 main.go:110] libmachine: [executing ==>] : C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
I0521 20:18:29.367715   10228 main.go:110] libmachine: [stdout =====>] :
I0521 20:18:29.367715   10228 main.go:110] libmachine: [stderr =====>] :
I0521 20:18:29.368538   10228 client.go:164] LocalClient.Create took 633.6379ms
panic: runtime error: index out of range [0] with length 0

goroutine 196 [running]:
github.com/docker/machine/drivers/hyperv.hypervAvailable(0xc000124c90, 0xc0002ba980)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/powershell.go:64 +0x105
github.com/docker/machine/drivers/hyperv.(*Driver).PreCreateCheck(0xc000106b40, 0x0, 0x0)
        /go/pkg/mod/github.com/machine-drivers/machine@v0.7.1-0.20200323212942-41eb826190d8/drivers/hyperv/hyperv.go:171 +0x3b
k8s.io/minikube/pkg/minikube/machine.(*LocalClient).Create(0xc000540040, 0xc000106c60, 0x0, 0x0)
        /app/pkg/minikube/machine/client.go:221 +0x3f5
k8s.io/minikube/pkg/minikube/machine.timedCreateHost.func2(0x1e65f40, 0xc000540040, 0xc000106c60, 0xc000526250, 0xc000424070)
        /app/pkg/minikube/machine/start.go:167 +0x42
created by k8s.io/minikube/pkg/minikube/machine.timedCreateHost
        /app/pkg/minikube/machine/start.go:166 +0x10e

<details>
OS Name	Microsoft Windows 10 Enterprise
Version	10.0.19041 Build 19041

The Get-Module command does not appear to be working.
▶ C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NoProfile -NonInteractive @(Get-Module -ListAvailable hyper-v).Name | Get-Unique
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

Hyper-V is installed and working, you can see a working VM:
C:\WINDOWS\system32> get-vm

Name                       State CPUUsage(%) MemoryAssigned(M) Uptime   Status             Version
----                       ----- ----------- ----------------- ------   ------             -------
Windows 10 test environment Off   0           0                 00:00:00 Operating normally 9.0

The command fails with the same error using the stable version of Kubernetes too.

</details>

**Comment by tstromberg** [comment] 2020-05-26 16:21
Thank you for sharing the output of the underlying command. It appears to be showing an empty list for the list of modules, which is strange.

This issue appears to be a duplicate of #2954, do you mind if we move the conversation there?

Ths way we can centralize the content relating to the issue. If you feel that this issue is not in fact a duplicate, please re-open it using `/reopen`. If you have additional information to share, please add it to the new issue.

Thank you for reporting this!

**Closed by tstromberg** 2020-05-26 16:21 UTC

**Comment by tstromberg** [comment] 2020-05-26 16:22
Just curious for context - was "minikube start" executed from a shell that is running as Administrator or a regular user?

**Comment by marcusm** [comment] 2020-05-27 01:25
I n this instance it was from an administrator account. I have tried it with both and get the exact same result.
